from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    CircleSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008726",
        title="원에서 지름을 나타내는 선분 찾기",
        canvas=Canvas(width=880.0, height=420.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.inserted.line.1"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle.outer",
                    "slot.line.gj",
                    "slot.line.nd",
                    "slot.line.dm",
                    "slot.line.ro",
                    "slot.line.mo",
                    "slot.pt.center",
                    "slot.lb.g",
                    "slot.lb.n",
                    "slot.lb.d",
                    "slot.lb.r",
                    "slot.lb.m",
                    "slot.lb.o",
                ),
            ),
            Region(
                id="region.options",
                role="choices",
                flow="absolute",
                slot_ids=(
                    "slot.opt1",
                    "slot.opt2",
                    "slot.opt3",
                    "slot.opt4",
                    "slot.opt5",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="원에서 원의 지름을 나타내는 선분은 어느 것일까요?",
                style_role="question",
                x=12,
                y=30,
                font_size=28,
                fill="#111111",
            ),
            CircleSlot(
                id="slot.circle.outer",
                prompt="",
                cx=345,
                cy=181,
                r=110,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.gj",
                prompt="",
                x1=235,
                y1=195,
                x2=415,
                y2=265,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.nd",
                prompt="",
                x1=250,
                y1=130,
                x2=440,
                y2=230,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.dm",
                prompt="",
                x1=345,
                y1=180,
                x2=405,
                y2=90,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.ro",
                prompt="",
                x1=500,
                y1=155,
                x2=500,
                y2=155,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.mo",
                prompt="",
                x1=500,
                y1=155,
                x2=500,
                y2=155,
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.center",
                prompt="",
                cx=345,
                cy=180,
                r=4,
                fill="#d81b60",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.lb.g",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=215,
                y=130,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.n",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=205,
                y=205,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.d",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=420,
                y=285,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.r",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=455,
                y=255,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.m",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=410,
                y=85,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.o",
                prompt="",
                text="ㅇ",
                style_role="label",
                x=315,
                y=200,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.opt1",
                prompt="",
                text="① 선분 ㄱㄹ",
                style_role="choice",
                x=20,
                y=352,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.opt2",
                prompt="",
                text="② 선분 ㄴㄷ",
                style_role="choice",
                x=213,
                y=352,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.opt3",
                prompt="",
                text="③ 선분 ㄷㅁ",
                style_role="choice",
                x=407,
                y=353,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.opt4",
                prompt="",
                text="④ 선분 ㄹㅇ",
                style_role="choice",
                x=20,
                y=396,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.opt5",
                prompt="",
                text="⑤ 선분 ㅁㅇ",
                style_role="choice",
                x=213,
                y=396,
                font_size=28,
                fill="#111111",
            ),
            LineSlot(
                id="slot.inserted.line.1",
                prompt="",
                x1=415,
                y1=265,
                x2=405,
                y2=90,
                stroke="#111827",
                stroke_width=1.5,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008726",
    "problem_type": "geometry_circle_diameter_choice",
    "metadata": {
        "language": "ko",
        "question": "원에서 지름을 나타내는 선분을 찾는 객관식 문제",
        "instruction": "그림을 보고 지름인 선분을 고른다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center", "type": "center_point"},
            {"id": "obj.segment_gr", "type": "segment", "label": "ㄱㄹ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle", "obj.center", "obj.segment_gr"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.diameter_definition"],
            },
            "plan": {
                "method": "definition_matching",
                "description": "원의 중심을 지나면서 원 위의 두 점을 잇는 선분을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_center_passing_segment",
                    "match_endpoints_on_circle",
                    "select_correct_choice",
                ]
            },
            "review": {"check_methods": ["definition_check", "choice_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "multiple_choice", "description": "원의 지름을 나타내는 선분"},
        "value": 1,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008726",
    "problem_type": "geometry_circle_diameter_choice",
    "inputs": {
        "total_ticks": 1,
        "target_label": "지름",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": {"type": "circle"}},
        {"ref": "obj.center", "value": {"type": "center_point"}},
        {"ref": "obj.segment_gr", "value": {"label": "ㄱㄹ"}},
    ],
    "target": {"ref": "answer.target", "type": "multiple_choice"},
    "method": "definition_matching",
    "plan": [
        "원의 중심을 지나고 원 위의 두 점을 잇는 선분을 찾는다.",
        "그 선분에 대응하는 보기를 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "원의 중심을 지나는 선분 확인", "value": "ㄱㄹ"},
        {"id": "step.2", "expr": "정답 보기 선택", "value": 1},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "ㄱㄹ은 원의 중심을 지나고 원 위의 두 점을 잇는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "선택한 보기가 ①인가",
            "expected": 1,
            "actual": 1,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "multiple_choice", "description": "원의 지름을 나타내는 선분"},
        "value": 1,
        "unit": "",
    },
}
