from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008716",
        title="도형에 대한 설명으로 틀린 것은 어느 것일까요?",
        canvas=Canvas(width=720, height=490, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.header.text",),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle.outer",
                    "slot.line.chord",
                    "slot.line.diameter",
                    "slot.line.radius",
                    "slot.pt.center",
                    "slot.lb.o",
                    "slot.lb.ga",
                    "slot.lb.na",
                    "slot.lb.da",
                    "slot.lb.ra",
                ),
            ),
            Region(
                id="region.choices",
                role="choice",
                flow="absolute",
                slot_ids=(
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                    "slot.choice.5",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.header.text",
                prompt="",
                text="도형에 대한 설명으로 틀린 것은 어느 것일까요?",
                style_role="question",
                x=35,
                y=35,
                font_size=26,
            ),
            # Diagram: Circle cx=520, cy=130, r=75
            CircleSlot(
                id="slot.circle.outer",
                prompt="",
                cx=520,
                cy=130,
                r=75,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            # Line ㄱㄹ (Chord): (501, 58) to (593, 114)
            LineSlot(
                id="slot.line.chord",
                prompt="",
                x1=501,
                y1=58,
                x2=593,
                y2=114,
                stroke="#111111",
                stroke_width=2,
            ),
            # Line ㄴㄹ (Diameter): (447, 146) through (520, 130) to (593, 114)
            LineSlot(
                id="slot.line.diameter",
                prompt="",
                x1=447,
                y1=146,
                x2=593,
                y2=114,
                stroke="#111111",
                stroke_width=2,
            ),
            # Line ㄷㅇ (Radius): (520, 130) to (546, 200)
            LineSlot(
                id="slot.line.radius",
                prompt="",
                x1=520,
                y1=130,
                x2=546,
                y2=200,
                stroke="#111111",
                stroke_width=2,
            ),
            # Center point ㅇ
            CircleSlot(
                id="slot.pt.center",
                prompt="",
                cx=520,
                cy=130,
                r=4,
                fill="#ec407a",
            ),
            TextSlot(
                id="slot.lb.o",
                prompt="",
                text="ㅇ",
                style_role="label",
                x=515,
                y=120,
                font_size=18,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.ga",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=495,
                y=48,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.na",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=428,
                y=152,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.da",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=545,
                y=218,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.ra",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=602,
                y=118,
                font_size=22,
                fill="#111111",
            ),
            # 5 Multiple Choice statements
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 원의 중심은 점 ㅇ입니다.",
                style_role="choice",
                x=40,
                y=255,
                font_size=24,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 원의 지름은 선분 ㄴㄹ입니다.",
                style_role="choice",
                x=40,
                y=300,
                font_size=24,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 선분 ㄴㅇ은 원의 반지름입니다.",
                style_role="choice",
                x=40,
                y=345,
                font_size=24,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 길이가 가장 긴 선분은 선분 ㄱㄹ입니다.",
                style_role="choice",
                x=40,
                y=390,
                font_size=24,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.5",
                prompt="",
                text="⑤ 선분 ㄷㅇ과 선분 ㄹㅇ의 길이는 같습니다.",
                style_role="choice",
                x=40,
                y=435,
                font_size=24,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008716",
    "problem_type": "multiple_choice",
    "metadata": {
        "language": "ko",
        "question": "도형에 대한 설명으로 틀린 것은 어느 것일까요?",
        "instruction": "보기 중 옳지 않은 설명을 고른다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center", "type": "point", "symbol": "ㅇ"},
            {"id": "obj.point_g", "type": "point", "symbol": "ㄱ"},
            {"id": "obj.point_n", "type": "point", "symbol": "ㄴ"},
            {"id": "obj.point_l", "type": "point", "symbol": "ㄹ"},
            {"id": "obj.point_d", "type": "point", "symbol": "ㄷ"},
            {"id": "obj.segment_nl", "type": "segment", "endpoints": ["obj.point_n", "obj.point_l"]},
            {"id": "obj.segment_gl", "type": "segment", "endpoints": ["obj.point_g", "obj.point_l"]},
            {"id": "obj.segment_no", "type": "segment", "endpoints": ["obj.point_n", "obj.center"]},
            {"id": "obj.segment_do", "type": "segment", "endpoints": ["obj.point_d", "obj.center"]},
            {"id": "obj.segment_lo", "type": "segment", "endpoints": ["obj.point_l", "obj.center"]},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.circle",
                    "obj.center",
                    "obj.segment_nl",
                    "obj.segment_gl",
                    "obj.segment_no",
                    "obj.segment_do",
                    "obj.segment_lo",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.incorrect_statement"],
            },
            "plan": {
                "method": "property_verification",
                "description": "중심, 지름, 반지름의 성질을 검증하여 옳지 않은 설명을 찾는다.",
            },
            "execute": {
                "expected_operations": ["verify_choice_statements"]
            },
            "review": {"check_methods": ["longest_segment_is_diameter"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": ["1", "2", "3", "4", "5"],
        "answer_key": ["4"],
        "target": {"type": "multiple_choice", "description": "도형에 대한 설명으로 틀린 것"},
        "value": "4",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008716",
    "problem_type": "multiple_choice",
    "inputs": {
        "total_ticks": 5,
        "target_label": "도형에 대한 설명으로 틀린 것",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.center", "value": {"symbol": "ㅇ"}},
        {"ref": "obj.segment_nl", "value": {"type": "diameter"}},
        {"ref": "obj.segment_no", "value": {"type": "radius"}},
        {"ref": "obj.segment_do", "value": {"type": "radius"}},
        {"ref": "obj.segment_lo", "value": {"type": "radius"}},
    ],
    "target": {"ref": "answer.target", "type": "multiple_choice"},
    "method": "property_verification",
    "plan": [
        "원의 중심, 지름, 반지름의 성질을 확인한다.",
        "보기 문장 중 원의 성질과 맞지 않는 것을 찾는다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "원의 중심은 점 ㅇ (참)", "value": True},
        {"id": "step.2", "expr": "선분 ㄴㄹ은 지름 (참)", "value": True},
        {"id": "step.3", "expr": "선분 ㄴㅇ은 반지름 (참)", "value": True},
        {"id": "step.4", "expr": "가장 긴 선분은 선분 ㄴㄹ(지름)이므로 선분 ㄱㄹ은 거짓", "value": "4"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "가장 긴 선분은 지름인가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {"id": "check.2", "expr": "틀린 보기는 4번인가", "expected": "4", "actual": "4", "pass": True},
    ],
    "answer": {
        "blanks": [],
        "choices": ["1", "2", "3", "4", "5"],
        "answer_key": ["4"],
        "target": {"type": "multiple_choice", "description": "도형에 대한 설명으로 틀린 것"},
        "value": "4",
        "unit": "",
    },
}


