from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextBoxSlot,
RectSlot)


PROBLEM_ID = "P3_1_01_00040_02135"
PROBLEM_TITLE = "Додавання трицифрових чисел із перенесенням"


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id=PROBLEM_ID,
        title=PROBLEM_TITLE,
        canvas=Canvas(
            width=900,
            height=320,
            coordinate_mode="logical",
        ),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.instruction",
                    "slot.first_number",
                    "slot.plus_sign",
                    "slot.second_number",
                    "slot.horizontal_line",
                    'konva_1785065387111_rect_91826', 'konva_1785065387111_paste_117760_0', 'konva_1785065387111_paste_146425_0', 'konva_1785065387111_paste_146425_1', 'konva_1785065387111_paste_166216_0'),
            ),
        ),
        slots=(TextBoxSlot(
                id="slot.instruction",
                x = 10.8, y = 22.4, width = 288, height=42,
                text="Впишіть у клітинки відповідні числа.",
                font_size=24,
                font_family='"Noto Sans", sans-serif',
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.first_number",
                x = 130, y = 112.4, width = 64.4, height=42,
                text="6 6 4",
                font_size=28,
                font_family='"Noto Sans", sans-serif',
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.plus_sign",
                x = 90.4, y = 143.2, width=32,
                height=42,
                text="+",
                font_size=28,
                font_family='"Noto Sans", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.second_number",
                x = 130.4, y = 143.2, width = 61.2, height=42,
                text="2 5 7",
                font_size=28,
                font_family='"Noto Sans", sans-serif',
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.horizontal_line",
                x = 84.8, y = 168.4, width = 121.2, height = 19.2, text="────────",
                font_size=24,
                font_family='"Noto Sans", sans-serif',
                fill="#111111",
                align="left",
                valign="middle",
            ),
            RectSlot(id = 'konva_1785065387111_rect_91826', prompt = '', x = 146.4, y = 88.6, width = 19.147, height = 19.699, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2), RectSlot(id = 'konva_1785065387111_paste_117760_0', prompt = '', x = 123.2, y = 88.8, width = 19.147, height = 19.699, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2), RectSlot(id = 'konva_1785065387111_paste_146425_0', prompt = '', x = 148.8, y = 188.6, width = 19.147, height = 19.699, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2), RectSlot(id = 'konva_1785065387111_paste_146425_1', prompt = '', x = 125.6, y = 188.8, width = 19.147, height = 19.699, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2), RectSlot(id = 'konva_1785065387111_paste_166216_0', prompt = '', x = 171.2, y = 188.6, width = 19.147, height = 19.699, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2)),
    )


PROBLEM_TEMPLATE = build_problem_template()


ANSWER = {'value': [1, 1, 9, 2, 1],
 'unit': '',
 'values': [1, 1, 9, 2, 1],
 'blanks': [{'id': 'konva_1785065387111_rect_91826',
             'slot_id': 'konva_1785065387111_rect_91826',
             'expected': 1},
            {'id': 'konva_1785065387111_paste_117760_0',
             'slot_id': 'konva_1785065387111_paste_117760_0',
             'expected': 1},
            {'id': 'konva_1785065387111_paste_146425_0',
             'slot_id': 'konva_1785065387111_paste_146425_0',
             'expected': 9},
            {'id': 'konva_1785065387111_paste_146425_1',
             'slot_id': 'konva_1785065387111_paste_146425_1',
             'expected': 2},
            {'id': 'konva_1785065387111_paste_166216_0',
             'slot_id': 'konva_1785065387111_paste_166216_0',
             'expected': 1}],
 'answer_key': [{'slot_id': 'konva_1785065387111_rect_91826', 'value': 1},
                {'slot_id': 'konva_1785065387111_paste_117760_0', 'value': 1},
                {'slot_id': 'konva_1785065387111_paste_146425_0', 'value': 9},
                {'slot_id': 'konva_1785065387111_paste_146425_1', 'value': 2},
                {'slot_id': 'konva_1785065387111_paste_166216_0', 'value': 1}],
 'expression': '664 + 257 = 921'}

SEMANTIC = {
    "problem_id": PROBLEM_ID,
    "problem_type": "multi_blank_vertical_addition",
    "metadata": {
        "grade": 3,
        "semester": 1,
        "subject": "Математика",
        "topic": "Додавання трицифрових чисел із перенесенням",
        "language": "uk-UA",
    },
    "domain": {
        "objects": [
            {
                "id": "number.addend_1",
                "type": "number",
                "label": "Перше число",
                "value": 664,
            },
            {
                "id": "number.addend_2",
                "type": "number",
                "label": "Друге число",
                "value": 257,
            },
            {
                "id": "carry.ones_to_tens",
                "type": "carry",
                "label": "Число, перенесене з розряду одиниць у розряд десятків",
                "value": 1,
            },
            {
                "id": "carry.tens_to_hundreds",
                "type": "carry",
                "label": "Число, перенесене з розряду десятків у розряд сотень",
                "value": 1,
            },
            {
                "id": "digit.answer_hundreds",
                "type": "place_value_digit",
                "label": "Цифра сотень у відповіді",
                "place": "hundreds",
                "value": 9,
            },
            {
                "id": "digit.answer_tens",
                "type": "place_value_digit",
                "label": "Цифра десятків у відповіді",
                "place": "tens",
                "value": 2,
            },
            {
                "id": "digit.answer_ones",
                "type": "place_value_digit",
                "label": "Цифра одиниць у відповіді",
                "place": "ones",
                "value": 1,
            },
            {
                "id": "number.sum",
                "type": "number",
                "label": "Сума чисел 664 і 257",
                "value": 921,
            },
        ],
        "relations": [
            {
                "id": "relation.sum_of_addends",
                "type": "sum_of",
                "subject": "number.sum",
                "objects": [
                    "number.addend_1",
                    "number.addend_2",
                ],
            },
            {
                "id": "relation.ones_carry",
                "type": "carry_to",
                "subject": "carry.ones_to_tens",
                "from_place": "ones",
                "to_place": "tens",
            },
            {
                "id": "relation.tens_carry",
                "type": "carry_to",
                "subject": "carry.tens_to_hundreds",
                "from_place": "tens",
                "to_place": "hundreds",
            },
        ],
    },
    "answer": ANSWER,
}

SEMANTIC_OVERRIDE = SEMANTIC


SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'P3_1_01_00040_02135',
 'problem_type': 'multi_blank_vertical_addition',
 'inputs': {'target_label': 'перенесені числа та цифри кожного розряду результату додавання',
            'unit': '',
            'answer_type': 'digit_list',
            'quantities': {'first_addend': 664, 'second_addend': 257},
            'place_values': {'first_addend': {'hundreds': 6, 'tens': 6, 'ones': 4},
                             'second_addend': {'hundreds': 2, 'tens': 5, 'ones': 7}},
            'conditions': ['Обчислюємо послідовно, починаючи з розряду одиниць.',
                           'Якщо сума цифр у розряді дорівнює 10 або більше, переносимо 1 до наступного вищого розряду.',
                           'У кожну клітинку вписуємо перенесене число та відповідну цифру результату.']},
 'given': [{'ref': 'number.addend_1', 'value': 664}, {'ref': 'number.addend_2', 'value': 257}],
 'target': {'ref': 'answer.vertical_addition_blanks', 'type': 'digit_list'},
 'method': 'Додаємо, починаючи з розряду одиниць, і враховуємо перенесене число під час обчислення наступного розряду.',
 'plan': ['Додати цифри одиниць 4 і 7.',
          'Позначити в розряді десятків число, перенесене з розряду одиниць.',
          'До цифр десятків 6 і 5 додати перенесену 1.',
          'Позначити в розряді сотень число, перенесене з розряду десятків.',
          'До цифр сотень 6 і 2 додати перенесену 1.',
          'Записати цифри сотень, десятків і одиниць результату обчислення.'],
 'steps': [{'id': 'step.add_ones',
            'expr': '4 + 7',
            'value': 11,
            'explanation': 'У розряді одиниць додаємо 4 і 7 та отримуємо 11.'},
           {'id': 'step.write_ones_and_carry',
            'expr': '11 = 1 × 10 + 1',
            'value': {'carry': 1, 'digit': 1},
            'explanation': 'У розряді одиниць записуємо 1, а 1 переносимо до розряду десятків.'},
           {'id': 'step.add_tens',
            'expr': '6 + 5 + 1',
            'value': 12,
            'explanation': 'У розряді десятків до 6 і 5 додаємо перенесену 1 та отримуємо 12.'},
           {'id': 'step.write_tens_and_carry',
            'expr': '12 = 1 × 10 + 2',
            'value': {'carry': 1, 'digit': 2},
            'explanation': 'У розряді десятків записуємо 2, а 1 переносимо до розряду сотень.'},
           {'id': 'step.add_hundreds',
            'expr': '6 + 2 + 1',
            'value': 9,
            'explanation': 'У розряді сотень до 6 і 2 додаємо перенесену 1 та отримуємо 9.'},
           {'id': 'step.compose_answer',
            'expr': '900 + 20 + 1',
            'value': 921,
            'explanation': 'Записавши послідовно цифри кожного розряду, отримуємо 921.'}],
 'checks': [{'id': 'check.ones_place', 'expr': '4 + 7', 'expected': 11, 'actual': 11, 'pass': True},
            {'id': 'check.tens_place',
             'expr': '6 + 5 + 1',
             'expected': 12,
             'actual': 12,
             'pass': True},
            {'id': 'check.hundreds_place',
             'expr': '6 + 2 + 1',
             'expected': 9,
             'actual': 9,
             'pass': True},
            {'id': 'check.total',
             'expr': '664 + 257',
             'expected': 921,
             'actual': 921,
             'pass': True},
            {'id': 'check.inverse_operation',
             'expr': '921 - 257',
             'expected': 664,
             'actual': 664,
             'pass': True}],
 'answer': ANSWER,
 'understanding': {'summary': 'За поданими даними потрібно знайти перенесені числа та цифри кожного розряду результату додавання.',
                   'facts': [{'ref': 'number.addend_1',
                              'label': 'перший доданок',
                              'value': 664,
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'number.addend_2',
                              'label': 'другий доданок',
                              'value': 257,
                              'unit': '',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.vertical_addition_blanks',
                                 'label': 'перенесені числа та цифри кожного розряду результату додавання',
                                 'unit': '',
                                 'source': 'unknown'}],
                   'relation': {'type': 'Додавання з перенесенням, починаючи з розряду одиниць',
                                'statement': 'Додаємо цифри одиниць 4 і 7.',
                                'symbolic': '4 + 7',
                                'uses': ['number.addend_1', 'number.addend_2'],
                                'result': 'answer.vertical_addition_blanks'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'Що потрібно знайти?',
                                             'choices': ['перший доданок',
                                                         'другий доданок',
                                                         'перенесені числа та цифри кожного розряду результату додавання'],
                                             'answer_index': 2}]}}

SEMANTIC_ANSWER = SOLVABLE["answer"]
