from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1537,
        height=595,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=(
                'slot.instruction',
                'slot.base_line',
                'slot.tick_left',
                'slot.tick_mid',
                'slot.tick_mid2',
                'slot.tick_right',
                'slot.guide_left_mid_top',
                'slot.guide_mid_right_top',
                'slot.guide_left_mid2_bottom',
                'slot.guide_mid_mid2_bottom',
                'slot.guide_mid2_right_bottom',
                'slot.label_821',
                'slot.label_448',
                'slot.label_236',
                'slot.circle_a',
                'slot.text_a',
                'slot.circle_b',
                'slot.text_b',
            ),
        ),
    )
    slots = (
        TextSlot(
            id='slot.instruction',
            prompt='',
            text='㉠과 ㉡의 길이는 각각 몇 cm입니까?',
            style_role='body',
            x=24.0,
            y=105.0,
            font_size=84,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#2B252A',
            semantic_role='instruction',
        ),
        LineSlot(
            id='slot.base_line',
            prompt='',
            x1=70.0,
            y1=332.0,
            x2=1481.0,
            y2=332.0,
            stroke='#2E2A2D',
            stroke_width=6.0,
            semantic_role='number_line',
        ),
        LineSlot(
            id='slot.tick_left',
            prompt='',
            x1=70.0,
            y1=298.0,
            x2=70.0,
            y2=368.0,
            stroke='#2E2A2D',
            stroke_width=4.0,
            semantic_role='point_tick',
        ),
        LineSlot(
            id='slot.tick_mid',
            prompt='',
            x1=982.0,
            y1=298.0,
            x2=982.0,
            y2=368.0,
            stroke='#2E2A2D',
            stroke_width=4.0,
            semantic_role='point_tick',
        ),
        LineSlot(
            id='slot.tick_mid2',
            prompt='',
            x1=1220.0,
            y1=298.0,
            x2=1220.0,
            y2=368.0,
            stroke='#2E2A2D',
            stroke_width=4.0,
            semantic_role='point_tick',
        ),
        LineSlot(
            id='slot.tick_right',
            prompt='',
            x1=1481.0,
            y1=298.0,
            x2=1481.0,
            y2=368.0,
            stroke='#2E2A2D',
            stroke_width=4.0,
            semantic_role='point_tick',
        ),
        PathSlot(
            id='slot.guide_left_mid_top',
            prompt='',
            d='M 70 332 Q 520 170 982 332',
            stroke='#2E2A2D',
            stroke_width=3.0,
            stroke_dasharray='16 9',
            fill='none',
            semantic_role='measurement_guide',
        ),
        PathSlot(
            id='slot.guide_mid_right_top',
            prompt='',
            d='M 982 332 Q 1230 150 1481 332',
            stroke='#2E2A2D',
            stroke_width=3.0,
            stroke_dasharray='16 9',
            fill='none',
            semantic_role='measurement_guide',
        ),
        PathSlot(
            id='slot.guide_left_mid2_bottom',
            prompt='',
            d='M 70 332 Q 640 760 1220 332',
            stroke='#2E2A2D',
            stroke_width=3.0,
            stroke_dasharray='16 9',
            fill='none',
            semantic_role='measurement_guide',
        ),
        PathSlot(
            id='slot.guide_mid_mid2_bottom',
            prompt='',
            d='M 982 332 Q 1100 440 1220 332',
            stroke='#2E2A2D',
            stroke_width=3.0,
            stroke_dasharray='16 9',
            fill='none',
            semantic_role='measurement_guide',
        ),
        PathSlot(
            id='slot.guide_mid2_right_bottom',
            prompt='',
            d='M 1220 332 Q 1350 490 1481 332',
            stroke='#2E2A2D',
            stroke_width=3.0,
            stroke_dasharray='16 9',
            fill='none',
            semantic_role='measurement_guide',
        ),
        TextSlot(
            id='slot.label_821',
            prompt='',
            text='821 cm',
            style_role='body',
            x=530.0,
            y=268.0,
            font_size=72,
            font_family='Cambria',
            anchor='middle',
            fill='#2B252A',
            semantic_role='distance_label',
        ),
        TextSlot(
            id='slot.label_448',
            prompt='',
            text='448 cm',
            style_role='body',
            x=1210.0,
            y=272.0,
            font_size=72,
            font_family='Cambria',
            anchor='middle',
            fill='#2B252A',
            semantic_role='distance_label',
        ),
        TextSlot(
            id='slot.label_236',
            prompt='',
            text='236 cm',
            style_role='body',
            x=1325.0,
            y=424.0,
            font_size=72,
            font_family='Cambria',
            anchor='middle',
            fill='#2B252A',
            semantic_role='distance_label',
        ),
        CircleSlot(
            id='slot.circle_a',
            prompt='',
            cx=660.0,
            cy=545.0,
            r=34.0,
            stroke='#2E2A2D',
            stroke_width=3.0,
            fill='none',
            semantic_role='point_label',
        ),
        TextSlot(
            id='slot.text_a',
            prompt='',
            text='ㄱ',
            style_role='body',
            x=660.0,
            y=556.0,
            font_size=58,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#2B252A',
            semantic_role='point_name',
        ),
        CircleSlot(
            id='slot.circle_b',
            prompt='',
            cx=1100.0,
            cy=382.0,
            r=34.0,
            stroke='#2E2A2D',
            stroke_width=3.0,
            fill='none',
            semantic_role='point_label',
        ),
        TextSlot(
            id='slot.text_b',
            prompt='',
            text='ㄴ',
            style_role='body',
            x=1100.0,
            y=393.0,
            font_size=58,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#2B252A',
            semantic_role='point_name',
        ),
    )
    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id='0010_선분의 길이 계산하기',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0010_선분의 길이 계산하기',
 'problem_type': 'line_segment_distance_system',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '㉠과 ㉡의 길이는 각각 몇 cm입니까?',
              'question': '주어진 여러 선분의 길이를 이용하여 미지의 선분 ㄱ, ㄴ의 길이를 구하는 문제',
              'required_layout_ids': ['slot.base_line',
                                      'slot.tick_left',
                                      'slot.tick_mid',
                                      'slot.tick_mid2',
                                      'slot.tick_right',
                                      'slot.guide_left_mid_top',
                                      'slot.guide_mid_right_top',
                                      'slot.guide_left_mid2_bottom',
                                      'slot.guide_mid_mid2_bottom',
                                      'slot.guide_mid2_right_bottom',
                                      'slot.circle_a',
                                      'slot.circle_b'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.p0', 'type': 'point'},
                        {'id': 'obj.p1', 'type': 'point'},
                        {'id': 'obj.p2', 'type': 'point'},
                        {'id': 'obj.p3', 'type': 'point'},
                        {'id': 'obj.dist_p0_p1', 'value': 821, 'unit': 'cm'},
                        {'id': 'obj.dist_p1_p3', 'value': 448, 'unit': 'cm'},
                        {'id': 'obj.dist_p2_p3', 'value': 236, 'unit': 'cm'}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'segment_subtraction_addition',
                                         'description': 'ㄴ은 (P1~P3)-(P2~P3)로 구하고, ㄱ은 (P0~P1)+ㄴ으로 '
                                                        '구한다.'}}},
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'confidence': 1.0,
            'value': 0,
            'unit': 'cm',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0010_선분의 길이 계산하기',
 'problem_type': 'line_segment_distance_system',
 'inputs': {'total_ticks': 1,
            'target_label': '',
            'target_ticks': 1,
            'target_count': 1,
            'unit': 'cm'},
 'given': [{'ref': 'obj.dist_p0_p1', 'value': 821},
           {'ref': 'obj.dist_p1_p3', 'value': 448},
           {'ref': 'obj.dist_p2_p3', 'value': 236}],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': {'ㄱ': 1033, 'ㄴ': 212},
             'actual': {'ㄱ': 1033, 'ㄴ': 212},
             'pass': True}],
 'answer': {'value': 0, 'unit': 'cm', 'derived_from': 'step.1'}}
