from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2404",
        title="∠CAM의 크기를 구하시오.",
        canvas=Canvas(width=960, height=760, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.problem",),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle.main",
                    "slot.seg.ca",
                    "slot.seg.ta",
                    "slot.seg.tn",
                    "slot.seg.m_ca",
                    "slot.seg.m_tn",
                    "slot.ra.ca.a",
                    "slot.ra.ca.b",
                    "slot.ra.ca.c",
                    "slot.ra.tn.a",
                    "slot.ra.tn.b",
                    "slot.ra.tn.c",
                    "slot.eq.1",
                    "slot.eq.2",
                    "slot.pt.c",
                    "slot.pt.a",
                    "slot.pt.n",
                    "slot.pt.t",
                    "slot.pt.m",
                    "slot.lb.c",
                    "slot.lb.a",
                    "slot.lb.n",
                    "slot.lb.t",
                    "slot.lb.m",
                    "slot.angle.28",
                ),
            ),
            Region(
                id="region.choices",
                role="choices",
                flow="absolute",
                slot_ids=(
                    "slot.choice.1a",
                    "slot.choice.1v",
                    "slot.choice.2a",
                    "slot.choice.2v",
                    "slot.choice.3a",
                    "slot.choice.3v",
                    "slot.choice.4a",
                    "slot.choice.4v",
                ),
            ),
            Region(
                id="region.overlay",
                role="overlay",
                flow="absolute",
                slot_ids=("slot.answer_overlay",),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.problem",
                prompt="",
                text="∠CAM의 크기를 구하시오.",
                style_role="question",
                x=40.0,
                y=72.0,
                font_size=48,
            ),
            CircleSlot(
                id="slot.circle.main",
                prompt="",
                cx=430.0,
                cy=390.0,
                r=250.0,
                stroke="#0B72D9",
                stroke_width=6,
                fill="none",
            ),
            LineSlot(
                id="slot.seg.ca",
                prompt="",
                x1=189.7,
                y1=321.1,
                x2=621.5,
                y2=229.3,
                stroke="#222222",
                stroke_width=5,
            ),
            LineSlot(
                id="slot.seg.ta",
                prompt="",
                x1=238.5,
                y1=550.7,
                x2=621.5,
                y2=229.3,
                stroke="#222222",
                stroke_width=5,
            ),
            LineSlot(
                id="slot.seg.tn",
                prompt="",
                x1=238.5,
                y1=550.7,
                x2=670.3,
                y2=458.9,
                stroke="#222222",
                stroke_width=5,
            ),
            LineSlot(
                id="slot.seg.m_ca",
                prompt="",
                x1=430.0,
                y1=390.0,
                x2=405.6,
                y2=275.2,
                stroke="#222222",
                stroke_width=5,
            ),
            LineSlot(
                id="slot.seg.m_tn",
                prompt="",
                x1=430.0,
                y1=390.0,
                x2=454.4,
                y2=504.8,
                stroke="#222222",
                stroke_width=5,
            ),
            LineSlot(
                id="slot.ra.ca.a",
                prompt="",
                x1=405.6,
                y1=275.2,
                x2=421.2,
                y2=271.9,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.ra.ca.b",
                prompt="",
                x1=421.2,
                y1=271.9,
                x2=424.6,
                y2=287.5,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.ra.ca.c",
                prompt="",
                x1=424.6,
                y1=287.5,
                x2=408.9,
                y2=290.8,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.ra.tn.a",
                prompt="",
                x1=454.4,
                y1=504.8,
                x2=470.1,
                y2=501.5,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.ra.tn.b",
                prompt="",
                x1=470.1,
                y1=501.5,
                x2=466.7,
                y2=485.8,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.ra.tn.c",
                prompt="",
                x1=466.7,
                y1=485.8,
                x2=451.1,
                y2=489.2,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.eq.1",
                prompt="",
                x1=410.8,
                y1=339.6,
                x2=424.8,
                y2=325.6,
                stroke="#E91E63",
                stroke_width=3,
            ),
            LineSlot(
                id="slot.eq.2",
                prompt="",
                x1=435.2,
                y1=454.4,
                x2=449.2,
                y2=440.4,
                stroke="#E91E63",
                stroke_width=3,
            ),
            CircleSlot(
                id="slot.pt.c",
                prompt="",
                cx=189.7,
                cy=321.1,
                r=4.0,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.pt.a",
                prompt="",
                cx=621.5,
                cy=229.3,
                r=4.0,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.pt.n",
                prompt="",
                cx=670.3,
                cy=458.9,
                r=4.0,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.pt.t",
                prompt="",
                cx=238.5,
                cy=550.7,
                r=4.0,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.pt.m", prompt="", cx=430.0, cy=390.0, r=4.0, fill="#222222"
            ),
            TextSlot(
                id="slot.lb.c",
                prompt="",
                text="C",
                style_role="label",
                x=159.7,
                y=335.1,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.a",
                prompt="",
                text="A",
                style_role="label",
                x=631.5,
                y=237.3,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.n",
                prompt="",
                text="N",
                style_role="label",
                x=678.3,
                y=470.9,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.t",
                prompt="",
                text="T",
                style_role="label",
                x=224.5,
                y=586.7,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.m",
                prompt="",
                text="M",
                style_role="label",
                x=410.0,
                y=378.0,
                font_size=48,
            ),
            TextSlot(
                id="slot.angle.28",
                prompt="",
                text="28°",
                style_role="label",
                x=312.5,
                y=602.7,
                font_size=48,
            ),
            TextSlot(
                id="slot.choice.1a",
                prompt="",
                text="1. 14",
                style_role="choice",
                x=770.0,
                y=320.0,
                font_size=48,
            ),
            TextSlot(
                id="slot.choice.2a",
                prompt="",
                text="2. 28",
                style_role="choice",
                x=770.0,
                y=380.0,
                font_size=48,
            ),
            TextSlot(
                id="slot.choice.3a",
                prompt="",
                text="3. 36",
                style_role="choice",
                x=770.0,
                y=440.0,
                font_size=48,
            ),
            TextSlot(
                id="slot.choice.4a",
                prompt="",
                text="4. 90",
                style_role="choice",
                x=770.0,
                y=500.0,
                font_size=48,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '2404',
 'problem_type': 'geometry_angle',
 'metadata': {'title': '∠CAM의 크기를 구하시오.',
              'tags': [],
              'question': '∠CAM의 크기를 구하시오.',
              'required_layout_ids': ['slot.circle.main',
                                      'slot.seg.ca',
                                      'slot.seg.ta',
                                      'slot.seg.tn',
                                      'slot.seg.m_ca',
                                      'slot.seg.m_tn',
                                      'slot.ra.ca.a',
                                      'slot.ra.ca.b',
                                      'slot.ra.ca.c',
                                      'slot.ra.tn.a',
                                      'slot.ra.tn.b',
                                      'slot.ra.tn.c',
                                      'slot.eq.1',
                                      'slot.eq.2',
                                      'slot.pt.c',
                                      'slot.pt.a',
                                      'slot.pt.n',
                                      'slot.pt.t',
                                      'slot.pt.m'],
              'extraction_confidence': 1.0,
              'language': 'ko',
              'instruction': '보기에서 알맞은 값을 고르시오.'},
 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'},
                        {'id': 'obj.point.c', 'type': 'point', 'label': 'C'},
                        {'id': 'obj.point.a', 'type': 'point', 'label': 'A'},
                        {'id': 'obj.point.n', 'type': 'point', 'label': 'N'},
                        {'id': 'obj.point.t', 'type': 'point', 'label': 'T'},
                        {'id': 'obj.point.m', 'type': 'point', 'label': 'M'},
                        {'id': 'obj.angle.cam',
                         'type': 'angle',
                         'vertex': 'obj.point.a',
                         'arms': ['obj.point.c', 'obj.point.m']},
                        {'id': 'obj.angle.mark_28',
                         'type': 'angle_measure',
                         'value': 28,
                         'unit': '도'}],
            'relations': [{'id': 'rel.connect.ca',
                           'type': 'segment',
                           'from_id': 'obj.point.c',
                           'to_id': 'obj.point.a'},
                          {'id': 'rel.connect.ta',
                           'type': 'segment',
                           'from_id': 'obj.point.t',
                           'to_id': 'obj.point.a'},
                          {'id': 'rel.connect.tn',
                           'type': 'segment',
                           'from_id': 'obj.point.t',
                           'to_id': 'obj.point.n'},
                          {'id': 'rel.connect.am',
                           'type': 'segment',
                           'from_id': 'obj.point.a',
                           'to_id': 'obj.point.m'},
                          {'id': 'rel.mark.right_angle_1',
                           'type': 'right_angle_mark',
                           'from_id': 'obj.point.a',
                           'to_id': 'obj.angle.cam'},
                          {'id': 'rel.mark.right_angle_2',
                           'type': 'right_angle_mark',
                           'from_id': 'obj.point.t',
                           'to_id': 'obj.point.n'}],
            'confidence': 1.0,
            'problem_solving': {'understand': {'given_refs': ['obj.angle.mark_28'],
                                               'target_ref': 'answer.target',
                                               'condition_refs': ['rel.connect.ca',
                                                                  'rel.connect.ta',
                                                                  'rel.connect.tn']},
                                'plan': {'method': 'angle_relation_reading',
                                         'description': '도형의 표시와 주어진 각도 표기를 읽어 ∠CAM의 값을 찾는다.'},
                                'execute': {'expected_operations': ['identify_angle_marks',
                                                                    'match_given_measure_to_corresponding_angle']},
                                'review': {'check_methods': ['choice_match_check',
                                                             'label_consistency_check']}}},
 'answer': {'blanks': [],
            'choices': [{'index': 1, 'text': '1. 14', 'value': '14'},
                        {'index': 2, 'text': '2. 28', 'value': '28'},
                        {'index': 3, 'text': '3. 36', 'value': '36'},
                        {'index': 4, 'text': '4. 90', 'value': '90'}],
            'answer_key': [2],
            'confidence': 1.0,
            'target': {'type': 'angle_measure', 'description': '∠CAM의 크기'},
            'value': 28,
            'unit': '도'}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '2404',
 'problem_type': 'geometry_angle',
 'inputs': {'total_ticks': 1,
            'target_label': '∠CAM',
            'target_ticks': 1,
            'target_count': 1,
            'unit': '도'},
 'given': [{'ref': 'obj.angle.mark_28', 'value': 28, 'unit': '도'}],
 'target': {'ref': 'answer.target', 'type': 'angle_measure'},
 'method': 'angle_relation_reading',
 'plan': ['도형의 표시를 읽어 주어진 28°가 어떤 각과 대응하는지 확인한다.', '그에 따라 ∠CAM의 크기를 선택지에서 찾는다.'],
 'steps': [{'id': 'step.1', 'operation': 'read_given_angle', 'expr': '28°', 'value': 28},
           {'id': 'step.2', 'operation': 'match_to_target_angle', 'expr': '∠CAM', 'value': 28}],
 'checks': [{'id': 'check.1',
             'type': 'choice_match_check',
             'expr': '선택지 2번',
             'expected': 28,
             'actual': 28,
             'pass': True}],
 'answer': {'value': 28, 'unit': '도', 'derived_from': 'choice.2'}}
