from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=980,
        height=730,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=(
                'slot.q1',
                'slot.q2',
                'slot.q3',
                'slot.q4',
                'slot.q5',
                'slot.label_g',
                'slot.label_n',
                'slot.label_r',
                'slot.label_d',
            ),
        ),
    )
    slots = (
        RectSlot(
            id='slot.bg',
            prompt='',
            x=0.0,
            y=0.0,
            width=980.0,
            height=730.0,
            stroke='none',
            stroke_width=0.0,
            fill='#F6F6F6',
            semantic_role='background',
        ),
        TextSlot(
            id='slot.q1',
            prompt='',
            text='여러 가지 크기의 정사각형을 겹치지 않게 붙여 다음과',
            style_role='body',
            x=29.0,
            y=60.0,
            font_size=31,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.q2',
            prompt='',
            text='같은 직사각형 모양도형을 만들었습니다. 색칠한 정사각형의',
            style_role='body',
            x=29.0,
            y=104.0,
            font_size=31,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.q3',
            prompt='',
            text='한 변의 길이가 15cm일 때, 직사각형 모양도형의',
            style_role='body',
            x=29.0,
            y=148.0,
            font_size=31,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.q4',
            prompt='',
            text='네 변의 길이의 합은 몇 cm입니까?',
            style_role='body',
            x=29.0,
            y=192.0,
            font_size=31,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.q5',
            prompt='',
            text='(각 가로와 세로 정사각형의 크기는 같습니다.)',
            style_role='body',
            x=29.0,
            y=236.0,
            font_size=31,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.label_g',
            prompt='',
            text='ㄱ',
            style_role='body',
            x=180.59975,
            y=342.61462,
            font_size=42,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.label_n',
            prompt='',
            text='ㄴ',
            style_role='body',
            x=658.59975,
            y=342.61462,
            font_size=42,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='label',
        ),
        LineSlot(
            id='slot.outer_left',
            prompt='',
            x1=202.59975,
            y1=346.61462,
            x2=202.59975,
            y2=626.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        LineSlot(
            id='slot.outer_top',
            prompt='',
            x1=202.59975,
            y1=346.61462,
            x2=650.59975,
            y2=346.61462,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        LineSlot(
            id='slot.v_main',
            prompt='',
            x1=370.59975,
            y1=346.61462,
            x2=370.59975,
            y2=626.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        LineSlot(
            id='slot.outer_right',
            prompt='',
            x1=650.59975,
            y1=346.61462,
            x2=650.59975,
            y2=626.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        LineSlot(
            id='slot.h_main',
            prompt='',
            x1=202.59975,
            y1=514.6146200000001,
            x2=370.59975,
            y2=514.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        LineSlot(
            id='slot.v_small',
            prompt='',
            x1=258.59975,
            y1=514.6146200000001,
            x2=258.59975,
            y2=626.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        RectSlot(
            id='slot.colored_square',
            prompt='',
            x=202.59975,
            y=570.6146200000001,
            width=56.0,
            height=56.0,
            stroke='none',
            stroke_width=0.0,
            fill='#4E78C2',
            semantic_role='highlight',
        ),
        LineSlot(
            id='slot.h_small',
            prompt='',
            x1=202.59975,
            y1=570.6146200000001,
            x2=258.59975,
            y2=570.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        LineSlot(
            id='slot.outer_bottom',
            prompt='',
            x1=202.59975,
            y1=626.6146200000001,
            x2=650.59975,
            y2=626.6146200000001,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='segment',
        ),
        TextSlot(
            id='slot.label_r',
            prompt='',
            text='ㄹ',
            style_role='body',
            x=180.59975,
            y=654.6146200000001,
            font_size=42,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.label_d',
            prompt='',
            text='ㄷ',
            style_role='body',
            x=658.59975,
            y=654.6146200000001,
            font_size=42,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='label',
        ),
    )
    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id='0015_도형의 둘레',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0015_도형의 둘레',
 'problem_type': 'diagram_rectangle_perimeter_from_squares',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '직사각형 모양도형의 네 변의 길이의 합은 몇 cm입니까?',
              'question': '정사각형들을 붙여 만든 큰 직사각형의 둘레를 구하는 문제',
              'required_layout_ids': ['slot.bg',
                                      'slot.outer_left',
                                      'slot.outer_top',
                                      'slot.v_main',
                                      'slot.outer_right',
                                      'slot.h_main',
                                      'slot.v_small',
                                      'slot.colored_square',
                                      'slot.h_small',
                                      'slot.outer_bottom'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.colored_square',
                         'type': 'square',
                         'side_length': 15,
                         'unit': 'cm'},
                        {'id': 'obj.large_rect',
                         'type': 'rectangle',
                         'width_ratio': 8,
                         'height_ratio': 5}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'proportional_measurement',
                                         'description': '색칠된 정사각형의 변을 기준으로 큰 직사각형의 가로(8배), 세로(5배) '
                                                        '길이를 구한다.'}}},
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'confidence': 1.0,
            'value': 390,
            'unit': 'cm',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0015_도형의 둘레',
 'problem_type': 'diagram_rectangle_perimeter_from_squares',
 'inputs': {'total_ticks': 1,
            'target_label': '',
            'target_ticks': 1,
            'target_count': 1,
            'unit': 'cm'},
 'given': [],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': 390,
             'actual': 390,
             'pass': True}],
 'answer': {'value': 390, 'unit': 'cm', 'derived_from': 'step.1'}}
