from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    LineSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2408",
        title="도형 문제",
        canvas=Canvas(width=1400, height=900, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.problem",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                    "slot.diagram.frame",
                    "slot.edge.base",
                    "slot.edge.left",
                    "slot.edge.right",
                    "slot.edge.inner",
                    "slot.pt.X",
                    "slot.pt.Y",
                    "slot.pt.Z",
                    "slot.pt.N",
                    "slot.pt.M",
                    "slot.lb.X",
                    "slot.lb.Y",
                    "slot.lb.Z",
                    "slot.lb.N",
                    "slot.lb.M",
                    "slot.marker.1.base",
                    "slot.marker.1.w1",
                    "slot.marker.1.w2",
                    "slot.marker.2.base",
                    "slot.marker.2.w1",
                    "slot.marker.2.w2",
                    "slot.answer",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.problem",
                prompt="",
                text="XN = 6, XM = 2, XY = 10일 때, NZ를 구하시오.",
                style_role="question",
                x=40.0,
                y=80.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
                fill="#000000",
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="1. 12",
                style_role="choice",
                x=860.0,
                y=320.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
                fill="#000000",
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="2. 16",
                style_role="choice",
                x=860.0,
                y=384.8,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
                fill="#000000",
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="3. 24",
                style_role="choice",
                x=860.0,
                y=449.6,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
                fill="#000000",
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="4. 32",
                style_role="choice",
                x=860.0,
                y=514.4,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
                fill="#000000",
            ),
            RectSlot(
                id="slot.diagram.frame",
                prompt="",
                x=40.0,
                y=200.0,
                width=752.0,
                height=660.0,
                stroke="#D1D5DB",
                stroke_width=1.0,
                fill="none",
                semantic_role="geometry_diagram_region",
            ),
            LineSlot(
                id="slot.edge.base",
                prompt="",
                x1=64.0,
                y1=746.0,
                x2=768.0,
                y2=746.0,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.edge.left",
                prompt="",
                x1=64.0,
                y1=746.0,
                x2=610.5,
                y2=314.0,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.edge.right",
                prompt="",
                x1=610.5,
                y1=314.0,
                x2=768.0,
                y2=746.0,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.edge.inner",
                prompt="",
                x1=258.6,
                y1=592.1,
                x2=315.9,
                y2=746.0,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            CircleSlot(
                id="slot.pt.X",
                prompt="",
                cx=64.0,
                cy=746.0,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.Z",
                prompt="",
                cx=768.0,
                cy=746.0,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.Y",
                prompt="",
                cx=610.5,
                cy=314.0,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.N",
                prompt="",
                cx=315.9,
                cy=746.0,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.M",
                prompt="",
                cx=258.6,
                cy=592.1,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            TextSlot(
                id="slot.lb.X",
                prompt="",
                text="X",
                style_role="label",
                x=70.0,
                y=740.0,
                font_size=36,
                font_family="Malgun Gothic",
                anchor="start",
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.Z",
                prompt="",
                text="Z",
                style_role="label",
                x=774.0,
                y=740.0,
                font_size=36,
                font_family="Malgun Gothic",
                anchor="start",
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.Y",
                prompt="",
                text="Y",
                style_role="label",
                x=616.5,
                y=308.0,
                font_size=36,
                font_family="Malgun Gothic",
                anchor="start",
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.N",
                prompt="",
                text="N",
                style_role="label",
                x=321.9,
                y=740.0,
                font_size=36,
                font_family="Malgun Gothic",
                anchor="start",
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb.M",
                prompt="",
                text="M",
                style_role="label",
                x=264.6,
                y=586.1,
                font_size=36,
                font_family="Malgun Gothic",
                anchor="start",
                fill="#111111",
            ),
            LineSlot(
                id="slot.marker.1.base",
                prompt="",
                x1=691.3,
                y1=535.6,
                x2=687.2,
                y2=524.4,
                stroke="#2563EB",
                stroke_width=1.8,
                semantic_role="geometry_parallel_marker",
            ),
            LineSlot(
                id="slot.marker.1.w1",
                prompt="",
                x1=687.2,
                y1=524.4,
                x2=693.4,
                y2=529.0,
                stroke="#2563EB",
                stroke_width=1.8,
                semantic_role="geometry_parallel_marker",
            ),
            LineSlot(
                id="slot.marker.1.w2",
                prompt="",
                x1=687.2,
                y1=524.4,
                x2=685.4,
                y2=531.9,
                stroke="#2563EB",
                stroke_width=1.8,
                semantic_role="geometry_parallel_marker",
            ),
            LineSlot(
                id="slot.marker.2.base",
                prompt="",
                x1=289.4,
                y1=674.7,
                x2=285.2,
                y2=663.4,
                stroke="#2563EB",
                stroke_width=1.8,
                semantic_role="geometry_parallel_marker",
            ),
            LineSlot(
                id="slot.marker.2.w1",
                prompt="",
                x1=285.2,
                y1=663.4,
                x2=291.4,
                y2=668.0,
                stroke="#2563EB",
                stroke_width=1.8,
                semantic_role="geometry_parallel_marker",
            ),
            LineSlot(
                id="slot.marker.2.w2",
                prompt="",
                x1=285.2,
                y1=663.4,
                x2=283.5,
                y2=671.0,
                stroke="#2563EB",
                stroke_width=1.8,
                semantic_role="geometry_parallel_marker",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '2408',
 'problem_type': 'geometry_multiple_choice',
 'metadata': {'title': '도형 문제',
              'tags': [],
              'instruction': 'NZ를 구하시오.',
              'question': 'XN = 6, XM = 2, XY = 10일 때, NZ를 구하시오.',
              'required_layout_ids': ['slot.diagram.frame',
                                      'slot.edge.base',
                                      'slot.edge.left',
                                      'slot.edge.right',
                                      'slot.edge.inner',
                                      'slot.pt.X',
                                      'slot.pt.Z',
                                      'slot.pt.Y',
                                      'slot.pt.N',
                                      'slot.pt.M',
                                      'slot.marker.1.base',
                                      'slot.marker.1.w1',
                                      'slot.marker.1.w2',
                                      'slot.marker.2.base',
                                      'slot.marker.2.w1',
                                      'slot.marker.2.w2'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.triangle', 'type': 'triangle', 'name': 'XZY'},
                        {'id': 'obj.point.X', 'type': 'point', 'name': 'X'},
                        {'id': 'obj.point.Y', 'type': 'point', 'name': 'Y'},
                        {'id': 'obj.point.Z', 'type': 'point', 'name': 'Z'},
                        {'id': 'obj.point.N', 'type': 'point', 'name': 'N'},
                        {'id': 'obj.point.M', 'type': 'point', 'name': 'M'},
                        {'id': 'obj.segment.XN', 'type': 'segment', 'name': 'XN', 'value': 6},
                        {'id': 'obj.segment.XM', 'type': 'segment', 'name': 'XM', 'value': 2},
                        {'id': 'obj.segment.XY', 'type': 'segment', 'name': 'XY', 'value': 10},
                        {'id': 'obj.segment.NZ', 'type': 'segment', 'name': 'NZ'}],
            'relations': [{'id': 'rel.N_on_XZ',
                           'type': 'lies_on',
                           'from_id': 'obj.point.N',
                           'to_id': 'obj.segment.XZ'},
                          {'id': 'rel.M_on_XY',
                           'type': 'lies_on',
                           'from_id': 'obj.point.M',
                           'to_id': 'obj.segment.XY'},
                          {'id': 'rel.find_NZ',
                           'type': 'find',
                           'from_id': 'obj.segment.NZ',
                           'to_id': 'answer.target'}],
            'confidence': 1.0,
            'problem_solving': {'understand': {'given_refs': ['obj.segment.XN',
                                                              'obj.segment.XM',
                                                              'obj.segment.XY'],
                                               'target_ref': 'answer.target',
                                               'condition_refs': ['rel.N_on_XZ',
                                                                  'rel.M_on_XY',
                                                                  'rel.find_NZ']},
                                'plan': {'method': 'use_given_length_relations',
                                         'description': '주어진 길이와 도형의 관계를 바탕으로 NZ를 구한다.'},
                                'execute': {'expected_operations': ['interpret_diagram_relations',
                                                                    'compare_segment_lengths',
                                                                    'determine_NZ']},
                                'review': {'check_methods': ['answer_matches_choice',
                                                             'check_unit_length_consistency']}}},
 'answer': {'blanks': [],
            'choices': [{'index': 1, 'text': '1. 12', 'value': '12'},
                        {'index': 2, 'text': '2. 16', 'value': '16'},
                        {'index': 3, 'text': '3. 24', 'value': '24'},
                        {'index': 4, 'text': '4. 32', 'value': '32'}],
            'answer_key': [3],
            'confidence': 1.0,
            'target': {'type': 'segment_length', 'description': 'NZ'},
            'value': 24,
            'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '2408',
 'problem_type': 'geometry_multiple_choice',
 'inputs': {'total_ticks': 0,
            'target_label': 'NZ',
            'target_ticks': 0,
            'target_count': 1,
            'unit': ''},
 'given': [{'ref': 'obj.segment.XN', 'value': 6},
           {'ref': 'obj.segment.XM', 'value': 2},
           {'ref': 'obj.segment.XY', 'value': 10}],
 'target': {'ref': 'answer.target', 'type': 'segment_length'},
 'method': 'use_given_length_relations',
 'plan': ['그림과 주어진 길이 정보를 읽는다.', 'NZ에 해당하는 값을 선택지와 대응시켜 확인한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'read_given_lengths',
            'expr': 'XN = 6, XM = 2, XY = 10',
            'value': 0},
           {'id': 'step.2', 'operation': 'identify_target', 'expr': 'find NZ', 'value': 0}],
 'checks': [{'id': 'check.1',
             'type': 'choice_match',
             'expr': '정답: C (24)',
             'expected': 24,
             'actual': 24,
             'pass': True}],
 'answer': {'value': 24, 'unit': '', 'derived_from': 'choice.3'}}
