from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008779",
        title="들이가 가장 많은 컵 고르기",
        canvas=Canvas(width=944, height=308, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.table.outer",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.r1c1",
                    "slot.table.r1c2",
                    "slot.table.r1c3",
                    "slot.table.r1c4",
                    "slot.table.r2c1",
                    "slot.table.r2c2",
                    "slot.table.r2c3",
                    "slot.table.r2c4",
                    "slot.choice",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="수조에 물을 가득 채우려면 ㉮, ㉯, ㉰ 컵에 물을 가득 채워 각각 다음과",
                style_role="question",
                x=10,
                y=38,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="같이 부어야 합니다. 들이가 가장 많은 컵은 어느 것인지 선택해 보세요.",
                style_role="question",
                x=10,
                y=88,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=160,
                y=124,
                width=530,
                height=84,
                fill="#FFFFFF",
                stroke="#9A9A9A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.h1",
                prompt="",
                x=160,
                y=124,
                width=530,
                height=42,
                fill="#FDE8C5",
                stroke="none",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.table.h2",
                prompt="",
                x=160,
                y=166,
                width=530,
                height=42,
                fill="#FFFFFF",
                stroke="none",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.table.v1",
                prompt="",
                x=160,
                y=124,
                width=200,
                height=84,
                fill="none",
                stroke="#9A9A9A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.v2",
                prompt="",
                x=360,
                y=124,
                width=110,
                height=84,
                fill="none",
                stroke="#9A9A9A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.v3",
                prompt="",
                x=470,
                y=124,
                width=110,
                height=84,
                fill="none",
                stroke="#9A9A9A",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table.r1c1",
                prompt="",
                text="컵",
                style_role="label",
                x=252.192,
                y=157.8,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r1c2",
                prompt="",
                text="㉮",
                style_role="label",
                x=400,
                y=157,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r1c3",
                prompt="",
                text="㉯",
                style_role="label",
                x=510,
                y=157,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r1c4",
                prompt="",
                text="㉰",
                style_role="label",
                x=620,
                y=157,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c1",
                prompt="",
                text="부은 횟수(번)",
                style_role="label",
                x=190,
                y=198,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c2",
                prompt="",
                text="16",
                style_role="label",
                x=400,
                y=198,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c3",
                prompt="",
                text="15",
                style_role="label",
                x=510,
                y=198,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c4",
                prompt="",
                text="11",
                style_role="label",
                x=620,
                y=198,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( ㉮ 컵, ㉯ 컵, ㉰ 컵 )",
                style_role="choice",
                x=310,
                y=281,
                font_size=28,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008779",
    "problem_type": "비교",
    "metadata": {
        "language": "ko",
        "question": "표를 보고 들이가 가장 많은 컵을 고르는 문제",
        "instruction": "들이가 가장 많은 컵은 어느 것인지 선택해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.cup.ga", "type": "cup", "label": "가"},
            {"id": "obj.cup.na", "type": "cup", "label": "나"},
            {"id": "obj.cup.da", "type": "cup", "label": "다"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["rel.pour_count.ga", "rel.pour_count.na", "rel.pour_count.da"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.inverse_relation"],
            },
            "plan": {
                "method": "비교",
                "description": "부은 횟수를 비교해 가장 적은 값을 찾고, 그 컵을 고른다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_counts",
                    "find_minimum_count",
                    "select_corresponding_cup",
                ]
            },
            "review": {"check_methods": ["smallest_count_matches_answer"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "cup_name", "description": "들이가 가장 많은 컵"},
        "value": "다 컵",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008779",
    "problem_type": "비교",
    "inputs": {
        "total_ticks": 3,
        "target_label": "들이가 가장 많은 컵",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "컵",
    },
    "given": [
        {"ref": "rel.pour_count.ga", "value": 16},
        {"ref": "rel.pour_count.na", "value": 15},
        {"ref": "rel.pour_count.da", "value": 11},
    ],
    "target": {"ref": "answer.target", "type": "cup_name"},
    "method": "비교",
    "plan": [
        "부은 횟수를 비교한다.",
        "가장 적게 부은 컵을 찾는다.",
        "그 컵이 들이가 가장 큰 컵이다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "16, 15, 11 중 가장 작은 수를 찾는다", "value": 11},
        {"id": "step.2", "expr": "11번에 해당하는 컵을 찾는다", "value": "다"},
        {"id": "step.3", "expr": "들이가 가장 많은 컵을 선택한다", "value": "다 컵"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "11이 16과 15보다 작은가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "가장 적은 부은 횟수와 선택한 컵이 일치하는가",
            "expected": "다",
            "actual": "다",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "cup_name", "description": "들이가 가장 많은 컵"},
        "value": "다 컵",
        "unit": "",
    },
}
