from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot, CircleSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008764', title='공책과 필통의 무게 비교', canvas=Canvas(width=960, height=520, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.qnum', 'slot.qtext1', 'slot.qtext2')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.scale.base', 'slot.scale.pillar', 'slot.scale.beam', 'slot.scale.left.pan', 'slot.scale.right.pan', 'slot.scale.left.stand', 'slot.scale.right.stand', 'slot.scale.center.knob', 'slot.scale.left.book', 'slot.scale.right.pencilcase', 'slot.label.book', 'slot.label.pencilcase')), Region(id='region.choice', role='stem', flow='absolute', slot_ids=('slot.choice',)), Region(id='region.answer', role='annotation', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.qnum', prompt='', text='□ 66.', style_role='question', x=14.0, y=40.0, font_size=28), TextSlot(id='slot.qtext1', prompt='', text='저울을 사용하여 공책과 필통의 무게를 비교하려고 합니다. 알맞은 말을', style_role='question', x=72.0, y=40.0, font_size=28), TextSlot(id='slot.qtext2', prompt='', text='선택하세요.', style_role='question', x=72.0, y=76.0, font_size=28), RectSlot(id='slot.scale.base', prompt='', x=380.0, y=250.0, width=215.0, height=52.0, rx=8.0, ry=8.0), RectSlot(id='slot.scale.pillar', prompt='', x=476.0, y=165.0, width=22.0, height=95.0, rx=6.0, ry=6.0), LineSlot(id='slot.scale.beam', prompt='', x1=382.0, y1=150.0, x2=582.0, y2=182.0), LineSlot(id='slot.scale.left.pan', prompt='', x1=408.0, y1=158.0, x2=438.0, y2=222.0), LineSlot(id='slot.scale.right.pan', prompt='', x1=556.0, y1=178.0, x2=526.0, y2=232.0), LineSlot(id='slot.scale.left.stand', prompt='', x1=424.0, y1=220.0, x2=424.0, y2=268.0), LineSlot(id='slot.scale.right.stand', prompt='', x1=538.0, y1=230.0, x2=538.0, y2=268.0), CircleSlot(id='slot.scale.center.knob', prompt='', cx=487.0, cy=208.0, r=5.0, fill='#222222'), RectSlot(id='slot.scale.left.book', prompt='', x=400.0, y=120.0, width=86.0, height=56.0, rx=4.0, ry=4.0), RectSlot(id='slot.scale.right.pencilcase', prompt='', x=520.0, y=126.0, width=76.0, height=54.0, rx=4.0, ry=4.0), TextSlot(id='slot.label.book', prompt='', text='공책', style_role='label', x=418.0, y=104.0, font_size=28), TextSlot(id='slot.label.pencilcase', prompt='', text='필통', style_role='label', x=536.0, y=108.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='공책이 필통보다 더 ( 무겁습니다, 가볍습니다 ).', style_role='question', x=200.0, y=392.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008764', 'problem_type': 'weight_comparison_choice', 'metadata': {'language': 'ko', 'question': '저울을 사용하여 공책과 필통의 무게를 비교하려고 합니다. 알맞은 말을 선택하세요.', 'instruction': '공책이 필통보다 더 ( 무겁습니다, 가볍습니다 ).'}, 'domain': {'objects': [{'id': 'obj.book', 'type': 'object', 'name': '공책'}, {'id': 'obj.pencilcase', 'type': 'object', 'name': '필통'}, {'id': 'obj.balance_scale', 'type': 'balance_scale'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.book', 'obj.pencilcase', 'obj.balance_scale', 'rel.left_side_higher'], 'target_ref': 'answer.target', 'condition_refs': ['rel.compare_weight']}, 'plan': {'method': 'balance_comparison', 'description': '저울의 높이 차이를 보고 더 가벼운 쪽과 더 무거운 쪽을 비교한다.'}, 'execute': {'expected_operations': ['observe_balance_tilt', 'compare_weights', 'choose_comparison_word']}, 'review': {'check_methods': ['tilted_side_is_lighter', 'sentence_choice_matches_scale']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'comparison_word', 'description': '공책이 필통보다 더 (무겁습니다/가볍습니다) 중 알맞은 말'}, 'value': '가볍습니다', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008764', 'problem_type': 'weight_comparison_choice', 'inputs': {'total_ticks': 0, 'target_label': '공책이 필통보다 더 ( 무겁습니다, 가볍습니다 )', 'target_ticks': 0, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.book', 'value': {'name': '공책'}}, {'ref': 'obj.pencilcase', 'value': {'name': '필통'}}, {'ref': 'rel.left_side_higher', 'value': {'direction': 'up'}}], 'target': {'ref': 'answer.target', 'type': 'comparison_word'}, 'method': 'balance_comparison', 'plan': ['저울에서 더 위로 올라간 쪽이 더 가볍다는 점을 확인한다.', '공책이 있는 왼쪽 접시가 위에 있는지 본다.', '알맞은 비교 말을 선택한다.'], 'steps': [{'id': 'step.1', 'expr': '왼쪽 접시가 오른쪽 접시보다 위에 있다', 'value': True}, {'id': 'step.2', 'expr': '위로 올라간 쪽은 더 가볍다', 'value': True}, {'id': 'step.3', 'expr': '공책 < 필통', 'value': True}, {'id': 'step.4', 'expr': '선택어 = 가볍습니다', 'value': '가볍습니다'}], 'checks': [{'id': 'check.1', 'expr': '저울의 위쪽 접시가 공책 쪽인지 확인', 'expected': True, 'actual': True, 'pass': True}, {'id': 'check.2', 'expr': '선택한 말이 그림의 비교 관계와 일치하는지 확인', 'expected': '가볍습니다', 'actual': '가볍습니다', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'comparison_word', 'description': '공책이 필통보다 더 (무겁습니다/가볍습니다) 중 알맞은 말'}, 'value': '가볍습니다', 'unit': ''}}
