from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008928",
        title="남학생이 가장 많이 하고 싶어 하는 종목",
        canvas=Canvas(width=960, height=418, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.no", "slot.q1", "slot.q2"),
            ),
            Region(
                id="region.table_title",
                role="diagram",
                flow="absolute",
                slot_ids=("slot.table_title",),
            ),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.table.border",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.v5",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.t00",
                    "slot.t01",
                    "slot.t02",
                    "slot.t03",
                    "slot.t04",
                    "slot.t05",
                    "slot.t10",
                    "slot.t11",
                    "slot.t12",
                    "slot.t13",
                    "slot.t14",
                    "slot.t15",
                    "slot.t20",
                    "slot.t21",
                    "slot.t22",
                    "slot.t23",
                    "slot.t24",
                    "slot.t25",
                ),
            ),
            Region(
                id="region.choices",
                role="diagram",
                flow="absolute",
                slot_ids=("slot.c1", "slot.c2", "slot.c3", "slot.c4"),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
            Region(id="region.explanation", role="explanation", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.no",
                prompt="",
                text="94.",
                style_role="question",
                x=10.0,
                y=20.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q1",
                prompt="",
                text="연수네 반 학생들이 학예회에서 하고 싶어 하는 종목을 조사하여 표로 나타냈습니다. 남학생이 가장 많이 하고 싶어 하는 종목은 무엇인가요?",
                style_role="question",
                x=52.0,
                y=20.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="",
                style_role="question",
                x=52.0,
                y=56.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table_title",
                prompt="",
                text="여학생과 남학생이 학예회에서 하고 싶어 하는 종목",
                style_role="label",
                x=244.0,
                y=102.0,
                font_size=24,
            ),
            RectSlot(
                id="slot.table.border", prompt="", x=164.0, y=117.0, width=636.0, height=116.0
            ),
            LineSlot(id="slot.table.v1", prompt="", x1=354.0, y1=117.0, x2=354.0, y2=233.0),
            LineSlot(id="slot.table.v2", prompt="", x1=449.0, y1=117.0, x2=449.0, y2=233.0),
            LineSlot(id="slot.table.v3", prompt="", x1=544.0, y1=117.0, x2=544.0, y2=233.0),
            LineSlot(id="slot.table.v4", prompt="", x1=639.0, y1=117.0, x2=639.0, y2=233.0),
            LineSlot(id="slot.table.v5", prompt="", x1=734.0, y1=117.0, x2=734.0, y2=233.0),
            LineSlot(id="slot.table.h1", prompt="", x1=164.0, y1=153.0, x2=800.0, y2=153.0),
            LineSlot(id="slot.table.h2", prompt="", x1=164.0, y1=193.0, x2=800.0, y2=193.0),
            TextSlot(
                id="slot.t00",
                prompt="",
                text="종목",
                style_role="table",
                x=248.0,
                y=142.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t01",
                prompt="",
                text="연극",
                style_role="table",
                x=391.0,
                y=142.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t02",
                prompt="",
                text="합주",
                style_role="table",
                x=486.0,
                y=142.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t03",
                prompt="",
                text="무용",
                style_role="table",
                x=581.0,
                y=142.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t04",
                prompt="",
                text="합창",
                style_role="table",
                x=676.0,
                y=142.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t05",
                prompt="",
                text="합계",
                style_role="table",
                x=768.0,
                y=142.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t10",
                prompt="",
                text="여학생 수(명)",
                style_role="table",
                x=204.0,
                y=182.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t11",
                prompt="",
                text="2",
                style_role="table",
                x=391.0,
                y=182.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t12",
                prompt="",
                text="7",
                style_role="table",
                x=486.0,
                y=182.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t13",
                prompt="",
                text="3",
                style_role="table",
                x=581.0,
                y=182.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t14",
                prompt="",
                text="1",
                style_role="table",
                x=676.0,
                y=182.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t15",
                prompt="",
                text="13",
                style_role="table",
                x=770.0,
                y=182.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t20",
                prompt="",
                text="남학생 수(명)",
                style_role="table",
                x=204.0,
                y=222.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t21",
                prompt="",
                text="4",
                style_role="table",
                x=391.0,
                y=222.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t22",
                prompt="",
                text="3",
                style_role="table",
                x=486.0,
                y=222.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t23",
                prompt="",
                text="2",
                style_role="table",
                x=581.0,
                y=222.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t24",
                prompt="",
                text="6",
                style_role="table",
                x=676.0,
                y=222.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.t25",
                prompt="",
                text="15",
                style_role="table",
                x=770.0,
                y=222.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.c1",
                prompt="",
                text="① 연극",
                style_role="choice",
                x=20.0,
                y=267.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.c2",
                prompt="",
                text="② 합주",
                style_role="choice",
                x=236.0,
                y=267.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.c3",
                prompt="",
                text="③ 무용",
                style_role="choice",
                x=408.0,
                y=267.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.c4",
                prompt="",
                text="④ 합창",
                style_role="choice",
                x=592.0,
                y=267.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008928",
    "problem_type": "table_interpretation",
    "metadata": {
        "language": "ko",
        "question": "남학생이 가장 많이 하고 싶어 하는 종목을 찾는 문제",
        "instruction": "표를 보고 알맞은 답을 고르세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.subjects", "type": "subjects", "items": ["연극", "합주", "무용", "합창"]},
            {
                "id": "obj.boys_counts",
                "type": "count_series",
                "label": "남학생 수",
                "values": [4, 3, 2, 6],
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.subjects", "obj.boys_counts"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.max_count"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "남학생 수를 비교하여 가장 큰 수에 해당하는 종목을 찾는다.",
            },
            "execute": {"expected_operations": ["compare_values", "select_max_category"]},
            "review": {"check_methods": ["max_value_matches_selected_subject"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "multiple_choice_option",
            "description": "남학생이 가장 많이 하고 싶어 하는 종목",
        },
        "value": 4,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008928",
    "problem_type": "table_interpretation",
    "inputs": {
        "total_ticks": 4,
        "target_label": "남학생이 가장 많이 하고 싶어 하는 종목",
        "target_ticks": 1,
        "target_count": 4,
        "unit": "",
    },
    "given": [
        {"ref": "obj.subjects", "value": ["연극", "합주", "무용", "합창"]},
        {"ref": "obj.boys_counts", "value": [4, 3, 2, 6]},
    ],
    "target": {"ref": "answer.target", "type": "multiple_choice_option"},
    "method": "compare_counts",
    "plan": ["남학생 수를 종목별로 비교한다.", "가장 큰 수에 해당하는 종목을 고른다."],
    "steps": [
        {"id": "step.1", "expr": "4, 3, 2, 6 중 최대값 찾기", "value": 6},
        {"id": "step.2", "expr": "최대값 6에 해당하는 종목 선택", "value": "합창"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "6이 4, 3, 2, 6 중 가장 큰 수인가?",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "선택한 종목이 합창인가?",
            "expected": "합창",
            "actual": "합창",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "multiple_choice_option",
            "description": "남학생이 가장 많이 하고 싶어 하는 종목",
        },
        "value": 4,
        "unit": "",
    },
}
