from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008733', title='사다리를 타고 분수 분류하기', canvas=Canvas(width=935.0, height=877.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q2', 'slot.q7', 'slot.q8', 'slot.q9', 'slot.q10', 'slot.q11', 'slot.q12', 'slot.q13', 'slot.q14', 'slot.q15', 'slot.q16', 'slot.q19', 'slot.q20', 'slot.q21', 'slot.q22', 'slot.q23', 'slot.q24', 'slot.q2.copy28', 'slot.q16.copy29', 'slot.q16.copy30')),), slots=(TextSlot(id='slot.q2', prompt='', text = '사다리를 타고 내려가 도착한 곳이 참이면 ○표,', style_role='question', x = 65, y = 98, font_size = 30), TextSlot(id='slot.q7', prompt='', text = '3', style_role='question', x = 300, y = 238, font_size = 30), TextSlot(id='slot.q8', prompt='', text = '10', style_role='question', x = 300, y = 355, font_size = 30), LineSlot(id='slot.q9', prompt='', x1 = 294, y1 = 255, x2 = 324, y2 = 255), TextSlot(id='slot.q10', prompt='', text = '2', style_role='question', x = 455, y = 238, font_size = 30), TextSlot(id='slot.q11', prompt='', text = '2', style_role='question', x = 455, y = 335, font_size = 30), LineSlot(id='slot.q12', prompt='', x1 = 451, y1 = 257, x2 = 476, y2 = 257), TextSlot(id='slot.q13', prompt='', text = '15', style_role='question', x = 615, y = 238, font_size = 30), TextSlot(id='slot.q14', prompt='', text = '7', style_role='question', x = 620, y = 340, font_size = 30), LineSlot(id='slot.q15', prompt='', x1 = 618, y1 = 255, x2 = 643, y2 = 255), RectSlot(id='slot.q16', prompt='', x = 140, y = 310, width = 110, height = 65, fill = '#fecaca', stroke = '#111111', stroke_width = 1.5), TextSlot(id='slot.q19', prompt='', text = '가분수', style_role='question', x = 285, y = 400, font_size = 30), TextSlot(id='slot.q20', prompt='', text = '진분수', style_role='question', x = 440, y = 400, font_size = 30), TextSlot(id='slot.q21', prompt='', text = '진분수', style_role='question', x = 600, y = 400, font_size = 30), TextSlot(id='slot.q22', prompt='', text = '(○, ×)', style_role='question', x = 250, y = 445, font_size = 30), TextSlot(id='slot.q23', prompt='', text = '(○, ×)', style_role='question', x = 410, y = 445, font_size = 30), TextSlot(id='slot.q24', prompt='', text = '(○, ×)', style_role='question', x = 570, y = 445, font_size = 30), TextSlot(id = 'slot.q2.copy28', prompt = '', text = '거짓이면 ×표를 선택하세요.', x = 65, y = 150, font_size = 30, fill = '#111111'), RectSlot(id = 'slot.q16.copy29', prompt = '', x = 60, y = 420, width = 110, height = 65, fill = '#fecaca', stroke = '#111111', stroke_width = 1.5), RectSlot(id = 'slot.q16.copy30', prompt = '', x = 240, y = 490, width = 110, height = 65, fill = '#fecaca', stroke = '#111111', stroke_width = 1.5)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008733', 'problem_type': '분수 분류', 'metadata': {'language': 'ko', 'question': '사다리를 타고 내려가 도착한 곳이 참이면 ○표, 거짓이면 ×표를 선택하는 문제', 'instruction': '분수를 가분수와 진분수로 분류한다.', 'points': 5}, 'domain': {'objects': [{'id': 'obj.frac.1', 'type': 'fraction', 'value': '3/10'}, {'id': 'obj.frac.2', 'type': 'fraction', 'value': '2/2'}, {'id': 'obj.frac.3', 'type': 'fraction', 'value': '15/7'}, {'id': 'obj.class.1', 'type': 'classification', 'value': '가분수'}, {'id': 'obj.class.2', 'type': 'classification', 'value': '진분수'}, {'id': 'obj.class.3', 'type': 'classification', 'value': '진분수'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.frac.1', 'obj.frac.2', 'obj.frac.3'], 'target_ref': 'answer.target', 'condition_refs': ['rel.match.1', 'rel.match.2', 'rel.match.3']}, 'plan': {'method': '분수의 분류 확인', 'description': '각 분수가 가분수인지 진분수인지 분류를 확인한다.'}, 'execute': {'expected_operations': ['분류 확인', '선택지 대응 확인']}, 'review': {'check_methods': ['화면에 보이는 해설과 대응 관계 확인']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selection_pattern', 'description': '○, ×, ○'}, 'value': 3, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008733', 'problem_type': '분수 분류', 'inputs': {'total_ticks': 3, 'target_label': '선택 결과', 'target_ticks': 3, 'target_count': 3, 'unit': ''}, 'given': [{'ref': 'obj.frac.1', 'value': '3/10'}, {'ref': 'obj.frac.2', 'value': '2/2'}, {'ref': 'obj.frac.3', 'value': '15/7'}], 'target': {'ref': 'answer.target', 'type': 'selection_pattern'}, 'method': '분수 분류 확인', 'plan': ['각 분수를 보고 가분수와 진분수를 구분한다.', '화면에 제시된 해설과 대응을 확인한다.'], 'steps': [{'id': 'step.1', 'expr': '3/10의 분류 확인', 'value': '진분수'}, {'id': 'step.2', 'expr': '2/2의 분류 확인', 'value': '가분수'}, {'id': 'step.3', 'expr': '15/7의 분류 확인', 'value': '가분수'}, {'id': 'step.4', 'expr': '선택 결과', 'value': '○, ×, ○'}], 'checks': [{'id': 'check.1', 'expr': '화면의 (정답) 표기와 선택 결과 일치 여부', 'expected': '○, ×, ○', 'actual': '○, ×, ○', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selection_pattern', 'description': '○, ×, ○'}, 'value': 3, 'unit': ''}}
