from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, PolygonSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008808', title='식탁의 무게 단위 선택', canvas=Canvas(width=940, height=348, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.qnum', 'slot.question', 'slot.checkbox')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.table.top', 'slot.table.face', 'slot.table.leg_left_front', 'slot.table.leg_right_front', 'slot.table.leg_right_back', 'slot.table.leg_center', 'slot.table.shadow')), Region(id='region.choice', role='choice', flow='absolute', slot_ids=('slot.choice',)), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.checkbox', prompt='', text='□', style_role='question', x=10.0, y=28.0, font_size=28), TextSlot(id='slot.qnum', prompt='', text='37.', style_role='question', x=52.0, y=28.0, font_size=28), TextSlot(id='slot.question', prompt='', text='식탁의 무게를 나타내는 데 알맞은 단위를 선택하세요.', style_role='question', x=96.0, y=28.0, font_size=28), RectSlot(id='slot.table.shadow', prompt='', x=382.0, y=82.0, width=186.0, height=98.0), PolygonSlot(id='slot.table.top', prompt='', points=((388.0, 46.0), (521.0, 46.0), (579.0, 81.0), (445.0, 81.0))), PolygonSlot(id='slot.table.face', prompt='', points=((388.0, 46.0), (445.0, 81.0), (445.0, 90.0), (388.0, 55.0))), LineSlot(id='slot.table.leg_left_front', prompt='', x1=406.0, y1=83.0, x2=406.0, y2=154.0), LineSlot(id='slot.table.leg_right_front', prompt='', x1=502.0, y1=83.0, x2=502.0, y2=154.0), LineSlot(id='slot.table.leg_right_back', prompt='', x1=542.0, y1=68.0, x2=542.0, y2=146.0), LineSlot(id='slot.table.leg_center', prompt='', x1=446.0, y1=83.0, x2=446.0, y2=128.0), TextSlot(id='slot.choice', prompt='', text='( g , kg )', style_role='question', x=792.0, y=228.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008808', 'problem_type': 'unit_selection', 'metadata': {'language': 'ko', 'question': '식탁의 무게를 나타내는 데 알맞은 단위를 선택하세요.', 'instruction': '무게를 나타내는 단위를 고른다.'}, 'domain': {'objects': [{'id': 'obj.table', 'type': 'furniture', 'name': '식탁'}, {'id': 'obj.unit_g', 'type': 'unit', 'name': 'g'}, {'id': 'obj.unit_kg', 'type': 'unit', 'name': 'kg'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.table', 'obj.unit_g', 'obj.unit_kg'], 'target_ref': 'answer.target', 'condition_refs': ['rel.choose_unit', 'rel.explanation']}, 'plan': {'method': 'unit_choice', 'description': '물건의 무게를 나타내는 데 알맞은 단위를 고른다.'}, 'execute': {'expected_operations': ['compare_unit_scale', 'select_appropriate_unit']}, 'review': {'check_methods': ['answer_matches_printed_choice']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'weight_unit', 'description': '식탁의 무게를 나타내는 알맞은 단위'}, 'value': 'kg', 'unit': 'kg'}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008808', 'problem_type': 'unit_selection', 'inputs': {'total_ticks': 2, 'target_label': '식탁의 무게를 나타내는 단위', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.table', 'value': {'name': '식탁'}}, {'ref': 'obj.unit_g', 'value': 'g'}, {'ref': 'obj.unit_kg', 'value': 'kg'}], 'target': {'ref': 'answer.target', 'type': 'weight_unit'}, 'method': 'unit_choice', 'plan': ['식탁에 어울리는 무게 단위를 고른다.', '작은 물건은 g, 더 무거운 물건은 kg을 사용한다.'], 'steps': [{'id': 'step.1', 'expr': 'g 와 kg 중 식탁에 알맞은 단위 선택', 'value': 'kg'}], 'checks': [{'id': 'check.1', 'expr': 'printed_answer == kg', 'expected': 'kg', 'actual': 'kg', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'weight_unit', 'description': '식탁의 무게를 나타내는 알맞은 단위'}, 'value': 'kg', 'unit': 'kg'}}
