from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009001', title='정사각형을 찾아 기호를 선택하세요.', canvas=Canvas(width=840, height=330, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.no', 'slot.q1', 'slot.grid.bg', 'slot.shape.ga', 'slot.shape.na', 'slot.shape.da', 'slot.shape.ra', 'slot.choice')),), slots=(TextSlot(id='slot.no', prompt='', text='39.', style_role='question', x=32.0, y=34.0, font_size=28), TextSlot(id='slot.q1', prompt='', text='정사각형을 찾아 기호를 선택하세요.', style_role='question', x=76.0, y=34.0, font_size=28), RectSlot(id='slot.grid.bg', prompt='', x=248.0, y=46.0, width=420.0, height=160.0, fill='#EAF6FF', stroke='#CFE6FA', stroke_width=1.0), RectSlot(id='slot.shape.ga', prompt='', x=272.0, y=66.0, width=110.0, height=42.0, fill='none', stroke='#444444', stroke_width=2.0), RectSlot(id='slot.shape.na', prompt='', x=394.0, y=88.0, width=86.0, height=86.0, fill='none', stroke='#444444', stroke_width=2.0), RectSlot(id='slot.shape.da', prompt='', x=502.0, y=70.0, width=44.0, height=96.0, fill='none', stroke='#444444', stroke_width=2.0), RectSlot(id='slot.shape.ra', prompt='', x=565.0, y=68.0, width=88.0, height=96.0, fill='none', stroke='#444444', stroke_width=2.0), TextSlot(id='slot.choice', prompt='', text='( 가, 나, 다, 라 )', style_role='question', x=330.0, y=228.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009001', 'problem_type': '도형_분류', 'metadata': {'language': 'ko', 'question': '정사각형을 찾아 기호를 선택하세요.', 'instruction': '정사각형에 해당하는 도형의 기호를 고른다.'}, 'domain': {'objects': [{'id': 'obj.ga', 'type': 'quadrilateral', 'label': '가'}, {'id': 'obj.na', 'type': 'square', 'label': '나'}, {'id': 'obj.da', 'type': 'quadrilateral', 'label': '다'}, {'id': 'obj.ra', 'type': 'quadrilateral', 'label': '라'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.ga', 'obj.na', 'obj.da', 'obj.ra'], 'target_ref': 'answer.target', 'condition_refs': ['rel.select_square']}, 'plan': {'method': 'shape_classification', 'description': '도형의 변과 각의 성질을 보고 정사각형에 해당하는 기호를 찾는다.'}, 'execute': {'expected_operations': ['compare_shape_properties', 'identify_square']}, 'review': {'check_methods': ['definition_match_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'symbol_selection', 'description': '정사각형에 해당하는 기호'}, 'value': '나', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009001', 'problem_type': '도형_분류', 'inputs': {'total_ticks': 4, 'target_label': '정사각형', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.ga', 'value': {'label': '가', 'type': 'quadrilateral'}}, {'ref': 'obj.na', 'value': {'label': '나', 'type': 'square'}}, {'ref': 'obj.da', 'value': {'label': '다', 'type': 'quadrilateral'}}, {'ref': 'obj.ra', 'value': {'label': '라', 'type': 'quadrilateral'}}], 'target': {'ref': 'answer.target', 'type': 'symbol_selection'}, 'method': 'shape_classification', 'plan': ['각 도형의 성질을 보고 정사각형인지 확인한다.', '정사각형에 해당하는 기호를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '정사각형의 성질과 도형 비교', 'value': '나'}], 'checks': [{'id': 'check.1', 'expr': '선택한 기호가 정사각형과 일치하는가', 'expected': '나', 'actual': '나', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'symbol_selection', 'description': '정사각형에 해당하는 기호'}, 'value': '나', 'unit': ''}}
