from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008897",
        title="과수원별 포도 생산량",
        canvas=Canvas(width=960, height=432, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.title",
                    "slot.tbl.h1",
                    "slot.tbl.h2",
                    "slot.tbl.c1",
                    "slot.tbl.c2",
                    "slot.tbl.c3",
                    "slot.tbl.r1",
                    "slot.tbl.r2",
                    "slot.tbl.r3",
                    "slot.leg1.txt",
                    "slot.leg2.txt",
                    "slot.choice",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.tbl.outer",
                    "slot.tbl.head",
                    "slot.tbl.vline",
                    "slot.tbl.hline1",
                    "slot.tbl.hline2",
                    "slot.tbl.hline3",
                    "slot.tbl.g1_1",
                    "slot.tbl.g1_2",
                    "slot.tbl.g1_3",
                    "slot.tbl.g1_4",
                    "slot.tbl.g2_1",
                    "slot.tbl.g2_2",
                    "slot.tbl.g2_3",
                    "slot.tbl.g2_4",
                    "slot.tbl.g2_5",
                    "slot.tbl.g3_1",
                    "slot.tbl.g3_2",
                    "slot.tbl.g3_3",
                    "slot.tbl.g3_4",
                    "slot.leg.big",
                    "slot.leg.small",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="63. 과수원별 포도 생산량을 조사하여 나타낸 그림그래프입니다. 포도 생산량이 가장 많은 과수원을 선택해 보세요.",
                style_role="question",
                x=18.0,
                y=38.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.title",
                prompt="",
                text="과수원별 포도 생산량",
                style_role="title",
                x=330.0,
                y=74.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.tbl.outer",
                prompt="",
                x=194.0,
                y=88.0,
                width=430.0,
                height=192.0,
                fill="none",
            ),
            RectSlot(
                id="slot.tbl.head",
                prompt="",
                x=194.0,
                y=88.0,
                width=430.0,
                height=38.0,
                fill="#D6B9DD",
            ),
            LineSlot(
                id="slot.tbl.vline",
                prompt="",
                x1=288.0,
                y1=88.0,
                x2=288.0,
                y2=280.0,
                stroke="#6D6170",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.tbl.hline1",
                prompt="",
                x1=194.0,
                y1=126.0,
                x2=624.0,
                y2=126.0,
                stroke="#6D6170",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.tbl.hline2",
                prompt="",
                x1=194.0,
                y1=164.0,
                x2=624.0,
                y2=164.0,
                stroke="#6D6170",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.tbl.hline3",
                prompt="",
                x1=194.0,
                y1=222.0,
                x2=624.0,
                y2=222.0,
                stroke="#6D6170",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.tbl.h1",
                prompt="",
                text="과수원",
                style_role="label",
                x=230.0,
                y=112.0,
                font_size=26,
            ),
            TextSlot(
                id="slot.tbl.h2",
                prompt="",
                text="생산량",
                style_role="label",
                x=404.0,
                y=112.0,
                font_size=26,
            ),
            TextSlot(
                id="slot.tbl.c1",
                prompt="",
                text="가",
                style_role="label",
                x=236.0,
                y=148.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c2",
                prompt="",
                text="나",
                style_role="label",
                x=236.0,
                y=186.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c3",
                prompt="",
                text="다",
                style_role="label",
                x=236.0,
                y=244.0,
                font_size=28,
            ),
            CircleSlot(id="slot.tbl.r1", prompt="", cx=332.0, cy=144.0, r=4.0, fill="#5B4A91"),
            CircleSlot(id="slot.tbl.r2", prompt="", cx=362.0, cy=144.0, r=4.0, fill="#5B4A91"),
            CircleSlot(id="slot.tbl.r3", prompt="", cx=392.0, cy=144.0, r=4.0, fill="#5B4A91"),
            CircleSlot(id="slot.tbl.g1_1", prompt="", cx=324.0, cy=146.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g1_2", prompt="", cx=356.0, cy=146.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g1_3", prompt="", cx=388.0, cy=146.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g1_4", prompt="", cx=420.0, cy=146.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g2_1", prompt="", cx=324.0, cy=182.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g2_2", prompt="", cx=356.0, cy=182.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g2_3", prompt="", cx=388.0, cy=182.0, r=4.0, fill="#5B4A91"),
            CircleSlot(id="slot.tbl.g2_4", prompt="", cx=414.0, cy=182.0, r=4.0, fill="#5B4A91"),
            CircleSlot(id="slot.tbl.g2_5", prompt="", cx=440.0, cy=182.0, r=4.0, fill="#5B4A91"),
            CircleSlot(id="slot.tbl.g3_1", prompt="", cx=324.0, cy=240.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g3_2", prompt="", cx=356.0, cy=240.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g3_3", prompt="", cx=388.0, cy=240.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.tbl.g3_4", prompt="", cx=418.0, cy=240.0, r=4.0, fill="#5B4A91"),
            TextSlot(
                id="slot.leg1.txt",
                prompt="",
                text="10 kg",
                style_role="label",
                x=702.0,
                y=226.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.leg2.txt",
                prompt="",
                text="1 kg",
                style_role="label",
                x=702.0,
                y=258.0,
                font_size=28,
            ),
            CircleSlot(id="slot.leg.big", prompt="", cx=674.0, cy=218.0, r=13.0, fill="#7A6AAE"),
            CircleSlot(id="slot.leg.small", prompt="", cx=674.0, cy=252.0, r=4.0, fill="#5B4A91"),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 가 과수원 , 나 과수원 , 다 과수원 )",
                style_role="label",
                x=514.0,
                y=315.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008897",
    "problem_type": "그림그래프_비교",
    "metadata": {
        "language": "ko",
        "question": "과수원별 포도 생산량을 조사하여 나타낸 그림그래프에서 포도 생산량이 가장 많은 과수원을 찾는 문제",
        "instruction": "포도 생산량이 가장 많은 과수원을 선택해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.orchard.ga", "type": "orchard", "name": "가 과수원"},
            {"id": "obj.orchard.na", "type": "orchard", "name": "나 과수원"},
            {"id": "obj.orchard.da", "type": "orchard", "name": "다 과수원"},
            {"id": "obj.legend.big", "type": "symbol", "meaning": "10 kg"},
            {"id": "obj.legend.small", "type": "symbol", "meaning": "1 kg"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.legend.big",
                    "obj.legend.small",
                    "obj.orchard.ga",
                    "obj.orchard.na",
                    "obj.orchard.da",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare.production"],
            },
            "plan": {
                "method": "그림그래프_비교",
                "description": "각 과수원의 그림 개수와 범례의 뜻을 함께 읽어 가장 많은 과수원을 찾는다.",
            },
            "execute": {
                "expected_operations": ["그림_개수_비교", "범례_해석", "가장_많은_과수원_선택"]
            },
            "review": {
                "check_methods": ["그림이_가장_많이_표시된_행_확인", "하단_정답_표기_일치_확인"]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_orchard", "description": "포도 생산량이 가장 많은 과수원"},
        "value": "가 과수원",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008897",
    "problem_type": "그림그래프_비교",
    "inputs": {
        "total_ticks": 0,
        "target_label": "가장 많은 과수원",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "",
    },
    "given": [
        {"ref": "obj.legend.big", "value": "10 kg"},
        {"ref": "obj.legend.small", "value": "1 kg"},
        {"ref": "obj.orchard.ga", "value": "가 과수원"},
        {"ref": "obj.orchard.na", "value": "나 과수원"},
        {"ref": "obj.orchard.da", "value": "다 과수원"},
    ],
    "target": {"ref": "answer.target", "type": "selected_orchard"},
    "method": "그림그래프_비교",
    "plan": [
        "범례의 뜻을 읽는다.",
        "각 과수원 행의 그림을 비교한다.",
        "가장 많은 과수원을 선택한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "가 과수원은 큰 포도 그림 4개", "value": 4},
        {"id": "step.2", "expr": "나 과수원은 큰 포도 그림 2개와 작은 포도 그림 3개", "value": 5},
        {"id": "step.3", "expr": "다 과수원은 큰 포도 그림 3개와 작은 포도 그림 1개", "value": 4},
        {"id": "step.4", "expr": "가장 많은 과수원 선택", "value": "가 과수원"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "하단 정답 표기와 일치하는가",
            "expected": "가 과수원",
            "actual": "가 과수원",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_orchard", "description": "포도 생산량이 가장 많은 과수원"},
        "value": "가 과수원",
        "unit": "",
    },
}
