from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008917",
        title="존경하는 위인별 학생 수",
        canvas=Canvas(width=940.0, height=435.0, coordinate_mode="logical"),
        regions=(
            Region(id="region.stem", role="stem", flow="absolute", slot_ids=("slot.q1",)),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.table.title",
                    "slot.table.border",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.v5",
                    "slot.table.v6",
                    "slot.table.c11",
                    "slot.table.c12",
                    "slot.table.c13",
                    "slot.table.c14",
                    "slot.table.c15",
                    "slot.table.c16",
                    "slot.table.c21",
                    "slot.table.c22",
                    "slot.table.c23",
                    "slot.table.c24",
                    "slot.table.c25",
                    "slot.table.c26",
                ),
            ),
            Region(
                id="region.choices",
                role="choices",
                flow="absolute",
                slot_ids=("slot.choice.1", "slot.choice.2", "slot.choice.3", "slot.choice.4"),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="83. 은우이네 반 학생들이 존경하는 위인을 조사하여 표로 나타냈습니다. 가장 많은 학생들이 존경하는 위인은 누구인가요?",
                style_role="question",
                x=18.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.title",
                prompt="",
                text="존경하는 위인별 학생 수",
                style_role="title",
                x=357.0,
                y=84.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.border",
                prompt="",
                x=107.0,
                y=118.0,
                width=727.0,
                height=112.0,
                fill="#FFFFFF",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.h1",
                prompt="",
                x=107.0,
                y=118.0,
                width=727.0,
                height=38.0,
                fill="#DCE6C7",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.h2",
                prompt="",
                x=107.0,
                y=156.0,
                width=727.0,
                height=38.0,
                fill="#FFFFFF",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v1",
                prompt="",
                x=107.0,
                y=118.0,
                width=166.0,
                height=112.0,
                fill="none",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v2",
                prompt="",
                x=272.0,
                y=118.0,
                width=119.0,
                height=112.0,
                fill="none",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v3",
                prompt="",
                x=390.0,
                y=118.0,
                width=119.0,
                height=112.0,
                fill="none",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v4",
                prompt="",
                x=509.0,
                y=118.0,
                width=119.0,
                height=112.0,
                fill="none",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v5",
                prompt="",
                x=627.0,
                y=118.0,
                width=119.0,
                height=112.0,
                fill="none",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v6",
                prompt="",
                x=745.0,
                y=118.0,
                width=89.0,
                height=112.0,
                fill="none",
                stroke="#9ACB54",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.table.c11",
                prompt="",
                text="위인",
                style_role="label",
                x=162.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c12",
                prompt="",
                text="세종대왕",
                style_role="label",
                x=294.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c13",
                prompt="",
                text="김구",
                style_role="label",
                x=433.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c14",
                prompt="",
                text="이순신",
                style_role="label",
                x=544.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c15",
                prompt="",
                text="유관순",
                style_role="label",
                x=664.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c16",
                prompt="",
                text="합계",
                style_role="label",
                x=777.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c21",
                prompt="",
                text="학생 수(명)",
                style_role="label",
                x=142.0,
                y=179.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c22",
                prompt="",
                text="10",
                style_role="label",
                x=318.0,
                y=179.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c23",
                prompt="",
                text="3",
                style_role="label",
                x=439.0,
                y=179.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c24",
                prompt="",
                text="8",
                style_role="label",
                x=557.0,
                y=179.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c25",
                prompt="",
                text="6",
                style_role="label",
                x=676.0,
                y=179.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c26",
                prompt="",
                text="27",
                style_role="label",
                x=793.0,
                y=179.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 세종대왕",
                style_role="choice",
                x=26.0,
                y=244.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 김구",
                style_role="choice",
                x=499.0,
                y=244.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 이순신",
                style_role="choice",
                x=26.0,
                y=282.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 유관순",
                style_role="choice",
                x=499.0,
                y=282.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008917",
    "problem_type": "표에서최대값찾기",
    "metadata": {
        "language": "ko",
        "question": "표에서 가장 많은 학생들이 존경하는 위인을 찾는 문제",
        "instruction": "가장 많은 학생들이 존경하는 위인을 고르시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.sejong", "type": "person", "name": "세종대왕", "students": 10},
            {"id": "obj.kimgu", "type": "person", "name": "김구", "students": 3},
            {"id": "obj.leesunsin", "type": "person", "name": "이순신", "students": 8},
            {"id": "obj.yukgwansoon", "type": "person", "name": "유관순", "students": 6},
            {"id": "obj.total", "type": "aggregate", "name": "합계", "students": 27},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.sejong", "obj.kimgu", "obj.leesunsin", "obj.yukgwansoon"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.max_student_count"],
            },
            "plan": {
                "method": "최댓값비교",
                "description": "표의 위인별 학생 수를 서로 비교하여 가장 큰 값을 찾는다.",
            },
            "execute": {"expected_operations": ["compare_values", "identify_maximum"]},
            "review": {"check_methods": ["largest_count_matches_selected_person"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person", "description": "가장 많은 학생들이 존경하는 위인"},
        "value": "세종대왕",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008917",
    "problem_type": "표에서최대값찾기",
    "inputs": {
        "total_ticks": 27,
        "target_label": "가장 많은 학생들이 존경하는 위인",
        "target_ticks": 10,
        "target_count": 4,
        "unit": "명",
    },
    "given": [
        {"ref": "obj.sejong", "value": {"name": "세종대왕", "students": 10}},
        {"ref": "obj.kimgu", "value": {"name": "김구", "students": 3}},
        {"ref": "obj.leesunsin", "value": {"name": "이순신", "students": 8}},
        {"ref": "obj.yukgwansoon", "value": {"name": "유관순", "students": 6}},
        {"ref": "obj.total", "value": {"name": "합계", "students": 27}},
    ],
    "target": {"ref": "answer.target", "type": "person"},
    "method": "최댓값비교",
    "plan": ["표에 있는 위인별 학생 수를 비교한다.", "가장 큰 수를 가진 위인을 찾는다."],
    "steps": [
        {"id": "step.1", "expr": "10, 3, 8, 6 중 가장 큰 수를 찾는다", "value": 10},
        {"id": "step.2", "expr": "가장 큰 수 10에 대응하는 위인을 확인한다", "value": "세종대왕"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "10 >= 3 and 10 >= 8 and 10 >= 6",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "선택된 위인이 세종대왕인지 확인",
            "expected": "세종대왕",
            "actual": "세종대왕",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person", "description": "가장 많은 학생들이 존경하는 위인"},
        "value": "세종대왕",
        "unit": "",
    },
}
