from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008898",
        title="마을별 자동차 수",
        canvas=Canvas(width=940.0, height=473.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q_num",
                    "slot.q_text",
                    "slot.table_title",
                    "slot.table",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q_num",
                prompt="",
                text="□ 64.",
                style_role="question",
                x=18.0,
                y=22.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q_text",
                prompt="",
                text="마을별 자동차 수를 조사한 표입니다. 자동차가 많은 마을부터 순서대로\n나열한 것을 고르세요.",
                style_role="question",
                x=62.0,
                y=22.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table_title",
                prompt="",
                text="마을별 자동차 수",
                style_role="title",
                x=464.0,
                y=84.0,
                font_size=28,
            ),
            RectSlot(id="slot.table", prompt="", x=246.0, y=120.0, width=520.0, height=78.0),
            TextSlot(
                id="slot.table.header1",
                prompt="",
                text="마을",
                style_role="table",
                x=288.0,
                y=146.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.header2",
                prompt="",
                text="가",
                style_role="table",
                x=372.0,
                y=146.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.header3",
                prompt="",
                text="나",
                style_role="table",
                x=450.0,
                y=146.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.header4",
                prompt="",
                text="다",
                style_role="table",
                x=527.0,
                y=146.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.header5",
                prompt="",
                text="라",
                style_role="table",
                x=606.0,
                y=146.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.header6",
                prompt="",
                text="합계",
                style_role="table",
                x=700.0,
                y=146.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.rowlabel",
                prompt="",
                text="자동차 수(대)",
                style_role="table",
                x=262.0,
                y=183.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.v1",
                prompt="",
                text="18",
                style_role="table",
                x=377.0,
                y=183.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.v2",
                prompt="",
                text="35",
                style_role="table",
                x=455.0,
                y=183.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.v3",
                prompt="",
                text="42",
                style_role="table",
                x=533.0,
                y=183.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.v4",
                prompt="",
                text="26",
                style_role="table",
                x=611.0,
                y=183.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.total",
                prompt="",
                text="121",
                style_role="table",
                x=698.0,
                y=183.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 가 마을, 나 마을, 다 마을, 라 마을",
                style_role="choice",
                x=28.0,
                y=232.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 나 마을, 가 마을, 라 마을, 다 마을",
                style_role="choice",
                x=28.0,
                y=274.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 다 마을, 나 마을, 라 마을, 가 마을",
                style_role="choice",
                x=28.0,
                y=316.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 다 마을, 나 마을, 가 마을, 라 마을",
                style_role="choice",
                x=28.0,
                y=359.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008898",
    "problem_type": "ordering_by_quantity",
    "metadata": {
        "language": "ko",
        "question": "마을별 자동차 수를 비교하여 자동차가 많은 마을부터 순서대로 나열한 것을 고르는 문제",
        "instruction": "자동차가 많은 마을부터 순서대로 나열한 것을 고르세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.village.ga", "type": "village", "label": "가"},
            {"id": "obj.village.na", "type": "village", "label": "나"},
            {"id": "obj.village.da", "type": "village", "label": "다"},
            {"id": "obj.village.ra", "type": "village", "label": "라"},
            {"id": "obj.count.ga", "type": "quantity", "unit": "대", "value": 18},
            {"id": "obj.count.na", "type": "quantity", "unit": "대", "value": 35},
            {"id": "obj.count.da", "type": "quantity", "unit": "대", "value": 42},
            {"id": "obj.count.ra", "type": "quantity", "unit": "대", "value": 26},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.village.ga",
                    "obj.village.na",
                    "obj.village.da",
                    "obj.village.ra",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare"],
            },
            "plan": {
                "method": "compare_and_order",
                "description": "각 마을의 자동차 수를 비교해 많은 순서로 배열한다.",
            },
            "execute": {
                "expected_operations": [
                    "read_table_values",
                    "compare_quantities",
                    "order_descending",
                ]
            },
            "review": {"check_methods": ["ordering_consistency_check", "table_value_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "descending_order_of_villages",
            "description": "자동차가 많은 마을부터 순서대로 나열한 것",
        },
        "value": 3,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008898",
    "problem_type": "ordering_by_quantity",
    "inputs": {
        "total_ticks": 4,
        "target_label": "자동차가 많은 마을부터 순서대로 나열",
        "target_ticks": 4,
        "target_count": 4,
        "unit": "대",
    },
    "given": [
        {"ref": "obj.count.ga", "value": 18},
        {"ref": "obj.count.na", "value": 35},
        {"ref": "obj.count.da", "value": 42},
        {"ref": "obj.count.ra", "value": 26},
    ],
    "target": {"ref": "answer.target", "type": "descending_order_of_villages"},
    "method": "compare_and_order",
    "plan": [
        "마을별 자동차 수를 읽는다.",
        "수의 크기를 비교한다.",
        "큰 수부터 마을 이름을 순서대로 배열한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "가=18, 나=35, 다=42, 라=26",
            "value": {"가": 18, "나": 35, "다": 42, "라": 26},
        },
        {"id": "step.2", "expr": "42 > 35 > 26 > 18", "value": ["다", "나", "라", "가"]},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "정렬된 순서가 자동차 수의 내림차순인지 확인",
            "expected": ["다", "나", "라", "가"],
            "actual": ["다", "나", "라", "가"],
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "표의 수치와 대응이 일치하는지 확인",
            "expected": {"가": 18, "나": 35, "다": 42, "라": 26},
            "actual": {"가": 18, "나": 35, "다": 42, "라": 26},
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "descending_order_of_villages",
            "description": "자동차가 많은 마을부터 순서대로 나열한 것",
        },
        "value": 3,
        "unit": "",
    },
}
