from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008903",
        title="주말에 가고 싶은 장소별 남녀 학생 수",
        canvas=Canvas(width=940, height=440, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.qno",
                    "slot.qtext",
                    "slot.table.title",
                    "slot.table.frame",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.h3",
                    "slot.table.h4",
                    "slot.table.h5",
                    "slot.table.r1",
                    "slot.table.r2",
                    "slot.table.r3",
                    "slot.table.r4",
                    "slot.table.r5",
                    "slot.choices",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.qno",
                prompt="",
                text="69.",
                style_role="question",
                x=14.0,
                y=26.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.qtext",
                prompt="",
                text="영은이는 학교 학생들이 주말에 가고 싶은 장소를 남학생과 여학생으로 나누어 표로 나타내었습니다. 가장 많은 남학생이 가고 싶은 장소를 선택해 보세요.",
                style_role="question",
                x=52.0,
                y=26.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.title",
                prompt="",
                text="주말에 가고 싶은 장소별 남녀 학생 수",
                style_role="title",
                x=260.0,
                y=122.0,
                font_size=28,
            ),
            RectSlot(id="slot.table.frame", prompt="", x=138.0, y=153.0, width=708.0, height=115.0),
            TextSlot(
                id="slot.table.h1",
                prompt="",
                text="장소",
                style_role="table_header",
                x=184.0,
                y=176.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2",
                prompt="",
                text="동물원",
                style_role="table_header",
                x=288.0,
                y=176.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h3",
                prompt="",
                text="고궁",
                style_role="table_header",
                x=396.0,
                y=176.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h4",
                prompt="",
                text="영화관",
                style_role="table_header",
                x=500.0,
                y=176.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h5",
                prompt="",
                text="놀이공원",
                style_role="table_header",
                x=604.0,
                y=176.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1",
                prompt="",
                text="합계",
                style_role="table_header",
                x=726.0,
                y=176.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2",
                prompt="",
                text="남학생 수(명)",
                style_role="table_header",
                x=166.0,
                y=212.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r3",
                prompt="",
                text="여학생 수(명)",
                style_role="table_header",
                x=166.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r4",
                prompt="",
                text="27",
                style_role="table_value",
                x=288.0,
                y=212.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r5",
                prompt="",
                text="15",
                style_role="table_value",
                x=392.0,
                y=212.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r6",
                prompt="",
                text="42",
                style_role="table_value",
                x=496.0,
                y=212.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r7",
                prompt="",
                text="33",
                style_role="table_value",
                x=602.0,
                y=212.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r8",
                prompt="",
                text="117",
                style_role="table_value",
                x=716.0,
                y=212.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r9",
                prompt="",
                text="17",
                style_role="table_value",
                x=288.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r10",
                prompt="",
                text="26",
                style_role="table_value",
                x=392.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r11",
                prompt="",
                text="21",
                style_role="table_value",
                x=496.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r12",
                prompt="",
                text="39",
                style_role="table_value",
                x=602.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r13",
                prompt="",
                text="103",
                style_role="table_value",
                x=716.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choices",
                prompt="",
                text="( 동물원 , 고궁 , 영화관 , 놀이공원 )",
                style_role="note",
                x=491.0,
                y=301.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008903",
    "problem_type": "표에서 비교하기",
    "metadata": {
        "language": "ko",
        "question": "주말에 가고 싶은 장소별 남녀 학생 수를 보고 가장 많은 남학생이 가고 싶은 장소를 찾는 문제",
        "instruction": "가장 많은 남학생이 가고 싶은 장소를 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.place.zoo", "type": "place", "name": "동물원"},
            {"id": "obj.place.palace", "type": "place", "name": "고궁"},
            {"id": "obj.place.movie", "type": "place", "name": "영화관"},
            {"id": "obj.place.amusement", "type": "place", "name": "놀이공원"},
            {"id": "obj.group.boys", "type": "student_group", "name": "남학생"},
            {"id": "obj.group.girls", "type": "student_group", "name": "여학생"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.group.boys",
                    "obj.place.zoo",
                    "obj.place.palace",
                    "obj.place.movie",
                    "obj.place.amusement",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.table.boys_counts"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "남학생 수를 장소별로 비교하여 가장 큰 값을 찾는다.",
            },
            "execute": {"expected_operations": ["compare_values", "select_maximum"]},
            "review": {"check_methods": ["max_value_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "place_name", "description": "가장 많은 남학생이 가고 싶은 장소"},
        "value": "영화관",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008903",
    "problem_type": "표에서 비교하기",
    "inputs": {
        "total_ticks": 4,
        "target_label": "가장 많은 남학생이 가고 싶은 장소",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.place.zoo", "value": {"boys": 27, "girls": 17}},
        {"ref": "obj.place.palace", "value": {"boys": 15, "girls": 26}},
        {"ref": "obj.place.movie", "value": {"boys": 42, "girls": 21}},
        {"ref": "obj.place.amusement", "value": {"boys": 33, "girls": 39}},
    ],
    "target": {"ref": "answer.target", "type": "place_name"},
    "method": "compare_counts",
    "plan": [
        "남학생 수를 장소별로 확인한다.",
        "가장 큰 수를 찾는다.",
        "그 수에 대응하는 장소를 답으로 정한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "남학생 수: 27, 15, 42, 33", "value": [27, 15, 42, 33]},
        {"id": "step.2", "expr": "최댓값 찾기", "value": 42},
        {"id": "step.3", "expr": "42명에 대응하는 장소", "value": "영화관"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "영화관의 남학생 수가 42명인지 확인",
            "expected": 42,
            "actual": 42,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "다른 장소의 남학생 수보다 큰지 확인",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "place_name", "description": "가장 많은 남학생이 가고 싶은 장소"},
        "value": "영화관",
        "unit": "",
    },
}
