from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008824', title='들이의 단위', canvas=Canvas(width=952.0, height=442.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.qnum', 'slot.qtext')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.bottle.body', 'slot.bottle.cap', 'slot.bottle.label', 'slot.bottle.unit', 'slot.zoom.circle', 'slot.zoom.text', 'slot.link.top', 'slot.link.bottom')), Region(id='region.choice', role='choice', flow='absolute', slot_ids=('slot.choice',)), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.qnum', prompt='', text='58.', style_role='question', x=20.0, y=32.0, font_size=28), TextSlot(id='slot.qtext', prompt='', text='물건에 표시되어 있는 들이의 단위를 알아보려고 합니다. 알맞은 것을 선택하세요.', style_role='question', x=60.0, y=32.0, font_size=28), RectSlot(id='slot.bottle.body', prompt='', x=357.0, y=99.0, width=61.0, height=144.0), RectSlot(id='slot.bottle.cap', prompt='', x=370.0, y=83.0, width=35.0, height=17.0), TextSlot(id='slot.bottle.label', prompt='', text='샴푸', style_role='label', x=372.0, y=132.0, font_size=28), TextSlot(id='slot.bottle.unit', prompt='', text='1L', style_role='label', x=375.0, y=204.0, font_size=24), CircleSlot(id='slot.zoom.circle', prompt='', cx=566.0, cy=148.0, r=57.0, fill='#FFFFFF'), TextSlot(id='slot.zoom.text', prompt='', text='1L', style_role='label', x=543.0, y=158.0, font_size=52), LineSlot(id='slot.link.top', prompt='', x1=391.0, y1=190.0, x2=511.0, y2=112.0), LineSlot(id='slot.link.bottom', prompt='', x1=396.0, y1=223.0, x2=506.0, y2=223.0), TextSlot(id='slot.choice', prompt='', text='샴푸통에 표시되어 있는 단위는 ( L , mL )입니다.', style_role='question', x=183.0, y=308.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008824', 'problem_type': '단위_판별', 'metadata': {'language': 'ko', 'question': '물건에 표시되어 있는 들이의 단위를 알아보려고 합니다. 알맞은 것을 선택하세요.', 'instruction': '샴푸통에 표시되어 있는 단위를 고르기'}, 'domain': {'objects': [{'id': 'obj.shampoo', 'type': 'container', 'name': '샴푸통'}, {'id': 'obj.marked_value', 'type': 'volume_label', 'value_text': '1L'}, {'id': 'obj.options', 'type': 'choices', 'candidates': ['L', 'mL']}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.shampoo', 'obj.marked_value', 'obj.options'], 'target_ref': 'answer.target', 'condition_refs': ['rel.shown_unit']}, 'plan': {'method': 'label_reading', 'description': '그림에 적힌 들이 표기를 읽고 보기에서 같은 단위를 고른다.'}, 'execute': {'expected_operations': ['read_marked_unit', 'match_to_choice']}, 'review': {'check_methods': ['compare_with_visible_label', 'confirm_explanation_consistency']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_unit', 'description': '샴푸통에 표시되어 있는 단위'}, 'value': 'L', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008824', 'problem_type': '단위_판별', 'inputs': {'total_ticks': 1, 'target_label': 'L', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.marked_value', 'value': '1L'}, {'ref': 'obj.options', 'value': ['L', 'mL']}], 'target': {'ref': 'answer.target', 'type': 'selected_unit'}, 'method': 'label_reading', 'plan': ['그림에 적힌 1L를 읽어 단위를 확인한다.', '보기 중 같은 단위인 L을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '표시된 값 읽기', 'value': '1L'}, {'id': 'step.2', 'expr': '1L의 단위 확인', 'value': 'L'}], 'checks': [{'id': 'check.1', 'expr': '그림의 표기와 선택한 단위가 같은가', 'expected': 'L', 'actual': 'L', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_unit', 'description': '샴푸통에 표시되어 있는 단위'}, 'value': 'L', 'unit': ''}}
