from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008722",
        title="원을 그린 규칙을 바르게 설명한 친구의 이름을 선택하세요",
        canvas=Canvas(width=960, height=540, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q2",
                    "slot.desc_box",
                    "slot.choice",
                    "slot.graphpaper.v0",
                    "slot.graphpaper.v1",
                    "slot.graphpaper.v2",
                    "slot.graphpaper.v3",
                    "slot.graphpaper.v4",
                    "slot.graphpaper.v5",
                    "slot.graphpaper.v6",
                    "slot.graphpaper.v7",
                    "slot.graphpaper.v8",
                    "slot.graphpaper.v9",
                    "slot.graphpaper.v10",
                    "slot.graphpaper.v11",
                    "slot.graphpaper.v12",
                    "slot.graphpaper.v13",
                    "slot.graphpaper.v14",
                    "slot.graphpaper.v15",
                    "slot.graphpaper.v16",
                    "slot.graphpaper.h0",
                    "slot.graphpaper.h1",
                    "slot.graphpaper.h2",
                    "slot.graphpaper.h3",
                    "slot.graphpaper.h4",
                    "slot.graphpaper.h5",
                    "slot.graphpaper.h6",
                    "slot.graphpaper.h7",
                    "slot.graphpaper.h8",
                    "slot.graphpaper.h9",
                    "slot.graphpaper.h10",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q2",
                prompt="",
                text="원을 그린 규칙을 바르게 설명한 친구의 이름을 선택하세요.",
                style_role="question",
                x=30,
                y=35,
                font_size=30,
            ),
            CircleSlot(
                id="slot.circle.l1",
                prompt="",
                cx=276,
                cy=190,
                r=25,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.circle.l2",
                prompt="",
                cx=351,
                cy=190,
                r=75,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.circle.c1",
                prompt="",
                cx=426,
                cy=190,
                r=25,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.circle.r2",
                prompt="",
                cx=500,
                cy=190,
                r=75,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.circle.r1",
                prompt="",
                cx=574,
                cy=190,
                r=25,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.l",
                prompt="",
                cx=276,
                cy=190,
                r=4,
                fill="#d81b88",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.a",
                prompt="",
                cx=351,
                cy=190,
                r=4,
                fill="#d81b88",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.c",
                prompt="",
                cx=426,
                cy=190,
                r=4,
                fill="#d81b88",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.d",
                prompt="",
                cx=502,
                cy=190,
                r=4,
                fill="#d81b88",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.r",
                prompt="",
                cx=576,
                cy=190,
                r=4,
                fill="#d81b88",
                stroke="#111111",
                stroke_width=2,
            ),
            RectSlot(id="slot.desc_box", prompt="", x=20, y=355, width=900, height=105),
            TextSlot(
                id="slot.desc1",
                prompt="",
                text="· 윤지: 원의 중심이 오른쪽으로 모눈 3칸씩 옮겨 갔어.",
                style_role="body",
                x=30,
                y=395,
                font_size=30,
            ),
            TextSlot(
                id="slot.desc2",
                prompt="",
                text="· 수진: 원의 반지름이 모눈 1칸, 2칸인 원을 반복하여 겹치도록 그렸어.",
                style_role="body",
                x=30,
                y=440,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 윤지 , 수진 )",
                style_role="body",
                x=365,
                y=495,
                font_size=30,
            ),
            LineSlot(
                id="slot.graphpaper.v0",
                prompt="",
                x1=225,
                y1=65,
                x2=225,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v1",
                prompt="",
                x1=250,
                y1=65,
                x2=250,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v2",
                prompt="",
                x1=275,
                y1=65,
                x2=275,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v3",
                prompt="",
                x1=300,
                y1=65,
                x2=300,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v4",
                prompt="",
                x1=325,
                y1=65,
                x2=325,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v5",
                prompt="",
                x1=350,
                y1=65,
                x2=350,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v6",
                prompt="",
                x1=375,
                y1=65,
                x2=375,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v7",
                prompt="",
                x1=400,
                y1=65,
                x2=400,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v8",
                prompt="",
                x1=425,
                y1=65,
                x2=425,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v9",
                prompt="",
                x1=450,
                y1=65,
                x2=450,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v10",
                prompt="",
                x1=475,
                y1=65,
                x2=475,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v11",
                prompt="",
                x1=500,
                y1=65,
                x2=500,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v12",
                prompt="",
                x1=525,
                y1=65,
                x2=525,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v13",
                prompt="",
                x1=550,
                y1=65,
                x2=550,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v14",
                prompt="",
                x1=575,
                y1=65,
                x2=575,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v15",
                prompt="",
                x1=600,
                y1=65,
                x2=600,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v16",
                prompt="",
                x1=625,
                y1=65,
                x2=625,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h0",
                prompt="",
                x1=225,
                y1=65,
                x2=625,
                y2=65,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h1",
                prompt="",
                x1=225,
                y1=90,
                x2=625,
                y2=90,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h2",
                prompt="",
                x1=225,
                y1=115,
                x2=625,
                y2=115,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h3",
                prompt="",
                x1=225,
                y1=140,
                x2=625,
                y2=140,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h4",
                prompt="",
                x1=225,
                y1=165,
                x2=625,
                y2=165,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h5",
                prompt="",
                x1=225,
                y1=190,
                x2=625,
                y2=190,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h6",
                prompt="",
                x1=225,
                y1=215,
                x2=625,
                y2=215,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h7",
                prompt="",
                x1=225,
                y1=240,
                x2=625,
                y2=240,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h8",
                prompt="",
                x1=225,
                y1=265,
                x2=625,
                y2=265,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h9",
                prompt="",
                x1=225,
                y1=290,
                x2=625,
                y2=290,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h10",
                prompt="",
                x1=225,
                y1=315,
                x2=625,
                y2=315,
                stroke="#2563eb",
                stroke_width=1,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008722",
    "problem_type": "도형_규칙_판단",
    "metadata": {
        "language": "ko",
        "question": "원을 그린 규칙을 바르게 설명한 친구의 이름을 선택하세요.",
        "instruction": "그림과 설명을 비교하여 알맞은 친구의 이름을 고른다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.diagram", "type": "circle_pattern"},
            {"id": "obj.yunji_statement", "type": "rule_statement", "speaker": "윤지"},
            {"id": "obj.sujin_statement", "type": "rule_statement", "speaker": "수진"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.diagram",
                    "obj.yunji_statement",
                    "obj.sujin_statement",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_rules"],
            },
            "plan": {
                "method": "rule_matching",
                "description": "그림의 원 배열 규칙과 각 친구의 설명이 일치하는지 비교한다.",
            },
            "execute": {
                "expected_operations": [
                    "inspect_circle_spacing",
                    "compare_center_shift",
                    "compare_radius_pattern",
                ]
            },
            "review": {"check_methods": ["statement_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "correct_friend_name",
            "description": "원을 그린 규칙을 바르게 설명한 친구의 이름",
        },
        "value": "윤지",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008722",
    "problem_type": "도형_규칙_판단",
    "inputs": {
        "total_ticks": 0,
        "target_label": "친구의 이름",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.diagram", "value": {"kind": "circle_pattern"}},
        {
            "ref": "obj.yunji_statement",
            "value": {"speaker": "윤지", "statement": "원의 중심이 오른쪽으로 모눈 3칸씩 옮겨 갔어."},
        },
        {
            "ref": "obj.sujin_statement",
            "value": {
                "speaker": "수진",
                "statement": "원의 반지름이 모눈 1칸, 2칸인 원을 반복하여 겹치도록 그렸어.",
            },
        },
    ],
    "target": {"ref": "answer.target", "type": "correct_friend_name"},
    "method": "rule_matching",
    "plan": [
        "그림에서 원의 배치 규칙을 보고 각 설명과 맞는지 비교한다.",
        "정확한 판정이 가능한 부분만 반영하고, 불확실한 부분은 TODO로 남긴다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "그림의 원 배치 규칙 확인", "value": "TODO"},
        {"id": "step.2", "expr": "윤지 설명과 그림 비교", "value": "TODO"},
        {"id": "step.3", "expr": "수진 설명과 그림 비교", "value": "TODO"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "설명과 그림의 규칙이 일치하는지 비교",
            "expected": "TODO",
            "actual": "TODO",
            "pass": False,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "correct_friend_name",
            "description": "원을 그린 규칙을 바르게 설명한 친구의 이름",
        },
        "value": "윤지",
        "unit": "",
    },
}
