from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    LineSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008631",
        title="수 모형을 보고 알맞은 수 고르기",
        canvas=Canvas(width=720, height=560, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.big_box",
                    "slot.big_rod1",
                    "slot.big_rod2",
                    "slot.big_rod3",
                    "slot.big_rod4",
                    "slot.big_rod5",
                    "slot.big_rod6",
                    "slot.big_cube1",
                    "slot.big_cube2",
                    "slot.big_cube3",
                    "slot.big_cube4",
                    "slot.big_cube5",
                    "slot.big_cube6",
                    "slot.big_cube7",
                    "slot.big_cube8",
                    "slot.arrow",
                    "slot.small_box1",
                    "slot.small_box2",
                    "slot.small_box3",
                    "slot.s1_rod1",
                    "slot.s1_rod2",
                    "slot.s1_cube1",
                    "slot.s1_cube2",
                    "slot.s1_cube3",
                    "slot.s2_rod1",
                    "slot.s2_rod2",
                    "slot.s2_cube1",
                    "slot.s2_cube2",
                    "slot.s2_cube3",
                    "slot.s3_rod1",
                    "slot.s3_rod2",
                    "slot.s3_cube1",
                    "slot.s3_cube2",
                    "slot.s3_cube3",
                    "slot.equation",
                    "slot.blank",
                ),
            ),
            Region(
                id="region.options",
                role="options",
                flow="absolute",
                slot_ids=(
                    "slot.opt1_num",
                    "slot.opt1_text",
                    "slot.opt2_num",
                    "slot.opt2_text",
                    "slot.opt3_num",
                    "slot.opt3_text",
                    "slot.opt4_num",
                    "slot.opt4_text",
                    "slot.opt5_num",
                    "slot.opt5_text",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="□",
                style_role="question",
                x=20.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="2. 수 모형을 보고 □ 안에 알맞은 수를 고르세요.",
                style_role="question",
                x=50.0,
                y=28.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.big_box",
                prompt="",
                x=360.0,
                y=52.0,
                width=246.0,
                height=96.0,
                fill="none",
                stroke="#4A78B8",
            ),
            RectSlot(
                id="slot.big_rod1",
                prompt="",
                x=380.0,
                y=66.0,
                width=10.0,
                height=72.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_rod2",
                prompt="",
                x=404.0,
                y=66.0,
                width=10.0,
                height=72.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_rod3",
                prompt="",
                x=428.0,
                y=66.0,
                width=10.0,
                height=72.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_rod4",
                prompt="",
                x=452.0,
                y=66.0,
                width=10.0,
                height=72.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_rod5",
                prompt="",
                x=476.0,
                y=66.0,
                width=10.0,
                height=72.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_rod6",
                prompt="",
                x=500.0,
                y=66.0,
                width=10.0,
                height=72.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube1",
                prompt="",
                x=526.0,
                y=70.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube2",
                prompt="",
                x=546.0,
                y=70.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube3",
                prompt="",
                x=526.0,
                y=90.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube4",
                prompt="",
                x=546.0,
                y=90.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube5",
                prompt="",
                x=526.0,
                y=110.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube6",
                prompt="",
                x=546.0,
                y=110.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube7",
                prompt="",
                x=526.0,
                y=130.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.big_cube8",
                prompt="",
                x=546.0,
                y=130.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            LineSlot(
                id="slot.arrow",
                prompt="",
                x1=483.0,
                y1=150.0,
                x2=483.0,
                y2=185.0,
                stroke="#888888",
            ),
            RectSlot(
                id="slot.small_box1",
                prompt="",
                x=300.0,
                y=206.0,
                width=84.0,
                height=128.0,
                fill="none",
                stroke="#4A78B8",
            ),
            RectSlot(
                id="slot.small_box2",
                prompt="",
                x=404.0,
                y=206.0,
                width=84.0,
                height=128.0,
                fill="none",
                stroke="#4A78B8",
            ),
            RectSlot(
                id="slot.small_box3",
                prompt="",
                x=508.0,
                y=206.0,
                width=84.0,
                height=128.0,
                fill="none",
                stroke="#4A78B8",
            ),
            RectSlot(
                id="slot.s1_rod1",
                prompt="",
                x=312.0,
                y=220.0,
                width=10.0,
                height=82.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s1_rod2",
                prompt="",
                x=332.0,
                y=220.0,
                width=10.0,
                height=82.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s1_cube1",
                prompt="",
                x=348.0,
                y=250.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s1_cube2",
                prompt="",
                x=348.0,
                y=270.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s1_cube3",
                prompt="",
                x=348.0,
                y=290.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s2_rod1",
                prompt="",
                x=416.0,
                y=220.0,
                width=10.0,
                height=82.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s2_rod2",
                prompt="",
                x=436.0,
                y=220.0,
                width=10.0,
                height=82.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s2_cube1",
                prompt="",
                x=452.0,
                y=250.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s2_cube2",
                prompt="",
                x=452.0,
                y=270.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s2_cube3",
                prompt="",
                x=452.0,
                y=290.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s3_rod1",
                prompt="",
                x=520.0,
                y=220.0,
                width=10.0,
                height=82.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s3_rod2",
                prompt="",
                x=540.0,
                y=220.0,
                width=10.0,
                height=82.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s3_cube1",
                prompt="",
                x=556.0,
                y=250.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s3_cube2",
                prompt="",
                x=556.0,
                y=270.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            RectSlot(
                id="slot.s3_cube3",
                prompt="",
                x=556.0,
                y=290.0,
                width=10.0,
                height=10.0,
                fill="none",
                stroke="#6BBCE8",
            ),
            TextSlot(
                id="slot.equation",
                prompt="",
                text="69 ÷ 3 =",
                style_role="question",
                x=380.0,
                y=362.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.blank",
                prompt="",
                x=530.0,
                y=338.0,
                width=26.0,
                height=26.0,
                fill="none",
                stroke="#222222",
            ),
            CircleSlot(
                id="slot.opt1_num", prompt="", cx=44.0, cy=423.0, r=7.0, fill="none"
            ),
            TextSlot(
                id="slot.opt1_text",
                prompt="",
                text="21",
                style_role="choice",
                x=58.0,
                y=430.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt2_num", prompt="", cx=320.0, cy=423.0, r=7.0, fill="none"
            ),
            TextSlot(
                id="slot.opt2_text",
                prompt="",
                text="22",
                style_role="choice",
                x=334.0,
                y=430.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt3_num", prompt="", cx=584.0, cy=423.0, r=7.0, fill="none"
            ),
            TextSlot(
                id="slot.opt3_text",
                prompt="",
                text="23",
                style_role="choice",
                x=598.0,
                y=430.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt4_num", prompt="", cx=44.0, cy=462.0, r=7.0, fill="none"
            ),
            TextSlot(
                id="slot.opt4_text",
                prompt="",
                text="24",
                style_role="choice",
                x=58.0,
                y=469.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt5_num", prompt="", cx=320.0, cy=462.0, r=7.0, fill="none"
            ),
            TextSlot(
                id="slot.opt5_text",
                prompt="",
                text="25",
                style_role="choice",
                x=334.0,
                y=469.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008631",
    "problem_type": "multiple_choice_division",
    "metadata": {
        "language": "ko",
        "question": "수 모형을 보고 □ 안에 알맞은 수를 고르세요.",
        "instruction": "수 모형과 나눗셈 식을 보고 알맞은 값을 고르는 문제",
    },
    "domain": {
        "objects": [
            {"id": "obj.dividend", "type": "number", "value": 69},
            {"id": "obj.divisor", "type": "number", "value": 3},
            {"id": "obj.blank", "type": "answer_blank"},
            {"id": "obj.options", "type": "choices", "values": [21, 22, 23, 24, 25]},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.dividend", "obj.divisor", "obj.options"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.division"],
            },
            "plan": {
                "method": "division_value_selection",
                "description": "나눗셈의 결과를 구해 보기 중 알맞은 값을 고른다.",
            },
            "execute": {"expected_operations": ["compute_69_div_3", "match_option"]},
            "review": {
                "check_methods": ["division_inverse_check", "option_match_check"]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "division_quotient", "description": "69 ÷ 3의 몫"},
        "value": 23,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008631",
    "problem_type": "multiple_choice_division",
    "inputs": {
        "total_ticks": 69,
        "target_label": "몫",
        "target_ticks": 3,
        "target_count": 1,
        "unit": "",
    },
    "plan": ["69를 3으로 나눈 몫을 구한다.", "보기 중 계산 결과와 같은 수를 찾는다."],
    "given": [
        {"ref": "obj.dividend", "value": 69},
        {"ref": "obj.divisor", "value": 3},
        {"ref": "obj.options", "value": [21, 22, 23, 24, 25]},
    ],
    "target": {"ref": "answer.target", "type": "division_quotient"},
    "method": "division_value_selection",
    "steps": [
        {"id": "step.1", "expr": "69 ÷ 3", "value": 23},
        {"id": "step.2", "expr": "보기에서 23 찾기", "value": 3},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "23 × 3 = 69",
            "expected": 69,
            "actual": 69,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "division_quotient", "description": "69 ÷ 3의 몫"},
        "value": 23,
        "unit": "",
    },
}
