from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008737",
        title="털실 길이 비교",
        canvas=Canvas(width=960, height=540, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.top",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.math.fraction.num",
                    "slot.math.fraction.bar",
                    "slot.math.fraction.den",
                    "slot.math.fraction_1.num",
                    "slot.math.fraction_1.bar",
                    "slot.math.fraction_1.den",
                    "slot.math.fraction_2.num",
                    "slot.math.fraction_2.bar",
                    "slot.math.fraction_2.den",
                    "slot.math.fraction_3.num",
                    "slot.math.fraction_3.bar",
                    "slot.math.fraction_3.den",
                    "slot.math.fraction_4.num",
                    "slot.math.fraction_4.bar",
                    "slot.math.fraction_4.den",
                    "slot.math.mixed_fraction.whole",
                    "slot.math.mixed_fraction.num",
                    "slot.math.mixed_fraction.bar",
                    "slot.math.mixed_fraction.den",
                    "slot.math.mixed_fraction_1.whole",
                    "slot.math.mixed_fraction_1.num",
                    "slot.math.mixed_fraction_1.bar",
                    "slot.math.mixed_fraction_1.den",
                    "slot.math.mixed_fraction_2.whole",
                    "slot.math.mixed_fraction_2.num",
                    "slot.math.mixed_fraction_2.bar",
                    "slot.math.mixed_fraction_2.den",
                    "slot.q1.copy1",
                    "slot.q1.copy1.copy3",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="재영이는 노란색 털실을",
                style_role="question",
                x=32,
                y=49,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="있습니다. 더 긴 털실은 무슨 색인지 알아보려고 합니다. 물음에 답하세요.",
                style_role="question",
                x=30,
                y=102,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="(1) 수직선을 보고, 더 큰 수를 선택해 보세요.",
                style_role="question",
                x=30,
                y=152,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.math.fraction.num",
                prompt="",
                text="9",
                x=(((480) + (125.0)) + (70.0)) + (-345.0),
                y=(((255) + (-100.0)) + (65.0)) + (-195.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction.bar",
                prompt="",
                x1=(((460) + (125.0)) + (70.0)) + (-345.0),
                y1=(((270) + (-100.0)) + (65.0)) + (-195.0),
                x2=(((500) + (125.0)) + (70.0)) + (-345.0),
                y2=(((270) + (-100.0)) + (65.0)) + (-195.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction.den",
                prompt="",
                text="7",
                x=(((480) + (125.0)) + (70.0)) + (-345.0),
                y=(((295) + (-100.0)) + (65.0)) + (-195.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_1.num",
                prompt="",
                text="9",
                x=((480) + (175.0)) + (70.0),
                y=((255) + (-100.0)) + (65.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_1.bar",
                prompt="",
                x1=((460) + (175.0)) + (70.0),
                y1=((270) + (-100.0)) + (65.0),
                x2=((500) + (175.0)) + (70.0),
                y2=((270) + (-100.0)) + (65.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_1.den",
                prompt="",
                text="7",
                x=((480) + (175.0)) + (70.0),
                y=((295) + (-100.0)) + (65.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_2.num",
                prompt="",
                text="9",
                x=(((480) + (235.0)) + (70.0)) + (100.0),
                y=(((255) + (-105.0)) + (65.0)) + (-40.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_2.bar",
                prompt="",
                x1=(((460) + (235.0)) + (70.0)) + (100.0),
                y1=(((270) + (-105.0)) + (65.0)) + (-40.0),
                x2=(((500) + (235.0)) + (70.0)) + (100.0),
                y2=(((270) + (-105.0)) + (65.0)) + (-40.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_2.den",
                prompt="",
                text="7",
                x=(((480) + (235.0)) + (70.0)) + (100.0),
                y=(((295) + (-105.0)) + (65.0)) + (-40.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_3.num",
                prompt="",
                text="7",
                x=((480) + (290.0)) + (70.0),
                y=((255) + (-105.0)) + (65.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_3.bar",
                prompt="",
                x1=((460) + (290.0)) + (70.0),
                y1=((270) + (-105.0)) + (65.0),
                x2=((500) + (290.0)) + (70.0),
                y2=((270) + (-105.0)) + (65.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_3.den",
                prompt="",
                text="7",
                x=((480) + (290.0)) + (70.0),
                y=((295) + (-105.0)) + (65.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_4.num",
                prompt="",
                text="7",
                x=((480) + (340.0)) + (-20.0),
                y=((255) + (-110.0)) + (140.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_4.bar",
                prompt="",
                x1=((460) + (340.0)) + (-20.0),
                y1=((270) + (-110.0)) + (140.0),
                x2=((500) + (340.0)) + (-20.0),
                y2=((270) + (-110.0)) + (140.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_4.den",
                prompt="",
                text="7",
                x=((480) + (340.0)) + (-20.0),
                y=((295) + (-110.0)) + (140.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction.whole",
                prompt="",
                text="1",
                x=(((455) + (340.0)) + (70.0)) + (-145.0),
                y=((((280) + (-30.0)) + (65.0)) + (-270.0)) + (5.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction.num",
                prompt="",
                text="3",
                x=(((495) + (340.0)) + (70.0)) + (-145.0),
                y=((((255) + (-30.0)) + (65.0)) + (-270.0)) + (5.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction.bar",
                prompt="",
                x1=(((475) + (340.0)) + (70.0)) + (-145.0),
                y1=((((270) + (-30.0)) + (65.0)) + (-270.0)) + (5.0),
                x2=(((515) + (340.0)) + (70.0)) + (-145.0),
                y2=((((270) + (-30.0)) + (65.0)) + (-270.0)) + (5.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction.den",
                prompt="",
                text="7",
                x=(((495) + (340.0)) + (70.0)) + (-145.0),
                y=((((295) + (-30.0)) + (65.0)) + (-270.0)) + (5.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.whole",
                prompt="",
                text="1",
                x=(455) + (360.0),
                y=((280) + (15.0)) + (140.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.num",
                prompt="",
                text="3",
                x=(495) + (360.0),
                y=((255) + (15.0)) + (140.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction_1.bar",
                prompt="",
                x1=(475) + (360.0),
                y1=((270) + (15.0)) + (140.0),
                x2=(515) + (360.0),
                y2=((270) + (15.0)) + (140.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.den",
                prompt="",
                text="7",
                x=(495) + (360.0),
                y=((295) + (15.0)) + (140.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_2.whole",
                prompt="",
                text="1",
                x=(455) + (360.0),
                y=(280) + (75.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_2.num",
                prompt="",
                text="3",
                x=(495) + (360.0),
                y=(255) + (75.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction_2.bar",
                prompt="",
                x1=(475) + (360.0),
                y1=(270) + (75.0),
                x2=(515) + (360.0),
                y2=(270) + (75.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction_2.den",
                prompt="",
                text="7",
                x=(495) + (360.0),
                y=(295) + (75.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.q1.copy1",
                prompt="",
                text="m 가지고 있고 보라색 털실을",
                x=357,
                y=49,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q1.copy1.copy3",
                prompt="",
                text="m 가지고",
                x=787,
                y=49,
                font_size=28,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008737",
    "problem_type": "fraction_comparison",
    "metadata": {
        "language": "ko",
        "question": "두 털실의 길이를 수직선으로 비교하여 더 큰 수를 찾는 문제",
        "instruction": "수직선을 보고 더 큰 수를 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.yellow_yarn", "type": "length", "value": "9/7 m", "color": "노란색"},
            {"id": "obj.purple_yarn", "type": "length", "value": "1 3/7 m", "color": "보라색"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.yellow_yarn", "obj.purple_yarn"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_lengths"],
            },
            "plan": {
                "method": "number_line_comparison",
                "description": "수직선에서 두 길이의 위치를 비교한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_positions_on_number_line",
                    "identify_larger_length",
                ]
            },
            "review": {"check_methods": ["position_order_check", "unit_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "larger_length_color", "description": "더 긴 털실의 색"},
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008737",
    "problem_type": "fraction_comparison",
    "inputs": {
        "total_ticks": 14,
        "target_label": "더 긴 털실의 색",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "m",
    },
    "given": [
        {"ref": "obj.yellow_yarn", "value": "9/7 m"},
        {"ref": "obj.purple_yarn", "value": "1 3/7 m"},
    ],
    "target": {"ref": "answer.target", "type": "larger_length_color"},
    "method": "number_line_comparison",
    "plan": ["수직선에서 두 수의 위치를 비교한다.", "더 오른쪽에 있는 수가 더 크다."],
    "steps": [
        {"id": "step.1", "expr": "9/7과 1 3/7의 위치를 수직선에서 비교한다", "value": 0},
        {"id": "step.2", "expr": "9/7 < 1 3/7", "value": 1},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "수직선 비교 결과가 더 큰 수를 오른쪽 값으로 선택하는지 확인",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "larger_length_color", "description": "더 긴 털실의 색"},
        "value": 0,
        "unit": "",
    },
}
