from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008775",
        title="누가 물을 더 많이 마셨나요",
        canvas=Canvas(width=940.0, height=469.0, coordinate_mode="logical"),
        regions=(
            Region(id="region.stem", role="stem", flow="absolute", slot_ids=("slot.q1", "slot.q2")),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.tbl.bg",
                    "slot.tbl.c1",
                    "slot.tbl.c2",
                    "slot.tbl.r1",
                    "slot.tbl.r2",
                    "slot.tbl.h1",
                    "slot.tbl.h2",
                    "slot.tbl.v1",
                    "slot.tbl.v2",
                ),
            ),
            Region(id="region.foot", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="87. 수경이와 현준이가 물을 마셨습니다. 마시기 전과 마신 후의 물의 양은",
                style_role="question",
                x=18.0,
                y=18.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="다음과 같습니다. 누가 물을 더 많이 마셨나요?",
                style_role="question",
                x=18.0,
                y=58.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.tbl.bg",
                prompt="",
                x=227.0,
                y=86.0,
                width=531.0,
                height=126.0,
                fill="#F2E8D9",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.c1",
                prompt="",
                x=227.0,
                y=86.0,
                width=151.0,
                height=41.0,
                fill="#F2E8D9",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.c2",
                prompt="",
                x=378.0,
                y=86.0,
                width=180.0,
                height=41.0,
                fill="#F2E8D9",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.r1",
                prompt="",
                x=558.0,
                y=86.0,
                width=200.0,
                height=41.0,
                fill="#F2E8D9",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.r2",
                prompt="",
                x=227.0,
                y=127.0,
                width=151.0,
                height=41.0,
                fill="#F2E8D9",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.h1",
                prompt="",
                x=227.0,
                y=168.0,
                width=151.0,
                height=44.0,
                fill="#F2E8D9",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.h2",
                prompt="",
                x=378.0,
                y=168.0,
                width=180.0,
                height=44.0,
                fill="#FFFFFF",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.v1",
                prompt="",
                x=558.0,
                y=168.0,
                width=200.0,
                height=44.0,
                fill="#FFFFFF",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.tbl.v2",
                prompt="",
                x=227.0,
                y=86.0,
                width=531.0,
                height=126.0,
                fill="none",
                stroke="#D7B38A",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.tbl.c1t",
                prompt="",
                text="",
                style_role="table",
                x=320.0,
                y=116.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c2t",
                prompt="",
                text="수경",
                style_role="table",
                x=455.0,
                y=116.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.r1t",
                prompt="",
                text="현준",
                style_role="table",
                x=639.0,
                y=116.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.h1t",
                prompt="",
                text="마시기 전",
                style_role="table",
                x=259.0,
                y=156.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.h2t",
                prompt="",
                text="2 L 500 mL",
                style_role="table",
                x=411.0,
                y=156.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.v1t",
                prompt="",
                text="2 L",
                style_role="table",
                x=631.0,
                y=156.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.h2b",
                prompt="",
                text="마신 후",
                style_role="table",
                x=259.0,
                y=198.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.v2t",
                prompt="",
                text="2 L 100 mL",
                style_role="table",
                x=410.0,
                y=198.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.v3t",
                prompt="",
                text="1 L 400 mL",
                style_role="table",
                x=626.0,
                y=198.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.note",
                prompt="",
                text="( 수경 , 현준 )",
                style_role="note",
                x=744.0,
                y=244.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008775",
    "problem_type": "comparison",
    "metadata": {
        "language": "ko",
        "question": "수경이와 현준이가 물을 마셨습니다. 마시기 전과 마신 후의 물의 양은 다음과 같습니다. 누가 물을 더 많이 마셨나요?",
        "instruction": "누가 물을 더 많이 마셨는지 구하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.sugyeong", "type": "person", "name": "수경"},
            {"id": "obj.hyeonjun", "type": "person", "name": "현준"},
            {
                "id": "obj.sugyeong_before",
                "type": "amount",
                "person": "obj.sugyeong",
                "state": "before",
                "value": "2 L 500 mL",
            },
            {
                "id": "obj.sugyeong_after",
                "type": "amount",
                "person": "obj.sugyeong",
                "state": "after",
                "value": "2 L 100 mL",
            },
            {
                "id": "obj.hyeonjun_before",
                "type": "amount",
                "person": "obj.hyeonjun",
                "state": "before",
                "value": "2 L",
            },
            {
                "id": "obj.hyeonjun_after",
                "type": "amount",
                "person": "obj.hyeonjun",
                "state": "after",
                "value": "1 L 400 mL",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.sugyeong_before",
                    "obj.sugyeong_after",
                    "obj.hyeonjun_before",
                    "obj.hyeonjun_after",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_drunk_amount"],
            },
            "plan": {
                "method": "compare_drunk_amount_by_difference",
                "description": "각 사람의 마신 물의 양을 비교하여 더 많이 마신 사람을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "difference_between_before_and_after",
                    "compare_two_amounts",
                ]
            },
            "review": {"check_methods": ["compare_result_consistency"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person", "description": "물을 더 많이 마신 사람"},
        "value": "현준",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008775",
    "problem_type": "comparison",
    "inputs": {
        "total_ticks": 2,
        "target_label": "물을 더 많이 마신 사람",
        "target_ticks": 2,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.sugyeong_before", "value": "2 L 500 mL"},
        {"ref": "obj.sugyeong_after", "value": "2 L 100 mL"},
        {"ref": "obj.hyeonjun_before", "value": "2 L"},
        {"ref": "obj.hyeonjun_after", "value": "1 L 400 mL"},
    ],
    "target": {"ref": "answer.target", "type": "person"},
    "method": "difference_between_before_and_after",
    "plan": ["각 사람의 마신 물의 양을 구한다.", "두 양을 비교한다.", "더 큰 쪽의 사람을 답한다."],
    "steps": [
        {"id": "step.1", "expr": "2 L 500 mL - 2 L 100 mL", "value": "400 mL"},
        {"id": "step.2", "expr": "2 L - 1 L 400 mL", "value": "600 mL"},
        {"id": "step.3", "expr": "400 mL < 600 mL", "value": "참"},
        {"id": "step.4", "expr": "더 많이 마신 사람", "value": "현준"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "마신 양 비교",
            "expected": "600 mL가 400 mL보다 큼",
            "actual": "600 mL > 400 mL",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person", "description": "물을 더 많이 마신 사람"},
        "value": "현준",
        "unit": "",
    },
}
