from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, CircleSlot, LineSlot, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008747",
        title="물의 양 비교 판단",
        canvas=Canvas(width=960, height=455, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.qtext1",
                    "slot.qtext2",
                    "slot.qtext3",
                    "slot.diagram.na_bottle",
                    "slot.diagram.na_arrow",
                    "slot.diagram.na_cups.1",
                    "slot.diagram.na_cups.2",
                    "slot.diagram.na_cups.3",
                    "slot.diagram.na_cups.4",
                    "slot.choice.o",
                    "slot.choice.x",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.qtext1",
                prompt="",
                text="두 병에 물을 가득 채운 후 모양과 크기가 같은 컵에 각각 물을 옮겼습니다.",
                style_role="question",
                x=29,
                y=77,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.qtext2",
                prompt="",
                text="바",
                style_role="question",
                x=585.0,
                y=42.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.qtext3",
                prompt="",
                text="르게 설명했으면 ○표, 그렇지 않으면 ×표를 선택하세요.",
                style_role="question",
                x=25,
                y=158,
                font_size=28,
                fill="#111111",
            ),
            CircleSlot(
                id="slot.diagram.ga_bottle.top1",
                prompt="",
                cx=248,
                cy=164,
                r=17,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.diagram.ga_bottle.top2",
                prompt="",
                cx=248,
                cy=162,
                r=14,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.diagram.ga_bottle.top3",
                prompt="",
                cx=248,
                cy=160,
                r=11,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            RectSlot(
                id="slot.diagram.na_bottle",
                prompt="",
                x=644,
                y=172,
                width=70,
                height=116,
                rx=14,
                ry=14,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.diagram.na_bottle.top1",
                prompt="",
                cx=679,
                cy=167,
                r=12,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.diagram.na_bottle.label",
                prompt="",
                cx=678,
                cy=227,
                r=12,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.diagram.na_bottle.label_text",
                prompt="",
                text="나",
                style_role="label",
                x=672,
                y=235,
                font_size=24,
                fill="#111111",
            ),
            LineSlot(
                id="slot.diagram.na_arrow",
                prompt="",
                x1=729,
                y1=223,
                x2=776,
                y2=223,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.diagram.na_cups.1",
                prompt="",
                text="컵",
                style_role="diagram",
                x=793,
                y=210,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.diagram.na_cups.2",
                prompt="",
                text="컵",
                style_role="diagram",
                x=828.0,
                y=130.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.diagram.na_cups.3",
                prompt="",
                text="컵",
                style_role="diagram",
                x=793,
                y=250,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.diagram.na_cups.4",
                prompt="",
                text="컵",
                style_role="diagram",
                x=828.0,
                y=170.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.o",
                prompt="",
                text="○",
                style_role="choice",
                x=37.0,
                y=268.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.x",
                prompt="",
                text="×",
                style_role="choice",
                x=37.0,
                y=296.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008747",
    "problem_type": "판단",
    "metadata": {
        "language": "ko",
        "question": "두 병에 물을 가득 채운 후 모양과 크기가 같은 컵에 각각 물을 옮겼습니다. 바르게 설명했으면 ○표, 그렇지 않으면 ×표를 선택하세요.",
        "instruction": "나 물병이 컵 3개만큼 물이 더 들어갑니다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.bottle.ga", "type": "bottle", "label": "가"},
            {"id": "obj.bottle.na", "type": "bottle", "label": "나"},
            {"id": "obj.cup_count.ga", "type": "cup_count", "value": 7},
            {"id": "obj.cup_count.na", "type": "cup_count", "value": 4},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.cup_count.ga", "obj.cup_count.na"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare.cups", "rel.difference"],
            },
            "plan": {
                "method": "compare_and_check_statement",
                "description": "두 물병의 컵 개수를 비교하여 문장이 맞는지 판단한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_cup_counts",
                    "find_difference",
                    "judge_true_false_statement",
                ]
            },
            "review": {"check_methods": ["difference_consistency_check", "statement_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "truth_judgment", "description": "문장이 바른지 ○/×로 판단하기"},
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008747",
    "problem_type": "판단",
    "inputs": {
        "total_ticks": 2,
        "target_label": "truth_judgment",
        "target_ticks": 1,
        "target_count": 2,
        "unit": "",
    },
    "plan": "두 물병의 컵 개수를 비교하고, 제시된 문장이 맞는지 확인한다.",
    "given": [{"ref": "obj.cup_count.ga", "value": 7}, {"ref": "obj.cup_count.na", "value": 4}],
    "target": {"ref": "answer.target", "type": "truth_judgment"},
    "method": "compare_and_check_statement",
    "steps": [
        {"id": "step.1", "expr": "7-4", "value": 3},
        {
            "id": "step.2",
            "expr": "문장: 나 물병이 컵 3개만큼 물이 더 들어갑니다. / 비교 결과 확인",
            "value": "false",
        },
    ],
    "checks": [{"id": "check.1", "expr": "7-4=3", "expected": 3, "actual": 3, "pass": True}],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "truth_judgment", "description": "문장이 바른지 ○/×로 판단하기"},
        "value": 0,
        "unit": "",
    },
}
