from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008852",
        title="파프리카와 브로콜리의 무게 비교",
        canvas=Canvas(width=944, height=472, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.left.label1",
                    "slot.left.label2",
                    "slot.right.label1",
                    "slot.right.label2",
                ),
            ),
            Region(
                id="region.diagram.left",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.left.balancer",
                    "slot.left.pan.left",
                    "slot.left.pan.right",
                    "slot.left.weight1",
                    "slot.left.weight2",
                    "slot.left.weight3",
                    "slot.left.weight4",
                ),
            ),
            Region(
                id="region.diagram.right",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.right.balancer",
                    "slot.right.pan.left",
                    "slot.right.pan.right",
                    "slot.right.weight1",
                    "slot.right.weight2",
                    "slot.right.weight3",
                    "slot.right.weight4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="96. 저울과 바둑돌을 사용하여 파프리카와 브로콜리의 무게를 비교했습니다.",
                style_role="question",
                x=18.0,
                y=24.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="파프리카와 브로콜리 중 어느 것이 더 무거운지 선택해 보세요.",
                style_role="question",
                x=18.0,
                y=64.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.left.label1",
                prompt="",
                x=267.0,
                y=94.0,
                width=72.0,
                height=30.0,
                fill="#F3E3BF",
                stroke="#D7C39A",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.left.label1.text",
                prompt="",
                text="파프리카",
                style_role="label",
                x=274.0,
                y=114.0,
                font_size=24,
            ),
            RectSlot(
                id="slot.left.label2",
                prompt="",
                x=358.0,
                y=92.0,
                width=72.0,
                height=39.0,
                fill="#F3E3BF",
                stroke="#D7C39A",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.left.label2.text",
                prompt="",
                text="바둑돌\n50개",
                style_role="label",
                x=367.0,
                y=110.0,
                font_size=24,
            ),
            RectSlot(
                id="slot.right.label1",
                prompt="",
                x=500.0,
                y=94.0,
                width=72.0,
                height=30.0,
                fill="#F3E3BF",
                stroke="#D7C39A",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.right.label1.text",
                prompt="",
                text="브로콜리",
                style_role="label",
                x=505.0,
                y=114.0,
                font_size=24,
            ),
            RectSlot(
                id="slot.right.label2",
                prompt="",
                x=591.0,
                y=92.0,
                width=72.0,
                height=39.0,
                fill="#F3E3BF",
                stroke="#D7C39A",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.right.label2.text",
                prompt="",
                text="바둑돌\n62개",
                style_role="label",
                x=600.0,
                y=110.0,
                font_size=24,
            ),
            RectSlot(
                id="slot.left.balancer",
                prompt="",
                x=234.0,
                y=164.0,
                width=186.0,
                height=110.0,
                fill="#EAF2FA",
                stroke="#9BB1C8",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.left.pan.left",
                prompt="",
                x=248.0,
                y=175.0,
                width=60.0,
                height=28.0,
                fill="#FFFFFF",
                stroke="#C9D3DE",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.left.pan.right",
                prompt="",
                x=360.0,
                y=175.0,
                width=60.0,
                height=28.0,
                fill="#FFFFFF",
                stroke="#C9D3DE",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.left.weight1",
                prompt="",
                text="파프리카",
                style_role="label",
                x=255.0,
                y=190.0,
                font_size=18,
            ),
            TextSlot(
                id="slot.left.weight2",
                prompt="",
                text="바둑돌",
                style_role="label",
                x=367.0,
                y=190.0,
                font_size=18,
            ),
            TextSlot(
                id="slot.left.weight3",
                prompt="",
                text="50개",
                style_role="label",
                x=374.0,
                y=212.0,
                font_size=18,
            ),
            TextSlot(
                id="slot.left.weight4",
                prompt="",
                text="● ● ● ● ●",
                style_role="label",
                x=365.0,
                y=228.0,
                font_size=18,
            ),
            RectSlot(
                id="slot.right.balancer",
                prompt="",
                x=469.0,
                y=164.0,
                width=186.0,
                height=110.0,
                fill="#EAF2FA",
                stroke="#9BB1C8",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.right.pan.left",
                prompt="",
                x=483.0,
                y=175.0,
                width=60.0,
                height=28.0,
                fill="#FFFFFF",
                stroke="#C9D3DE",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.right.pan.right",
                prompt="",
                x=595.0,
                y=175.0,
                width=60.0,
                height=28.0,
                fill="#FFFFFF",
                stroke="#C9D3DE",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.right.weight1",
                prompt="",
                text="브로콜리",
                style_role="label",
                x=488.0,
                y=190.0,
                font_size=18,
            ),
            TextSlot(
                id="slot.right.weight2",
                prompt="",
                text="바둑돌",
                style_role="label",
                x=602.0,
                y=190.0,
                font_size=18,
            ),
            TextSlot(
                id="slot.right.weight3",
                prompt="",
                text="62개",
                style_role="label",
                x=607.0,
                y=212.0,
                font_size=18,
            ),
            TextSlot(
                id="slot.right.weight4",
                prompt="",
                text="● ● ● ● ●",
                style_role="label",
                x=595.0,
                y=228.0,
                font_size=18,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008852",
    "problem_type": "comparison_weight",
    "metadata": {
        "language": "ko",
        "question": "저울과 바둑돌의 대응 관계를 비교하여 파프리카와 브로콜리 중 더 무거운 것을 고르는 문제",
        "instruction": "파프리카와 브로콜리 중 어느 것이 더 무거운지 선택해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.paprika", "type": "vegetable", "name": "파프리카"},
            {"id": "obj.broccoli", "type": "vegetable", "name": "브로콜리"},
            {"id": "obj.stones_50", "type": "reference_weight", "name": "바둑돌 50개", "count": 50},
            {"id": "obj.stones_62", "type": "reference_weight", "name": "바둑돌 62개", "count": 62},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.paprika", "obj.broccoli", "obj.stones_50", "obj.stones_62"],
                "target_ref": "answer.target",
                "condition_refs": [
                    "rel.paprika_equals_50",
                    "rel.broccoli_equals_62",
                    "rel.compare_50_62",
                ],
            },
            "plan": {
                "method": "compare_reference_weights",
                "description": "각 채소가 대응하는 바둑돌 개수를 비교하여 더 큰 쪽을 찾는다.",
            },
            "execute": {"expected_operations": ["identify_correspondence", "compare_counts"]},
            "review": {"check_methods": ["count_comparison_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "heavier_object", "description": "파프리카와 브로콜리 중 더 무거운 것"},
        "value": "브로콜리",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008852",
    "problem_type": "comparison_weight",
    "inputs": {
        "total_ticks": 0,
        "target_label": "더 무거운 것",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "",
    },
    "given": [
        {"ref": "obj.paprika", "value": {"name": "파프리카"}},
        {"ref": "obj.broccoli", "value": {"name": "브로콜리"}},
        {"ref": "obj.stones_50", "value": {"count": 50}},
        {"ref": "obj.stones_62", "value": {"count": 62}},
    ],
    "target": {"ref": "answer.target", "type": "heavier_object"},
    "method": "compare_reference_weights",
    "plan": [
        "파프리카와 브로콜리가 각각 몇 개의 바둑돌 무게와 같은지 확인한다.",
        "바둑돌 개수를 비교하여 더 큰 쪽과 대응된 채소를 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "파프리카 ↔ 바둑돌 50개", "value": 50},
        {"id": "step.2", "expr": "브로콜리 ↔ 바둑돌 62개", "value": 62},
        {"id": "step.3", "expr": "50 < 62", "value": "브로콜리"},
    ],
    "checks": [
        {"id": "check.1", "expr": "50 < 62", "expected": True, "actual": True, "pass": True},
        {
            "id": "check.2",
            "expr": "더 큰 바둑돌 개수에 대응하는 채소가 더 무겁다",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "heavier_object", "description": "파프리카와 브로콜리 중 더 무거운 것"},
        "value": "브로콜리",
        "unit": "",
    },
}
