from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008957",
        title="가게별 일주일 동안 팔린 막대사탕 수",
        canvas=Canvas(width=960.0, height=519.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2", "slot.q3"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.title_box",
                    "slot.table.outer",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.h3",
                    "slot.table.h4",
                    "slot.table.h5",
                    "slot.lbl.h1",
                    "slot.lbl.h2",
                    "slot.lbl.h3",
                    "slot.lbl.h4",
                    "slot.lbl.left.1",
                    "slot.lbl.left.2",
                    "slot.lbl.left.3",
                    "slot.lbl.right.1",
                    "slot.lbl.right.2",
                    "slot.lbl.right.3",
                    "slot.legend.b1",
                    "slot.legend.b2",
                    "slot.legend.b3",
                    "slot.legend.b4",
                    "slot.legend.b5",
                    "slot.legend.b6",
                    "slot.legend.t1",
                    "slot.legend.t2",
                    "slot.legend.t3",
                    "slot.legend.t4",
                    "slot.legend.t5",
                    "slot.legend.t6",
                    "slot.legend.t7",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="□ 27. 가게별 일주일 동안 팔린 막대사탕 수를 조사하여 그림그래프로 나타내었",
                style_role="question",
                x=18.0,
                y=30.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="습니다. 나 가게보다 막대사탕을 더 많이 판 가게를 모두 선택하세요.",
                style_role="question",
                x=18.0,
                y=64.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q3", prompt="", text="", style_role="question", x=0.0, y=0.0, font_size=28
            ),
            RectSlot(id="slot.title_box", prompt="", x=285.0, y=86.0, width=262.0, height=45.0),
            TextSlot(
                id="slot.titletxt",
                prompt="",
                text="일주일 동안 팔린 막대사탕 수",
                style_role="title",
                x=310.0,
                y=115.0,
                font_size=28,
            ),
            RectSlot(id="slot.table.outer", prompt="", x=190.0, y=136.0, width=612.0, height=198.0),
            LineSlot(id="slot.table.v1", prompt="", x1=280.0, y1=136.0, x2=280.0, y2=334.0),
            LineSlot(id="slot.table.v2", prompt="", x1=491.0, y1=136.0, x2=491.0, y2=334.0),
            LineSlot(id="slot.table.v3", prompt="", x1=580.0, y1=136.0, x2=580.0, y2=334.0),
            LineSlot(id="slot.table.v4", prompt="", x1=690.0, y1=136.0, x2=690.0, y2=334.0),
            LineSlot(id="slot.table.h1", prompt="", x1=190.0, y1=178.0, x2=802.0, y2=178.0),
            LineSlot(id="slot.table.h2", prompt="", x1=190.0, y1=221.0, x2=802.0, y2=221.0),
            LineSlot(id="slot.table.h3", prompt="", x1=190.0, y1=261.0, x2=802.0, y2=261.0),
            LineSlot(id="slot.table.h4", prompt="", x1=190.0, y1=302.0, x2=802.0, y2=302.0),
            LineSlot(id="slot.table.h5", prompt="", x1=190.0, y1=334.0, x2=802.0, y2=334.0),
            TextSlot(
                id="slot.lbl.h1",
                prompt="",
                text="가게",
                style_role="label",
                x=214.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.h2",
                prompt="",
                text="막대사탕 수",
                style_role="label",
                x=332.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.h3",
                prompt="",
                text="가게",
                style_role="label",
                x=518.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.h4",
                prompt="",
                text="막대사탕 수",
                style_role="label",
                x=636.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.left.1",
                prompt="",
                text="가",
                style_role="label",
                x=226.0,
                y=208.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.left.2",
                prompt="",
                text="다",
                style_role="label",
                x=226.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.left.3",
                prompt="",
                text="마",
                style_role="label",
                x=226.0,
                y=292.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.right.1",
                prompt="",
                text="나",
                style_role="label",
                x=517.0,
                y=208.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.right.2",
                prompt="",
                text="라",
                style_role="label",
                x=517.0,
                y=250.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.right.3",
                prompt="",
                text="바",
                style_role="label",
                x=517.0,
                y=292.0,
                font_size=28,
            ),
            CircleSlot(id="slot.g.a.1", prompt="", cx=301.0, cy=205.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.a.2", prompt="", cx=319.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.a.3", prompt="", cx=337.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.a.4", prompt="", cx=355.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.d.1", prompt="", cx=301.0, cy=246.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.d.2", prompt="", cx=328.0, cy=246.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.d.3", prompt="", cx=355.0, cy=246.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.d.4", prompt="", cx=382.0, cy=246.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.d.5", prompt="", cx=400.0, cy=246.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.m.1", prompt="", cx=301.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.m.2", prompt="", cx=319.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.m.3", prompt="", cx=337.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.m.4", prompt="", cx=355.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.m.5", prompt="", cx=373.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.m.6", prompt="", cx=391.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.n.1", prompt="", cx=592.0, cy=205.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.n.2", prompt="", cx=619.0, cy=205.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.n.3", prompt="", cx=646.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.n.4", prompt="", cx=664.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.n.5", prompt="", cx=682.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.n.6", prompt="", cx=700.0, cy=205.0, r=5.0, fill="#ffcfbf"),
            CircleSlot(id="slot.g.r.1", prompt="", cx=592.0, cy=246.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.r.2", prompt="", cx=619.0, cy=246.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.r.3", prompt="", cx=646.0, cy=246.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.b.1", prompt="", cx=592.0, cy=286.0, r=8.0, fill="#ffb3a6"),
            CircleSlot(id="slot.g.b.2", prompt="", cx=619.0, cy=286.0, r=5.0, fill="#ffcfbf"),
            RectSlot(id="slot.legend.b1", prompt="", x=692.0, y=342.0, width=14.0, height=30.0),
            RectSlot(id="slot.legend.b2", prompt="", x=712.0, y=342.0, width=7.0, height=18.0),
            RectSlot(id="slot.legend.b3", prompt="", x=717.0, y=342.0, width=4.0, height=8.0),
            RectSlot(id="slot.legend.b4", prompt="", x=724.0, y=342.0, width=14.0, height=30.0),
            RectSlot(id="slot.legend.b5", prompt="", x=744.0, y=342.0, width=7.0, height=18.0),
            RectSlot(id="slot.legend.b6", prompt="", x=749.0, y=342.0, width=4.0, height=8.0),
            TextSlot(
                id="slot.legend.t1",
                prompt="",
                text="100개",
                style_role="label",
                x=708.0,
                y=365.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.t2",
                prompt="",
                text="10개",
                style_role="label",
                x=748.0,
                y=365.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.t3",
                prompt="",
                text="( 가, 나, 다, 라 ) 가게",
                style_role="label",
                x=682.0,
                y=401.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.t4",
                prompt="",
                text="",
                style_role="label",
                x=0.0,
                y=0.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.t5",
                prompt="",
                text="",
                style_role="label",
                x=0.0,
                y=0.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.t6",
                prompt="",
                text="",
                style_role="label",
                x=0.0,
                y=0.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.t7",
                prompt="",
                text="",
                style_role="label",
                x=0.0,
                y=0.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008957",
    "problem_type": "그림그래프_비교",
    "metadata": {
        "language": "ko",
        "question": "가게별 일주일 동안 팔린 막대사탕 수를 조사하여 그림그래프로 나타내었습니다. 나 가게보다 막대사탕을 더 많이 판 가게를 모두 선택하세요.",
        "instruction": "나 가게보다 막대사탕을 더 많이 판 가게를 모두 선택하세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.shop.가", "type": "store", "name": "가"},
            {"id": "obj.shop.나", "type": "store", "name": "나"},
            {"id": "obj.shop.다", "type": "store", "name": "다"},
            {"id": "obj.shop.라", "type": "store", "name": "라"},
            {"id": "obj.shop.마", "type": "store", "name": "마"},
            {"id": "obj.shop.바", "type": "store", "name": "바"},
            {"id": "obj.legend.big", "type": "unit_symbol", "name": "100개"},
            {"id": "obj.legend.small", "type": "unit_symbol", "name": "10개"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.shop.나", "obj.legend.big", "obj.legend.small"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare.n"],
            },
            "plan": {
                "method": "graph_compare",
                "description": "그림그래프의 표를 보고 나 가게와 각 가게의 수를 비교한다.",
            },
            "execute": {"expected_operations": ["count_symbols", "compare_values"]},
            "review": {"check_methods": ["compare_each_store_with_n"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "stores_more_than_n",
            "description": "나 가게보다 막대사탕을 더 많이 판 가게",
        },
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008957",
    "problem_type": "그림그래프_비교",
    "inputs": {
        "total_ticks": 0,
        "target_label": "나 가게보다 더 많이 판 가게",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "개",
    },
    "given": [
        {"ref": "obj.shop.나", "value": None},
        {"ref": "obj.legend.big", "value": 100},
        {"ref": "obj.legend.small", "value": 10},
    ],
    "target": {"ref": "answer.target", "type": "stores_more_than_n"},
    "method": "graph_compare",
    "plan": [
        "그림그래프에서 나 가게와 다른 가게의 막대사탕 수를 비교합니다.",
        "나 가게보다 큰 수를 가진 가게를 고릅니다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "나 가게의 값은 해설에 240개로 제시됨", "value": 240},
        {"id": "step.2", "expr": "다 가게와 라 가게는 나 가게보다 많음", "value": "다, 라"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "선택된 가게가 나 가게보다 더 많은지 확인",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "stores_more_than_n",
            "description": "나 가게보다 막대사탕을 더 많이 판 가게",
        },
        "value": 2,
        "unit": "",
    },
}
