from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
    person_slots,
    PathSlot,
    PolygonSlot,
)


def build_problem_template() -> ProblemTemplate:
    left_person = person_slots(
        "slot.person.left", cx=256.0, head_cy=527.0, hair="#8A3F32", shirt="#F06AA0", bow="#D487D8"
    )
    right_person = person_slots(
        "slot.person.right",
        cx=616.0,
        head_cy=527.0,
        hair="#C77A22",
        shirt="#F7B51E",
        bow="#E7A2C2",
        pigtails=True,
    )
    return ProblemTemplate(
        id="S3_초등_3_008728",
        title="그림을 보고 바르게 말한 사람을 선택하기",
        canvas=Canvas(width=840.0, height=648.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header", role="stem", flow="absolute", slot_ids=("slot.header.text",)
            ),
            Region(
                id="region.cars",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.cars.outer",
                    "slot.cars.group1",
                    "slot.cars.group2",
                    "slot.cars.group3",
                    "slot.cars.group4",
                    "slot.cars.group5",
                    "slot.cars.group6",
                    "slot.cars.group7",
                ),
            ),
            Region(
                id="region.speech.left",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.speech.left",
                    "slot.speech.left.text1",
                    "slot.speech.left.text2",
                    "slot.speech.left.text3",
                    *(slot.id for slot in left_person),
                ),
            ),
            Region(
                id="region.speech.right",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.speech.right",
                    "slot.speech.right.text1",
                    "slot.speech.right.text2",
                    "slot.speech.right.text3",
                    *(slot.id for slot in right_person),
                ),
            ),
            Region(
                id="region.footer",
                role="answer",
                flow="absolute",
                slot_ids=(
                    "slot.inserted.car.1.body",
                    "slot.inserted.car.1.roof",
                    "slot.inserted.car.1.window.left",
                    "slot.inserted.car.1.window.right",
                    "slot.inserted.car.1.wheel.left",
                    "slot.inserted.car.1.wheel.right",
                    "slot.inserted.car.1.hub.left",
                    "slot.inserted.car.1.hub.right",
                    "slot.inserted.car.1.body.copy1",
                    "slot.inserted.car.1.roof.copy1",
                    "slot.inserted.car.1.window.left.copy1",
                    "slot.inserted.car.1.window.right.copy1",
                    "slot.inserted.car.1.wheel.left.copy1",
                    "slot.inserted.car.1.wheel.right.copy1",
                    "slot.inserted.car.1.hub.left.copy1",
                    "slot.inserted.car.1.hub.right.copy1",
                    "slot.inserted.car.1.body.copy2",
                    "slot.inserted.car.1.roof.copy2",
                    "slot.inserted.car.1.window.left.copy2",
                    "slot.inserted.car.1.window.right.copy2",
                    "slot.inserted.car.1.wheel.left.copy2",
                    "slot.inserted.car.1.wheel.right.copy2",
                    "slot.inserted.car.1.hub.left.copy2",
                    "slot.inserted.car.1.hub.right.copy2",
                    "slot.inserted.car.1.body.copy4",
                    "slot.inserted.car.1.roof.copy4",
                    "slot.inserted.car.1.window.left.copy4",
                    "slot.inserted.car.1.window.right.copy4",
                    "slot.inserted.car.1.body.copy1.copy4",
                    "slot.inserted.car.1.roof.copy1.copy4",
                    "slot.inserted.car.1.window.left.copy1.copy4",
                    "slot.inserted.car.1.window.right.copy1.copy4",
                    "slot.inserted.car.1.body.copy2.copy4",
                    "slot.inserted.car.1.roof.copy2.copy4",
                    "slot.inserted.car.1.window.left.copy2.copy4",
                    "slot.inserted.car.1.window.right.copy2.copy4",
                    "slot.inserted.car.1.wheel.left.copy4",
                    "slot.inserted.car.1.wheel.right.copy4",
                    "slot.inserted.car.1.hub.left.copy4",
                    "slot.inserted.car.1.hub.right.copy4",
                    "slot.inserted.car.1.wheel.left.copy1.copy4",
                    "slot.inserted.car.1.wheel.right.copy1.copy4",
                    "slot.inserted.car.1.hub.left.copy1.copy4",
                    "slot.inserted.car.1.hub.right.copy1.copy4",
                    "slot.inserted.car.1.wheel.left.copy2.copy4",
                    "slot.inserted.car.1.wheel.right.copy2.copy4",
                    "slot.inserted.car.1.hub.left.copy2.copy4",
                    "slot.inserted.car.1.hub.right.copy2.copy4",
                    "slot.inserted.car.1.body.copy2.copy4.copy5",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy8",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7.copy8",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.body.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.roof.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy9",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7.copy9",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy8.copy9",
                    "slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7.copy8.copy9",
                    "slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7.copy8.copy9",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.header.text",
                prompt="",
                text="그림을 보고 바르게 말한 사람을 선택해 보세요.",
                style_role="question",
                x=26.0,
                y=28.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.cars.outer",
                prompt="",
                x=45,
                y=410,
                width=745,
                height=205,
                rx=14,
                ry=14,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group1",
                prompt="",
                x=625,
                y=65,
                width=170,
                height=45,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group2",
                prompt="",
                x=111,
                y=203,
                width=165,
                height=42,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group3",
                prompt="",
                x=433,
                y=68,
                width=165,
                height=42,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group4",
                prompt="",
                x=60,
                y=65,
                width=175,
                height=45,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group5",
                prompt="",
                x=67.33689880371094,
                y=271.1443786621094,
                width=163,
                height=42,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group6",
                prompt="",
                x=335,
                y=140,
                width=180,
                height=50,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.cars.group7",
                prompt="",
                x=343.71514892578125,
                y=205.5775146484375,
                width=163,
                height=42,
                rx=6,
                ry=6,
                fill="#ffffff",
                stroke="#dc2626",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.speech.left",
                prompt="",
                x=90,
                y=460,
                width=330,
                height=155,
                rx=72,
                ry=72,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.speech.left.text1",
                prompt="",
                text="색칠한 부분은",
                style_role="body",
                x=204,
                y=377,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.speech.left.text2",
                prompt="",
                text="7묶음 중에서 3묶음이므로",
                style_role="body",
                x=43,
                y=424,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.speech.left.text3",
                prompt="",
                text="전체의 3/7이야.",
                style_role="body",
                x=96,
                y=471,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.speech.right",
                prompt="",
                x=390,
                y=355,
                width=350,
                height=155,
                rx=72,
                ry=72,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.speech.right.text1",
                prompt="",
                text="색칠하지 않은 부분은",
                style_role="body",
                x=496,
                y=392,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.speech.right.text2",
                prompt="",
                text="7묶음 중에서 4묶음이므로",
                style_role="body",
                x=479,
                y=429,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.speech.right.text3",
                prompt="",
                text="전체의 4/7이야.",
                style_role="body",
                x=547,
                y=471,
                font_size=28,
                fill="#111111",
            ),
            *left_person,
            *right_person,
            PathSlot(
                id="slot.inserted.car.1.body",
                prompt="",
                d="M 70 90 Q 70 80 80 80 L 90 70 L 115 70 L 125 80 L 135 80 Q 140 85 145 95 L 140 100 L 70 100 Q 70 95 70 90 Z",
                fill="#69BD58",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof",
                prompt="",
                d="M 85 80 L 95 70 L 110 70 L 120 80 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left",
                prompt="",
                points=[[90, 80], [95, 75], [100, 75], [100, 80]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right",
                prompt="",
                points=[[105, 75], [110, 75], [115, 80], [105, 80]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left",
                prompt="",
                cx=85,
                cy=100,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right",
                prompt="",
                cx=125,
                cy=100,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left",
                prompt="",
                cx=85,
                cy=100,
                r=5,
                fill="#D1D5DB",
                stroke="none",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right",
                prompt="",
                cx=125,
                cy=100,
                r=5,
                fill="#D1D5DB",
                stroke="none",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy1",
                prompt="",
                d="M 155 90 Q 155 80 165 80 L 175 70 L 200 70 L 210 80 L 220 80 Q 225 85 230 95 L 225 100 L 155 100 Q 155 95 155 90 Z",
                fill="#69BD58",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy1",
                prompt="",
                d="M 170 80 L 180 70 L 195 70 L 205 80 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy1",
                prompt="",
                points=[[175, 80], [180, 75], [185, 75], [185, 80]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy1",
                prompt="",
                points=[[190, 75], [195, 75], [200, 80], [190, 80]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy1",
                prompt="",
                cx=170,
                cy=100,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy1",
                prompt="",
                cx=210,
                cy=100,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy1",
                prompt="",
                cx=170,
                cy=100,
                r=5,
                fill="#D1D5DB",
                stroke_width=2,
                stroke="#111111",
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy1",
                prompt="",
                cx=210,
                cy=100,
                r=5,
                fill="#D1D5DB",
                stroke_width=2,
                stroke="#111111",
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2",
                prompt="",
                d="M 245 90 Q 245 80 255 80 L 265 70 L 290 70 L 300 80 L 310 80 Q 315 85 320 95 L 315 100 L 245 100 Q 245 95 245 90 Z",
                fill="#69BD58",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2",
                prompt="",
                d="M 260 80 L 270 70 L 285 70 L 295 80 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2",
                prompt="",
                points=[[265, 80], [270, 75], [275, 75], [275, 80]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2",
                prompt="",
                points=[[280, 75], [285, 75], [290, 80], [280, 80]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2",
                prompt="",
                cx=260,
                cy=100,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2",
                prompt="",
                cx=300,
                cy=100,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2",
                prompt="",
                cx=260,
                cy=100,
                r=5,
                fill="#D1D5DB",
                stroke_width=2,
                stroke="#111111",
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2",
                prompt="",
                cx=300,
                cy=100,
                r=5,
                fill="#D1D5DB",
                stroke_width=2,
                stroke="#111111",
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy4",
                prompt="",
                d="M 350 89 Q 350 79 360 79 L 370 69 L 395 69 L 405 79 L 415 79 Q 420 84 425 94 L 420 99 L 350 99 Q 350 94 350 89 Z",
                fill="#69BD58",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy4",
                prompt="",
                d="M 365 79 L 375 69 L 390 69 L 400 79 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy4",
                prompt="",
                points=[[370, 79], [375, 74], [380, 74], [380, 79]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy4",
                prompt="",
                points=[[385, 74], [390, 74], [395, 79], [385, 79]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy1.copy4",
                prompt="",
                d="M 438 89 Q 438 79 448 79 L 458 69 L 483 69 L 493 79 L 503 79 Q 508 84 513 94 L 508 99 L 438 99 Q 438 94 438 89 Z",
                fill="#69BD58",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy1.copy4",
                prompt="",
                d="M 453 79 L 463 69 L 478 69 L 488 79 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy1.copy4",
                prompt="",
                points=[[458, 79], [463, 74], [468, 74], [468, 79]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy1.copy4",
                prompt="",
                points=[[473, 74], [478, 74], [483, 79], [473, 79]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4",
                prompt="",
                d="M 525 89 Q 525 79 535 79 L 545 69 L 570 69 L 580 79 L 590 79 Q 595 84 600 94 L 595 99 L 525 99 Q 525 94 525 89 Z",
                fill="#69BD58",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4",
                prompt="",
                d="M 540 79 L 550 69 L 565 69 L 575 79 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4",
                prompt="",
                points=[[545, 79], [550, 74], [555, 74], [555, 79]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4",
                prompt="",
                points=[[560, 74], [565, 74], [570, 79], [560, 79]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy4",
                prompt="",
                cx=365,
                cy=99,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy4",
                prompt="",
                cx=405,
                cy=99,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy4",
                prompt="",
                cx=365,
                cy=99,
                r=5,
                fill="#D1D5DB",
                stroke_width=2,
                stroke="#111111",
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy4",
                prompt="",
                cx=405,
                cy=99,
                r=5,
                fill="#D1D5DB",
                stroke_width=2,
                stroke="#111111",
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy1.copy4",
                prompt="",
                cx=453,
                cy=99,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy1.copy4",
                prompt="",
                cx=493,
                cy=99,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy1.copy4",
                prompt="",
                cx=453,
                cy=99,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy1.copy4",
                prompt="",
                cx=493,
                cy=99,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4",
                prompt="",
                cx=540,
                cy=99,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4",
                prompt="",
                cx=580,
                cy=99,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4",
                prompt="",
                cx=540,
                cy=99,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4",
                prompt="",
                cx=580,
                cy=99,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5",
                prompt="",
                d="M 148 170 Q 148 160 158 160 L 168 150 L 193 150 L 203 160 L 213 160 Q 218 165 223 175 L 218 180 L 148 180 Q 148 175 148 170 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5",
                prompt="",
                d="M 163 160 L 173 150 L 188 150 L 198 160 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5",
                prompt="",
                points=[[168, 160], [173, 155], [178, 155], [178, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5",
                prompt="",
                points=[[183, 155], [188, 155], [193, 160], [183, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5",
                prompt="",
                cx=163,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5",
                prompt="",
                cx=203,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5",
                prompt="",
                cx=163,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5",
                prompt="",
                cx=203,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy7",
                prompt="",
                d="M 238 170 Q 238 160 248 160 L 258 150 L 283 150 L 293 160 L 303 160 Q 308 165 313 175 L 308 180 L 238 180 Q 238 175 238 170 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy7",
                prompt="",
                d="M 253 160 L 263 150 L 278 150 L 288 160 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7",
                prompt="",
                points=[[258, 160], [263, 155], [268, 155], [268, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7",
                prompt="",
                points=[[273, 155], [278, 155], [283, 160], [273, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7",
                prompt="",
                cx=253,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7",
                prompt="",
                cx=293,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7",
                prompt="",
                cx=253,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7",
                prompt="",
                cx=293,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy8",
                prompt="",
                d="M 350 170 Q 350 160 360 160 L 370 150 L 395 150 L 405 160 L 415 160 Q 420 165 425 175 L 420 180 L 350 180 Q 350 175 350 170 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy8",
                prompt="",
                d="M 365 160 L 375 150 L 390 150 L 400 160 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy8",
                prompt="",
                points=[[370, 160], [375, 155], [380, 155], [380, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy8",
                prompt="",
                points=[[385, 155], [390, 155], [395, 160], [385, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                d="M 440 170 Q 440 160 450 160 L 460 150 L 485 150 L 495 160 L 505 160 Q 510 165 515 175 L 510 180 L 440 180 Q 440 175 440 170 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                d="M 455 160 L 465 150 L 480 150 L 490 160 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                points=[[460, 160], [465, 155], [470, 155], [470, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                points=[[475, 155], [480, 155], [485, 160], [475, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy8",
                prompt="",
                cx=365,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy8",
                prompt="",
                cx=405,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy8",
                prompt="",
                cx=365,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy8",
                prompt="",
                cx=405,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                cx=455,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                cx=495,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                cx=455,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7.copy8",
                prompt="",
                cx=495,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy9",
                prompt="",
                d="M 345 170 Q 345 160 355 160 L 365 150 L 390 150 L 400 160 L 410 160 Q 415 165 420 175 L 415 180 L 345 180 Q 345 175 345 170 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy9",
                prompt="",
                d="M 360 160 L 370 150 L 385 150 L 395 160 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy9",
                prompt="",
                points=[[365, 160], [370, 155], [375, 155], [375, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy9",
                prompt="",
                points=[[380, 155], [385, 155], [390, 160], [380, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                d="M 435 170 Q 435 160 445 160 L 455 150 L 480 150 L 490 160 L 500 160 Q 505 165 510 175 L 505 180 L 435 180 Q 435 175 435 170 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                d="M 450 160 L 460 150 L 475 150 L 485 160 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                points=[[455, 160], [460, 155], [465, 155], [465, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                points=[[470, 155], [475, 155], [480, 160], [470, 160]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                d="M 485 305 Q 485 295 495 295 L 505 285 L 530 285 L 540 295 L 550 295 Q 555 300 560 310 L 555 315 L 485 315 Q 485 310 485 305 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                d="M 500 295 L 510 285 L 525 285 L 535 295 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                points=[[505, 295], [510, 290], [515, 290], [515, 295]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                points=[[520, 290], [525, 290], [530, 295], [520, 295]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PathSlot(
                id="slot.inserted.car.1.body.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                d="M 575 305 Q 575 295 585 295 L 595 285 L 620 285 L 630 295 L 640 295 Q 645 300 650 310 L 645 315 L 575 315 Q 575 310 575 305 Z",
                fill="#ffffff",
                stroke="#3E9B6D",
                stroke_width=2,
            ),
            PathSlot(
                id="slot.inserted.car.1.roof.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                d="M 590 295 L 600 285 L 615 285 L 625 295 Z",
                fill="#A7E3D3",
                stroke="#2D9A7A",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.left.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                points=[[595, 295], [600, 290], [605, 290], [605, 295]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            PolygonSlot(
                id="slot.inserted.car.1.window.right.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                points=[[610, 290], [615, 290], [620, 295], [610, 295]],
                fill="#E8FFF8",
                stroke="#2D9A7A",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy9",
                prompt="",
                cx=360,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy9",
                prompt="",
                cx=400,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy9",
                prompt="",
                cx=360,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy9",
                prompt="",
                cx=400,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                cx=450,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                cx=490,
                cy=180,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                cx=450,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7.copy9",
                prompt="",
                cx=490,
                cy=180,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                cx=500,
                cy=315,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                cx=540,
                cy=315,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                cx=500,
                cy=315,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy8.copy9",
                prompt="",
                cx=540,
                cy=315,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.left.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                cx=590,
                cy=315,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.wheel.right.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                cx=630,
                cy=315,
                r=5,
                fill="#4B5563",
                stroke="#1F2937",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.left.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                cx=590,
                cy=315,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.inserted.car.1.hub.right.copy2.copy4.copy5.copy7.copy8.copy9",
                prompt="",
                cx=630,
                cy=315,
                r=5,
                fill="#D1D5DB",
                stroke="#111111",
                stroke_width=2,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008728",
    "problem_type": "fraction_description_choice",
    "metadata": {
        "language": "ko",
        "question": "그림을 보고 바르게 말한 사람을 선택해 보세요.",
        "instruction": "그림의 색칠한 부분과 색칠하지 않은 부분을 분수로 바르게 말한 사람을 고른다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.picture", "type": "picture_group"},
            {"id": "obj.colored_part", "type": "part", "property": "색칠한 부분"},
            {"id": "obj.uncolored_part", "type": "part", "property": "색칠하지 않은 부분"},
            {"id": "obj.fraction_colored", "type": "fraction", "value": "3/7"},
            {"id": "obj.fraction_uncolored", "type": "fraction", "value": "4/7"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.picture", "obj.colored_part", "obj.uncolored_part"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.describe_colored", "rel.describe_uncolored"],
            },
            "plan": {
                "method": "fraction_description_matching",
                "description": "그림의 색칠 상태를 설명한 말이 분수와 맞는지 확인한다.",
            },
            "execute": {
                "expected_operations": [
                    "match_description_to_fraction",
                    "compare_statement_with_picture",
                ]
            },
            "review": {"check_methods": ["picture_statement_consistency"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_selection", "description": "그림을 바르게 말한 사람"},
        "value": 1,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008728",
    "problem_type": "fraction_description_choice",
    "inputs": {
        "total_ticks": 7,
        "target_label": "그림을 바르게 말한 사람",
        "target_ticks": 3,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.colored_part", "value": {"description": "색칠한 부분", "fraction": "3/7"}},
        {
            "ref": "obj.uncolored_part",
            "value": {"description": "색칠하지 않은 부분", "fraction": "4/7"},
        },
    ],
    "target": {"ref": "answer.target", "type": "person_selection"},
    "method": "fraction_description_matching",
    "plan": [
        "그림의 색칠한 부분과 색칠하지 않은 부분을 분수 설명과 비교한다.",
        "말풍선의 설명이 그림과 맞는 사람을 찾는다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "색칠한 부분 ↔ 3/7", "value": "진경"},
        {"id": "step.2", "expr": "색칠하지 않은 부분 ↔ 4/7", "value": "현진"},
        {"id": "step.3", "expr": "그림과 맞는 말 고르기", "value": "진경"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "색칠한 부분이 7묶음 중 3묶음인지 확인",
            "expected": "3/7",
            "actual": "3/7",
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "색칠하지 않은 부분이 7묶음 중 4묶음인지 확인",
            "expected": "4/7",
            "actual": "4/7",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_selection", "description": "그림을 바르게 말한 사람"},
        "value": 1,
        "unit": "",
    },
}
