from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008847', title='알맞은 단위를 골라 보세요', canvas=Canvas(width=840, height=330, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.no', 'slot.title', 'slot.coin', 'slot.statement_1', 'slot.statement_2')),), slots=(TextSlot(id='slot.no', prompt='', text='86.', style_role='question', x=18.0, y=28.0, font_size=28), TextSlot(id='slot.title', prompt='', text='알맞은 단위를 골라 보세요.', style_role='question', x=56.0, y=28.0, font_size=28), RectSlot(id='slot.coin', prompt='', x=442.0, y=28.0, width=102.0, height=102.0), TextSlot(id='slot.statement_1', prompt='', text='100원짜리 동전의 무게는 약 5(', style_role='question', x=188.0, y=206.0, font_size=28), TextSlot(id='slot.statement_2', prompt='', text='g , kg , t', style_role='question', x=327.0, y=206.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008847', 'problem_type': 'unit_choice', 'metadata': {'language': 'ko', 'question': '100원짜리 동전의 무게에 알맞은 단위를 고르는 문제', 'instruction': '알맞은 단위를 골라 보세요.'}, 'domain': {'objects': [{'id': 'obj.coin_100won', 'type': 'coin', 'name': '100원짜리 동전'}, {'id': 'obj.weight_value', 'type': 'quantity', 'value': 5, 'unit_candidates': ['g', 'kg', 't']}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.coin_100won', 'obj.weight_value'], 'target_ref': 'answer.target', 'condition_refs': ['rel.choose_unit']}, 'plan': {'method': 'unit_selection', 'description': '주어진 무게에 맞는 단위를 고른다.'}, 'execute': {'expected_operations': ['compare_unit_scale', 'select_appropriate_unit']}, 'review': {'check_methods': ['unit_reasonableness_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'appropriate_unit', 'description': '100원짜리 동전의 무게에 알맞은 단위'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008847', 'problem_type': 'unit_choice', 'inputs': {'total_ticks': 1, 'target_label': '알맞은 단위', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.coin_100won', 'value': {'name': '100원짜리 동전'}}, {'ref': 'obj.weight_value', 'value': {'value': 5, 'unit_candidates': ['g', 'kg', 't']}}], 'target': {'ref': 'answer.target', 'type': 'appropriate_unit'}, 'method': 'unit_selection', 'plan': ['주어진 수 5에 대해 g, kg, t 중 가장 알맞은 무게 단위를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '100원짜리 동전의 무게에 맞는 단위 후보를 비교한다.', 'value': 'g'}], 'checks': [{'id': 'check.1', 'expr': '동전의 무게는 작은 단위인 g로 나타내는 것이 자연스럽다.', 'expected': 'g', 'actual': 'g', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'appropriate_unit', 'description': '100원짜리 동전의 무게에 알맞은 단위'}, 'value': 0, 'unit': ''}}
