from __future__ import annotations
from modu_math.dsl import Canvas, LineSlot, PathSlot, ProblemTemplate, RectSlot, Region, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008879', title='가장 무거운 것 고르기', canvas=Canvas(width=960.0, height=500.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q_mark', 'slot.q1', 'slot.q2', 'slot.scale1.label', 'slot.scale1.fruit1', 'slot.scale1.fruit2', 'slot.scale2.label', 'slot.scale2.fruit1', 'slot.scale2.fruit2', 'slot.choice')),), slots=(TextSlot(id='slot.q_mark', prompt='', text='□', style_role='question', x=12.0, y=30.0, font_size=28), TextSlot(id='slot.q1', prompt='', text='34. 저울로 딸기, 복숭아, 배의 무게를 비교하고 있습니다. 가장 무거운 것은', style_role='question', x=48.0, y=30.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='무엇인지 알맞은 것을 선택해 보세요.', style_role='question', x=12.0, y=66.0, font_size=28), TextSlot(id='slot.scale1.label', prompt='', text='가  딸기    복숭아', style_role='label', x=214.0, y=116.0, font_size=28), TextSlot(id='slot.scale2.label', prompt='', text='나  복숭아    배', style_role='label', x=548.0, y=116.0, font_size=28), RectSlot(id='slot.scale1.base', prompt='', x=230.0, y=150.0, width=240.0, height=120.0, rx=10.0, ry=10.0), RectSlot(id='slot.scale2.base', prompt='', x=564.0, y=150.0, width=240.0, height=120.0, rx=10.0, ry=10.0), LineSlot(id='slot.scale1.bar', prompt='', x1=260.0, y1=210.0, x2=440.0, y2=195.0), LineSlot(id='slot.scale2.bar', prompt='', x1=594.0, y1=195.0, x2=774.0, y2=210.0), TextSlot(id='slot.scale1.fruit1', prompt='', text='딸기', style_role='label', x=265.0, y=166.0, font_size=28), TextSlot(id='slot.scale1.fruit2', prompt='', text='복숭아', style_role='label', x=398.0, y=166.0, font_size=28), TextSlot(id='slot.scale2.fruit1', prompt='', text='복숭아', style_role='label', x=606.0, y=166.0, font_size=28), TextSlot(id='slot.scale2.fruit2', prompt='', text='배', style_role='label', x=744.0, y=166.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='( 딸기 , 복숭아 , 배 )', style_role='choice', x=360.0, y=328.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008879', 'problem_type': '비교', 'metadata': {'language': 'ko', 'question': '저울로 딸기, 복숭아, 배의 무게를 비교하고 있습니다. 가장 무거운 것은 무엇인지 알맞은 것을 선택해 보세요.', 'instruction': '가장 무거운 것을 선택한다.'}, 'domain': {'objects': [{'id': 'obj.strawberry', 'type': 'fruit', 'name': '딸기'}, {'id': 'obj.peach', 'type': 'fruit', 'name': '복숭아'}, {'id': 'obj.pear', 'type': 'fruit', 'name': '배'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.strawberry', 'obj.peach', 'obj.pear', 'rel.compare.1', 'rel.compare.2'], 'target_ref': 'answer.target', 'condition_refs': ['rel.compare.1', 'rel.compare.2']}, 'plan': {'method': '비교하기', 'description': '주어진 비교 관계를 바탕으로 가장 무거운 대상을 찾는다.'}, 'execute': {'expected_operations': ['compare_weights', 'select_heaviest']}, 'review': {'check_methods': ['comparison_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'heaviest_fruit', 'description': '가장 무거운 것'}, 'value': '배', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008879', 'problem_type': '비교', 'inputs': {'total_ticks': 0, 'target_label': '가장 무거운 것', 'target_ticks': 0, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.strawberry', 'value': '딸기'}, {'ref': 'obj.peach', 'value': '복숭아'}, {'ref': 'obj.pear', 'value': '배'}, {'ref': 'rel.compare.1', 'value': {'left': '딸기', 'right': '복숭아'}}, {'ref': 'rel.compare.2', 'value': {'left': '복숭아', 'right': '배'}}], 'target': {'ref': 'answer.target', 'type': 'heaviest_fruit'}, 'method': '비교하기', 'plan': ['가와 나의 비교 결과를 살펴서 더 무거운 대상을 찾는다.', '두 비교를 연결하여 세 과일 중 가장 무거운 것을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '가: 딸기와 복숭아 비교', 'value': '복숭아'}, {'id': 'step.2', 'expr': '나: 복숭아와 배 비교', 'value': '배'}, {'id': 'step.3', 'expr': '가장 무거운 것 선택', 'value': '배'}], 'checks': [{'id': 'check.1', 'expr': '비교 결과가 문제의 해설과 일치하는가', 'expected': '배', 'actual': '배', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'heaviest_fruit', 'description': '가장 무거운 것'}, 'value': '배', 'unit': ''}}
