from __future__ import annotations
from modu_math.dsl import Canvas, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008998', title='그림을 보고 알맞은 말을 선택하세요.', canvas=Canvas(width=840, height=360, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.title', 'slot.shape.rect', 'slot.shape.square', 'slot.label.rect', 'slot.label.square', 'slot.sentence.1', 'slot.sentence.2')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.title', prompt='', text='□ 36. 그림을 보고 알맞은 말을 선택하세요.', style_role='question', x=16.0, y=24.0, font_size=28), RectSlot(id='slot.shape.rect', prompt='', x=286.0, y=42.0, width=136.0, height=88.0), RectSlot(id='slot.shape.square', prompt='', x=486.0, y=42.0, width=76.0, height=76.0), TextSlot(id='slot.label.rect', prompt='', text='직사각형', style_role='label', x=324.0, y=144.0, font_size=28), TextSlot(id='slot.label.square', prompt='', text='정사각형', style_role='label', x=503.0, y=144.0, font_size=28), TextSlot(id='slot.sentence.1', prompt='', text='직사각형은 마주 보는 ( 두, 네 ) 변의 길이가 같습니다.', style_role='question', x=98.0, y=192.0, font_size=28), TextSlot(id='slot.sentence.2', prompt='', text='정사각형은 ( 두, 네 ) 변의 길이가 모두 같습니다.', style_role='question', x=118.0, y=230.0, font_size=28), LineSlot(id='slot.shape.rect.corner1.a', prompt='', x1=286.0, y1=42.0, x2=296.0, y2=42.0), LineSlot(id='slot.shape.rect.corner1.b', prompt='', x1=286.0, y1=42.0, x2=286.0, y2=52.0), LineSlot(id='slot.shape.rect.corner2.a', prompt='', x1=412.0, y1=42.0, x2=402.0, y2=42.0), LineSlot(id='slot.shape.rect.corner2.b', prompt='', x1=412.0, y1=42.0, x2=412.0, y2=52.0), LineSlot(id='slot.shape.rect.corner3.a', prompt='', x1=286.0, y1=130.0, x2=296.0, y2=130.0), LineSlot(id='slot.shape.rect.corner3.b', prompt='', x1=286.0, y1=130.0, x2=286.0, y2=120.0), LineSlot(id='slot.shape.rect.corner4.a', prompt='', x1=412.0, y1=130.0, x2=402.0, y2=130.0), LineSlot(id='slot.shape.rect.corner4.b', prompt='', x1=412.0, y1=130.0, x2=412.0, y2=120.0), LineSlot(id='slot.shape.square.corner1.a', prompt='', x1=486.0, y1=42.0, x2=496.0, y2=42.0), LineSlot(id='slot.shape.square.corner1.b', prompt='', x1=486.0, y1=42.0, x2=486.0, y2=52.0), LineSlot(id='slot.shape.square.corner2.a', prompt='', x1=562.0, y1=42.0, x2=552.0, y2=42.0), LineSlot(id='slot.shape.square.corner2.b', prompt='', x1=562.0, y1=42.0, x2=562.0, y2=52.0), LineSlot(id='slot.shape.square.corner3.a', prompt='', x1=486.0, y1=118.0, x2=496.0, y2=118.0), LineSlot(id='slot.shape.square.corner3.b', prompt='', x1=486.0, y1=118.0, x2=486.0, y2=108.0), LineSlot(id='slot.shape.square.corner4.a', prompt='', x1=562.0, y1=118.0, x2=552.0, y2=118.0), LineSlot(id='slot.shape.square.corner4.b', prompt='', x1=562.0, y1=118.0, x2=562.0, y2=108.0)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008998', 'problem_type': '도형의 성질 선택', 'metadata': {'language': 'ko', 'question': '그림을 보고 알맞은 말을 선택하는 문제', 'instruction': '직사각형과 정사각형의 성질을 읽고 괄호 안 알맞은 말을 고른다.'}, 'domain': {'objects': [{'id': 'obj.rectangle', 'type': 'quadrilateral', 'name': '직사각형'}, {'id': 'obj.square', 'type': 'quadrilateral', 'name': '정사각형'}, {'id': 'obj.choice_2_4', 'type': 'choice', 'candidates': ['두', '네']}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.rectangle', 'obj.square', 'obj.choice_2_4'], 'target_ref': 'answer.target', 'condition_refs': ['rel.rectangle_opposite_sides_equal', 'rel.square_all_sides_equal']}, 'plan': {'method': '도형의 성질 비교', 'description': '각 도형의 변의 길이 성질을 읽고 괄호 안 말이 두인지 네인지 고른다.'}, 'execute': {'expected_operations': ['직사각형의 성질 확인', '정사각형의 성질 확인', '알맞은 말 선택']}, 'review': {'check_methods': ['도형 이름과 성질 대응 확인', '문장 의미와 선택어 일치 확인']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': '직사각형과 정사각형 문장의 괄호 안 알맞은 말'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008998', 'problem_type': '도형의 성질 선택', 'inputs': {'total_ticks': 2, 'target_label': '괄호 안 알맞은 말', 'target_ticks': 2, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.rectangle', 'value': {'name': '직사각형'}}, {'ref': 'obj.square', 'value': {'name': '정사각형'}}], 'target': {'ref': 'answer.target', 'type': 'choice_selection'}, 'method': '도형의 성질 비교', 'plan': ['직사각형과 정사각형의 성질을 읽는다.', '문장 속 괄호에서 알맞은 말을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '직사각형은 마주 보는 변의 길이가 같다.', 'value': '두'}, {'id': 'step.2', 'expr': '정사각형은 네 변의 길이가 모두 같다.', 'value': '네'}], 'checks': [{'id': 'check.1', 'expr': '직사각형의 선택어가 성질과 맞는가', 'expected': '두', 'actual': '두', 'pass': True}, {'id': 'check.2', 'expr': '정사각형의 선택어가 성질과 맞는가', 'expected': '네', 'actual': '네', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': '직사각형과 정사각형 문장의 괄호 안 알맞은 말'}, 'value': 0, 'unit': ''}}
