from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008911', title='표를 읽고 가장 많은 값을 고르기', canvas=Canvas(width=960.0, height=420.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.table_title', 'slot.table_outer', 'slot.h1', 'slot.h2', 'slot.view')),), slots=(TextSlot(id='slot.q1', prompt='', text='□ 77. 정국이네 반 학생들이 생일에 받고 싶은 선물을 사주하여 표로 나타냈습니다.\n가장 많은 학생들이 받고 싶은 선물을 선택하세요.', style_role='question', x=14.0, y=24.0, font_size=28), TextSlot(id='slot.table_title', prompt='', text='생일에 받고 싶은 선물별 학생 수', style_role='body', x=260.0, y=108.0, font_size=28), RectSlot(id='slot.table_outer', prompt='', x=140.0, y=140.0, width=690.0, height=80.0), TextSlot(id='slot.h1', prompt='', text='선물    책    휴대전화    게임기    옷    합계', style_role='body', x=162.0, y=169.0, font_size=28), TextSlot(id='slot.h2', prompt='', text='학생 수(명)    6    12    8    4    30', style_role='body', x=160.0, y=206.0, font_size=28), TextSlot(id='slot.view', prompt='', text='( 책 , 휴대전화 , 게임기 , 옷 )', style_role='body', x=610.0, y=266.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008911', 'problem_type': 'table_max_selection', 'metadata': {'language': 'ko', 'question': '표에서 가장 많은 학생들이 받고 싶은 선물을 고르는 문제', 'instruction': '가장 많은 학생들이 받고 싶은 선물을 선택하세요.', 'points': 0}, 'domain': {'objects': [{'id': 'obj.table', 'type': 'table', 'title': '생일에 받고 싶은 선물별 학생 수'}, {'id': 'obj.gift.book', 'type': 'gift', 'name': '책'}, {'id': 'obj.gift.phone', 'type': 'gift', 'name': '휴대전화'}, {'id': 'obj.gift.game', 'type': 'gift', 'name': '게임기'}, {'id': 'obj.gift.clothes', 'type': 'gift', 'name': '옷'}, {'id': 'obj.count.book', 'type': 'count', 'value': 6}, {'id': 'obj.count.phone', 'type': 'count', 'value': 12}, {'id': 'obj.count.game', 'type': 'count', 'value': 8}, {'id': 'obj.count.clothes', 'type': 'count', 'value': 4}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.gift.book', 'obj.gift.phone', 'obj.gift.game', 'obj.gift.clothes'], 'target_ref': 'answer.target', 'condition_refs': ['rel.max_count']}, 'plan': {'method': 'compare_table_values', 'description': '표의 학생 수를 비교해 가장 큰 값에 대응하는 선물을 찾는다.'}, 'execute': {'expected_operations': ['read_table_values', 'compare_counts', 'select_maximum']}, 'review': {'check_methods': ['maximum_value_check', 'table_entry_match_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'gift_name', 'description': '가장 많은 학생들이 받고 싶은 선물'}, 'value': '휴대전화', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008911', 'problem_type': 'table_max_selection', 'inputs': {'total_ticks': 0, 'target_label': '가장 많은 학생들이 받고 싶은 선물', 'target_ticks': 0, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.count.book', 'value': 6}, {'ref': 'obj.count.phone', 'value': 12}, {'ref': 'obj.count.game', 'value': 8}, {'ref': 'obj.count.clothes', 'value': 4}], 'target': {'ref': 'answer.target', 'type': 'gift_name'}, 'method': 'compare_table_values', 'plan': ['표에 있는 학생 수를 하나씩 비교한다.', '가장 큰 수에 대응하는 선물을 찾는다.'], 'steps': [{'id': 'step.1', 'expr': '6, 12, 8, 4 중 가장 큰 수를 찾는다.', 'value': 12}, {'id': 'step.2', 'expr': '12에 대응하는 선물을 찾는다.', 'value': '휴대전화'}], 'checks': [{'id': 'check.1', 'expr': '12가 6, 8, 4보다 큰지 확인한다.', 'expected': True, 'actual': True, 'pass': True}, {'id': 'check.2', 'expr': '12의 대응 항목이 휴대전화인지 확인한다.', 'expected': '휴대전화', 'actual': '휴대전화', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'gift_name', 'description': '가장 많은 학생들이 받고 싶은 선물'}, 'value': '휴대전화', 'unit': ''}}
