from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008745', title='들이 비교', canvas=Canvas(width=960, height=480, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2', 'slot.q3')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.diagram.left.bottle', 'slot.diagram.left.bucket', 'slot.diagram.right.bottle', 'slot.diagram.right.bucket', 'slot.diagram.label.ga', 'slot.diagram.label.na', 'slot.diagram.left.water', 'slot.diagram.right.water')), Region(id='region.choice', role='choice', flow='absolute', slot_ids=('slot.choice.1', 'slot.choice.2')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='□ 42.  가 물병과 나 물병에 물을 가득 채운 후 모양과 크기가 같은 그릇에 옮겨', style_role='question', x=16.0, y=34.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='담았습니다. 그림과 같이 물을 채웠을 때에 가 물병과 나 물병의 들이를 비교하', style_role='question', x=16.0, y=68.0, font_size=28), TextSlot(id='slot.q3', prompt='', text='려고 합니다. 알맞은 말을 선택하세요.', style_role='question', x=16.0, y=102.0, font_size=28), RectSlot(id='slot.diagram.left.bottle', prompt='', x=298.0, y=108.0, width=88.0, height=34.0), RectSlot(id='slot.diagram.left.bucket', prompt='', x=364.0, y=176.0, width=92.0, height=70.0), RectSlot(id='slot.diagram.right.bottle', prompt='', x=558.0, y=102.0, width=92.0, height=36.0), RectSlot(id='slot.diagram.right.bucket', prompt='', x=530.0, y=172.0, width=96.0, height=76.0), TextSlot(id='slot.diagram.label.ga', prompt='', text='가', style_role='label', x=334.0, y=128.0, font_size=28), TextSlot(id='slot.diagram.label.na', prompt='', text='나', style_role='label', x=598.0, y=122.0, font_size=28), RectSlot(id='slot.diagram.left.water', prompt='', x=372.0, y=218.0, width=76.0, height=18.0), RectSlot(id='slot.diagram.right.water', prompt='', x=538.0, y=208.0, width=80.0, height=28.0), TextSlot(id='slot.choice.1', prompt='', text='(1) 옮겨 담은 물의 높이가 더 높은 것은 ( 가 물병, 나 물병)입니다.', style_role='question', x=36.0, y=314.0, font_size=28), TextSlot(id='slot.choice.2', prompt='', text='(2) 들이가 더 많은 것은 ( 가 물병, 나 물병)입니다.', style_role='question', x=36.0, y=350.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008745', 'problem_type': '비교', 'metadata': {'language': 'ko', 'question': '가 물병과 나 물병의 들이를 비교하는 문제', 'instruction': '알맞은 말을 선택하세요.'}, 'domain': {'objects': [{'id': 'obj.bottle.ga', 'type': '물병', 'label': '가 물병'}, {'id': 'obj.bottle.na', 'type': '물병', 'label': '나 물병'}, {'id': 'obj.container.left', 'type': '그릇', 'label': '왼쪽 그릇', 'same_shape_as': 'obj.container.right', 'same_size_as': 'obj.container.right'}, {'id': 'obj.container.right', 'type': '그릇', 'label': '오른쪽 그릇', 'same_shape_as': 'obj.container.left', 'same_size_as': 'obj.container.left'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.bottle.ga', 'obj.bottle.na', 'obj.container.left', 'obj.container.right'], 'target_ref': 'answer.target', 'condition_refs': ['rel.compare.height', 'rel.compare.capacity']}, 'plan': {'method': 'same_container_height_comparison', 'description': '같은 모양과 크기의 그릇에 옮겨 담은 물의 높이를 비교하여 들이의 많고 적음을 판단한다.'}, 'execute': {'expected_operations': ['compare_water_heights', 'infer_capacity_relation']}, 'review': {'check_methods': ['same_container_rule_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': '옮겨 담은 물의 높이가 더 높은 것과 들이가 더 많은 것'}, 'value': '나 물병', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008745', 'problem_type': '비교', 'inputs': {'total_ticks': 2, 'target_label': '가 물병, 나 물병', 'target_ticks': 2, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.bottle.ga', 'value': {'label': '가 물병'}}, {'ref': 'obj.bottle.na', 'value': {'label': '나 물병'}}], 'target': {'ref': 'answer.target', 'type': 'choice_selection'}, 'method': 'same_container_rule_check', 'plan': ['같은 모양과 크기의 그릇에 옮겨 담은 물의 높이를 비교한다.', '물의 높이가 더 높은 쪽의 들이가 더 많다고 판단한다.'], 'steps': [{'id': 'step.1', 'expr': '그림에서 오른쪽 그릇의 물 높이가 더 높다', 'value': '나 물병'}, {'id': 'step.2', 'expr': '같은 그릇에서는 물 높이가 더 높은 쪽의 들이가 더 많다', 'value': '나 물병'}], 'checks': [{'id': 'check.1', 'expr': '같은 모양과 크기의 그릇 비교인지 확인', 'expected': True, 'actual': True, 'pass': True}, {'id': 'check.2', 'expr': '정답 선택이 그림의 높이 비교와 일치하는지 확인', 'expected': '나 물병', 'actual': '나 물병', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': '옮겨 담은 물의 높이가 더 높은 것과 들이가 더 많은 것'}, 'value': '나 물병', 'unit': ''}}
