from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008687', title='알맞은 말을 선택하세요', canvas=Canvas(width=880, height=516, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1',)), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.circle.outer', 'slot.radius.horizontal', 'slot.radius.diagonal', 'slot.pt.center', 'slot.pt.above', 'slot.box', 'slot.box.line1', 'slot.box.line2'))), slots=(TextSlot(id='slot.q1', prompt='', text='76. 알맞은 말을 선택하세요.', style_role='question', x=16.0, y=30.0, font_size=28), CircleSlot(id='slot.circle.outer', prompt='', cx=489.0, cy=163.0, r=118.0, fill='none'), LineSlot(id='slot.radius.horizontal', prompt='', x1=489.0, y1=163.0, x2=371.0, y2=163.0), LineSlot(id='slot.radius.diagonal', prompt='', x1=489.0, y1=163.0, x2=432.0, y2=65.0), CircleSlot(id='slot.pt.center', prompt='', cx=489.0, cy=163.0, r=3.5, fill='#ff2aa8'), CircleSlot(id='slot.pt.above', prompt='', cx=491.0, cy=149.0, r=4.0, fill='none'), RectSlot(id='slot.box', prompt='', x=104.0, y=286.0, width=750.0, height=121.0, fill='none'), TextSlot(id='slot.box.line1', prompt='', text='한 원에는 반지름을 ( 2개만 , 무수히 많이 ) 그을 수 있고', style_role='question', x=147.0, y=329.0, font_size=28), TextSlot(id='slot.box.line2', prompt='', text='그 길이는 모두 ( 같습니다, 다릅니다 ).', style_role='question', x=242.0, y=371.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008687', 'problem_type': 'multiple_choice', 'metadata': {'language': 'ko', 'question': '알맞은 말을 선택하세요.', 'instruction': '원에서 반지름의 개수와 길이에 대한 알맞은 말을 고르는 문제'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.radius', 'type': 'radius', 'relation': 'from_center_to_circle'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle', 'obj.radius'], 'target_ref': 'answer.target', 'condition_refs': ['rel.radius_count', 'rel.radius_length']}, 'plan': {'method': 'concept_selection', 'description': '원의 반지름에 대한 개념을 보고 알맞은 선택지를 고른다.'}, 'execute': {'expected_operations': ['identify_radius_property', 'select_matching_words']}, 'review': {'check_methods': ['compare_with_radius_definition', 'check_consistency_of_selected_words']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_words', 'description': '한 원에는 반지름을 ( 2개만 , 무수히 많이 ) 그을 수 있고 그 길이는 모두 ( 같습니다, 다릅니다 ).'}, 'value': '무수히 많이, 같습니다', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008687', 'problem_type': 'multiple_choice', 'inputs': {'total_ticks': 0, 'target_label': 'selected_words', 'target_ticks': 0, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': 'circle'}, {'ref': 'obj.radius', 'value': 'radius_from_center_to_circle'}], 'target': {'ref': 'answer.target', 'type': 'selected_words'}, 'method': 'concept_selection', 'plan': ['원의 반지름에 대한 성질을 확인한다.', '개수와 길이에 맞는 선택지를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '원의 반지름 성질 확인', 'value': '무수히 많이, 같습니다'}], 'checks': [{'id': 'check.1', 'expr': '반지름은 무수히 많이 그을 수 있고 길이는 모두 같은가', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_words', 'description': '한 원에는 반지름을 ( 2개만 , 무수히 많이 ) 그을 수 있고 그 길이는 모두 ( 같습니다, 다릅니다 ).'}, 'value': '무수히 많이, 같습니다', 'unit': ''}}
