from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009025', title='삼각형을 보고 알맞은 기호를 모두 선택하세요', canvas=Canvas(width=724.0, height=304.0, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.qnum', 'slot.instruction')), Region(id='region.shapes', role='figure', flow='absolute', slot_ids=('slot.lb.ga', 'slot.lb.na', 'slot.lb.da', 'slot.lb.ra', 'slot.tri.ga.1', 'slot.tri.ga.2', 'slot.tri.ga.3', 'slot.tri.na.1', 'slot.tri.na.2', 'slot.tri.na.3', 'slot.tri.da.1', 'slot.tri.da.2', 'slot.tri.da.3', 'slot.tri.ra.1', 'slot.tri.ra.2', 'slot.tri.ra.3')), Region(id='region.choice', role='stem', flow='absolute', slot_ids=('slot.choice_main', 'slot.choice_bottom_1', 'slot.choice_bottom_2'))), slots=(TextSlot(id='slot.qnum', prompt='', text='64.', style_role='question', x=22.0, y=28.0, font_size=28), TextSlot(id='slot.instruction', prompt='', text='삼각형을 보고 알맞은 기호를 모두 선택하세요.', style_role='question', x=92.0, y=28.0, font_size=28), TextSlot(id='slot.lb.ga', prompt='', text='가', style_role='label', x=112.0, y=62.0, font_size=28), TextSlot(id='slot.lb.na', prompt='', text='나', style_role='label', x=278.0, y=62.0, font_size=28), TextSlot(id='slot.lb.da', prompt='', text='다', style_role='label', x=444.0, y=62.0, font_size=28), TextSlot(id='slot.lb.ra', prompt='', text='라', style_role='label', x=605.0, y=62.0, font_size=28), LineSlot(id='slot.tri.ga.1', prompt='', x1=170.0, y1=42.0, x2=150.0, y2=112.0), LineSlot(id='slot.tri.ga.2', prompt='', x1=170.0, y1=42.0, x2=205.0, y2=112.0), LineSlot(id='slot.tri.ga.3', prompt='', x1=150.0, y1=112.0, x2=205.0, y2=112.0), LineSlot(id='slot.tri.na.1', prompt='', x1=320.0, y1=48.0, x2=320.0, y2=112.0), LineSlot(id='slot.tri.na.2', prompt='', x1=320.0, y1=48.0, x2=388.0, y2=112.0), LineSlot(id='slot.tri.na.3', prompt='', x1=320.0, y1=112.0, x2=388.0, y2=112.0), LineSlot(id='slot.tri.da.1', prompt='', x1=492.0, y1=106.0, x2=583.0, y2=54.0), LineSlot(id='slot.tri.da.2', prompt='', x1=492.0, y1=106.0, x2=544.0, y2=106.0), LineSlot(id='slot.tri.da.3', prompt='', x1=544.0, y1=106.0, x2=583.0, y2=54.0), LineSlot(id='slot.tri.ra.1', prompt='', x1=648.0, y1=44.0, x2=690.0, y2=44.0), LineSlot(id='slot.tri.ra.2', prompt='', x1=690.0, y1=44.0, x2=690.0, y2=112.0), LineSlot(id='slot.tri.ra.3', prompt='', x1=648.0, y1=44.0, x2=690.0, y2=112.0), TextSlot(id='slot.choice_main', prompt='', text='(1) 직각이 있는 삼각형은 ( 가, 나, 다, 라 )입니다.', style_role='question', x=18.0, y=164.0, font_size=28), TextSlot(id='slot.choice_bottom_1', prompt='', text='(1) 직각이 있는 삼각형은 나, 라입니다.', style_role='question', x=8.0, y=210.0, font_size=24), TextSlot(id='slot.choice_bottom_2', prompt='', text='(1) 나, 라', style_role='question', x=8.0, y=248.0, font_size=24)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009025', 'problem_type': '도형_판별', 'metadata': {'language': 'ko', 'question': '삼각형을 보고 알맞은 기호를 모두 선택하세요.', 'instruction': '직각이 있는 삼각형을 고르는 문항이다.'}, 'domain': {'objects': [{'id': 'obj.triangle.ga', 'type': 'triangle', 'label': '가'}, {'id': 'obj.triangle.na', 'type': 'triangle', 'label': '나'}, {'id': 'obj.triangle.da', 'type': 'triangle', 'label': '다'}, {'id': 'obj.triangle.ra', 'type': 'triangle', 'label': '라'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.triangle.ga', 'obj.triangle.na', 'obj.triangle.da', 'obj.triangle.ra'], 'target_ref': 'answer.target', 'condition_refs': ['rel.select_right_triangle']}, 'plan': {'method': 'shape_classification', 'description': '각 삼각형이 직각삼각형인지 보고 해당 기호를 고른다.'}, 'execute': {'expected_operations': ['inspect_triangle_shapes', 'identify_right_angles', 'select_matching_labels']}, 'review': {'check_methods': ['compare_selected_labels_with_figures', 'confirm_only_right_triangle_labels_are_selected']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_labels', 'description': '직각이 있는 삼각형의 기호'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009025', 'problem_type': '도형_판별', 'inputs': {'total_ticks': 4, 'target_label': '직각이 있는 삼각형', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.triangle.ga', 'value': {'label': '가'}}, {'ref': 'obj.triangle.na', 'value': {'label': '나'}}, {'ref': 'obj.triangle.da', 'value': {'label': '다'}}, {'ref': 'obj.triangle.ra', 'value': {'label': '라'}}], 'target': {'ref': 'answer.target', 'type': 'selected_labels'}, 'method': 'shape_classification', 'plan': ['네 개의 삼각형을 보고 직각이 있는지 확인한다.', '직각이 있는 삼각형에 해당하는 기호를 선택한다.'], 'steps': [{'id': 'step.1', 'expr': '삼각형 4개를 확인한다.', 'value': 4}, {'id': 'step.2', 'expr': '직각이 있는 삼각형의 기호를 고른다.', 'value': 0}], 'checks': [{'id': 'check.1', 'expr': '선택한 기호가 직각이 있는 삼각형에 해당하는지 확인한다.', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_labels', 'description': '직각이 있는 삼각형의 기호'}, 'value': 0, 'unit': ''}}
