from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008873",
        title="수조에 물을 가득 채우기",
        canvas=Canvas(width=940.0, height=372.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q_num",
                    "slot.q_text1",
                    "slot.q_text2",
                    "slot.table.outer",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.c1r1",
                    "slot.table.c2r1",
                    "slot.table.c3r1",
                    "slot.table.c0r2",
                    "slot.table.c1r2",
                    "slot.table.c2r2",
                    "slot.table.c3r2",
                    "slot.choice_line",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q_num",
                prompt="",
                text="26.",
                style_role="question",
                x=12.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q_text1",
                prompt="",
                text="수조에 물을 가득 채우려면 다음과 같이 각각 부어야 합니다.",
                style_role="question",
                x=88.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q_text2",
                prompt="",
                text="㉠ 그릇, ㉡ 그릇, ㉢ 그릇 중 들이가 가장 많은 것을 선택해 보세요.",
                style_role="question",
                x=28.0,
                y=66.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=188.0,
                y=94.0,
                width=582.0,
                height=86.0,
                fill="#EEF4DB",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.h1",
                prompt="",
                x=188.0,
                y=126.0,
                width=582.0,
                height=0.0,
                fill="none",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.h2",
                prompt="",
                x=188.0,
                y=164.0,
                width=582.0,
                height=0.0,
                fill="none",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v1",
                prompt="",
                x=336.0,
                y=94.0,
                width=0.0,
                height=86.0,
                fill="none",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v2",
                prompt="",
                x=485.0,
                y=94.0,
                width=0.0,
                height=86.0,
                fill="none",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v3",
                prompt="",
                x=634.0,
                y=94.0,
                width=0.0,
                height=86.0,
                fill="none",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.v4",
                prompt="",
                x=770.0,
                y=94.0,
                width=0.0,
                height=86.0,
                fill="none",
                stroke="#A9C36A",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.table.c0r2",
                prompt="",
                text="그릇의 수",
                style_role="body",
                x=218.0,
                y=151.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c1r1",
                prompt="",
                text="㉠ 그릇",
                style_role="body",
                x=371.0,
                y=119.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c2r1",
                prompt="",
                text="㉡ 그릇",
                style_role="body",
                x=519.0,
                y=119.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c3r1",
                prompt="",
                text="㉢ 그릇",
                style_role="body",
                x=670.0,
                y=119.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c1r2",
                prompt="",
                text="3개",
                style_role="body",
                x=390.0,
                y=156.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c2r2",
                prompt="",
                text="6개",
                style_role="body",
                x=541.0,
                y=156.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.c3r2",
                prompt="",
                text="4개",
                style_role="body",
                x=690.0,
                y=156.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice_line",
                prompt="",
                text="( ㉠ 그릇, ㉡ 그릇, ㉢ 그릇 )",
                style_role="body",
                x=303.0,
                y=210.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("비교", "표", "들이다"),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008873",
    "problem_type": "comparison_selection",
    "metadata": {
        "language": "ko",
        "question": "수조에 물을 가득 채우기 위해 부은 그릇의 수를 비교하여 들이가 가장 많은 것을 고르는 문제",
        "instruction": "가, 나, 다 그릇 중 들이가 가장 많은 것을 선택하시오.",
        "points": 5,
    },
    "domain": {
        "objects": [
            {"id": "obj.g1", "type": "container_option", "label": "가 그릇"},
            {"id": "obj.g2", "type": "container_option", "label": "나 그릇"},
            {"id": "obj.g3", "type": "container_option", "label": "다 그릇"},
            {"id": "obj.count.g1", "type": "count", "value": 3},
            {"id": "obj.count.g2", "type": "count", "value": 6},
            {"id": "obj.count.g3", "type": "count", "value": 4},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.count.g1", "obj.count.g2", "obj.count.g3"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare", "rel.inverse"],
            },
            "plan": {
                "method": "compare_inverse_quantity",
                "description": "부은 그릇의 수를 비교하여 가장 작은 수에 해당하는 선택지를 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_counts",
                    "compare_numbers",
                    "select_smallest_count_option",
                ]
            },
            "review": {"check_methods": ["ordering_check", "rule_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "option_selection", "description": "들이가 가장 많은 그릇"},
        "value": "가 그릇",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008873",
    "problem_type": "comparison_selection",
    "inputs": {
        "total_ticks": 3,
        "target_label": "들이가 가장 많은 그릇",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "개",
    },
    "given": [
        {"ref": "obj.count.g1", "value": 3},
        {"ref": "obj.count.g2", "value": 6},
        {"ref": "obj.count.g3", "value": 4},
    ],
    "target": {"ref": "answer.target", "type": "option_selection"},
    "method": "compare_inverse_quantity",
    "plan": ["부은 그릇의 수를 비교한다.", "가장 작은 수에 해당하는 선택지를 찾는다."],
    "steps": [
        {"id": "step.1", "expr": "3 < 4 < 6", "value": "3<4<6"},
        {"id": "step.2", "expr": "가장 작은 수는 3이므로 해당 선택지를 고른다", "value": "가 그릇"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "3<4<6의 순서가 맞는지 확인",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "가장 작은 수에 해당하는 선택지가 가 그릇인지 확인",
            "expected": "가 그릇",
            "actual": "가 그릇",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "option_selection", "description": "들이가 가장 많은 그릇"},
        "value": "가 그릇",
        "unit": "",
    },
}
