from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    LineSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008670",
        title="규칙에 따라 원을 4개 더 그리기",
        canvas=Canvas(width=940, height=590, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2"),
            ),
            Region(
                id="region.diagram.top1",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.top1.box",
                    "slot.top1.grid.v1",
                    "slot.top1.grid.v2",
                    "slot.top1.grid.v3",
                    "slot.top1.grid.v4",
                    "slot.top1.grid.v5",
                    "slot.top1.grid.v6",
                    "slot.top1.grid.v7",
                    "slot.top1.grid.v8",
                    "slot.top1.grid.v9",
                    "slot.top1.grid.v10",
                    "slot.top1.grid.v11",
                    "slot.top1.grid.v12",
                    "slot.top1.grid.v13",
                    "slot.top1.grid.v14",
                    "slot.top1.grid.v15",
                    "slot.top1.grid.v16",
                    "slot.top1.grid.v17",
                    "slot.top1.grid.v18",
                    "slot.top1.grid.v19",
                    "slot.top1.grid.v20",
                    "slot.top1.grid.v21",
                    "slot.top1.grid.h1",
                    "slot.top1.grid.h2",
                    "slot.top1.grid.h3",
                    "slot.top1.grid.h4",
                    "slot.top1.grid.h5",
                    "slot.top1.grid.h6",
                    "slot.top1.grid.h7",
                    "slot.top1.grid.h8",
                    "slot.top1.grid.h9",
                    "slot.top1.grid.h10",
                    "slot.top1.grid.h11",
                    "slot.top1.grid.h12",
                    "slot.top1.grid.h13",
                    "slot.top1.grid.h14",
                    "slot.top1.grid.h15",
                    "slot.top1.grid.h16",
                    "slot.top1.grid.h17",
                    "slot.top1.grid.h18",
                    "slot.top1.grid.h19",
                    "slot.top1.grid.h20",
                    "slot.top1.c1",
                    "slot.top1.c2",
                    "slot.top1.c3",
                    "slot.top1.c4",
                    "slot.top1.c5",
                    "slot.top1.c6",
                    "slot.top1.c7",
                    "slot.top1.c8",
                    "slot.top1.c9",
                    "slot.top1.c10",
                    "slot.top1.c11",
                    "slot.top1.c12",
                ),
            ),
            Region(
                id="region.diagram.top2",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.top2.box",
                    "slot.top2.grid.v1",
                    "slot.top2.grid.v2",
                    "slot.top2.grid.v3",
                    "slot.top2.grid.v4",
                    "slot.top2.grid.v5",
                    "slot.top2.grid.v6",
                    "slot.top2.grid.v7",
                    "slot.top2.grid.v8",
                    "slot.top2.grid.v9",
                    "slot.top2.grid.v10",
                    "slot.top2.grid.v11",
                    "slot.top2.grid.v12",
                    "slot.top2.grid.v13",
                    "slot.top2.grid.v14",
                    "slot.top2.grid.v15",
                    "slot.top2.grid.v16",
                    "slot.top2.grid.v17",
                    "slot.top2.grid.v18",
                    "slot.top2.grid.v19",
                    "slot.top2.grid.v20",
                    "slot.top2.grid.v21",
                    "slot.top2.grid.h1",
                    "slot.top2.grid.h2",
                    "slot.top2.grid.h3",
                    "slot.top2.grid.h4",
                    "slot.top2.grid.h5",
                    "slot.top2.grid.h6",
                    "slot.top2.grid.h7",
                    "slot.top2.grid.h8",
                    "slot.top2.grid.h9",
                    "slot.top2.grid.h10",
                    "slot.top2.grid.h11",
                    "slot.top2.grid.h12",
                    "slot.top2.grid.h13",
                    "slot.top2.grid.h14",
                    "slot.top2.grid.h15",
                    "slot.top2.grid.h16",
                    "slot.top2.grid.h17",
                    "slot.top2.grid.h18",
                    "slot.top2.grid.h19",
                    "slot.top2.grid.h20",
                    "slot.top2.c1",
                    "slot.top2.c2",
                    "slot.top2.c3",
                    "slot.top2.c4",
                    "slot.top2.c5",
                    "slot.top2.c6",
                    "slot.top2.c7",
                    "slot.top2.c8",
                    "slot.top2.c9",
                    "slot.top2.c10",
                    "slot.top2.c11",
                    "slot.top2.c12",
                ),
            ),
            Region(
                id="region.answer",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.answer.box",
                    "slot.answer.grid.v1",
                    "slot.answer.grid.v2",
                    "slot.answer.grid.v3",
                    "slot.answer.grid.v4",
                    "slot.answer.grid.v5",
                    "slot.answer.grid.v6",
                    "slot.answer.grid.v7",
                    "slot.answer.grid.v8",
                    "slot.answer.grid.v9",
                    "slot.answer.grid.v10",
                    "slot.answer.grid.v11",
                    "slot.answer.grid.v12",
                    "slot.answer.grid.v13",
                    "slot.answer.grid.v14",
                    "slot.answer.grid.v15",
                    "slot.answer.grid.v16",
                    "slot.answer.grid.v17",
                    "slot.answer.grid.v18",
                    "slot.answer.grid.v19",
                    "slot.answer.grid.v20",
                    "slot.answer.grid.v21",
                    "slot.answer.grid.h1",
                    "slot.answer.grid.h2",
                    "slot.answer.grid.h3",
                    "slot.answer.grid.h4",
                    "slot.answer.grid.h5",
                    "slot.answer.grid.h6",
                    "slot.answer.grid.h7",
                    "slot.answer.grid.h8",
                    "slot.answer.grid.h9",
                    "slot.answer.grid.h10",
                    "slot.answer.grid.h11",
                    "slot.answer.grid.h12",
                    "slot.answer.grid.h13",
                    "slot.answer.grid.h14",
                    "slot.answer.grid.h15",
                    "slot.answer.grid.h16",
                    "slot.answer.grid.h17",
                    "slot.answer.grid.h18",
                    "slot.answer.grid.h19",
                    "slot.answer.grid.h20",
                    "slot.answer.c1",
                    "slot.answer.c2",
                    "slot.answer.c3",
                    "slot.answer.c4",
                    "slot.answer.c5",
                    "slot.answer.c6",
                ),
            ),
            Region(id="region.explanation", role="note", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="49.  규칙에 따라 원을 4개 더 그리려고 합니다. 바르게 그린 것을 선택하세",
                style_role="question",
                x=10.0,
                y=30.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="요.",
                style_role="question",
                x=10.0,
                y=60.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.top1.box",
                prompt="",
                x=286.0,
                y=87.0,
                width=370.0,
                height=108.0,
            ),
            LineSlot(
                id="slot.top1.grid.v1",
                prompt="",
                x1=299.0,
                y1=87.0,
                x2=299.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v2",
                prompt="",
                x1=314.0,
                y1=87.0,
                x2=314.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v3",
                prompt="",
                x1=329.0,
                y1=87.0,
                x2=329.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v4",
                prompt="",
                x1=344.0,
                y1=87.0,
                x2=344.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v5",
                prompt="",
                x1=359.0,
                y1=87.0,
                x2=359.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v6",
                prompt="",
                x1=374.0,
                y1=87.0,
                x2=374.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v7",
                prompt="",
                x1=389.0,
                y1=87.0,
                x2=389.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v8",
                prompt="",
                x1=404.0,
                y1=87.0,
                x2=404.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v9",
                prompt="",
                x1=419.0,
                y1=87.0,
                x2=419.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v10",
                prompt="",
                x1=434.0,
                y1=87.0,
                x2=434.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v11",
                prompt="",
                x1=449.0,
                y1=87.0,
                x2=449.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v12",
                prompt="",
                x1=464.0,
                y1=87.0,
                x2=464.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v13",
                prompt="",
                x1=479.0,
                y1=87.0,
                x2=479.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v14",
                prompt="",
                x1=494.0,
                y1=87.0,
                x2=494.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v15",
                prompt="",
                x1=509.0,
                y1=87.0,
                x2=509.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v16",
                prompt="",
                x1=524.0,
                y1=87.0,
                x2=524.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v17",
                prompt="",
                x1=539.0,
                y1=87.0,
                x2=539.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v18",
                prompt="",
                x1=554.0,
                y1=87.0,
                x2=554.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v19",
                prompt="",
                x1=569.0,
                y1=87.0,
                x2=569.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v20",
                prompt="",
                x1=584.0,
                y1=87.0,
                x2=584.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.v21",
                prompt="",
                x1=599.0,
                y1=87.0,
                x2=599.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h1",
                prompt="",
                x1=286.0,
                y1=95.0,
                x2=656.0,
                y2=95.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h2",
                prompt="",
                x1=286.0,
                y1=106.0,
                x2=656.0,
                y2=106.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h3",
                prompt="",
                x1=286.0,
                y1=117.0,
                x2=656.0,
                y2=117.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h4",
                prompt="",
                x1=286.0,
                y1=128.0,
                x2=656.0,
                y2=128.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h5",
                prompt="",
                x1=286.0,
                y1=139.0,
                x2=656.0,
                y2=139.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h6",
                prompt="",
                x1=286.0,
                y1=150.0,
                x2=656.0,
                y2=150.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h7",
                prompt="",
                x1=286.0,
                y1=161.0,
                x2=656.0,
                y2=161.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h8",
                prompt="",
                x1=286.0,
                y1=172.0,
                x2=656.0,
                y2=172.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h9",
                prompt="",
                x1=286.0,
                y1=183.0,
                x2=656.0,
                y2=183.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h10",
                prompt="",
                x1=286.0,
                y1=194.0,
                x2=656.0,
                y2=194.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h11",
                prompt="",
                x1=286.0,
                y1=205.0,
                x2=656.0,
                y2=205.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h12",
                prompt="",
                x1=286.0,
                y1=216.0,
                x2=656.0,
                y2=216.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h13",
                prompt="",
                x1=286.0,
                y1=227.0,
                x2=656.0,
                y2=227.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h14",
                prompt="",
                x1=286.0,
                y1=238.0,
                x2=656.0,
                y2=238.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h15",
                prompt="",
                x1=286.0,
                y1=249.0,
                x2=656.0,
                y2=249.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h16",
                prompt="",
                x1=286.0,
                y1=260.0,
                x2=656.0,
                y2=260.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h17",
                prompt="",
                x1=286.0,
                y1=271.0,
                x2=656.0,
                y2=271.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h18",
                prompt="",
                x1=286.0,
                y1=282.0,
                x2=656.0,
                y2=282.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h19",
                prompt="",
                x1=286.0,
                y1=293.0,
                x2=656.0,
                y2=293.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top1.grid.h20",
                prompt="",
                x1=286.0,
                y1=195.0,
                x2=656.0,
                y2=195.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.top1.c1",
                prompt="",
                cx=353.0,
                cy=141.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c2",
                prompt="",
                cx=353.0,
                cy=141.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c3", prompt="", cx=353.0, cy=141.0, r=3.5, fill="#E91E63"
            ),
            CircleSlot(
                id="slot.top1.c4",
                prompt="",
                cx=414.0,
                cy=141.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c5",
                prompt="",
                cx=414.0,
                cy=141.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c6", prompt="", cx=414.0, cy=141.0, r=3.5, fill="#E91E63"
            ),
            CircleSlot(
                id="slot.top1.c7",
                prompt="",
                cx=475.0,
                cy=141.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c8",
                prompt="",
                cx=475.0,
                cy=141.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c9", prompt="", cx=475.0, cy=141.0, r=3.5, fill="#E91E63"
            ),
            CircleSlot(
                id="slot.top1.c10",
                prompt="",
                cx=539.0,
                cy=141.0,
                r=52.0,
                fill="none",
                stroke="#1EA7FF",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c11",
                prompt="",
                cx=539.0,
                cy=141.0,
                r=14.0,
                fill="none",
                stroke="#1EA7FF",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top1.c12", prompt="", cx=539.0, cy=141.0, r=3.5, fill="#1EA7FF"
            ),
            RectSlot(
                id="slot.top2.box",
                prompt="",
                x=286.0,
                y=197.0,
                width=370.0,
                height=138.0,
            ),
            LineSlot(
                id="slot.top2.grid.v1",
                prompt="",
                x1=299.0,
                y1=197.0,
                x2=299.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v2",
                prompt="",
                x1=314.0,
                y1=197.0,
                x2=314.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v3",
                prompt="",
                x1=329.0,
                y1=197.0,
                x2=329.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v4",
                prompt="",
                x1=344.0,
                y1=197.0,
                x2=344.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v5",
                prompt="",
                x1=359.0,
                y1=197.0,
                x2=359.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v6",
                prompt="",
                x1=374.0,
                y1=197.0,
                x2=374.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v7",
                prompt="",
                x1=389.0,
                y1=197.0,
                x2=389.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v8",
                prompt="",
                x1=404.0,
                y1=197.0,
                x2=404.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v9",
                prompt="",
                x1=419.0,
                y1=197.0,
                x2=419.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v10",
                prompt="",
                x1=434.0,
                y1=197.0,
                x2=434.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v11",
                prompt="",
                x1=449.0,
                y1=197.0,
                x2=449.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v12",
                prompt="",
                x1=464.0,
                y1=197.0,
                x2=464.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v13",
                prompt="",
                x1=479.0,
                y1=197.0,
                x2=479.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v14",
                prompt="",
                x1=494.0,
                y1=197.0,
                x2=494.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v15",
                prompt="",
                x1=509.0,
                y1=197.0,
                x2=509.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v16",
                prompt="",
                x1=524.0,
                y1=197.0,
                x2=524.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v17",
                prompt="",
                x1=539.0,
                y1=197.0,
                x2=539.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v18",
                prompt="",
                x1=554.0,
                y1=197.0,
                x2=554.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v19",
                prompt="",
                x1=569.0,
                y1=197.0,
                x2=569.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v20",
                prompt="",
                x1=584.0,
                y1=197.0,
                x2=584.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.v21",
                prompt="",
                x1=599.0,
                y1=197.0,
                x2=599.0,
                y2=335.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h1",
                prompt="",
                x1=286.0,
                y1=205.0,
                x2=656.0,
                y2=205.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h2",
                prompt="",
                x1=286.0,
                y1=216.0,
                x2=656.0,
                y2=216.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h3",
                prompt="",
                x1=286.0,
                y1=227.0,
                x2=656.0,
                y2=227.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h4",
                prompt="",
                x1=286.0,
                y1=238.0,
                x2=656.0,
                y2=238.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h5",
                prompt="",
                x1=286.0,
                y1=249.0,
                x2=656.0,
                y2=249.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h6",
                prompt="",
                x1=286.0,
                y1=260.0,
                x2=656.0,
                y2=260.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h7",
                prompt="",
                x1=286.0,
                y1=271.0,
                x2=656.0,
                y2=271.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h8",
                prompt="",
                x1=286.0,
                y1=282.0,
                x2=656.0,
                y2=282.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h9",
                prompt="",
                x1=286.0,
                y1=293.0,
                x2=656.0,
                y2=293.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h10",
                prompt="",
                x1=286.0,
                y1=304.0,
                x2=656.0,
                y2=304.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h11",
                prompt="",
                x1=286.0,
                y1=315.0,
                x2=656.0,
                y2=315.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h12",
                prompt="",
                x1=286.0,
                y1=326.0,
                x2=656.0,
                y2=326.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h13",
                prompt="",
                x1=286.0,
                y1=337.0,
                x2=656.0,
                y2=337.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h14",
                prompt="",
                x1=286.0,
                y1=197.0,
                x2=656.0,
                y2=197.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h15",
                prompt="",
                x1=286.0,
                y1=347.0,
                x2=656.0,
                y2=347.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h16",
                prompt="",
                x1=286.0,
                y1=358.0,
                x2=656.0,
                y2=358.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h17",
                prompt="",
                x1=286.0,
                y1=369.0,
                x2=656.0,
                y2=369.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h18",
                prompt="",
                x1=286.0,
                y1=380.0,
                x2=656.0,
                y2=380.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h19",
                prompt="",
                x1=286.0,
                y1=391.0,
                x2=656.0,
                y2=391.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.top2.grid.h20",
                prompt="",
                x1=286.0,
                y1=402.0,
                x2=656.0,
                y2=402.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.top2.c1",
                prompt="",
                cx=353.0,
                cy=267.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c2",
                prompt="",
                cx=353.0,
                cy=267.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c3", prompt="", cx=353.0, cy=267.0, r=3.5, fill="#E91E63"
            ),
            CircleSlot(
                id="slot.top2.c4",
                prompt="",
                cx=414.0,
                cy=267.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c5",
                prompt="",
                cx=414.0,
                cy=267.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c6", prompt="", cx=414.0, cy=267.0, r=3.5, fill="#E91E63"
            ),
            CircleSlot(
                id="slot.top2.c7",
                prompt="",
                cx=475.0,
                cy=267.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c8",
                prompt="",
                cx=475.0,
                cy=267.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c9", prompt="", cx=475.0, cy=267.0, r=3.5, fill="#E91E63"
            ),
            CircleSlot(
                id="slot.top2.c10",
                prompt="",
                cx=539.0,
                cy=267.0,
                r=52.0,
                fill="none",
                stroke="#1EA7FF",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c11",
                prompt="",
                cx=539.0,
                cy=267.0,
                r=14.0,
                fill="none",
                stroke="#1EA7FF",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.top2.c12", prompt="", cx=539.0, cy=267.0, r=3.5, fill="#1EA7FF"
            ),
            RectSlot(
                id="slot.answer.box",
                prompt="",
                x=54.0,
                y=381.0,
                width=410.0,
                height=139.0,
            ),
            LineSlot(
                id="slot.answer.grid.v1",
                prompt="",
                x1=56.0,
                y1=381.0,
                x2=56.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v2",
                prompt="",
                x1=71.0,
                y1=381.0,
                x2=71.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v3",
                prompt="",
                x1=86.0,
                y1=381.0,
                x2=86.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v4",
                prompt="",
                x1=101.0,
                y1=381.0,
                x2=101.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v5",
                prompt="",
                x1=116.0,
                y1=381.0,
                x2=116.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v6",
                prompt="",
                x1=131.0,
                y1=381.0,
                x2=131.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v7",
                prompt="",
                x1=146.0,
                y1=381.0,
                x2=146.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v8",
                prompt="",
                x1=161.0,
                y1=381.0,
                x2=161.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v9",
                prompt="",
                x1=176.0,
                y1=381.0,
                x2=176.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v10",
                prompt="",
                x1=191.0,
                y1=381.0,
                x2=191.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v11",
                prompt="",
                x1=206.0,
                y1=381.0,
                x2=206.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v12",
                prompt="",
                x1=221.0,
                y1=381.0,
                x2=221.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v13",
                prompt="",
                x1=236.0,
                y1=381.0,
                x2=236.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v14",
                prompt="",
                x1=251.0,
                y1=381.0,
                x2=251.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v15",
                prompt="",
                x1=266.0,
                y1=381.0,
                x2=266.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v16",
                prompt="",
                x1=281.0,
                y1=381.0,
                x2=281.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v17",
                prompt="",
                x1=296.0,
                y1=381.0,
                x2=296.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v18",
                prompt="",
                x1=311.0,
                y1=381.0,
                x2=311.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v19",
                prompt="",
                x1=326.0,
                y1=381.0,
                x2=326.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v20",
                prompt="",
                x1=341.0,
                y1=381.0,
                x2=341.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.v21",
                prompt="",
                x1=356.0,
                y1=381.0,
                x2=356.0,
                y2=520.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h1",
                prompt="",
                x1=54.0,
                y1=392.0,
                x2=464.0,
                y2=392.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h2",
                prompt="",
                x1=54.0,
                y1=403.0,
                x2=464.0,
                y2=403.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h3",
                prompt="",
                x1=54.0,
                y1=414.0,
                x2=464.0,
                y2=414.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h4",
                prompt="",
                x1=54.0,
                y1=425.0,
                x2=464.0,
                y2=425.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h5",
                prompt="",
                x1=54.0,
                y1=436.0,
                x2=464.0,
                y2=436.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h6",
                prompt="",
                x1=54.0,
                y1=447.0,
                x2=464.0,
                y2=447.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h7",
                prompt="",
                x1=54.0,
                y1=458.0,
                x2=464.0,
                y2=458.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h8",
                prompt="",
                x1=54.0,
                y1=469.0,
                x2=464.0,
                y2=469.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h9",
                prompt="",
                x1=54.0,
                y1=480.0,
                x2=464.0,
                y2=480.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h10",
                prompt="",
                x1=54.0,
                y1=491.0,
                x2=464.0,
                y2=491.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h11",
                prompt="",
                x1=54.0,
                y1=502.0,
                x2=464.0,
                y2=502.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h12",
                prompt="",
                x1=54.0,
                y1=513.0,
                x2=464.0,
                y2=513.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h13",
                prompt="",
                x1=54.0,
                y1=524.0,
                x2=464.0,
                y2=524.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h14",
                prompt="",
                x1=54.0,
                y1=381.0,
                x2=464.0,
                y2=381.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h15",
                prompt="",
                x1=54.0,
                y1=535.0,
                x2=464.0,
                y2=535.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h16",
                prompt="",
                x1=54.0,
                y1=546.0,
                x2=464.0,
                y2=546.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h17",
                prompt="",
                x1=54.0,
                y1=557.0,
                x2=464.0,
                y2=557.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h18",
                prompt="",
                x1=54.0,
                y1=568.0,
                x2=464.0,
                y2=568.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h19",
                prompt="",
                x1=54.0,
                y1=579.0,
                x2=464.0,
                y2=579.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.answer.grid.h20",
                prompt="",
                x1=54.0,
                y1=590.0,
                x2=464.0,
                y2=590.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.answer.c1",
                prompt="",
                cx=121.0,
                cy=452.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.answer.c2",
                prompt="",
                cx=121.0,
                cy=452.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.answer.c3",
                prompt="",
                cx=121.0,
                cy=452.0,
                r=3.5,
                fill="#E91E63",
            ),
            CircleSlot(
                id="slot.answer.c4",
                prompt="",
                cx=182.0,
                cy=452.0,
                r=52.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.answer.c5",
                prompt="",
                cx=182.0,
                cy=452.0,
                r=14.0,
                fill="none",
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.answer.c6",
                prompt="",
                cx=182.0,
                cy=452.0,
                r=3.5,
                fill="#E91E63",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008670",
    "problem_type": "pattern_selection",
    "metadata": {
        "language": "ko",
        "question": "규칙에 따라 원을 4개 더 그리려고 합니다. 바르게 그린 것을 선택하세요.",
        "instruction": "규칙에 따라 원을 4개 더 그리려고 합니다. 바르게 그린 것을 선택하세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle_group", "type": "concentric_circle_pattern"},
            {
                "id": "obj.rule",
                "type": "pattern_rule",
                "description": "중심이 같고 반지름이 각각 1칸, 3칸인 원을 2개 그린 후 중심을 오른쪽으로 4칸씩 옮긴다.",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.rule"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.pattern_applies"],
            },
            "plan": {
                "method": "pattern_matching",
                "description": "규칙에 맞는 원 배치를 그림에서 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_circle_positions",
                    "compare_circle_radii",
                ]
            },
            "review": {"check_methods": ["rule_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "correct_choice",
            "description": "규칙에 따라 원을 4개 더 그린 바른 그림",
        },
        "value": 1,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008670",
    "problem_type": "pattern_selection",
    "inputs": {
        "total_ticks": 4,
        "target_label": "바르게 그린 것",
        "target_ticks": 4,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {
            "ref": "obj.rule",
            "value": {
                "description": "중심이 같고 반지름이 각각 1칸, 3칸인 원을 2개 그린 후 중심을 오른쪽으로 4칸씩 옮긴다."
            },
        }
    ],
    "target": {"ref": "answer.target", "type": "correct_choice"},
    "plan": "그림의 원 배치가 해설의 규칙과 같은지 확인한다.",
    "method": "pattern_matching",
    "steps": [
        {
            "id": "step.1",
            "expr": "규칙 확인: 중심이 같고 반지름이 1칸, 3칸인 원 2개",
            "value": 2,
        },
        {"id": "step.2", "expr": "중심 이동 간격 확인: 오른쪽으로 4칸씩", "value": 4},
        {"id": "step.3", "expr": "바른 그림은 규칙과 일치하는 선택지", "value": 1},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "해설 문장의 규칙이 그림과 일치하는가",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "correct_choice",
            "description": "규칙에 따라 원을 4개 더 그린 바른 그림",
        },
        "value": 1,
        "unit": "",
    },
}
