from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008978', title='각 판단하기', canvas=Canvas(width=760, height=300, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2', 'slot.q3', 'slot.q4', 'slot.q5', 'slot.q6')),), slots=(TextSlot(id='slot.q1', prompt='', text='□ 13.', style_role='question', x=8.0, y=20.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='각이면', style_role='question', x=85.0, y=20.0, font_size=28), TextSlot(id='slot.q3', prompt='', text='○', style_role='emphasis', x=149.0, y=20.0, font_size=28), TextSlot(id='slot.q4', prompt='', text=', 각이 아니면', style_role='question', x=174.0, y=20.0, font_size=28), TextSlot(id='slot.q5', prompt='', text='×', style_role='emphasis', x=313.0, y=20.0, font_size=28), TextSlot(id='slot.q6', prompt='', text='를 선택하세요.', style_role='question', x=339.0, y=20.0, font_size=28), LineSlot(id='slot.shape.left', prompt='', x1=349.0, y1=39.0, x2=291.0, y2=95.0), LineSlot(id='slot.shape.right', prompt='', x1=349.0, y1=39.0, x2=418.0, y2=95.0), CircleSlot(id='slot.mark.blue_circle', prompt='', cx=33.0, cy=128.0, r=6.0, fill='#FFFFFF'), TextSlot(id='slot.mark.blue_circle_text', prompt='', text='○', style_role='emphasis', x=28.0, y=134.0, font_size=20), TextSlot(id='slot.mark.blue_x', prompt='', text='×', style_role='emphasis', x=306.0, y=132.0, font_size=22), CircleSlot(id='slot.answer_blank', prompt='', cx=64.0, cy=187.0, r=10.0, fill='#FFFFFF')), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008978', 'problem_type': '판단형', 'metadata': {'language': 'ko', 'question': '각이면 ○, 각이 아니면 ×를 선택하세요.', 'instruction': '도형이 각인지 판단하여 선택한다.'}, 'domain': {'objects': [{'id': 'obj.figure', 'type': 'geometry_figure'}, {'id': 'obj.definition', 'type': 'definition', 'content': '한 점에서 그은 두 반직선으로 이루어진 도형'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.figure', 'obj.definition'], 'target_ref': 'answer.target', 'condition_refs': ['rel.classify']}, 'plan': {'method': 'figure_classification', 'description': '도형이 각의 정의에 맞는지 확인한다.'}, 'execute': {'expected_operations': ['compare_figure_with_definition', 'choose_circle_or_cross']}, 'review': {'check_methods': ['definition_match_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selection', 'description': '각이면 ○, 각이 아니면 ×'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008978', 'problem_type': '판단형', 'inputs': {'total_ticks': 1, 'target_label': '각 판별', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.figure', 'value': {'type': 'geometry_figure'}}, {'ref': 'obj.definition', 'value': {'content': '한 점에서 그은 두 반직선으로 이루어진 도형'}}], 'target': {'ref': 'answer.target', 'type': 'selection'}, 'method': 'figure_classification', 'plan': ['도형이 각의 정의에 맞는지 살펴본다.', '맞으면 ○, 아니면 ×를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '도형과 각의 정의 비교', 'value': '판단 필요'}], 'checks': [{'id': 'check.1', 'expr': '정의와 도형이 일치하는지 확인', 'expected': '일치 여부 판단', 'actual': '판단 필요', 'pass': False}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selection', 'description': '각이면 ○, 각이 아니면 ×'}, 'value': 0, 'unit': ''}}
