from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008946",
        title="가장 많은 학생들이 좋아하는 간식",
        canvas=Canvas(width=960, height=377, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.title_box",
                    "slot.title_text",
                    "slot.table_border",
                    "slot.table_v1",
                    "slot.table_v2",
                    "slot.table_v3",
                    "slot.table_v4",
                    "slot.table_v5",
                    "slot.table_h1",
                    "slot.table_h2",
                    "slot.cell.r1c1",
                    "slot.cell.r1c2",
                    "slot.cell.r1c3",
                    "slot.cell.r1c4",
                    "slot.cell.r1c5",
                    "slot.cell.r1c6",
                    "slot.cell.r2c1",
                    "slot.cell.r2c2",
                    "slot.cell.r2c3",
                    "slot.cell.r2c4",
                    "slot.cell.r2c5",
                    "slot.cell.r2c6",
                    "slot.group",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="□ 16. 현서네 반 학생들이 좋아하는 간식을 조사하여 표로 나타냈습니다. 가장 많은 학생들이 좋아하는 간식은 무엇일까요?",
                style_role="question",
                x=19.0,
                y=27.0,
                font_size=28,
            ),
            RectSlot(id="slot.title_box", prompt="", x=272.0, y=88.0, width=434.0, height=50.0),
            TextSlot(
                id="slot.title_text",
                prompt="",
                text="현서네 반 학생들이 좋아하는 간식",
                style_role="title",
                x=337.0,
                y=121.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table_border", prompt="", x=186.0, y=114.0, width=596.0, height=114.0
            ),
            TextSlot(
                id="slot.cell.r1c1",
                prompt="",
                text="간식",
                style_role="table_cell",
                x=241.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r1c2",
                prompt="",
                text="라면",
                style_role="table_cell",
                x=356.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r1c3",
                prompt="",
                text="치킨",
                style_role="table_cell",
                x=454.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r1c4",
                prompt="",
                text="햄버거",
                style_role="table_cell",
                x=548.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r1c5",
                prompt="",
                text="피자",
                style_role="table_cell",
                x=648.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r1c6",
                prompt="",
                text="합계",
                style_role="table_cell",
                x=746.0,
                y=141.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r2c1",
                prompt="",
                text="학생 수(명)",
                style_role="table_cell",
                x=236.0,
                y=180.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r2c2",
                prompt="",
                text="8",
                style_role="table_cell",
                x=347.0,
                y=181.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r2c3",
                prompt="",
                text="11",
                style_role="table_cell",
                x=450.0,
                y=181.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r2c4",
                prompt="",
                text="5",
                style_role="table_cell",
                x=548.0,
                y=181.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r2c5",
                prompt="",
                text="7",
                style_role="table_cell",
                x=644.0,
                y=181.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.cell.r2c6",
                prompt="",
                text="31",
                style_role="table_cell",
                x=747.0,
                y=181.0,
                font_size=28,
            ),
            LineSlot(id="slot.table_v1", prompt="", x1=335.0, y1=114.0, x2=335.0, y2=228.0),
            LineSlot(id="slot.table_v2", prompt="", x1=429.0, y1=114.0, x2=429.0, y2=228.0),
            LineSlot(id="slot.table_v3", prompt="", x1=524.0, y1=114.0, x2=524.0, y2=228.0),
            LineSlot(id="slot.table_v4", prompt="", x1=618.0, y1=114.0, x2=618.0, y2=228.0),
            LineSlot(id="slot.table_v5", prompt="", x1=715.0, y1=114.0, x2=715.0, y2=228.0),
            LineSlot(id="slot.table_h1", prompt="", x1=186.0, y1=154.0, x2=782.0, y2=154.0),
            LineSlot(id="slot.table_h2", prompt="", x1=186.0, y1=193.0, x2=782.0, y2=193.0),
            TextSlot(
                id="slot.group",
                prompt="",
                text="( 라면 , 치킨 , 햄버거 , 피자 )",
                style_role="note",
                x=559.0,
                y=263.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008946",
    "problem_type": "comparison_table",
    "metadata": {
        "language": "ko",
        "question": "표에서 가장 많은 학생들이 좋아하는 간식을 찾는 문제",
        "instruction": "가장 많은 학생들이 좋아하는 간식을 고르시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.snack.ramen", "type": "snack", "name": "라면"},
            {"id": "obj.snack.chicken", "type": "snack", "name": "치킨"},
            {"id": "obj.snack.hamburger", "type": "snack", "name": "햄버거"},
            {"id": "obj.snack.pizza", "type": "snack", "name": "피자"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.snack.ramen",
                    "obj.snack.chicken",
                    "obj.snack.hamburger",
                    "obj.snack.pizza",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.snack_count", "rel.maximum"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "각 간식에 해당하는 학생 수를 비교하여 가장 큰 값을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "read_table_counts",
                    "compare_values",
                    "select_largest_category",
                ]
            },
            "review": {"check_methods": ["max_value_check", "category_match_check"]},
        },
    },
    "answer": {
        "target": {"type": "snack_name", "description": "가장 많은 학생들이 좋아하는 간식"},
        "value": "치킨",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008946",
    "problem_type": "comparison_table",
    "inputs": {
        "total_ticks": 0,
        "target_label": "가장 많은 학생들이 좋아하는 간식",
        "target_ticks": 0,
        "target_count": 4,
        "unit": "",
    },
    "given": [
        {"ref": "obj.snack.ramen", "value": {"name": "라면", "count": 8}},
        {"ref": "obj.snack.chicken", "value": {"name": "치킨", "count": 11}},
        {"ref": "obj.snack.hamburger", "value": {"name": "햄버거", "count": 5}},
        {"ref": "obj.snack.pizza", "value": {"name": "피자", "count": 7}},
    ],
    "target": {"ref": "answer.target", "type": "snack_name"},
    "plan": ["표에 있는 각 간식의 학생 수를 비교한다.", "가장 큰 수에 대응하는 간식을 찾는다."],
    "method": "compare_counts",
    "steps": [
        {
            "id": "step.1",
            "expr": "라면 8, 치킨 11, 햄버거 5, 피자 7",
            "value": {"라면": 8, "치킨": 11, "햄버거": 5, "피자": 7},
        },
        {"id": "step.2", "expr": "11 > 8 > 7 > 5", "value": "치킨"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "가장 큰 값이 11인지 확인",
            "expected": 11,
            "actual": 11,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "11에 대응하는 간식이 치킨인지 확인",
            "expected": "치킨",
            "actual": "치킨",
            "pass": True,
        },
    ],
    "answer": {"value": "치킨", "unit": "", "derived_from": "step.2"},
}
