from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot, CircleSlot, PolygonSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008800', title='저울로 무게 비교하기', canvas=Canvas(width=940, height=390, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2', 'slot.q3')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.scale.base', 'slot.scale.pillar', 'slot.scale.beam', 'slot.scale.left.pan', 'slot.scale.right.pan', 'slot.scale.left.string', 'slot.scale.right.string', 'slot.pt.pencil', 'slot.pt.case', 'slot.lb.pencil', 'slot.lb.case')), Region(id='region.choice', role='body', flow='absolute', slot_ids=('slot.choice',)), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='□ 29. 저울을 이용하여 연필과 필통의 무게를 비교했습니다. 알맞은 말을 선택', style_role='question', x=12.0, y=28.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='하세요.', style_role='question', x=12.0, y=66.0, font_size=28), TextSlot(id='slot.q3', prompt='', text='', style_role='question', x=0.0, y=0.0, font_size=28), RectSlot(id='slot.scale.base', prompt='', x=402.0, y=218.0, width=188.0, height=40.0), RectSlot(id='slot.scale.pillar', prompt='', x=494.0, y=164.0, width=18.0, height=76.0), LineSlot(id='slot.scale.beam', prompt='', x1=456.0, y1=170.0, x2=560.0, y2=194.0), PolygonSlot(id='slot.scale.left.pan', prompt='', points=((395.0, 149.0), (437.0, 149.0), (429.0, 170.0), (403.0, 170.0))), PolygonSlot(id='slot.scale.right.pan', prompt='', points=((550.0, 170.0), (592.0, 170.0), (584.0, 149.0), (558.0, 149.0))), LineSlot(id='slot.scale.left.string', prompt='', x1=416.0, y1=170.0, x2=416.0, y2=149.0), LineSlot(id='slot.scale.right.string', prompt='', x1=574.0, y1=170.0, x2=574.0, y2=149.0), CircleSlot(id='slot.pt.pencil', prompt='', cx=421.0, cy=146.0, r=3.8, fill='#222222'), CircleSlot(id='slot.pt.case', prompt='', cx=573.0, cy=146.0, r=3.8, fill='#222222'), TextSlot(id='slot.lb.pencil', prompt='', text='연필', style_role='label', x=394.0, y=140.0, font_size=28), TextSlot(id='slot.lb.case', prompt='', text='필통', style_role='label', x=552.0, y=138.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='( 연필 , 필통 )이 더 무겁습니다.', style_role='body', x=295.0, y=274.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008800', 'problem_type': 'weight_comparison', 'metadata': {'language': 'ko', 'question': '저울을 이용하여 연필과 필통의 무게를 비교하는 문제', 'instruction': '알맞은 말을 선택한다.'}, 'domain': {'objects': [{'id': 'obj.pencil', 'type': 'object', 'name': '연필'}, {'id': 'obj.case', 'type': 'object', 'name': '필통'}, {'id': 'obj.scale', 'type': 'scale', 'name': '저울'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.pencil', 'obj.case', 'obj.scale'], 'target_ref': 'answer.target', 'condition_refs': ['rel.compare_weight']}, 'plan': {'method': 'compare_by_scale', 'description': '저울에서 더 내려간 쪽의 물건이 더 무거운지 확인한다.'}, 'execute': {'expected_operations': ['identify_heavier_side', 'match_object_to_heavier_side']}, 'review': {'check_methods': ['compare_with_given_explanation']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'heavier_object_name', 'description': '더 무거운 물건의 이름'}, 'value': '필통', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008800', 'problem_type': 'weight_comparison', 'inputs': {'total_ticks': 0, 'target_label': '더 무거운 물건', 'target_ticks': 0, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.pencil', 'value': {'name': '연필'}}, {'ref': 'obj.case', 'value': {'name': '필통'}}], 'target': {'ref': 'answer.target', 'type': 'heavier_object_name'}, 'method': 'compare_by_scale', 'plan': ['저울에서 더 내려간 쪽을 확인한다.', '그 쪽에 놓인 물건을 더 무거운 것으로 판단한다.'], 'steps': [{'id': 'step.1', 'expr': '저울의 오른쪽 접시가 더 내려가 있음', 'value': 'right_heavier'}, {'id': 'step.2', 'expr': '오른쪽 접시에 놓인 물건 = 필통', 'value': '필통'}], 'checks': [{'id': 'check.1', 'expr': '해설과 일치하는가', 'expected': '필통', 'actual': '필통', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'heavier_object_name', 'description': '더 무거운 물건의 이름'}, 'value': '필통', 'unit': ''}}
