from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008669",
        title="원의 중심과 반지름",
        canvas=Canvas(width=960, height=500, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.choice_box",
                    "slot.choice.a.outer",
                    "slot.choice.a.left",
                    "slot.choice.a.right",
                    "slot.choice.b.outer",
                    "slot.choice.b.middle",
                    "slot.choice.b.inner",
                    "slot.choice.c.outer",
                    "slot.choice.c.inner",
                    "slot.ans.outer1",
                    "slot.ans.outer2",
                    "slot.ans.inner",
                    "slot.ex1.outer",
                    "slot.ex1.left",
                    "slot.ex1.right",
                    "slot.ex1.dot1",
                    "slot.ex1.dot2",
                    "slot.ex2.outer",
                    "slot.ex2.middle",
                    "slot.ex2.inner",
                    "slot.ex2.dot",
                    "slot.ex3.outer",
                    "slot.ex3.inner",
                    "slot.ex3.inner2",
                    "slot.ex3.dot1",
                    "slot.ex3.dot2",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="□ 48.  원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것을 찾아 선택하",
                style_role="question",
                x=16.0,
                y=22.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="세요.",
                style_role="question",
                x=16.0,
                y=58.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.choice_box",
                prompt="",
                x=200.0,
                y=88.0,
                width=582.0,
                height=130.0,
                fill="none",
                stroke="#A89BEA",
            ),
            CircleSlot(
                id="slot.choice.a.outer",
                prompt="",
                cx=295.0,
                cy=149.0,
                r=44.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.a.left",
                prompt="",
                cx=280.0,
                cy=149.0,
                r=22.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.a.right",
                prompt="",
                cx=310.0,
                cy=149.0,
                r=22.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.outer",
                prompt="",
                cx=484.0,
                cy=149.0,
                r=44.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.middle",
                prompt="",
                cx=484.0,
                cy=149.0,
                r=31.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.inner",
                prompt="",
                cx=484.0,
                cy=149.0,
                r=16.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.c.outer",
                prompt="",
                cx=683.0,
                cy=149.0,
                r=44.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.c.inner",
                prompt="",
                cx=683.0,
                cy=173.0,
                r=24.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ans.outer1",
                prompt="",
                cx=92.0,
                cy=267.0,
                r=35.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ans.outer2",
                prompt="",
                cx=92.0,
                cy=267.0,
                r=22.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ans.inner",
                prompt="",
                cx=92.0,
                cy=267.0,
                r=11.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex1.outer",
                prompt="",
                cx=93.0,
                cy=434.0,
                r=42.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex1.left",
                prompt="",
                cx=74.0,
                cy=434.0,
                r=22.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex1.right",
                prompt="",
                cx=112.0,
                cy=434.0,
                r=22.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex1.dot1",
                prompt="",
                cx=73.0,
                cy=436.0,
                r=3.8,
                fill="#1DA1F2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.ex1.dot2",
                prompt="",
                cx=113.0,
                cy=436.0,
                r=3.8,
                fill="#1DA1F2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.ex2.outer",
                prompt="",
                cx=239.0,
                cy=434.0,
                r=42.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex2.middle",
                prompt="",
                cx=239.0,
                cy=434.0,
                r=31.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex2.inner",
                prompt="",
                cx=239.0,
                cy=434.0,
                r=16.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex2.dot",
                prompt="",
                cx=239.0,
                cy=434.0,
                r=3.8,
                fill="#1DA1F2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.ex3.outer",
                prompt="",
                cx=372.0,
                cy=434.0,
                r=42.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex3.inner",
                prompt="",
                cx=372.0,
                cy=460.0,
                r=20.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex3.inner2",
                prompt="",
                cx=372.0,
                cy=446.0,
                r=13.0,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.ex3.dot1",
                prompt="",
                cx=372.0,
                cy=436.0,
                r=3.8,
                fill="#1DA1F2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.ex3.dot2",
                prompt="",
                cx=372.0,
                cy=459.0,
                r=3.8,
                fill="#1DA1F2",
                stroke="none",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008669",
    "problem_type": "도형_판별",
    "metadata": {
        "language": "ko",
        "question": "원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것을 찾아 선택하세요.",
        "instruction": "정답을 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.choice_1", "type": "circle_figure"},
            {"id": "obj.choice_2", "type": "circle_figure"},
            {"id": "obj.choice_3", "type": "circle_figure"},
            {"id": "obj.example", "type": "circle_figure"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.choice_1", "obj.choice_2", "obj.choice_3"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.center_same", "rel.radius_different"],
            },
            "plan": {
                "method": "도형 비교",
                "description": "각 그림에서 중심이 같은지와 반지름만 달라졌는지를 비교한다.",
            },
            "execute": {
                "expected_operations": ["중심 비교", "반지름 비교", "해설 문장 확인"]
            },
            "review": {
                "check_methods": ["중심 이동 여부 확인", "반지름만 변화했는지 확인"]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_figure",
            "description": "원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것",
        },
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008669",
    "problem_type": "도형_판별",
    "inputs": {
        "total_ticks": 3,
        "target_label": "정답",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.choice_1", "value": "도형 선택지 1"},
        {"ref": "obj.choice_2", "value": "도형 선택지 2"},
        {"ref": "obj.choice_3", "value": "도형 선택지 3"},
    ],
    "target": {"ref": "answer.target", "type": "selected_figure"},
    "method": "도형 비교",
    "plan": [
        "그림마다 원의 중심이 같은지 확인한다.",
        "반지름만 다르게 그린 그림인지 비교한다.",
        "해설에 맞는 그림을 선택한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "선택지 1은 중심이 이동한 그림인지 확인",
            "value": "중심 이동",
        },
        {
            "id": "step.2",
            "expr": "선택지 2는 중심은 같고 반지름만 다른지 확인",
            "value": "중심 같음, 반지름 다름",
        },
        {
            "id": "step.3",
            "expr": "선택지 3은 중심이 이동한 그림인지 확인",
            "value": "중심 이동",
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "해설과 일치하는 선택지인지 확인",
            "expected": "선택지 2",
            "actual": "선택지 2",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_figure",
            "description": "원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것",
        },
        "value": 2,
        "unit": "",
    },
}
