from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, CircleSlot, PathSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008870', title='물이 더 적게 들어가는 것', canvas=Canvas(width=948.0, height=460.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.pic.bottle_body', 'slot.pic.bottle_top', 'slot.pic.bottle_open', 'slot.pic.bottle_handle', 'slot.pic.bottle_water', 'slot.pic.bottle_label', 'slot.pic.bowl_outer', 'slot.pic.bowl_inner', 'slot.pic.bowl_water', 'slot.pic.bowl_label', 'slot.pic.option')), Region(id='region.bottom', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='23. 물병에 물을 가득 채운 후 그릇에 모두 부었더니 다음 그림과 같았습니다. 물병과 그릇 중 들이가 더 적은 것을 선택하세요.', style_role='question', x=12.0, y=30.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='', style_role='question', x=12.0, y=62.0, font_size=28), RectSlot(id='slot.pic.bottle_body', prompt='', x=406.0, y=92.0, width=112.0, height=34.0, fill='none', stroke='#8EC6E8', stroke_width=2.0, rx=10.0, ry=10.0), LineSlot(id='slot.pic.bottle_top', prompt='', x1=444.0, y1=90.0, x2=516.0, y2=116.0, stroke='#8EC6E8', stroke_width=2.0), CircleSlot(id='slot.pic.bottle_open', prompt='', cx=517.5, cy=116.5, r=14.0, fill='none', stroke='#A7B0B8', stroke_width=2.0), LineSlot(id='slot.pic.bottle_handle', prompt='', x1=475.0, y1=92.0, x2=499.0, y2=102.0, stroke='#F36B6B', stroke_width=4.0), PathSlot(id='slot.pic.bottle_water', prompt='', d='M 418 94 C 421 101, 423 105, 430 110 L 506 110 C 506 110, 505 104, 503 96 Z', fill='#EAF6FF', stroke='none'), TextSlot(id='slot.pic.bottle_label', prompt='', text='물병', style_role='label', x=406.0, y=144.0, font_size=20), RectSlot(id='slot.pic.bowl_outer', prompt='', x=476.0, y=180.0, width=148.0, height=74.0, fill='none', stroke='#8EC6E8', stroke_width=2.0, rx=10.0, ry=10.0), CircleSlot(id='slot.pic.bowl_inner', prompt='', cx=550.0, cy=180.0, r=74.0, fill='none', stroke='#8EC6E8', stroke_width=2.0), PathSlot(id='slot.pic.bowl_water', prompt='', d='M 490 218 C 515 210, 590 210, 610 218 L 610 252 L 490 252 Z', fill='#4DA8E0', stroke='none'), TextSlot(id='slot.pic.bowl_label', prompt='', text='그릇', style_role='label', x=526.0, y=286.0, font_size=20), TextSlot(id='slot.pic.option', prompt='', text='( 물병 , 그릇 )', style_role='label', x=406.0, y=330.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008870', 'problem_type': '비교_들이다', 'metadata': {'language': 'ko', 'question': '물병과 그릇 중 들이가 더 적은 것을 선택하는 문제', 'instruction': '보기를 보고 정답을 고른다.'}, 'domain': {'objects': [{'id': 'obj.bottle', 'type': 'container', 'name': '물병'}, {'id': 'obj.bowl', 'type': 'container', 'name': '그릇'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.bottle', 'obj.bowl', 'rel.pour_all'], 'target_ref': 'answer.target', 'condition_refs': ['rel.compare_capacity']}, 'plan': {'method': '비교하기', 'description': '그릇에 물병의 물이 모두 들어가고도 남는지 보고 들이가 더 적은 것을 고른다.'}, 'execute': {'expected_operations': ['상황 비교', '정답 선택']}, 'review': {'check_methods': ['해설 문장과 선택이 일치하는지 확인']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'container_name', 'description': '들이가 더 적은 것'}, 'value': '물병', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008870', 'problem_type': '비교_들이다', 'inputs': {'total_ticks': 0, 'target_label': '들이가 더 적은 것', 'target_ticks': 0, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.bottle', 'value': {'name': '물병'}}, {'ref': 'obj.bowl', 'value': {'name': '그릇'}}, {'ref': 'rel.pour_all', 'value': {'description': '물병의 물을 그릇에 모두 붓는다'}}], 'target': {'ref': 'answer.target', 'type': 'container_name'}, 'method': '비교하기', 'plan': ['그릇에 물병의 물이 모두 들어가는지 확인한다.', '더 적은 들이를 가진 용기를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '그릇에 물병의 물이 모두 들어가고 가득 차지 않음', 'value': '그릇이 더 큼'}, {'id': 'step.2', 'expr': '들이가 더 적은 것 선택', 'value': '물병'}], 'checks': [{'id': 'check.1', 'expr': '해설의 선택이 정답과 일치하는가', 'expected': '물병', 'actual': '물병', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'container_name', 'description': '들이가 더 적은 것'}, 'value': '물병', 'unit': ''}}
