from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009037', title='정사각형을 찾아 선택하세요', canvas=Canvas(width=816, height=480, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.choice_text', 'slot.opt.ga', 'slot.opt.na', 'slot.opt.da', 'slot.opt.ra', 'slot.opt.ma', 'slot.opt.lb.ga', 'slot.opt.lb.na', 'slot.opt.lb.da', 'slot.opt.lb.ra', 'slot.opt.lb.ma')),), slots=(TextSlot(id='slot.q1', prompt='', text='75. 정사각형을 찾아 선택하세요.', style_role='question', x=18.0, y=28.0, font_size=28), TextSlot(id='slot.choice_text', prompt='', text='( 가, 나, 다, 라, 마 )', style_role='body', x=208.0, y=212.0, font_size=28), RectSlot(id='slot.opt.ga', prompt='', x=48.0, y=70.0, width=80.0, height=60.0), RectSlot(id='slot.opt.na', prompt='', x=162.0, y=70.0, width=80.0, height=60.0), RectSlot(id='slot.opt.da', prompt='', x=276.0, y=70.0, width=80.0, height=60.0), RectSlot(id='slot.opt.ra', prompt='', x=390.0, y=70.0, width=80.0, height=60.0), RectSlot(id='slot.opt.ma', prompt='', x=504.0, y=70.0, width=80.0, height=60.0), TextSlot(id='slot.opt.lb.ga', prompt='', text='가', style_role='label', x=74.0, y=118.0, font_size=28), TextSlot(id='slot.opt.lb.na', prompt='', text='나', style_role='label', x=188.0, y=110.0, font_size=28), TextSlot(id='slot.opt.lb.da', prompt='', text='다', style_role='label', x=302.0, y=110.0, font_size=28), TextSlot(id='slot.opt.lb.ra', prompt='', text='라', style_role='label', x=416.0, y=118.0, font_size=28), TextSlot(id='slot.opt.lb.ma', prompt='', text='마', style_role='label', x=530.0, y=110.0, font_size=28), RectSlot(id='slot.opt2.ga', prompt='', x=48.0, y=354.0, width=80.0, height=60.0), RectSlot(id='slot.opt2.na', prompt='', x=162.0, y=354.0, width=80.0, height=60.0), RectSlot(id='slot.opt2.da', prompt='', x=276.0, y=354.0, width=80.0, height=60.0), RectSlot(id='slot.opt2.ra', prompt='', x=390.0, y=354.0, width=80.0, height=60.0), RectSlot(id='slot.opt2.ma', prompt='', x=504.0, y=354.0, width=80.0, height=60.0), TextSlot(id='slot.opt2.lb.ga', prompt='', text='가', style_role='label', x=74.0, y=402.0, font_size=28), TextSlot(id='slot.opt2.lb.na', prompt='', text='나', style_role='label', x=188.0, y=394.0, font_size=28), TextSlot(id='slot.opt2.lb.da', prompt='', text='다', style_role='label', x=302.0, y=394.0, font_size=28), TextSlot(id='slot.opt2.lb.ra', prompt='', text='라', style_role='label', x=416.0, y=402.0, font_size=28), TextSlot(id='slot.opt2.lb.ma', prompt='', text='마', style_role='label', x=530.0, y=394.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=('도형', '정사각형', '선택형'))
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009037', 'problem_type': 'shape_selection', 'metadata': {'language': 'ko', 'question': '정사각형을 찾아 선택하세요.', 'instruction': '( 가, 나, 다, 라, 마 ) 중에서 정사각형을 고르는 문제이다.'}, 'domain': {'objects': [{'id': 'obj.choice.ga', 'type': 'shape_option', 'label': '가'}, {'id': 'obj.choice.na', 'type': 'shape_option', 'label': '나'}, {'id': 'obj.choice.da', 'type': 'shape_option', 'label': '다'}, {'id': 'obj.choice.ra', 'type': 'shape_option', 'label': '라'}, {'id': 'obj.choice.ma', 'type': 'shape_option', 'label': '마'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.choice.ga', 'obj.choice.na', 'obj.choice.da', 'obj.choice.ra', 'obj.choice.ma'], 'target_ref': 'answer.target', 'condition_refs': ['rel.select_square']}, 'plan': {'method': 'shape_property_check', 'description': '네 각이 모두 직각이고 네 변의 길이가 모두 같은 도형을 찾는다.'}, 'execute': {'expected_operations': ['compare_shape_properties', 'select_matching_option']}, 'review': {'check_methods': ['all_right_angles', 'all_sides_equal']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_shape', 'description': '정사각형'}, 'value': '마', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009037', 'problem_type': 'shape_selection', 'inputs': {'total_ticks': 5, 'target_label': '정사각형', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.choice.ga', 'value': {'label': '가'}}, {'ref': 'obj.choice.na', 'value': {'label': '나'}}, {'ref': 'obj.choice.da', 'value': {'label': '다'}}, {'ref': 'obj.choice.ra', 'value': {'label': '라'}}, {'ref': 'obj.choice.ma', 'value': {'label': '마'}}], 'target': {'ref': 'answer.target', 'type': 'selected_shape'}, 'method': 'shape_property_check', 'plan': ['각 보기의 도형 성질을 살펴 정사각형 조건에 맞는 것을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '가, 나, 다, 라, 마 중 정사각형 조건에 맞는 도형을 찾는다.', 'value': '마'}], 'checks': [{'id': 'check.1', 'expr': '선택한 도형이 정사각형인가', 'expected': '정사각형', 'actual': '마', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_shape', 'description': '정사각형'}, 'value': '마', 'unit': ''}}
