from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008912",
        title="생일에 받고 싶은 선물별 학생 수",
        canvas=Canvas(width=940, height=397, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q.no",
                    "slot.q.line1",
                    "slot.q.line2",
                    "slot.table.title",
                    "slot.table.rect",
                    "slot.table.hdr1",
                    "slot.table.hdr2",
                    "slot.table.hdr3",
                    "slot.table.hdr4",
                    "slot.table.hdr5",
                    "slot.table.hdr6",
                    "slot.table.val1",
                    "slot.table.val2",
                    "slot.table.val3",
                    "slot.table.val4",
                    "slot.table.val5",
                    "slot.table.val6",
                    "slot.choice",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q.no",
                prompt="",
                text="78.",
                style_role="question",
                x=12.0,
                y=24.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.line1",
                prompt="",
                text="정국이는 반 학생들이 생일에 받고 싶은 선물을 조사하여 표로 나타내었습니다.",
                style_role="question",
                x=56.0,
                y=24.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.line2",
                prompt="",
                text="가장 적은 학생들이 받고 싶은 선물을 선택하세요.",
                style_role="question",
                x=56.0,
                y=64.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.title",
                prompt="",
                text="생일에 받고 싶은 선물별 학생 수",
                style_role="label",
                x=281.0,
                y=96.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.rect",
                prompt="",
                x=123.0,
                y=116.0,
                width=704.0,
                height=81.0,
                fill="#E4EBD0",
                stroke="#9CCB59",
                stroke_width=1.4,
            ),
            TextSlot(
                id="slot.table.hdr1",
                prompt="",
                text="선물",
                style_role="label",
                x=174.0,
                y=144.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.hdr2",
                prompt="",
                text="책",
                style_role="label",
                x=364.0,
                y=144.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.hdr3",
                prompt="",
                text="휴대전화",
                style_role="label",
                x=452.0,
                y=144.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.hdr4",
                prompt="",
                text="게임기",
                style_role="label",
                x=567.0,
                y=144.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.hdr5",
                prompt="",
                text="옷",
                style_role="label",
                x=684.0,
                y=144.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.hdr6",
                prompt="",
                text="합계",
                style_role="label",
                x=779.0,
                y=144.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.val1",
                prompt="",
                text="학생 수(명)",
                style_role="label",
                x=154.0,
                y=181.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.val2",
                prompt="",
                text="6",
                style_role="label",
                x=347.0,
                y=180.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.val3",
                prompt="",
                text="12",
                style_role="label",
                x=446.0,
                y=180.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.val4",
                prompt="",
                text="8",
                style_role="label",
                x=567.0,
                y=180.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.val5",
                prompt="",
                text="4",
                style_role="label",
                x=685.0,
                y=180.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.val6",
                prompt="",
                text="30",
                style_role="label",
                x=773.0,
                y=180.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 책 , 휴대전화 , 게임기 , 옷 )",
                style_role="label",
                x=603.0,
                y=234.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008912",
    "problem_type": "table_minimum_selection",
    "metadata": {
        "language": "ko",
        "question": "표에서 가장 적은 학생들이 받고 싶은 선물을 고르는 문제",
        "instruction": "가장 적은 학생들이 받고 싶은 선물을 선택하세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.gift.book", "type": "gift", "name": "책"},
            {"id": "obj.gift.phone", "type": "gift", "name": "휴대전화"},
            {"id": "obj.gift.game", "type": "gift", "name": "게임기"},
            {"id": "obj.gift.clothes", "type": "gift", "name": "옷"},
            {"id": "obj.count.book", "type": "count", "value": 6, "unit": "명"},
            {"id": "obj.count.phone", "type": "count", "value": 12, "unit": "명"},
            {"id": "obj.count.game", "type": "count", "value": 8, "unit": "명"},
            {"id": "obj.count.clothes", "type": "count", "value": 4, "unit": "명"},
            {"id": "obj.count.total", "type": "count", "value": 30, "unit": "명"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.count.book",
                    "obj.count.phone",
                    "obj.count.game",
                    "obj.count.clothes",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.minimum_selection"],
            },
            "plan": {
                "method": "find_minimum",
                "description": "표의 학생 수를 비교하여 가장 작은 값을 가진 선물을 찾는다.",
            },
            "execute": {"expected_operations": ["compare_counts", "select_smallest_count"]},
            "review": {"check_methods": ["minimum_value_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_gift", "description": "가장 적은 학생들이 받고 싶은 선물"},
        "value": "옷",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008912",
    "problem_type": "table_minimum_selection",
    "inputs": {
        "total_ticks": 30,
        "target_label": "가장 적은 학생들이 받고 싶은 선물",
        "target_ticks": 4,
        "target_count": 4,
        "unit": "명",
    },
    "given": [
        {"ref": "obj.count.book", "value": 6},
        {"ref": "obj.count.phone", "value": 12},
        {"ref": "obj.count.game", "value": 8},
        {"ref": "obj.count.clothes", "value": 4},
        {"ref": "obj.count.total", "value": 30},
    ],
    "target": {"ref": "answer.target", "type": "selected_gift"},
    "method": "find_minimum",
    "plan": ["표의 학생 수를 비교하여 가장 작은 수를 찾는다."],
    "steps": [
        {"id": "step.1", "expr": "6, 12, 8, 4, 30 중 가장 작은 수를 찾는다.", "value": 4},
        {"id": "step.2", "expr": "가장 작은 수 4에 대응하는 선물은 옷이다.", "value": "옷"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "4가 나머지 값 6, 12, 8, 30보다 작은가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "4에 대응하는 항목이 옷인가",
            "expected": "옷",
            "actual": "옷",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_gift", "description": "가장 적은 학생들이 받고 싶은 선물"},
        "value": "옷",
        "unit": "",
    },
}
