from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008964",
        title="모둠 학생들이 접은 종이꽃 수",
        canvas=Canvas(width=960, height=900, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.table.title",
                    "slot.table.head1",
                    "slot.table.head2",
                    "slot.table.r1.name",
                    "slot.table.r2.name",
                    "slot.table.r3.name",
                    "slot.legend.big",
                    "slot.legend.big.label",
                    "slot.legend.small",
                    "slot.legend.small.label",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                    "slot.choice.5",
                ),
            ),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.table.outer",
                    "slot.table.vline",
                    "slot.table.hline1",
                    "slot.table.hline2",
                    "slot.table.hline3",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="34. 재경이네 모둠 학생들이 접은 종이꽃의 수를 조사하여 그림그래프로 나타냈습니다.",
                style_role="question",
                x=18.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="재경이와 채미가 접은 종이꽃이 모두 67송이라면 채민이와 은서가 접은 종이꽃은 모두 몇 송이일까요?",
                style_role="question",
                x=18.0,
                y=64.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.title",
                prompt="",
                text="모둠 학생들이 접은 종이꽃 수",
                style_role="caption",
                x=280.0,
                y=112.0,
                font_size=28,
            ),
            RectSlot(id="slot.table.outer", prompt="", x=205.0, y=136.0, width=530.0, height=302.0),
            RectSlot(id="slot.table.vline", prompt="", x=364.0, y=136.0, width=1.0, height=302.0),
            RectSlot(id="slot.table.hline1", prompt="", x=205.0, y=182.0, width=530.0, height=1.0),
            RectSlot(id="slot.table.hline2", prompt="", x=205.0, y=248.0, width=530.0, height=1.0),
            RectSlot(id="slot.table.hline3", prompt="", x=205.0, y=314.0, width=530.0, height=1.0),
            TextSlot(
                id="slot.table.head1",
                prompt="",
                text="이름",
                style_role="label",
                x=250.0,
                y=165.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.head2",
                prompt="",
                text="종이꽃 수",
                style_role="label",
                x=542.0,
                y=165.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1.name",
                prompt="",
                text="재경",
                style_role="label",
                x=255.0,
                y=225.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2.name",
                prompt="",
                text="은서",
                style_role="label",
                x=255.0,
                y=291.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r3.name",
                prompt="",
                text="채민",
                style_role="label",
                x=255.0,
                y=357.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.big",
                prompt="",
                text="🌼",
                style_role="label",
                x=565.0,
                y=468.0,
                font_size=40,
            ),
            TextSlot(
                id="slot.legend.big.label",
                prompt="",
                text=":10송이",
                style_role="label",
                x=615.0,
                y=485.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.small",
                prompt="",
                text="🌼",
                style_role="label",
                x=685.0,
                y=476.0,
                font_size=26,
            ),
            TextSlot(
                id="slot.legend.small.label",
                prompt="",
                text=":1송이",
                style_role="label",
                x=715.0,
                y=485.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 49송이",
                style_role="choice",
                x=35.0,
                y=535.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 52송이",
                style_role="choice",
                x=300.0,
                y=535.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 55송이",
                style_role="choice",
                x=610.0,
                y=535.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 57송이",
                style_role="choice",
                x=35.0,
                y=585.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.5",
                prompt="",
                text="⑤ 59송이",
                style_role="choice",
                x=300.0,
                y=585.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008964",
    "problem_type": "그림그래프_합",
    "metadata": {
        "language": "ko",
        "question": "재경이와 채민이가 접은 종이꽃이 모두 67송이라면 채민이와 은서가 접은 종이꽃은 모두 몇 송이인지 묻는 문제",
        "instruction": "그림그래프의 범례와 해설 관계를 읽고 알맞은 값을 찾는다.",
        "points": 5,
    },
    "domain": {
        "objects": [
            {"id": "obj.group", "type": "group", "name": "재경이네 모둠 학생들"},
            {"id": "obj.jaegyeong", "type": "student", "name": "재경"},
            {"id": "obj.eunseo", "type": "student", "name": "은서"},
            {"id": "obj.chaemin", "type": "student", "name": "채민"},
            {"id": "obj.legend.big", "type": "pictograph_unit", "value": 10},
            {"id": "obj.legend.small", "type": "pictograph_unit", "value": 1},
            {"id": "obj.sum_jaegyeong_chaemin", "type": "quantity", "value": 67},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.sum_jaegyeong_chaemin", "obj.legend.big", "obj.legend.small"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.legend_meaning", "rel.partial_sum"],
            },
            "plan": {
                "method": "그림그래프_해석",
                "description": "범례를 읽고 알려진 합과 한 사람의 수를 이용해 필요한 합을 찾는다.",
            },
            "execute": {
                "expected_operations": ["범례 해석", "부분 수량 관계 파악", "합 관계 읽기"]
            },
            "review": {"check_methods": ["문장과 식의 대응 확인", "단위 일치 확인"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "sum_of_counts", "description": "채민이와 은서가 접은 종이꽃의 수"},
        "value": 59,
        "unit": "송이",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008964",
    "problem_type": "그림그래프_합",
    "inputs": {
        "total_ticks": 67,
        "target_label": "채민이와 은서가 접은 종이꽃의 수",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "송이",
    },
    "given": [
        {"ref": "obj.sum_jaegyeong_chaemin", "value": 67},
        {"ref": "obj.eunseo", "value": "25송이"},
    ],
    "target": {"ref": "answer.target", "type": "sum_of_counts"},
    "method": "그림그래프_관계식",
    "plan": [
        "범례를 해석한다.",
        "해설에 보이는 관계식을 읽어 필요한 합을 구한다.",
        "채민이와 은서의 합을 확인한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "67 - 33", "value": 34},
        {"id": "step.2", "expr": "34 + 25", "value": 59},
    ],
    "checks": [
        {"id": "check.1", "expr": "34 + 25 = 59", "expected": 59, "actual": 59, "pass": True}
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "sum_of_counts", "description": "채민이와 은서가 접은 종이꽃의 수"},
        "value": 59,
        "unit": "송이",
    },
}
