from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008955",
        title="친구들이 좋아하는 과일",
        canvas=Canvas(width=940, height=556, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q_num", "slot.q1", "slot.q2"),
            ),
            Region(
                id="region.banner",
                role="diagram",
                flow="absolute",
                slot_ids=("slot.banner", "slot.banner_title"),
            ),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.table.outer",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.v5",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.h3",
                    "slot.r1c1.name",
                    "slot.r1c1.fruit",
                    "slot.r1c2.name",
                    "slot.r1c2.fruit",
                    "slot.r1c3.name",
                    "slot.r1c3.fruit",
                    "slot.r1c4.name",
                    "slot.r1c4.fruit",
                    "slot.r1c5.name",
                    "slot.r1c5.fruit",
                    "slot.r2c1.name",
                    "slot.r2c1.fruit",
                    "slot.r2c2.name",
                    "slot.r2c2.fruit",
                    "slot.r2c3.name",
                    "slot.r2c3.fruit",
                    "slot.r2c4.name",
                    "slot.r2c4.fruit",
                    "slot.r2c5.name",
                    "slot.r2c5.fruit",
                    "slot.r3c1.name",
                    "slot.r3c1.fruit",
                    "slot.r3c2.name",
                    "slot.r3c2.fruit",
                    "slot.r3c3.name",
                    "slot.r3c3.fruit",
                    "slot.r3c4.name",
                    "slot.r3c4.fruit",
                    "slot.r3c5.name",
                    "slot.r3c5.fruit",
                ),
            ),
            Region(
                id="region.legend",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.legend.apple",
                    "slot.legend.grape",
                    "slot.legend.strawberry",
                    "slot.legend.banana",
                ),
            ),
            Region(
                id="region.answer_area",
                role="note",
                flow="absolute",
                slot_ids=("slot.choice_text",),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q_num",
                prompt="",
                text="25.",
                style_role="question",
                x=10.0,
                y=29.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q1",
                prompt="",
                text="은호네 모둠 친구들이 좋아하는 과일을 조사하여 나타내었습니다.",
                style_role="question",
                x=55.0,
                y=30.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="선미가 좋아하는 과일을 선택하세요.",
                style_role="question",
                x=21.0,
                y=64.0,
                font_size=28,
            ),
            RectSlot(id="slot.banner", prompt="", x=320.0, y=86.0, width=286.0, height=28.0),
            TextSlot(
                id="slot.banner_title",
                prompt="",
                text="친구들이 좋아하는 과일",
                style_role="title",
                x=358.0,
                y=104.0,
                font_size=28,
            ),
            RectSlot(id="slot.table.outer", prompt="", x=250.0, y=104.0, width=430.0, height=266.0),
            RectSlot(id="slot.table.v1", prompt="", x=336.0, y=104.0, width=0.0, height=266.0),
            RectSlot(id="slot.table.v2", prompt="", x=422.0, y=104.0, width=0.0, height=266.0),
            RectSlot(id="slot.table.v3", prompt="", x=508.0, y=104.0, width=0.0, height=266.0),
            RectSlot(id="slot.table.v4", prompt="", x=594.0, y=104.0, width=0.0, height=266.0),
            RectSlot(id="slot.table.v5", prompt="", x=680.0, y=104.0, width=0.0, height=266.0),
            RectSlot(id="slot.table.h1", prompt="", x=250.0, y=192.0, width=430.0, height=0.0),
            RectSlot(id="slot.table.h2", prompt="", x=250.0, y=280.0, width=430.0, height=0.0),
            RectSlot(id="slot.table.h3", prompt="", x=250.0, y=368.0, width=430.0, height=0.0),
            TextSlot(
                id="slot.r1c1.name",
                prompt="",
                text="은호",
                style_role="label",
                x=273.0,
                y=130.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c1.fruit",
                prompt="",
                text="사과",
                style_role="label",
                x=273.0,
                y=173.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c2.name",
                prompt="",
                text="민지",
                style_role="label",
                x=359.0,
                y=130.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c2.fruit",
                prompt="",
                text="포도",
                style_role="label",
                x=359.0,
                y=173.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c3.name",
                prompt="",
                text="정민",
                style_role="label",
                x=445.0,
                y=130.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c3.fruit",
                prompt="",
                text="딸기",
                style_role="label",
                x=445.0,
                y=173.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c4.name",
                prompt="",
                text="준수",
                style_role="label",
                x=531.0,
                y=130.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c4.fruit",
                prompt="",
                text="딸기",
                style_role="label",
                x=531.0,
                y=173.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c5.name",
                prompt="",
                text="호진",
                style_role="label",
                x=617.0,
                y=130.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r1c5.fruit",
                prompt="",
                text="딸기",
                style_role="label",
                x=617.0,
                y=173.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c1.name",
                prompt="",
                text="선아",
                style_role="label",
                x=273.0,
                y=218.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c1.fruit",
                prompt="",
                text="딸기",
                style_role="label",
                x=273.0,
                y=261.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c2.name",
                prompt="",
                text="효성",
                style_role="label",
                x=359.0,
                y=218.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c2.fruit",
                prompt="",
                text="사과",
                style_role="label",
                x=359.0,
                y=261.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c3.name",
                prompt="",
                text="영준",
                style_role="label",
                x=445.0,
                y=218.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c3.fruit",
                prompt="",
                text="포도",
                style_role="label",
                x=445.0,
                y=261.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c4.name",
                prompt="",
                text="규진",
                style_role="label",
                x=531.0,
                y=218.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c4.fruit",
                prompt="",
                text="사과",
                style_role="label",
                x=531.0,
                y=261.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c5.name",
                prompt="",
                text="현영",
                style_role="label",
                x=617.0,
                y=218.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r2c5.fruit",
                prompt="",
                text="딸기",
                style_role="label",
                x=617.0,
                y=261.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c1.name",
                prompt="",
                text="승희",
                style_role="label",
                x=273.0,
                y=306.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c1.fruit",
                prompt="",
                text="포도",
                style_role="label",
                x=273.0,
                y=349.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c2.name",
                prompt="",
                text="선미",
                style_role="label",
                x=359.0,
                y=306.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c2.fruit",
                prompt="",
                text="딸기",
                style_role="label",
                x=359.0,
                y=349.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c3.name",
                prompt="",
                text="은수",
                style_role="label",
                x=445.0,
                y=306.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c3.fruit",
                prompt="",
                text="사과",
                style_role="label",
                x=445.0,
                y=349.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c4.name",
                prompt="",
                text="재민",
                style_role="label",
                x=531.0,
                y=306.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c4.fruit",
                prompt="",
                text="바나나",
                style_role="label",
                x=531.0,
                y=349.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c5.name",
                prompt="",
                text="은채",
                style_role="label",
                x=617.0,
                y=306.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.r3c5.fruit",
                prompt="",
                text="사과",
                style_role="label",
                x=617.0,
                y=349.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.apple",
                prompt="",
                text="사과",
                style_role="label",
                x=344.0,
                y=410.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.grape",
                prompt="",
                text="포도",
                style_role="label",
                x=424.0,
                y=410.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.strawberry",
                prompt="",
                text="딸기",
                style_role="label",
                x=508.0,
                y=410.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.banana",
                prompt="",
                text="바나나",
                style_role="label",
                x=596.0,
                y=410.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice_text",
                prompt="",
                text="( 사과, 포도, 딸기, 바나나 )",
                style_role="note",
                x=542.0,
                y=450.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008955",
    "problem_type": "표에서정보찾기",
    "metadata": {
        "language": "ko",
        "question": "은호네 모둠 친구들이 좋아하는 과일을 조사하여 나타내었습니다. 선미가 좋아하는 과일을 선택하세요.",
        "instruction": "표에서 선미의 칸을 찾아 과일을 확인한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.table", "type": "data_table"},
            {"id": "obj.person.sunmi", "type": "person", "name": "선미"},
            {"id": "obj.fruit.apple", "type": "fruit", "name": "사과"},
            {"id": "obj.fruit.grape", "type": "fruit", "name": "포도"},
            {"id": "obj.fruit.strawberry", "type": "fruit", "name": "딸기"},
            {"id": "obj.fruit.banana", "type": "fruit", "name": "바나나"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.table", "obj.person.sunmi"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.lookup.favorite_fruit"],
            },
            "plan": {
                "method": "table_lookup",
                "description": "표에서 선미의 이름이 있는 칸을 찾아 그 칸의 과일을 읽는다.",
            },
            "execute": {"expected_operations": ["find_name", "read_cell_fruit", "match_legend"]},
            "review": {"check_methods": ["legend_match_check", "cell_lookup_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "favorite_fruit", "description": "선미가 좋아하는 과일"},
        "value": "딸기",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008955",
    "problem_type": "표에서정보찾기",
    "inputs": {
        "total_ticks": 0,
        "target_label": "선미가 좋아하는 과일",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.table", "value": "친구들이 좋아하는 과일 표"},
        {"ref": "obj.person.sunmi", "value": "선미"},
    ],
    "target": {"ref": "answer.target", "type": "favorite_fruit"},
    "method": "table_lookup",
    "plan": [
        "표에서 선미가 있는 칸을 찾는다.",
        "그 칸에 대응하는 과일을 확인한다.",
        "범례와 비교해 과일 이름을 읽는다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "선미가 있는 칸 찾기", "value": "3행 2열"},
        {"id": "step.2", "expr": "선미의 칸에 있는 과일 확인하기", "value": "딸기"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "범례와 칸의 그림이 일치하는가",
            "expected": "딸기",
            "actual": "딸기",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "favorite_fruit", "description": "선미가 좋아하는 과일"},
        "value": "딸기",
        "unit": "",
    },
}
