from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008709', title='원의 지름', canvas=Canvas(width=880.0, height=560.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.circle', 'slot.circle_label', 'slot.note_box', 'slot.note1', 'slot.note_arrow', 'slot.note2', 'slot.choice.1', 'slot.choice.2', 'slot.choice.3', 'slot.choice.4')),), slots=(TextSlot(id='slot.q1', prompt='', text='□ 5. □ 안에 공통으로 들어갈 선분으로 알맞은 것은 무엇인가요?', style_role='question', x=12.0, y=28.0, font_size=28), CircleSlot(id='slot.circle', prompt='', cx=472.0, cy=126.0, r=72.0, fill='none'), LineSlot(id='slot.circle.line1', prompt='', x1=430.0, y1=64.0, x2=390.0, y2=170.0), LineSlot(id='slot.circle.line2', prompt='', x1=452.0, y1=60.0, x2=414.0, y2=168.0), LineSlot(id='slot.circle.line3', prompt='', x1=478.0, y1=58.0, x2=440.0, y2=170.0), LineSlot(id='slot.circle.line4', prompt='', x1=546.0, y1=84.0, x2=512.0, y2=198.0), CircleSlot(id='slot.circle.center_mark', prompt='', cx=446.0, cy=125.0, r=4.0, fill='none'), CircleSlot(id='slot.circle.pink_dot', prompt='', cx=457.0, cy=124.0, r=3.5, fill='#ff4fa0'), TextSlot(id='slot.circle_label', prompt='', text='ㄱ ㄷ ㅁ ㄴ ㄹ ㅂ ㅅ ㅈ', style_role='label', x=414.0, y=46.0, font_size=22), RectSlot(id='slot.note_box', prompt='', x=90.0, y=220.0, width=750.0, height=127.0, fill='none'), TextSlot(id='slot.note1', prompt='', text='선분', style_role='note', x=137.0, y=271.0, font_size=30), RectSlot(id='slot.note1_blank', prompt='', x=190.0, y=248.0, width=67.0, height=31.0, fill='none'), TextSlot(id='slot.note_arrow', prompt='', text='→', style_role='note', x=271.0, y=300.0, font_size=34), TextSlot(id='slot.note2', prompt='', text='원의 지름은 선분', style_role='note', x=316.0, y=302.0, font_size=30), RectSlot(id='slot.note2_blank', prompt='', x=506.0, y=297.0, width=67.0, height=31.0, fill='none'), TextSlot(id='slot.note2_tail', prompt='', text='입니다.', style_role='note', x=584.0, y=302.0, font_size=30), TextSlot(id='slot.choice.1', prompt='', text='① ㄱㄴ', style_role='choice', x=21.0, y=392.0, font_size=28), TextSlot(id='slot.choice.2', prompt='', text='② ㄷㅁ', style_role='choice', x=477.0, y=392.0, font_size=28), TextSlot(id='slot.choice.3', prompt='', text='③ ㅁㅂ', style_role='choice', x=21.0, y=439.0, font_size=28), TextSlot(id='slot.choice.4', prompt='', text='④ ㅅㅈ', style_role='choice', x=477.0, y=439.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008709', 'problem_type': 'concept_multiple_choice', 'metadata': {'language': 'ko', 'question': '□ 안에 공통으로 들어갈 선분으로 알맞은 것은 무엇인가요?', 'instruction': '원의 지름의 뜻을 알고 알맞은 선분을 고르는 문제'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.diameter', 'type': 'segment', 'property': 'longest_segment_in_circle'}, {'id': 'obj.candidate_1', 'type': 'segment'}, {'id': 'obj.candidate_2', 'type': 'segment'}, {'id': 'obj.candidate_3', 'type': 'segment'}, {'id': 'obj.candidate_4', 'type': 'segment'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle'], 'target_ref': 'answer.target', 'condition_refs': ['rel.diameter_definition']}, 'plan': {'method': 'definition_match', 'description': '원의 지름의 뜻과 보기의 선분 이름을 맞춘다.'}, 'execute': {'expected_operations': ['identify_definition', 'compare_candidates', 'select_matching_segment']}, 'review': {'check_methods': ['definition_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'matching_segment_name', 'description': '두 빈칸에 공통으로 들어갈 선분 이름'}, 'value': 'ㅁㅂ', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008709', 'problem_type': 'concept_multiple_choice', 'inputs': {'total_ticks': 4, 'target_label': '원의 지름', 'target_ticks': 1, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': {'type': 'circle'}}, {'ref': 'obj.diameter', 'value': {'property': 'longest_segment_in_circle'}}], 'target': {'ref': 'answer.target', 'type': 'matching_segment_name'}, 'method': 'definition_match', 'plan': ['원의 지름의 뜻을 확인한다.', '보기 중 지름에 해당하는 선분 이름을 찾는다.', '두 빈칸에 같은 선분 이름이 들어가는지 확인한다.'], 'steps': [{'id': 'step.1', 'expr': '원의 지름 = 원 안에 그을 수 있는 가장 긴 선분', 'value': '정의 확인'}, {'id': 'step.2', 'expr': '보기에서 지름에 해당하는 선분을 고른다', 'value': 'ㅁㅂ'}, {'id': 'step.3', 'expr': '두 빈칸에 같은 선분 이름을 넣는다', 'value': 'ㅁㅂ'}], 'checks': [{'id': 'check.1', 'expr': '선분 ㅁㅂ가 원 안에 그을 수 있는 가장 긴 선분인지 확인', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'matching_segment_name', 'description': '두 빈칸에 공통으로 들어갈 선분 이름'}, 'value': 'ㅁㅂ', 'unit': ''}}
