from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008768', title='무게를 알맞게 어림한 것을 찾아 선택하세요', canvas=Canvas(width=808, height=333, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2')), Region(id='region.choice_box', role='figure', flow='absolute', slot_ids=('slot.box', 'slot.coin', 'slot.choice')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='70.', style_role='question', x=12.0, y=24.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='무게를 알맞게 어림한 것을 찾아 선택하세요.', style_role='question', x=53.0, y=24.0, font_size=28), RectSlot(id='slot.box', prompt='', x=292.0, y=78.0, width=390.0, height=154.0, fill='none', stroke='#00B050'), TextSlot(id='slot.coin', prompt='', text='동전 그림\n500', style_role='diagram', x=453.0, y=107.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='약 ( 7 g , 7kg , 7 t )', style_role='answer_choice', x=382.0, y=190.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008768', 'problem_type': 'weight_estimation_multiple_choice', 'metadata': {'language': 'ko', 'question': '무게를 알맞게 어림한 것을 찾아 선택하세요.', 'instruction': '보기 중 알맞은 무게를 고른다.'}, 'domain': {'objects': [{'id': 'obj.coin_500won', 'type': 'coin', 'label': '500원짜리 동전', 'unit': 'g'}, {'id': 'obj.choice_7g', 'type': 'weight_option', 'label': '7 g', 'unit': 'g'}, {'id': 'obj.choice_7kg', 'type': 'weight_option', 'label': '7kg', 'unit': 'kg'}, {'id': 'obj.choice_7t', 'type': 'weight_option', 'label': '7 t', 'unit': 't'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.coin_500won', 'obj.choice_7g', 'obj.choice_7kg', 'obj.choice_7t'], 'target_ref': 'answer.target', 'condition_refs': ['rel.select_best_estimate']}, 'plan': {'method': 'unit_reasoning', 'description': '동전의 무게와 보기의 단위를 비교하여 가장 알맞은 어림값을 고른다.'}, 'execute': {'expected_operations': ['compare_units', 'choose_reasonable_estimate']}, 'review': {'check_methods': ['unit_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'multiple_choice_weight_estimate', 'description': '500원짜리 동전의 알맞은 무게'}, 'value': '7 g', 'unit': 'g'}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008768', 'problem_type': 'weight_estimation_multiple_choice', 'inputs': {'total_ticks': 3, 'target_label': '500원짜리 동전의 알맞은 무게', 'target_ticks': 1, 'target_count': 1, 'unit': 'g'}, 'given': [{'ref': 'obj.coin_500won', 'value': {'label': '500원짜리 동전', 'unit': 'g'}}, {'ref': 'obj.choice_7g', 'value': {'label': '7 g', 'unit': 'g'}}, {'ref': 'obj.choice_7kg', 'value': {'label': '7kg', 'unit': 'kg'}}, {'ref': 'obj.choice_7t', 'value': {'label': '7 t', 'unit': 't'}}], 'target': {'ref': 'answer.target', 'type': 'multiple_choice_weight_estimate'}, 'method': 'unit_reasoning', 'plan': ['보기의 단위를 비교하여 500원짜리 동전의 무게로 가장 알맞은 값을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '7 g, 7kg, 7 t 비교', 'value': '7 g'}], 'checks': [{'id': 'check.1', 'expr': '선택한 단위가 동전의 무게로 적절한지 확인', 'expected': 'g', 'actual': 'g', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'multiple_choice_weight_estimate', 'description': '500원짜리 동전의 알맞은 무게'}, 'value': '7 g', 'unit': 'g'}}
