from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008771",
        title="실제 무게에 가장 가깝게 어림한 사람",
        canvas=Canvas(width=960, height=392, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.choice",
                    "slot.table_1.outer",
                    "slot.table_1.v1",
                    "slot.table_1.v2",
                    "slot.table_1.v3",
                    "slot.table_1.h1",
                    "slot.table_1.r1c1",
                    "slot.table_1.r1c2",
                    "slot.table_1.r1c3",
                    "slot.table_1.r1c4",
                    "slot.table_1.r2c1",
                    "slot.table_1.r2c2",
                    "slot.table_1.r2c3",
                    "slot.table_1.r2c4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="주연, 선우, 다혜는 실제 무게가 2 kg 100 g인 고양이의 무게를 다음과 같이",
                style_role="question",
                x=18,
                y=44,
                font_size=28,
                fill="#111111",
                max_width=927.36,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="어림하였습니다. 실제 무게에 가장 가깝게 어림한 사람은 누구인가요?",
                style_role="question",
                x=18,
                y=84,
                font_size=28,
                fill="#111111",
                max_width=745.92,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 주연 , 선우 , 다혜 )",
                style_role="note",
                x=335,
                y=379,
                font_size=28,
                fill="#111111",
                max_width=322.56,
            ),
            RectSlot(
                id="slot.table_1.outer",
                prompt="",
                x=60,
                y=115,
                width=705,
                height=165,
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v1",
                prompt="",
                x1=240,
                y1=115,
                x2=240,
                y2=280,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v2",
                prompt="",
                x1=430,
                y1=115,
                x2=430,
                y2=280,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v3",
                prompt="",
                x1=605,
                y1=115,
                x2=605,
                y2=280,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.h1",
                prompt="",
                x1=60,
                y1=195,
                x2=765,
                y2=195,
                stroke="#111827",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table_1.r1c1",
                prompt="",
                text="이름",
                x=150,
                y=167,
                font_size=28,
                max_width=160,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c2",
                prompt="",
                text="주연",
                x=335,
                y=167,
                font_size=28,
                max_width=170,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c3",
                prompt="",
                text="선우",
                x=520,
                y=167,
                font_size=28,
                max_width=155,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c4",
                prompt="",
                text="다혜",
                x=685,
                y=167,
                font_size=28,
                max_width=140,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c1",
                prompt="",
                text="어림한 무게",
                x=150,
                y=249,
                font_size=28,
                max_width=160,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c2",
                prompt="",
                text="약 2kg",
                x=335,
                y=249,
                font_size=28,
                max_width=170,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c3",
                prompt="",
                text="약 2kg 300g",
                x=520.897,
                y=248.665,
                font_size=28,
                max_width=155,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c4",
                prompt="",
                text="약 1kg 800g",
                x=684.103,
                y=247.768,
                font_size=28,
                max_width=140,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008771",
    "problem_type": "비교_가까운_어림값",
    "metadata": {
        "language": "ko",
        "question": "실제 무게 2 kg 100 g에 가장 가깝게 어림한 사람을 찾는 문제",
        "instruction": "실제 무게에 가장 가깝게 어림한 사람은 누구인가요?",
    },
    "domain": {
        "objects": [
            {"id": "obj.actual_weight", "type": "weight", "value": "2 kg 100 g"},
            {"id": "obj.juyeon", "type": "estimate", "owner": "주연", "value": "2 kg"},
            {"id": "obj.seonu", "type": "estimate", "owner": "선우", "value": "2 kg 300 g"},
            {"id": "obj.dahye", "type": "estimate", "owner": "다혜", "value": "1 kg 800 g"},
        ],
        "relations": [],
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_name", "description": "실제 무게에 가장 가깝게 어림한 사람"},
        "value": "주연",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008771",
    "problem_type": "비교_가까운_어림값",
    "inputs": {
        "total_ticks": 0,
        "target_label": "실제 무게에 가장 가깝게 어림한 사람",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "kg,g",
    },
    "given": [
        {"ref": "obj.actual_weight", "value": "2 kg 100 g"},
        {"ref": "obj.juyeon", "value": "2 kg"},
        {"ref": "obj.seonu", "value": "2 kg 300 g"},
        {"ref": "obj.dahye", "value": "1 kg 800 g"},
    ],
    "target": {"ref": "answer.target", "type": "person_name"},
    "method": "compare_distances",
    "plan": ["실제 무게와 각 어림값의 차이를 비교합니다.", "가장 차이가 작은 사람을 찾습니다."],
    "steps": [
        {"id": "step.1", "expr": "2 kg 100 g와 주연의 어림값 2 kg 비교", "value": "100 g 차이"},
        {
            "id": "step.2",
            "expr": "2 kg 100 g와 선우의 어림값 2 kg 300 g 비교",
            "value": "200 g 차이",
        },
        {
            "id": "step.3",
            "expr": "2 kg 100 g와 다혜의 어림값 1 kg 800 g 비교",
            "value": "300 g 차이",
        },
        {"id": "step.4", "expr": "가장 차이가 작은 사람 선택", "value": "주연"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "100 g, 200 g, 300 g 중 가장 작은 값 확인",
            "expected": "100 g",
            "actual": "100 g",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_name", "description": "실제 무게에 가장 가깝게 어림한 사람"},
        "value": "주연",
        "unit": "",
    },
}
