from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    CircleSlot,
    RectSlot,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008659",
        title="원의 중심 찾기",
        canvas=Canvas(width=640.0, height=420.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.qnum", "slot.question"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.grid_frame",
                    "slot.grid.v1",
                    "slot.grid.v2",
                    "slot.grid.v3",
                    "slot.grid.v4",
                    "slot.grid.v5",
                    "slot.grid.v6",
                    "slot.grid.v7",
                    "slot.grid.v8",
                    "slot.grid.v9",
                    "slot.grid.h1",
                    "slot.grid.h2",
                    "slot.grid.h3",
                    "slot.grid.h4",
                    "slot.grid.h5",
                    "slot.grid.h6",
                    "slot.grid.h7",
                    "slot.grid.h8",
                    "slot.grid.h9",
                    "slot.circle",
                    "slot.pt.giyeok",
                    "slot.pt.nieun",
                    "slot.pt.mieum",
                    "slot.pt.rieul",
                    "slot.lb.giyeok",
                    "slot.lb.nieun",
                    "slot.lb.mieum",
                    "slot.lb.rieul",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.qnum",
                prompt="",
                text="□ 34.",
                style_role="question",
                x=12.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.question",
                prompt="",
                text="그림에서 원의 중심을 선택해 보세요.",
                style_role="question",
                x=82.0,
                y=28.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.grid_frame",
                prompt="",
                x=360.0,
                y=58.0,
                width=206.0,
                height=206.0,
                fill="none",
                stroke="#4DB3FF",
            ),
            LineSlot(
                id="slot.grid.v1",
                prompt="",
                x1=385.0,
                y1=58.0,
                x2=385.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v2",
                prompt="",
                x1=410.0,
                y1=58.0,
                x2=410.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v3",
                prompt="",
                x1=435.0,
                y1=58.0,
                x2=435.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v4",
                prompt="",
                x1=460.0,
                y1=58.0,
                x2=460.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v5",
                prompt="",
                x1=485.0,
                y1=58.0,
                x2=485.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v6",
                prompt="",
                x1=510.0,
                y1=58.0,
                x2=510.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v7",
                prompt="",
                x1=535.0,
                y1=58.0,
                x2=535.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v8",
                prompt="",
                x1=560.0,
                y1=58.0,
                x2=560.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v9",
                prompt="",
                x1=585.0,
                y1=58.0,
                x2=585.0,
                y2=264.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h1",
                prompt="",
                x1=360.0,
                y1=83.0,
                x2=566.0,
                y2=83.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h2",
                prompt="",
                x1=360.0,
                y1=108.0,
                x2=566.0,
                y2=108.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h3",
                prompt="",
                x1=360.0,
                y1=133.0,
                x2=566.0,
                y2=133.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h4",
                prompt="",
                x1=360.0,
                y1=158.0,
                x2=566.0,
                y2=158.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h5",
                prompt="",
                x1=360.0,
                y1=183.0,
                x2=566.0,
                y2=183.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h6",
                prompt="",
                x1=360.0,
                y1=208.0,
                x2=566.0,
                y2=208.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h7",
                prompt="",
                x1=360.0,
                y1=233.0,
                x2=566.0,
                y2=233.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h8",
                prompt="",
                x1=360.0,
                y1=258.0,
                x2=566.0,
                y2=258.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h9",
                prompt="",
                x1=360.0,
                y1=283.0,
                x2=566.0,
                y2=283.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.circle",
                prompt="",
                cx=463.0,
                cy=163.0,
                r=81.0,
                fill="none",
                stroke="#222222",
            ),
            CircleSlot(
                id="slot.pt.giyeok",
                prompt="",
                cx=385.0,
                cy=183.0,
                r=4.0,
                fill="#D81B60",
            ),
            CircleSlot(
                id="slot.pt.nieun", prompt="", cx=420.0, cy=150.0, r=4.0, fill="#D81B60"
            ),
            CircleSlot(
                id="slot.pt.mieum", prompt="", cx=463.0, cy=130.0, r=4.0, fill="#D81B60"
            ),
            CircleSlot(
                id="slot.pt.rieul", prompt="", cx=463.0, cy=183.0, r=4.0, fill="#D81B60"
            ),
            TextSlot(
                id="slot.lb.giyeok",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=370.0,
                y=198.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.nieun",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=431.0,
                y=165.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.mieum",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=456.0,
                y=150.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.rieul",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=454.0,
                y=198.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008659",
    "problem_type": "도형_원의중심_선택",
    "metadata": {
        "language": "ko",
        "question": "그림에서 원의 중심을 선택해 보세요.",
        "instruction": "그림에서 원의 중심을 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.point.giyeok", "type": "point", "label": "ㄱ"},
            {"id": "obj.point.nieun", "type": "point", "label": "ㄴ"},
            {"id": "obj.point.mieum", "type": "point", "label": "ㅁ"},
            {"id": "obj.point.rieul", "type": "point", "label": "ㄹ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.circle",
                    "obj.point.giyeok",
                    "obj.point.nieun",
                    "obj.point.mieum",
                    "obj.point.rieul",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.center_choice"],
            },
            "plan": {
                "method": "중심_판단",
                "description": "원의 안쪽에서 가장 중심에 있는 점을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "원 내부의 후보점을 비교한다",
                    "중심에 해당하는 점을 선택한다",
                ]
            },
            "review": {"check_methods": ["원 안에서 가장 중앙에 있는지 확인한다"]},
        },
    },
    "answer": {
        "target": {"type": "selected_point", "description": "원의 중심"},
        "value": "ㄹ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008659",
    "problem_type": "도형_원의중심_선택",
    "inputs": {
        "total_ticks": 0,
        "target_label": "원의 중심",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": {"type": "circle"}},
        {"ref": "obj.point.giyeok", "value": {"label": "ㄱ"}},
        {"ref": "obj.point.nieun", "value": {"label": "ㄴ"}},
        {"ref": "obj.point.mieum", "value": {"label": "ㅁ"}},
        {"ref": "obj.point.rieul", "value": {"label": "ㄹ"}},
    ],
    "target": {"ref": "answer.target", "type": "selected_point"},
    "method": "중심_판단",
    "plan": [
        "그림에서 원 안의 후보점들을 살펴본다.",
        "원의 가장 중심에 있는 점을 고른다.",
    ],
    "steps": [{"id": "step.1", "expr": "원 내부 후보점 비교", "value": "ㄹ"}],
    "checks": [
        {
            "id": "check.1",
            "expr": "원의 중심인지 확인",
            "expected": "ㄹ",
            "actual": "ㄹ",
            "pass": True,
        }
    ],
    "answer": {"value": "ㄹ", "unit": "", "derived_from": "step.1"},
}
