from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008657",
        title="원을 그릴 때 컴퍼스를 바르게 사용하는 것",
        canvas=Canvas(width=940.0, height=366.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.title.mark", "slot.title.no", "slot.title.text"),
            ),
            Region(
                id="region.options",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.box",
                    "slot.opt.a.label",
                    "slot.opt.a.circle",
                    "slot.opt.a.center",
                    "slot.opt.a.center2",
                    "slot.opt.a.compass.left",
                    "slot.opt.a.compass.right",
                    "slot.opt.a.compass.tip",
                    "slot.opt.a.compass.lead",
                    "slot.opt.b.label",
                    "slot.opt.b.circle",
                    "slot.opt.b.center",
                    "slot.opt.b.center2",
                    "slot.opt.b.compass.left",
                    "slot.opt.b.compass.right",
                    "slot.opt.b.compass.tip",
                    "slot.opt.b.compass.lead",
                    "slot.opt.c.label",
                    "slot.opt.c.circle",
                    "slot.opt.c.center",
                    "slot.opt.c.center2",
                    "slot.opt.c.compass.left",
                    "slot.opt.c.compass.right",
                    "slot.opt.c.compass.tip",
                    "slot.opt.c.compass.lead",
                ),
            ),
            Region(id="region.footer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.title.mark",
                prompt="",
                text="□",
                style_role="question",
                x=12.0,
                y=22.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.title.no",
                prompt="",
                text="32.",
                style_role="question",
                x=36.0,
                y=22.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.title.text",
                prompt="",
                text="원을 그릴 때 컴퍼스를 바르게 사용하는 것을 찾아 선택해보세요.",
                style_role="question",
                x=82.0,
                y=22.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.box",
                prompt="",
                x=203.0,
                y=52.0,
                width=596.0,
                height=191.0,
                fill="none",
                stroke="#18B7AF",
                stroke_width=2.0,
            ),
            TextSlot(
                id="slot.opt.a.label",
                prompt="",
                text="가",
                style_role="label",
                x=242.0,
                y=90.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt.a.circle",
                prompt="",
                cx=292.0,
                cy=162.0,
                r=40.0,
                fill="none",
                stroke="#A9A9A9",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt.a.center",
                prompt="",
                cx=293.0,
                cy=154.0,
                r=3.0,
                fill="#E91E63",
            ),
            CircleSlot(
                id="slot.opt.a.center2",
                prompt="",
                cx=292.0,
                cy=179.0,
                r=4.0,
                fill="none",
                stroke="#666666",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.opt.a.compass.left",
                prompt="",
                x1=291.0,
                y1=102.0,
                x2=259.0,
                y2=152.0,
                stroke="#95A5A6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.opt.a.compass.right",
                prompt="",
                x1=291.0,
                y1=102.0,
                x2=327.0,
                y2=151.0,
                stroke="#95A5A6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.opt.a.compass.tip",
                prompt="",
                x1=338.0,
                y1=107.0,
                x2=338.0,
                y2=170.0,
                stroke="#B6B84B",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.opt.a.compass.lead",
                prompt="",
                x1=338.0,
                y1=158.0,
                x2=338.0,
                y2=168.0,
                stroke="#E2AF4A",
                stroke_width=2.5,
            ),
            TextSlot(
                id="slot.opt.b.label",
                prompt="",
                text="나",
                style_role="label",
                x=471.0,
                y=90.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt.b.circle",
                prompt="",
                cx=522.0,
                cy=162.0,
                r=40.0,
                fill="none",
                stroke="#A9A9A9",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt.b.center",
                prompt="",
                cx=523.0,
                cy=154.0,
                r=3.0,
                fill="#E91E63",
            ),
            CircleSlot(
                id="slot.opt.b.center2",
                prompt="",
                cx=522.0,
                cy=179.0,
                r=4.0,
                fill="none",
                stroke="#666666",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.opt.b.compass.left",
                prompt="",
                x1=521.0,
                y1=102.0,
                x2=507.0,
                y2=151.0,
                stroke="#95A5A6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.opt.b.compass.right",
                prompt="",
                x1=521.0,
                y1=102.0,
                x2=551.0,
                y2=152.0,
                stroke="#95A5A6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.opt.b.compass.tip",
                prompt="",
                x1=559.0,
                y1=107.0,
                x2=559.0,
                y2=170.0,
                stroke="#B6B84B",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.opt.b.compass.lead",
                prompt="",
                x1=559.0,
                y1=158.0,
                x2=559.0,
                y2=168.0,
                stroke="#E2AF4A",
                stroke_width=2.5,
            ),
            TextSlot(
                id="slot.opt.c.label",
                prompt="",
                text="다",
                style_role="label",
                x=650.0,
                y=90.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.opt.c.circle",
                prompt="",
                cx=706.0,
                cy=162.0,
                r=40.0,
                fill="none",
                stroke="#A9A9A9",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt.c.center",
                prompt="",
                cx=707.0,
                cy=154.0,
                r=3.0,
                fill="#E91E63",
            ),
            CircleSlot(
                id="slot.opt.c.center2",
                prompt="",
                cx=706.0,
                cy=179.0,
                r=4.0,
                fill="none",
                stroke="#666666",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.opt.c.compass.left",
                prompt="",
                x1=705.0,
                y1=102.0,
                x2=691.0,
                y2=151.0,
                stroke="#95A5A6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.opt.c.compass.right",
                prompt="",
                x1=705.0,
                y1=102.0,
                x2=734.0,
                y2=152.0,
                stroke="#95A5A6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.opt.c.compass.tip",
                prompt="",
                x1=675.0,
                y1=107.0,
                x2=675.0,
                y2=170.0,
                stroke="#B6B84B",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.opt.c.compass.lead",
                prompt="",
                x1=675.0,
                y1=158.0,
                x2=675.0,
                y2=168.0,
                stroke="#E2AF4A",
                stroke_width=2.5,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008657",
    "problem_type": "도형_보기선택",
    "metadata": {
        "language": "ko",
        "question": "원을 그릴 때 컴퍼스를 바르게 사용하는 것을 찾아 선택하는 문제",
        "instruction": "보기 가, 나, 다 중에서 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.compass", "type": "compass"},
            {
                "id": "obj.center",
                "type": "point",
                "description": "원의 중심으로 보이는 점",
            },
            {"id": "obj.choice.a", "type": "option", "label": "가"},
            {"id": "obj.choice.b", "type": "option", "label": "나"},
            {"id": "obj.choice.c", "type": "option", "label": "다"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.circle",
                    "obj.compass",
                    "obj.choice.a",
                    "obj.choice.b",
                    "obj.choice.c",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.correct_usage"],
            },
            "plan": {
                "method": "visual_choice",
                "description": "컴퍼스 침이 원의 중심에 놓인 보기인지 확인한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_three_options",
                    "check_center_alignment",
                ]
            },
            "review": {
                "check_methods": ["match_explanation_text", "confirm_selected_option"]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_option",
            "description": "컴퍼스를 바르게 사용하는 보기",
        },
        "value": "나",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008657",
    "problem_type": "도형_보기선택",
    "inputs": {
        "total_ticks": 0,
        "target_label": "컴퍼스를 바르게 사용하는 보기",
        "target_ticks": 0,
        "target_count": 3,
        "unit": "",
    },
    "given": [
        {"ref": "obj.choice.a", "value": "가"},
        {"ref": "obj.choice.b", "value": "나"},
        {"ref": "obj.choice.c", "value": "다"},
    ],
    "target": {"ref": "answer.target", "type": "selected_option"},
    "method": "visual_choice",
    "plan": [
        "세 보기에서 컴퍼스 침의 위치를 비교한다.",
        "원의 중심에 침이 놓인 보기를 찾는다.",
    ],
    "steps": [{"id": "step.1", "expr": "보기 가, 나, 다 비교", "value": "나"}],
    "checks": [
        {
            "id": "check.1",
            "expr": "해설의 선택지와 일치하는지 확인",
            "expected": "나",
            "actual": "나",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_option",
            "description": "컴퍼스를 바르게 사용하는 보기",
        },
        "value": "나",
        "unit": "",
    },
}
