from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008643",
        title="원의 중심",
        canvas=Canvas(width=700, height=620, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header",
                role="stem",
                flow="absolute",
                slot_ids=("slot.qnum", "slot.qtext", "slot.checkbox"),
            ),
            Region(
                id="region.diagram.top",
                role="figure",
                flow="absolute",
                slot_ids=(
                    "slot.grid.top.v1",
                    "slot.grid.top.v2",
                    "slot.grid.top.v3",
                    "slot.grid.top.v4",
                    "slot.grid.top.v5",
                    "slot.grid.top.v6",
                    "slot.grid.top.v7",
                    "slot.grid.top.v8",
                    "slot.grid.top.v9",
                    "slot.grid.top.h1",
                    "slot.grid.top.h2",
                    "slot.grid.top.h3",
                    "slot.grid.top.h4",
                    "slot.grid.top.h5",
                    "slot.grid.top.h6",
                    "slot.grid.top.h7",
                    "slot.grid.top.h8",
                    "slot.grid.top.h9",
                    "slot.circle.top",
                    "slot.pt.top.ga",
                    "slot.pt.top.na",
                    "slot.pt.top.da",
                    "slot.pt.top.ra",
                    "slot.pt.top.ma",
                    "slot.lb.top.ga",
                    "slot.lb.top.na",
                    "slot.lb.top.da",
                    "slot.lb.top.ra",
                    "slot.lb.top.ma",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
            Region(
                id="region.explanation",
                role="explanation",
                flow="absolute",
                slot_ids=(),
            ),
            Region(
                id="region.diagram.bottom",
                role="figure",
                flow="absolute",
                slot_ids=(
                    "slot.grid.bottom.v1",
                    "slot.grid.bottom.v2",
                    "slot.grid.bottom.v3",
                    "slot.grid.bottom.v4",
                    "slot.grid.bottom.v5",
                    "slot.grid.bottom.v6",
                    "slot.grid.bottom.v7",
                    "slot.grid.bottom.v8",
                    "slot.grid.bottom.v9",
                    "slot.grid.bottom.h1",
                    "slot.grid.bottom.h2",
                    "slot.grid.bottom.h3",
                    "slot.grid.bottom.h4",
                    "slot.grid.bottom.h5",
                    "slot.grid.bottom.h6",
                    "slot.grid.bottom.h7",
                    "slot.grid.bottom.h8",
                    "slot.grid.bottom.h9",
                    "slot.circle.bottom",
                    "slot.emph.bottom",
                    "slot.pt.bottom.ga",
                    "slot.pt.bottom.na",
                    "slot.pt.bottom.da",
                    "slot.pt.bottom.ra",
                    "slot.pt.bottom.ma",
                    "slot.lb.bottom.ga",
                    "slot.lb.bottom.na",
                    "slot.lb.bottom.da",
                    "slot.lb.bottom.ra",
                    "slot.lb.bottom.ma",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.checkbox",
                prompt="",
                text="□",
                style_role="question",
                x=10.0,
                y=27.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.qnum",
                prompt="",
                text="15.",
                style_role="question",
                x=30.0,
                y=30.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.qtext",
                prompt="",
                text="원의 중심을 찾아 선택해 보세요.",
                style_role="question",
                x=72.0,
                y=30.0,
                font_size=28,
            ),
            LineSlot(
                id="slot.grid.top.v1",
                prompt="",
                x1=396.0,
                y1=50.0,
                x2=396.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v2",
                prompt="",
                x1=420.0,
                y1=50.0,
                x2=420.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v3",
                prompt="",
                x1=444.0,
                y1=50.0,
                x2=444.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v4",
                prompt="",
                x1=468.0,
                y1=50.0,
                x2=468.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v5",
                prompt="",
                x1=492.0,
                y1=50.0,
                x2=492.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v6",
                prompt="",
                x1=516.0,
                y1=50.0,
                x2=516.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v7",
                prompt="",
                x1=540.0,
                y1=50.0,
                x2=540.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v8",
                prompt="",
                x1=564.0,
                y1=50.0,
                x2=564.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v9",
                prompt="",
                x1=588.0,
                y1=50.0,
                x2=588.0,
                y2=258.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h1",
                prompt="",
                x1=396.0,
                y1=50.0,
                x2=588.0,
                y2=50.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h2",
                prompt="",
                x1=396.0,
                y1=74.0,
                x2=588.0,
                y2=74.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h3",
                prompt="",
                x1=396.0,
                y1=98.0,
                x2=588.0,
                y2=98.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h4",
                prompt="",
                x1=396.0,
                y1=122.0,
                x2=588.0,
                y2=122.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h5",
                prompt="",
                x1=396.0,
                y1=146.0,
                x2=588.0,
                y2=146.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h6",
                prompt="",
                x1=396.0,
                y1=170.0,
                x2=588.0,
                y2=170.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h7",
                prompt="",
                x1=396.0,
                y1=194.0,
                x2=588.0,
                y2=194.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h8",
                prompt="",
                x1=396.0,
                y1=218.0,
                x2=588.0,
                y2=218.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.h9",
                prompt="",
                x1=396.0,
                y1=242.0,
                x2=588.0,
                y2=242.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.circle.top",
                prompt="",
                cx=492.0,
                cy=146.0,
                r=73.0,
                fill="none",
                stroke="#444444",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.pt.top.ga", prompt="", cx=492.0, cy=74.0, r=3.8, fill="#d94b8a"
            ),
            CircleSlot(
                id="slot.pt.top.na",
                prompt="",
                cx=492.0,
                cy=146.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.top.da",
                prompt="",
                cx=540.0,
                cy=146.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.top.ra",
                prompt="",
                cx=444.0,
                cy=194.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.top.ma",
                prompt="",
                cx=540.0,
                cy=194.0,
                r=3.8,
                fill="#d94b8a",
            ),
            TextSlot(
                id="slot.lb.top.ga",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=503.0,
                y=81.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.top.na",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=503.0,
                y=161.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.top.da",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=551.0,
                y=161.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.top.ra",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=455.0,
                y=209.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.top.ma",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=551.0,
                y=209.0,
                font_size=24,
            ),
            LineSlot(
                id="slot.grid.bottom.v1",
                prompt="",
                x1=37.0,
                y1=396.0,
                x2=37.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v2",
                prompt="",
                x1=61.0,
                y1=396.0,
                x2=61.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v3",
                prompt="",
                x1=85.0,
                y1=396.0,
                x2=85.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v4",
                prompt="",
                x1=109.0,
                y1=396.0,
                x2=109.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v5",
                prompt="",
                x1=133.0,
                y1=396.0,
                x2=133.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v6",
                prompt="",
                x1=157.0,
                y1=396.0,
                x2=157.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v7",
                prompt="",
                x1=181.0,
                y1=396.0,
                x2=181.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v8",
                prompt="",
                x1=205.0,
                y1=396.0,
                x2=205.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v9",
                prompt="",
                x1=229.0,
                y1=396.0,
                x2=229.0,
                y2=585.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h1",
                prompt="",
                x1=37.0,
                y1=396.0,
                x2=229.0,
                y2=396.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h2",
                prompt="",
                x1=37.0,
                y1=420.0,
                x2=229.0,
                y2=420.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h3",
                prompt="",
                x1=37.0,
                y1=444.0,
                x2=229.0,
                y2=444.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h4",
                prompt="",
                x1=37.0,
                y1=468.0,
                x2=229.0,
                y2=468.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h5",
                prompt="",
                x1=37.0,
                y1=492.0,
                x2=229.0,
                y2=492.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h6",
                prompt="",
                x1=37.0,
                y1=516.0,
                x2=229.0,
                y2=516.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h7",
                prompt="",
                x1=37.0,
                y1=540.0,
                x2=229.0,
                y2=540.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h8",
                prompt="",
                x1=37.0,
                y1=564.0,
                x2=229.0,
                y2=564.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.h9",
                prompt="",
                x1=37.0,
                y1=588.0,
                x2=229.0,
                y2=588.0,
                stroke="#43b7ff",
                stroke_dasharray="5 3",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.circle.bottom",
                prompt="",
                cx=133.0,
                cy=492.0,
                r=73.0,
                fill="none",
                stroke="#444444",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.emph.bottom",
                prompt="",
                cx=133.0,
                cy=492.0,
                r=18.0,
                fill="none",
                stroke="#c9d7ff",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.pt.bottom.ga",
                prompt="",
                cx=133.0,
                cy=420.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.bottom.na",
                prompt="",
                cx=133.0,
                cy=492.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.bottom.da",
                prompt="",
                cx=181.0,
                cy=492.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.bottom.ra",
                prompt="",
                cx=85.0,
                cy=540.0,
                r=3.8,
                fill="#d94b8a",
            ),
            CircleSlot(
                id="slot.pt.bottom.ma",
                prompt="",
                cx=181.0,
                cy=540.0,
                r=3.8,
                fill="#d94b8a",
            ),
            TextSlot(
                id="slot.lb.bottom.ga",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=144.0,
                y=427.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.bottom.na",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=144.0,
                y=507.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.bottom.da",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=192.0,
                y=507.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.bottom.ra",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=96.0,
                y=555.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.bottom.ma",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=192.0,
                y=555.0,
                font_size=24,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008643",
    "problem_type": "geometry_circle_center",
    "metadata": {
        "language": "ko",
        "question": "원의 중심을 찾아 선택해 보세요.",
        "instruction": "정답을 선택한다.",
        "points": 0,
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center_candidate", "type": "point", "label": "ㄴ"},
            {
                "id": "obj.points_on_figure",
                "type": "point_set",
                "labels": ["ㄱ", "ㄷ", "ㄹ", "ㅁ"],
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle", "obj.points_on_figure"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.center_property"],
            },
            "plan": {
                "method": "circle_center_identification",
                "description": "원 위의 점들과 같은 거리를 가지는 중심 후보를 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_center_candidate",
                    "match_visual_center",
                ]
            },
            "review": {"check_methods": ["center_property_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_point", "description": "원의 중심"},
        "value": "ㄴ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008643",
    "problem_type": "geometry_circle_center",
    "inputs": {
        "total_ticks": 0,
        "target_label": "원의 중심",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": "circle"},
        {"ref": "obj.points_on_figure", "value": ["ㄱ", "ㄷ", "ㄹ", "ㅁ"]},
    ],
    "target": {"ref": "answer.target", "type": "selected_point"},
    "method": "circle_center_identification",
    "plan": [
        "원의 중심과 원 위의 점 사이의 거리가 같다는 성질을 이용한다.",
        "그림에서 중심처럼 보이는 점을 찾는다.",
    ],
    "steps": [{"id": "step.1", "expr": "원의 중심 후보를 찾는다", "value": "ㄴ"}],
    "checks": [
        {
            "id": "check.1",
            "expr": "원의 중심은 원 위의 점들과 같은 거리를 가져야 한다",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_point", "description": "원의 중심"},
        "value": "ㄴ",
        "unit": "",
    },
}
