from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, PathSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009057', title='각을 찾아 선택하세요', canvas=Canvas(width=646, height=343, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.pnum', 'slot.instruction')), Region(id='region.options', role='body', flow='absolute', slot_ids=('slot.options_box', 'slot.opt1.curve', 'slot.opt1.base', 'slot.opt2.up', 'slot.opt2.down', 'slot.opt3.left', 'slot.opt3.right')), Region(id='region.answer', role='body', flow='absolute', slot_ids=('slot.answer_shape1', 'slot.answer_shape2')), Region(id='region.explanation', role='explanation', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.pnum', prompt='', text='95.', style_role='question', x=16.0, y=27.0, font_size=24), TextSlot(id='slot.instruction', prompt='', text='각을 찾아 선택하세요.', style_role='question', x=75.0, y=27.0, font_size=28), RectSlot(id='slot.options_box', prompt='', x=208.0, y=46.0, width=398.0, height=67.0, rx=8.0, ry=8.0), PathSlot(id='slot.opt1.curve', prompt='', d='M 231.0 72.0 Q 264.0 71.0 274.0 102.0'), LineSlot(id='slot.opt1.base', prompt='', x1=229.0, y1=102.0, x2=270.0, y2=102.0), LineSlot(id='slot.opt2.up', prompt='', x1=319.0, y1=92.0, x2=386.0, y2=68.0), LineSlot(id='slot.opt2.down', prompt='', x1=319.0, y1=84.0, x2=385.0, y2=94.0), LineSlot(id='slot.opt3.left', prompt='', x1=442.0, y1=72.0, x2=501.0, y2=101.0), LineSlot(id='slot.opt3.right', prompt='', x1=443.0, y1=72.0, x2=503.0, y2=102.0), LineSlot(id='slot.answer_shape1', prompt='', x1=71.0, y1=170.0, x2=150.0, y2=210.0), LineSlot(id='slot.answer_shape2', prompt='', x1=70.0, y1=170.0, x2=141.0, y2=170.0)), diagrams=(), groups=(), constraints=(), tags=('초등수학', '각', '선택형'))
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009057', 'problem_type': '도형_분류', 'metadata': {'language': 'ko', 'question': '각을 찾아 선택하세요.', 'instruction': '각인지 아닌지를 도형으로 판단하는 선택형 문제'}, 'domain': {'objects': [{'id': 'obj.option_1', 'type': 'figure', 'description': '곡선과 직선이 함께 보이는 선택지'}, {'id': 'obj.option_2', 'type': 'figure', 'description': '두 선이 한 점에서 만나지 않는 선택지'}, {'id': 'obj.option_3', 'type': 'figure', 'description': '두 직선이 한 점에서 만나는 듯 보이는 선택지'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.option_1', 'obj.option_2', 'obj.option_3'], 'target_ref': 'answer.target', 'condition_refs': ['rel.classify_angle']}, 'plan': {'method': '도형_분류', 'description': '각의 조건에 맞는 그림을 고른다.'}, 'execute': {'expected_operations': ['도형의 선 모양 확인', '한 점에서 만나는지 확인', '각인지 분류']}, 'review': {'check_methods': ['조건 일치 확인', '해설 문구와 선택지 대응 확인']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_figure', 'description': '각을 나타내는 그림'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009057', 'problem_type': '도형_분류', 'inputs': {'total_ticks': 3, 'target_label': '각', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.option_1', 'value': {'description': '곡선과 직선이 함께 보이는 선택지'}}, {'ref': 'obj.option_2', 'value': {'description': '두 선이 한 점에서 만나지 않는 선택지'}}, {'ref': 'obj.option_3', 'value': {'description': '두 직선이 한 점에서 만나는 듯 보이는 선택지'}}], 'target': {'ref': 'answer.target', 'type': 'selected_figure'}, 'method': '도형_분류', 'plan': ['각의 조건을 확인하고 선택지의 도형을 비교한다.'], 'steps': [{'id': 'step.1', 'expr': '선택지 1의 선 모양 확인', 'value': '곡선과 직선이 함께 보임'}, {'id': 'step.2', 'expr': '선택지 2의 만남 여부 확인', 'value': '두 반직선이 한 점에서 만나지 않음'}, {'id': 'step.3', 'expr': '선택지 3의 만남 여부 확인', 'value': '두 직선이 한 점에서 만나는 듯 보임'}], 'checks': [{'id': 'check.1', 'expr': '해설 문구가 각의 조건을 설명하는지 확인', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_figure', 'description': '각을 나타내는 그림'}, 'value': 0, 'unit': ''}}
