from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008907', title='태어난 계절별 학생 수', canvas=Canvas(width=940, height=399, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.title', 'slot.table.outer', 'slot.table.v1', 'slot.table.v2', 'slot.table.v3', 'slot.table.v4', 'slot.table.v5', 'slot.table.h1', 'slot.table.r1c1', 'slot.table.r1c2', 'slot.table.r1c3', 'slot.table.r1c4', 'slot.table.r1c5', 'slot.table.r1c6', 'slot.table.r2c1', 'slot.table.r2c2', 'slot.table.r2c3', 'slot.table.r2c4', 'slot.table.r2c5', 'slot.table.r2c6', 'slot.choice')),), slots=(TextSlot(id='slot.q1', prompt='', text='73. 유라네 반 학생들이 태어난 계절을 조사하여 표로 나타내었습니다. 가장 많은 학생들이 태어난 계절을 선택해 보세요.', style_role='question', x=20.0, y=20.0, font_size=28), TextSlot(id='slot.title', prompt='', text='태어난 계절별 학생 수', style_role='title', x=465.0, y=108.0, font_size=28), RectSlot(id='slot.table.outer', prompt='', x=168.0, y=121.0, width=648.0, height=80.0), RectSlot(id='slot.table.v1', prompt='', x=338.0, y=121.0, width=1.0, height=80.0), RectSlot(id='slot.table.v2', prompt='', x=435.0, y=121.0, width=1.0, height=80.0), RectSlot(id='slot.table.v3', prompt='', x=532.0, y=121.0, width=1.0, height=80.0), RectSlot(id='slot.table.v4', prompt='', x=629.0, y=121.0, width=1.0, height=80.0), RectSlot(id='slot.table.v5', prompt='', x=726.0, y=121.0, width=1.0, height=80.0), RectSlot(id='slot.table.h1', prompt='', x=168.0, y=161.0, width=648.0, height=1.0), TextSlot(id='slot.table.r1c1', prompt='', text='계절', style_role='table', x=222.0, y=148.0, font_size=28), TextSlot(id='slot.table.r1c2', prompt='', text='봄', style_role='table', x=373.0, y=148.0, font_size=28), TextSlot(id='slot.table.r1c3', prompt='', text='여름', style_role='table', x=464.0, y=148.0, font_size=28), TextSlot(id='slot.table.r1c4', prompt='', text='가을', style_role='table', x=558.0, y=148.0, font_size=28), TextSlot(id='slot.table.r1c5', prompt='', text='겨울', style_role='table', x=655.0, y=148.0, font_size=28), TextSlot(id='slot.table.r1c6', prompt='', text='합계', style_role='table', x=753.0, y=148.0, font_size=28), TextSlot(id='slot.table.r2c1', prompt='', text='학생 수(명)', style_role='table', x=223.0, y=188.0, font_size=28), TextSlot(id='slot.table.r2c2', prompt='', text='6', style_role='table', x=373.0, y=188.0, font_size=28), TextSlot(id='slot.table.r2c3', prompt='', text='10', style_role='table', x=468.0, y=188.0, font_size=28), TextSlot(id='slot.table.r2c4', prompt='', text='3', style_role='table', x=559.0, y=188.0, font_size=28), TextSlot(id='slot.table.r2c5', prompt='', text='9', style_role='table', x=656.0, y=188.0, font_size=28), TextSlot(id='slot.table.r2c6', prompt='', text='28', style_role='table', x=754.0, y=188.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='( 봄, 여름, 가을, 겨울 )', style_role='choice', x=648.0, y=237.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008907', 'problem_type': 'table_comparison', 'metadata': {'language': 'ko', 'question': '표에서 가장 많은 학생들이 태어난 계절을 고르는 문제', 'instruction': '가장 많은 학생들이 태어난 계절을 선택해 보세요.'}, 'domain': {'objects': [{'id': 'obj.spring_count', 'type': 'count', 'label': '봄', 'value': 6}, {'id': 'obj.summer_count', 'type': 'count', 'label': '여름', 'value': 10}, {'id': 'obj.autumn_count', 'type': 'count', 'label': '가을', 'value': 3}, {'id': 'obj.winter_count', 'type': 'count', 'label': '겨울', 'value': 9}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.spring_count', 'obj.summer_count', 'obj.autumn_count', 'obj.winter_count'], 'target_ref': 'answer.target', 'condition_refs': ['rel.max_count']}, 'plan': {'method': 'compare_counts', 'description': '각 계절의 학생 수를 비교하여 가장 큰 수에 대응하는 계절을 찾는다.'}, 'execute': {'expected_operations': ['compare_values', 'select_maximum']}, 'review': {'check_methods': ['verify_greatest_value']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'season', 'description': '가장 많은 학생들이 태어난 계절'}, 'value': '여름', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008907', 'problem_type': 'table_comparison', 'inputs': {'total_ticks': 4, 'target_label': '가장 많은 학생들이 태어난 계절', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.spring_count', 'value': 6}, {'ref': 'obj.summer_count', 'value': 10}, {'ref': 'obj.autumn_count', 'value': 3}, {'ref': 'obj.winter_count', 'value': 9}], 'target': {'ref': 'answer.target', 'type': 'season'}, 'method': 'compare_counts', 'plan': ['네 계절의 학생 수를 비교한다.', '가장 큰 수가 대응하는 계절을 찾는다.'], 'steps': [{'id': 'step.1', 'expr': 'max(6, 10, 3, 9)', 'value': 10}, {'id': 'step.2', 'expr': '10에 대응하는 계절', 'value': '여름'}], 'checks': [{'id': 'check.1', 'expr': '10 > 6 and 10 > 3 and 10 > 9', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'season', 'description': '가장 많은 학생들이 태어난 계절'}, 'value': '여름', 'unit': ''}}
