from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008734', title='진분수인 재료 고르기', canvas=Canvas(width=940, height=426, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.table.border', 'slot.col1.top', 'slot.col1.mid', 'slot.col1.bottom', 'slot.col2.top', 'slot.col2.mid', 'slot.col2.bottom', 'slot.col3.top', 'slot.col3.mid', 'slot.col3.bottom', 'slot.col4.top', 'slot.col4.mid', 'slot.col4.bottom', 'slot.choice')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='89. 블루베리 즙 2잔을 만드는 데 필요한 재료입니다. 빈 칸에 진분수인 재료를 모두 선택해 보세요.', style_role='question', x=14.0, y=20.0, font_size=28), RectSlot(id='slot.table.border', prompt='', x=230.0, y=90.0, width=530.0, height=205.0), TextSlot(id='slot.col1.top', prompt='', text='블루베리', style_role='body', x=266.0, y=206.0, font_size=28), TextSlot(id='slot.col1.mid', prompt='', text='7\n4', style_role='body', x=270.0, y=258.0, font_size=28), TextSlot(id='slot.col1.bottom', prompt='', text='컵', style_role='body', x=308.0, y=258.0, font_size=28), TextSlot(id='slot.col2.top', prompt='', text='물', style_role='body', x=397.0, y=206.0, font_size=28), TextSlot(id='slot.col2.mid', prompt='', text='6\n6', style_role='body', x=401.0, y=258.0, font_size=28), TextSlot(id='slot.col2.bottom', prompt='', text='컵', style_role='body', x=439.0, y=258.0, font_size=28), TextSlot(id='slot.col3.top', prompt='', text='우유', style_role='body', x=520.0, y=206.0, font_size=28), TextSlot(id='slot.col3.mid', prompt='', text='3\n8', style_role='body', x=534.0, y=258.0, font_size=28), TextSlot(id='slot.col3.bottom', prompt='', text='컵', style_role='body', x=574.0, y=258.0, font_size=28), TextSlot(id='slot.col4.top', prompt='', text='꿀', style_role='body', x=653.0, y=206.0, font_size=28), TextSlot(id='slot.col4.mid', prompt='', text='5\n14', style_role='body', x=661.0, y=258.0, font_size=28), TextSlot(id='slot.col4.bottom', prompt='', text='컵', style_role='body', x=699.0, y=258.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='( 블루베리 , 물 , 우유 , 꿀 )', style_role='body', x=616.0, y=332.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008734', 'problem_type': 'fraction_classification', 'metadata': {'language': 'ko', 'question': '블루베리 즙 2잔을 만드는 데 필요한 재료 중 진분수인 재료를 고르는 문제', 'instruction': '빈 칸에 진분수인 재료를 모두 선택해 보세요.'}, 'domain': {'objects': [{'id': 'obj.blueberry', 'type': 'ingredient', 'name': '블루베리'}, {'id': 'obj.water', 'type': 'ingredient', 'name': '물'}, {'id': 'obj.milk', 'type': 'ingredient', 'name': '우유'}, {'id': 'obj.honey', 'type': 'ingredient', 'name': '꿀'}, {'id': 'obj.frac.blueberry', 'type': 'fraction', 'value': '7/4', 'unit': '컵'}, {'id': 'obj.frac.water', 'type': 'fraction', 'value': '6/6', 'unit': '컵'}, {'id': 'obj.frac.milk', 'type': 'fraction', 'value': '3/8', 'unit': '컵'}, {'id': 'obj.frac.honey', 'type': 'fraction', 'value': '5/14', 'unit': '컵'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.frac.blueberry', 'obj.frac.water', 'obj.frac.milk', 'obj.frac.honey'], 'target_ref': 'answer.target', 'condition_refs': ['rel.milk_is_proper_fraction', 'rel.honey_is_proper_fraction']}, 'plan': {'method': 'fraction_classification', 'description': '각 분수가 진분수인지 확인한 뒤 해당하는 재료를 고른다.'}, 'execute': {'expected_operations': ['compare_numerator_and_denominator', 'select_proper_fractions']}, 'review': {'check_methods': ['numerator_smaller_than_denominator', 'selection_matches_example']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_ingredients', 'description': '진분수인 재료'}, 'value': 2, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008734', 'problem_type': 'fraction_classification', 'inputs': {'total_ticks': 4, 'target_label': '진분수인 재료', 'target_ticks': 2, 'target_count': 2, 'unit': '컵'}, 'given': [{'ref': 'obj.frac.blueberry', 'value': '7/4'}, {'ref': 'obj.frac.water', 'value': '6/6'}, {'ref': 'obj.frac.milk', 'value': '3/8'}, {'ref': 'obj.frac.honey', 'value': '5/14'}], 'target': {'ref': 'answer.target', 'type': 'selected_ingredients'}, 'method': 'fraction_classification', 'plan': ['각 재료의 분수에서 분자와 분모를 비교한다.', '분자가 분모보다 작은 경우만 진분수로 고른다.'], 'steps': [{'id': 'step.1', 'expr': '7 < 4', 'value': False}, {'id': 'step.2', 'expr': '6 < 6', 'value': False}, {'id': 'step.3', 'expr': '3 < 8', 'value': True}, {'id': 'step.4', 'expr': '5 < 14', 'value': True}], 'checks': [{'id': 'check.1', 'expr': '진분수는 분자가 분모보다 작은가', 'expected': True, 'actual': True, 'pass': True}, {'id': 'check.2', 'expr': '선택된 재료가 우유와 꿀인가', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_ingredients', 'description': '진분수인 재료'}, 'value': 2, 'unit': ''}}
