from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009039', title='도형을 보고 알맞은 말을 선택하세요.', canvas=Canvas(width=960, height=490, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q.title', 'slot.shape', 'slot.choice.left', 'slot.choice.mid', 'slot.choice.right')),), slots=(TextSlot(id='slot.q.title', prompt='', text='□ 77. 도형을 보고 알맞은 말을 선택하세요.', style_role='question', x=12.0, y=22.0, font_size=28), RectSlot(id='slot.shape', prompt='', x=406.0, y=50.0, width=146.0, height=145.0, stroke='#333333', fill='none'), RectSlot(id='slot.choice.left', prompt='', x=36.0, y=200.0, width=282.0, height=174.0, stroke='#A77BC8', fill='none'), RectSlot(id='slot.choice.mid', prompt='', x=333.0, y=200.0, width=282.0, height=174.0, stroke='#A77BC8', fill='none'), RectSlot(id='slot.choice.right', prompt='', x=630.0, y=200.0, width=282.0, height=174.0, stroke='#A77BC8', fill='none'), TextSlot(id='slot.choice.left.text', prompt='', text='도형은\n직사각형이\n( 맞아요 , 아니에요 ).', style_role='choice', x=177.0, y=221.0, font_size=28), TextSlot(id='slot.choice.mid.text', prompt='', text='도형은\n정사각형이\n( 맞아요 , 아니에요 ).', style_role='choice', x=474.0, y=221.0, font_size=28), TextSlot(id='slot.choice.right.text', prompt='', text='정사각형은\n직사각형이라고 할 수\n( 있어요 , 없어요 ).', style_role='choice', x=771.0, y=221.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009039', 'problem_type': '도형_분류_포함관계', 'metadata': {'language': 'ko', 'question': '도형을 보고 알맞은 말을 선택하세요.', 'instruction': '도형의 성질과 포함 관계를 판단한다.'}, 'domain': {'objects': [{'id': 'obj.shape', 'type': 'quadrilateral', 'name': '도형'}, {'id': 'obj.rectangle', 'type': 'shape_class', 'name': '직사각형'}, {'id': 'obj.square', 'type': 'shape_class', 'name': '정사각형'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.shape', 'obj.rectangle', 'obj.square'], 'target_ref': 'answer.target', 'condition_refs': ['rel.square_is_rectangle']}, 'plan': {'method': 'shape_classification', 'description': '도형의 분류 관계를 보고 문장의 맞음 여부를 판단한다.'}, 'execute': {'expected_operations': ['identify_shape_properties', 'compare_class_membership', 'read_answer_choice']}, 'review': {'check_methods': ['relation_consistency_check', 'statement_match_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'multiple_choice_judgment', 'description': '도형과 정사각형, 직사각형의 관계에 대한 판단'}, 'value': 3, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009039', 'problem_type': '도형_분류_포함관계', 'inputs': {'total_ticks': 0, 'target_label': '도형의 분류 판단', 'target_ticks': 0, 'target_count': 3, 'unit': ''}, 'given': [{'ref': 'obj.shape', 'value': {'type': 'quadrilateral'}}, {'ref': 'obj.rectangle', 'value': {'name': '직사각형'}}, {'ref': 'obj.square', 'value': {'name': '정사각형'}}], 'target': {'ref': 'answer.target', 'type': 'multiple_choice_judgment'}, 'method': 'shape_classification', 'plan': ['도형의 성질을 보고 직사각형과 정사각형의 관계를 판단한다.', '화면에 인쇄된 정답과 해설 문장을 확인한다.'], 'steps': [{'id': 'step.1', 'expr': '도형 분류 판단 3개', 'value': 3}, {'id': 'step.2', 'expr': '인쇄된 정답 표기 확인', 'value': '맞아요, 맞아요, 있어요'}], 'checks': [{'id': 'check.1', 'expr': '정답 표기와 해설 문장이 일치하는지 확인', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'multiple_choice_judgment', 'description': '도형과 정사각형, 직사각형의 관계에 대한 판단'}, 'value': 3, 'unit': ''}}
