from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, CircleSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009018', title='직선 ㄷ ㄹ을 선택하세요.', canvas=Canvas(width=656, height=265, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.num', 'slot.q')), Region(id='region.choice_box', role='diagram', flow='absolute', slot_ids=('slot.box', 'slot.opt1.line', 'slot.opt1.p1', 'slot.opt1.p2', 'slot.opt1.lb1', 'slot.opt1.lb2', 'slot.opt2.line', 'slot.opt2.p1', 'slot.opt2.p2', 'slot.opt2.lb1', 'slot.opt2.lb2')), Region(id='region.answer_explain', role='answer', flow='absolute', slot_ids=('slot.answer.line', 'slot.answer.p1', 'slot.answer.p2'))), slots=(TextSlot(id='slot.num', prompt='', text='56.', style_role='question', x=13.0, y=26.0, font_size=28), TextSlot(id='slot.q', prompt='', text='직선 ㄷ ㄹ을 선택하세요.', style_role='question', x=63.0, y=26.0, font_size=28), RectSlot(id='slot.box', prompt='', x=264.0, y=41.0, width=341.0, height=141.0, fill='none', stroke='#8F86E8', stroke_width=1.5), LineSlot(id='slot.opt1.line', prompt='', x1=333.0, y1=90.0, x2=481.0, y2=90.0, stroke='#333333', stroke_width=1.0), CircleSlot(id='slot.opt1.p1', prompt='', cx=334.0, cy=90.0, r=2.6, fill='#333333'), CircleSlot(id='slot.opt1.p2', prompt='', cx=479.0, cy=90.0, r=2.6, fill='#333333'), TextSlot(id='slot.opt1.lb1', prompt='', text='ㄷ', style_role='label', x=329.0, y=79.0, font_size=28), TextSlot(id='slot.opt1.lb2', prompt='', text='ㄹ', style_role='label', x=474.0, y=79.0, font_size=28), LineSlot(id='slot.opt2.line', prompt='', x1=330.0, y1=141.0, x2=479.0, y2=141.0, stroke='#333333', stroke_width=1.0), CircleSlot(id='slot.opt2.p1', prompt='', cx=331.0, cy=141.0, r=2.6, fill='#333333'), CircleSlot(id='slot.opt2.p2', prompt='', cx=478.0, cy=141.0, r=2.6, fill='#333333'), TextSlot(id='slot.opt2.lb1', prompt='', text='ㄷ', style_role='label', x=326.0, y=130.0, font_size=28), TextSlot(id='slot.opt2.lb2', prompt='', text='ㄹ', style_role='label', x=472.0, y=130.0, font_size=28), LineSlot(id='slot.answer.line', prompt='', x1=74.0, y1=221.0, x2=228.0, y2=221.0, stroke='#333333', stroke_width=1.0), CircleSlot(id='slot.answer.p1', prompt='', cx=75.0, cy=221.0, r=2.6, fill='#333333'), CircleSlot(id='slot.answer.p2', prompt='', cx=228.0, cy=221.0, r=2.6, fill='#333333')), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009018', 'problem_type': 'geometry_line_selection', 'metadata': {'language': 'ko', 'question': '직선 ㄷ ㄹ을 선택하세요.', 'instruction': '보기에서 점 ㄷ과 점 ㄹ을 모두 지나는 직선을 고른다.'}, 'domain': {'objects': [{'id': 'obj.point.d', 'type': 'point', 'name': 'ㄷ'}, {'id': 'obj.point.r', 'type': 'point', 'name': 'ㄹ'}, {'id': 'obj.line.dr', 'type': 'line', 'name': '직선 ㄷㄹ', 'passes_through': ['obj.point.d', 'obj.point.r']}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.point.d', 'obj.point.r'], 'target_ref': 'answer.target', 'condition_refs': ['rel.line_through_points']}, 'plan': {'method': 'identify_matching_line', 'description': '두 점 ㄷ, ㄹ을 모두 지나는 직선을 찾는다.'}, 'execute': {'expected_operations': ['compare_visual_options', 'find_line_through_two_points']}, 'review': {'check_methods': ['both_points_on_line']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_line', 'description': '점 ㄷ과 점 ㄹ을 모두 지나는 직선'}, 'value': 1, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009018', 'problem_type': 'geometry_line_selection', 'inputs': {'total_ticks': 0, 'target_label': '직선 ㄷ ㄹ', 'target_ticks': 0, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.point.d', 'value': {'name': 'ㄷ'}}, {'ref': 'obj.point.r', 'value': {'name': 'ㄹ'}}], 'target': {'ref': 'answer.target', 'type': 'selected_line'}, 'method': 'identify_matching_line', 'plan': ['점 ㄷ과 점 ㄹ을 모두 지나는 직선을 찾는다.', '보기와 해설의 선 모양을 비교한다.'], 'steps': [{'id': 'step.1', 'expr': '두 점 ㄷ, ㄹ을 지나는 직선 찾기', 'value': '직선 ㄷㄹ'}], 'checks': [{'id': 'check.1', 'expr': '선이 점 ㄷ과 점 ㄹ을 모두 지나는가', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_line', 'description': '점 ㄷ과 점 ㄹ을 모두 지나는 직선'}, 'value': 1, 'unit': ''}}
