from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, CircleSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008935', title='하루 동안 팔린 우산의 수', canvas=Canvas(width=960, height=540, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q_num', 'slot.q1', 'slot.q2', 'slot.q_title', 'slot.table.head1', 'slot.table.head2', 'slot.table.row1.label', 'slot.table.row2.label', 'slot.table.row3.label', 'slot.legend.big_icon', 'slot.legend.big_text', 'slot.legend.small_icon', 'slot.legend.small_text', 'slot.choice.1', 'slot.choice.2', 'slot.choice.3', 'slot.choice.4')),), slots=(TextSlot(id='slot.q_num', prompt='', text='3.', style_role='question', x=20.0, y=34.0, font_size=28), TextSlot(id='slot.q1', prompt='', text='우산 가게에서 하루 동안 팔린 우산의 수를 그림그래프로 나타내었습니다.', style_role='question', x=54.0, y=34.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='많이 팔린 우산의 색깔부터 순서대로 쓴 것을 고르세요.', style_role='question', x=54.0, y=68.0, font_size=28), TextSlot(id='slot.q_title', prompt='', text='하루 동안 팔린 우산의 수', style_role='title', x=360.0, y=106.0, font_size=28), RectSlot(id='slot.table.outer', prompt='', x=220.0, y=118.0, width=510.0, height=192.0), LineSlot(id='slot.table.v1', prompt='', x1=310.0, y1=118.0, x2=310.0, y2=310.0), LineSlot(id='slot.table.h1', prompt='', x1=220.0, y1=154.0, x2=730.0, y2=154.0), LineSlot(id='slot.table.h2', prompt='', x1=220.0, y1=202.0, x2=730.0, y2=202.0), LineSlot(id='slot.table.h3', prompt='', x1=220.0, y1=250.0, x2=730.0, y2=250.0), TextSlot(id='slot.table.head1', prompt='', text='색깔', style_role='label', x=250.0, y=142.0, font_size=28), TextSlot(id='slot.table.head2', prompt='', text='우산의 수', style_role='label', x=460.0, y=142.0, font_size=28), TextSlot(id='slot.table.row1.label', prompt='', text='검은색', style_role='label', x=236.0, y=190.0, font_size=28), TextSlot(id='slot.table.row2.label', prompt='', text='회색', style_role='label', x=236.0, y=238.0, font_size=28), TextSlot(id='slot.table.row3.label', prompt='', text='파란색', style_role='label', x=236.0, y=286.0, font_size=28), RectSlot(id='slot.legend.big_icon', prompt='', x=510.0, y=320.0, width=30.0, height=24.0), TextSlot(id='slot.legend.big_text', prompt='', text='10개', style_role='label', x=548.0, y=340.0, font_size=28), RectSlot(id='slot.legend.small_icon', prompt='', x=648.0, y=320.0, width=18.0, height=14.0), TextSlot(id='slot.legend.small_text', prompt='', text='1개', style_role='label', x=676.0, y=340.0, font_size=28), TextSlot(id='slot.choice.1', prompt='', text='① 회색, 파란색, 검은색', style_role='choice', x=38.0, y=390.0, font_size=28), TextSlot(id='slot.choice.2', prompt='', text='② 회색, 검은색, 파란색', style_role='choice', x=510.0, y=390.0, font_size=28), TextSlot(id='slot.choice.3', prompt='', text='③ 검은색, 파란색, 회색', style_role='choice', x=38.0, y=432.0, font_size=28), TextSlot(id='slot.choice.4', prompt='', text='④ 파란색, 검은색, 회색', style_role='choice', x=510.0, y=432.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008935', 'problem_type': 'picture_graph_ordering', 'metadata': {'language': 'ko', 'question': '우산 가게에서 하루 동안 팔린 우산의 수를 그림그래프로 나타낸 뒤, 많이 팔린 우산의 색깔부터 순서대로 고르는 문제', 'instruction': '많이 팔린 우산의 색깔부터 순서대로 쓴 것을 고르세요.'}, 'domain': {'objects': [{'id': 'obj.color.black', 'type': 'color', 'name': '검은색'}, {'id': 'obj.color.gray', 'type': 'color', 'name': '회색'}, {'id': 'obj.color.blue', 'type': 'color', 'name': '파란색'}, {'id': 'obj.legend.big', 'type': 'pictograph_unit', 'name': '큰 우산', 'quantity_per_icon': 10}, {'id': 'obj.legend.small', 'type': 'pictograph_unit', 'name': '작은 우산', 'quantity_per_icon': 1}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.color.black', 'obj.color.gray', 'obj.color.blue', 'obj.legend.big', 'obj.legend.small'], 'target_ref': 'answer.target', 'condition_refs': ['rel.rank_desc']}, 'plan': {'method': 'compare_counts', 'description': '각 색깔의 우산 수를 비교하여 많이 팔린 순서로 나눈다.'}, 'execute': {'expected_operations': ['read_pictograph', 'compare_sales_counts', 'sort_descending']}, 'review': {'check_methods': ['descending_order_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'color_order', 'description': '많이 팔린 우산의 색깔부터 순서'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008935', 'problem_type': 'picture_graph_ordering', 'inputs': {'total_ticks': 0, 'target_label': '색깔 순서', 'target_ticks': 0, 'target_count': 3, 'unit': ''}, 'given': [{'ref': 'obj.color.black', 'value': {'name': '검은색'}}, {'ref': 'obj.color.gray', 'value': {'name': '회색'}}, {'ref': 'obj.color.blue', 'value': {'name': '파란색'}}], 'target': {'ref': 'answer.target', 'type': 'color_order'}, 'method': 'compare_counts', 'plan': ['각 색깔의 우산 수를 비교한다.', '많이 팔린 색부터 적게 팔린 색까지 순서대로 나눈다.'], 'steps': [{'id': 'step.1', 'expr': '해설에 제시된 수량 비교: 50, 23, 16', 'value': [50, 23, 16]}, {'id': 'step.2', 'expr': '50 > 23 > 16에 해당하는 색의 순서 읽기', 'value': ['파란색', '검은색', '회색']}], 'checks': [{'id': 'check.1', 'expr': '내림차순인지 확인', 'expected': ['파란색', '검은색', '회색'], 'actual': ['파란색', '검은색', '회색'], 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'color_order', 'description': '많이 팔린 우산의 색깔부터 순서'}, 'value': 0, 'unit': ''}}
