from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008831', title='L 단위에 알맞은 물건 고르기', canvas=Canvas(width=960, height=570, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.box', 'slot.box.title', 'slot.pic1', 'slot.pic1.label', 'slot.pic2', 'slot.pic2.label', 'slot.pic3', 'slot.pic3.label', 'slot.sentence')),), slots=(TextSlot(id='slot.q1', prompt='', text='67. <보기>를 보고 알맞은 물건을 선택하여 문장을 완성해 보세요.', style_role='question', x=12.0, y=34.0, font_size=28), RectSlot(id='slot.box', prompt='', x=102.0, y=51.0, width=748.0, height=226.0), TextSlot(id='slot.box.title', prompt='', text='<보기>', style_role='label', x=130.0, y=89.0, font_size=28), TextSlot(id='slot.pic1', prompt='', text='주사기', style_role='label', x=242.0, y=241.0, font_size=28), TextSlot(id='slot.pic1.label', prompt='', text='주사기', style_role='label', x=242.0, y=239.0, font_size=28), TextSlot(id='slot.pic2', prompt='', text='물뿌리개', style_role='label', x=467.0, y=241.0, font_size=28), TextSlot(id='slot.pic2.label', prompt='', text='물뿌리개', style_role='label', x=467.0, y=239.0, font_size=28), TextSlot(id='slot.pic3', prompt='', text='항아리', style_role='label', x=698.0, y=241.0, font_size=28), TextSlot(id='slot.pic3.label', prompt='', text='항아리', style_role='label', x=698.0, y=239.0, font_size=28), TextSlot(id='slot.sentence', prompt='', text='( 주사기 , 물뿌리개 , 항아리 )의 들이는 약 40 L입니다.', style_role='question', x=154.0, y=347.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008831', 'problem_type': 'selection_capacity_unit', 'metadata': {'language': 'ko', 'question': '<보기>를 보고 알맞은 물건을 선택하여 문장을 완성해 보세요.', 'instruction': 'L 단위에 알맞은 물건을 고르는 문제'}, 'domain': {'objects': [{'id': 'obj.syringe', 'type': 'container_or_tool', 'name': '주사기'}, {'id': 'obj.watering_can', 'type': 'container_or_tool', 'name': '물뿌리개'}, {'id': 'obj.jar', 'type': 'container_or_tool', 'name': '항아리'}, {'id': 'obj.capacity', 'type': 'capacity', 'value': 40, 'unit': 'L'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.syringe', 'obj.watering_can', 'obj.jar', 'obj.capacity'], 'target_ref': 'answer.target', 'condition_refs': ['rel.capacity_fits']}, 'plan': {'method': 'unit_suitability_choice', 'description': 'L 단위를 쓰기에 알맞은 물건을 보기에서 고른다.'}, 'execute': {'expected_operations': ['compare_item_scale', 'select_best_match']}, 'review': {'check_methods': ['unit_appropriateness_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_object', 'description': '약 40 L의 들이에 알맞은 물건'}, 'value': '항아리', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008831', 'problem_type': 'selection_capacity_unit', 'inputs': {'total_ticks': 0, 'target_label': '약 40 L의 들이에 알맞은 물건', 'target_ticks': 0, 'target_count': 1, 'unit': 'L'}, 'given': [{'ref': 'obj.syringe', 'value': '주사기'}, {'ref': 'obj.watering_can', 'value': '물뿌리개'}, {'ref': 'obj.jar', 'value': '항아리'}, {'ref': 'obj.capacity', 'value': {'value': 40, 'unit': 'L'}}], 'target': {'ref': 'answer.target', 'type': 'selected_object'}, 'method': 'unit_suitability_choice', 'plan': ['보기의 물건들 중에서 L 단위를 쓰기에 알맞은 큰 들이의 물건을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '보기의 물건을 확인한다', 'value': ['주사기', '물뿌리개', '항아리']}, {'id': 'step.2', 'expr': '40 L에 알맞은 물건을 선택한다', 'value': '항아리'}], 'checks': [{'id': 'check.1', 'expr': '선택한 물건이 L 단위에 알맞은 큰 들이의 물건인지 확인', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_object', 'description': '약 40 L의 들이에 알맞은 물건'}, 'value': '항아리', 'unit': ''}}
