from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    ProblemTemplate,
    Region,
    TextSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008654",
        title="원의 규칙 비교",
        canvas=Canvas(width=960, height=480, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.label.ga",
                    "slot.label.na",
                    "slot.diagram.ga.grid.v1",
                    "slot.diagram.ga.grid.v2",
                    "slot.diagram.ga.grid.v3",
                    "slot.diagram.ga.grid.v4",
                    "slot.diagram.ga.grid.v5",
                    "slot.diagram.ga.grid.v6",
                    "slot.diagram.ga.grid.v7",
                    "slot.diagram.ga.grid.v8",
                    "slot.diagram.ga.grid.v9",
                    "slot.diagram.ga.grid.h1",
                    "slot.diagram.ga.grid.h2",
                    "slot.diagram.ga.grid.h3",
                    "slot.diagram.ga.grid.h4",
                    "slot.diagram.ga.grid.h5",
                    "slot.diagram.ga.grid.h6",
                    "slot.diagram.ga.grid.h7",
                    "slot.diagram.ga.grid.h8",
                    "slot.diagram.ga.circle1",
                    "slot.diagram.ga.circle2",
                    "slot.diagram.ga.circle3",
                    "slot.diagram.na.grid.v1",
                    "slot.diagram.na.grid.v2",
                    "slot.diagram.na.grid.v3",
                    "slot.diagram.na.grid.v4",
                    "slot.diagram.na.grid.v5",
                    "slot.diagram.na.grid.v6",
                    "slot.diagram.na.grid.v7",
                    "slot.diagram.na.grid.v8",
                    "slot.diagram.na.grid.v9",
                    "slot.diagram.na.grid.h1",
                    "slot.diagram.na.grid.h2",
                    "slot.diagram.na.grid.h3",
                    "slot.diagram.na.grid.h4",
                    "slot.diagram.na.grid.h5",
                    "slot.diagram.na.grid.h6",
                    "slot.diagram.na.grid.h7",
                    "slot.diagram.na.grid.h8",
                    "slot.diagram.na.circle1",
                    "slot.diagram.na.circle2",
                    "slot.diagram.na.circle3",
                    "slot.desc1",
                    "slot.desc2",
                    "slot.bottom",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="29. 가와 나는 규칙에 따라 원을 그린 것입니다. 알맞은 것을 선택해 두 모양을 그린 규칙의 같은 점과 다른 점을 설명해 보세요.",
                style_role="question",
                x=10.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.ga",
                prompt="",
                text="가",
                style_role="label",
                x=232.0,
                y=82.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.na",
                prompt="",
                text="나",
                style_role="label",
                x=516.0,
                y=82.0,
                font_size=28,
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v1",
                prompt="",
                x1=252.0,
                y1=82.0,
                x2=252.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v2",
                prompt="",
                x1=273.0,
                y1=82.0,
                x2=273.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v3",
                prompt="",
                x1=294.0,
                y1=82.0,
                x2=294.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v4",
                prompt="",
                x1=315.0,
                y1=82.0,
                x2=315.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v5",
                prompt="",
                x1=336.0,
                y1=82.0,
                x2=336.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v6",
                prompt="",
                x1=357.0,
                y1=82.0,
                x2=357.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v7",
                prompt="",
                x1=378.0,
                y1=82.0,
                x2=378.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v8",
                prompt="",
                x1=399.0,
                y1=82.0,
                x2=399.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.v9",
                prompt="",
                x1=420.0,
                y1=82.0,
                x2=420.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h1",
                prompt="",
                x1=252.0,
                y1=82.0,
                x2=421.0,
                y2=82.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h2",
                prompt="",
                x1=252.0,
                y1=103.0,
                x2=421.0,
                y2=103.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h3",
                prompt="",
                x1=252.0,
                y1=124.0,
                x2=421.0,
                y2=124.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h4",
                prompt="",
                x1=252.0,
                y1=145.0,
                x2=421.0,
                y2=145.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h5",
                prompt="",
                x1=252.0,
                y1=166.0,
                x2=421.0,
                y2=166.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h6",
                prompt="",
                x1=252.0,
                y1=187.0,
                x2=421.0,
                y2=187.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h7",
                prompt="",
                x1=252.0,
                y1=208.0,
                x2=421.0,
                y2=208.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.ga.grid.h8",
                prompt="",
                x1=252.0,
                y1=229.0,
                x2=421.0,
                y2=229.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.diagram.ga.circle1",
                prompt="",
                cx = 115, cy = 150, r = 75, fill="none",
            ),
            CircleSlot(
                id="slot.diagram.ga.circle2",
                prompt="",
                cx = 420, cy = 175, r = 55, fill="none",
            ),
            CircleSlot(
                id="slot.diagram.ga.circle3",
                prompt="",
                cx = 295, cy = 170, r = 30, fill="none",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v1",
                prompt="",
                x1=536.0,
                y1=82.0,
                x2=536.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v2",
                prompt="",
                x1=557.0,
                y1=82.0,
                x2=557.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v3",
                prompt="",
                x1=578.0,
                y1=82.0,
                x2=578.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v4",
                prompt="",
                x1=599.0,
                y1=82.0,
                x2=599.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v5",
                prompt="",
                x1=620.0,
                y1=82.0,
                x2=620.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v6",
                prompt="",
                x1=641.0,
                y1=82.0,
                x2=641.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v7",
                prompt="",
                x1=662.0,
                y1=82.0,
                x2=662.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v8",
                prompt="",
                x1=683.0,
                y1=82.0,
                x2=683.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.v9",
                prompt="",
                x1=704.0,
                y1=82.0,
                x2=704.0,
                y2=261.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h1",
                prompt="",
                x1=536.0,
                y1=82.0,
                x2=705.0,
                y2=82.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h2",
                prompt="",
                x1=536.0,
                y1=103.0,
                x2=705.0,
                y2=103.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h3",
                prompt="",
                x1=536.0,
                y1=124.0,
                x2=705.0,
                y2=124.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h4",
                prompt="",
                x1=536.0,
                y1=145.0,
                x2=705.0,
                y2=145.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h5",
                prompt="",
                x1=536.0,
                y1=166.0,
                x2=705.0,
                y2=166.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h6",
                prompt="",
                x1=536.0,
                y1=187.0,
                x2=705.0,
                y2=187.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h7",
                prompt="",
                x1=536.0,
                y1=208.0,
                x2=705.0,
                y2=208.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.diagram.na.grid.h8",
                prompt="",
                x1=536.0,
                y1=229.0,
                x2=705.0,
                y2=229.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.diagram.na.circle1",
                prompt="",
                cx=620.0,
                cy=173.0,
                r=88.0,
                fill="none",
            ),
            CircleSlot(
                id="slot.diagram.na.circle2",
                prompt="",
                cx=620.0,
                cy=173.0,
                r=56.0,
                fill="none",
            ),
            CircleSlot(
                id="slot.diagram.na.circle3",
                prompt="",
                cx=620.0,
                cy=173.0,
                r=29.0,
                fill="none",
            ),
            TextSlot(
                id="slot.desc1",
                prompt="",
                text="(2) 다른 점: ( 가, 나)는 원의 중심을 옮겨 가며 그렸고,( 가, 나)는 원의 중심이 모두 같게 그렸습니다.",
                style_role="question",
                x=10.0,
                y=310.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.desc2",
                prompt="",
                text="(2) 다른 점: 가는 원의 중심을 옮겨 가며 그렸고, 나는 원의 중심이 모두 같게 그렸습니다.",
                style_role="question",
                x=10.0,
                y=386.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.bottom",
                prompt="",
                text="(2) 가, 나",
                style_role="question",
                x=2.0,
                y=462.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008654",
    "problem_type": "compare_patterns",
    "metadata": {
        "language": "ko",
        "question": "원을 그린 두 규칙의 같은 점과 다른 점을 설명하는 문제",
        "instruction": "알맞은 것을 선택해 두 모양을 그린 규칙의 같은 점과 다른 점을 설명해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.figure.ga", "type": "figure", "label": "가"},
            {"id": "obj.figure.na", "type": "figure", "label": "나"},
            {"id": "obj.circle_set.ga", "type": "circle_group", "count": 3},
            {"id": "obj.circle_set.na", "type": "circle_group", "count": 3},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.figure.ga", "obj.figure.na"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare.same", "rel.compare.different"],
            },
            "plan": {
                "method": "compare_two_figures",
                "description": "두 그림에서 원의 중심 배치를 비교해 같은 점과 다른 점을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "observe_figure_ga",
                    "observe_figure_na",
                    "compare_center_positions",
                ]
            },
            "review": {
                "check_methods": ["compare_background", "compare_circle_centers"]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "explain_same_and_different",
            "description": "두 모양을 그린 규칙의 같은 점과 다른 점",
        },
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008654",
    "problem_type": "compare_patterns",
    "inputs": {
        "total_ticks": 0,
        "target_label": "두 모양을 그린 규칙의 같은 점과 다른 점",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "",
    },
    "given": [
        {"ref": "obj.figure.ga", "value": "가"},
        {"ref": "obj.figure.na", "value": "나"},
    ],
    "target": {"ref": "answer.target", "type": "explain_same_and_different"},
    "method": "compare_two_figures",
    "plan": [
        "두 그림의 원 배치와 중심 위치를 비교한다.",
        "같은 점은 공통 배경과 같은 종류의 원이라는 점으로 본다.",
        "다른 점은 원의 중심이 옮겨졌는지, 모두 같은지로 본다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "가 그림의 원 중심 배치 확인",
            "value": "중심이 서로 다른 위치로 옮겨진 배치",
        },
        {
            "id": "step.2",
            "expr": "나 그림의 원 중심 배치 확인",
            "value": "중심이 모두 같은 배치",
        },
        {
            "id": "step.3",
            "expr": "두 그림의 공통점 비교",
            "value": "같은 격자 위에 원 3개를 겹쳐 그림",
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "가와 나의 배치가 서로 다른가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "나의 원들이 같은 중심을 가지는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "explain_same_and_different",
            "description": "두 모양을 그린 규칙의 같은 점과 다른 점",
        },
        "value": 0,
        "unit": "",
    },
}
