from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008739",
        title="집에서 가장 가까운 곳",
        canvas=Canvas(width=960, height=560, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header",
                role="stem",
                flow="absolute",
                slot_ids=("slot.question", "slot.question.copy1"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.house.box",
                    "slot.bookstore.box",
                    "slot.bank.box",
                    "slot.school.box",
                    "slot.house.label",
                    "slot.bookstore.label",
                    "slot.bank.label",
                    "slot.school.label",
                    "slot.line.bookstore",
                    "slot.line.bank",
                    "slot.line.school",
                    "slot.dist.bookstore",
                    "slot.dist.bank",
                    "slot.dist.school",
                    "slot.option",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
            Region(id="region.explanation", role="explanation", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.question",
                prompt="",
                text="집에서 각 장소까지의 거리를 나타낸 것입니다. 집에서 가장 가까운 곳은 어디인지 선택하세요.",
                style_role="question",
                x=76,
                y=86,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.house.box",
                prompt="",
                x=403,
                y=251,
                width=58,
                height=34,
                fill="#FFF6D5",
                stroke="#C9B36A",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.bookstore.box",
                prompt="",
                x=253,
                y=377,
                width=50,
                height=34,
                fill="#EFEAFB",
                stroke="#B7AED9",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.bank.box",
                prompt="",
                x=605,
                y=361,
                width=50,
                height=34,
                fill="#FFF3A6",
                stroke="#D8C85A",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.school.box",
                prompt="",
                x=615,
                y=255,
                width=50,
                height=34,
                fill="#F2F2F2",
                stroke="#B8B8B8",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.line.bookstore",
                prompt="",
                x1=432,
                y1=285,
                x2=278,
                y2=394,
                stroke="#222222",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.bank",
                prompt="",
                x1=432,
                y1=285,
                x2=630,
                y2=378,
                stroke="#222222",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.line.school",
                prompt="",
                x1=432,
                y1=285,
                x2=640,
                y2=272,
                stroke="#222222",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.house.label",
                prompt="",
                text="집",
                style_role="diagram_label",
                x=391,
                y=247,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.bookstore.label",
                prompt="",
                text="서점",
                style_role="diagram_label",
                x=257,
                y=431,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.bank.label",
                prompt="",
                text="은행",
                style_role="diagram_label",
                x=621,
                y=421,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.school.label",
                prompt="",
                text="학교",
                style_role="diagram_label",
                x=631,
                y=303,
                font_size=22,
                fill="#111111",
            ),
            TextSlot(
                id="slot.dist.bookstore",
                prompt="",
                text="7 1/10 km",
                style_role="diagram_label",
                x=325,
                y=331,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.dist.bank",
                prompt="",
                text="69/10 km",
                style_role="diagram_label",
                x=501,
                y=357,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.dist.school",
                prompt="",
                text="7 3/10 km",
                style_role="diagram_label",
                x=503,
                y=233,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option",
                prompt="",
                text="( 서점 , 은행 , 학교 )",
                style_role="choice",
                x=687,
                y=445,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.question.copy1",
                prompt="",
                text="집에서 각 장소까지의 거리를 나타낸 것입니다. 집에서 가장 가까운 곳은 어디인지 선택하세요.",
                x=81,
                y=171,
                font_size=28,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008739",
    "problem_type": "comparison_minimum",
    "metadata": {
        "language": "ko",
        "question": "집에서 각 장소까지의 거리를 나타낸 것입니다. 집에서 가장 가까운 곳은 어디인지 선택하세요.",
        "instruction": "가장 가까운 곳을 고르시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.house", "type": "place", "name": "집"},
            {"id": "obj.bookstore", "type": "place", "name": "서점"},
            {"id": "obj.bank", "type": "place", "name": "은행"},
            {"id": "obj.school", "type": "place", "name": "학교"},
            {"id": "obj.dist_bookstore", "type": "distance", "value_text": "7 1/10 km"},
            {"id": "obj.dist_bank", "type": "distance", "value_text": "69/10 km"},
            {"id": "obj.dist_school", "type": "distance", "value_text": "7 3/10 km"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.dist_bookstore", "obj.dist_bank", "obj.dist_school"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_distances"],
            },
            "plan": {
                "method": "compare_distances",
                "description": "세 장소까지의 거리를 비교하여 가장 작은 값을 찾는다.",
            },
            "execute": {
                "expected_operations": ["read_distances", "compare_values", "select_minimum"]
            },
            "review": {"check_methods": ["minimum_check", "label_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "nearest_place", "description": "집에서 가장 가까운 곳"},
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008739",
    "problem_type": "comparison_minimum",
    "inputs": {
        "total_ticks": 3,
        "target_label": "가장 가까운 곳",
        "target_ticks": 1,
        "target_count": 3,
        "unit": "km",
    },
    "given": [
        {"ref": "obj.dist_bookstore", "value": "7 1/10 km"},
        {"ref": "obj.dist_bank", "value": "69/10 km"},
        {"ref": "obj.dist_school", "value": "7 3/10 km"},
    ],
    "target": {"ref": "answer.target", "type": "nearest_place"},
    "method": "compare_distances",
    "plan": [
        "세 장소의 거리를 읽는다.",
        "표기된 값을 비교하여 가장 작은 거리를 찾는다.",
        "가장 작은 거리의 장소를 답으로 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "서점 거리 읽기", "value": "7 1/10 km"},
        {"id": "step.2", "expr": "은행 거리 읽기", "value": "69/10 km"},
        {"id": "step.3", "expr": "학교 거리 읽기", "value": "7 3/10 km"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "세 값 중 가장 작은 값을 선택했는지 확인",
            "expected": "은행",
            "actual": "은행",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "nearest_place", "description": "집에서 가장 가까운 곳"},
        "value": 0,
        "unit": "",
    },
}
