from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, LineSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008869', title='어항과 수조의 들이 비교', canvas=Canvas(width=940, height=520, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2', 'slot.q3', 'slot.q4', 'slot.q5')),), slots=(TextSlot(id='slot.q1', prompt='', text='22.', style_role='question', x=12.0, y=28.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='어항에 물을 가득 채운 후 수조에 옮겨 담았습니다.', style_role='question', x=88.0, y=28.0, font_size=28), TextSlot(id='slot.q3', prompt='', text='그림과 같이 수조를', style_role='question', x=12.0, y=64.0, font_size=28), TextSlot(id='slot.q4', prompt='', text='가득 채우고 어항에 물이 남았다면 어항과 수조 중 들이가 더 많은 것은 어느 것인가요?', style_role='question', x=12.0, y=100.0, font_size=28), RectSlot(id='slot.aquarium_left_body', prompt='', x=168.0, y=148.0, width=128.0, height=110.0), TextSlot(id='slot.lb.aquarium_left', prompt='', text='어항', style_role='label', x=190.0, y=280.0, font_size=28), RectSlot(id='slot.aquarium_left_water', prompt='', x=176.0, y=182.0, width=112.0, height=68.0), RectSlot(id='slot.tank_left_body', prompt='', x=286.0, y=198.0, width=118.0, height=94.0), TextSlot(id='slot.lb.tank_left', prompt='', text='수조', style_role='label', x=321.0, y=320.0, font_size=28), RectSlot(id='slot.tank_left_water', prompt='', x=292.0, y=258.0, width=106.0, height=34.0), TextSlot(id='slot.arrow', prompt='', text='→', style_role='label', x=459.0, y=258.0, font_size=40), RectSlot(id='slot.aquarium_right_body', prompt='', x=516.0, y=148.0, width=128.0, height=110.0), TextSlot(id='slot.lb.aquarium_right', prompt='', text='어항', style_role='label', x=548.0, y=280.0, font_size=28), RectSlot(id='slot.aquarium_right_water', prompt='', x=525.0, y=232.0, width=110.0, height=36.0), RectSlot(id='slot.tank_right_body', prompt='', x=676.0, y=198.0, width=118.0, height=94.0), TextSlot(id='slot.lb.tank_right', prompt='', text='수조', style_role='label', x=711.0, y=320.0, font_size=28), RectSlot(id='slot.tank_right_water', prompt='', x=682.0, y=210.0, width=106.0, height=82.0), TextSlot(id='slot.q5', prompt='', text='( 어항, 수조 )', style_role='question', x=397.0, y=378.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008869', 'problem_type': '비교', 'metadata': {'language': 'ko', 'question': '어항에 물을 가득 채운 후 수조에 옮겨 담았습니다. 그림과 같이 수조를 가득 채우고 어항에 물이 남았다면 어항과 수조 중 들이가 더 많은 것은 어느 것인가요?', 'instruction': '어항과 수조 중 들이가 더 많은 것을 고르시오.'}, 'domain': {'objects': [{'id': 'obj.aquarium', 'type': '용기', 'name': '어항'}, {'id': 'obj.tank', 'type': '용기', 'name': '수조'}, {'id': 'obj.transfer', 'type': '이동', 'name': '물 옮기기'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.aquarium', 'obj.tank', 'rel.transfer_water', 'rel.remaining_water'], 'target_ref': 'answer.target', 'condition_refs': ['rel.capacity_compare']}, 'plan': {'method': '비교', 'description': '옮겨 담은 뒤에도 물이 남는지 그림의 관계를 보고 들이가 더 큰 용기를 찾는다.'}, 'execute': {'expected_operations': ['그림 관계 확인', '남는 물의 의미 해석', '더 큰 들이 판단']}, 'review': {'check_methods': ['남는 물이 있으면 더 큰 용기인지 확인', '정답 용기 이름이 그림과 일치하는지 확인']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'capacity_comparison', 'description': '어항과 수조 중 들이가 더 많은 것'}, 'value': '어항', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008869', 'problem_type': '비교', 'inputs': {'total_ticks': 0, 'target_label': '어항과 수조 중 들이가 더 많은 것', 'target_ticks': 0, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.aquarium', 'value': {'name': '어항'}}, {'ref': 'obj.tank', 'value': {'name': '수조'}}, {'ref': 'rel.remaining_water', 'value': {'meaning': '수조를 가득 채우고 어항에 물이 남음'}}], 'target': {'ref': 'answer.target', 'type': 'capacity_comparison'}, 'method': '비교', 'plan': ['그림에서 수조가 가득 차고도 어항에 물이 남는다는 관계를 확인한다.', '남는 물이 있다는 것은 어항의 들이가 수조보다 크다는 뜻으로 해석한다.'], 'steps': [{'id': 'step.1', 'expr': '수조가 가득 찬 뒤에도 어항에 물이 남는다', 'value': '어항의 들이가 더 큼'}, {'id': 'step.2', 'expr': '비교 대상: 어항, 수조', 'value': '어항'}], 'checks': [{'id': 'check.1', 'expr': '남는 물이 있으면 더 큰 용기가 어항인지 확인', 'expected': '어항', 'actual': '어항', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'capacity_comparison', 'description': '어항과 수조 중 들이가 더 많은 것'}, 'value': '어항', 'unit': ''}}
