from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008771",
        title="실제 무게에 가장 가깝게 어림한 사람",
        canvas=Canvas(width=960, height=392, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.table.outer",
                    "slot.table.r1c1",
                    "slot.table.r1c2",
                    "slot.table.r1c3",
                    "slot.table.r1c4",
                    "slot.table.r2c1",
                    "slot.table.r2c2",
                    "slot.table.r2c3",
                    "slot.table.r2c4",
                    "slot.choice",
                    "slot.table_1.outer",
                    "slot.table_1.v1",
                    "slot.table_1.v2",
                    "slot.table_1.v3",
                    "slot.table_1.h1",
                    "slot.table_1.r1c1",
                    "slot.table_1.r1c2",
                    "slot.table_1.r1c3",
                    "slot.table_1.r1c4",
                    "slot.table_1.r2c1",
                    "slot.table_1.r2c2",
                    "slot.table_1.r2c3",
                    "slot.table_1.r2c4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="주연, 선우, 다혜는 실제 무게가 2 kg 100 g인 고양이의 무게를 다음과 같이",
                style_role="question",
                x=12.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="어림하였습니다. 실제 무게에 가장 가깝게 어림한 사람은 누구인가요?",
                style_role="question",
                x=12,
                y=68,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=((68.0) + (-15.0)) + (5.0),
                y=((82.0) + (150.0)) + (25.0),
                width=790.0,
                height=84.0,
            ),
            RectSlot(
                id="slot.table.r1c1",
                prompt="",
                x=((68.0) + (-15.0)) + (5.0),
                y=((82.0) + (150.0)) + (25.0),
                width=198.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r1c2",
                prompt="",
                x=((266.0) + (-15.0)) + (5.0),
                y=((82.0) + (150.0)) + (25.0),
                width=198.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r1c3",
                prompt="",
                x=((464.0) + (-15.0)) + (5.0),
                y=((82.0) + (150.0)) + (25.0),
                width=198.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r1c4",
                prompt="",
                x=((662.0) + (-15.0)) + (5.0),
                y=((82.0) + (150.0)) + (25.0),
                width=196.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r2c1",
                prompt="",
                x=((68.0) + (-15.0)) + (5.0),
                y=((124.0) + (150.0)) + (25.0),
                width=198.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r2c2",
                prompt="",
                x=((266.0) + (-15.0)) + (5.0),
                y=((124.0) + (150.0)) + (25.0),
                width=198.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r2c3",
                prompt="",
                x=((464.0) + (-15.0)) + (5.0),
                y=((124.0) + (150.0)) + (25.0),
                width=198.0,
                height=42.0,
            ),
            RectSlot(
                id="slot.table.r2c4",
                prompt="",
                x=((662.0) + (-15.0)) + (5.0),
                y=((124.0) + (150.0)) + (25.0),
                width=196.0,
                height=42.0,
            ),
            TextSlot(
                id="slot.table.r1c1_text",
                prompt="",
                text="이름",
                style_role="label",
                x=((167.0) + (-15.0)) + (5.0),
                y=((108.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c2_text",
                prompt="",
                text="주연",
                style_role="label",
                x=((365.0) + (-15.0)) + (5.0),
                y=((108.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c3_text",
                prompt="",
                text="선우",
                style_role="label",
                x=((563.0) + (-15.0)) + (5.0),
                y=((108.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c4_text",
                prompt="",
                text="다혜",
                style_role="label",
                x=((760.0) + (-15.0)) + (5.0),
                y=((108.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c1_text",
                prompt="",
                text="어림한 무게",
                style_role="label",
                x=((167.0) + (-15.0)) + (5.0),
                y=((150.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c2_text",
                prompt="",
                text="약 2 kg",
                style_role="label",
                x=((365.0) + (-15.0)) + (5.0),
                y=((150.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c3_text",
                prompt="",
                text="약 2 kg 300 g",
                style_role="label",
                x=((563.0) + (-15.0)) + (5.0),
                y=((150.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c4_text",
                prompt="",
                text="약 1 kg 800 g",
                style_role="label",
                x=((760.0) + (-15.0)) + (5.0),
                y=((150.0) + (150.0)) + (25.0),
                font_size=28,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 주연 , 선우 , 다혜 )",
                style_role="note",
                x=335,
                y=379,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.table_1.outer",
                prompt="",
                x=165,
                y=110,
                width=535,
                height=120,
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v1",
                prompt="",
                x1=300,
                y1=110,
                x2=300,
                y2=230,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v2",
                prompt="",
                x1=425,
                y1=110,
                x2=425,
                y2=230,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v3",
                prompt="",
                x1=580,
                y1=110,
                x2=580,
                y2=230,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.h1",
                prompt="",
                x1=165,
                y1=170,
                x2=700,
                y2=170,
                stroke="#111827",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table_1.r1c1",
                prompt="",
                text="이름",
                x=240,
                y=155,
                font_size=30,
                max_width=130,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c2",
                prompt="",
                text="주연",
                x=385,
                y=155,
                font_size=30,
                max_width=115,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c3",
                prompt="",
                text="선우",
                x=515,
                y=155,
                font_size=30,
                max_width=110,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c4",
                prompt="",
                text="",
                x=640,
                y=155,
                font_size=30,
                max_width=100,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c1",
                prompt="",
                text="어림한 무게",
                x=240,
                y=200,
                font_size=30,
                max_width=130,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c2",
                prompt="",
                text="약 2kg",
                x=385,
                y=215,
                font_size=30,
                max_width=115,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c3",
                prompt="",
                text="",
                x=515,
                y=215,
                font_size=30,
                max_width=110,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c4",
                prompt="",
                text="",
                x=640,
                y=215,
                font_size=30,
                max_width=100,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008771",
    "problem_type": "비교_가까운_어림값",
    "metadata": {
        "language": "ko",
        "question": "실제 무게 2 kg 100 g에 가장 가깝게 어림한 사람을 찾는 문제",
        "instruction": "실제 무게에 가장 가깝게 어림한 사람은 누구인가요?",
    },
    "domain": {
        "objects": [
            {"id": "obj.actual_weight", "type": "weight", "value": "2 kg 100 g"},
            {"id": "obj.juyeon", "type": "estimate", "owner": "주연", "value": "2 kg"},
            {"id": "obj.seonu", "type": "estimate", "owner": "선우", "value": "2 kg 300 g"},
            {"id": "obj.dahye", "type": "estimate", "owner": "다혜", "value": "1 kg 800 g"},
        ],
        "relations": [],
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_name", "description": "실제 무게에 가장 가깝게 어림한 사람"},
        "value": "주연",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008771",
    "problem_type": "비교_가까운_어림값",
    "inputs": {
        "total_ticks": 0,
        "target_label": "실제 무게에 가장 가깝게 어림한 사람",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "kg,g",
    },
    "given": [
        {"ref": "obj.actual_weight", "value": "2 kg 100 g"},
        {"ref": "obj.juyeon", "value": "2 kg"},
        {"ref": "obj.seonu", "value": "2 kg 300 g"},
        {"ref": "obj.dahye", "value": "1 kg 800 g"},
    ],
    "target": {"ref": "answer.target", "type": "person_name"},
    "method": "compare_distances",
    "plan": ["실제 무게와 각 어림값의 차이를 비교합니다.", "가장 차이가 작은 사람을 찾습니다."],
    "steps": [
        {"id": "step.1", "expr": "2 kg 100 g와 주연의 어림값 2 kg 비교", "value": "100 g 차이"},
        {
            "id": "step.2",
            "expr": "2 kg 100 g와 선우의 어림값 2 kg 300 g 비교",
            "value": "200 g 차이",
        },
        {
            "id": "step.3",
            "expr": "2 kg 100 g와 다혜의 어림값 1 kg 800 g 비교",
            "value": "300 g 차이",
        },
        {"id": "step.4", "expr": "가장 차이가 작은 사람 선택", "value": "주연"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "100 g, 200 g, 300 g 중 가장 작은 값 확인",
            "expected": "100 g",
            "actual": "100 g",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_name", "description": "실제 무게에 가장 가깝게 어림한 사람"},
        "value": "주연",
        "unit": "",
    },
}
