from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, ProblemTemplate, RectSlot, Region, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008960', title='학생들의 혈액형 그림그래프', canvas=Canvas(width=945, height=695, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2', 'slot.q3')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.title', 'slot.table.outer', 'slot.table.header_left', 'slot.table.header_right', 'slot.table.row.a', 'slot.table.row.b', 'slot.table.row.ab', 'slot.table.row.o', 'slot.legend.face', 'slot.legend.dot', 'slot.choice.1.label', 'slot.choice.2.label', 'slot.choice.3.label', 'slot.choice.4.label', 'slot.choice.5.label')), Region(id='region.footer', role='footer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='30. 정호네 학교 학생 1250명의 혈액형을 조사하여 그림그래프로 나타내었습니다.', style_role='question', x=20.0, y=28.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='혈액형이 AB형인 학생 수를 바르게 나타낸 것은 어느 것일까요?', style_role='question', x=20.0, y=64.0, font_size=28), TextSlot(id='slot.q3', prompt='', text='', style_role='question', x=0.0, y=0.0, font_size=28), TextSlot(id='slot.title', prompt='', text='학생들의 혈액형', style_role='title', x=450.0, y=124.0, font_size=28), RectSlot(id='slot.table.outer', prompt='', x=245.0, y=158.0, width=420.0, height=246.0), RectSlot(id='slot.table.header_left', prompt='', x=245.0, y=158.0, width=110.0, height=44.0), RectSlot(id='slot.table.header_right', prompt='', x=355.0, y=158.0, width=310.0, height=44.0), RectSlot(id='slot.table.row.a', prompt='', x=245.0, y=202.0, width=110.0, height=50.0), RectSlot(id='slot.table.row.b', prompt='', x=245.0, y=252.0, width=110.0, height=50.0), RectSlot(id='slot.table.row.ab', prompt='', x=245.0, y=302.0, width=110.0, height=50.0), RectSlot(id='slot.table.row.o', prompt='', x=245.0, y=352.0, width=110.0, height=52.0), TextSlot(id='slot.legend.face', prompt='', text='😊 100명', style_role='label', x=510.0, y=386.0, font_size=28), TextSlot(id='slot.legend.dot', prompt='', text='• 10명', style_role='label', x=610.0, y=386.0, font_size=28), TextSlot(id='slot.choice.1.label', prompt='', text='①', style_role='label', x=36.0, y=420.0, font_size=28), TextSlot(id='slot.choice.2.label', prompt='', text='②', style_role='label', x=500.0, y=420.0, font_size=28), TextSlot(id='slot.choice.3.label', prompt='', text='③', style_role='label', x=36.0, y=472.0, font_size=28), TextSlot(id='slot.choice.4.label', prompt='', text='④', style_role='label', x=500.0, y=472.0, font_size=28), TextSlot(id='slot.choice.5.label', prompt='', text='⑤', style_role='label', x=36.0, y=524.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008960', 'problem_type': 'picture_graph_choice', 'metadata': {'language': 'ko', 'question': '정호네 학교 학생 1250명의 혈액형을 조사하여 그림그래프로 나타내었습니다. 혈액형이 AB형인 학생 수를 바르게 나타낸 것은 어느 것일까요?', 'instruction': '그림그래프와 선택지 중 알맞은 것을 고르기'}, 'domain': {'objects': [{'id': 'obj.total_students', 'type': 'count', 'value': 1250, 'unit': '명'}, {'id': 'obj.legend.big_icon', 'type': 'pictograph_unit', 'value': 100, 'unit': '명'}, {'id': 'obj.legend.small_icon', 'type': 'pictograph_unit', 'value': 10, 'unit': '명'}, {'id': 'obj.blood_type.ab', 'type': 'category', 'label': 'AB형'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.total_students', 'obj.legend.big_icon', 'obj.legend.small_icon'], 'target_ref': 'answer.target', 'condition_refs': ['rel.legend_scale', 'rel.find_ab_count']}, 'plan': {'method': '그림그래프에서 AB형에 해당하는 조합을 고른다.', 'description': '전체 학생 수와 다른 혈액형의 합을 참고해 AB형에 맞는 그림 조합을 찾는다.'}, 'execute': {'expected_operations': ['read_graph_values', 'compare_choice_patterns', 'match_pictograph_unit']}, 'review': {'check_methods': ['choice_match_check', 'unit_count_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': 'AB형 학생 수를 바르게 나타낸 선택지'}, 'value': 4, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008960', 'problem_type': 'picture_graph_choice', 'inputs': {'total_ticks': 1250, 'target_label': 'AB형', 'target_ticks': 270, 'target_count': 270, 'unit': '명'}, 'given': [{'ref': 'obj.total_students', 'value': 1250}, {'ref': 'obj.legend.big_icon', 'value': 100}, {'ref': 'obj.legend.small_icon', 'value': 10}], 'target': {'ref': 'answer.target', 'type': 'choice_selection'}, 'method': '그림그래프 판독 및 선택지 대응', 'plan': ['전체 학생 수와 해설에 보이는 합계를 이용해 AB형의 수를 확인한다.', 'AB형 수를 100명 단위와 10명 단위 그림으로 바꾼 선택지를 찾는다.'], 'steps': [{'id': 'step.1', 'expr': '350 + 290 + 340', 'value': 980}, {'id': 'step.2', 'expr': '1250 - 980', 'value': 270}, {'id': 'step.3', 'expr': '270 = 100×2 + 10×7', 'value': 270}, {'id': 'step.4', 'expr': '선택지 비교 결과 ④', 'value': 4}], 'checks': [{'id': 'check.1', 'expr': '100×2 + 10×7', 'expected': 270, 'actual': 270, 'pass': True}, {'id': 'check.2', 'expr': '선택지 번호', 'expected': 4, 'actual': 4, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': 'AB형 학생 수를 바르게 나타낸 선택지'}, 'value': 4, 'unit': ''}}
