from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008966",
        title="두 번째로 많은 학생들이 받고 싶어 하는 생일 선물",
        canvas=Canvas(width=945, height=460, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.title_box",
                    "slot.table.outer",
                    "slot.table.c1r1",
                    "slot.table.c2r1",
                    "slot.table.c3r1",
                    "slot.table.c4r1",
                    "slot.table.c5r1",
                    "slot.table.c6r1",
                    "slot.table.c1r2",
                    "slot.table.c2r2",
                    "slot.table.c3r2",
                    "slot.table.c4r2",
                    "slot.table.c5r2",
                    "slot.table.c6r2",
                    "slot.table.caption",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="36. 윤지네 반 학생들이 받고 싶어 하는 생일 선물을 조사하여 결과를 나타내었습니다. 두 번째로 많은 학생들이 받고 싶어 하는 생일 선물을 선택하세요.",
                style_role="question",
                x=14.0,
                y=28.0,
                font_size=28,
            ),
            RectSlot(id="slot.title_box", prompt="", x=241.0, y=130.0, width=487.0, height=48.0),
            TextSlot(
                id="slot.title_box.text",
                prompt="",
                text="학생들이 받고 싶어 하는 생일 선물",
                style_role="title",
                x=307.0,
                y=162.0,
                font_size=28,
            ),
            RectSlot(id="slot.table.outer", prompt="", x=109.0, y=182.0, width=750.0, height=120.0),
            RectSlot(id="slot.table.c1r1", prompt="", x=109.0, y=182.0, width=165.0, height=48.0),
            RectSlot(id="slot.table.c2r1", prompt="", x=274.0, y=182.0, width=117.0, height=48.0),
            RectSlot(id="slot.table.c3r1", prompt="", x=391.0, y=182.0, width=117.0, height=48.0),
            RectSlot(id="slot.table.c4r1", prompt="", x=508.0, y=182.0, width=118.0, height=48.0),
            RectSlot(id="slot.table.c5r1", prompt="", x=626.0, y=182.0, width=118.0, height=48.0),
            RectSlot(id="slot.table.c6r1", prompt="", x=744.0, y=182.0, width=115.0, height=48.0),
            RectSlot(id="slot.table.c1r2", prompt="", x=109.0, y=230.0, width=165.0, height=42.0),
            RectSlot(id="slot.table.c2r2", prompt="", x=274.0, y=230.0, width=117.0, height=42.0),
            RectSlot(id="slot.table.c3r2", prompt="", x=391.0, y=230.0, width=117.0, height=42.0),
            RectSlot(id="slot.table.c4r2", prompt="", x=508.0, y=230.0, width=118.0, height=42.0),
            RectSlot(id="slot.table.c5r2", prompt="", x=626.0, y=230.0, width=118.0, height=42.0),
            RectSlot(id="slot.table.c6r2", prompt="", x=744.0, y=230.0, width=115.0, height=42.0),
            TextSlot(
                id="slot.table.r1c1",
                prompt="",
                text="선물",
                style_role="body",
                x=180.0,
                y=214.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c2",
                prompt="",
                text="휴대전화",
                style_role="body",
                x=303.0,
                y=214.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c3",
                prompt="",
                text="학용품",
                style_role="body",
                x=426.0,
                y=214.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c4",
                prompt="",
                text="장난감",
                style_role="body",
                x=548.0,
                y=214.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c5",
                prompt="",
                text="책",
                style_role="body",
                x=686.0,
                y=214.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c6",
                prompt="",
                text="합계",
                style_role="body",
                x=810.0,
                y=214.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c1",
                prompt="",
                text="학생 수(명)",
                style_role="body",
                x=177.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c2",
                prompt="",
                text="11",
                style_role="body",
                x=303.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c3",
                prompt="",
                text="5",
                style_role="body",
                x=426.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c4",
                prompt="",
                text="8",
                style_role="body",
                x=548.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c5",
                prompt="",
                text="4",
                style_role="body",
                x=686.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c6",
                prompt="",
                text="28",
                style_role="body",
                x=810.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.caption",
                prompt="",
                text="( 휴대전화 , 학용품 , 장난감 , 책 )",
                style_role="body",
                x=287.0,
                y=307.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008966",
    "problem_type": "comparison_table",
    "metadata": {
        "language": "ko",
        "question": "윤지네 반 학생들이 받고 싶어 하는 생일 선물을 조사하여 결과를 나타내었습니다. 두 번째로 많은 학생들이 받고 싶어 하는 생일 선물을 선택하세요.",
        "instruction": "두 번째로 많은 학생들이 받고 싶어 하는 생일 선물을 선택하세요.",
        "points": 0,
    },
    "domain": {
        "objects": [
            {"id": "obj.phone", "type": "gift_category", "name": "휴대전화", "count": 11},
            {"id": "obj.school_supplies", "type": "gift_category", "name": "학용품", "count": 5},
            {"id": "obj.toy", "type": "gift_category", "name": "장난감", "count": 8},
            {"id": "obj.book", "type": "gift_category", "name": "책", "count": 4},
            {"id": "obj.total", "type": "total", "name": "합계", "count": 28},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.phone", "obj.school_supplies", "obj.toy", "obj.book"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_counts"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "표의 학생 수를 비교하여 두 번째로 큰 값을 찾는다.",
            },
            "execute": {"expected_operations": ["compare_values", "identify_second_largest"]},
            "review": {"check_methods": ["order_check", "table_value_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "gift_category",
            "description": "두 번째로 많은 학생들이 받고 싶어 하는 생일 선물",
        },
        "value": "장난감",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008966",
    "problem_type": "comparison_table",
    "inputs": {
        "total_ticks": 1,
        "target_label": "두 번째로 많은 학생들이 받고 싶어 하는 생일 선물",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.phone", "value": {"name": "휴대전화", "count": 11}},
        {"ref": "obj.school_supplies", "value": {"name": "학용품", "count": 5}},
        {"ref": "obj.toy", "value": {"name": "장난감", "count": 8}},
        {"ref": "obj.book", "value": {"name": "책", "count": 4}},
        {"ref": "obj.total", "value": {"name": "합계", "count": 28}},
    ],
    "target": {"ref": "answer.target", "type": "gift_category"},
    "plan": "표의 각 선물별 학생 수를 비교하여 두 번째로 큰 범주를 찾는다.",
    "steps": [
        {"id": "step.1", "expr": "11, 5, 8, 4를 비교한다.", "value": [11, 5, 8, 4]},
        {
            "id": "step.2",
            "expr": "큰 순서로 정리하면 11 > 8 > 5 > 4 이다.",
            "value": ["휴대전화", "장난감", "학용품", "책"],
        },
        {"id": "step.3", "expr": "두 번째로 큰 값에 해당하는 선물을 찾는다.", "value": "장난감"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "장난감의 학생 수는 8이고, 이는 두 번째로 큰 값인가?",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "gift_category",
            "description": "두 번째로 많은 학생들이 받고 싶어 하는 생일 선물",
        },
        "value": "장난감",
        "unit": "",
    },
}
