from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008712', title='원의 지름을 나타내는 선분', canvas=Canvas(width=960, height=360, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1',)), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.circle.outer', 'slot.line.kr', 'slot.line.nl', 'slot.line.od', 'slot.pt.center', 'slot.pt.giyeok', 'slot.pt.nieun', 'slot.pt.digeut', 'slot.pt.rieul', 'slot.pt.ieung', 'slot.lb.giyeok', 'slot.lb.nieun', 'slot.lb.digeut', 'slot.lb.rieul', 'slot.lb.ieung')), Region(id='region.choice', role='choice', flow='absolute', slot_ids=('slot.choice',)), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='10. 원에서 원의 지름을 나타내는 선분을 선택하세요.', style_role='question', x=20.0, y=30.0, font_size=28), CircleSlot(id='slot.circle.outer', prompt='', cx=490.0, cy=150.0, r=84.0, fill='none'), LineSlot(id='slot.line.kr', prompt='', x1=468.0, y1=68.0, x2=570.0, y2=127.0), LineSlot(id='slot.line.nl', prompt='', x1=405.0, y1=178.0, x2=570.0, y2=127.0), LineSlot(id='slot.line.od', prompt='', x1=490.0, y1=150.0, x2=530.0, y2=228.0), CircleSlot(id='slot.pt.center', prompt='', cx=490.0, cy=150.0, r=4.0, fill='#d81b60'), CircleSlot(id='slot.pt.giyeok', prompt='', cx=472.0, cy=68.0, r=3.8, fill='#222222'), CircleSlot(id='slot.pt.nieun', prompt='', cx=405.0, cy=178.0, r=3.8, fill='#222222'), CircleSlot(id='slot.pt.digeut', prompt='', cx=530.0, cy=228.0, r=3.8, fill='#222222'), CircleSlot(id='slot.pt.rieul', prompt='', cx=571.0, cy=127.0, r=3.8, fill='#222222'), CircleSlot(id='slot.pt.ieung', prompt='', cx=490.0, cy=118.0, r=3.8, fill='#222222'), TextSlot(id='slot.lb.giyeok', prompt='', text='ㄱ', style_role='label', x=458.0, y=58.0, font_size=28), TextSlot(id='slot.lb.nieun', prompt='', text='ㄴ', style_role='label', x=384.0, y=192.0, font_size=28), TextSlot(id='slot.lb.digeut', prompt='', text='ㄷ', style_role='label', x=524.0, y=256.0, font_size=28), TextSlot(id='slot.lb.rieul', prompt='', text='ㄹ', style_role='label', x=580.0, y=132.0, font_size=28), TextSlot(id='slot.lb.ieung', prompt='', text='ㅇ', style_role='label', x=484.0, y=109.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='( 선분 ㄱㄹ , 선분 ㄴㄹ , 선분 ㅇㄷ )', style_role='choice', x=470.0, y=266.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008712', 'problem_type': 'geometry_circle_diameter_selection', 'metadata': {'language': 'ko', 'question': '원에서 원의 지름을 나타내는 선분을 선택하는 문제', 'instruction': '원에서 원의 지름을 나타내는 선분을 선택하세요.'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.center', 'type': 'center', 'of': 'obj.circle'}, {'id': 'obj.segment.gn', 'type': 'segment', 'label': 'ㄱㄹ'}, {'id': 'obj.segment.nn', 'type': 'segment', 'label': 'ㄴㄹ'}, {'id': 'obj.segment.od', 'type': 'segment', 'label': 'ㅇㄷ'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle', 'obj.center', 'obj.segment.gn', 'obj.segment.nn', 'obj.segment.od'], 'target_ref': 'answer.target', 'condition_refs': ['rel.diameter_candidate']}, 'plan': {'method': 'diagram_identification', 'description': '중심을 지나고 원 위의 두 점을 이은 선분을 찾는다.'}, 'execute': {'expected_operations': ['compare_segments_to_center', 'identify_circle_points']}, 'review': {'check_methods': ['center_pass_check', 'endpoint_on_circle_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_segment', 'description': '원의 지름을 나타내는 선분'}, 'value': '선분 ㄴㄹ', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008712', 'problem_type': 'geometry_circle_diameter_selection', 'inputs': {'total_ticks': 1, 'target_label': '지름을 나타내는 선분', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': {'type': 'circle'}}, {'ref': 'obj.center', 'value': {'type': 'center'}}, {'ref': 'obj.segment.gn', 'value': {'label': 'ㄱㄹ'}}, {'ref': 'obj.segment.nn', 'value': {'label': 'ㄴㄹ'}}, {'ref': 'obj.segment.od', 'value': {'label': 'ㅇㄷ'}}], 'target': {'ref': 'answer.target', 'type': 'selected_segment'}, 'method': 'diagram_identification', 'plan': ['원의 중심을 지나는 선분을 찾는다.', '원 위의 두 점을 이은 선분인지 확인한다.'], 'steps': [{'id': 'step.1', 'expr': '선분 ㄴㄹ은 중심을 지난다.', 'value': '선분 ㄴㄹ'}, {'id': 'step.2', 'expr': '선분 ㄴㄹ은 원 위의 두 점을 이은 선분이다.', 'value': '선분 ㄴㄹ'}, {'id': 'step.3', 'expr': '지름에 해당하는 선분 선택', 'value': '선분 ㄴㄹ'}], 'checks': [{'id': 'check.1', 'expr': '중심 통과 여부', 'expected': True, 'actual': True, 'pass': True}, {'id': 'check.2', 'expr': '원 위의 두 점 연결 여부', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_segment', 'description': '원의 지름을 나타내는 선분'}, 'value': '선분 ㄴㄹ', 'unit': ''}}
