from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, LineSlot, CircleSlot, PathSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009015', title='반직선 선택하기', canvas=Canvas(width=760, height=240, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.no_box', 'slot.qnum', 'slot.qtext')), Region(id='region.figures_top', role='diagram', flow='absolute', slot_ids=('slot.top.segment', 'slot.top.segment.p1', 'slot.top.segment.p2', 'slot.top.ray', 'slot.top.ray.p1', 'slot.top.ray.p2', 'slot.top.curve')), Region(id='region.figures_bottom', role='diagram', flow='absolute', slot_ids=('slot.answer.ray', 'slot.answer.ray.p1', 'slot.answer.ray.p2')), Region(id='region.explanation', role='explanation', flow='absolute', slot_ids=())), slots=(RectSlot(id='slot.no_box', prompt='', x=10.0, y=8.0, width=16.0, height=16.0), TextSlot(id='slot.qnum', prompt='', text='53.', style_role='question', x=34.0, y=24.0, font_size=28), TextSlot(id='slot.qtext', prompt='', text='반직선을 선택하세요.', style_role='question', x=88.0, y=24.0, font_size=28), LineSlot(id='slot.top.segment', prompt='', x1=151.0, y1=84.0, x2=279.0, y2=84.0), CircleSlot(id='slot.top.segment.p1', prompt='', cx=151.0, cy=84.0, r=3.0, fill='#222222'), CircleSlot(id='slot.top.segment.p2', prompt='', cx=279.0, cy=84.0, r=3.0, fill='#222222'), LineSlot(id='slot.top.ray', prompt='', x1=394.0, y1=60.0, x2=512.0, y2=109.0), CircleSlot(id='slot.top.ray.p1', prompt='', cx=394.0, cy=60.0, r=3.0, fill='#222222'), CircleSlot(id='slot.top.ray.p2', prompt='', cx=468.0, cy=91.0, r=3.0, fill='#222222'), PathSlot(id='slot.top.curve', prompt='', d='M 660.0 40.0 C 694.0 67.0 695.0 119.0 655.0 145.0 C 623.0 165.0 585.0 153.0 566.0 124.0'), CircleSlot(id='slot.answer.ray.p1', prompt='', cx=42.0, cy=147.0, r=3.0, fill='#222222'), CircleSlot(id='slot.answer.ray.p2', prompt='', cx=157.0, cy=194.0, r=3.0, fill='#222222'), LineSlot(id='slot.answer.ray', prompt='', x1=42.0, y1=147.0, x2=178.0, y2=202.0)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009015', 'problem_type': '도형_선분_반직선_곡선_선택', 'metadata': {'language': 'ko', 'question': '반직선을 선택하세요.', 'instruction': '도형들 중에서 반직선에 해당하는 것을 고른다.'}, 'domain': {'objects': [{'id': 'obj.top.segment', 'type': 'line_segment'}, {'id': 'obj.top.ray', 'type': 'ray_candidate'}, {'id': 'obj.top.curve', 'type': 'curve'}, {'id': 'obj.answer.ray', 'type': 'ray'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.top.segment', 'obj.top.ray', 'obj.top.curve', 'obj.answer.ray'], 'target_ref': 'answer.target', 'condition_refs': ['rel.choose_ray']}, 'plan': {'method': '도형 분류', 'description': '보이는 도형들 중 반직선의 특징에 맞는 것을 고른다.'}, 'execute': {'expected_operations': ['도형의 끝점과 방향을 확인한다', '한 점에서 시작해 한쪽으로 이어지는지 본다', '정답 표시가 붙은 도형을 확인한다']}, 'review': {'check_methods': ['해설 문장과 도형의 특징을 대조한다']}}}, 'answer': {'target': {'type': 'selected_shape', 'description': '반직선'}, 'value': 1, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009015', 'problem_type': '도형_선분_반직선_곡선_선택', 'inputs': {'total_ticks': 3, 'target_label': '반직선', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.top.segment', 'value': {'type': 'line_segment'}}, {'ref': 'obj.top.ray', 'value': {'type': 'ray_candidate'}}, {'ref': 'obj.top.curve', 'value': {'type': 'curve'}}, {'ref': 'obj.answer.ray', 'value': {'type': 'ray'}}], 'target': {'ref': 'answer.target', 'type': 'selected_shape'}, 'method': '도형 분류', 'plan': ['보이는 도형의 특징을 비교해 반직선을 찾는다.'], 'steps': [{'id': 'step.1', 'expr': '반직선의 특징 확인', 'value': '한 점에서 시작하여 한쪽으로 끝없이 늘인 곧은 선'}, {'id': 'step.2', 'expr': '정답 표시가 붙은 도형 확인', 'value': '반직선'}], 'checks': [{'id': 'check.1', 'expr': '해설 문장과 선택 대상이 일치하는지 확인', 'expected': '반직선', 'actual': '반직선', 'pass': True}], 'answer': {'value': 1, 'unit': '', 'derived_from': 'step.2'}}
