from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    ProblemTemplate,
    Region,
    TextSlot,
    ImageSlot,
    PathSlot,
    TextBoxSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008802",
        title="고구마와 감자의 무게를 비교하는 방법",
        canvas=Canvas(width=952.0, height=602.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.inserted.calloutRect.1",
                    "slot.inserted.calloutRect.1.copy1",
                ),
            ),
            Region(
                id="region.dialogue_left",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.left.speech",
                    "slot.left.name",
                    "tr8YvmUi6ZnuyChUrZhgf",
                    "7YhqQ7atny95jS000mK7i",
                    "VafHSxaOlJa31_nCm2Cm6",
                ),
            ),
            Region(
                id="region.dialogue_right",
                role="diagram",
                flow="absolute",
                slot_ids=("slot.right.speech", "slot.right.name"),
            ),
            Region(id="region.footer", role="note", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="고구마와 감자를 양손에 들어 보니 어느 것이 더 무거운지 알 수 없었습니다.",
                style_role="question",
                x=38.2,
                y=39.72,
                font_size=28,
                fill="#111111",
                max_width=922.178,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="고구마와 감자의 무게를 비교할 수 있는 방법을 바르게 말한 사람을",
                style_role="question",
                x=31.912,
                y=383.935,
                font_size=28,
                fill="#111111",
                max_width=805.41,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="선택해 보세요.",
                style_role="question",
                x=37.153,
                y=79.424,
                font_size=28,
                fill="#111111",
                max_width=210.537,
            ),
            TextSlot(
                id="slot.left.speech",
                prompt="",
                text="눈으로 크기를 비교해 보면",
                style_role="speech",
                x=36.8,
                y=160.157,
                font_size=28,
                fill="#111111",
                max_width=434.802,
            ),
            TextSlot(
                id="slot.left.name",
                prompt="",
                text="상규",
                style_role="label",
                x=221.493,
                y=570.213,
                font_size=30,
                fill="#111111",
                max_width=93.505,
            ),
            TextSlot(
                id="slot.right.speech",
                prompt="",
                text="저울의 양쪽 접시에 고구마와 감자를",
                style_role="speech",
                x=472.29,
                y=152.421,
                font_size=28,
                fill="#111111",
                max_width=446.725,
            ),
            TextSlot(
                id="slot.right.name",
                prompt="",
                text="민하",
                style_role="label",
                x=775.727,
                y=571.247,
                font_size=28,
                fill="#111111",
                max_width=89.577,
            ),
            PathSlot(
                id="slot.inserted.calloutRect.1",
                prompt="",
                d="M 22.89 112.607 L 423.87 112.607 L 423.87 257.033 L 286.391 257.033 L 211.924 301.471 L 223.381 257.033 L 22.89 257.033 Z",
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1.5,
            ),
            PathSlot(
                id="slot.inserted.calloutRect.1.copy1",
                prompt="",
                d="M 440.285 107.904 L 958.416 107.904 L 958.416 238.901 L 780.771 238.901 L 684.547 279.207 L 699.35 238.901 L 440.285 238.901 Z",
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1.5,
            ),
            TextBoxSlot(
                id="tr8YvmUi6ZnuyChUrZhgf",
                prompt="",
                text="크기가\n조금이라도 더 큰 것이\n더 무거워.",
                x=35.496,
                y=173.863,
                font_size=30,
                fill="#111111",
                width=330,
                height=37.5,
                align="left",
                line_height=1.05,
            ),
            TextBoxSlot(
                id="7YhqQ7atny95jS000mK7i",
                prompt="",
                text="각각 올려\n접시가 아래로 내려온 것이\n더 무거워.",
                x=582.077,
                y=183.864,
                font_size=25,
                fill="#111111",
                width=509.739,
                height=24,
                align="left",
                line_height=1.05,
            ),
            TextBoxSlot(
                id="VafHSxaOlJa31_nCm2Cm6",
                prompt="",
                text="크기가 조금이라도 더 큰 것이 더 무거워",
                x=33.691,
                y=177.759,
                font_size=30,
                fill="#111111",
                width=330,
                height=37.5,
                align="left",
                line_height=1.05,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008802",
    "problem_type": "choice",
    "metadata": {
        "language": "ko",
        "question": "고구마와 감자의 무게를 비교할 수 있는 방법을 바르게 말한 사람을 선택하는 문제",
        "instruction": "바르게 말한 사람을 선택해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.sweet_potato", "type": "food", "name": "고구마"},
            {"id": "obj.potato", "type": "food", "name": "감자"},
            {"id": "obj.sun_gyu", "type": "person", "name": "상규"},
            {"id": "obj.min_ha", "type": "person", "name": "민하"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.sweet_potato", "obj.potato", "obj.sun_gyu", "obj.min_ha"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_weight"],
            },
            "plan": {
                "method": "compare_by_scale",
                "description": "무게를 직접 비교할 수 있는 올바른 방법을 고른다.",
            },
            "execute": {
                "expected_operations": ["문장의 뜻 비교", "무게 비교 방법 확인", "올바른 사람 선택"]
            },
            "review": {"check_methods": ["방법이 무게 비교에 적절한지 확인"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_person",
            "description": "고구마와 감자의 무게를 비교하는 올바른 방법을 말한 사람",
        },
        "value": "민하",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008802",
    "problem_type": "choice",
    "inputs": {
        "total_ticks": 0,
        "target_label": "정답인 사람",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.sweet_potato", "value": {"name": "고구마"}},
        {"ref": "obj.potato", "value": {"name": "감자"}},
        {"ref": "obj.sun_gyu", "value": {"name": "상규"}},
        {"ref": "obj.min_ha", "value": {"name": "민하"}},
    ],
    "target": {"ref": "answer.target", "type": "selected_person"},
    "method": "compare_by_scale",
    "plan": [
        "두 사람이 말한 방법이 무게 비교에 적절한지 확인한다.",
        "저울을 이용하는 방법이 올바른지 판단한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "상규의 방법은 눈으로 크기를 비교하는 방법이다.",
            "value": "부적절",
        },
        {
            "id": "step.2",
            "expr": "민하의 방법은 저울의 양쪽 접시에 각각 올려 무게를 비교하는 방법이다.",
            "value": "적절",
        },
        {"id": "step.3", "expr": "올바른 사람 선택", "value": "민하"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "저울을 사용해 무게를 비교하는 방법이 맞는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "선택된 사람이 민하인가",
            "expected": "민하",
            "actual": "민하",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_person",
            "description": "고구마와 감자의 무게를 비교하는 올바른 방법을 말한 사람",
        },
        "value": "민하",
        "unit": "",
    },
}
