from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot, ImageSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008759",
        title="어림한 들이 비교",
        canvas=Canvas(width=940, height=430, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.choice",
                    "slot.q1.copy3",
                    "slot.q1.copy3.copy4",
                    "slot.table_1.outer",
                    "slot.table_1.v1",
                    "slot.table_1.v2",
                    "slot.table_1.h1",
                    "slot.table_1.r1c1",
                    "slot.table_1.r1c2",
                    "slot.table_1.r1c3",
                    "slot.table_1.r2c1",
                    "slot.table_1.r2c2",
                    "slot.table_1.r2c3",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="운영이와 현주는 실제 들이가 1500 mL인 물통의 들이를",
                style_role="question",
                x=12.0,
                y=30.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 운영 , 현주 )",
                style_role="body",
                x=265,
                y=390,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q1.copy3",
                prompt="",
                text="다음과 같이 어림하였습니다. 물통의 실제 들이에 더 가깝게",
                x=12,
                y=75,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q1.copy3.copy4",
                prompt="",
                text="어림한 사람은 누구인지 선택해 보세요.",
                x=12,
                y=120,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.table_1.outer",
                prompt="",
                x=(75) + (5.0),
                y=(215) + (-60.0),
                width=545,
                height=160,
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v1",
                prompt="",
                x1=(260) + (5.0),
                y1=(215) + (-60.0),
                x2=(260) + (5.0),
                y2=(375) + (-60.0),
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.v2",
                prompt="",
                x1=(435) + (5.0),
                y1=(215) + (-60.0),
                x2=(435) + (5.0),
                y2=(375) + (-60.0),
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table_1.h1",
                prompt="",
                x1=(75) + (5.0),
                y1=(285) + (-60.0),
                x2=(620) + (5.0),
                y2=(285) + (-60.0),
                stroke="#111827",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table_1.r1c1",
                prompt="",
                text="이름",
                x=(170) + (5.0),
                y=(265) + (-60.0),
                font_size=30,
                max_width=165,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c2",
                prompt="",
                text="윤영",
                x=(350) + (5.0),
                y=(265) + (-60.0),
                font_size=30,
                max_width=155,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r1c3",
                prompt="",
                text="현주",
                x=(530) + (5.0),
                y=(265) + (-60.0),
                font_size=30,
                max_width=165,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c1",
                prompt="",
                text="어림한 들이",
                x=(170) + (5.0),
                y=(345) + (-60.0),
                font_size=30,
                max_width=165,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c2",
                prompt="",
                text="약 1100ml",
                x=(350) + (5.0),
                y=(345) + (-60.0),
                font_size=30,
                max_width=155,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table_1.r2c3",
                prompt="",
                text="약 1300ml",
                x=(530) + (5.0),
                y=(345) + (-60.0),
                font_size=30,
                max_width=165,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008759",
    "problem_type": "비교",
    "metadata": {
        "language": "ko",
        "question": "실제 들이가 1500 mL인 물통의 들이를 더 가깝게 어림한 사람을 찾는 문제",
        "instruction": "물통의 실제 들이에 더 가깝게 어림한 사람은 누구인지 선택해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.capacity_actual", "type": "capacity", "value": 1500, "unit": "mL"},
            {"id": "obj.estimate.yeong", "type": "capacity", "value": 1100, "unit": "mL"},
            {"id": "obj.estimate.hyeonju", "type": "capacity", "value": 1300, "unit": "mL"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.capacity_actual", "obj.estimate.yeong", "obj.estimate.hyeonju"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare.yeong", "rel.compare.hyeonju"],
            },
            "plan": {
                "method": "compare_differences",
                "description": "기준값과 각 어림값의 차이를 비교하여 더 가까운 사람을 찾는다.",
            },
            "execute": {
                "expected_operations": ["compare_absolute_difference", "select_smaller_difference"]
            },
            "review": {"check_methods": ["difference_comparison"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_name", "description": "실제 들이에 더 가깝게 어림한 사람"},
        "value": "현주",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008759",
    "problem_type": "비교",
    "inputs": {
        "total_ticks": 0,
        "target_label": "실제 들이에 더 가깝게 어림한 사람",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "mL",
    },
    "given": [
        {"ref": "obj.capacity_actual", "value": {"amount": 1500, "unit": "mL"}},
        {"ref": "obj.estimate.yeong", "value": {"amount": 1100, "unit": "mL"}},
        {"ref": "obj.estimate.hyeonju", "value": {"amount": 1300, "unit": "mL"}},
    ],
    "target": {"ref": "answer.target", "type": "person_name"},
    "method": "compare_differences",
    "plan": ["기준값 1500 mL와 두 어림값의 차이를 비교한다.", "차이가 더 작은 쪽을 고른다."],
    "steps": [
        {"id": "step.1", "expr": "1500 - 1100", "value": 400},
        {"id": "step.2", "expr": "1500 - 1300", "value": 200},
        {"id": "step.3", "expr": "400 > 200", "value": True},
        {"id": "step.4", "expr": "더 가까운 사람", "value": "현주"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "1500 - 1100 = 400",
            "expected": 400,
            "actual": 400,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "1500 - 1300 = 200",
            "expected": 200,
            "actual": 200,
            "pass": True,
        },
        {"id": "check.3", "expr": "200 < 400", "expected": True, "actual": True, "pass": True},
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_name", "description": "실제 들이에 더 가깝게 어림한 사람"},
        "value": "현주",
        "unit": "",
    },
}
