from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008757",
        title="들이의 비교와 어림",
        canvas=Canvas(width=940, height=596, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.top",
                role="stem",
                flow="absolute",
                slot_ids=("slot.top.qmark", "slot.top.text"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.bottle.water.body",
                    "slot.bottle.water.cap",
                    "slot.bottle.water.label",
                    "slot.bottle.water.neck",
                    "slot.bottle.water.rings1",
                    "slot.bottle.water.rings2",
                    "slot.bottle.water.rings3",
                    "slot.bottle.water.rings4",
                    "slot.bottle.water.rings5",
                    "slot.bottle.soy.body",
                    "slot.bottle.soy.cap1",
                    "slot.bottle.soy.cap2",
                    "slot.bottle.soy.handle",
                    "slot.bottle.soy.label",
                    "slot.bottle.soy.spout",
                    "slot.bottle.soy.base",
                    "slot.diag.water_name",
                    "slot.diag.water_volume",
                    "slot.diag.soy_name",
                ),
            ),
            Region(
                id="region.choice1",
                role="stem",
                flow="absolute",
                slot_ids=("slot.choice1.text",),
            ),
            Region(
                id="region.choice2",
                role="stem",
                flow="absolute",
                slot_ids=("slot.choice2.arrow", "slot.choice2.text"),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.top.qmark",
                prompt="",
                text="□",
                style_role="question",
                x=9.0,
                y=26.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.top.text",
                prompt="",
                text="54. 500 mL 생수병을 보고 들이를 어림해 보려고 합니다. 알맞은 것을 선택하세요.",
                style_role="question",
                x=38.0,
                y=31.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.bottle.water.body",
                prompt="",
                x=352.0,
                y=122.0,
                width=56.0,
                height=103.0,
                fill="#ffffff",
                stroke="#3aa6df",
                stroke_width=2.0,
                rx=10.0,
                ry=10.0,
            ),
            RectSlot(
                id="slot.bottle.water.cap",
                prompt="",
                x=368.0,
                y=106.0,
                width=24.0,
                height=18.0,
                fill="#5fc0e8",
                stroke="#3aa6df",
                stroke_width=2.0,
                rx=4.0,
                ry=4.0,
            ),
            TextSlot(
                id="slot.bottle.water.label",
                prompt="",
                text="",
                style_role="diagram",
                x=0.0,
                y=0.0,
                font_size=28,
            ),
            LineSlot(
                id="slot.bottle.water.neck",
                prompt="",
                x1=375.0,
                y1=124.0,
                x2=375.0,
                y2=146.0,
                stroke="#3aa6df",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.bottle.water.rings1",
                prompt="",
                x1=353.0,
                y1=136.0,
                x2=407.0,
                y2=136.0,
                stroke="#3aa6df",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.bottle.water.rings2",
                prompt="",
                x1=353.0,
                y1=145.0,
                x2=407.0,
                y2=145.0,
                stroke="#3aa6df",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.bottle.water.rings3",
                prompt="",
                x1=353.0,
                y1=154.0,
                x2=407.0,
                y2=154.0,
                stroke="#3aa6df",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.bottle.water.rings4",
                prompt="",
                x1=353.0,
                y1=163.0,
                x2=407.0,
                y2=163.0,
                stroke="#3aa6df",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.bottle.water.rings5",
                prompt="",
                x1=353.0,
                y1=172.0,
                x2=407.0,
                y2=172.0,
                stroke="#3aa6df",
                stroke_width=1.4,
            ),
            RectSlot(
                id="slot.bottle.soy.body",
                prompt="",
                x=580.0,
                y=104.0,
                width=64.0,
                height=127.0,
                fill="#7b4a26",
                stroke="#7b4a26",
                stroke_width=2.0,
                rx=18.0,
                ry=18.0,
            ),
            RectSlot(
                id="slot.bottle.soy.cap1",
                prompt="",
                x=598.0,
                y=74.0,
                width=28.0,
                height=18.0,
                fill="#f07b5c",
                stroke="#f07b5c",
                stroke_width=2.0,
                rx=4.0,
                ry=4.0,
            ),
            RectSlot(
                id="slot.bottle.soy.cap2",
                prompt="",
                x=600.0,
                y=60.0,
                width=24.0,
                height=16.0,
                fill="#f59a73",
                stroke="#f59a73",
                stroke_width=2.0,
                rx=4.0,
                ry=4.0,
            ),
            LineSlot(
                id="slot.bottle.soy.handle",
                prompt="",
                x1=635.0,
                y1=85.0,
                x2=635.0,
                y2=142.0,
                stroke="#ce4c3a",
                stroke_width=6.0,
            ),
            RectSlot(
                id="slot.bottle.soy.label",
                prompt="",
                x=584.0,
                y=165.0,
                width=56.0,
                height=44.0,
                fill="#f2efe7",
                stroke="#f2efe7",
                stroke_width=1.0,
                rx=4.0,
                ry=4.0,
            ),
            LineSlot(
                id="slot.bottle.soy.spout",
                prompt="",
                x1=613.0,
                y1=92.0,
                x2=622.0,
                y2=92.0,
                stroke="#ce4c3a",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.bottle.soy.base",
                prompt="",
                x1=591.0,
                y1=231.0,
                x2=633.0,
                y2=231.0,
                stroke="#7b4a26",
                stroke_width=2.0,
            ),
            TextSlot(
                id="slot.diag.water_name",
                prompt="",
                text="생수병",
                style_role="label",
                x=352.0,
                y=271.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.diag.water_volume",
                prompt="",
                text="500 mL",
                style_role="label",
                x=339.0,
                y=313.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.diag.soy_name",
                prompt="",
                text="간장병",
                style_role="label",
                x=584.0,
                y=271.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice1.text",
                prompt="",
                text="간장병의 들이는 500 mL 생수병의 들이보다 ( 많습니다 , 적습니다 ).",
                style_role="question",
                x=68.0,
                y=401.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice2.arrow",
                prompt="",
                text="→",
                style_role="question",
                x=214.0,
                y=445.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice2.text",
                prompt="",
                text="간장병의 들이는 약 ( 2 mL , 2 L )입니다.",
                style_role="question",
                x=246.0,
                y=442.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008757",
    "problem_type": "들이_비교와_어림",
    "metadata": {
        "language": "ko",
        "question": "500 mL 생수병을 기준으로 간장병의 들이를 비교하고 알맞게 어림하는 문제",
        "instruction": "알맞은 것을 선택하세요.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.water_bottle",
                "type": "container",
                "name": "생수병",
                "capacity_unit": "mL",
                "capacity_value": 500,
            },
            {"id": "obj.soy_bottle", "type": "container", "name": "간장병"},
        ],
        "relations": [],
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_selection",
            "description": "간장병의 들이 비교 결과와 어림한 단위를 고른다",
        },
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008757",
    "problem_type": "들이_비교와_어림",
    "inputs": {
        "total_ticks": 0,
        "target_label": "간장병의 들이와 500 mL 생수병의 들이 비교",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "mL/L",
    },
    "given": [
        {
            "ref": "obj.water_bottle",
            "value": {"name": "생수병", "capacity_value": 500, "capacity_unit": "mL"},
        },
        {"ref": "obj.soy_bottle", "value": {"name": "간장병"}},
    ],
    "target": {"ref": "answer.target", "type": "choice_selection"},
    "method": "compare_and_estimate",
    "plan": [
        "간장병의 들이가 500 mL 생수병보다 큰지 작은지를 읽는다.",
        "비교 결과에 맞는 문장을 고르고, 어림한 단위를 선택한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "간장병의 들이 ? 500 mL 생수병의 들이",
            "value": "more",
        },
        {
            "id": "step.2",
            "expr": "선택지 비교: (많습니다, 적습니다)",
            "value": "많습니다",
        },
        {"id": "step.3", "expr": "선택지 비교: (2 mL, 2 L)", "value": "2 L"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "비교 결과가 500 mL보다 큼과 일치하는가",
            "expected": "more",
            "actual": "more",
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "어림 단위가 큰 들이에 맞는가",
            "expected": "2 L",
            "actual": "2 L",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_selection",
            "description": "간장병의 들이 비교 결과와 어림한 단위를 고른다",
        },
        "value": 2,
        "unit": "",
    },
}
