from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008932",
        title="밭별 수박 생산량",
        canvas=Canvas(width=960, height=552, coordinate_mode="logical"),
        regions=(
            Region(id="region.stem", role="stem", flow="absolute", slot_ids=("slot.q1", "slot.q2")),
            Region(id="region.title", role="title", flow="absolute", slot_ids=("slot.title",)),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.table.outer",
                    "slot.table.vline",
                    "slot.table.hline1",
                    "slot.table.hline2",
                    "slot.table.hline3",
                    "slot.table.hline4",
                    "slot.table.head.left",
                    "slot.table.head.right",
                    "slot.row.ga",
                    "slot.row.na",
                    "slot.row.da",
                    "slot.lbl.ga",
                    "slot.lbl.na",
                    "slot.lbl.da",
                    "slot.wm1",
                    "slot.wm2",
                    "slot.wm3",
                    "slot.wm4",
                    "slot.wm5",
                    "slot.wm6",
                    "slot.wm7",
                    "slot.wm8",
                    "slot.wm9",
                    "slot.wm10",
                    "slot.wm11",
                    "slot.wm12",
                    "slot.wm13",
                    "slot.wm14",
                    "slot.wm15",
                    "slot.wm16",
                ),
            ),
            Region(
                id="region.legend",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.legend.big",
                    "slot.legend.big.label",
                    "slot.legend.small",
                    "slot.legend.small.label",
                ),
            ),
            Region(id="region.choices", role="body", flow="absolute", slot_ids=("slot.choice",)),
            Region(id="region.answer", role="body", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="100. 밭별 수박 생산량을 조사하여 그림그래프로 나타내었습니다. 수박 생산량이",
                style_role="question",
                x=16.0,
                y=30.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="가장 많은 밭을 선택해 보세요.",
                style_role="question",
                x=16.0,
                y=66.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.title",
                prompt="",
                text="밭별 수박 생산량",
                style_role="title",
                x=380.0,
                y=108.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=222.0,
                y=122.0,
                width=532.0,
                height=204.0,
                fill="#EFF6DF",
                stroke="#8FCB58",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.table.head.left",
                prompt="",
                x=222.0,
                y=122.0,
                width=86.0,
                height=39.0,
                fill="#EFF6DF",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.head.right",
                prompt="",
                x=308.0,
                y=122.0,
                width=446.0,
                height=39.0,
                fill="#EFF6DF",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.row.ga",
                prompt="",
                x=222.0,
                y=161.0,
                width=532.0,
                height=61.0,
                fill="#FFFFFF",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.row.na",
                prompt="",
                x=222.0,
                y=222.0,
                width=532.0,
                height=61.0,
                fill="#FFFFFF",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.row.da",
                prompt="",
                x=222.0,
                y=283.0,
                width=532.0,
                height=43.0,
                fill="#FFFFFF",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.vline",
                prompt="",
                x=308.0,
                y=122.0,
                width=0.0,
                height=204.0,
                fill="none",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.hline1",
                prompt="",
                x=222.0,
                y=161.0,
                width=532.0,
                height=0.0,
                fill="none",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.hline2",
                prompt="",
                x=222.0,
                y=222.0,
                width=532.0,
                height=0.0,
                fill="none",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.hline3",
                prompt="",
                x=222.0,
                y=283.0,
                width=532.0,
                height=0.0,
                fill="none",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.hline4",
                prompt="",
                x=222.0,
                y=326.0,
                width=532.0,
                height=0.0,
                fill="none",
                stroke="#8FCB58",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.lbl.ga",
                prompt="",
                text="밭",
                style_role="body",
                x=254.0,
                y=148.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.na",
                prompt="",
                text="수박 생산량",
                style_role="body",
                x=496.0,
                y=148.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lbl.da",
                prompt="",
                text="가",
                style_role="body",
                x=259.0,
                y=205.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.wm1",
                prompt="",
                text="나",
                style_role="body",
                x=259.0,
                y=266.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.wm2",
                prompt="",
                text="다",
                style_role="body",
                x=259.0,
                y=307.0,
                font_size=28,
            ),
            CircleSlot(id="slot.wm3", prompt="", cx=360.0, cy=192.0, r=20.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm4", prompt="", cx=400.0, cy=192.0, r=20.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm5", prompt="", cx=438.0, cy=192.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm6", prompt="", cx=470.0, cy=192.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm7", prompt="", cx=500.0, cy=192.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm8", prompt="", cx=360.0, cy=253.0, r=20.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm9", prompt="", cx=400.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm10", prompt="", cx=432.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm11", prompt="", cx=464.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm12", prompt="", cx=496.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm13", prompt="", cx=528.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm14", prompt="", cx=560.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm15", prompt="", cx=592.0, cy=253.0, r=13.0, fill="#8BC34A"),
            CircleSlot(id="slot.wm16", prompt="", cx=360.0, cy=304.0, r=20.0, fill="#8BC34A"),
            CircleSlot(id="slot.legend.big", prompt="", cx=556.0, cy=360.0, r=19.0, fill="#8BC34A"),
            TextSlot(
                id="slot.legend.big.label",
                prompt="",
                text="100통",
                style_role="body",
                x=586.0,
                y=368.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.legend.small", prompt="", cx=662.0, cy=360.0, r=13.0, fill="#8BC34A"
            ),
            TextSlot(
                id="slot.legend.small.label",
                prompt="",
                text="10통",
                style_role="body",
                x=688.0,
                y=368.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 가 밭, 나 밭, 다 밭 )",
                style_role="body",
                x=680.0,
                y=406.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("그림그래프", "비교", "수박생산량"),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008932",
    "problem_type": "그림그래프_비교",
    "metadata": {
        "language": "ko",
        "question": "밭별 수박 생산량을 조사하여 그림그래프로 나타내었습니다. 수박 생산량이 가장 많은 밭을 선택해 보세요.",
        "instruction": "가, 나, 다 중에서 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.field.ga", "type": "field", "label": "가"},
            {"id": "obj.field.na", "type": "field", "label": "나"},
            {"id": "obj.field.da", "type": "field", "label": "다"},
            {"id": "obj.legend.big", "type": "legend_unit", "label": "100통"},
            {"id": "obj.legend.small", "type": "legend_unit", "label": "10통"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.field.ga",
                    "obj.field.na",
                    "obj.field.da",
                    "obj.legend.big",
                    "obj.legend.small",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare.production", "rel.compare.production.2"],
            },
            "plan": {
                "method": "picture_graph_compare",
                "description": "그림의 크기와 개수를 비교하여 수박 생산량이 가장 많은 밭을 찾는다.",
            },
            "execute": {"expected_operations": ["count_and_compare_symbols"]},
            "review": {"check_methods": ["largest_symbol_group"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "field_name", "description": "수박 생산량이 가장 많은 밭"},
        "value": "다 밭",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008932",
    "problem_type": "그림그래프_비교",
    "inputs": {
        "total_ticks": 0,
        "target_label": "수박 생산량이 가장 많은 밭",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "",
    },
    "given": [
        {"ref": "obj.field.ga", "value": {"label": "가"}},
        {"ref": "obj.field.na", "value": {"label": "나"}},
        {"ref": "obj.field.da", "value": {"label": "다"}},
        {"ref": "obj.legend.big", "value": {"label": "100통"}},
        {"ref": "obj.legend.small", "value": {"label": "10통"}},
    ],
    "target": {"ref": "answer.target", "type": "field_name"},
    "method": "picture_graph_compare",
    "plan": [
        "각 밭의 수박 그림을 비교하여 가장 많은 밭을 찾는다.",
        "큰 그림과 작은 그림의 개수를 함께 본다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "그림그래프에서 각 밭의 수박 그림 수를 비교한다.",
            "value": "다 밭",
        }
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "가, 나, 다 중 가장 많은 밭이 다인지 확인한다.",
            "expected": "다 밭",
            "actual": "다 밭",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "field_name", "description": "수박 생산량이 가장 많은 밭"},
        "value": "다 밭",
        "unit": "",
    },
}
