from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008746",
        title="물병과 컵 비교",
        canvas=Canvas(width=944.0, height=436.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                    "slot.q5",
                    "slot.q6",
                    "slot.q7",
                    "slot.q8",
                    "slot.q9",
                    "slot.q10",
                    "slot.q11",
                    "slot.q12",
                    "slot.q13",
                    "slot.q14",
                    "slot.q15",
                    "slot.q16",
                    "slot.q17",
                    "slot.q18",
                    "slot.q19",
                    "slot.q20",
                    "slot.q21",
                    "slot.q22",
                    "slot.q23",
                    "slot.q24",
                    "slot.q25",
                    "slot.q26",
                    "slot.q27",
                    "slot.q28",
                    "slot.q29",
                    "slot.q30",
                    "slot.q31",
                    "slot.q32",
                    "slot.q33",
                    "slot.q34",
                    "slot.q35",
                    "slot.q37",
                    "slot.q39",
                    "slot.q40",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="□ 43.",
                style_role="question",
                x=14.0,
                y=25.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="두 물병에 물을 가득 채운 후 모양과 크기가 같은 컵에 각각 옮겨 담았습니다. 바르게 설명했으면 ○표, 그렇지 않으면 ×표를 선택하세요.",
                style_role="question",
                x=63.0,
                y=28.0,
                font_size=28,
            ),
            RectSlot(id="slot.q3", prompt="", x=119.0, y=90.0, width=27.0, height=112.0),
            RectSlot(id="slot.q4", prompt="", x=119.0, y=90.0, width=27.0, height=112.0),
            CircleSlot(id="slot.q5", prompt="", cx=132.5, cy=90.0, r=13.0, fill="#FFFFFF"),
            LineSlot(id="slot.q6", prompt="", x1=119.0, y1=90.0, x2=146.0, y2=90.0),
            TextSlot(
                id="slot.q7",
                prompt="",
                text="가",
                style_role="label",
                x=124.0,
                y=162.0,
                font_size=28,
            ),
            LineSlot(id="slot.q8", prompt="", x1=159.0, y1=143.0, x2=191.0, y2=143.0),
            LineSlot(id="slot.q9", prompt="", x1=191.0, y1=143.0, x2=203.0, y2=143.0),
            LineSlot(id="slot.q10", prompt="", x1=159.0, y1=143.0, x2=203.0, y2=143.0),
            RectSlot(id="slot.q11", prompt="", x=214.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q12", prompt="", x=242.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q13", prompt="", x=270.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q14", prompt="", x=298.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q15", prompt="", x=326.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q16", prompt="", x=514.0, y=88.0, width=27.0, height=112.0),
            RectSlot(id="slot.q17", prompt="", x=514.0, y=88.0, width=27.0, height=112.0),
            CircleSlot(id="slot.q18", prompt="", cx=527.5, cy=88.0, r=13.0, fill="#FFFFFF"),
            LineSlot(id="slot.q19", prompt="", x1=514.0, y1=88.0, x2=541.0, y2=88.0),
            TextSlot(
                id="slot.q20",
                prompt="",
                text="나",
                style_role="label",
                x=519.0,
                y=160.0,
                font_size=28,
            ),
            LineSlot(id="slot.q21", prompt="", x1=555.0, y1=141.0, x2=587.0, y2=141.0),
            LineSlot(id="slot.q22", prompt="", x1=587.0, y1=141.0, x2=599.0, y2=141.0),
            LineSlot(id="slot.q23", prompt="", x1=555.0, y1=141.0, x2=599.0, y2=141.0),
            RectSlot(id="slot.q24", prompt="", x=507.0, y=85.0, width=44.0, height=6.0),
            RectSlot(id="slot.q25", prompt="", x=519.0, y=84.0, width=19.0, height=10.0),
            RectSlot(id="slot.q26", prompt="", x=543.0, y=86.0, width=10.0, height=39.0),
            RectSlot(id="slot.q27", prompt="", x=619.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q28", prompt="", x=647.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q29", prompt="", x=675.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q30", prompt="", x=703.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q31", prompt="", x=731.0, y=108.0, width=22.0, height=30.0),
            RectSlot(id="slot.q32", prompt="", x=759.0, y=108.0, width=22.0, height=30.0),
            TextSlot(
                id="slot.q33",
                prompt="",
                text="나 물병이 컵 1개만큼 물이 더 들어갑니다.",
                style_role="question",
                x=237.0,
                y=235.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q34",
                prompt="",
                text="○",
                style_role="choice",
                x=33.0,
                y=265.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q35",
                prompt="",
                text="×",
                style_role="choice",
                x=33.0,
                y=294.0,
                font_size=28,
            ),
            CircleSlot(id="slot.q37", prompt="", cx=73.0, cy=332.0, r=10.0, fill="#FFFFFF"),
            TextSlot(
                id="slot.q39",
                prompt="",
                text="→",
                style_role="question",
                x=18.0,
                y=410.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q40",
                prompt="",
                text="나 물병이 가 물병보다 컵 6 - 5 = 1(개)만큼 물이 더 들어갑니다.",
                style_role="question",
                x=69.0,
                y=411.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008746",
    "problem_type": "true_false_comparison",
    "metadata": {
        "language": "ko",
        "question": "두 물병의 물의 양을 컵 개수로 비교한 설명이 맞는지 판단하는 문제",
        "instruction": "바르게 설명했으면 ○표, 그렇지 않으면 ×표를 선택",
    },
    "domain": {
        "objects": [
            {"id": "obj.bottle_a", "type": "bottle", "label": "가"},
            {"id": "obj.bottle_b", "type": "bottle", "label": "나"},
            {"id": "obj.cup_unit", "type": "cup", "unit_role": "comparison_unit"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.bottle_a", "obj.bottle_b", "obj.cup_unit"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.count_a", "rel.count_b", "rel.compare"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "두 물병의 컵 개수를 비교하여 차이를 확인한다.",
            },
            "execute": {
                "expected_operations": ["read_counts", "subtract_counts", "compare_statement"]
            },
            "review": {"check_methods": ["difference_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "truth_value_selection", "description": "설명의 옳고 그름에 대한 선택"},
        "value": 1,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008746",
    "problem_type": "true_false_comparison",
    "inputs": {
        "total_ticks": 0,
        "target_label": "truth_value_selection",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "개",
    },
    "given": [
        {"ref": "obj.bottle_a", "value": {"label": "가", "cups": 5}},
        {"ref": "obj.bottle_b", "value": {"label": "나", "cups": 6}},
    ],
    "target": {"ref": "answer.target", "type": "truth_value_selection"},
    "plan": [
        "두 물병이 나타내는 컵 개수를 읽는다.",
        "두 수의 차이를 구해 설명 문장과 맞는지 확인한다.",
    ],
    "method": "compare_counts",
    "steps": [
        {"id": "step.1", "expr": "6 - 5", "value": 1},
        {"id": "step.2", "expr": "나 물병 - 가 물병 = 1", "value": 1},
    ],
    "checks": [{"id": "check.1", "expr": "6 - 5 = 1", "expected": 1, "actual": 1, "pass": True}],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "truth_value_selection", "description": "설명의 옳고 그름에 대한 선택"},
        "value": 1,
        "unit": "",
    },
}
