from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, LineSlot, CircleSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009016', title='직선을 선택하세요', canvas=Canvas(width=720, height=268, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.title',)),), slots=(TextSlot(id='slot.title', prompt='', text='□ 54. 직선을 선택하세요.', style_role='question', x=10.0, y=22.0, font_size=28), LineSlot(id='slot.shape.left.line1', prompt='', x1=107.0, y1=97.0, x2=210.0, y2=56.0), LineSlot(id='slot.shape.left.line2', prompt='', x1=210.0, y1=56.0, x2=283.0, y2=109.0), CircleSlot(id='slot.shape.left.dot1', prompt='', cx=145.0, cy=82.0, r=3.0, fill='#222222'), CircleSlot(id='slot.shape.left.dot2', prompt='', cx=250.0, cy=94.0, r=3.0, fill='#222222'), LineSlot(id='slot.shape.middle.line', prompt='', x1=371.0, y1=96.0, x2=516.0, y2=52.0), CircleSlot(id='slot.shape.middle.dot1', prompt='', cx=396.0, cy=88.0, r=3.0, fill='#222222'), CircleSlot(id='slot.shape.middle.dot2', prompt='', cx=476.0, cy=63.0, r=3.0, fill='#222222'), LineSlot(id='slot.shape.right.curve1', prompt='', x1=611.0, y1=58.0, x2=670.0, y2=48.0), LineSlot(id='slot.shape.right.curve2', prompt='', x1=670.0, y1=48.0, x2=696.0, y2=72.0), LineSlot(id='slot.shape.right.curve3', prompt='', x1=696.0, y1=72.0, x2=652.0, y2=92.0), LineSlot(id='slot.shape.right.curve4', prompt='', x1=652.0, y1=92.0, x2=611.0, y2=111.0), CircleSlot(id='slot.shape.right.dot1', prompt='', cx=698.0, cy=49.0, r=3.0, fill='#222222'), CircleSlot(id='slot.shape.right.dot2', prompt='', cx=612.0, cy=114.0, r=3.0, fill='#222222'), LineSlot(id='slot.answer.shape.line', prompt='', x1=45.0, y1=193.0, x2=145.0, y2=139.0), CircleSlot(id='slot.answer.shape.dot1', prompt='', cx=63.0, cy=184.0, r=3.0, fill='#222222'), CircleSlot(id='slot.answer.shape.dot2', prompt='', cx=127.0, cy=149.0, r=3.0, fill='#222222')), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009016', 'problem_type': 'shape_selection', 'metadata': {'language': 'ko', 'question': '직선을 선택하세요.', 'instruction': '보기 중 직선에 해당하는 그림을 고르는 문제'}, 'domain': {'objects': [{'id': 'obj.line.left', 'type': 'line_shape', 'kind': 'bent_line'}, {'id': 'obj.line.middle', 'type': 'line_shape', 'kind': 'straight_line'}, {'id': 'obj.line.right', 'type': 'line_shape', 'kind': 'curve'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.line.left', 'obj.line.middle', 'obj.line.right'], 'target_ref': 'answer.target', 'condition_refs': ['rel.select_straight']}, 'plan': {'method': 'shape_comparison', 'description': '보기의 선 모양을 비교하여 곧은 선인지 확인한다.'}, 'execute': {'expected_operations': ['compare_line_shapes', 'identify_straight_line']}, 'review': {'check_methods': ['definition_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selection', 'description': '직선'}, 'value': 2, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009016', 'problem_type': 'shape_selection', 'inputs': {'total_ticks': 3, 'target_label': '직선', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.line.left', 'value': {'kind': 'bent_line'}}, {'ref': 'obj.line.middle', 'value': {'kind': 'straight_line'}}, {'ref': 'obj.line.right', 'value': {'kind': 'curve'}}], 'target': {'ref': 'answer.target', 'type': 'selection'}, 'method': 'shape_comparison', 'plan': ['보기의 선 모양을 비교한다.', '직선의 정의에 맞는 곧은 선을 찾는다.'], 'steps': [{'id': 'step.1', 'expr': '왼쪽 그림은 꺾인 선이다.', 'value': 'bent_line'}, {'id': 'step.2', 'expr': '가운데 그림은 곧은 선이다.', 'value': 'straight_line'}, {'id': 'step.3', 'expr': '오른쪽 그림은 곡선이다.', 'value': 'curve'}, {'id': 'step.4', 'expr': '직선에 해당하는 그림을 선택한다.', 'value': '가운데 그림'}], 'checks': [{'id': 'check.1', 'expr': '직선의 정의에 맞는가', 'expected': 'straight_line', 'actual': 'straight_line', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selection', 'description': '직선'}, 'value': 2, 'unit': ''}}
