from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008737",
        title="털실 길이 비교",
        canvas=Canvas(width=960, height=540, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.top",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2", "slot.q3", "slot.q4"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.len1.label",
                    "slot.len1.axis",
                    "slot.len1.grid0",
                    "slot.len1.grid1",
                    "slot.len1.grid2",
                    "slot.len1.grid3",
                    "slot.len1.grid4",
                    "slot.len1.grid5",
                    "slot.len1.grid6",
                    "slot.len1.grid7",
                    "slot.len1.grid8",
                    "slot.len1.grid9",
                    "slot.len1.grid10",
                    "slot.len1.blue",
                    "slot.len1.zero",
                    "slot.len1.one",
                    "slot.len1.two",
                    "slot.len1.seven_over_seven",
                    "slot.len2.label",
                    "slot.len2.axis",
                    "slot.len2.grid0",
                    "slot.len2.grid1",
                    "slot.len2.grid2",
                    "slot.len2.grid3",
                    "slot.len2.grid4",
                    "slot.len2.grid5",
                    "slot.len2.grid6",
                    "slot.len2.grid7",
                    "slot.len2.grid8",
                    "slot.len2.grid9",
                    "slot.len2.grid10",
                    "slot.len2.blue",
                    "slot.len2.zero",
                    "slot.len2.one",
                    "slot.len2.two",
                    "slot.len2.seven_over_seven",
                    "slot.compare",
                    "slot.bottom_partial",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="재영이는 노란색 털실을 9/7 m 가지고 있고 보라색 털실을 1 3/7 m 가지고",
                style_role="question",
                x=32,
                y=49,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="있습니다. 더 긴 털실은 무슨 색인지 알아보려고 합니다. 물음에 답하세요.",
                style_role="question",
                x=30,
                y=87,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="(1) 수직선을 보고, 더 큰 수를 선택해 보세요.",
                style_role="question",
                x=30,
                y=137,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="(1) 수직선에 나타난 부분을 비교하면 9/7 < 1 3/7 입니다.",
                style_role="question",
                x=0.0,
                y=466.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len1.label",
                prompt="",
                text="9/7 m",
                style_role="label",
                x=177.91995239257812,
                y=220.84005737304688,
                font_size=30,
                fill="#111111",
            ),
            LineSlot(id="slot.len1.axis", prompt="", x1=284.0, y1=211.0, x2=748.0, y2=211.0),
            LineSlot(id="slot.len1.grid0", prompt="", x1=284.0, y1=202.0, x2=284.0, y2=220.0),
            LineSlot(id="slot.len1.grid1", prompt="", x1=330.4, y1=204.0, x2=330.4, y2=218.0),
            LineSlot(id="slot.len1.grid2", prompt="", x1=376.8, y1=204.0, x2=376.8, y2=218.0),
            LineSlot(id="slot.len1.grid3", prompt="", x1=423.2, y1=204.0, x2=423.2, y2=218.0),
            LineSlot(id="slot.len1.grid4", prompt="", x1=469.6, y1=204.0, x2=469.6, y2=218.0),
            LineSlot(id="slot.len1.grid5", prompt="", x1=516.0, y1=202.0, x2=516.0, y2=220.0),
            LineSlot(id="slot.len1.grid6", prompt="", x1=562.4, y1=204.0, x2=562.4, y2=218.0),
            LineSlot(id="slot.len1.grid7", prompt="", x1=608.8, y1=204.0, x2=608.8, y2=218.0),
            LineSlot(id="slot.len1.grid8", prompt="", x1=655.2, y1=204.0, x2=655.2, y2=218.0),
            LineSlot(id="slot.len1.grid9", prompt="", x1=701.6, y1=204.0, x2=701.6, y2=218.0),
            LineSlot(id="slot.len1.grid10", prompt="", x1=748.0, y1=202.0, x2=748.0, y2=220.0),
            LineSlot(id="slot.len1.blue", prompt="", x1=284.0, y1=211.0, x2=586.0, y2=211.0),
            TextSlot(
                id="slot.len1.zero",
                prompt="",
                text="0",
                style_role="label",
                x=278.0,
                y=245.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len1.one",
                prompt="",
                text="1",
                style_role="label",
                x=510.0,
                y=245.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len1.two",
                prompt="",
                text="2(m)",
                style_role="label",
                x=734.0,
                y=245.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len1.seven_over_seven",
                prompt="",
                text="7/7",
                style_role="label",
                x=500.0,
                y=190.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len2.label",
                prompt="",
                text="1 3/7 m",
                style_role="label",
                x=166,
                y=326,
                font_size=28,
                fill="#111111",
            ),
            LineSlot(id="slot.len2.axis", prompt="", x1=284.0, y1=311.0, x2=748.0, y2=311.0),
            LineSlot(id="slot.len2.grid0", prompt="", x1=284.0, y1=302.0, x2=284.0, y2=320.0),
            LineSlot(id="slot.len2.grid1", prompt="", x1=330.4, y1=304.0, x2=330.4, y2=318.0),
            LineSlot(id="slot.len2.grid2", prompt="", x1=376.8, y1=304.0, x2=376.8, y2=318.0),
            LineSlot(id="slot.len2.grid3", prompt="", x1=423.2, y1=304.0, x2=423.2, y2=318.0),
            LineSlot(id="slot.len2.grid4", prompt="", x1=469.6, y1=304.0, x2=469.6, y2=318.0),
            LineSlot(id="slot.len2.grid5", prompt="", x1=516.0, y1=302.0, x2=516.0, y2=320.0),
            LineSlot(id="slot.len2.grid6", prompt="", x1=562.4, y1=304.0, x2=562.4, y2=318.0),
            LineSlot(id="slot.len2.grid7", prompt="", x1=608.8, y1=304.0, x2=608.8, y2=318.0),
            LineSlot(id="slot.len2.grid8", prompt="", x1=655.2, y1=304.0, x2=655.2, y2=318.0),
            LineSlot(id="slot.len2.grid9", prompt="", x1=701.6, y1=304.0, x2=701.6, y2=318.0),
            LineSlot(id="slot.len2.grid10", prompt="", x1=748.0, y1=302.0, x2=748.0, y2=320.0),
            LineSlot(id="slot.len2.blue", prompt="", x1=284.0, y1=311.0, x2=611.0, y2=311.0),
            TextSlot(
                id="slot.len2.zero",
                prompt="",
                text="0",
                style_role="label",
                x=278.0,
                y=345.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len2.one",
                prompt="",
                text="1",
                style_role="label",
                x=510.0,
                y=345.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len2.two",
                prompt="",
                text="2(m)",
                style_role="label",
                x=734.0,
                y=345.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.len2.seven_over_seven",
                prompt="",
                text="7/7",
                style_role="label",
                x=500.0,
                y=290.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.compare",
                prompt="",
                text="( 9/7 , 1 3/7 )",
                style_role="label",
                x=416.0,
                y=392.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.bottom_partial",
                prompt="",
                text="(1) 1 3/7",
                style_role="question",
                x=0.0,
                y=520.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008737",
    "problem_type": "fraction_comparison",
    "metadata": {
        "language": "ko",
        "question": "두 털실의 길이를 수직선으로 비교하여 더 큰 수를 찾는 문제",
        "instruction": "수직선을 보고 더 큰 수를 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.yellow_yarn", "type": "length", "value": "9/7 m", "color": "노란색"},
            {"id": "obj.purple_yarn", "type": "length", "value": "1 3/7 m", "color": "보라색"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.yellow_yarn", "obj.purple_yarn"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_lengths"],
            },
            "plan": {
                "method": "number_line_comparison",
                "description": "수직선에서 두 길이의 위치를 비교한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_positions_on_number_line",
                    "identify_larger_length",
                ]
            },
            "review": {"check_methods": ["position_order_check", "unit_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "larger_length_color", "description": "더 긴 털실의 색"},
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008737",
    "problem_type": "fraction_comparison",
    "inputs": {
        "total_ticks": 14,
        "target_label": "더 긴 털실의 색",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "m",
    },
    "given": [
        {"ref": "obj.yellow_yarn", "value": "9/7 m"},
        {"ref": "obj.purple_yarn", "value": "1 3/7 m"},
    ],
    "target": {"ref": "answer.target", "type": "larger_length_color"},
    "method": "number_line_comparison",
    "plan": ["수직선에서 두 수의 위치를 비교한다.", "더 오른쪽에 있는 수가 더 크다."],
    "steps": [
        {"id": "step.1", "expr": "9/7과 1 3/7의 위치를 수직선에서 비교한다", "value": 0},
        {"id": "step.2", "expr": "9/7 < 1 3/7", "value": 1},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "수직선 비교 결과가 더 큰 수를 오른쪽 값으로 선택하는지 확인",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "larger_length_color", "description": "더 긴 털실의 색"},
        "value": 0,
        "unit": "",
    },
}
