from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009000', title='네 변의 길이가 모두 같은 사각형을 찾아 기호를 선택하세요', canvas=Canvas(width=820, height=340, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.num', 'slot.title')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.bg', 'slot.fig1', 'slot.fig2', 'slot.fig3', 'slot.fig4', 'slot.fig1.lb', 'slot.fig2.lb', 'slot.fig3.lb', 'slot.fig4.lb', 'slot.choice')), Region(id='region.footer', role='explanation', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.num', prompt='', text='38.', style_role='question', x=16.0, y=30.0, font_size=28), TextSlot(id='slot.title', prompt='', text='네 변의 길이가 모두 같은 사각형을 찾아 기호를 선택하세요.', style_role='question', x=54.0, y=30.0, font_size=28), RectSlot(id='slot.bg', prompt='', x=220.0, y=45.0, width=440.0, height=95.0), RectSlot(id='slot.fig1', prompt='', x=240.0, y=60.0, width=112.0, height=42.0), RectSlot(id='slot.fig2', prompt='', x=364.0, y=86.0, width=94.0, height=80.0), RectSlot(id='slot.fig3', prompt='', x=488.0, y=56.0, width=42.0, height=95.0), RectSlot(id='slot.fig4', prompt='', x=570.0, y=56.0, width=78.0, height=95.0), TextSlot(id='slot.fig1.lb', prompt='', text='가', style_role='label', x=286.0, y=88.0, font_size=28), TextSlot(id='slot.fig2.lb', prompt='', text='나', style_role='label', x=404.0, y=128.0, font_size=28), TextSlot(id='slot.fig3.lb', prompt='', text='다', style_role='label', x=501.0, y=104.0, font_size=28), TextSlot(id='slot.fig4.lb', prompt='', text='라', style_role='label', x=603.0, y=104.0, font_size=28), TextSlot(id='slot.choice', prompt='', text='( 가, 나, 다, 라 )', style_role='question', x=285.0, y=172.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009000', 'problem_type': '도형_성질_선택', 'metadata': {'language': 'ko', 'question': '네 변의 길이가 모두 같은 사각형을 찾아 기호를 선택하는 문제', 'instruction': '보기에서 조건에 맞는 도형의 기호를 고른다.'}, 'domain': {'objects': [{'id': 'obj.shape.a', 'type': 'quadrilateral_candidate', 'label': '가'}, {'id': 'obj.shape.b', 'type': 'quadrilateral_candidate', 'label': '나'}, {'id': 'obj.shape.c', 'type': 'quadrilateral_candidate', 'label': '다'}, {'id': 'obj.shape.d', 'type': 'quadrilateral_candidate', 'label': '라'}, {'id': 'obj.target_property', 'type': 'shape_property', 'name': '네 변의 길이가 모두 같음'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.shape.a', 'obj.shape.b', 'obj.shape.c', 'obj.shape.d'], 'target_ref': 'answer.target', 'condition_refs': ['obj.target_property']}, 'plan': {'method': 'shape_property_selection', 'description': '보기의 사각형들 중 네 변의 길이가 모두 같은 도형을 찾는다.'}, 'execute': {'expected_operations': ['compare_side_properties', 'select_matching_label']}, 'review': {'check_methods': ['property_match_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'label_selection', 'description': '네 변의 길이가 모두 같은 사각형의 기호'}, 'value': 1, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009000', 'problem_type': '도형_성질_선택', 'inputs': {'total_ticks': 4, 'target_label': '나', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.shape.a', 'value': {'label': '가'}}, {'ref': 'obj.shape.b', 'value': {'label': '나'}}, {'ref': 'obj.shape.c', 'value': {'label': '다'}}, {'ref': 'obj.shape.d', 'value': {'label': '라'}}], 'target': {'ref': 'answer.target', 'type': 'label_selection'}, 'method': 'shape_property_selection', 'plan': ['보기의 도형들을 살펴서 네 변의 길이가 모두 같은 도형을 찾는다.', '해당 도형에 붙은 기호를 답으로 고른다.'], 'steps': [{'id': 'step.1', 'expr': '가, 나, 다, 라 중 조건에 맞는 도형 찾기', 'value': '나'}], 'checks': [{'id': 'check.1', 'expr': '네 변의 길이가 모두 같은 사각형인지 확인', 'expected': '나', 'actual': '나', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'label_selection', 'description': '네 변의 길이가 모두 같은 사각형의 기호'}, 'value': 1, 'unit': ''}}
