from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, CircleSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008715', title='원에서 반지름을 나타내는 선분을 선택하시오', canvas=Canvas(width=960, height=360, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1',)), Region(id='region.figure', role='diagram', flow='absolute', slot_ids=('slot.circle', 'slot.seg_gs', 'slot.seg_nr', 'slot.seg_do', 'slot.seg_bm', 'slot.pt.o', 'slot.pt.g', 'slot.pt.s', 'slot.pt.n', 'slot.pt.r', 'slot.pt.d', 'slot.pt.m', 'slot.pt.b', 'slot.lb.g', 'slot.lb.s', 'slot.lb.n', 'slot.lb.r', 'slot.lb.d', 'slot.lb.m', 'slot.lb.b')), Region(id='region.choices', role='choices', flow='absolute', slot_ids=('slot.choices',)), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='□ 15.  원에서 반지름을 나타내는 선분을 선택하시오.', style_role='question', x=18.0, y=30.0, font_size=28), RectSlot(id='slot.circle', prompt='', x=476.0, y=52.0, width=150.0, height=150.0), LineSlot(id='slot.seg_gs', prompt='', x1=486.0, y1=74.0, x2=555.0, y2=52.0), LineSlot(id='slot.seg_nr', prompt='', x1=505.0, y1=106.0, x2=539.0, y2=181.0), LineSlot(id='slot.seg_do', prompt='', x1=520.0, y1=181.0, x2=539.0, y2=118.0), LineSlot(id='slot.seg_bm', prompt='', x1=554.0, y1=52.0, x2=534.0, y2=181.0), CircleSlot(id='slot.pt.o', prompt='', cx=518.0, cy=120.0, r=3.5, fill='#d81b60'), CircleSlot(id='slot.pt.g', prompt='', cx=487.0, cy=76.0, r=3.5, fill='#222222'), CircleSlot(id='slot.pt.s', prompt='', cx=551.0, cy=54.0, r=3.5, fill='#222222'), CircleSlot(id='slot.pt.n', prompt='', cx=481.0, cy=110.0, r=3.5, fill='#222222'), CircleSlot(id='slot.pt.r', prompt='', cx=515.0, cy=181.0, r=3.5, fill='#222222'), CircleSlot(id='slot.pt.d', prompt='', cx=530.0, cy=164.0, r=3.5, fill='#222222'), CircleSlot(id='slot.pt.m', prompt='', cx=565.0, cy=180.0, r=3.5, fill='#222222'), CircleSlot(id='slot.pt.b', prompt='', cx=566.0, cy=54.0, r=3.5, fill='#222222'), TextSlot(id='slot.lb.g', prompt='', text='ㄱ', style_role='label', x=468.0, y=82.0, font_size=28), TextSlot(id='slot.lb.s', prompt='', text='ㅅ', style_role='label', x=560.0, y=45.0, font_size=28), TextSlot(id='slot.lb.n', prompt='', text='ㄴ', style_role='label', x=460.0, y=118.0, font_size=28), TextSlot(id='slot.lb.r', prompt='', text='ㄹ', style_role='label', x=512.0, y=198.0, font_size=28), TextSlot(id='slot.lb.d', prompt='', text='ㄷ', style_role='label', x=523.0, y=186.0, font_size=28), TextSlot(id='slot.lb.m', prompt='', text='ㅁ', style_role='label', x=573.0, y=197.0, font_size=28), TextSlot(id='slot.lb.b', prompt='', text='ㅂ', style_role='label', x=568.0, y=45.0, font_size=28), TextSlot(id='slot.choices', prompt='', text='( 선분 ㄱㅅ , 선분 ㄴㄹ , 선분 ㄷㅇ , 선분 ㅂㅁ )', style_role='body', x=356.0, y=235.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008715', 'problem_type': 'geometry_circle_radius_choice', 'metadata': {'language': 'ko', 'question': '원에서 반지름을 나타내는 선분을 선택하시오.', 'instruction': '보기에서 반지름에 해당하는 선분을 고른다.'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.center.o', 'type': 'point', 'role': 'center', 'label': 'ㅇ'}, {'id': 'obj.radius_candidate.d_o', 'type': 'segment', 'label': '선분 ㄷㅇ'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle', 'obj.center.o', 'obj.radius_candidate.d_o'], 'target_ref': 'answer.target', 'condition_refs': ['rel.radius_definition']}, 'plan': {'method': 'definition_matching', 'description': '원의 중심과 원 위의 한 점을 이은 선분을 찾는다.'}, 'execute': {'expected_operations': ['identify_center', 'identify_point_on_circle', 'match_radius_definition']}, 'review': {'check_methods': ['definition_check', 'candidate_comparison']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_segment', 'description': '원의 반지름을 나타내는 선분'}, 'value': 1, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008715', 'problem_type': 'geometry_circle_radius_choice', 'inputs': {'total_ticks': 0, 'target_label': '선분 ㄷㅇ', 'target_ticks': 0, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': {'type': 'circle'}}, {'ref': 'obj.center.o', 'value': {'label': 'ㅇ', 'role': 'center'}}, {'ref': 'obj.radius_candidate.d_o', 'value': {'label': '선분 ㄷㅇ'}}], 'target': {'ref': 'answer.target', 'type': 'selected_segment'}, 'method': 'definition_matching', 'plan': ['원의 중심과 원 위의 한 점을 이은 선분을 찾는다.', '보기의 선분들 중 정의에 맞는 것을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '원의 중심과 원 위의 점을 잇는 선분 찾기', 'value': '선분 ㄷㅇ'}], 'checks': [{'id': 'check.1', 'expr': '선분 ㄷㅇ이 중심 ㅇ와 원 위의 점 ㄷ을 잇는가', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_segment', 'description': '원의 반지름을 나타내는 선분'}, 'value': 1, 'unit': ''}}
