from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_009048', title='알맞은 말을 선택하세요', canvas=Canvas(width=822, height=428, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.q1',)), Region(id='region.dialogue.left', role='body', flow='absolute', slot_ids=('slot.balloon.left', 'slot.balloon.left.text')), Region(id='region.dialogue.right', role='body', flow='absolute', slot_ids=('slot.balloon.right', 'slot.balloon.right.text')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=('slot.explain.arrow',))), slots=(TextSlot(id='slot.q1', prompt='', text='86. 알맞은 말을 선택하세요.', style_role='question', x=14.0, y=26.0, font_size=28), RectSlot(id='slot.balloon.left', prompt='', x=150.0, y=52.0, width=240.0, height=98.0), TextSlot(id='slot.balloon.left.text', prompt='', text='반직선 ㄱㄴ과 반직선 ㄴㄱ은\n모두 (곧은 선, 곡은 선)이야.', style_role='body', x=170.0, y=76.0, font_size=28), RectSlot(id='slot.balloon.right', prompt='', x=484.0, y=48.0, width=260.0, height=108.0), TextSlot(id='slot.balloon.right.text', prompt='', text='반직선 ㄱㄴ과 반직선 ㄴㄱ은\n끝없이 늘인 방향이 다르므로 같다고\n말할 수 (있어, 없어).', style_role='body', x=508.0, y=68.0, font_size=28), LineSlot(id='slot.explain.brace.top', prompt='', x1=336.0, y1=346.0, x2=336.0, y2=376.0), LineSlot(id='slot.explain.brace.bottom', prompt='', x1=336.0, y1=376.0, x2=336.0, y2=402.0), LineSlot(id='slot.explain.arrow', prompt='', x1=354.0, y1=374.0, x2=384.0, y2=374.0)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_009048', 'problem_type': '선택형', 'metadata': {'language': 'ko', 'question': '알맞은 말을 선택하세요.', 'instruction': '반직선 ㄱㄴ과 반직선 ㄴㄱ의 성질을 보고 알맞은 말을 고른다.'}, 'domain': {'objects': [{'id': 'obj.ray_gn', 'type': 'ray', 'name': '반직선 ㄱㄴ'}, {'id': 'obj.ray_ng', 'type': 'ray', 'name': '반직선 ㄴㄱ'}, {'id': 'obj.point_g', 'type': 'point', 'name': '점 ㄱ'}, {'id': 'obj.point_n', 'type': 'point', 'name': '점 ㄴ'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.ray_gn', 'obj.ray_ng', 'obj.point_g', 'obj.point_n'], 'target_ref': 'answer.target', 'condition_refs': ['rel.ray_gn.start', 'rel.ray_ng.start', 'rel.rays.not_equal']}, 'plan': {'method': 'compare_start_points', 'description': '두 반직선의 시작점을 비교하여 같은지 아닌지를 판단한다.'}, 'execute': {'expected_operations': ['identify_start_point', 'compare_direction_and_start_point', 'choose_correct_words']}, 'review': {'check_methods': ['check_start_point_difference', 'check_choice_consistency']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': '곧은 선, 없어'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_009048', 'problem_type': '선택형', 'inputs': {'total_ticks': 2, 'target_label': '알맞은 말', 'target_ticks': 2, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.ray_gn', 'value': {'name': '반직선 ㄱㄴ', 'start_point': '점 ㄱ'}}, {'ref': 'obj.ray_ng', 'value': {'name': '반직선 ㄴㄱ', 'start_point': '점 ㄴ'}}], 'target': {'ref': 'answer.target', 'type': 'choice_selection'}, 'method': 'compare_start_points', 'plan': ['두 반직선의 시작점을 확인한다.', '시작점이 다르므로 같은 반직선인지 판단한다.', '문장 속 괄호에 들어갈 알맞은 말을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '반직선 ㄱㄴ의 시작점 확인', 'value': '점 ㄱ'}, {'id': 'step.2', 'expr': '반직선 ㄴㄱ의 시작점 확인', 'value': '점 ㄴ'}, {'id': 'step.3', 'expr': '시작점 비교', 'value': '다름'}, {'id': 'step.4', 'expr': '정답 선택', 'value': '곧은 선, 없어'}], 'checks': [{'id': 'check.1', 'expr': '두 반직선의 시작점이 다른가', 'expected': True, 'actual': True, 'pass': True}, {'id': 'check.2', 'expr': '선택한 말이 해설과 일치하는가', 'expected': '곧은 선, 없어', 'actual': '곧은 선, 없어', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_selection', 'description': '곧은 선, 없어'}, 'value': 0, 'unit': ''}}
