from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, LineSlot, RectSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_009064",
        title="직사각형을 모두 선택하세요",
        canvas=Canvas(width=690.0, height=390.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.title",
                    "slot.shape.a",
                    "slot.shape.b",
                    "slot.shape.c",
                    "slot.shape.d",
                    "slot.shape.e",
                    "slot.label.a",
                    "slot.label.b",
                    "slot.label.c",
                    "slot.label.d",
                    "slot.label.e",
                    "slot.list",
                ),
            ),
            Region(
                id="region.explanation",
                role="explanation",
                flow="absolute",
                slot_ids=(
                    "slot.ex_shape.a",
                    "slot.ex_shape.b",
                    "slot.ex_shape.c",
                    "slot.ex_shape.d",
                    "slot.ex_shape.e",
                    "slot.ex_label.a",
                    "slot.ex_label.b",
                    "slot.ex_label.c",
                    "slot.ex_label.d",
                    "slot.ex_label.e",
                    "slot.corner.a1",
                    "slot.corner.a2",
                    "slot.corner.b1",
                    "slot.corner.b2",
                    "slot.corner.c1",
                    "slot.corner.c2",
                    "slot.corner.d1",
                    "slot.corner.d2",
                    "slot.corner.e1",
                    "slot.corner.e2",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.title",
                prompt="",
                text="4. 직사각형을 모두 선택하세요.",
                style_role="question",
                x=18.0,
                y=22.0,
                font_size=28,
            ),
            RectSlot(id="slot.shape.a", prompt="", x=116.0, y=54.0, width=70.0, height=48.0),
            RectSlot(id="slot.shape.b", prompt="", x=231.0, y=54.0, width=68.0, height=48.0),
            RectSlot(id="slot.shape.c", prompt="", x=318.0, y=54.0, width=38.0, height=48.0),
            RectSlot(id="slot.shape.d", prompt="", x=390.0, y=54.0, width=92.0, height=48.0),
            RectSlot(id="slot.shape.e", prompt="", x=528.0, y=54.0, width=70.0, height=48.0),
            TextSlot(
                id="slot.label.a",
                prompt="",
                text="가",
                style_role="label",
                x=139.0,
                y=84.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.b",
                prompt="",
                text="나",
                style_role="label",
                x=254.0,
                y=84.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.c",
                prompt="",
                text="다",
                style_role="label",
                x=331.0,
                y=84.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.d",
                prompt="",
                text="라",
                style_role="label",
                x=426.0,
                y=84.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.e",
                prompt="",
                text="마",
                style_role="label",
                x=550.0,
                y=84.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.list",
                prompt="",
                text="( 가 , 나 , 다 , 라 , 마 )",
                style_role="question",
                x=202.0,
                y=129.0,
                font_size=28,
            ),
            RectSlot(id="slot.ex_shape.a", prompt="", x=104.0, y=250.0, width=69.0, height=48.0),
            RectSlot(id="slot.ex_shape.b", prompt="", x=229.0, y=250.0, width=69.0, height=48.0),
            RectSlot(id="slot.ex_shape.c", prompt="", x=314.0, y=250.0, width=38.0, height=48.0),
            RectSlot(id="slot.ex_shape.d", prompt="", x=395.0, y=250.0, width=95.0, height=48.0),
            RectSlot(id="slot.ex_shape.e", prompt="", x=545.0, y=250.0, width=69.0, height=48.0),
            TextSlot(
                id="slot.ex_label.a",
                prompt="",
                text="가",
                style_role="label",
                x=130.0,
                y=280.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.ex_label.b",
                prompt="",
                text="나",
                style_role="label",
                x=254.0,
                y=280.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.ex_label.c",
                prompt="",
                text="다",
                style_role="label",
                x=331.0,
                y=280.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.ex_label.d",
                prompt="",
                text="라",
                style_role="label",
                x=428.0,
                y=280.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.ex_label.e",
                prompt="",
                text="마",
                style_role="label",
                x=568.0,
                y=280.0,
                font_size=28,
            ),
            LineSlot(id="slot.corner.a1", prompt="", x1=104.0, y1=250.0, x2=114.0, y2=250.0),
            LineSlot(id="slot.corner.a2", prompt="", x1=104.0, y1=250.0, x2=104.0, y2=260.0),
            LineSlot(id="slot.corner.b1", prompt="", x1=229.0, y1=250.0, x2=239.0, y2=250.0),
            LineSlot(id="slot.corner.b2", prompt="", x1=229.0, y1=250.0, x2=229.0, y2=260.0),
            LineSlot(id="slot.corner.c1", prompt="", x1=314.0, y1=250.0, x2=324.0, y2=250.0),
            LineSlot(id="slot.corner.c2", prompt="", x1=314.0, y1=250.0, x2=314.0, y2=260.0),
            LineSlot(id="slot.corner.d1", prompt="", x1=395.0, y1=250.0, x2=405.0, y2=250.0),
            LineSlot(id="slot.corner.d2", prompt="", x1=395.0, y1=250.0, x2=395.0, y2=260.0),
            LineSlot(id="slot.corner.e1", prompt="", x1=545.0, y1=250.0, x2=555.0, y2=250.0),
            LineSlot(id="slot.corner.e2", prompt="", x1=545.0, y1=250.0, x2=545.0, y2=260.0),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_009064",
    "problem_type": "도형_선택",
    "metadata": {
        "language": "ko",
        "question": "직사각형을 모두 선택하세요.",
        "instruction": "도형들 중 직사각형에 해당하는 것을 고른다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.shape.a", "type": "quadrilateral", "label": "가"},
            {"id": "obj.shape.b", "type": "quadrilateral", "label": "나"},
            {"id": "obj.shape.c", "type": "quadrilateral", "label": "다"},
            {"id": "obj.shape.d", "type": "quadrilateral", "label": "라"},
            {"id": "obj.shape.e", "type": "quadrilateral", "label": "마"},
            {
                "id": "obj.rectangle_definition",
                "type": "definition",
                "text": "네 각이 모두 직각인 사각형",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.shape.a",
                    "obj.shape.b",
                    "obj.shape.c",
                    "obj.shape.d",
                    "obj.shape.e",
                    "obj.rectangle_definition",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.selects"],
            },
            "plan": {
                "method": "definition_matching",
                "description": "직사각형의 정의와 각 도형의 모양을 대응해 본다.",
            },
            "execute": {"expected_operations": ["compare_shapes", "match_definition"]},
            "review": {"check_methods": ["definition_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_shapes", "description": "직사각형에 해당하는 도형을 고른다."},
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_009064",
    "problem_type": "도형_선택",
    "inputs": {
        "total_ticks": 5,
        "target_label": "직사각형",
        "target_ticks": 2,
        "target_count": 2,
        "unit": "",
    },
    "given": [
        {"ref": "obj.shape.a", "value": {"label": "가"}},
        {"ref": "obj.shape.b", "value": {"label": "나"}},
        {"ref": "obj.shape.c", "value": {"label": "다"}},
        {"ref": "obj.shape.d", "value": {"label": "라"}},
        {"ref": "obj.shape.e", "value": {"label": "마"}},
    ],
    "target": {"ref": "answer.target", "type": "selected_shapes"},
    "method": "definition_matching",
    "plan": ["직사각형의 정의를 보고 해당하는 도형을 고른다."],
    "steps": [
        {
            "id": "step.1",
            "expr": "직사각형의 정의를 확인한다.",
            "value": "네 각이 모두 직각인 사각형",
        },
        {"id": "step.2", "expr": "도형들을 정의와 비교한다.", "value": "TODO"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "정의와 선택이 일치하는지 확인한다.",
            "expected": 2,
            "actual": 2,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_shapes", "description": "직사각형에 해당하는 도형을 고른다."},
        "value": 2,
        "unit": "",
    },
}
