from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008954",
        title="학생들이 여행 가고 싶은 나라",
        canvas=Canvas(width=940.0, height=406.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q_no",
                    "slot.q1",
                    "slot.q2",
                    "slot.title_box",
                    "slot.title_text",
                    "slot.table.outer",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.v5",
                    "slot.table.h1",
                    "slot.table.r1c1",
                    "slot.table.r1c2",
                    "slot.table.r1c3",
                    "slot.table.r1c4",
                    "slot.table.r1c5",
                    "slot.table.r1c6",
                    "slot.table.r2c1",
                    "slot.table.r2c2",
                    "slot.table.r2c3",
                    "slot.table.r2c4",
                    "slot.table.r2c5",
                    "slot.table.r2c6",
                    "slot.choice",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q_no",
                prompt="",
                text="□ 24.",
                style_role="question",
                x=10.0,
                y=26.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q1",
                prompt="",
                text="영지네 반 학생들이 여행 가고 싶은 나라를 조사하여 표로 나타냈습니다.",
                style_role="question",
                x=63.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="가장 많은 학생들이 가고 싶어 하는 나라를 선택하세요.",
                style_role="question",
                x=63.0,
                y=68.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.title_box",
                prompt="",
                x=301.0,
                y=86.0,
                width=420.0,
                height=44.0,
                fill="#e7f1d6",
                stroke="#cfdcbe",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.title_text",
                prompt="",
                text="학생들이 여행 가고 싶은 나라",
                style_role="title",
                x=352.0,
                y=115.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=144.0,
                y=137.0,
                width=686.0,
                height=87.0,
                fill="#eaf4da",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.table.v1",
                prompt="",
                x=302.0,
                y=137.0,
                width=0.0,
                height=87.0,
                fill="none",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.table.v2",
                prompt="",
                x=408.0,
                y=137.0,
                width=0.0,
                height=87.0,
                fill="none",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.table.v3",
                prompt="",
                x=514.0,
                y=137.0,
                width=0.0,
                height=87.0,
                fill="none",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.table.v4",
                prompt="",
                x=620.0,
                y=137.0,
                width=0.0,
                height=87.0,
                fill="none",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.table.v5",
                prompt="",
                x=726.0,
                y=137.0,
                width=0.0,
                height=87.0,
                fill="none",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            RectSlot(
                id="slot.table.h1",
                prompt="",
                x=144.0,
                y=182.0,
                width=686.0,
                height=0.0,
                fill="none",
                stroke="#92c35d",
                stroke_width=1.0,
            ),
            TextSlot(
                id="slot.table.r1c1",
                prompt="",
                text="나라",
                style_role="body",
                x=180.0,
                y=168.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c2",
                prompt="",
                text="미국",
                style_role="body",
                x=333.0,
                y=168.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c3",
                prompt="",
                text="중국",
                style_role="body",
                x=439.0,
                y=168.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c4",
                prompt="",
                text="일본",
                style_role="body",
                x=545.0,
                y=168.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c5",
                prompt="",
                text="호주",
                style_role="body",
                x=652.0,
                y=168.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c6",
                prompt="",
                text="합계",
                style_role="body",
                x=758.0,
                y=168.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c1",
                prompt="",
                text="학생 수(명)",
                style_role="body",
                x=165.0,
                y=210.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c2",
                prompt="",
                text="12",
                style_role="body",
                x=334.0,
                y=210.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c3",
                prompt="",
                text="6",
                style_role="body",
                x=444.0,
                y=210.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c4",
                prompt="",
                text="7",
                style_role="body",
                x=550.0,
                y=210.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c5",
                prompt="",
                text="10",
                style_role="body",
                x=649.0,
                y=210.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c6",
                prompt="",
                text="35",
                style_role="body",
                x=755.0,
                y=210.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 미국, 중국, 일본, 호주 )",
                style_role="body",
                x=594.0,
                y=259.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008954",
    "problem_type": "data_interpretation",
    "metadata": {
        "language": "ko",
        "question": "학생들이 여행 가고 싶은 나라를 표로 나타내고, 가장 많은 학생들이 가고 싶어 하는 나라를 찾는 문제",
        "instruction": "가장 많은 학생들이 가고 싶어 하는 나라를 선택하세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.country.us", "type": "country", "name": "미국"},
            {"id": "obj.country.cn", "type": "country", "name": "중국"},
            {"id": "obj.country.jp", "type": "country", "name": "일본"},
            {"id": "obj.country.au", "type": "country", "name": "호주"},
            {"id": "obj.count.us", "type": "count", "value": 12},
            {"id": "obj.count.cn", "type": "count", "value": 6},
            {"id": "obj.count.jp", "type": "count", "value": 7},
            {"id": "obj.count.au", "type": "count", "value": 10},
            {"id": "obj.count.total", "type": "count", "value": 35},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.count.us",
                    "obj.count.cn",
                    "obj.count.jp",
                    "obj.count.au",
                    "obj.count.total",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.max_count"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "각 나라의 학생 수를 서로 비교하여 가장 큰 수에 해당하는 나라를 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_country_counts",
                    "identify_largest_count",
                    "select_matching_country",
                ]
            },
            "review": {"check_methods": ["largest_value_check", "country_count_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "country_name", "description": "가장 많은 학생들이 가고 싶어 하는 나라"},
        "value": "미국",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008954",
    "problem_type": "data_interpretation",
    "inputs": {
        "total_ticks": 35,
        "target_label": "가장 많은 학생들이 가고 싶어 하는 나라",
        "target_ticks": 12,
        "target_count": 4,
        "unit": "명",
    },
    "plan": [
        "표에 있는 각 나라의 학생 수를 비교합니다.",
        "가장 큰 수가 어느 나라에 해당하는지 확인합니다.",
        "그 나라를 정답으로 선택합니다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "미국 12명, 중국 6명, 일본 7명, 호주 10명",
            "value": {"미국": 12, "중국": 6, "일본": 7, "호주": 10},
        },
        {"id": "step.2", "expr": "12 > 10 > 7 > 6", "value": "미국이 가장 큼"},
        {"id": "step.3", "expr": "가장 많은 학생들이 가고 싶어 하는 나라 선택", "value": "미국"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "최댓값이 12인지 확인",
            "expected": 12,
            "actual": 12,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "12에 대응하는 나라가 미국인지 확인",
            "expected": "미국",
            "actual": "미국",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "country_name", "description": "가장 많은 학생들이 가고 싶어 하는 나라"},
        "value": "미국",
        "unit": "",
    },
}
