from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008666",
        title="원의 반지름과 중심 이동",
        canvas=Canvas(width=940, height=495, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.qnum", "slot.qtext1", "slot.qtext2"),
            ),
            Region(
                id="region.options",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.box",
                    "slot.opt1.c1",
                    "slot.opt1.c2",
                    "slot.opt1.c3",
                    "slot.opt2.c1",
                    "slot.opt2.c2",
                    "slot.opt3.c1",
                    "slot.opt3.c2",
                    "slot.opt3.c3",
                ),
            ),
            Region(
                id="region.answer",
                role="annotation",
                flow="absolute",
                slot_ids=(
                    "slot.answer_diagram.c1",
                    "slot.answer_diagram.c2",
                    "slot.answer_diagram.c3",
                ),
            ),
            Region(
                id="region.explanation",
                role="explanation",
                flow="absolute",
                slot_ids=(),
            ),
            Region(
                id="region.bottom_diagrams",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.bot1.c1",
                    "slot.bot1.c2",
                    "slot.bot1.c3",
                    "slot.bot1.p1",
                    "slot.bot1.p2",
                    "slot.bot1.p3",
                    "slot.bot2.c1",
                    "slot.bot2.c2",
                    "slot.bot2.p1",
                    "slot.bot2.p2",
                    "slot.bot3.c1",
                    "slot.bot3.c2",
                    "slot.bot3.c3",
                    "slot.bot3.p1",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.qnum",
                prompt="",
                text="42.",
                style_role="question",
                x=17.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.qtext1",
                prompt="",
                text="원의 반지름은 모두 같고 원의 중심을 옮겨 가며 그린 그림을 찾아 선택",
                style_role="question",
                x=58.0,
                y=31.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.qtext2",
                prompt="",
                text="하세요.",
                style_role="question",
                x=44.0,
                y=66.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.box",
                prompt="",
                x=201.0,
                y=86.0,
                width=569.0,
                height=131.0,
                fill="none",
                stroke="#9ACD32",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.opt1.c1",
                prompt="",
                cx=286.0,
                cy=146.0,
                r=22.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt1.c2",
                prompt="",
                cx=302.0,
                cy=124.0,
                r=22.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt1.c3",
                prompt="",
                cx=318.0,
                cy=146.0,
                r=22.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt2.c1",
                prompt="",
                cx=486.0,
                cy=138.0,
                r=40.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt2.c2",
                prompt="",
                cx=459.0,
                cy=147.0,
                r=13.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt3.c1",
                prompt="",
                cx=649.0,
                cy=138.0,
                r=37.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt3.c2",
                prompt="",
                cx=649.0,
                cy=138.0,
                r=23.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.opt3.c3",
                prompt="",
                cx=649.0,
                cy=138.0,
                r=11.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.answer_diagram.c1",
                prompt="",
                cx=98.0,
                cy=246.0,
                r=18.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.answer_diagram.c2",
                prompt="",
                cx=114.0,
                cy=226.0,
                r=18.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.answer_diagram.c3",
                prompt="",
                cx=130.0,
                cy=246.0,
                r=18.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot1.c1",
                prompt="",
                cx=92.0,
                cy=427.0,
                r=22.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot1.c2",
                prompt="",
                cx=111.0,
                cy=406.0,
                r=22.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot1.c3",
                prompt="",
                cx=130.0,
                cy=427.0,
                r=22.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot1.p1",
                prompt="",
                cx=81.0,
                cy=436.0,
                r=3.5,
                fill="#1da1f2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.bot1.p2",
                prompt="",
                cx=97.0,
                cy=420.0,
                r=3.5,
                fill="#1da1f2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.bot1.p3",
                prompt="",
                cx=112.0,
                cy=410.0,
                r=3.5,
                fill="#1da1f2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.bot2.c1",
                prompt="",
                cx=216.0,
                cy=427.0,
                r=41.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot2.c2",
                prompt="",
                cx=192.0,
                cy=427.0,
                r=13.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot2.p1",
                prompt="",
                cx=171.0,
                cy=427.0,
                r=3.5,
                fill="#1da1f2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.bot2.p2",
                prompt="",
                cx=192.0,
                cy=427.0,
                r=3.5,
                fill="#1da1f2",
                stroke="none",
            ),
            CircleSlot(
                id="slot.bot3.c1",
                prompt="",
                cx=348.0,
                cy=427.0,
                r=37.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot3.c2",
                prompt="",
                cx=348.0,
                cy=427.0,
                r=23.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot3.c3",
                prompt="",
                cx=348.0,
                cy=427.0,
                r=11.0,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.bot3.p1",
                prompt="",
                cx=348.0,
                cy=427.0,
                r=3.5,
                fill="#1da1f2",
                stroke="none",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008666",
    "problem_type": "도형_관계_선택",
    "metadata": {
        "language": "ko",
        "question": "원의 반지름은 모두 같고 원의 중심을 옮겨 가며 그린 그림을 찾아 선택하세요.",
        "instruction": "그림의 반지름과 중심 관계를 비교하여 보기와 해설을 읽는다.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.option1",
                "type": "circle_group",
                "property": "same_radius_overlapping_centers",
            },
            {
                "id": "obj.option2",
                "type": "circle_group",
                "property": "different_radii_moved_centers",
            },
            {
                "id": "obj.option3",
                "type": "circle_group",
                "property": "concentric_circles",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.option1", "obj.option2", "obj.option3"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_radius", "rel.compare_center"],
            },
            "plan": {
                "method": "도형 성질 비교",
                "description": "각 보기의 반지름이 같은지와 중심이 옮겨졌는지를 비교한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_radius",
                    "compare_center",
                    "match_description_to_view",
                ]
            },
            "review": {
                "check_methods": [
                    "description_consistency_check",
                    "circle_relation_check",
                ]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "선택",
            "description": "원의 반지름이 모두 같고 원의 중심을 옮겨 가며 그린 그림",
        },
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008666",
    "problem_type": "도형_관계_선택",
    "inputs": {
        "total_ticks": 3,
        "target_label": "반지름이 모두 같고 원의 중심을 옮겨 가며 그린 그림",
        "target_ticks": 1,
        "target_count": 3,
        "unit": "",
    },
    "given": [
        {
            "ref": "obj.option1",
            "value": {"property": "same_radius_overlapping_centers"},
        },
        {"ref": "obj.option2", "value": {"property": "different_radii_moved_centers"}},
        {"ref": "obj.option3", "value": {"property": "concentric_circles"}},
    ],
    "target": {"ref": "answer.target", "type": "선택"},
    "method": "도형 성질 비교",
    "plan": [
        "각 보기의 원들에서 반지름이 같은지 확인한다.",
        "원의 중심이 옮겨졌는지, 같은 중심인지 확인한다.",
        "문장과 가장 잘 맞는 그림을 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "보기 1의 원 관계 확인", "value": "겹쳐진 원들"},
        {
            "id": "step.2",
            "expr": "보기 2의 원 관계 확인",
            "value": "반지름이 다른 원들",
        },
        {"id": "step.3", "expr": "보기 3의 원 관계 확인", "value": "동심원"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "문장 조건과 일치하는 보기인지 확인",
            "expected": "반지름이 모두 같고 중심이 이동한 그림",
            "actual": "미확정",
            "pass": False,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "선택",
            "description": "원의 반지름이 모두 같고 원의 중심을 옮겨 가며 그린 그림",
        },
        "value": 0,
        "unit": "",
    },
}
