from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, CircleSlot, LineSlot, RectSlot, PathSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008696', title='원을 둘로 똑같이 나누는 선분', canvas=Canvas(width=960, height=540, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.q_num', 'slot.q_title')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.circle.1', 'slot.circle.2', 'slot.circle.3', 'slot.fold.1', 'slot.fold.2', 'slot.dot.1', 'slot.dot.2', 'slot.dot.3', 'slot.arrow.1', 'slot.arrow.2')), Region(id='region.choice', role='stem', flow='absolute', slot_ids=('slot.choice.1', 'slot.choice.2', 'slot.choice.3'))), slots=(TextSlot(id='slot.q_num', prompt='', text='85.', style_role='question', x=16.0, y=24.0, font_size=28), TextSlot(id='slot.q_title', prompt='', text='원을 둘로 똑같이 나누는 선분을 알아보려고 합니다. 알맞은 말을 선택하세요.', style_role='question', x=58.0, y=24.0, font_size=28), CircleSlot(id='slot.circle.1', prompt='', cx=196.0, cy=144.0, r=56.0, fill='#FCE8EF'), CircleSlot(id='slot.circle.2', prompt='', cx=480.0, cy=144.0, r=56.0, fill='#FCE8EF'), CircleSlot(id='slot.circle.3', prompt='', cx=763.0, cy=144.0, r=56.0, fill='#FCE8EF'), LineSlot(id='slot.fold.1', prompt='', x1=196.0, y1=88.0, x2=196.0, y2=200.0), LineSlot(id='slot.fold.2', prompt='', x1=424.0, y1=144.0, x2=536.0, y2=144.0), CircleSlot(id='slot.dot.1', prompt='', cx=763.0, cy=144.0, r=4.0, fill='#FF4DA0'), CircleSlot(id='slot.dot.2', prompt='', cx=762.0, cy=144.0, r=2.5, fill='#FF4DA0'), CircleSlot(id='slot.dot.3', prompt='', cx=772.0, cy=129.0, r=4.0, fill='#FFFFFF'), LineSlot(id='slot.arrow.1', prompt='', x1=297.0, y1=144.0, x2=336.0, y2=144.0), LineSlot(id='slot.arrow.2', prompt='', x1=581.0, y1=144.0, x2=620.0, y2=144.0), TextSlot(id='slot.choice.1', prompt='', text='(2) 원을 둘로 똑같이 나누는 선분은 ( 반지름 , 지름 )입니다.', style_role='question', x=10.0, y=398.0, font_size=28), TextSlot(id='slot.choice.2', prompt='', text='(2) 원을 둘로 똑같이 나누는 선분은 지름입니다.', style_role='question', x=10.0, y=442.0, font_size=28), TextSlot(id='slot.choice.3', prompt='', text='(2) 지름', style_role='question', x=10.0, y=487.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008696', 'problem_type': 'geometry_circle_fold', 'metadata': {'language': 'ko', 'question': '원을 둘로 똑같이 나누는 선분의 이름을 고르는 문제', 'instruction': '알맞은 말을 선택하세요.'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.fold_line', 'type': 'segment'}, {'id': 'obj.center', 'type': 'point'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle', 'obj.fold_line', 'obj.center'], 'target_ref': 'answer.target', 'condition_refs': ['rel.divide_circle_equally', 'rel.intersects_at_center']}, 'plan': {'method': 'concept_choice', 'description': '그림에서 원을 둘로 똑같이 나누는 선분의 개념과 맞는 말을 고른다.'}, 'execute': {'expected_operations': ['identify_shape_property', 'match_geometry_term']}, 'review': {'check_methods': ['term_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'geometry_term', 'description': '원을 둘로 똑같이 나누는 선분의 이름'}, 'value': '지름', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008696', 'problem_type': 'geometry_circle_fold', 'inputs': {'total_ticks': 0, 'target_label': '원을 둘로 똑같이 나누는 선분의 이름', 'target_ticks': 0, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': {'type': 'circle'}}, {'ref': 'obj.fold_line', 'value': {'type': 'segment'}}, {'ref': 'obj.center', 'value': {'type': 'point'}}], 'target': {'ref': 'answer.target', 'type': 'geometry_term'}, 'method': 'concept_choice', 'plan': ['그림에서 원을 접었을 때 원이 둘로 똑같이 나뉘는지 확인한다.', '그 성질에 맞는 선분의 이름을 선택한다.'], 'steps': [{'id': 'step.1', 'expr': '원은 중심을 지나며 둘로 똑같이 나뉘는 선분과 관련된다.', 'value': 'geometry_property'}, {'id': 'step.2', 'expr': '선택지에서 해당하는 용어를 찾는다.', 'value': '지름'}], 'checks': [{'id': 'check.1', 'expr': '원을 둘로 똑같이 나누는 선분인지 확인', 'expected': 'true', 'actual': 'true', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'geometry_term', 'description': '원을 둘로 똑같이 나누는 선분의 이름'}, 'value': '지름', 'unit': ''}}
