from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008926",
        title="가장 적은 학생이 하고 싶어 하는 종목",
        canvas=Canvas(width=940, height=392, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.title",
                    "slot.table.h1.c1",
                    "slot.table.h1.c2",
                    "slot.table.h1.c3",
                    "slot.table.h1.c4",
                    "slot.table.h1.c5",
                    "slot.table.h1.c6",
                    "slot.table.h2.c1",
                    "slot.table.h2.c2",
                    "slot.table.h2.c3",
                    "slot.table.h2.c4",
                    "slot.table.h2.c5",
                    "slot.table.h2.c6",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="92. 연수네 반 학생들이 학예회에서 하고 싶은 종목을 조사하여 표로\n나타내었습니다. 가장 적은 학생이 하고 싶어 하는 종목은 무엇인가요?",
                style_role="question",
                x=16.0,
                y=24.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.title",
                prompt="",
                text="학예회에서 하고 싶어 하는 종목",
                style_role="title",
                x=266.0,
                y=116.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.h1.c1",
                prompt="",
                x=188.0,
                y=154.0,
                width=148.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h1.c2",
                prompt="",
                x=336.0,
                y=154.0,
                width=92.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h1.c3",
                prompt="",
                x=428.0,
                y=154.0,
                width=92.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h1.c4",
                prompt="",
                x=520.0,
                y=154.0,
                width=92.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h1.c5",
                prompt="",
                x=612.0,
                y=154.0,
                width=92.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h1.c6",
                prompt="",
                x=704.0,
                y=154.0,
                width=88.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h2.c1",
                prompt="",
                x=188.0,
                y=194.0,
                width=148.0,
                height=40.0,
                fill="#dfe8bd",
            ),
            RectSlot(
                id="slot.table.h2.c2",
                prompt="",
                x=336.0,
                y=194.0,
                width=92.0,
                height=40.0,
                fill="#ffffff",
            ),
            RectSlot(
                id="slot.table.h2.c3",
                prompt="",
                x=428.0,
                y=194.0,
                width=92.0,
                height=40.0,
                fill="#ffffff",
            ),
            RectSlot(
                id="slot.table.h2.c4",
                prompt="",
                x=520.0,
                y=194.0,
                width=92.0,
                height=40.0,
                fill="#ffffff",
            ),
            RectSlot(
                id="slot.table.h2.c5",
                prompt="",
                x=612.0,
                y=194.0,
                width=92.0,
                height=40.0,
                fill="#ffffff",
            ),
            RectSlot(
                id="slot.table.h2.c6",
                prompt="",
                x=704.0,
                y=194.0,
                width=88.0,
                height=40.0,
                fill="#ffffff",
            ),
            TextSlot(
                id="slot.table.h1.c1",
                prompt="",
                text="종목",
                style_role="table",
                x=214.0,
                y=182.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h1.c2",
                prompt="",
                text="연극",
                style_role="table",
                x=354.0,
                y=182.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h1.c3",
                prompt="",
                text="합주",
                style_role="table",
                x=446.0,
                y=182.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h1.c4",
                prompt="",
                text="무용",
                style_role="table",
                x=538.0,
                y=182.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h1.c5",
                prompt="",
                text="합창",
                style_role="table",
                x=630.0,
                y=182.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h1.c6",
                prompt="",
                text="합계",
                style_role="table",
                x=724.0,
                y=182.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2.c1",
                prompt="",
                text="학생 수(명)",
                style_role="table",
                x=204.0,
                y=222.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2.c2",
                prompt="",
                text="6",
                style_role="table",
                x=370.0,
                y=222.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2.c3",
                prompt="",
                text="10",
                style_role="table",
                x=458.0,
                y=222.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2.c4",
                prompt="",
                text="5",
                style_role="table",
                x=552.0,
                y=222.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2.c5",
                prompt="",
                text="7",
                style_role="table",
                x=646.0,
                y=222.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.h2.c6",
                prompt="",
                text="28",
                style_role="table",
                x=734.0,
                y=222.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 연극",
                style_role="choice",
                x=28.0,
                y=285.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 합주",
                style_role="choice",
                x=227.0,
                y=285.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 무용",
                style_role="choice",
                x=411.0,
                y=285.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 합창",
                style_role="choice",
                x=591.0,
                y=285.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008926",
    "problem_type": "table_comparison",
    "metadata": {
        "language": "ko",
        "question": "학예회에서 하고 싶어 하는 종목을 나타낸 표를 보고 가장 적은 학생이 하고 싶어 하는 종목을 찾는 문제",
        "instruction": "가장 적은 학생이 하고 싶어 하는 종목을 고르시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.table", "type": "table"},
            {"id": "obj.event.연극", "type": "item", "label": "연극", "count": 6},
            {"id": "obj.event.합주", "type": "item", "label": "합주", "count": 10},
            {"id": "obj.event.무용", "type": "item", "label": "무용", "count": 5},
            {"id": "obj.event.합창", "type": "item", "label": "합창", "count": 7},
            {"id": "obj.total", "type": "total", "count": 28},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.event.연극",
                    "obj.event.합주",
                    "obj.event.무용",
                    "obj.event.합창",
                    "obj.total",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.table.entries", "rel.min_count"],
            },
            "plan": {
                "method": "compare_counts",
                "description": "표에 있는 각 종목의 학생 수를 비교하여 가장 작은 값을 찾는다.",
            },
            "execute": {
                "expected_operations": ["read_table_counts", "compare_values", "select_minimum"]
            },
            "review": {"check_methods": ["minimum_count_check", "table_reading_check"]},
        },
    },
    "answer": {
        "target": {
            "type": "min_count_category",
            "description": "가장 적은 학생이 하고 싶어 하는 종목",
        },
        "value": "무용",
        "unit": "",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008926",
    "problem_type": "table_comparison",
    "inputs": {
        "total_ticks": 28,
        "target_label": "가장 적은 학생이 하고 싶어 하는 종목",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "명",
    },
    "given": [
        {"ref": "obj.event.연극", "value": 6},
        {"ref": "obj.event.합주", "value": 10},
        {"ref": "obj.event.무용", "value": 5},
        {"ref": "obj.event.합창", "value": 7},
        {"ref": "obj.total", "value": 28},
    ],
    "target": {"ref": "answer.target", "type": "min_count_category"},
    "method": "compare_counts",
    "plan": [
        "표에 있는 각 종목의 학생 수를 읽는다.",
        "가장 작은 수를 찾는다.",
        "그 수에 대응하는 종목을 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "연극, 합주, 무용, 합창의 학생 수를 읽기", "value": [6, 10, 5, 7]},
        {"id": "step.2", "expr": "6, 10, 5, 7 중 가장 작은 수 찾기", "value": 5},
        {"id": "step.3", "expr": "가장 작은 수 5에 대응하는 종목 확인", "value": "무용"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "5가 6, 10, 7보다 작은가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "무용의 학생 수가 5인가",
            "expected": 5,
            "actual": 5,
            "pass": True,
        },
    ],
    "answer": {"value": "무용", "unit": "", "derived_from": "step.3"},
}
