from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008908",
        title="가장 적은 학생들이 태어난 계절",
        canvas=Canvas(width=960, height=390, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2", "slot.q3", "slot.q4", "slot.q5"),
            ),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.tbl.title",
                    "slot.tbl.outer",
                    "slot.tbl.c1r1",
                    "slot.tbl.c2r1",
                    "slot.tbl.c3r1",
                    "slot.tbl.c4r1",
                    "slot.tbl.c5r1",
                    "slot.tbl.c6r1",
                    "slot.tbl.c1r2",
                    "slot.tbl.c2r2",
                    "slot.tbl.c3r2",
                    "slot.tbl.c4r2",
                    "slot.tbl.c5r2",
                    "slot.tbl.c6r2",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="□ 74.",
                style_role="question",
                x=18.0,
                y=42.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="유라네 반 학생들이 태어난 계절을 조사하여 표로 나타내었습니다.",
                style_role="question",
                x=90.0,
                y=42.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="가장 적은",
                style_role="question",
                x=750.0,
                y=42.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="학생들이 태어난 계절을 선택해 보세요.",
                style_role="question",
                x=18.0,
                y=79.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q5", prompt="", text="", style_role="question", x=0.0, y=0.0, font_size=28
            ),
            TextSlot(
                id="slot.tbl.title",
                prompt="",
                text="태어난 계절별 학생 수",
                style_role="title",
                x=350.0,
                y=128.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.tbl.outer",
                prompt="",
                x=175.0,
                y=158.0,
                width=610.0,
                height=82.0,
                fill="#E8F1D1",
                stroke="#87C442",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.tbl.c1r1",
                prompt="",
                text="계절",
                style_role="table",
                x=221.0,
                y=189.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c2r1",
                prompt="",
                text="봄",
                style_role="table",
                x=341.0,
                y=189.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c3r1",
                prompt="",
                text="여름",
                style_role="table",
                x=430.0,
                y=189.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c4r1",
                prompt="",
                text="가을",
                style_role="table",
                x=529.0,
                y=189.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c5r1",
                prompt="",
                text="겨울",
                style_role="table",
                x=622.0,
                y=189.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c6r1",
                prompt="",
                text="합계",
                style_role="table",
                x=715.0,
                y=189.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c1r2",
                prompt="",
                text="학생 수(명)",
                style_role="table",
                x=212.0,
                y=228.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c2r2",
                prompt="",
                text="6",
                style_role="table",
                x=344.0,
                y=228.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c3r2",
                prompt="",
                text="10",
                style_role="table",
                x=435.0,
                y=228.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c4r2",
                prompt="",
                text="3",
                style_role="table",
                x=529.0,
                y=228.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c5r2",
                prompt="",
                text="9",
                style_role="table",
                x=624.0,
                y=228.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c6r2",
                prompt="",
                text="28",
                style_role="table",
                x=719.0,
                y=228.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008908",
    "problem_type": "comparison_table_choice",
    "metadata": {
        "language": "ko",
        "question": "표에서 가장 적은 학생들이 태어난 계절을 고르는 문제",
        "instruction": "가장 적은 학생들이 태어난 계절을 선택해 보세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.spring", "type": "season", "label": "봄", "count": 6},
            {"id": "obj.summer", "type": "season", "label": "여름", "count": 10},
            {"id": "obj.autumn", "type": "season", "label": "가을", "count": 3},
            {"id": "obj.winter", "type": "season", "label": "겨울", "count": 9},
            {"id": "obj.total", "type": "total", "label": "합계", "count": 28},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.spring", "obj.summer", "obj.autumn", "obj.winter"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_counts"],
            },
            "plan": {
                "method": "find_minimum",
                "description": "표의 학생 수를 비교하여 가장 작은 값을 가진 계절을 찾는다.",
            },
            "execute": {"expected_operations": ["compare_values", "identify_minimum"]},
            "review": {"check_methods": ["minimum_value_check", "label_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "season_name", "description": "가장 적은 학생들이 태어난 계절"},
        "value": "가을",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008908",
    "problem_type": "comparison_table_choice",
    "inputs": {
        "total_ticks": 28,
        "target_label": "가장 적은 학생들이 태어난 계절",
        "target_ticks": 3,
        "target_count": 1,
        "unit": "명",
    },
    "given": [
        {"ref": "obj.spring", "value": {"label": "봄", "count": 6}},
        {"ref": "obj.summer", "value": {"label": "여름", "count": 10}},
        {"ref": "obj.autumn", "value": {"label": "가을", "count": 3}},
        {"ref": "obj.winter", "value": {"label": "겨울", "count": 9}},
        {"ref": "obj.total", "value": {"label": "합계", "count": 28}},
    ],
    "target": {"ref": "answer.target", "type": "season_name"},
    "method": "find_minimum",
    "plan": [
        "표에 있는 학생 수를 비교한다.",
        "가장 작은 수를 찾는다.",
        "그 수에 해당하는 계절을 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "봄 6, 여름 10, 가을 3, 겨울 9를 비교한다.",
            "value": {"봄": 6, "여름": 10, "가을": 3, "겨울": 9},
        },
        {"id": "step.2", "expr": "가장 작은 수는 3이다.", "value": 3},
        {"id": "step.3", "expr": "3명에 해당하는 계절은 가을이다.", "value": "가을"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "3 < 6 and 3 < 10 and 3 < 9",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "가을의 학생 수가 최소값과 일치하는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "season_name", "description": "가장 적은 학생들이 태어난 계절"},
        "value": "가을",
        "unit": "",
    },
}
