from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008891",
        title="그림그래프에서 가장 많이 팔린 음식과 가장 적게 팔린 음식 찾기",
        canvas=Canvas(width=960, height=706, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header",
                role="stem",
                flow="absolute",
                slot_ids=("slot.no", "slot.stem1", "slot.stem2"),
            ),
            Region(
                id="region.graph",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.graph.title",
                    "slot.graph.box",
                    "slot.graph.col1.label",
                    "slot.graph.col2.label",
                    "slot.graph.col3.label",
                    "slot.graph.col4.label",
                    "slot.legend.big",
                    "slot.legend.big.text",
                    "slot.legend.small",
                    "slot.legend.small.text",
                ),
            ),
            Region(
                id="region.choices",
                role="choices",
                flow="absolute",
                slot_ids=("slot.choice.1", "slot.choice.2", "slot.choice.3", "slot.choice.4"),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.no",
                prompt="",
                text="55.",
                style_role="question",
                x=14.0,
                y=26.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.stem1",
                prompt="",
                text="어느 음식점에서 일주일 동안 팔린 음식의 수를 그림그래프로 나타내었습니다. 일주일 동안 가장 많이 팔린 음식과 가장 적게 팔린 음식을 순서대로",
                style_role="question",
                x=48.0,
                y=26.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.stem2",
                prompt="",
                text="나열한 것을 고르세요.",
                style_role="question",
                x=46.0,
                y=62.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.graph.title",
                prompt="",
                text="일주일 동안 팔린 음식의 수",
                style_role="diagram",
                x=340.0,
                y=110.0,
                font_size=28,
            ),
            RectSlot(id="slot.graph.box", prompt="", x=225.0, y=128.0, width=500.0, height=250.0),
            TextSlot(
                id="slot.graph.col1.label",
                prompt="",
                text="김치찌개",
                style_role="diagram",
                x=246.0,
                y=384.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.graph.col2.label",
                prompt="",
                text="비빔밥",
                style_role="diagram",
                x=376.0,
                y=384.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.graph.col3.label",
                prompt="",
                text="만둣국",
                style_role="diagram",
                x=504.0,
                y=384.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.graph.col4.label",
                prompt="",
                text="된장찌\n개",
                style_role="diagram",
                x=636.0,
                y=375.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.big",
                prompt="",
                text="그릇 그림",
                style_role="diagram",
                x=483.0,
                y=438.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.big.text",
                prompt="",
                text="100그릇",
                style_role="diagram",
                x=535.0,
                y=439.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.small",
                prompt="",
                text="그릇 그림",
                style_role="diagram",
                x=646.0,
                y=438.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.legend.small.text",
                prompt="",
                text="10그릇",
                style_role="diagram",
                x=688.0,
                y=439.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 된장찌개, 비빔밥",
                style_role="choice",
                x=30.0,
                y=500.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 김치찌개, 된장찌개",
                style_role="choice",
                x=469.0,
                y=500.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 된장찌개, 김치찌개",
                style_role="choice",
                x=30.0,
                y=545.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 김치찌개, 비빔밥",
                style_role="choice",
                x=469.0,
                y=545.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008891",
    "problem_type": "picture_graph_ordering",
    "metadata": {
        "language": "ko",
        "question": "일주일 동안 가장 많이 팔린 음식과 가장 적게 팔린 음식을 순서대로 고르는 문제",
        "instruction": "그림그래프를 보고 가장 많이 팔린 음식과 가장 적게 팔린 음식을 순서대로 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.food.1", "type": "food", "name": "김치찌개"},
            {"id": "obj.food.2", "type": "food", "name": "비빔밥"},
            {"id": "obj.food.3", "type": "food", "name": "만둣국"},
            {"id": "obj.food.4", "type": "food", "name": "된장찌개"},
            {"id": "obj.legend.big", "type": "legend_unit", "value": "100그릇"},
            {"id": "obj.legend.small", "type": "legend_unit", "value": "10그릇"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.food.1",
                    "obj.food.2",
                    "obj.food.3",
                    "obj.food.4",
                    "obj.legend.big",
                    "obj.legend.small",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.rank_desc"],
            },
            "plan": {
                "method": "compare_picture_graph_counts",
                "description": "그림그래프에서 각 음식의 판매량을 비교해 가장 큰 것부터 가장 작은 것까지 순서를 판단한다.",
            },
            "execute": {
                "expected_operations": [
                    "read_legend",
                    "compare_counts",
                    "match_order_to_food_names",
                ]
            },
            "review": {"check_methods": ["descending_order_check", "choice_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "ordered_food_names",
            "description": "가장 많이 팔린 음식과 가장 적게 팔린 음식을 순서대로 고르기",
        },
        "value": ["김치찌개", "된장찌개"],
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008891",
    "problem_type": "picture_graph_ordering",
    "inputs": {
        "total_ticks": 1,
        "target_label": "가장 많이 팔린 음식과 가장 적게 팔린 음식",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.legend.big", "value": "100그릇"},
        {"ref": "obj.legend.small", "value": "10그릇"},
        {"ref": "obj.food.1", "value": "김치찌개"},
        {"ref": "obj.food.2", "value": "비빔밥"},
        {"ref": "obj.food.3", "value": "만둣국"},
        {"ref": "obj.food.4", "value": "된장찌개"},
    ],
    "target": {"ref": "answer.target", "type": "ordered_food_names"},
    "method": "compare_picture_graph_counts",
    "plan": [
        "그림그래프의 범례를 확인한다.",
        "각 음식의 판매량을 비교해 큰 값부터 작은 값 순으로 정렬한다.",
        "보기와 비교해 정답을 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "범례 확인",
            "value": {"big_unit": "100그릇", "small_unit": "10그릇"},
        },
        {
            "id": "step.2",
            "expr": "판매량 비교 결과를 큰 값부터 작은 값 순으로 정렬",
            "value": ["김치찌개", "만둣국", "비빔밥", "된장찌개"],
        },
        {
            "id": "step.3",
            "expr": "가장 많이 팔린 음식과 가장 적게 팔린 음식 선택",
            "value": ["김치찌개", "된장찌개"],
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "정렬 순서가 내림차순인지 확인",
            "expected": ["김치찌개", "만둣국", "비빔밥", "된장찌개"],
            "actual": ["김치찌개", "만둣국", "비빔밥", "된장찌개"],
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "선택한 보기와 일치하는지 확인",
            "expected": ["김치찌개", "된장찌개"],
            "actual": ["김치찌개", "된장찌개"],
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "ordered_food_names",
            "description": "가장 많이 팔린 음식과 가장 적게 팔린 음식을 순서대로 고르기",
        },
        "value": ["김치찌개", "된장찌개"],
        "unit": "",
    },
}
