from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, PolygonSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_009058",
        title="직각삼각형을 모두 선택하세요",
        canvas=Canvas(width=670.0, height=420.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header",
                role="stem",
                flow="absolute",
                slot_ids=("slot.qnum", "slot.qtext"),
            ),
            Region(
                id="region.top_grid",
                role="figure",
                flow="absolute",
                slot_ids=(
                    "slot.grid.top.bg",
                    "slot.grid.top.v1",
                    "slot.grid.top.v2",
                    "slot.grid.top.v3",
                    "slot.grid.top.v4",
                    "slot.grid.top.v5",
                    "slot.grid.top.v6",
                    "slot.grid.top.v7",
                    "slot.grid.top.v8",
                    "slot.grid.top.v9",
                    "slot.grid.top.v10",
                    "slot.grid.top.v11",
                    "slot.grid.top.v12",
                    "slot.grid.top.v13",
                    "slot.grid.top.v14",
                    "slot.grid.top.v15",
                    "slot.grid.top.v16",
                    "slot.grid.top.v17",
                    "slot.grid.top.v18",
                    "slot.grid.top.v19",
                    "slot.grid.top.h1",
                    "slot.grid.top.h2",
                    "slot.grid.top.h3",
                    "slot.grid.top.h4",
                    "slot.grid.top.h5",
                    "slot.grid.top.h6",
                    "slot.grid.top.h7",
                ),
            ),
            Region(
                id="region.top_shapes",
                role="figure",
                flow="absolute",
                slot_ids=(
                    "slot.shape.가",
                    "slot.shape.나",
                    "slot.shape.다",
                    "slot.shape.라",
                    "slot.shape.마",
                    "slot.label.가",
                    "slot.label.나",
                    "slot.label.다",
                    "slot.label.라",
                    "slot.label.마",
                    "slot.right.나",
                    "slot.right.라",
                ),
            ),
            Region(id="region.choice", role="stem", flow="absolute", slot_ids=("slot.choice",)),
            Region(id="region.answer", role="stem", flow="absolute", slot_ids=()),
            Region(
                id="region.bottom_grid",
                role="figure",
                flow="absolute",
                slot_ids=(
                    "slot.grid.bottom.bg",
                    "slot.grid.bottom.v1",
                    "slot.grid.bottom.v2",
                    "slot.grid.bottom.v3",
                    "slot.grid.bottom.v4",
                    "slot.grid.bottom.v5",
                    "slot.grid.bottom.v6",
                    "slot.grid.bottom.v7",
                    "slot.grid.bottom.v8",
                    "slot.grid.bottom.v9",
                    "slot.grid.bottom.v10",
                    "slot.grid.bottom.v11",
                    "slot.grid.bottom.v12",
                    "slot.grid.bottom.v13",
                    "slot.grid.bottom.v14",
                    "slot.grid.bottom.v15",
                    "slot.grid.bottom.v16",
                    "slot.grid.bottom.v17",
                    "slot.grid.bottom.v18",
                    "slot.grid.bottom.v19",
                    "slot.grid.bottom.h1",
                    "slot.grid.bottom.h2",
                    "slot.grid.bottom.h3",
                    "slot.grid.bottom.h4",
                    "slot.grid.bottom.h5",
                    "slot.grid.bottom.h6",
                    "slot.grid.bottom.h7",
                ),
            ),
            Region(
                id="region.bottom_shapes",
                role="figure",
                flow="absolute",
                slot_ids=(
                    "slot.shape2.가",
                    "slot.shape2.나",
                    "slot.shape2.다",
                    "slot.shape2.라",
                    "slot.shape2.마",
                    "slot.label2.가",
                    "slot.label2.나",
                    "slot.label2.다",
                    "slot.label2.라",
                    "slot.label2.마",
                    "slot.right2.나",
                    "slot.right2.라",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.qnum",
                prompt="",
                text="96.",
                style_role="question",
                x=18.0,
                y=20.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.qtext",
                prompt="",
                text="직각삼각형을 모두 선택하세요.",
                style_role="question",
                x=48.0,
                y=20.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.grid.top.bg",
                prompt="",
                x=200.0,
                y=36.0,
                width=448.0,
                height=96.0,
                fill="none",
                stroke="#BFE8FF",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.top.v1",
                prompt="",
                x1=220.0,
                y1=36.0,
                x2=220.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v2",
                prompt="",
                x1=240.0,
                y1=36.0,
                x2=240.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v3",
                prompt="",
                x1=260.0,
                y1=36.0,
                x2=260.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v4",
                prompt="",
                x1=280.0,
                y1=36.0,
                x2=280.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v5",
                prompt="",
                x1=300.0,
                y1=36.0,
                x2=300.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v6",
                prompt="",
                x1=320.0,
                y1=36.0,
                x2=320.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v7",
                prompt="",
                x1=340.0,
                y1=36.0,
                x2=340.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v8",
                prompt="",
                x1=360.0,
                y1=36.0,
                x2=360.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v9",
                prompt="",
                x1=380.0,
                y1=36.0,
                x2=380.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v10",
                prompt="",
                x1=400.0,
                y1=36.0,
                x2=400.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v11",
                prompt="",
                x1=420.0,
                y1=36.0,
                x2=420.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v12",
                prompt="",
                x1=440.0,
                y1=36.0,
                x2=440.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v13",
                prompt="",
                x1=460.0,
                y1=36.0,
                x2=460.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v14",
                prompt="",
                x1=480.0,
                y1=36.0,
                x2=480.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v15",
                prompt="",
                x1=500.0,
                y1=36.0,
                x2=500.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v16",
                prompt="",
                x1=520.0,
                y1=36.0,
                x2=520.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v17",
                prompt="",
                x1=540.0,
                y1=36.0,
                x2=540.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v18",
                prompt="",
                x1=560.0,
                y1=36.0,
                x2=560.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.v19",
                prompt="",
                x1=580.0,
                y1=36.0,
                x2=580.0,
                y2=132.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h1",
                prompt="",
                x1=200.0,
                y1=48.0,
                x2=648.0,
                y2=48.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h2",
                prompt="",
                x1=200.0,
                y1=60.0,
                x2=648.0,
                y2=60.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h3",
                prompt="",
                x1=200.0,
                y1=72.0,
                x2=648.0,
                y2=72.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h4",
                prompt="",
                x1=200.0,
                y1=84.0,
                x2=648.0,
                y2=84.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h5",
                prompt="",
                x1=200.0,
                y1=96.0,
                x2=648.0,
                y2=96.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h6",
                prompt="",
                x1=200.0,
                y1=108.0,
                x2=648.0,
                y2=108.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.top.h7",
                prompt="",
                x1=200.0,
                y1=120.0,
                x2=648.0,
                y2=120.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            PolygonSlot(
                id="slot.shape.가",
                prompt="",
                points=((225.0, 60.0), (213.0, 104.0), (237.0, 104.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape.나",
                prompt="",
                points=((280.0, 104.0), (330.0, 60.0), (330.0, 104.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape.다",
                prompt="",
                points=((355.0, 104.0), (395.0, 60.0), (375.0, 104.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape.라",
                prompt="",
                points=((420.0, 104.0), (420.0, 60.0), (480.0, 60.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape.마",
                prompt="",
                points=((535.0, 104.0), (535.0, 60.0), (590.0, 82.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.label.가",
                prompt="",
                text="가",
                style_role="label",
                x=222.0,
                y=88.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.나",
                prompt="",
                text="나",
                style_role="label",
                x=312.0,
                y=90.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.다",
                prompt="",
                text="다",
                style_role="label",
                x=364.0,
                y=98.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.라",
                prompt="",
                text="라",
                style_role="label",
                x=432.0,
                y=74.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label.마",
                prompt="",
                text="마",
                style_role="label",
                x=565.0,
                y=80.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.right.나",
                prompt="",
                x=323.0,
                y=94.0,
                width=8.0,
                height=8.0,
                fill="none",
                stroke="#333333",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.right.라",
                prompt="",
                x=427.0,
                y=64.0,
                width=8.0,
                height=8.0,
                fill="none",
                stroke="#333333",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 가 , 나 , 다 , 라 , 마 )",
                style_role="question",
                x=250.0,
                y=158.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.grid.bottom.bg",
                prompt="",
                x=200.0,
                y=282.0,
                width=448.0,
                height=96.0,
                fill="none",
                stroke="#BFE8FF",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.grid.bottom.v1",
                prompt="",
                x1=220.0,
                y1=282.0,
                x2=220.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v2",
                prompt="",
                x1=240.0,
                y1=282.0,
                x2=240.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v3",
                prompt="",
                x1=260.0,
                y1=282.0,
                x2=260.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v4",
                prompt="",
                x1=280.0,
                y1=282.0,
                x2=280.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v5",
                prompt="",
                x1=300.0,
                y1=282.0,
                x2=300.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v6",
                prompt="",
                x1=320.0,
                y1=282.0,
                x2=320.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v7",
                prompt="",
                x1=340.0,
                y1=282.0,
                x2=340.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v8",
                prompt="",
                x1=360.0,
                y1=282.0,
                x2=360.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v9",
                prompt="",
                x1=380.0,
                y1=282.0,
                x2=380.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v10",
                prompt="",
                x1=400.0,
                y1=282.0,
                x2=400.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v11",
                prompt="",
                x1=420.0,
                y1=282.0,
                x2=420.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v12",
                prompt="",
                x1=440.0,
                y1=282.0,
                x2=440.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v13",
                prompt="",
                x1=460.0,
                y1=282.0,
                x2=460.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v14",
                prompt="",
                x1=480.0,
                y1=282.0,
                x2=480.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v15",
                prompt="",
                x1=500.0,
                y1=282.0,
                x2=500.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v16",
                prompt="",
                x1=520.0,
                y1=282.0,
                x2=520.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v17",
                prompt="",
                x1=540.0,
                y1=282.0,
                x2=540.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v18",
                prompt="",
                x1=560.0,
                y1=282.0,
                x2=560.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.v19",
                prompt="",
                x1=580.0,
                y1=282.0,
                x2=580.0,
                y2=378.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h1",
                prompt="",
                x1=200.0,
                y1=294.0,
                x2=648.0,
                y2=294.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h2",
                prompt="",
                x1=200.0,
                y1=306.0,
                x2=648.0,
                y2=306.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h3",
                prompt="",
                x1=200.0,
                y1=318.0,
                x2=648.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h4",
                prompt="",
                x1=200.0,
                y1=330.0,
                x2=648.0,
                y2=330.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h5",
                prompt="",
                x1=200.0,
                y1=342.0,
                x2=648.0,
                y2=342.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h6",
                prompt="",
                x1=200.0,
                y1=354.0,
                x2=648.0,
                y2=354.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.bottom.h7",
                prompt="",
                x1=200.0,
                y1=366.0,
                x2=648.0,
                y2=366.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            PolygonSlot(
                id="slot.shape2.가",
                prompt="",
                points=((225.0, 310.0), (213.0, 354.0), (237.0, 354.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape2.나",
                prompt="",
                points=((280.0, 354.0), (330.0, 310.0), (330.0, 354.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape2.다",
                prompt="",
                points=((355.0, 354.0), (395.0, 310.0), (375.0, 354.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape2.라",
                prompt="",
                points=((420.0, 354.0), (420.0, 310.0), (480.0, 310.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            PolygonSlot(
                id="slot.shape2.마",
                prompt="",
                points=((535.0, 354.0), (535.0, 310.0), (590.0, 332.0)),
                fill="none",
                stroke="#333333",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.label2.가",
                prompt="",
                text="가",
                style_role="label",
                x=222.0,
                y=338.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label2.나",
                prompt="",
                text="나",
                style_role="label",
                x=312.0,
                y=340.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label2.다",
                prompt="",
                text="다",
                style_role="label",
                x=364.0,
                y=348.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label2.라",
                prompt="",
                text="라",
                style_role="label",
                x=432.0,
                y=324.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.label2.마",
                prompt="",
                text="마",
                style_role="label",
                x=565.0,
                y=330.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.right2.나",
                prompt="",
                x=323.0,
                y=344.0,
                width=8.0,
                height=8.0,
                fill="none",
                stroke="#333333",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.right2.라",
                prompt="",
                x=427.0,
                y=314.0,
                width=8.0,
                height=8.0,
                fill="none",
                stroke="#333333",
                stroke_width=1.2,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_009058",
    "problem_type": "도형_분류",
    "metadata": {
        "language": "ko",
        "question": "직각삼각형을 모두 선택하세요.",
        "instruction": "보기 중 직각삼각형을 고르는 문제",
    },
    "domain": {
        "objects": [
            {"id": "obj.triangle.가", "type": "triangle", "label": "가"},
            {"id": "obj.triangle.나", "type": "triangle", "label": "나"},
            {"id": "obj.triangle.다", "type": "triangle", "label": "다"},
            {"id": "obj.triangle.라", "type": "triangle", "label": "라"},
            {"id": "obj.triangle.마", "type": "triangle", "label": "마"},
            {"id": "obj.right_mark.나", "type": "right_angle_marker", "target": "obj.triangle.나"},
            {"id": "obj.right_mark.라", "type": "right_angle_marker", "target": "obj.triangle.라"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.triangle.가",
                    "obj.triangle.나",
                    "obj.triangle.다",
                    "obj.triangle.라",
                    "obj.triangle.마",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.classify"],
            },
            "plan": {"method": "도형_분류", "description": "직각 표시가 있는 삼각형을 찾는다."},
            "execute": {
                "expected_operations": ["identify_right_angle_marker", "select_matching_labels"]
            },
            "review": {"check_methods": ["match_visible_marker_to_label"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_labels", "description": "직각삼각형으로 선택할 라벨"},
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_009058",
    "problem_type": "도형_분류",
    "inputs": {
        "total_ticks": 5,
        "target_label": "직각삼각형",
        "target_ticks": 2,
        "target_count": 2,
        "unit": "",
    },
    "given": [
        {"ref": "obj.triangle.가", "value": {"label": "가"}},
        {"ref": "obj.triangle.나", "value": {"label": "나"}},
        {"ref": "obj.triangle.다", "value": {"label": "다"}},
        {"ref": "obj.triangle.라", "value": {"label": "라"}},
        {"ref": "obj.triangle.마", "value": {"label": "마"}},
    ],
    "target": {"ref": "answer.target", "type": "selected_labels"},
    "method": "도형_분류",
    "plan": ["직각 표시가 있는 삼각형을 찾는다.", "찾은 도형의 라벨을 선택한다."],
    "steps": [
        {"id": "step.1", "expr": "직각 표시가 있는 도형 확인", "value": ["나", "라"]},
        {"id": "step.2", "expr": "선택할 라벨 정리", "value": ["나", "라"]},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "직각 표시와 라벨이 대응하는가",
            "expected": ["나", "라"],
            "actual": ["나", "라"],
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_labels", "description": "직각삼각형으로 선택할 라벨"},
        "value": 2,
        "unit": "",
    },
}
