from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008647",
        title="원 안의 선분 중 길이가 가장 긴 선분 찾기",
        canvas=Canvas(width=960, height=720, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q.no",
                    "slot.q.text",
                    "slot.q.circle",
                    "slot.q.top.circle",
                    "slot.q.top.center",
                    "slot.q.top.radius1",
                    "slot.q.top.radius2",
                    "slot.q.top.radius3",
                    "slot.q.top.radius4",
                    "slot.q.top.diameter",
                    "slot.q.top.label.d",
                    "slot.q.top.label.ㄴ",
                    "slot.q.top.label.ㄹ",
                    "slot.q.top.label.ㄱ",
                    "slot.q.top.label.ㅁ",
                    "slot.q.top.center_mark",
                    "slot.expl.circle",
                    "slot.expl.top.circle",
                    "slot.expl.top.center",
                    "slot.expl.top.radius1",
                    "slot.expl.top.radius2",
                    "slot.expl.top.radius3",
                    "slot.expl.top.radius4",
                    "slot.expl.top.diameter",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q.no",
                prompt="",
                text="□ 19.",
                style_role="question",
                x=12.0,
                y=34.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.text",
                prompt="",
                text="원 안의 선분 중 길이가 가장 긴 선분을 찾아 기호를 선택하세요.",
                style_role="question",
                x=86.0,
                y=34.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.q.circle", prompt="", cx=505.0, cy=190.0, r=95.0, fill="none"
            ),
            CircleSlot(
                id="slot.q.top.circle",
                prompt="",
                cx=505.0,
                cy=190.0,
                r=2.5,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.q.top.center",
                prompt="",
                cx=505.0,
                cy=191.0,
                r=3.0,
                fill="#ff3aa7",
            ),
            LineSlot(
                id="slot.q.top.radius1",
                prompt="",
                x1=505.0,
                y1=190.0,
                x2=458.0,
                y2=107.0,
            ),
            LineSlot(
                id="slot.q.top.radius2",
                prompt="",
                x1=505.0,
                y1=190.0,
                x2=410.0,
                y2=228.0,
            ),
            LineSlot(
                id="slot.q.top.radius3",
                prompt="",
                x1=505.0,
                y1=190.0,
                x2=560.0,
                y2=108.0,
            ),
            LineSlot(
                id="slot.q.top.radius4",
                prompt="",
                x1=505.0,
                y1=190.0,
                x2=596.0,
                y2=230.0,
            ),
            LineSlot(
                id="slot.q.top.diameter",
                prompt="",
                x1=505.0,
                y1=95.0,
                x2=505.0,
                y2=285.0,
            ),
            TextSlot(
                id="slot.q.top.label.d",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=497.0,
                y=80.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.top.label.ㄴ",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=448.0,
                y=118.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.top.label.ㄹ",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=566.0,
                y=118.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.top.label.ㄱ",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=390.0,
                y=231.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.top.label.ㅁ",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=604.0,
                y=232.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q.top.center_mark",
                prompt="",
                text="ㅇ",
                style_role="label",
                x=519.0,
                y=194.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.expl.circle",
                prompt="",
                cx=191.0,
                cy=487.0,
                r=95.0,
                fill="none",
            ),
            CircleSlot(
                id="slot.expl.top.circle",
                prompt="",
                cx=191.0,
                cy=487.0,
                r=2.5,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.expl.top.center",
                prompt="",
                cx=191.0,
                cy=487.0,
                r=3.0,
                fill="#ff3aa7",
            ),
            LineSlot(
                id="slot.expl.top.radius1",
                prompt="",
                x1=191.0,
                y1=487.0,
                x2=140.0,
                y2=404.0,
            ),
            LineSlot(
                id="slot.expl.top.radius2",
                prompt="",
                x1=191.0,
                y1=487.0,
                x2=97.0,
                y2=525.0,
            ),
            LineSlot(
                id="slot.expl.top.radius3",
                prompt="",
                x1=191.0,
                y1=487.0,
                x2=245.0,
                y2=406.0,
            ),
            LineSlot(
                id="slot.expl.top.radius4",
                prompt="",
                x1=191.0,
                y1=487.0,
                x2=286.0,
                y2=528.0,
            ),
            LineSlot(
                id="slot.expl.top.diameter",
                prompt="",
                x1=191.0,
                y1=392.0,
                x2=191.0,
                y2=582.0,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008647",
    "problem_type": "geometry_comparison",
    "metadata": {
        "language": "ko",
        "question": "원 안의 선분 중 길이가 가장 긴 선분을 찾아 기호를 선택하세요.",
        "instruction": "가장 긴 선분의 기호를 고른다.",
        "points": 5,
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {
                "id": "obj.segment.d",
                "type": "segment",
                "symbol": "ㄷ",
                "role": "diameter_candidate",
            },
            {
                "id": "obj.segment.others",
                "type": "segment_set",
                "description": "원 안의 다른 선분들",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle", "obj.segment.d", "obj.segment.others"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.longest", "rel.center_pass"],
            },
            "plan": {
                "method": "compare_segments_by_circle_property",
                "description": "원 안의 선분들 가운데 원의 중심을 지나는 선분을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_center_passing_segment",
                    "match_symbol_to_segment",
                ]
            },
            "review": {"check_methods": ["property_check_longest_segment_is_diameter"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "symbol_choice",
            "description": "길이가 가장 긴 선분의 기호",
        },
        "value": "ㄷ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008647",
    "problem_type": "geometry_comparison",
    "inputs": {
        "total_ticks": 0,
        "target_label": "ㄷ",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": {"type": "circle"}},
        {
            "ref": "obj.segment.d",
            "value": {"symbol": "ㄷ", "property": "passes_through_center"},
        },
        {
            "ref": "obj.segment.others",
            "value": {"description": "other segments in the circle"},
        },
    ],
    "target": {"ref": "answer.target", "type": "symbol_choice"},
    "method": "compare_segments_by_circle_property",
    "plan": [
        "원의 중심을 지나는 선분을 찾는다.",
        "그 선분에 대응하는 기호를 확인한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "원의 중심을 지나는 선분 확인", "value": "ㄷ"},
        {"id": "step.2", "expr": "가장 긴 선분의 기호 선택", "value": "ㄷ"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "중심을 지나는 선분이 가장 긴가?",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "symbol_choice",
            "description": "길이가 가장 긴 선분의 기호",
        },
        "value": "ㄷ",
        "unit": "",
    },
}
