from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008913",
        title="생일에 받고 싶은 선물별 학생 수",
        canvas=Canvas(width=944, height=471, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q.mark",
                    "slot.q1",
                    "slot.q2",
                    "slot.table.title",
                    "slot.table.cell.r1c1",
                    "slot.table.cell.r1c2",
                    "slot.table.cell.r1c3",
                    "slot.table.cell.r1c4",
                    "slot.table.cell.r1c5",
                    "slot.table.cell.r1c6",
                    "slot.table.cell.r2c1",
                    "slot.table.cell.r2c2",
                    "slot.table.cell.r2c3",
                    "slot.table.cell.r2c4",
                    "slot.table.cell.r2c5",
                    "slot.table.cell.r2c6",
                    "slot.opt1",
                    "slot.opt2",
                    "slot.opt3",
                    "slot.opt4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q.mark",
                prompt="",
                text="□",
                style_role="question",
                x=6.0,
                y=33.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q1",
                prompt="",
                text="79. 정국이는 반 학생들이 생일에 받고 싶은 선물을 조사하여 표로 나타냈습니다.",
                style_role="question",
                x=45.0,
                y=41.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="받고 싶은 학생 수가 많은 선물부터 순서대로 나열한 것을 고르세요.",
                style_role="question",
                x=45.0,
                y=74.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.title",
                prompt="",
                text="생일에 받고 싶은 선물별 학생 수",
                style_role="question",
                x=298.0,
                y=115.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.table.cell.r1c1",
                prompt="",
                x=141.0,
                y=137.0,
                width=160.0,
                height=38.0,
                fill="#dfe8c9",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r1c2",
                prompt="",
                x=301.0,
                y=137.0,
                width=104.0,
                height=38.0,
                fill="#dfe8c9",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r1c3",
                prompt="",
                x=405.0,
                y=137.0,
                width=104.0,
                height=38.0,
                fill="#dfe8c9",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r1c4",
                prompt="",
                x=509.0,
                y=137.0,
                width=104.0,
                height=38.0,
                fill="#dfe8c9",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r1c5",
                prompt="",
                x=613.0,
                y=137.0,
                width=105.0,
                height=38.0,
                fill="#dfe8c9",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r1c6",
                prompt="",
                x=718.0,
                y=137.0,
                width=105.0,
                height=38.0,
                fill="#dfe8c9",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r2c1",
                prompt="",
                x=141.0,
                y=175.0,
                width=160.0,
                height=37.0,
                fill="#ffffff",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r2c2",
                prompt="",
                x=301.0,
                y=175.0,
                width=104.0,
                height=37.0,
                fill="#ffffff",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r2c3",
                prompt="",
                x=405.0,
                y=175.0,
                width=104.0,
                height=37.0,
                fill="#ffffff",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r2c4",
                prompt="",
                x=509.0,
                y=175.0,
                width=104.0,
                height=37.0,
                fill="#ffffff",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r2c5",
                prompt="",
                x=613.0,
                y=175.0,
                width=105.0,
                height=37.0,
                fill="#ffffff",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.cell.r2c6",
                prompt="",
                x=718.0,
                y=175.0,
                width=105.0,
                height=37.0,
                fill="#ffffff",
                stroke="#9bcf44",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.table.r1c1.text",
                prompt="",
                text="선물",
                style_role="question",
                x=202.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c2.text",
                prompt="",
                text="책",
                style_role="question",
                x=336.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c3.text",
                prompt="",
                text="휴대전화",
                style_role="question",
                x=421.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c4.text",
                prompt="",
                text="게임기",
                style_role="question",
                x=535.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c5.text",
                prompt="",
                text="옷",
                style_role="question",
                x=653.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r1c6.text",
                prompt="",
                text="합계",
                style_role="question",
                x=757.0,
                y=166.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c1.text",
                prompt="",
                text="학생 수(명)",
                style_role="question",
                x=164.0,
                y=200.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c2.text",
                prompt="",
                text="6",
                style_role="question",
                x=348.0,
                y=200.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c3.text",
                prompt="",
                text="12",
                style_role="question",
                x=447.0,
                y=200.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c4.text",
                prompt="",
                text="8",
                style_role="question",
                x=551.0,
                y=200.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c5.text",
                prompt="",
                text="4",
                style_role="question",
                x=657.0,
                y=200.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.table.r2c6.text",
                prompt="",
                text="30",
                style_role="question",
                x=756.0,
                y=200.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.opt1",
                prompt="",
                text="① 휴대전화, 게임기, 책, 옷",
                style_role="question",
                x=40.0,
                y=246.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.opt2",
                prompt="",
                text="② 휴대전화, 책, 게임기, 옷",
                style_role="question",
                x=40.0,
                y=285.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.opt3",
                prompt="",
                text="③ 옷, 책, 게임기, 휴대전화",
                style_role="question",
                x=40.0,
                y=324.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.opt4",
                prompt="",
                text="④ 책, 휴대전화, 게임기, 옷",
                style_role="question",
                x=40.0,
                y=364.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008913",
    "problem_type": "순서_비교",
    "metadata": {
        "language": "ko",
        "question": "표에서 학생 수가 많은 선물부터 순서대로 나열한 것을 고르는 문제",
        "instruction": "받고 싶은 학생 수가 많은 선물부터 순서대로 나열한 것을 고르세요.",
        "points": 0,
    },
    "domain": {
        "objects": [
            {"id": "obj.book", "type": "gift", "name": "책", "count": 6},
            {"id": "obj.phone", "type": "gift", "name": "휴대전화", "count": 12},
            {"id": "obj.game", "type": "gift", "name": "게임기", "count": 8},
            {"id": "obj.clothes", "type": "gift", "name": "옷", "count": 4},
            {"id": "obj.total", "type": "total", "name": "합계", "count": 30},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.book", "obj.phone", "obj.game", "obj.clothes", "obj.total"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.rank_desc"],
            },
            "plan": {
                "method": "compare_and_order",
                "description": "표의 학생 수를 비교하여 큰 수부터 작은 수 순서로 나열한다.",
            },
            "execute": {
                "expected_operations": ["read_counts", "compare_counts", "order_descending"]
            },
            "review": {"check_methods": ["descending_order_check", "table_reading_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "descending_order_of_gifts",
            "description": "학생 수가 많은 선물부터 순서대로 나열한 것",
        },
        "value": 1,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008913",
    "problem_type": "순서_비교",
    "inputs": {
        "total_ticks": 30,
        "target_label": "학생 수가 많은 선물부터 순서",
        "target_ticks": 4,
        "target_count": 4,
        "unit": "명",
    },
    "given": [
        {"ref": "obj.book", "value": {"name": "책", "count": 6}},
        {"ref": "obj.phone", "value": {"name": "휴대전화", "count": 12}},
        {"ref": "obj.game", "value": {"name": "게임기", "count": 8}},
        {"ref": "obj.clothes", "value": {"name": "옷", "count": 4}},
        {"ref": "obj.total", "value": {"name": "합계", "count": 30}},
    ],
    "target": {"ref": "answer.target", "type": "descending_order_of_gifts"},
    "method": "compare_and_order",
    "plan": [
        "표에 있는 각 선물의 학생 수를 읽는다.",
        "학생 수가 큰 선물부터 작은 선물 순서로 배열한다.",
        "선택지에서 같은 순서가 맞는 것을 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "휴대전화=12, 게임기=8, 책=6, 옷=4",
            "value": [
                {"name": "휴대전화", "count": 12},
                {"name": "게임기", "count": 8},
                {"name": "책", "count": 6},
                {"name": "옷", "count": 4},
            ],
        },
        {"id": "step.2", "expr": "12 > 8 > 6 > 4", "value": ["휴대전화", "게임기", "책", "옷"]},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "정렬이 큰 수부터인지 확인",
            "expected": ["휴대전화", "게임기", "책", "옷"],
            "actual": ["휴대전화", "게임기", "책", "옷"],
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "descending_order_of_gifts",
            "description": "학생 수가 많은 선물부터 순서대로 나열한 것",
        },
        "value": 1,
        "unit": "",
    },
}
