from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008848', title='알맞은 단위를 골라 보세요', canvas=Canvas(width=736, height=370, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.rhino', 'slot.q2')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='□ 87. 알맞은 단위를 골라 보세요.', style_role='question', x=10.0, y=26.0, font_size=28), RectSlot(id='slot.rhino', prompt='', x=360.0, y=42.0, width=246.0, height=82.0), TextSlot(id='slot.q2', prompt='', text='코뿔소의 무게는 약 3( g , kg , t )입니다.', style_role='question', x=228.0, y=192.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=('단위선택', '질량단위', '초등수학'))
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008848', 'problem_type': 'unit_choice', 'metadata': {'language': 'ko', 'question': '알맞은 단위를 고르기', 'instruction': '코뿔소의 무게에 알맞은 단위를 고르세요.'}, 'domain': {'objects': [{'id': 'obj.rhino', 'type': 'animal', 'name': '코뿔소'}, {'id': 'obj.mass_value', 'type': 'quantity', 'value': 3}, {'id': 'obj.unit_g', 'type': 'unit', 'name': 'g'}, {'id': 'obj.unit_kg', 'type': 'unit', 'name': 'kg'}, {'id': 'obj.unit_t', 'type': 'unit', 'name': 't'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.rhino', 'obj.mass_value', 'obj.unit_g', 'obj.unit_kg', 'obj.unit_t'], 'target_ref': 'answer.target', 'condition_refs': ['rel.mass_measurement', 'rel.choose_largest_suitable_unit']}, 'plan': {'method': 'compare_mass_units', 'description': '무게를 나타내는 단위 후보를 비교하여 알맞은 단위를 고른다.'}, 'execute': {'expected_operations': ['compare_unit_sizes', 'select_suitable_unit']}, 'review': {'check_methods': ['mass_reasonableness_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'unit_name', 'description': '코뿔소의 무게에 알맞은 단위'}, 'value': 't', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008848', 'problem_type': 'unit_choice', 'inputs': {'total_ticks': 3, 'target_label': '알맞은 단위', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.rhino', 'value': {'name': '코뿔소'}}, {'ref': 'obj.mass_value', 'value': 3}, {'ref': 'obj.unit_g', 'value': {'name': 'g'}}, {'ref': 'obj.unit_kg', 'value': {'name': 'kg'}}, {'ref': 'obj.unit_t', 'value': {'name': 't'}}], 'target': {'ref': 'answer.target', 'type': 'unit_name'}, 'method': 'compare_mass_units', 'plan': ['무게의 크기에 맞는 단위 후보를 비교한다.', '코뿔소처럼 무거운 대상에 알맞은 단위를 고른다.'], 'steps': [{'id': 'step.1', 'expr': 'g, kg, t 중 무거운 대상에 알맞은 단위 선택', 'value': 't'}], 'checks': [{'id': 'check.1', 'expr': '코뿔소의 무게는 3 kg보다 더 무겁다', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'unit_name', 'description': '코뿔소의 무게에 알맞은 단위'}, 'value': 't', 'unit': ''}}
