from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot, PolygonSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008719', title='원의 중심이 되는 곳', canvas=Canvas(width=940, height=370, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.no', 'slot.q1', 'slot.q2')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.band', 'slot.pt1', 'slot.pt2', 'slot.pt3', 'slot.pt4', 'slot.pt5', 'slot.lb1', 'slot.lb2', 'slot.lb3', 'slot.lb4', 'slot.lb5', 'slot.pin_body', 'slot.pin_head', 'slot.pin_tip', 'slot.pencil_body', 'slot.pencil_tip', 'slot.pencil_eraser')), Region(id='region.footer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.no', prompt='', text='□ 22.', style_role='question', x=8.0, y=36.0, font_size=28), TextSlot(id='slot.q1', prompt='', text='그림과 같이 띠 종이를 나 못으로 고정한 후 연필을 구멍에 넣어 원을', style_role='question', x=56.0, y=36.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='그리려고 합니다. 원의 중심이 되는 곳을 선택하세요.', style_role='question', x=56.0, y=74.0, font_size=28), RectSlot(id='slot.band', prompt='', x=268.0, y=124.0, width=436.0, height=104.0, fill='#f3efcf', stroke='#c9bf93', stroke_width=1.2), CircleSlot(id='slot.pt1', prompt='', cx=320.0, cy=164.0, r=4.0, fill='#d6c79a'), CircleSlot(id='slot.pt2', prompt='', cx=408.0, cy=164.0, r=4.0, fill='#d6c79a'), CircleSlot(id='slot.pt3', prompt='', cx=500.0, cy=164.0, r=4.0, fill='#d6c79a'), CircleSlot(id='slot.pt4', prompt='', cx=592.0, cy=164.0, r=4.0, fill='#d6c79a'), CircleSlot(id='slot.pt5', prompt='', cx=676.0, cy=164.0, r=4.0, fill='#d6c79a'), TextSlot(id='slot.lb1', prompt='', text='①', style_role='diagram', x=312.0, y=192.0, font_size=28), TextSlot(id='slot.lb2', prompt='', text='②', style_role='diagram', x=400.0, y=192.0, font_size=28), TextSlot(id='slot.lb3', prompt='', text='③', style_role='diagram', x=492.0, y=192.0, font_size=28), TextSlot(id='slot.lb4', prompt='', text='④', style_role='diagram', x=584.0, y=192.0, font_size=28), TextSlot(id='slot.lb5', prompt='', text='⑤', style_role='diagram', x=668.0, y=192.0, font_size=28), LineSlot(id='slot.pin_body', prompt='', x1=500.0, y1=114.0, x2=500.0, y2=154.0, stroke='#8e8e8e', stroke_width=5.0), CircleSlot(id='slot.pin_head', prompt='', cx=500.0, cy=108.0, r=8.0, fill='#d8d8d8'), CircleSlot(id='slot.pin_tip', prompt='', cx=500.0, cy=160.0, r=4.0, fill='#a7a7a7'), RectSlot(id='slot.pencil_body', prompt='', x=664.0, y=78.0, width=12.0, height=80.0, fill='#ffb5b5', stroke='#ee7777', stroke_width=1.0), PolygonSlot(id='slot.pencil_tip', prompt='', points=((664.0, 158.0), (676.0, 158.0), (670.0, 172.0)), fill='#e6c08b', stroke='#c49b62', stroke_width=1.0), RectSlot(id='slot.pencil_eraser', prompt='', x=664.0, y=68.0, width=12.0, height=10.0, fill='#d9a27f', stroke='#b98160', stroke_width=1.0)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008719', 'problem_type': 'multiple_choice_geometry', 'metadata': {'language': 'ko', 'question': '띠 종이를 나 못으로 고정한 후 연필을 구멍에 넣어 원을 그리려고 할 때, 원의 중심이 되는 곳을 고르는 문제', 'instruction': '원의 중심이 되는 곳을 선택하세요.'}, 'domain': {'objects': [{'id': 'obj.band', 'type': 'strip_paper'}, {'id': 'obj.pin', 'type': 'pin'}, {'id': 'obj.pencil', 'type': 'pencil'}, {'id': 'obj.choice_3', 'type': 'candidate_point'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.band', 'obj.pin', 'obj.pencil', 'obj.choice_3'], 'target_ref': 'answer.target', 'condition_refs': ['rel.pin_center']}, 'plan': {'method': 'identify_given_center_point', 'description': '누름 못이 꽂힌 위치가 원의 중심인지 그림과 해설의 대응으로 확인한다.'}, 'execute': {'expected_operations': ['match_pin_position_to_choice', 'select_center_candidate']}, 'review': {'check_methods': ['compare_with_printed_explanation', 'verify_choice_label']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_label', 'description': '원의 중심이 되는 곳'}, 'value': 3, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008719', 'problem_type': 'multiple_choice_geometry', 'inputs': {'total_ticks': 5, 'target_label': '③', 'target_ticks': 3, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.pin', 'value': 'choice_3'}, {'ref': 'obj.choice_3', 'value': {'label': '③'}}], 'target': {'ref': 'answer.target', 'type': 'choice_label'}, 'method': 'identify_given_center_point', 'plan': ['누름 못이 꽂힌 위치를 찾는다.', '그 위치와 같은 선택지 번호를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '누름 못이 꽂힌 점과 일치하는 선택지 확인', 'value': '③'}], 'checks': [{'id': 'check.1', 'expr': 'printed_answer == choice_label', 'expected': '③', 'actual': '③', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'choice_label', 'description': '원의 중심이 되는 곳'}, 'value': 3, 'unit': ''}}
