from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot, CircleSlot, PolygonSlot, PathSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008865', title='샴푸통의 들이 비교', canvas=Canvas(width=940, height=431, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.diag.left', 'slot.diag.right', 'slot.diag.arrow', 'slot.diag.left_label', 'slot.diag.right_label', 'slot.diag.left_text', 'slot.diag.right_text')), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.q1', prompt='', text='□ 14. 어머니께서 리필용 샴푸를 사서 빈 샴푸통에 모두 부었더니 그림과 같이', style_role='question', x=12.0, y=30.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='샴푸통이 가득 차지 않았습니다. 알맞은 말을 선택하세요.', style_role='question', x=12.0, y=64.0, font_size=28), RectSlot(id='slot.diag.left', prompt='', x=397.0, y=99.0, width=43.0, height=96.0), RectSlot(id='slot.diag.right', prompt='', x=500.0, y=92.0, width=73.0, height=109.0), LineSlot(id='slot.diag.arrow', prompt='', x1=465.0, y1=145.0, x2=489.0, y2=145.0), TextSlot(id='slot.diag.left_text', prompt='', text='리필용\n샴푸', style_role='label', x=401.0, y=128.0, font_size=18), TextSlot(id='slot.diag.right_text', prompt='', text='샴푸통', style_role='label', x=520.0, y=183.0, font_size=18), TextSlot(id='slot.diag.left_label', prompt='', text='가', style_role='label', x=414.0, y=235.0, font_size=28), TextSlot(id='slot.diag.right_label', prompt='', text='나', style_role='label', x=529.0, y=235.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008865', 'problem_type': '비교_들이', 'metadata': {'language': 'ko', 'question': '그림을 보고 두 통의 들이를 비교하는 문제', 'instruction': '알맞은 말을 선택한다.'}, 'domain': {'objects': [{'id': 'obj.left_container', 'type': 'container', 'name': '리필용 샴푸', 'role': '가'}, {'id': 'obj.right_container', 'type': 'container', 'name': '샴푸통', 'role': '나'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.left_container', 'obj.right_container', 'rel.compare_capacity'], 'target_ref': 'answer.target', 'condition_refs': []}, 'plan': {'method': '그림_비교', 'description': '그림과 문장을 보고 가와 나의 들이를 비교한다.'}, 'execute': {'expected_operations': ['identify_containers', 'compare_capacity', 'choose_appropriate_word']}, 'review': {'check_methods': ['sentence_matches_picture']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'word_choice', 'description': '가 통은 나 통보다 들이가 더 (많습니다/적습니다)에서 알맞은 말'}, 'value': 0, 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008865', 'problem_type': '비교_들이', 'inputs': {'total_ticks': 0, 'target_label': '가 통은 나 통보다 들이가 더 (많습니다, 적습니다)', 'target_ticks': 0, 'target_count': 0, 'unit': ''}, 'given': [{'ref': 'obj.left_container', 'value': {'name': '리필용 샴푸', 'role': '가'}}, {'ref': 'obj.right_container', 'value': {'name': '샴푸통', 'role': '나'}}], 'target': {'ref': 'answer.target', 'type': 'word_choice'}, 'method': '그림_비교', 'plan': ['그림에 보이는 두 용기를 확인한다.', '가와 나는 각각 왼쪽과 오른쪽 용기에 대응한다.', '문장에서 들이 비교에 맞는 말을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '가 = 리필용 샴푸, 나 = 샴푸통', 'value': '대응 확인'}, {'id': 'step.2', 'expr': '그림의 상태를 보고 가와 나의 들이를 비교한다', 'value': '가의 들이가 더 적음'}, {'id': 'step.3', 'expr': '선택지 중 알맞은 말 고르기', 'value': '적습니다'}], 'checks': [{'id': 'check.1', 'expr': '그림 해석과 문장이 일치하는가', 'expected': '적습니다', 'actual': '적습니다', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'word_choice', 'description': '가 통은 나 통보다 들이가 더 (많습니다/적습니다)에서 알맞은 말'}, 'value': 0, 'unit': ''}}
