from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008688', title='원의 성질 선택', canvas=Canvas(width=886.0, height=563.0, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.q1', 'slot.q2', 'slot.circle', 'slot.circle.center', 'slot.circle.line1', 'slot.circle.line2', 'slot.circle.mark1', 'slot.circle.mark2', 'slot.circle.mark3', 'slot.choice_box', 'slot.choice.line1', 'slot.choice.line2')),), slots=(TextSlot(id='slot.q1', prompt='', text='□ 77.', style_role='question', x=11.0, y=29.0, font_size=28), TextSlot(id='slot.q2', prompt='', text='알맞은 말을 선택하세요.', style_role='question', x=73.0, y=29.0, font_size=28), CircleSlot(id='slot.circle', prompt='', cx=561.0, cy=214.0, r=147.0, fill='none'), CircleSlot(id='slot.circle.center', prompt='', cx=556.0, cy=214.0, r=4.0, fill='#ff2a8a'), LineSlot(id='slot.circle.line1', prompt='', x1=408.0, y1=214.0, x2=702.0, y2=214.0), LineSlot(id='slot.circle.line2', prompt='', x1=474.0, y1=73.0, x2=619.0, y2=311.0), CircleSlot(id='slot.circle.mark1', prompt='', cx=558.0, cy=202.0, r=4.0, fill='none'), CircleSlot(id='slot.circle.mark2', prompt='', cx=398.0, cy=309.0, r=1.5, fill='#222222'), CircleSlot(id='slot.circle.mark3', prompt='', cx=696.0, cy=311.0, r=1.5, fill='#222222'), RectSlot(id='slot.choice_box', prompt='', x=96.0, y=352.0, width=763.0, height=118.0, fill='none'), TextSlot(id='slot.choice.line1', prompt='', text='한 원에는 지름을 ( 2개만, 무수히 많이 ) 그을 수 있고', style_role='question', x=161.0, y=403.0, font_size=28), TextSlot(id='slot.choice.line2', prompt='', text='그 길이는 모두 ( 같습니다, 다릅니다 ).', style_role='question', x=209.0, y=441.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008688', 'problem_type': 'multiple_choice_circle_property', 'metadata': {'language': 'ko', 'question': '알맞은 말을 선택하세요.', 'instruction': '원의 성질에 대한 문장 완성'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.diameter', 'type': 'diameter', 'countability': 'many'}, {'id': 'obj.diameter_length', 'type': 'length_property', 'relation': 'same'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle'], 'target_ref': 'answer.target', 'condition_refs': ['rel.diameter_count', 'rel.diameter_length']}, 'plan': {'method': 'circle_property_selection', 'description': '원의 성질을 보고 알맞은 선택지를 고른다.'}, 'execute': {'expected_operations': ['identify_circle_property', 'choose_correct_words']}, 'review': {'check_methods': ['property_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_words', 'description': '문장 괄호 안에서 알맞은 말'}, 'value': '무수히 많이, 같습니다', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008688', 'problem_type': 'multiple_choice_circle_property', 'inputs': {'total_ticks': 0, 'target_label': 'selected_words', 'target_ticks': 0, 'target_count': 2, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': {'type': 'circle'}}], 'target': {'ref': 'answer.target', 'type': 'selected_words'}, 'method': 'circle_property_selection', 'plan': ['원의 성질을 확인한다.', '두 문장에 들어갈 알맞은 말을 고른다.'], 'steps': [{'id': 'step.1', 'expr': '원의 지름은 여러 개 그을 수 있는가', 'value': '무수히 많이'}, {'id': 'step.2', 'expr': '지름의 길이는 모두 같은가', 'value': '같습니다'}], 'checks': [{'id': 'check.1', 'expr': '원의 지름 개수와 길이 성질이 문장과 일치하는가', 'expected': True, 'actual': True, 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'selected_words', 'description': '문장 괄호 안에서 알맞은 말'}, 'value': '무수히 많이, 같습니다', 'unit': ''}}
