from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008825', title='들이의 단위 알아보기', canvas=Canvas(width=960, height=420, coordinate_mode='logical'), regions=(Region(id='region.header', role='stem', flow='absolute', slot_ids=('slot.qno', 'slot.qtext1', 'slot.qtext2')), Region(id='region.diagram', role='diagram', flow='absolute', slot_ids=('slot.box.front', 'slot.box.side', 'slot.box.top', 'slot.box.label.small', 'slot.box.label.large', 'slot.magnifier', 'slot.magnifier.inner', 'slot.magnifier.label', 'slot.connector1', 'slot.connector2')), Region(id='region.choice', role='body', flow='absolute', slot_ids=('slot.choice',)), Region(id='region.answer', role='answer', flow='absolute', slot_ids=())), slots=(TextSlot(id='slot.qno', prompt='', text='59.', style_role='question', x=18.0, y=34.0, font_size=28), TextSlot(id='slot.qtext1', prompt='', text='물건에 표시되어 있는 들이의 단위를 알아보고, 알맞은 것을 선택하세', style_role='question', x=52.0, y=34.0, font_size=28), TextSlot(id='slot.qtext2', prompt='', text='요.', style_role='question', x=18.0, y=66.0, font_size=28), RectSlot(id='slot.box.front', prompt='', x=356.0, y=100.0, width=32.0, height=92.0, fill='#DDF2D8', stroke='#7BCB87', stroke_width=1.2), RectSlot(id='slot.box.side', prompt='', x=388.0, y=106.0, width=10.0, height=86.0, fill='#D3EBCF', stroke='#7BCB87', stroke_width=1.2), PolygonSlot(id='slot.box.top', prompt='', points=((356.0, 100.0), (372.0, 88.0), (404.0, 88.0), (388.0, 106.0)), fill='#E9F7E6', stroke='#7BCB87', stroke_width=1.2), TextSlot(id='slot.box.label.small', prompt='', text='200 mL', style_role='label', x=352.0, y=186.0, font_size=12), TextSlot(id='slot.box.label.large', prompt='', text='200 mL', style_role='label', x=515.0, y=163.0, font_size=28), CircleSlot(id='slot.magnifier', prompt='', cx=613.0, cy=149.0, r=56.0, fill='#FFF7FB', stroke='#FF1E9A', stroke_width=2.0), RectSlot(id='slot.magnifier.inner', prompt='', x=559.0, y=116.0, width=108.0, height=62.0, fill='#FFFFFF', stroke='#B5B5B5', stroke_width=0.8), TextSlot(id='slot.magnifier.label', prompt='', text='200 mL', style_role='label', x=570.0, y=165.0, font_size=28), LineSlot(id='slot.connector1', prompt='', x1=390.0, y1=130.0, x2=570.0, y2=92.0, stroke='#FF1E9A', stroke_width=1.6, stroke_dasharray='5 4'), LineSlot(id='slot.connector2', prompt='', x1=390.0, y1=193.0, x2=570.0, y2=194.0, stroke='#FF1E9A', stroke_width=1.6, stroke_dasharray='5 4'), TextSlot(id='slot.choice', prompt='', text='두유팩에 표시되어 있는 단위는 ( L , mL )입니다.', style_role='body', x=203.0, y=275.0, font_size=28)), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008825', 'problem_type': 'unit_reading', 'metadata': {'language': 'ko', 'question': '물건에 표시되어 있는 들이의 단위를 알아보고, 알맞은 것을 선택하세요.', 'instruction': '두유팩에 표시되어 있는 단위를 고르기'}, 'domain': {'objects': [{'id': 'obj.container', 'type': 'container', 'label': '두유팩처럼 보이는 용기'}, {'id': 'obj.label', 'type': 'volume_label', 'text': '200 mL'}, {'id': 'obj.choice', 'type': 'unit_choice', 'options': ['L', 'mL']}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.label', 'obj.choice'], 'target_ref': 'answer.target', 'condition_refs': ['rel.label_on_container', 'rel.choose_unit']}, 'plan': {'method': 'label_reading', 'description': '그림에 인쇄된 수치를 보고 단위를 고른다.'}, 'execute': {'expected_operations': ['read_printed_label', 'match_unit_symbol']}, 'review': {'check_methods': ['compare_with_printed_text']}}}, 'answer': {'target': {'type': 'selected_unit', 'description': '두유팩에 표시되어 있는 단위'}, 'value': 'mL', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008825', 'problem_type': 'unit_reading', 'inputs': {'total_ticks': 1, 'target_label': 'mL', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.label', 'value': {'text': '200 mL'}}, {'ref': 'obj.choice', 'value': {'options': ['L', 'mL']}}], 'target': {'ref': 'answer.target', 'type': 'selected_unit'}, 'method': 'label_reading', 'plan': ['그림에 표시된 글자를 읽고 단위를 확인한다.', '선택지 중 같은 단위를 고른다.'], 'steps': [{'id': 'step.1', 'expr': '그림의 표기 읽기', 'value': '200 mL'}, {'id': 'step.2', 'expr': '표기에서 단위 확인', 'value': 'mL'}], 'checks': [{'id': 'check.1', 'expr': '200 mL의 단위가 mL인지 확인', 'expected': 'mL', 'actual': 'mL', 'pass': True}], 'answer': {'value': 'mL', 'unit': '', 'derived_from': 'step.2'}}
