from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, CircleSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(id='S3_초등_3_008686', title='원의 지름을 나타내는 선분 판단', canvas=Canvas(width=940, height=469, coordinate_mode='logical'), regions=(Region(id='region.stem', role='stem', flow='absolute', slot_ids=('slot.qnum', 'slot.diagram.circle', 'slot.diagram.diameter', 'slot.diagram.left_label', 'slot.diagram.right_label', 'slot.diagram.center_mark', 'slot.diagram.pink_dot', 'slot.statement', 'slot.choice.o', 'slot.choice.x', 'slot.answer.blank')),), slots=(TextSlot(id='slot.qnum', prompt='', text='□ 75. 다음을 읽고 바르게 설명하였으면 ○표, 그렇지 않으면 ×표를 선택하세\n요.', style_role='question', x=10.0, y=26.0, font_size=28), CircleSlot(id='slot.diagram.circle', prompt='', cx=487.0, cy=175.0, r=90.0, fill='none'), LineSlot(id='slot.diagram.diameter', prompt='', x1=392.0, y1=175.0, x2=582.0, y2=175.0), TextSlot(id='slot.diagram.left_label', prompt='', text='ㄱ', style_role='label', x=375.0, y=181.0, font_size=28), TextSlot(id='slot.diagram.right_label', prompt='', text='ㄴ', style_role='label', x=587.0, y=181.0, font_size=28), CircleSlot(id='slot.diagram.center_mark', prompt='', cx=487.0, cy=165.0, r=4.5, fill='none'), CircleSlot(id='slot.diagram.pink_dot', prompt='', cx=487.0, cy=175.0, r=2.0, fill='none'), TextSlot(id='slot.statement', prompt='', text='원의 지름을 나타내는 선분은 선분 ㄱㄴ입니다.', style_role='question', x=203.0, y=295.0, font_size=28), TextSlot(id='slot.choice.o', prompt='', text='○', style_role='label', x=29.0, y=325.0, font_size=28), TextSlot(id='slot.choice.x', prompt='', text='×', style_role='label', x=29.0, y=355.0, font_size=28), CircleSlot(id='slot.answer.blank', prompt='', cx=66.0, cy=392.0, r=10.0, fill='none')), diagrams=(), groups=(), constraints=(), tags=())
PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': 'S3_초등_3_008686', 'problem_type': 'ox_judgment', 'metadata': {'language': 'ko', 'question': '원의 지름을 나타내는 선분이 무엇인지 판단하는 문제', 'instruction': '다음을 읽고 바르게 설명하였으면 ○표, 그렇지 않으면 ×표를 하세요.'}, 'domain': {'objects': [{'id': 'obj.circle', 'type': 'circle'}, {'id': 'obj.segment_gn', 'type': 'segment', 'label': 'ㄱㄴ'}], 'relations': [], 'problem_solving': {'understand': {'given_refs': ['obj.circle', 'obj.segment_gn'], 'target_ref': 'answer.target', 'condition_refs': ['rel.diameter_claim']}, 'plan': {'method': 'ox_judgment', 'description': '문장의 내용이 도형의 성질과 맞는지 판단한다.'}, 'execute': {'expected_operations': ['compare_statement_with_geometry', 'judge_true_or_false']}, 'review': {'check_methods': ['statement_consistency_check']}}}, 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'ox_judgment', 'description': '선분 ㄱㄴ이 원의 지름을 나타낸다는 설명이 맞는지'}, 'value': '○', 'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1.1', 'problem_id': 'S3_초등_3_008686', 'problem_type': 'ox_judgment', 'inputs': {'total_ticks': 1, 'target_label': '선분 ㄱㄴ이 원의 지름인지 판단', 'target_ticks': 1, 'target_count': 1, 'unit': ''}, 'given': [{'ref': 'obj.circle', 'value': {'type': 'circle'}}, {'ref': 'obj.segment_gn', 'value': {'type': 'segment', 'label': 'ㄱㄴ'}}], 'target': {'ref': 'answer.target', 'type': 'ox_judgment'}, 'method': 'ox_judgment', 'plan': ['문장에서 선분 ㄱㄴ이 원의 지름이라고 말하는지 확인한다.', '도형의 성질과 문장의 내용이 같으면 ○, 다르면 ×로 판단한다.'], 'steps': [{'id': 'step.1', 'expr': '선분 ㄱㄴ의 위치와 원의 중심을 지난다는 관계를 확인한다.', 'value': '중심을 지나는 선분'}, {'id': 'step.2', 'expr': "문장 '선분 ㄱㄴ은 원의 지름을 나타냅니다.'의 진위 판단", 'value': '○'}], 'checks': [{'id': 'check.1', 'expr': '문장 내용이 도형의 지름 성질과 일치하는가', 'expected': '○', 'actual': '○', 'pass': True}], 'answer': {'blanks': [], 'choices': [], 'answer_key': [], 'target': {'type': 'ox_judgment', 'description': '선분 ㄱㄴ이 원의 지름을 나타낸다는 설명이 맞는지'}, 'value': '○', 'unit': ''}}
