from __future__ import annotations

from modu_math.dsl import Canvas, CircleSlot, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2410.answer",
        title="삼각형 ADE에서 CD의 길이를 구하시오.",
        canvas=Canvas(width=980, height=620, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.diagram.frame",
                    "slot.seg.AD",
                    "slot.seg.DE",
                    "slot.seg.AE",
                    "slot.seg.BC",
                    "slot.mark.parallel.bc",
                    "slot.mark.parallel.de",
                    "slot.pt.A",
                    "slot.pt.B",
                    "slot.pt.C",
                    "slot.pt.D",
                    "slot.pt.E",
                    "slot.lb.A",
                    "slot.lb.B",
                    "slot.lb.C",
                    "slot.lb.D",
                    "slot.lb.E",
                    "slot.len.AB",
                    "slot.len.BE",
                    "slot.len.AC",
                    "slot.len.CD",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                    "slot.answer",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="삼각형 ADE에서 BC는 내부 선분이고 DE와 평행하다. AB=16, BE=20, AC=x-3, CD=x+5일 때 CD를 구하시오.",
                style_role="question",
                x=34.0,
                y=46.0,
                font_size=24,
                fill="#111111",
            ),
            RectSlot(
                id="slot.diagram.frame",
                prompt="",
                x=42.0,
                y=92.0,
                width=560.0,
                height=440.0,
                stroke="#D0D0D0",
                stroke_width=2.0,
                fill="none",
            ),
            LineSlot(id="slot.seg.AD", prompt="", x1=120.0, y1=460.0, x2=420.0, y2=170.0, stroke="#444444", stroke_width=3.0),
            LineSlot(id="slot.seg.DE", prompt="", x1=420.0, y1=170.0, x2=540.0, y2=450.0, stroke="#444444", stroke_width=3.0),
            LineSlot(id="slot.seg.AE", prompt="", x1=120.0, y1=460.0, x2=540.0, y2=450.0, stroke="#444444", stroke_width=3.0),
            LineSlot(id="slot.seg.BC", prompt="", x1=307.0, y1=455.6, x2=253.6, y2=326.7, stroke="#444444", stroke_width=3.0),
            LineSlot(id="slot.mark.parallel.bc", prompt="", x1=286.0, y1=404.8, x2=294.0, y2=423.5, stroke="#2D6CDF", stroke_width=3.0),
            LineSlot(id="slot.mark.parallel.de", prompt="", x1=468.0, y1=282.0, x2=476.0, y2=300.7, stroke="#2D6CDF", stroke_width=3.0),
            CircleSlot(id="slot.pt.A", prompt="", cx=120.0, cy=460.0, r=4.0, fill="#222222"),
            CircleSlot(id="slot.pt.B", prompt="", cx=307.0, cy=455.6, r=4.0, fill="#222222"),
            CircleSlot(id="slot.pt.C", prompt="", cx=253.6, cy=326.7, r=4.0, fill="#222222"),
            CircleSlot(id="slot.pt.D", prompt="", cx=420.0, cy=170.0, r=4.0, fill="#222222"),
            CircleSlot(id="slot.pt.E", prompt="", cx=540.0, cy=450.0, r=4.0, fill="#222222"),
            TextSlot(id="slot.lb.A", prompt="", text="A", style_role="label", x=106.0, y=474.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.lb.B", prompt="", text="B", style_role="label", x=311.0, y=474.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.lb.C", prompt="", text="C", style_role="label", x=236.0, y=324.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.lb.D", prompt="", text="D", style_role="label", x=424.0, y=158.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.lb.E", prompt="", text="E", style_role="label", x=548.0, y=456.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.len.AB", prompt="", text="16", style_role="label", x=210.0, y=468.0, font_size=24, fill="#111111"),
            TextSlot(id="slot.len.BE", prompt="", text="20", style_role="label", x=415.0, y=468.0, font_size=24, fill="#111111"),
            TextSlot(id="slot.len.AC", prompt="", text="x-3", style_role="label", x=174.0, y=375.0, font_size=24, fill="#111111"),
            TextSlot(id="slot.len.CD", prompt="", text="x+5", style_role="label", x=322.0, y=242.0, font_size=24, fill="#111111"),
            TextSlot(id="slot.choice.1", prompt="", text="1. 32", style_role="choice", x=684.0, y=154.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.choice.2", prompt="", text="2. 35", style_role="choice", x=684.0, y=206.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.choice.3", prompt="", text="3. 36", style_role="choice", x=684.0, y=258.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.choice.4", prompt="", text="4. 40", style_role="choice", x=684.0, y=310.0, font_size=28, fill="#111111"),
            TextSlot(id="slot.answer", prompt="", text="정답: 4번 (40)", style_role="note", x=684.0, y=548.0, font_size=28, fill="#D61F26"),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("triangle", "parallel", "segment", "geometry"),
    )


PROBLEM_TEMPLATE = build_problem_template()
