from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=800,
        height=520,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.q1', 'slot.q2'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.q1',
            prompt='',
            text='다음은 각기둥의 전개도입니다.',
            style_role='body',
            x=18.6,
            y=47.7,
            font_size=30,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.q2',
            prompt='',
            text='전개도를 접어서 만든 입체도형의 모서리는 모두 몇 개인가요?',
            style_role='body',
            x=16.1,
            y=89.9,
            font_size=30,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        PolygonSlot(
            id='slot.top_hex',
            prompt='',
            points=((350.466, 209.104),
             (320.48, 160.912),
             (350.466, 112.72),
             (399.534, 112.72),
             (429.52, 160.912),
             (399.534, 209.104)),
            stroke='#333333',
            stroke_width=2.0,
            fill='#CFCFCF',
            semantic_role='net',
        ),
        RectSlot(
            id='slot.strip_rect',
            prompt='',
            x=250.0,
            y=210.0,
            width=300.0,
            height=130.0,
            stroke='#333333',
            stroke_width=2.0,
            fill='#CFCFCF',
            semantic_role='net',
        ),
        LineSlot(
            id='slot.fold_1',
            prompt='',
            x1=300.0,
            y1=210.0,
            x2=300.0,
            y2=340.0,
            stroke='#333333',
            stroke_width=1.0,
            semantic_role='fold_line',
        ),
        LineSlot(
            id='slot.fold_2',
            prompt='',
            x1=350.0,
            y1=210.0,
            x2=350.0,
            y2=340.0,
            stroke='#333333',
            stroke_width=1.0,
            semantic_role='fold_line',
        ),
        LineSlot(
            id='slot.fold_3',
            prompt='',
            x1=400.0,
            y1=210.0,
            x2=400.0,
            y2=340.0,
            stroke='#333333',
            stroke_width=1.0,
            semantic_role='fold_line',
        ),
        LineSlot(
            id='slot.fold_4',
            prompt='',
            x1=450.0,
            y1=210.0,
            x2=450.0,
            y2=340.0,
            stroke='#333333',
            stroke_width=1.0,
            semantic_role='fold_line',
        ),
        LineSlot(
            id='slot.fold_5',
            prompt='',
            x1=500.0,
            y1=210.0,
            x2=500.0,
            y2=340.0,
            stroke='#333333',
            stroke_width=1.0,
            semantic_role='fold_line',
        ),
        PolygonSlot(
            id='slot.bot_hex',
            prompt='',
            points=((350.788, 437.28000000000003),
             (320.802, 389.088),
             (350.788, 340.896),
             (399.856, 340.896),
             (429.842, 389.088),
             (399.856, 437.28000000000003)),
            stroke='#333333',
            stroke_width=2.0,
            fill='#CFCFCF',
            semantic_role='net',
        ),
    )
    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id='0012_전개도 모서리',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0012_전개도 모서리',
 'problem_type': 'geometry_net_edge_count',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '전개도를 접어서 만든 입체도형의 모서리는 모두 몇 개인가요?',
              'question': '주어진 전개도를 접어서 만든 입체도형(육각기둥)의 모서리 개수를 구하는 문제',
              'required_layout_ids': ['slot.top_hex',
                                      'slot.strip_rect',
                                      'slot.fold_1',
                                      'slot.fold_2',
                                      'slot.fold_3',
                                      'slot.fold_4',
                                      'slot.fold_5',
                                      'slot.bot_hex'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.net', 'type': 'net', 'base_shape': 'hexagon', 'side_faces': 6},
                        {'id': 'obj.result', 'type': 'prism', 'base_sides': 6}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'shape_identification_and_property',
                                         'description': '전개도를 분석하여 육각기둥임을 파악하고, 각기둥의 모서리 공식(n*3)을 '
                                                        '적용한다.'}}},
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'confidence': 1.0,
            'value': 18,
            'unit': '개',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0012_전개도 모서리',
 'problem_type': 'geometry_net_edge_count',
 'inputs': {'total_ticks': 1,
            'target_label': '',
            'target_ticks': 1,
            'target_count': 1,
            'unit': '개'},
 'given': [],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': 18,
             'actual': 18,
             'pass': True}],
 'answer': {'value': 18, 'unit': '개', 'derived_from': 'step.1'}}
