from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1143,
        height=368,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='absolute',
            slot_ids=('slot.question',
             'slot.road',
             'slot.house.1.body',
             'slot.house.1.roof',
             'slot.house.2.body',
             'slot.house.2.roof',
             'slot.house.3.body',
             'slot.house.3.roof',
             'slot.label.1.line1',
             'slot.label.1.line2',
             'slot.label.2.line1',
             'slot.label.2.line2',
             'slot.label.3.line1',
             'slot.label.3.line2',
             'slot.arc.total',
             'slot.text.total',
             'slot.arc.part',
             'slot.text.part'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.question',
            prompt='',
            text='석기네 집에서 한별이네 집까지의 거리는 몇 m입니까?',
            style_role='body',
            x=10.0,
            y=50.0,
            font_size=35,
            fill='#222222',
        ),
        LineSlot(
            id='slot.road',
            prompt='',
            x1=100.0,
            y1=235.0,
            x2=1040.0,
            y2=235.0,
            stroke='#666666',
            stroke_width=2.0,
        ),
        RectSlot(
            id='slot.house.1.body',
            prompt='',
            x=135.0,
            y=175.0,
            width=80.0,
            height=60.0,
            stroke='#444444',
            stroke_width=1.5,
            fill='#fef3c7',
        ),
        PolygonSlot(
            id='slot.house.1.roof',
            prompt='',
            points=((135.0, 175.0), (175.0, 145.0), (215.0, 175.0)),
            stroke='#444444',
            stroke_width=1.5,
            fill='#ef4444',
        ),
        TextSlot(
            id='slot.label.1.line1',
            prompt='',
            text='한초네',
            style_role='body',
            x=175.0,
            y=275.0,
            font_size=35,
            anchor='middle',
            fill='#222222',
        ),
        TextSlot(
            id='slot.label.1.line2',
            prompt='',
            text='집',
            style_role='body',
            x=175.0,
            y=315.0,
            font_size=35,
            anchor='middle',
            fill='#222222',
        ),
        RectSlot(
            id='slot.house.2.body',
            prompt='',
            x=542.5,
            y=175.0,
            width=80.0,
            height=60.0,
            stroke='#444444',
            stroke_width=1.5,
            fill='#dcfce7',
        ),
        PolygonSlot(
            id='slot.house.2.roof',
            prompt='',
            points=((542.5, 175.0), (582.5, 145.0), (622.5, 175.0)),
            stroke='#444444',
            stroke_width=1.5,
            fill='#10b981',
        ),
        TextSlot(
            id='slot.label.2.line1',
            prompt='',
            text='석기네',
            style_role='body',
            x=582.5,
            y=275.0,
            font_size=35,
            anchor='middle',
            fill='#222222',
        ),
        TextSlot(
            id='slot.label.2.line2',
            prompt='',
            text='집',
            style_role='body',
            x=582.5,
            y=315.0,
            font_size=35,
            anchor='middle',
            fill='#222222',
        ),
        RectSlot(
            id='slot.house.3.body',
            prompt='',
            x=932.5,
            y=175.0,
            width=80.0,
            height=60.0,
            stroke='#444444',
            stroke_width=1.5,
            fill='#dbeafe',
        ),
        PolygonSlot(
            id='slot.house.3.roof',
            prompt='',
            points=((932.5, 175.0), (972.5, 145.0), (1012.5, 175.0)),
            stroke='#444444',
            stroke_width=1.5,
            fill='#3b82f6',
        ),
        TextSlot(
            id='slot.label.3.line1',
            prompt='',
            text='한별이네',
            style_role='body',
            x=972.5,
            y=275.0,
            font_size=35,
            anchor='middle',
            fill='#222222',
        ),
        TextSlot(
            id='slot.label.3.line2',
            prompt='',
            text='집',
            style_role='body',
            x=972.5,
            y=315.0,
            font_size=35,
            anchor='middle',
            fill='#222222',
        ),
        PathSlot(
            id='slot.arc.total',
            prompt='',
            d='M 175 135 Q 573 20 972 135',
            stroke='#444444',
            stroke_width=2.0,
            stroke_dasharray='5,5',
            fill='none',
        ),
        TextSlot(
            id='slot.text.total',
            prompt='',
            text='732m',
            style_role='body',
            x=750.9855382064089,
            y=139.21659722772347,
            font_size=35,
            anchor='middle',
            fill='#444444',
        ),
        PathSlot(
            id='slot.arc.part',
            prompt='',
            d='M 182.06291262 151.9510089 Q 385.06291262 91.9510089 589.06291262 151.9510089',
            stroke='#444444',
            stroke_width=2.0,
            stroke_dasharray='5,5',
            fill='none',
        ),
        TextSlot(
            id='slot.text.part',
            prompt='',
            text='368m',
            style_role='body',
            x=365.286789609772,
            y=166.5034079089963,
            font_size=35,
            anchor='middle',
            fill='#444444',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='msedge_z9mZBoibP0',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_023',
    'problem_type': 'word_problem',
    'metadata': {'language': 'ko', 'question': '석기네 집에서 한별이네 집까지의 거리는 몇 m입니까?', 'instruction': ''},
    'domain': {   'objects': [   {   'id': 'obj1',
                                     'type': 'question',
                                     'text': '석기네 집에서 한별이네 집까지의 거리는 몇 m입니까?'},
                                 {'id': 'obj2', 'type': 'label', 'text': '한초네 집'},
                                 {'id': 'obj3', 'type': 'label', 'text': '석기네 집'},
                                 {'id': 'obj4', 'type': 'label', 'text': '한별이네 집'},
                                 {'id': 'obj5', 'type': 'number', 'value': 368, 'text': '368m'},
                                 {'id': 'obj6', 'type': 'number', 'value': 732, 'text': '732m'},
                                 {'id': 'obj7', 'type': 'unit', 'value': 'm', 'text': 'm'},
                                 {'id': 'obj8', 'type': 'segment', 'text': '한초네 집-석기네 집'},
                                 {'id': 'obj9', 'type': 'segment', 'text': '한초네 집-한별이네 집'},
                                 {'id': 'obj10', 'type': 'segment', 'text': '석기네 집-한별이네 집'}],
                  'relations': [   {   'id': 'rel1',
                                       'type': 'asks_for',
                                       'from_id': 'obj1',
                                       'to_id': 'obj10'},
                                   {   'id': 'rel2',
                                       'type': 'labels',
                                       'from_id': 'obj2',
                                       'to_id': 'obj8'},
                                   {   'id': 'rel3',
                                       'type': 'labels',
                                       'from_id': 'obj3',
                                       'to_id': 'obj8'},
                                   {   'id': 'rel4',
                                       'type': 'labels',
                                       'from_id': 'obj3',
                                       'to_id': 'obj10'},
                                   {   'id': 'rel5',
                                       'type': 'labels',
                                       'from_id': 'obj4',
                                       'to_id': 'obj9'},
                                   {   'id': 'rel6',
                                       'type': 'maps_to',
                                       'from_id': 'obj5',
                                       'to_id': 'obj8'},
                                   {   'id': 'rel7',
                                       'type': 'maps_to',
                                       'from_id': 'obj6',
                                       'to_id': 'obj9'},
                                   {   'id': 'rel8',
                                       'type': 'precedes',
                                       'from_id': 'obj2',
                                       'to_id': 'obj3'},
                                   {   'id': 'rel9',
                                       'type': 'precedes',
                                       'from_id': 'obj3',
                                       'to_id': 'obj4'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {'target': {'type': 'number', 'description': '정답'}, 'value': 364, 'unit': 'm'}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_023',
    'problem_type': 'word_problem',
    'inputs': {   'total_ticks': 364,
                  'target_label': '정답',
                  'target_ticks': 364,
                  'target_count': 364,
                  'unit': 'm'},
    'plan': ['전체 거리 732m에서 한초네 집 থেকে 석기네 집까지 368m를 빼면 석기네 집에서 한별이네 집까지는 364m입니다.'],
    'steps': [   {   'id': 'step.1',
                     'expr': '전체 거리 732m에서 한초네 집 থেকে 석기네 집까지 368m를 빼면 석기네 집에서 한별이네 집까지는 364m입니다.',
                     'value': 364}],
    'checks': [],
    'answer': {'value': 364, 'unit': 'm'}}
