from __future__ import annotations

from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot, fraction_slots


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=640,
        height=320,
        coordinate_mode="logical",
    )

    regions = (
        Region(
            id="region.stem",
            role="stem",
            flow="absolute",
            slot_ids=(
                "slot.title",
                "slot.eq.box",
                "slot.eq.blank",
                "slot.eq.mul",
                "slot.eq.left_frac.num",
                "slot.eq.left_frac.bar",
                "slot.eq.left_frac.den",
                "slot.eq.equal",
                "slot.eq.mixed.whole",
                "slot.eq.mixed.frac.num",
                "slot.eq.mixed.frac.bar",
                "slot.eq.mixed.frac.den",
            ),
        ),
    )

    slots = (
        TextSlot(
            id="slot.title",
            prompt="",
            text="□ 안에 알맞은 수를 구해 보시오.",
            style_role="body",
            x=10.0,
            y=45.0,
            font_size=40,
            fill="#2d2a2b",
        ),
        RectSlot(
            id="slot.eq.box",
            prompt="",
            x=170.0,
            y=88.0,
            width=346.0,
            height=126.0,
            rx=16.0,
            ry=16.0,
            stroke="#b6b6b8",
            stroke_width=3.2,
            fill="none",
        ),
        RectSlot(
            id="slot.eq.blank",
            prompt="",
            x=200.0,
            y=130.0,
            width=35.0,
            height=35.0,
            rx=6.0,
            ry=6.0,
            stroke="#2d2a2b",
            stroke_width=2.0,
            fill="none",
        ),
        TextSlot(
            id="slot.eq.mul",
            prompt="",
            text="×",
            style_role="body",
            x=245.0,
            y=161.0,
            font_size=40,
            fill="#2d2a2b",
        ),
        *fraction_slots(
            id_prefix="slot.eq.left_frac",
            numerator="7",
            denominator="10",
            x=324.0,
            numerator_y=130.0,
            bar_y=142.0,
            denominator_y=184.0,
            bar_width=54.0,
            font_size=40,
            fill="#2d2a2b",
            stroke="#2d2a2b",
            stroke_width=2.2,
        ),
        TextSlot(
            id="slot.eq.equal",
            prompt="",
            text="=",
            style_role="body",
            x=372.0,
            y=161.0,
            font_size=45,
            fill="#2d2a2b",
        ),
        TextSlot(
            id="slot.eq.mixed.whole",
            prompt="",
            text="4",
            style_role="body",
            x=416.0,
            y=160.0,
            font_size=45,
            fill="#2d2a2b",
        ),
        *fraction_slots(
            id_prefix="slot.eq.mixed.frac",
            numerator="1",
            denominator="5",
            x=468.0,
            numerator_y=132.0,
            bar_y=143.0,
            denominator_y=184.0,
            bar_width=34.0,
            font_size=45,
            fill="#2d2a2b",
            stroke="#2d2a2b",
            stroke_width=2.0,
        ),
    )

    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id="msedge_JyNCo4cod2",
        title="",
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_010',
    'problem_type': 'fill_in_blank',
    'metadata': {   'language': 'ko',
                    'question': '□ × 7/10 = 4 1/5',
                    'instruction': '□ 안에 알맞은 수를 구해 보시오.'},
    'domain': {   'objects': [   {   'id': 'obj_instruction',
                                     'type': 'instruction',
                                     'text': '□ 안에 알맞은 수를 구해 보시오.'},
                                 {   'id': 'obj_question',
                                     'type': 'question',
                                     'text': '□ × 7/10 = 4 1/5'},
                                 {'id': 'obj_blank', 'type': 'blank', 'text': '□'},
                                 {   'id': 'obj_fraction',
                                     'type': 'fraction',
                                     'value': '7/10',
                                     'text': '7/10'},
                                 {   'id': 'obj_mixed_number',
                                     'type': 'number',
                                     'value': '4 1/5',
                                     'text': '4 1/5'},
                                 {   'id': 'obj_equation',
                                     'type': 'equation',
                                     'text': '□ × 7/10 = 4 1/5'},
                                 {   'id': 'obj_operator',
                                     'type': 'operator',
                                     'value': '×',
                                     'text': '×'}],
                  'relations': [   {   'id': 'rel_contains_1',
                                       'type': 'contains',
                                       'from_id': 'obj_instruction',
                                       'to_id': 'obj_blank'},
                                   {   'id': 'rel_contains_2',
                                       'type': 'contains',
                                       'from_id': 'obj_question',
                                       'to_id': 'obj_equation'},
                                   {   'id': 'rel_defines_1',
                                       'type': 'defines',
                                       'from_id': 'obj_equation',
                                       'to_id': 'obj_blank'},
                                   {   'id': 'rel_applies_1',
                                       'type': 'applies_to',
                                       'from_id': 'obj_operator',
                                       'to_id': 'obj_equation'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {'target': {'type': 'number', 'description': '정답'}, 'value': 6, 'unit': ''}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_010',
    'problem_type': 'fill_in_blank',
    'inputs': {   'total_ticks': 6,
                  'target_label': '정답',
                  'target_ticks': 6,
                  'target_count': 6,
                  'unit': ''},
    'plan': [],
    'steps': [{'id': 'step.1', 'expr': '계산', 'value': 6}],
    'checks': [],
    'answer': {'value': 6, 'unit': ''}}
