from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1050,
        height=616,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.b1', 'slot.text_5', 'slot.b2', 'slot.b3', 'slot.b4'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.b1',
            prompt='',
            text='229+985를 다음과 같은 방법으로 계산하였습니다.\n□ 안에 알맞은 수를 써넣으시오.',
            style_role='body',
            x=71.39065551757812,
            y=101.47355270385742,
            font_size=44,
            fill='#111111',
        ),
        RectSlot(
            id='slot.rect_6',
            prompt='',
            x=77.65080261230469,
            y=252.62855529785156,
            width=900,
            height=127.73997497558594,
            stroke='#222',
            stroke_width=2.0,
            fill='none',
        ),
        TextSlot(
            id='slot.b2',
            prompt='',
            text='220과 980을 먼저 더하고 9와 5를 더한 후 두 수를 더합니다.',
            style_role='body',
            x=115.4915771484375,
            y=322.9292449951172,
            font_size=34,
            fill='#111111',
        ),
        TextSlot(
            id='slot.b3',
            prompt='',
            text='229+985=(220+□)+(□+5)=□+14=□',
            style_role='body',
            x=96.42572021484375,
            y=500.4971008300781,
            font_size=45,
            fill='#111111',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='msedge_2zziXaAZVd',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_001',
    'problem_type': 'fill_in_blank',
    'metadata': {   'language': 'ko',
                    'question': '229+985 = (220+□) + (□+5) = □ + 14 = □',
                    'instruction': '229+985를 다음과 같은 방법으로 계산하였습니다. □ 안에 알맞은 수를 써넣으시오.'},
    'domain': {   'objects': [   {'id': 'n229', 'type': 'number', 'value': 229, 'text': '229'},
                                 {'id': 'n985', 'type': 'number', 'value': 985, 'text': '985'},
                                 {'id': 'n220', 'type': 'number', 'value': 220, 'text': '220'},
                                 {'id': 'n980', 'type': 'number', 'value': 980, 'text': '980'},
                                 {'id': 'n9', 'type': 'number', 'value': 9, 'text': '9'},
                                 {'id': 'n5', 'type': 'number', 'value': 5, 'text': '5'},
                                 {'id': 'n14', 'type': 'number', 'value': 14, 'text': '14'},
                                 {'id': 'n1200', 'type': 'number', 'value': 1200, 'text': '1200'},
                                 {'id': 'n1214', 'type': 'number', 'value': 1214, 'text': '1214'},
                                 {'id': 'blank1', 'type': 'blank', 'text': '220+□의 □'},
                                 {'id': 'blank2', 'type': 'blank', 'text': '(□+5)의 □'},
                                 {'id': 'blank3', 'type': 'blank', 'text': '= □ + 14의 □'},
                                 {'id': 'blank4', 'type': 'blank', 'text': '= □의 □'},
                                 {   'id': 'instr1',
                                     'type': 'instruction',
                                     'text': '□ 안에 알맞은 수를 써넣으시오.'},
                                 {   'id': 'q1',
                                     'type': 'question',
                                     'text': '229+985를 다음과 같은 방법으로 계산하였습니다.'},
                                 {   'id': 'expr1',
                                     'type': 'expression',
                                     'value': '229+985',
                                     'text': '229+985'},
                                 {   'id': 'expr2',
                                     'type': 'expression',
                                     'value': '(220+9)+(980+5)',
                                     'text': '(220+□)+(□+5)'},
                                 {   'id': 'expr3',
                                     'type': 'expression',
                                     'value': '1200+14',
                                     'text': '□+14'}],
                  'relations': [   {   'id': 'r1',
                                       'type': 'asks_for',
                                       'from_id': 'instr1',
                                       'to_id': 'blank1'},
                                   {   'id': 'r2',
                                       'type': 'asks_for',
                                       'from_id': 'instr1',
                                       'to_id': 'blank2'},
                                   {   'id': 'r3',
                                       'type': 'asks_for',
                                       'from_id': 'instr1',
                                       'to_id': 'blank3'},
                                   {   'id': 'r4',
                                       'type': 'asks_for',
                                       'from_id': 'instr1',
                                       'to_id': 'blank4'},
                                   {   'id': 'r5',
                                       'type': 'decomposes_into',
                                       'from_id': 'n229',
                                       'to_id': 'n220'},
                                   {   'id': 'r6',
                                       'type': 'decomposes_into',
                                       'from_id': 'n985',
                                       'to_id': 'n980'},
                                   {   'id': 'r7',
                                       'type': 'blank_value',
                                       'from_id': 'blank1',
                                       'to_id': 'n9'},
                                   {   'id': 'r8',
                                       'type': 'blank_value',
                                       'from_id': 'blank2',
                                       'to_id': 'n980'},
                                   {   'id': 'r9',
                                       'type': 'blank_value',
                                       'from_id': 'blank3',
                                       'to_id': 'n1200'},
                                   {   'id': 'r10',
                                       'type': 'blank_value',
                                       'from_id': 'blank4',
                                       'to_id': 'n1214'},
                                   {   'id': 'r11',
                                       'type': 'rewrites_to',
                                       'from_id': 'expr1',
                                       'to_id': 'expr2'},
                                   {   'id': 'r12',
                                       'type': 'rewrites_to',
                                       'from_id': 'expr2',
                                       'to_id': 'expr3'},
                                   {   'id': 'r13',
                                       'type': 'computes_to',
                                       'from_id': 'expr3',
                                       'to_id': 'n1214'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {   'target': {'type': 'number', 'description': '정답'},
                  'value': {'blank1': 9, 'blank2': 980, 'blank3': 1200, 'blank4': 1214},
                  'unit': ''}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_001',
    'problem_type': 'fill_in_blank',
    'inputs': {   'total_ticks': 0,
                  'target_label': '정답',
                  'target_ticks': 0,
                  'target_count': 0,
                  'unit': ''},
    'plan': [   '229는 220과 9로, 985는 980과 5로 나눌 수 있습니다. 따라서 229+985=(220+9)+(980+5)이고, 이를 다시 '
                '(220+980)+(9+5)로 묶으면 1200+14가 됩니다. 그래서 빈칸에 들어갈 수는 순서대로 9, 980, 1200, 1214입니다.'],
    'steps': [   {   'id': 'step.1',
                     'expr': '229는 220과 9로, 985는 980과 5로 나눌 수 있습니다. 따라서 229+985=(220+9)+(980+5)이고, '
                             '이를 다시 (220+980)+(9+5)로 묶으면 1200+14가 됩니다. 그래서 빈칸에 들어갈 수는 순서대로 9, 980, '
                             '1200, 1214입니다.',
                     'value': {'blank1': 9, 'blank2': 980, 'blank3': 1200, 'blank4': 1214}}],
    'checks': [],
    'answer': {'value': 3403, 'unit': ''}}
