from __future__ import annotations

from modu_math.dsl import Canvas, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot, fraction_slots


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=512,
        height=256,
        coordinate_mode="logical",
    )

    regions = (
        Region(
            id="region.stem",
            role="stem",
            flow="absolute",
            slot_ids=(
                "slot.title.blank",
                "slot.title.text",
                "slot.eq.f1.num",
                "slot.eq.f1.bar",
                "slot.eq.f1.den",
                "slot.eq.op1",
                "slot.eq.f2.num",
                "slot.eq.f2.bar",
                "slot.eq.f2.den",
                "slot.eq.eq1",
                "slot.eq.f3.num",
                "slot.eq.f3.bar",
                "slot.eq.f3.den",
                "slot.eq.op2",
                "slot.eq.blank.num",
                "slot.eq.blank.bar",
                "slot.eq.blank.den",
                "slot.eq.eq2",
                "slot.eq.result.blank",
            ),
        ),
    )

    slots = (
        RectSlot(
            id="slot.title.blank",
            prompt="",
            x=20.0,
            y=22.0,
            width=34.0,
            height=34.0,
            rx=6.0,
            ry=6.0,
            stroke="#333333",
            stroke_width=1.8,
            fill="none",
        ),
        TextSlot(
            id="slot.title.text",
            prompt="",
            text="안에 알맞은 수를 써넣으시오.",
            style_role="body",
            x=64.0,
            y=48.0,
            font_size=35,
            fill="#222222",
        ),
        *fraction_slots(
            id_prefix="slot.eq.f1",
            numerator="2",
            denominator="3",
            x=40.0,
            numerator_y=133.0,
            bar_y=146.0,
            denominator_y=186.0,
            bar_width=30.0,
            font_size=35,
            fill="#222222",
            stroke="#222222",
            stroke_width=2.0,
        ),
        TextSlot(
            id="slot.eq.op1",
            prompt="",
            text="÷",
            style_role="body",
            x=76.0,
            y=165.0,
            font_size=35,
            fill="#222222",
        ),
        *fraction_slots(
            id_prefix="slot.eq.f2",
            numerator="3",
            denominator="4",
            x=126.0,
            numerator_y=133.0,
            bar_y=146.0,
            denominator_y=186.0,
            bar_width=30.0,
            font_size=35,
            fill="#222222",
            stroke="#222222",
            stroke_width=2.0,
        ),
        TextSlot(
            id="slot.eq.eq1",
            prompt="",
            text="=",
            style_role="body",
            x=154.0,
            y=165.0,
            font_size=35,
            fill="#222222",
        ),
        *fraction_slots(
            id_prefix="slot.eq.f3",
            numerator="2",
            denominator="3",
            x=208.0,
            numerator_y=133.0,
            bar_y=146.0,
            denominator_y=186.0,
            bar_width=30.0,
            font_size=35,
            fill="#222222",
            stroke="#222222",
            stroke_width=2.0,
        ),
        TextSlot(
            id="slot.eq.op2",
            prompt="",
            text="×",
            style_role="body",
            x=244.0,
            y=165.0,
            font_size=35,
            fill="#222222",
        ),
        RectSlot(
            id="slot.eq.blank.num",
            prompt="",
            x=289.0,
            y=94.0,
            width=51.0,
            height=50.0,
            rx=5.0,
            ry=5.0,
            stroke="#333333",
            stroke_width=1.6,
            fill="none",
        ),
        LineSlot(
            id="slot.eq.blank.bar",
            prompt="",
            x1=290.0,
            y1=153.0,
            x2=339.0,
            y2=153.0,
            stroke="#333333",
            stroke_width=1.8,
        ),
        RectSlot(
            id="slot.eq.blank.den",
            prompt="",
            x=289.0,
            y=163.0,
            width=51.0,
            height=50.0,
            rx=5.0,
            ry=5.0,
            stroke="#333333",
            stroke_width=1.6,
            fill="none",
        ),
        TextSlot(
            id="slot.eq.eq2",
            prompt="",
            text="=",
            style_role="body",
            x=350.0,
            y=165.0,
            font_size=35,
            fill="#222222",
        ),
        RectSlot(
            id="slot.eq.result.blank",
            prompt="",
            x=398.0,
            y=112.0,
            width=60.0,
            height=85.0,
            rx=5.0,
            ry=5.0,
            stroke="#333333",
            stroke_width=1.8,
            fill="none",
        ),
    )

    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id="msedge_QTZDAUKaxK",
        title="",
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_018',
    'problem_type': 'fill_in_blank',
    'metadata': {   'language': 'ko',
                    'question': '2/3 ÷ 3/4 = 2/3 × [ ]/[ ] = [ ]',
                    'instruction': '안에 알맞은 수를 써넣으시오.'},
    'domain': {   'objects': [   {   'id': 'instr1',
                                     'type': 'instruction',
                                     'text': '안에 알맞은 수를 써넣으시오.'},
                                 {   'id': 'eq1',
                                     'type': 'equation',
                                     'text': '2/3 ÷ 3/4 = 2/3 × [ ]/[ ] = [ ]'},
                                 {'id': 'frac1', 'type': 'fraction', 'value': '2/3', 'text': '2/3'},
                                 {'id': 'op1', 'type': 'operator', 'value': '÷', 'text': '÷'},
                                 {'id': 'frac2', 'type': 'fraction', 'value': '3/4', 'text': '3/4'},
                                 {'id': 'op2', 'type': 'operator', 'value': '×', 'text': '×'},
                                 {'id': 'blank1', 'type': 'blank'},
                                 {'id': 'blank2', 'type': 'blank'},
                                 {'id': 'blank3', 'type': 'blank'}],
                  'relations': [   {   'id': 'rel1',
                                       'type': 'contains',
                                       'from_id': 'eq1',
                                       'to_id': 'frac1'},
                                   {   'id': 'rel2',
                                       'type': 'contains',
                                       'from_id': 'eq1',
                                       'to_id': 'frac2'},
                                   {   'id': 'rel3',
                                       'type': 'contains',
                                       'from_id': 'eq1',
                                       'to_id': 'blank1'},
                                   {   'id': 'rel4',
                                       'type': 'contains',
                                       'from_id': 'eq1',
                                       'to_id': 'blank2'},
                                   {   'id': 'rel5',
                                       'type': 'contains',
                                       'from_id': 'eq1',
                                       'to_id': 'blank3'},
                                   {   'id': 'rel6',
                                       'type': 'evaluates_to',
                                       'from_id': 'eq1',
                                       'to_id': 'blank3'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {   'target': {'type': 'number', 'description': '정답'},
                  'value': ['4', '3', '8/9'],
                  'unit': ''}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_018',
    'problem_type': 'fill_in_blank',
    'inputs': {   'total_ticks': 0,
                  'target_label': '정답',
                  'target_ticks': 0,
                  'target_count': 0,
                  'unit': ''},
    'plan': ['나눗셈을 역수의 곱셈으로 바꾸면 2/3 × 4/3 = 8/9 이다.'],
    'steps': [   {   'id': 'step.1',
                     'expr': '나눗셈을 역수의 곱셈으로 바꾸면 2/3 × 4/3 = 8/9 이다.',
                     'value': ['4', '3', '8/9']}],
    'checks': [],
    'answer': {'value': 7, 'unit': ''}}
