from __future__ import annotations

from modu_math.dsl import Canvas, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1112,
        height=382,
        coordinate_mode="logical",
    )

    regions = (
        Region(
            id="region.stem",
            role="stem",
            flow="absolute",
            slot_ids=(
                "slot.title.blank",
                "slot.title.text",
                "slot.left.label",
                "slot.left.top.h.blank",
                "slot.left.top.t",
                "slot.left.top.o",
                "slot.left.minus",
                "slot.left.mid.h",
                "slot.left.mid.t.blank",
                "slot.left.mid.o.blank",
                "slot.left.bar",
                "slot.left.bot.h",
                "slot.left.bot.t",
                "slot.left.bot.o",
                "slot.right.label",
                "slot.right.top.h",
                "slot.right.top.t.blank",
                "slot.right.top.o",
                "slot.right.minus",
                "slot.right.mid.h",
                "slot.right.mid.t",
                "slot.right.mid.o.blank",
                "slot.right.bar",
                "slot.right.bot.h.blank",
                "slot.right.bot.t",
                "slot.right.bot.o",
            ),
        ),
    )

    slots = (
        RectSlot(
            id="slot.title.blank",
            prompt="",
            x=34.0,
            y=30.0,
            width=48.0,
            height=44.0,
            stroke="#444444",
            stroke_width=2.0,
            fill="none",
        ),
        TextSlot(
            id="slot.title.text",
            prompt="",
            text="안에 알맞은 숫자를 써넣으시오.",
            style_role="body",
            x=96.0,
            y=66.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.label",
            prompt="",
            text="(1)",
            style_role="body",
            x=38.0,
            y=170.0,
            font_size=35,
            fill="#222222",
        ),
        RectSlot(
            id="slot.left.top.h.blank",
            prompt="",
            x=190.0,
            y=132.0,
            width=60.0,
            height=60.0,
            stroke="#666666",
            stroke_width=2.0,
            fill="none",
        ),
        TextSlot(
            id="slot.left.top.t",
            prompt="",
            text="8",
            style_role="body",
            x=278.0,
            y=176.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.top.o",
            prompt="",
            text="3",
            style_role="body",
            x=348.0,
            y=176.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.minus",
            prompt="",
            text="−",
            style_role="body",
            x=132.0,
            y=252.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.mid.h",
            prompt="",
            text="4",
            style_role="body",
            x=208.0,
            y=252.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        RectSlot(
            id="slot.left.mid.t.blank",
            prompt="",
            x=254.0,
            y=212.0,
            width=60.0,
            height=60.0,
            stroke="#666666",
            stroke_width=2.0,
            fill="none",
        ),
        RectSlot(
            id="slot.left.mid.o.blank",
            prompt="",
            x=324.0,
            y=212.0,
            width=60.0,
            height=60.0,
            stroke="#666666",
            stroke_width=2.0,
            fill="none",
        ),
        LineSlot(
            id="slot.left.bar",
            prompt="",
            x1=114.0,
            y1=290.0,
            x2=392.0,
            y2=290.0,
            stroke="#333333",
            stroke_width=2.0,
        ),
        TextSlot(
            id="slot.left.bot.h",
            prompt="",
            text="4",
            style_role="body",
            x=208.0,
            y=342.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.bot.t",
            prompt="",
            text="8",
            style_role="body",
            x=278.0,
            y=342.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.bot.o",
            prompt="",
            text="6",
            style_role="body",
            x=348.0,
            y=342.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.label",
            prompt="",
            text="(2)",
            style_role="body",
            x=710.0,
            y=170.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.top.h",
            prompt="",
            text="6",
            style_role="body",
            x=922.0,
            y=176.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        RectSlot(
            id="slot.right.top.t.blank",
            prompt="",
            x=958.0,
            y=132.0,
            width=60.0,
            height=60.0,
            stroke="#666666",
            stroke_width=2.0,
            fill="none",
        ),
        TextSlot(
            id="slot.right.top.o",
            prompt="",
            text="5",
            style_role="body",
            x=1052.0,
            y=176.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.minus",
            prompt="",
            text="−",
            style_role="body",
            x=808.0,
            y=252.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.mid.h",
            prompt="",
            text="2",
            style_role="body",
            x=922.0,
            y=252.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.mid.t",
            prompt="",
            text="3",
            style_role="body",
            x=987.0,
            y=252.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        RectSlot(
            id="slot.right.mid.o.blank",
            prompt="",
            x=1022.0,
            y=212.0,
            width=60.0,
            height=60.0,
            stroke="#666666",
            stroke_width=2.0,
            fill="none",
        ),
        LineSlot(
            id="slot.right.bar",
            prompt="",
            x1=790.0,
            y1=290.0,
            x2=1068.0,
            y2=290.0,
            stroke="#333333",
            stroke_width=2.0,
        ),
        RectSlot(
            id="slot.right.bot.h.blank",
            prompt="",
            x=892.0,
            y=302.0,
            width=60.0,
            height=60.0,
            stroke="#666666",
            stroke_width=2.0,
            fill="none",
        ),
        TextSlot(
            id="slot.right.bot.t",
            prompt="",
            text="7",
            style_role="body",
            x=987.0,
            y=342.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.bot.o",
            prompt="",
            text="6",
            style_role="body",
            x=1052.0,
            y=342.0,
            anchor="middle",
            font_size=35,
            fill="#222222",
        ),
    )

    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id="msedge_NbzkRH7yFC",
        title="",
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_013',
    'problem_type': 'fill_in_blank',
    'metadata': {   'language': 'ko',
                    'question': '(1) □83 - 4□□ = 486\n(2) 6□5 - 23□ = □76',
                    'instruction': '□ 안에 알맞은 숫자를 써넣으시오.'},
    'domain': {   'objects': [   {   'id': 'instr1',
                                     'type': 'instruction',
                                     'text': '□ 안에 알맞은 숫자를 써넣으시오.'},
                                 {'id': 'q1', 'type': 'question', 'text': '(1) □83 - 4□□ = 486'},
                                 {'id': 'q2', 'type': 'question', 'text': '(2) 6□5 - 23□ = □76'},
                                 {   'id': 'b1',
                                     'type': 'blank',
                                     'text': '(1) hundreds digit of minuend'},
                                 {   'id': 'b2',
                                     'type': 'blank',
                                     'text': '(1) tens digit of subtrahend'},
                                 {   'id': 'b3',
                                     'type': 'blank',
                                     'text': '(1) ones digit of subtrahend'},
                                 {'id': 'b4', 'type': 'blank', 'text': '(2) tens digit of minuend'},
                                 {   'id': 'b5',
                                     'type': 'blank',
                                     'text': '(2) ones digit of subtrahend'},
                                 {   'id': 'b6',
                                     'type': 'blank',
                                     'text': '(2) hundreds digit of result'}],
                  'relations': [   {   'id': 'r1',
                                       'type': 'asks_for',
                                       'from_id': 'instr1',
                                       'to_id': 'q1'},
                                   {   'id': 'r2',
                                       'type': 'asks_for',
                                       'from_id': 'instr1',
                                       'to_id': 'q2'},
                                   {'id': 'r3', 'type': 'contains', 'from_id': 'q1', 'to_id': 'b1'},
                                   {'id': 'r4', 'type': 'contains', 'from_id': 'q1', 'to_id': 'b2'},
                                   {'id': 'r5', 'type': 'contains', 'from_id': 'q1', 'to_id': 'b3'},
                                   {'id': 'r6', 'type': 'contains', 'from_id': 'q2', 'to_id': 'b4'},
                                   {'id': 'r7', 'type': 'contains', 'from_id': 'q2', 'to_id': 'b5'},
                                   {   'id': 'r8',
                                       'type': 'contains',
                                       'from_id': 'q2',
                                       'to_id': 'b6'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {   'target': {'type': 'number', 'description': '정답'},
                  'value': [9, 9, 7, 1, 9, 3],
                  'unit': ''}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_013',
    'problem_type': 'fill_in_blank',
    'inputs': {   'total_ticks': 0,
                  'target_label': '정답',
                  'target_ticks': 0,
                  'target_count': 0,
                  'unit': ''},
    'plan': [   '(1) [ ]83 - 4[ ][ ] = 486 gives 983 - 497 = 486, so blanks are 9, 9, 7. (2) 6[ ]5 '
                '- 23[ ] = [ ]76 gives 615 - 239 = 376, so blanks are 1, 9, 3.'],
    'steps': [   {   'id': 'step.1',
                     'expr': '(1) [ ]83 - 4[ ][ ] = 486 gives 983 - 497 = 486, so blanks are 9, 9, '
                             '7. (2) 6[ ]5 - 23[ ] = [ ]76 gives 615 - 239 = 376, so blanks are 1, '
                             '9, 3.',
                     'value': [9, 9, 7, 1, 9, 3]}],
    'checks': [],
    'answer': {'value': 38, 'unit': ''}}
