from __future__ import annotations

from modu_math.dsl import Canvas, LineSlot, PathSlot, ProblemTemplate, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1016,
        height=286,
        coordinate_mode="logical",
    )

    regions = (
        Region(
            id="region.stem",
            role="stem",
            flow="absolute",
            slot_ids=(
                "slot.title",
                "slot.label.left",
                "slot.label.right",
                "slot.left.oval",
                "slot.left.divide.h",
                "slot.left.divide.v",
                "slot.left.num.a",
                "slot.left.num.b",
                "slot.right.oval",
                "slot.right.divide.h",
                "slot.right.divide.v",
                "slot.right.num.a",
                "slot.right.num.b",
            ),
        ),
    )

    slots = (
        TextSlot(
            id="slot.title",
            prompt="",
            text="빈 곳에 두 수의 차를 써넣으시오.",
            style_role="body",
            x=8.0,
            y=46.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.label.left",
            prompt="",
            text="(1)",
            style_role="body",
            x=8.0,
            y=142.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.label.right",
            prompt="",
            text="(2)",
            style_role="body",
            x=578.0,
            y=142.0,
            font_size=35,
            fill="#222222",
        ),
        PathSlot(
            id="slot.left.oval",
            prompt="",
            d="M 94 190 A 180 75 0 1 0 454 190 A 180 75 0 1 0 94 190",
            stroke="#b9db79",
            stroke_width=3.0,
            fill="none",
        ),
        LineSlot(
            id="slot.left.divide.h",
            prompt="",
            x1=96.0,
            y1=190.0,
            x2=452.0,
            y2=190.0,
            stroke="#b9db79",
            stroke_width=3.0,
        ),
        LineSlot(
            id="slot.left.divide.v",
            prompt="",
            x1=274.0,
            y1=115.0,
            x2=274.0,
            y2=190.0,
            stroke="#b9db79",
            stroke_width=3.0,
        ),
        TextSlot(
            id="slot.left.num.a",
            prompt="",
            text="350",
            style_role="body",
            x=154.0,
            y=173.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.left.num.b",
            prompt="",
            text="186",
            style_role="body",
            x=301.0,
            y=173.0,
            font_size=35,
            fill="#222222",
        ),
        PathSlot(
            id="slot.right.oval",
            prompt="",
            d="M 656 190 A 180 75 0 1 0 1014 190 A 180 75 0 1 0 656 190",
            stroke="#87b5eb",
            stroke_width=3.0,
            fill="none",
        ),
        LineSlot(
            id="slot.right.divide.h",
            prompt="",
            x1=658.0,
            y1=190.0,
            x2=1012.0,
            y2=190.0,
            stroke="#87b5eb",
            stroke_width=3.0,
        ),
        LineSlot(
            id="slot.right.divide.v",
            prompt="",
            x1=835.0,
            y1=115.0,
            x2=835.0,
            y2=190.0,
            stroke="#87b5eb",
            stroke_width=3.0,
        ),
        TextSlot(
            id="slot.right.num.a",
            prompt="",
            text="426",
            style_role="body",
            x=727.0,
            y=173.0,
            font_size=35,
            fill="#222222",
        ),
        TextSlot(
            id="slot.right.num.b",
            prompt="",
            text="702",
            style_role="body",
            x=850.0,
            y=173.0,
            font_size=35,
            fill="#222222",
        ),
    )

    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id="msedge_mz1O7IIvt3",
        title="",
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_012',
    'problem_type': 'fill_in_blank',
    'metadata': {   'language': 'ko',
                    'question': '(1) 350 186\n(2) 426 702',
                    'instruction': '빈 곳에 두 수의 차를 써넣으시오.'},
    'domain': {   'objects': [   {   'id': 'obj_instruction',
                                     'type': 'instruction',
                                     'text': '빈 곳에 두 수의 차를 써넣으시오.'},
                                 {'id': 'obj_q1', 'type': 'question', 'value': 1, 'text': '(1)'},
                                 {'id': 'obj_q2', 'type': 'question', 'value': 2, 'text': '(2)'},
                                 {'id': 'obj_n350', 'type': 'number', 'value': 350, 'text': '350'},
                                 {'id': 'obj_n186', 'type': 'number', 'value': 186, 'text': '186'},
                                 {'id': 'obj_n426', 'type': 'number', 'value': 426, 'text': '426'},
                                 {'id': 'obj_n702', 'type': 'number', 'value': 702, 'text': '702'},
                                 {'id': 'obj_blank1', 'type': 'blank'},
                                 {'id': 'obj_blank2', 'type': 'blank'},
                                 {'id': 'obj_shape1', 'type': 'shape', 'text': 'oval'},
                                 {'id': 'obj_shape2', 'type': 'shape', 'text': 'oval'}],
                  'relations': [   {   'id': 'rel1',
                                       'type': 'asks_for',
                                       'from_id': 'obj_instruction',
                                       'to_id': 'obj_blank1'},
                                   {   'id': 'rel2',
                                       'type': 'asks_for',
                                       'from_id': 'obj_instruction',
                                       'to_id': 'obj_blank2'},
                                   {   'id': 'rel3',
                                       'type': 'contains',
                                       'from_id': 'obj_shape1',
                                       'to_id': 'obj_n350'},
                                   {   'id': 'rel4',
                                       'type': 'contains',
                                       'from_id': 'obj_shape1',
                                       'to_id': 'obj_n186'},
                                   {   'id': 'rel5',
                                       'type': 'contains',
                                       'from_id': 'obj_shape2',
                                       'to_id': 'obj_n426'},
                                   {   'id': 'rel6',
                                       'type': 'contains',
                                       'from_id': 'obj_shape2',
                                       'to_id': 'obj_n702'},
                                   {   'id': 'rel7',
                                       'type': 'contains',
                                       'from_id': 'obj_shape1',
                                       'to_id': 'obj_blank1'},
                                   {   'id': 'rel8',
                                       'type': 'contains',
                                       'from_id': 'obj_shape2',
                                       'to_id': 'obj_blank2'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {   'target': {'type': 'number', 'description': '정답'},
                  'value': [164, 276],
                  'unit': ''}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_012',
    'problem_type': 'fill_in_blank',
    'inputs': {   'total_ticks': 0,
                  'target_label': '정답',
                  'target_ticks': 0,
                  'target_count': 0,
                  'unit': ''},
    'plan': ['두 수의 차를 구하면 (1) 350-186=164, (2) 702-426=276이다.'],
    'steps': [   {   'id': 'step.1',
                     'expr': '두 수의 차를 구하면 (1) 350-186=164, (2) 702-426=276이다.',
                     'value': [164, 276]}],
    'checks': [],
    'answer': {'value': 440, 'unit': ''}}
