from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=900,
        height=350,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='absolute',
            slot_ids=('slot.instr',
             'slot.q1.n',
             'slot.q1.f.num',
             'slot.q1.f.bar',
             'slot.q1.f.den',
             'slot.q2.f1.num',
             'slot.q2.f1.bar',
             'slot.q2.f1.den',
             'slot.q2.div',
             'slot.q2.f2.num',
             'slot.q2.f2.bar',
             'slot.q2.f2.den',
             'slot.q3.n',
             'slot.q3.f.num',
             'slot.q3.f.bar',
             'slot.q3.f.den',
             'slot.blank1',
             'slot.blank2',
             'slot.blank3'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.instr',
            prompt='',
            text='계산 결과가 다른 하나에 ○표 하시오.',
            style_role='body',
            x=20.0,
            y=50.0,
            font_size=35,
            fill='#111111',
        ),
        TextSlot(
            id='slot.q1.n',
            prompt='',
            text='3 ÷',
            style_role='body',
            x=36.652755060852236,
            y=150.0,
            font_size=35,
            fill='#111111',
        ),
        TextSlot(
            id='slot.q1.f.num',
            prompt='',
            text='1',
            style_role='body',
            x=135.0,
            y=128.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        LineSlot(
            id='slot.q1.f.bar',
            prompt='',
            x1=112.5,
            y1=140.0,
            x2=157.5,
            y2=140.0,
            stroke='#111111',
            stroke_width=2.0,
        ),
        TextSlot(
            id='slot.q1.f.den',
            prompt='',
            text='2',
            style_role='body',
            x=135.0,
            y=177.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        TextSlot(
            id='slot.blank1',
            prompt='',
            text='(        )',
            style_role='body',
            x=70.0,
            y=240.0,
            font_size=35,
            fill='#111111',
        ),
        TextSlot(
            id='slot.q2.f1.num',
            prompt='',
            text='12',
            style_role='body',
            x=320.0,
            y=128.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        LineSlot(
            id='slot.q2.f1.bar',
            prompt='',
            x1=292.5,
            y1=140.0,
            x2=347.5,
            y2=140.0,
            stroke='#111111',
            stroke_width=2.0,
        ),
        TextSlot(
            id='slot.q2.f1.den',
            prompt='',
            text='17',
            style_role='body',
            x=320.0,
            y=177.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        TextSlot(
            id='slot.q2.div',
            prompt='',
            text='÷',
            style_role='body',
            x=363.8773029556639,
            y=150.0,
            font_size=35,
            fill='#111111',
        ),
        TextSlot(
            id='slot.q2.f2.num',
            prompt='',
            text='5',
            style_role='body',
            x=440.0,
            y=128.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        LineSlot(
            id='slot.q2.f2.bar',
            prompt='',
            x1=412.5,
            y1=140.0,
            x2=467.5,
            y2=140.0,
            stroke='#111111',
            stroke_width=2.0,
        ),
        TextSlot(
            id='slot.q2.f2.den',
            prompt='',
            text='17',
            style_role='body',
            x=440.0,
            y=177.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        TextSlot(
            id='slot.blank2',
            prompt='',
            text='(        )',
            style_role='body',
            x=364.4699419834839,
            y=240.0,
            font_size=35,
            fill='#111111',
        ),
        TextSlot(
            id='slot.q3.n',
            prompt='',
            text='4 ÷',
            style_role='body',
            x=609.9896405476527,
            y=153.33684307955167,
            font_size=35,
            fill='#111111',
        ),
        TextSlot(
            id='slot.q3.f.num',
            prompt='',
            text='2',
            style_role='body',
            x=705.0,
            y=128.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        LineSlot(
            id='slot.q3.f.bar',
            prompt='',
            x1=682.5,
            y1=140.0,
            x2=727.5,
            y2=140.0,
            stroke='#111111',
            stroke_width=2.0,
        ),
        TextSlot(
            id='slot.q3.f.den',
            prompt='',
            text='3',
            style_role='body',
            x=705.0,
            y=177.0,
            font_size=35,
            anchor='middle',
            fill='#111111',
        ),
        TextSlot(
            id='slot.blank3',
            prompt='',
            text='(        )',
            style_role='body',
            x=640.0,
            y=240.0,
            font_size=35,
            fill='#111111',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='msedge_ZUpk9809oW',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_026',
    'problem_type': 'arithmetic',
    'metadata': {   'language': 'ko',
                    'question': '다음 세 식 중 계산 결과가 다른 하나에 ○표 하시오.',
                    'instruction': '계산 결과가 다른 하나에 ○표 하시오.'},
    'domain': {   'objects': [   {   'id': 'instr_1',
                                     'type': 'instruction',
                                     'text': '계산 결과가 다른 하나에 ○표 하시오.'},
                                 {   'id': 'q_1',
                                     'type': 'question',
                                     'text': '다음 세 식 중 계산 결과가 다른 하나에 ○표 하시오.'},
                                 {   'id': 'expr_1',
                                     'type': 'expression',
                                     'value': '3 ÷ 1/2',
                                     'text': '3 ÷ 1/2'},
                                 {   'id': 'expr_2',
                                     'type': 'expression',
                                     'value': '12/17 ÷ 5/17',
                                     'text': '12/17 ÷ 5/17'},
                                 {   'id': 'expr_3',
                                     'type': 'expression',
                                     'value': '4 ÷ 2/3',
                                     'text': '4 ÷ 2/3'},
                                 {'id': 'blank_1', 'type': 'blank', 'text': '(    )'},
                                 {'id': 'blank_2', 'type': 'blank', 'text': '(    )'},
                                 {'id': 'blank_3', 'type': 'blank', 'text': '(    )'}],
                  'relations': [   {   'id': 'rel_1',
                                       'type': 'asks_for',
                                       'from_id': 'instr_1',
                                       'to_id': 'q_1'},
                                   {   'id': 'rel_2',
                                       'type': 'applies_to',
                                       'from_id': 'instr_1',
                                       'to_id': 'expr_1'},
                                   {   'id': 'rel_3',
                                       'type': 'applies_to',
                                       'from_id': 'instr_1',
                                       'to_id': 'expr_2'},
                                   {   'id': 'rel_4',
                                       'type': 'applies_to',
                                       'from_id': 'instr_1',
                                       'to_id': 'expr_3'},
                                   {   'id': 'rel_5',
                                       'type': 'contains',
                                       'from_id': 'q_1',
                                       'to_id': 'expr_1'},
                                   {   'id': 'rel_6',
                                       'type': 'contains',
                                       'from_id': 'q_1',
                                       'to_id': 'expr_2'},
                                   {   'id': 'rel_7',
                                       'type': 'contains',
                                       'from_id': 'q_1',
                                       'to_id': 'expr_3'},
                                   {   'id': 'rel_8',
                                       'type': 'labels',
                                       'from_id': 'blank_1',
                                       'to_id': 'expr_1'},
                                   {   'id': 'rel_9',
                                       'type': 'labels',
                                       'from_id': 'blank_2',
                                       'to_id': 'expr_2'},
                                   {   'id': 'rel_10',
                                       'type': 'labels',
                                       'from_id': 'blank_3',
                                       'to_id': 'expr_3'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {   'target': {'type': 'number', 'description': '정답'},
                  'value': '12/17 ÷ 5/17',
                  'unit': ''}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_026',
    'problem_type': 'arithmetic',
    'inputs': {   'total_ticks': 0,
                  'target_label': '정답',
                  'target_ticks': 0,
                  'target_count': 0,
                  'unit': ''},
    'plan': [   'The prompt asks to identify the expression with a different result, but the image '
                'does not explicitly indicate which one is marked.'],
    'steps': [   {   'id': 'step.1',
                     'expr': 'The prompt asks to identify the expression with a different result, '
                             'but the image does not explicitly indicate which one is marked.',
                     'value': '12/17 ÷ 5/17'}],
    'checks': [],
    'answer': {'value': 0, 'unit': ''}}
