from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle, fraction_slots

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=696,
        height=540,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='absolute',
            slot_ids=('slot.title.pre',
             'slot.title.base.num',
             'slot.title.base.bar',
             'slot.title.base.den',
             'slot.title.mid',
             'slot.title.area.whole',
             'slot.title.area.frac.num',
             'slot.title.area.frac.bar',
             'slot.title.area.frac.den',
             'slot.title.area.suffix',
             'slot.title.q1',
             'slot.diagram.parallelogram',
             'slot.diagram.guide',
             'slot.label.area.prefix',
             'slot.label.area.whole',
             'slot.label.area.frac.num',
             'slot.label.area.frac.bar',
             'slot.label.area.frac.den',
             'slot.label.area.suffix',
             'slot.label.arrow',
             'slot.label.arrow.head',
             'slot.base.num',
             'slot.base.bar',
             'slot.base.den',
             'slot.base.unit'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.title.pre',
            prompt='',
            text='밑변의 길이가',
            style_role='body',
            x=6.0,
            y=48.0,
            font_size=34,
            fill='#111111',
        ),
        *fraction_slots(
            id_prefix='slot.title.base',
            numerator='2',
            denominator='3',
            x=253.0,
            numerator_y=26.0,
            denominator_y=70.0,
            bar_y=40.0,
            bar_width=40.0,
            font_size=34,
            fill='#222222',
            stroke='#222222',
            stroke_width=1.8,
        ),
        TextSlot(
            id='slot.title.mid',
            prompt='',
            text='m인 평행사변형의 넓이가',
            style_role='body',
            x=282.0,
            y=48.0,
            font_size=34,
            fill='#111111',
        ),
        TextSlot(
            id='slot.title.area.whole',
            prompt='',
            text='1',
            style_role='body',
            x=6.0,
            y=112.0,
            font_size=34,
            fill='#111111',
        ),
        *fraction_slots(
            id_prefix='slot.title.area.frac',
            numerator='1',
            denominator='4',
            x=50.0,
            numerator_y=92.0,
            denominator_y=132.0,
            bar_y=104.0,
            bar_width=34.0,
            font_size=30,
            fill='#111111',
            stroke='#111111',
            stroke_width=1.8,
        ),
        TextSlot(
            id='slot.title.area.suffix',
            prompt='',
            text='m²입니다. 이 평행사변형의 높이는 몇 m',
            style_role='body',
            x=80.0,
            y=112.0,
            font_size=34,
            fill='#111111',
        ),
        TextSlot(
            id='slot.title.q1',
            prompt='',
            text='입니까?',
            style_role='body',
            x=6.0,
            y=200.0,
            font_size=34,
            fill='#111111',
        ),
        PolygonSlot(
            id='slot.diagram.parallelogram',
            prompt='',
            points=((351.0, 282.0), (415.0, 283.0), (493.0, 457.0), (433.0, 456.0)),
            stroke='#333333',
            stroke_width=1.2,
            fill='#d9d9de',
        ),
        PathSlot(
            id='slot.diagram.guide',
            prompt='',
            d='M 418 456 Q 424 469 438 474',
            stroke='#333333',
            stroke_width=1.0,
            stroke_dasharray='4 4',
            fill='none',
        ),
        TextSlot(
            id='slot.label.area.prefix',
            prompt='',
            text='넓이:',
            style_role='body',
            x=141.42515325291674,
            y=378.23830091316745,
            font_size=31,
            fill='#111111',
        ),
        TextSlot(
            id='slot.label.area.whole',
            prompt='',
            text='1',
            style_role='body',
            x=215.42515325291674,
            y=378.23830091316745,
            font_size=31,
            fill='#111111',
        ),
        *fraction_slots(
            id_prefix='slot.label.area.frac',
            numerator='1',
            denominator='4',
            x=250,
            numerator_y=360.23830091316745,
            denominator_y=397.23830091316745,
            bar_y=369.23830091316745,
            bar_width=28.0,
            font_size=27,
            fill='#111111',
            stroke='#111111',
            stroke_width=1.6,
        ),
        TextSlot(
            id='slot.label.area.suffix',
            prompt='',
            text='m²',
            style_role='body',
            x=275,
            y=378.23830091316745,
            font_size=31,
            fill='#111111',
        ),
        LineSlot(
            id='slot.label.arrow',
            prompt='',
            x1=345.0,
            y1=369.0,
            x2=414.0,
            y2=371.0,
            stroke='#111111',
            stroke_width=1.2,
        ),
        PolygonSlot(
            id='slot.label.arrow.head',
            prompt='',
            points=((422.0, 371.0), (412.0, 366.0), (412.0, 376.0)),
            stroke='none',
            fill='#111111',
        ),
        *fraction_slots(
            id_prefix='slot.base',
            numerator='2',
            denominator='3',
            x=459.0,
            numerator_y=483.0,
            denominator_y=523.0,
            bar_y=495.0,
            bar_width=34.0,
            font_size=31,
            fill='#222222',
            stroke='#222222',
            stroke_width=1.8,
        ),
        TextSlot(
            id='slot.base.unit',
            prompt='',
            text='m',
            style_role='body',
            x=507.0,
            y=488.0,
            font_size=31,
            fill='#111111',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='p260422_006',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {   'problem_id': 'p260422_006',
    'problem_type': 'measurement',
    'metadata': {   'language': 'ko',
                    'question': '밑변의 길이가 2/3 m인 평행사변형의 넓이가 1 1/4 m^2입니다. 이 평행사변형의 높이는 몇 m입니까?',
                    'instruction': ''},
    'domain': {   'objects': [   {'id': 'obj1', 'type': 'fraction', 'value': '2/3', 'text': '2/3'},
                                 {   'id': 'obj2',
                                     'type': 'fraction',
                                     'value': '1 1/4',
                                     'text': '1 1/4'},
                                 {'id': 'obj3', 'type': 'unit', 'value': 'm', 'text': 'm'},
                                 {'id': 'obj4', 'type': 'unit', 'value': 'm^2', 'text': 'm^2'},
                                 {   'id': 'obj5',
                                     'type': 'shape',
                                     'value': 'parallelogram',
                                     'text': '평행사변형'},
                                 {   'id': 'obj6',
                                     'type': 'question',
                                     'text': '이 평행사변형의 높이는 몇 m입니까?'}],
                  'relations': [   {   'id': 'rel1',
                                       'type': 'labels',
                                       'from_id': 'obj1',
                                       'to_id': 'obj3'},
                                   {   'id': 'rel2',
                                       'type': 'labels',
                                       'from_id': 'obj2',
                                       'to_id': 'obj4'},
                                   {   'id': 'rel3',
                                       'type': 'asks_for',
                                       'from_id': 'obj6',
                                       'to_id': 'obj5'},
                                   {   'id': 'rel4',
                                       'type': 'references',
                                       'from_id': 'obj5',
                                       'to_id': 'obj1'},
                                   {   'id': 'rel5',
                                       'type': 'references',
                                       'from_id': 'obj5',
                                       'to_id': 'obj2'}],
                  'problem_solving': {'understand': {}, 'plan': {}, 'execute': {}, 'review': {}}},
    'answer': {'target': {'type': 'number', 'description': '정답'}, 'value': 1.875, 'unit': 'm'}}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'p260422_006',
    'problem_type': 'measurement',
    'inputs': {   'total_ticks': 1.875,
                  'target_label': '정답',
                  'target_ticks': 1.875,
                  'target_count': 1.875,
                  'unit': 'm'},
    'plan': ['평행사변형의 넓이 = 밑변 × 높이이므로 높이 = 1 1/4 ÷ 2/3 = 15/8 m = 1 7/8 m이다.'],
    'steps': [   {   'id': 'step.1',
                     'expr': '평행사변형의 넓이 = 밑변 × 높이이므로 높이 = 1 1/4 ÷ 2/3 = 15/8 m = 1 7/8 m이다.',
                     'value': 1.875}],
    'checks': [],
    'answer': {'value': 1.875, 'unit': 'm'}}
