from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=311,
        height=192,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.t1',
             'slot.blank_top',
             'slot.top_2',
             'slot.top_6',
             'slot.plus',
             'slot.mid_5',
             'slot.blank_mid',
             'slot.blank_low',
             'slot.ans_1',
             'slot.ans_3',
             'slot.ans_0',
             'slot.ans_4'),
        ),
    )
    slots = (
        RectSlot(
            id='slot.bg',
            prompt='',
            x=0.0,
            y=0.0,
            width=311.0,
            height=192.0,
            stroke='none',
            stroke_width=0.0,
            fill='none',
        ),
        TextSlot(
            id='slot.t1',
            prompt='',
            text='□ 안에 알맞은 수를 써넣으세요.',
            style_role='body',
            x=6.0,
            y=30.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
        ),
        RectSlot(
            id='slot.blank_top',
            prompt='',
            x=167.0,
            y=45.0,
            width=34.0,
            height=34.0,
            stroke='#666666',
            stroke_width=1.5,
            fill='none',
            semantic_role='answer_anchor',
        ),
        TextSlot(
            id='slot.top_2',
            prompt='',
            text='2',
            style_role='body',
            x=225.0,
            y=72.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.top_6',
            prompt='',
            text='6',
            style_role='body',
            x=265.0,
            y=72.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.plus',
            prompt='',
            text='+',
            style_role='body',
            x=140.0,
            y=116.0,
            font_size=34,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.mid_5',
            prompt='',
            text='5',
            style_role='body',
            x=184.0,
            y=115.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
        RectSlot(
            id='slot.blank_mid',
            prompt='',
            x=208.0,
            y=90.0,
            width=34.0,
            height=34.0,
            stroke='#666666',
            stroke_width=1.5,
            fill='none',
            semantic_role='answer_anchor',
        ),
        RectSlot(
            id='slot.blank_low',
            prompt='',
            x=248.0,
            y=90.0,
            width=34.0,
            height=34.0,
            stroke='#666666',
            stroke_width=1.5,
            fill='none',
            semantic_role='answer_anchor',
        ),
        RectSlot(
            id='slot.sep',
            prompt='',
            x=112.0,
            y=144.0,
            width=182.0,
            height=1.0,
            stroke='none',
            stroke_width=0.0,
            fill='#777777',
        ),
        TextSlot(
            id='slot.ans_1',
            prompt='',
            text='1',
            style_role='body',
            x=145.0,
            y=174.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.ans_3',
            prompt='',
            text='3',
            style_role='body',
            x=184.0,
            y=174.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.ans_0',
            prompt='',
            text='0',
            style_role='body',
            x=225.0,
            y=174.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
        TextSlot(
            id='slot.ans_4',
            prompt='',
            text='4',
            style_role='body',
            x=265.0,
            y=174.0,
            font_size=17,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='label',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='0003_세로셈 빈칸 채우기',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0003_세로셈 빈칸 채우기',
 'problem_type': 'arithmetic_vertical_addition_puzzle',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '□ 안에 알맞은 수를 써넣으세요.',
              'question': '세로 덧셈식 [□26] + [5□□] = [1304]에서 빈칸에 알맞은 숫자를 구하는 문제',
              'required_layout_ids': ['slot.bg',
                                      'slot.blank_top',
                                      'slot.blank_mid',
                                      'slot.blank_low',
                                      'slot.sep'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.vertical_add',
                         'type': 'vertical_arithmetic',
                         'description': '[□26] + [5□□] = [1304]'}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'digit_analysis',
                                         'description': '일의 자리부터 시작하여 올림수를 고려하며 각 빈칸의 숫자를 찾아간다.'}}},
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'confidence': 1.0,
            'value': 0,
            'unit': '',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0003_세로셈 빈칸 채우기',
 'problem_type': 'arithmetic_vertical_addition_puzzle',
 'inputs': {'total_ticks': 1, 'target_label': '', 'target_ticks': 1, 'target_count': 1, 'unit': ''},
 'given': [],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': [7, 7, 8],
             'actual': [7, 7, 8],
             'pass': True}],
 'answer': {'value': 0, 'unit': '', 'derived_from': 'step.1'}}
