from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, TextSlot, LineSlot, Region


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2403",
        title="x를 구하시오. 소수 첫째 자리까지 반올림하시오.",
        canvas=Canvas(width=1400, height=900, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.problem_text",
                    "slot.diagram_box",
                    "slot.choice_1",
                    "slot.choice_2",
                    "slot.choice_3",
                    "slot.choice_4",
                    "slot.answer_overlay",
                    "slot.geom_ab",
                    "slot.geom_ac",
                    "slot.geom_bc",
                    "slot.geom_ad",
                    "slot.geom_perp_1",
                    "slot.geom_perp_2",
                    "slot.geom_tick_1",
                    "slot.geom_tick_2",
                    "slot.geom_len_left",
                    "slot.geom_len_x",
                    "slot.geom_len_y",
                    "slot.geom_angle_54",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.problem_text",
                prompt="",
                text="x를 구하시오. 소수 첫째 자리까지 반올림하시오.",
                style_role="question",
                x=40.0,
                y=90.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
            ),
            RectSlot(
                id="slot.diagram_box",
                prompt="",
                x=40.0,
                y=200.0,
                width=760.0,
                height=620.0,
                stroke="#D1D5DB",
                stroke_width=1.0,
                fill="none",
            ),
            TextSlot(
                id="slot.choice_1",
                prompt="",
                text="1. 18.8",
                style_role="question",
                x=860.0,
                y=320.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
            ),
            TextSlot(
                id="slot.choice_2",
                prompt="",
                text="2. 23.2",
                style_role="question",
                x=860.0,
                y=390.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
            ),
            TextSlot(
                id="slot.choice_3",
                prompt="",
                text="3. 25.9",
                style_role="question",
                x=860.0,
                y=460.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
            ),
            TextSlot(
                id="slot.choice_4",
                prompt="",
                text="4. 44.0",
                style_role="question",
                x=860.0,
                y=530.0,
                font_size=48,
                font_family="sans-serif",
                anchor="start",
            ),
            TextSlot(
                id="slot.answer_overlay",
                prompt="",
                text="정답: A (18.8)",
                style_role="note",
                x=1376.0,
                y=876.0,
                font_size=56,
                font_family="Malgun Gothic",
                anchor="end",
                fill="#D32222",
            ),
            LineSlot(
                id="slot.geom_ab",
                prompt="",
                x1=410.6,
                y1=250.0,
                x2=140.0,
                y2=700.0,
                stroke="#1976D2",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.geom_ac",
                prompt="",
                x1=410.6,
                y1=250.0,
                x2=680.0,
                y2=700.0,
                stroke="#1976D2",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.geom_bc",
                prompt="",
                x1=140.0,
                y1=700.0,
                x2=680.0,
                y2=700.0,
                stroke="#1976D2",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.geom_ad",
                prompt="",
                x1=410.6,
                y1=250.0,
                x2=406.0,
                y2=700.0,
                stroke="#1976D2",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.geom_perp_1",
                prompt="",
                x1=406.4,
                y1=666.0,
                x2=440.4,
                y2=666.0,
                stroke="#111111",
                stroke_width=2.4,
            ),
            LineSlot(
                id="slot.geom_perp_2",
                prompt="",
                x1=440.0,
                y1=700.0,
                x2=440.4,
                y2=666.0,
                stroke="#111111",
                stroke_width=2.4,
            ),
            LineSlot(
                id="slot.geom_tick_1",
                prompt="",
                x1=269.4,
                y1=508.2,
                x2=248.8,
                y2=495.8,
                stroke="#E91E63",
                stroke_width=3.0,
            ),
            LineSlot(
                id="slot.geom_tick_2",
                prompt="",
                x1=571.8,
                y1=495.8,
                x2=551.2,
                y2=508.2,
                stroke="#E91E63",
                stroke_width=3.0,
            ),
            TextSlot(
                id="slot.geom_len_left",
                prompt="",
                text="32",
                style_role="label",
                x=227.3,
                y=465.0,
                font_size=48,
                font_family="Malgun Gothic",
                anchor="start",
            ),
            TextSlot(
                id="slot.geom_len_x",
                prompt="",
                text="x",
                style_role="label",
                x=255.0,
                y=758.0,
                font_size=48,
                font_family="Malgun Gothic",
                anchor="start",
            ),
            TextSlot(
                id="slot.geom_len_y",
                prompt="",
                text="y",
                style_role="label",
                x=422.3,
                y=483.0,
                font_size=48,
                font_family="Malgun Gothic",
                anchor="start",
            ),
            TextSlot(
                id="slot.geom_angle_54",
                prompt="",
                text="54°",
                style_role="label",
                x=594.0,
                y=682.0,
                font_size=48,
                font_family="Malgun Gothic",
                anchor="start",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '2403',
 'problem_type': 'geometry_triangle',
 'metadata': {'title': 'x를 구하시오. 소수 첫째 자리까지 반올림하시오.',
              'tags': [],
              'instruction': '도형의 라벨과 표식을 바탕으로 x를 찾는 기하 문제',
              'question': 'x를 구하시오. 소수 첫째 자리까지 반올림하시오.',
              'required_layout_ids': ['slot.diagram_box',
                                      'slot.geom_ab',
                                      'slot.geom_ac',
                                      'slot.geom_bc',
                                      'slot.geom_ad',
                                      'slot.geom_perp_1',
                                      'slot.geom_perp_2',
                                      'slot.geom_tick_1',
                                      'slot.geom_tick_2'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.triangle', 'type': 'triangle'},
                        {'id': 'obj.side_label_32', 'type': 'length_label', 'value': 32},
                        {'id': 'obj.side_label_x', 'type': 'length_label', 'value': None},
                        {'id': 'obj.side_label_y', 'type': 'length_label', 'value': None},
                        {'id': 'obj.angle_54', 'type': 'angle_label', 'value': 54, 'unit': 'deg'}],
            'relations': [{'id': 'rel.tick_marks_equal',
                           'type': 'equal_side_mark',
                           'from_id': 'obj.triangle',
                           'to_id': 'obj.triangle'},
                          {'id': 'rel.perpendicular_altitude',
                           'type': 'perpendicular',
                           'from_id': 'obj.triangle',
                           'to_id': 'obj.triangle'}],
            'confidence': 1.0,
            'problem_solving': {'understand': {'given_refs': ['obj.side_label_32', 'obj.angle_54'],
                                               'target_ref': 'answer.target',
                                               'condition_refs': ['rel.tick_marks_equal',
                                                                  'rel.perpendicular_altitude']},
                                'plan': {'method': 'geometry_relation_reading',
                                         'description': '도형의 길이 표기와 각도 표기를 확인하고 x가 무엇을 뜻하는지 해석한다.'},
                                'execute': {'expected_operations': ['identify_labeled_parts',
                                                                    'match_labels_to_segments',
                                                                    'determine_target_quantity']},
                                'review': {'check_methods': ['label_position_check',
                                                             'diagram_relation_check']}}},
 'answer': {'blanks': [],
            'choices': [{'index': 1, 'text': '1. 18.8', 'value': '18.8'},
                        {'index': 2, 'text': '2. 23.2', 'value': '23.2'},
                        {'index': 3, 'text': '3. 2', 'value': '2'},
                        {'index': 4, 'text': '4. 44.0', 'value': '44.0'}],
            'answer_key': [1],
            'confidence': 1.0,
            'target': {'type': 'unknown_geometry_quantity', 'description': 'x'},
            'value': 18.8,
            'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '2403',
 'problem_type': 'geometry_triangle',
 'inputs': {'total_ticks': 2,
            'target_label': 'x',
            'target_ticks': 0,
            'target_count': 1,
            'unit': ''},
 'given': [{'ref': 'obj.side_label_32', 'value': 32}, {'ref': 'obj.angle_54', 'value': 54}],
 'target': {'ref': 'answer.target', 'type': 'unknown_geometry_quantity'},
 'method': 'geometry_relation_reading',
 'plan': ['도형에 표시된 라벨과 표식을 확인한다.', 'x가 가리키는 대상이 무엇인지 그림만으로 해석한다.'],
 'steps': [{'id': 'step.1', 'operation': 'identify_labels', 'expr': '32, x, y, 54°', 'value': 0}],
 'checks': [{'id': 'check.1',
             'type': 'label_presence_check',
             'expr': 'x is visibly printed in the diagram',
             'expected': 1,
             'actual': 1,
             'pass': True}],
 'answer': {'value': 18.8, 'unit': '', 'derived_from': 'choice.1'}}
