from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    RectSlot,
    TextSlot,
    LineSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2401",
        title="도형의 넓이를 구하시오.",
        canvas=Canvas(width=1400, height=980, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.problem",),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.diagram.panel",
                    "slot.edge.ab",
                    "slot.edge.bc",
                    "slot.edge.ac",
                    "slot.pt.a",
                    "slot.pt.b",
                    "slot.pt.c",
                    "slot.lb.a",
                    "slot.lb.b",
                    "slot.lb.c",
                    "slot.len.ab",
                    "slot.len.bc",
                    "slot.len.ac",
                    "slot.dim.cap.ab.a",
                    "slot.dim.cap.ab.b",
                    "slot.dim.arr.ab.1",
                    "slot.dim.arr.ab.2",
                    "slot.dim.arr.ab.3",
                    "slot.dim.arr.ab.4",
                    "slot.dim.cap.bc.a",
                    "slot.dim.cap.bc.b",
                    "slot.dim.arr.bc.1",
                    "slot.dim.arr.bc.2",
                    "slot.dim.arr.bc.3",
                    "slot.dim.arr.bc.4",
                    "slot.dim.cap.ac.a",
                    "slot.dim.cap.ac.b",
                    "slot.dim.arr.ac.1",
                    "slot.dim.arr.ac.2",
                    "slot.dim.arr.ac.3",
                    "slot.dim.arr.ac.4",
                ),
            ),
            Region(
                id="region.choices",
                role="choices",
                flow="absolute",
                slot_ids=(
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                ),
            ),
            Region(
                id="region.overlay",
                role="annotation",
                flow="absolute",
                slot_ids=("slot.answer.overlay",),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.problem",
                prompt="",
                text="도형의 넓이를 구하시오.",
                style_role="question",
                x=40.0,
                y=80.0,
                font_size=48,
                anchor="start",
            ),
            RectSlot(
                id="slot.diagram.panel",
                prompt="",
                x=40.0,
                y=200.0,
                width=752.0,
                height=740.0,
                stroke="#D1D5DB",
                stroke_width=1.0,
                fill="none",
                semantic_role="geometry_diagram_region",
            ),
            LineSlot(
                id="slot.edge.ab",
                prompt="",
                x1=73.7,
                y1=910.4,
                x2=417.9,
                y2=224.0,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.edge.bc",
                prompt="",
                x1=417.9,
                y1=224.0,
                x2=758.3,
                y2=910.4,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.edge.ac",
                prompt="",
                x1=73.7,
                y1=910.4,
                x2=758.3,
                y2=910.4,
                stroke="#374151",
                stroke_width=2.2,
                semantic_role="geometry_edge",
            ),
            CircleSlot(
                id="slot.pt.a",
                prompt="",
                cx=73.7,
                cy=910.4,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.b",
                prompt="",
                cx=417.9,
                cy=224.0,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.c",
                prompt="",
                cx=758.3,
                cy=910.4,
                r=3.8,
                stroke="#111111",
                stroke_width=1.0,
                fill="#111111",
                semantic_role="geometry_point",
            ),
            TextSlot(
                id="slot.lb.a",
                prompt="",
                text="A",
                style_role="label",
                x=79.7,
                y=904.4,
                font_size=36,
                anchor="start",
                semantic_role="geometry_point_label",
            ),
            TextSlot(
                id="slot.lb.b",
                prompt="",
                text="B",
                style_role="label",
                x=423.9,
                y=218.0,
                font_size=36,
                anchor="start",
                semantic_role="geometry_point_label",
            ),
            TextSlot(
                id="slot.lb.c",
                prompt="",
                text="C",
                style_role="label",
                x=764.3,
                y=904.4,
                font_size=36,
                anchor="start",
                semantic_role="geometry_point_label",
            ),
            TextSlot(
                id="slot.len.ab",
                prompt="",
                text="13",
                style_role="label",
                x=249.8,
                y=563.2,
                font_size=36,
                anchor="start",
                semantic_role="geometry_length_label",
            ),
            TextSlot(
                id="slot.len.bc",
                prompt="",
                text="13",
                style_role="label",
                x=592.1,
                y=563.2,
                font_size=36,
                anchor="start",
                semantic_role="geometry_length_label",
            ),
            TextSlot(
                id="slot.len.ac",
                prompt="",
                text="10",
                style_role="label",
                x=420.0,
                y=906.4,
                font_size=36,
                anchor="start",
                semantic_role="geometry_length_label",
            ),
            LineSlot(
                id="slot.dim.cap.ab.a",
                prompt="",
                x1=66.5,
                y1=906.9,
                x2=80.9,
                y2=914.0,
                stroke="#111111",
                stroke_width=1.5,
                semantic_role="geometry_dimension_cap",
            ),
            LineSlot(
                id="slot.dim.cap.ab.b",
                prompt="",
                x1=410.7,
                y1=220.4,
                x2=425.0,
                y2=227.6,
                stroke="#111111",
                stroke_width=1.5,
                semantic_role="geometry_dimension_cap",
            ),
            LineSlot(
                id="slot.dim.arr.ab.1",
                prompt="",
                x1=75.9,
                y1=906.0,
                x2=75.0,
                y2=914.5,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.ab.2",
                prompt="",
                x1=75.9,
                y1=906.0,
                x2=69.7,
                y2=911.8,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.ab.3",
                prompt="",
                x1=415.6,
                y1=228.5,
                x2=416.5,
                y2=220.0,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.ab.4",
                prompt="",
                x1=415.6,
                y1=228.5,
                x2=421.9,
                y2=222.7,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.cap.bc.a",
                prompt="",
                x1=425.0,
                y1=220.4,
                x2=410.7,
                y2=227.6,
                stroke="#111111",
                stroke_width=1.5,
                semantic_role="geometry_dimension_cap",
            ),
            LineSlot(
                id="slot.dim.cap.bc.b",
                prompt="",
                x1=765.5,
                y1=906.9,
                x2=751.1,
                y2=914.0,
                stroke="#111111",
                stroke_width=1.5,
                semantic_role="geometry_dimension_cap",
            ),
            LineSlot(
                id="slot.dim.arr.bc.1",
                prompt="",
                x1=420.1,
                y1=228.5,
                x2=413.8,
                y2=222.6,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.bc.2",
                prompt="",
                x1=420.1,
                y1=228.5,
                x2=419.2,
                y2=220.0,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.bc.3",
                prompt="",
                x1=756.1,
                y1=906.0,
                x2=762.3,
                y2=911.8,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.bc.4",
                prompt="",
                x1=756.1,
                y1=906.0,
                x2=756.9,
                y2=914.5,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.cap.ac.a",
                prompt="",
                x1=73.7,
                y1=902.4,
                x2=73.7,
                y2=918.4,
                stroke="#111111",
                stroke_width=1.5,
                semantic_role="geometry_dimension_cap",
            ),
            LineSlot(
                id="slot.dim.cap.ac.b",
                prompt="",
                x1=758.3,
                y1=902.4,
                x2=758.3,
                y2=918.4,
                stroke="#111111",
                stroke_width=1.5,
                semantic_role="geometry_dimension_cap",
            ),
            LineSlot(
                id="slot.dim.arr.ac.1",
                prompt="",
                x1=78.7,
                y1=910.4,
                x2=70.7,
                y2=913.4,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.ac.2",
                prompt="",
                x1=78.7,
                y1=910.4,
                x2=70.7,
                y2=907.4,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.ac.3",
                prompt="",
                x1=753.3,
                y1=910.4,
                x2=761.3,
                y2=907.4,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            LineSlot(
                id="slot.dim.arr.ac.4",
                prompt="",
                x1=753.3,
                y1=910.4,
                x2=761.3,
                y2=913.4,
                stroke="#111111",
                stroke_width=1.8,
                semantic_role="geometry_dimension_arrow",
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="1. 30",
                style_role="choice",
                x=860.0,
                y=320.0,
                font_size=48,
                anchor="start",
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="2. 60",
                style_role="choice",
                x=860.0,
                y=380.0,
                font_size=48,
                anchor="start",
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="3. 120",
                style_role="choice",
                x=860.0,
                y=460.0,
                font_size=48,
                anchor="start",
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="4. 240",
                style_role="choice",
                x=860.0,
                y=540.0,
                font_size=48,
                anchor="start",
            ),
            TextSlot(
                id="slot.answer.overlay",
                prompt="",
                text="정답: 2 (60)",
                style_role="annotation",
                x=1376.0,
                y=956.0,
                font_size=56,
                anchor="end",
                fill="#D32222",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '2401',
 'problem_type': 'geometry_area_multiple_choice',
 'metadata': {'title': '도형의 넓이를 구하시오.',
              'tags': [],
              'question': '도형의 넓이를 구하시오.',
              'required_layout_ids': ['slot.diagram.panel',
                                      'slot.edge.ab',
                                      'slot.edge.bc',
                                      'slot.edge.ac',
                                      'slot.pt.a',
                                      'slot.pt.b',
                                      'slot.pt.c',
                                      'slot.dim.cap.ab.a',
                                      'slot.dim.cap.ab.b',
                                      'slot.dim.arr.ab.1',
                                      'slot.dim.arr.ab.2',
                                      'slot.dim.arr.ab.3',
                                      'slot.dim.arr.ab.4',
                                      'slot.dim.cap.bc.a',
                                      'slot.dim.cap.bc.b',
                                      'slot.dim.arr.bc.1',
                                      'slot.dim.arr.bc.2',
                                      'slot.dim.arr.bc.3',
                                      'slot.dim.arr.bc.4',
                                      'slot.dim.cap.ac.a',
                                      'slot.dim.cap.ac.b',
                                      'slot.dim.arr.ac.1',
                                      'slot.dim.arr.ac.2',
                                      'slot.dim.arr.ac.3',
                                      'slot.dim.arr.ac.4'],
              'extraction_confidence': 1.0,
              'language': 'ko',
              'instruction': '도형의 넓이를 구하시오.'},
 'domain': {'objects': [{'id': 'obj.triangle_abc',
                         'type': 'triangle',
                         'vertices': ['obj.point_a', 'obj.point_b', 'obj.point_c']},
                        {'id': 'obj.point_a', 'type': 'point', 'label': 'A'},
                        {'id': 'obj.point_b', 'type': 'point', 'label': 'B'},
                        {'id': 'obj.point_c', 'type': 'point', 'label': 'C'},
                        {'id': 'obj.length_ab', 'type': 'length', 'value': 13},
                        {'id': 'obj.length_bc', 'type': 'length', 'value': 13},
                        {'id': 'obj.length_ac', 'type': 'length', 'value': 10},
                        {'id': 'obj.choice_1', 'type': 'choice', 'label': '1. 30'},
                        {'id': 'obj.choice_2', 'type': 'choice', 'label': '2. 60'},
                        {'id': 'obj.choice_3', 'type': 'choice', 'label': '3. 120'},
                        {'id': 'obj.choice_4', 'type': 'choice', 'label': '4. 240'}],
            'relations': [{'id': 'rel.length_on_triangle',
                           'type': 'labeled_length_on_edge',
                           'from_id': 'obj.triangle_abc',
                           'to_id': 'obj.length_ab'}],
            'confidence': 1.0,
            'problem_solving': {'understand': {'given_refs': ['obj.triangle_abc',
                                                              'obj.length_ab',
                                                              'obj.length_bc',
                                                              'obj.length_ac'],
                                               'target_ref': 'answer.target',
                                               'condition_refs': ['rel.length_on_triangle']},
                                'plan': {'method': 'area_from_triangle_lengths',
                                         'description': '보이는 변 길이 표기를 바탕으로 도형의 넓이를 묻는 문제로 해석하되, '
                                                        '계산은 확정하지 않는다.'},
                                'execute': {'expected_operations': ['identify_triangle',
                                                                    'read_length_labels']},
                                'review': {'check_methods': ['match_visible_labels',
                                                             'avoid_inferred_calculation']}}},
 'answer': {'blanks': [],
            'choices': [{'index': 1, 'text': '1. 30', 'value': '30'},
                        {'index': 2, 'text': '2. 60', 'value': '60'},
                        {'index': 3, 'text': '3. 120', 'value': '120'},
                        {'index': 4, 'text': '4. 240', 'value': '240'}],
            'answer_key': [2],
            'confidence': 1.0,
            'target': {'type': 'area', 'description': '도형의 넓이'},
            'value': 60,
            'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '2401',
 'problem_type': 'geometry_area_multiple_choice',
 'inputs': {'total_ticks': 0,
            'target_label': '도형의 넓이',
            'target_ticks': 0,
            'target_count': 1,
            'unit': ''},
 'given': [{'ref': 'obj.triangle_abc', 'value': {'vertices': ['A', 'B', 'C']}},
           {'ref': 'obj.length_ab', 'value': 13},
           {'ref': 'obj.length_bc', 'value': 13},
           {'ref': 'obj.length_ac', 'value': 10}],
 'target': {'ref': 'answer.target', 'type': 'area'},
 'method': 'read_visible_information_only',
 'plan': ['보이는 도형과 길이 표기를 확인한다.', '추론 계산은 하지 않고, 정답 오버레이도 의미 계약에 사용하지 않는다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_shape',
            'expr': 'triangle ABC',
            'value': 'triangle'},
           {'id': 'step.2',
            'operation': 'read_labels',
            'expr': 'AB=13, BC=13, AC=10',
            'value': {'ab': 13, 'bc': 13, 'ac': 10}}],
 'checks': [{'id': 'check.1',
             'type': 'visible_label_match',
             'expr': 'labels match source image',
             'expected': True,
             'actual': True,
             'pass': True}],
 'answer': {'value': 60, 'unit': '', 'derived_from': 'choice.2'}}
