from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    LineSlot,
    CircleSlot,
    PathSlot,
)

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_pLAtjeyTaF",
        title="ㄱ과 ㄴ의 길이",
        canvas=Canvas(width=560, height=320, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.line_main",
                    "slot.tick1",
                    "slot.tick2",
                    "slot.tick3",
                    "slot.tick4",
                    "slot.arc_top_821",
                    "slot.text_821",
                    "slot.arc_top_448",
                    "slot.text_448",
                    "slot.arc_bot_g",
                    "slot.circle_g",
                    "slot.text_g",
                    "slot.arc_bot_n",
                    "slot.circle_n",
                    "slot.text_n",
                    "slot.arc_bot_236",
                    "slot.text_236",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="㉠과 ㉡의 길이는 각각 몇 cm입니까?",
                style_role="question",
                x=18.0,
                y=34.0,
                font_size=28,
            ),
            LineSlot(
                id="slot.line_main",
                prompt="",
                x1=30.0,
                y1=125.0,
                x2=530.0,
                y2=125.0,
                stroke="#222222",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.tick1",
                prompt="",
                x1=30.0,
                y1=116.0,
                x2=30.0,
                y2=135.0,
                stroke="#222222",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.tick2",
                prompt="",
                x1=320.0,
                y1=116.0,
                x2=320.0,
                y2=135.0,
                stroke="#222222",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.tick3",
                prompt="",
                x1=420.0,
                y1=116.0,
                x2=420.0,
                y2=135.0,
                stroke="#222222",
                stroke_width=1.4,
            ),
            LineSlot(
                id="slot.tick4",
                prompt="",
                x1=530.0,
                y1=116.0,
                x2=530.0,
                y2=135.0,
                stroke="#222222",
                stroke_width=1.4,
            ),
            PathSlot(
                id="slot.arc_top_821",
                prompt="",
                d="M 30 125 Q 225 30 420 125",
                stroke="#666666",
                stroke_width=1.2,
                stroke_dasharray="5 3",
                fill="none",
            ),
            TextSlot(
                id="slot.text_821",
                prompt="",
                text="821 cm",
                style_role="label",
                x=190.0,
                y=70.0,
                font_size=26,
            ),
            PathSlot(
                id="slot.arc_top_448",
                prompt="",
                d="M 320 125 Q 425 30 530 125",
                stroke="#666666",
                stroke_width=1.2,
                stroke_dasharray="5 3",
                fill="none",
            ),
            TextSlot(
                id="slot.text_448",
                prompt="",
                text="448 cm",
                style_role="label",
                x=390.0,
                y=70.0,
                font_size=26,
            ),
            PathSlot(
                id="slot.arc_bot_g",
                prompt="",
                d="M 30 125 Q 175 250 320 125",
                stroke="#666666",
                stroke_width=1.2,
                stroke_dasharray="5 3",
                fill="none",
            ),
            CircleSlot(
                id="slot.circle_g",
                prompt="",
                cx=175.0,
                cy=187.5,
                r=16.0,
                stroke="#666666",
                stroke_width=1.1,
                fill="#ffffff",
            ),
            TextSlot(
                id="slot.text_g",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=168.0,
                y=196.0,
                font_size=24,
            ),
            PathSlot(
                id="slot.arc_bot_n",
                prompt="",
                d="M 320 125 Q 370 200 420 125",
                stroke="#666666",
                stroke_width=1.2,
                stroke_dasharray="5 3",
                fill="none",
            ),
            CircleSlot(
                id="slot.circle_n",
                prompt="",
                cx=370.0,
                cy=162.5,
                r=16.0,
                stroke="#666666",
                stroke_width=1.1,
                fill="#ffffff",
            ),
            TextSlot(
                id="slot.text_n",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=363.0,
                y=171.0,
                font_size=24,
            ),
            PathSlot(
                id="slot.arc_bot_236",
                prompt="",
                d="M 420 125 Q 475 200 530 125",
                stroke="#666666",
                stroke_width=1.2,
                stroke_dasharray="5 3",
                fill="none",
            ),
            TextSlot(
                id="slot.text_236",
                prompt="",
                text="236 cm",
                style_role="label",
                x=440.0,
                y=180.0,
                font_size=26,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_pLAtjeyTaF",
    "problem_type": "length_relation",
    "metadata": {
        "language": "ko",
        "question": "㉠과 ㉡의 길이는 각각 몇 cm입니까?",
        "instruction": "그림의 길이 관계를 보고 ㉠과 ㉡의 길이를 구하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.segment_total", "type": "length", "value": 821, "unit": "cm"},
            {"id": "obj.segment_part_right", "type": "length", "value": 448, "unit": "cm"},
            {"id": "obj.segment_part_small", "type": "length", "value": 236, "unit": "cm"},
            {"id": "obj.answer_giyeok", "type": "unknown_length", "label": "ㄱ", "unit": "cm"},
            {"id": "obj.answer_nieun", "type": "unknown_length", "label": "ㄴ", "unit": "cm"},
        ],
        "relations": [
            {
                "id": "rel.total_is_sum",
                "type": "sum_relation",
                "from_id": "obj.answer_giyeok",
                "to_id": "obj.segment_total",
                "via": ["obj.answer_nieun"],
            },
            {
                "id": "rel.right_is_sum",
                "type": "sum_relation",
                "from_id": "obj.answer_nieun",
                "to_id": "obj.segment_part_right",
                "via": ["obj.segment_part_small"],
            },
        ],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.segment_total", "obj.segment_part_right", "obj.segment_part_small"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.total_is_sum", "rel.right_is_sum"],
            },
            "plan": {
                "method": "subtraction",
                "description": "전체 길이에서 알려진 부분 길이를 빼서 ㄱ을 구하고, 또 다른 부분 길이의 차로 ㄴ을 구한다.",
            },
            "execute": {
                "expected_operations": ["subtract_known_part", "subtract_nested_part"]
            },
            "review": {
                "check_methods": ["inverse_operation_check", "unit_consistency_check"]
            },
        },
    },
    "answer": {
        "target": {"type": "two_lengths", "description": "㉠과 ㉡의 길이"},
        "value": 609,
        "unit": "cm",
    },
}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'Hpdf_pLAtjeyTaF',
    'problem_type': 'length_relation',
    'inputs': {   'total_ticks': 609,
                  'target_label': '길이',
                  'target_ticks': 609,
                  'target_count': 609,
                  'unit': 'cm'},
    'plan': [   '전체 구조를 보면, 821cm는 ㉠과 ㉡의 합이고, 448cm는 ㉡과 236cm의 합이다.',
                '먼저 ㉡을 구하기 위해 448cm에서 236cm를 뺀다.',
                '㉡ = 448 - 236 = 212 (cm)',
                '이제 ㉠을 구하기 위해 821cm에서 구한 ㉡을 뺀다.',
                '㉠ = 821 - 212 = 609 (cm)'],
    'steps': [   {'id': 'step.1', 'expr': '㉡ = 448 - 236', 'value': 212},
                 {'id': 'step.2', 'expr': '㉠ = 821 - 212', 'value': 609}],
    'checks': [   {   'id': 'check.1',
                      'expr': '609 + 212',
                      'expected': 821,
                      'actual': 821,
                      'pass': True},
                  {   'id': 'check.2',
                      'expr': '212 + 236',
                      'expected': 448,
                      'actual': 448,
                      'pass': True}],
    'answer': {'value': 609, 'unit': 'cm'}}
