from __future__ import annotations

from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot


SEMANTIC_OVERRIDE = {
    "problem_type": "word_problem",
    "metadata": {
        "instruction": "가격표의 6개 물건 중 서로 다른 3개를 각각 1개씩 산다.",
        "question": "소민이가 산 물건 중 가장 비싼 것은 무엇입니까?",
        "tags": ["price_table", "change", "selection", "combinatorics"],
    },
    "domain": {
        "objects": [
            {
                "id": "person.somin",
                "type": "person",
                "properties": {"name": "소민"},
                "confidence": 1.0,
            },
            {
                "id": "coin.500",
                "type": "coin",
                "properties": {"denomination": 500, "currency": "KRW"},
                "confidence": 1.0,
            },
            {
                "id": "coin.10",
                "type": "coin",
                "properties": {"denomination": 10, "currency": "KRW"},
                "confidence": 1.0,
            },
            {
                "id": "item.eraser",
                "type": "item",
                "properties": {"name": "지우개", "price": 340, "unit": "원"},
                "confidence": 1.0,
            },
            {
                "id": "item.glue",
                "type": "item",
                "properties": {"name": "얌체공", "price": 250, "unit": "원"},
                "confidence": 1.0,
            },
            {
                "id": "item.protractor",
                "type": "item",
                "properties": {"name": "각도기", "price": 430, "unit": "원"},
                "confidence": 1.0,
            },
            {
                "id": "item.ruler",
                "type": "item",
                "properties": {"name": "자", "price": 290, "unit": "원"},
                "confidence": 1.0,
            },
            {
                "id": "item.paste",
                "type": "item",
                "properties": {"name": "풀", "price": 470, "unit": "원"},
                "confidence": 1.0,
            },
            {
                "id": "item.knife",
                "type": "item",
                "properties": {"name": "칼", "price": 520, "unit": "원"},
                "confidence": 1.0,
            },
        ],
        "relations": [
            {
                "id": "rel.purchase.count",
                "type": "purchase_count",
                "from_id": "person.somin",
                "to_id": "item.eraser",
                "properties": {"distinct_items": 3, "quantity_each": 1},
                "confidence": 1.0,
            },
            {
                "id": "rel.change.10won",
                "type": "change",
                "from_id": "person.somin",
                "to_id": "coin.10",
                "properties": {"count": 3, "total": 30, "unit": "원"},
                "confidence": 1.0,
            },
            {
                "id": "rel.payment.500only",
                "type": "payment_constraint",
                "from_id": "person.somin",
                "to_id": "coin.500",
                "properties": {"rule": "paid_amount_is_multiple_of_500"},
                "confidence": 1.0,
            },
        ],
        "confidence": 1.0,
    },
    "answer": {
        "value": "각도기",
        "unit": "",
        "source": "price_table_and_change_constraints",
        "confidence": 1.0,
    },
}


SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "Hpdf_6h0oMCBwYY",
    "problem_type": "word_problem",
    "inputs": {
        "total_ticks": 970,
        "target_label": "가장 비싼 물건의 가격",
        "target_ticks": 430,
        "target_count": 1,
        "unit": "원",
    },
    "plan": [
        "거스름돈 10원짜리 3개이므로 거스름돈은 30원이다.",
        "500원짜리 동전만 사용했으므로 지불 금액은 500의 배수이다.",
        "따라서 산 3개 물건의 가격 합은 (500의 배수 - 30)이다.",
        "가격표의 6개 물건 중 3개를 고르는 조합 중 합이 470, 970, 1470, ... 인 경우를 찾는다.",
        "조건을 만족하는 조합의 물건 중 가장 비싼 물건을 고른다.",
    ],
    "steps": [
        {"id": "s1", "expr": "change_total = 10 * 3", "value": 30},
        {"id": "s2", "expr": "sum(items) = 500*k - 30", "value": 970},
        {"id": "s3", "expr": "250 + 290 + 430", "value": 970},
        {"id": "s4", "expr": "max(250, 290, 430)", "value": 430},
    ],
    "checks": [
        {
            "id": "c1",
            "expr": "970 + 30",
            "expected": 1000,
            "actual": 1000,
            "pass": True,
        },
        {
            "id": "c2",
            "expr": "max_price == 430",
            "expected": 430,
            "actual": 430,
            "pass": True,
        },
    ],
    "answer": {"value": 430, "unit": "원"},
}


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_6h0oMCBwYY",
        title="가장 비싼 물건 찾기",
        canvas=Canvas(width=800, height=660, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.stem.l1",
                    "slot.stem.l2",
                    "slot.stem.l3",
                    "slot.stem.l4",
                    "slot.stem.l5",
                    "slot.price.box",
                    "slot.price.left.1",
                    "slot.price.left.2",
                    "slot.price.left.3",
                    "slot.price.right.1",
                    "slot.price.right.2",
                    "slot.price.right.3",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.stem.l1",
                prompt="",
                text="소민이는 500원짜리 동전만 몇 개를 가지고",
                style_role="body",
                x=16.0,
                y=52.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.stem.l2",
                prompt="",
                text="문구점에 갔습니다. 다음 가격이 제시된 물건",
                style_role="body",
                x=16.0,
                y=102.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.stem.l3",
                prompt="",
                text="중 3가지를 각각 1개씩 사고 받은 거스름돈은",
                style_role="body",
                x=16.0,
                y=152.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.stem.l4",
                prompt="",
                text="10원짜리 동전 3개였습니다. 소민이가 산 물",
                style_role="body",
                x=16.0,
                y=202.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.stem.l5",
                prompt="",
                text="건 중 가장 비싼 것은 무엇입니까?",
                style_role="question",
                x=16.0,
                y=252.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.price.box",
                prompt="",
                x=16.0,
                y=300.0,
                width=768.0,
                height=340.0,
                rx=10.0,
                ry=10.0,
                stroke="#9A9A9A",
                stroke_width=2.0,
                fill="none",
            ),
            TextSlot(
                id="slot.price.left.1",
                prompt="",
                text="지우개 1개: 340원",
                style_role="body",
                x=56.0,
                y=368.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.price.left.2",
                prompt="",
                text="얌체공 1개: 250원",
                style_role="body",
                x=56.0,
                y=436.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.price.left.3",
                prompt="",
                text="각도기 1개: 430원",
                style_role="body",
                x=56.0,
                y=504.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.price.right.1",
                prompt="",
                text="자 1개: 290원",
                style_role="body",
                x=480.0,
                y=368.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.price.right.2",
                prompt="",
                text="풀 1개: 470원",
                style_role="body",
                x=480.0,
                y=436.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.price.right.3",
                prompt="",
                text="칼 1개: 520원",
                style_role="body",
                x=480.0,
                y=504.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("price_table", "change", "selection"),
    )
