from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    LineSlot,
    PolygonSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=557,
        height=520,
        coordinate_mode="logical",
    )

    regions = (
        Region(
            id="region.stem",
            role="stem",
            flow="absolute",
            slot_ids=(
                "slot.title.l1",
                "slot.title.l2",
                "slot.left.panel",
                "slot.badge.bg",
                "slot.badge.text",
                "slot.left.top",
                "slot.left.top.left",
                "slot.left.top.star",
                "slot.left.top.right",
                "slot.left.arrow1",
                "slot.left.rule1",
                "slot.left.diamond",
                "slot.left.diamond.text",
                "slot.left.arrow2",
                "slot.left.rule2",
                "slot.left.bottom",
                "slot.left.bottom.text",
                "slot.right.top",
                "slot.right.top.left",
                "slot.right.top.star",
                "slot.right.top.right",
                "slot.right.arrow1",
                "slot.right.diamond",
                "slot.right.diamond.text",
                "slot.right.arrow2",
                "slot.right.bottom",
                "slot.right.bottom.text",
            ),
        ),
    )

    slots = (
        TextSlot(
            id="slot.title.l1",
            prompt="",
            text="732★567을 보기와 같은 방법으로 계산하려",
            style_role="body",
            x=10.0,
            y=50.0,
            font_size=28,
            fill="#222222",
        ),
        TextSlot(
            id="slot.title.l2",
            prompt="",
            text="고 합니다. ㉠에 알맞은 수를 구하시오.",
            style_role="body",
            x=10.0,
            y=100.0,
            font_size=28,
            fill="#222222",
        ),
        RectSlot(
            id="slot.badge.bg",
            prompt="",
            x=80.0,
            y=128.0,
            width=52.0,
            height=30.0,
            rx=10.0,
            ry=10.0,
            stroke="#8a8d93",
            stroke_width=1.0,
            fill="#8a8d93",
        ),
        TextSlot(
            id="slot.badge.text",
            prompt="",
            text="보기",
            style_role="body",
            x=85.4,
            y=150.6,
            font_size=22,
            fill="#1f2328",
        ),
        RectSlot(
            id="slot.left.panel",
            prompt="",
            x=63.0,
            y=145.0,
            width=227.0,
            height=358.0,
            rx=8.0,
            ry=8.0,
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="none",
        ),
        RectSlot(
            id="slot.left.top",
            prompt="",
            x=82.0,
            y=171.0,
            width=160.0,
            height=64.0,
            rx=32.0,
            ry=32.0,
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="#d1d3d8",
        ),
        TextSlot(
            id="slot.left.top.left",
            prompt="",
            text="가",
            style_role="body",
            x=112.0,
            y=214.0,
            font_size=28,
            fill="#1f2328",
        ),
        PolygonSlot(
            id="slot.left.top.star",
            prompt="",
            x=163.0,
            y=188.0,
            points=(
                (0.0, 0.0),
                (4.0, 10.0),
                (15.0, 10.0),
                (6.0, 17.0),
                (10.0, 28.0),
                (0.0, 21.0),
                (-10.0, 28.0),
                (-6.0, 17.0),
                (-15.0, 10.0),
                (-4.0, 10.0),
            ),
            stroke="#7d8087",
            stroke_width=1.0,
            fill="#7d8087",
        ),
        TextSlot(
            id="slot.left.top.right",
            prompt="",
            text="나",
            style_role="body",
            x=186.0,
            y=214.0,
            font_size=28,
            fill="#1f2328",
        ),
        LineSlot(
            id="slot.left.arrow1",
            prompt="",
            x1=163.0,
            y1=236.0,
            x2=163.0,
            y2=292.0,
            stroke="#55585f",
            stroke_width=2.0,
        ),
        TextSlot(
            id="slot.left.rule1",
            prompt="",
            text="가-나",
            style_role="body",
            x=188.0,
            y=272.0,
            font_size=28,
            fill="#1f2328",
        ),
        PolygonSlot(
            id="slot.left.diamond",
            prompt="",
            points=((163.0, 296.0), (242.0, 331.0), (163.0, 366.0), (84.0, 331.0)),
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="#d8dae0",
        ),
        TextSlot(
            id="slot.left.diamond.text",
            prompt="",
            text="다",
            style_role="body",
            x=149.0,
            y=340.0,
            font_size=28,
            fill="#1f2328",
        ),
        LineSlot(
            id="slot.left.arrow2",
            prompt="",
            x1=163.0,
            y1=366.0,
            x2=163.0,
            y2=419.0,
            stroke="#55585f",
            stroke_width=2.0,
        ),
        TextSlot(
            id="slot.left.rule2",
            prompt="",
            text="다+348",
            style_role="body",
            x=181.0,
            y=395.0,
            font_size=28,
            fill="#1f2328",
        ),
        RectSlot(
            id="slot.left.bottom",
            prompt="",
            x=82.0,
            y=423.0,
            width=160.0,
            height=64.0,
            rx=32.0,
            ry=32.0,
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="#d1d3d8",
        ),
        TextSlot(
            id="slot.left.bottom.text",
            prompt="",
            text="라",
            style_role="body",
            x=150.0,
            y=466.0,
            font_size=28,
            fill="#1f2328",
        ),
        RectSlot(
            id="slot.right.top",
            prompt="",
            x=326.0,
            y=171.0,
            width=158.0,
            height=64.0,
            rx=32.0,
            ry=32.0,
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="#d1d3d8",
        ),
        TextSlot(
            id="slot.right.top.left",
            prompt="",
            text="732",
            style_role="body",
            x=344.0,
            y=214.0,
            font_size=28,
            fill="#1f2328",
        ),
        PolygonSlot(
            id="slot.right.top.star",
            prompt="",
            x=405.0,
            y=188.0,
            points=(
                (0.0, 0.0),
                (4.0, 10.0),
                (15.0, 10.0),
                (6.0, 17.0),
                (10.0, 28.0),
                (0.0, 21.0),
                (-10.0, 28.0),
                (-6.0, 17.0),
                (-15.0, 10.0),
                (-4.0, 10.0),
            ),
            stroke="#7d8087",
            stroke_width=1.0,
            fill="#7d8087",
        ),
        TextSlot(
            id="slot.right.top.right",
            prompt="",
            text="567",
            style_role="body",
            x=425.0,
            y=214.0,
            font_size=28,
            fill="#1f2328",
        ),
        LineSlot(
            id="slot.right.arrow1",
            prompt="",
            x1=405.0,
            y1=236.0,
            x2=405.0,
            y2=292.0,
            stroke="#55585f",
            stroke_width=2.0,
        ),
        PolygonSlot(
            id="slot.right.diamond",
            prompt="",
            points=((405.0, 296.0), (484.0, 331.0), (405.0, 366.0), (326.0, 331.0)),
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="#d8dae0",
        ),
        TextSlot(
            id="slot.right.diamond.text",
            prompt="",
            text="다",
            style_role="body",
            x=391.0,
            y=340.0,
            font_size=28,
            fill="#1f2328",
        ),
        LineSlot(
            id="slot.right.arrow2",
            prompt="",
            x1=405.0,
            y1=366.0,
            x2=405.0,
            y2=419.0,
            stroke="#55585f",
            stroke_width=2.0,
        ),
        RectSlot(
            id="slot.right.bottom",
            prompt="",
            x=326.0,
            y=423.0,
            width=158.0,
            height=64.0,
            rx=32.0,
            ry=32.0,
            stroke="#8a8d93",
            stroke_width=2.0,
            fill="#d1d3d8",
        ),
        TextSlot(
            id="slot.right.bottom.text",
            prompt="",
            text="㉠",
            style_role="body",
            x=392.0,
            y=466.0,
            font_size=28,
            fill="#1f2328",
        ),
    )

    diagrams = ()
    groups = ()
    constraints = ()

    return ProblemTemplate(
        id="Hpdf_3Qm6WHKnJ8",
        title="",
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_3Qm6WHKnJ8",
    "problem_type": "custom_operation",
    "metadata": {
        "language": "ko",
        "question": "732★567을 보기와 같은 방법으로 계산하려고 합니다. ㉠에 알맞은 수를 구하시오.",
        "instruction": "보기의 규칙을 파악하여 주어진 식을 계산한다.",
    },
    "domain": {
        "objects": [
            {"id": "var.가", "type": "variable", "label": "가"},
            {"id": "var.나", "type": "variable", "label": "나"},
            {"id": "expr.다", "type": "subtraction_expression", "left": "var.가", "right": "var.나"},
            {"id": "expr.라", "type": "addition_expression", "left": "expr.다", "right": 348},
            {"id": "op.star", "type": "custom_operator", "symbol": "★", "definition": "expr.라"},
            {"id": "expr.target", "type": "application", "operator": "op.star", "args": [732, 567]},
        ],
        "relations": [
            {"id": "rel.target", "type": "equality", "left": "var.㉠", "right": "expr.target"}
        ],
        "problem_solving": {
            "understand": {
                "given_refs": ["op.star"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.target"],
            },
            "plan": {
                "method": "apply_custom_operation",
                "description": "보기에서 가 ★ 나 = (가 - 나) + 348 이라는 규칙을 찾고, 732 ★ 567에 대입한다.",
            },
            "execute": {
                "expected_operations": ["compute_subtraction", "compute_addition"]
            },
            "review": {"check_methods": ["recalculate"]},
        },
    },
    "answer": {
        "target": {
            "type": "number",
            "ref": "var.㉠",
            "description": "㉠에 알맞은 수",
        },
        "value": 513,
        "unit": "",
    },
}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'Hpdf_3Qm6WHKnJ8',
    'problem_type': 'custom_operation',
    'inputs': {   'total_ticks': 513,
                  'target_label': '㉠에 알맞은 수',
                  'target_ticks': 513,
                  'target_count': 513,
                  'unit': ''},
    'plan': [   '보기의 흐름도를 통해 가 ★ 나 = (가 - 나) + 348 이라는 규칙을 파악한다.',
                '다 = 가 - 나 이므로, 732 - 567을 계산하여 다를 구한다.',
                '㉠(라) = 다 + 348 이므로, 구한 다에 348을 더해 ㉠을 구한다.'],
    'steps': [   {'id': 'step.s1', 'expr': '다 = 732 - 567', 'value': 165},
                 {'id': 'step.s2', 'expr': '㉠ = 165 + 348', 'value': 513}],
    'checks': [   {   'id': 'check.c1',
                      'expr': '513 - 348',
                      'expected': 165,
                      'actual': 165,
                      'pass': True},
                  {   'id': 'check.c2',
                      'expr': '165 + 567',
                      'expected': 732,
                      'actual': 732,
                      'pass': True}],
    'answer': {'value': 513, 'unit': ''}}
