from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_lah0OIGiEi",
        title="도형에서 직각삼각형 개수",
        canvas=Canvas(width=560, height=360, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.shape.outer_left",
                    "slot.shape.outer_top",
                    "slot.shape.outer_mid",
                    "slot.shape.outer_bottom",
                    "slot.shape.left_diag1",
                    "slot.shape.left_diag2",
                    "slot.shape.top_diag1",
                    "slot.shape.top_diag2",
                    "slot.shape.mid_diag1",
                    "slot.shape.mid_diag2",
                    "slot.shape.bottom_diag1",
                    "slot.shape.bottom_diag2",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="도형에서 찾을 수 있는 크고 작은 직각삼각형",
                style_role="question",
                x=8.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="은 모두 몇 개입니까?",
                style_role="question",
                x=8.0,
                y=68.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.shape.outer_left",
                prompt="",
                x=165.0,
                y=198.0,
                width=110.0,
                height=72.0,
                stroke="#333333",
                stroke_width=1.6,
                fill="none",
            ),
            RectSlot(
                id="slot.shape.outer_top",
                prompt="",
                x=275.0,
                y=126.0,
                width=110.0,
                height=72.0,
                stroke="#333333",
                stroke_width=1.6,
                fill="none",
            ),
            RectSlot(
                id="slot.shape.outer_mid",
                prompt="",
                x=275.0,
                y=198.0,
                width=110.0,
                height=72.0,
                stroke="#333333",
                stroke_width=1.6,
                fill="none",
            ),
            RectSlot(
                id="slot.shape.outer_bottom",
                prompt="",
                x=275.0,
                y=270.0,
                width=110.0,
                height=72.0,
                stroke="#333333",
                stroke_width=1.6,
                fill="none",
            ),
            LineSlot(
                id="slot.shape.left_diag1",
                prompt="",
                x1=165.0,
                y1=198.0,
                x2=275.0,
                y2=270.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.left_diag2",
                prompt="",
                x1=165.0,
                y1=270.0,
                x2=275.0,
                y2=198.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.top_diag1",
                prompt="",
                x1=275.0,
                y1=126.0,
                x2=385.0,
                y2=198.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.top_diag2",
                prompt="",
                x1=275.0,
                y1=198.0,
                x2=385.0,
                y2=126.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.mid_diag1",
                prompt="",
                x1=275.0,
                y1=198.0,
                x2=385.0,
                y2=270.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.mid_diag2",
                prompt="",
                x1=275.0,
                y1=270.0,
                x2=385.0,
                y2=198.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.bottom_diag1",
                prompt="",
                x1=275.0,
                y1=270.0,
                x2=385.0,
                y2=342.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.shape.bottom_diag2",
                prompt="",
                x1=275.0,
                y1=342.0,
                x2=385.0,
                y2=270.0,
                stroke="#333333",
                stroke_width=1.6,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_lah0OIGiEi",
    "problem_type": "count_right_triangles",
    "metadata": {
        "language": "ko",
        "question": "도형에서 찾을 수 있는 크고 작은 직각삼각형은 모두 몇 개입니까?",
        "instruction": "직각삼각형의 개수를 구하시오.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.figure",
                "type": "composite_shape",
                "description": "정사각형 4개가 십자가 형태(일부 누락)로 결합되고 대각선이 그려진 도형",
            },
        ],
        "relations": [
            {
                "id": "rel.count",
                "type": "count_shape",
                "shape_type": "right_triangle",
                "target": "answer.target"
            }
        ],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.figure"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.count"],
            },
            "plan": {
                "method": "systematic_counting_by_size",
                "description": "가장 작은 직각삼각형부터 크기별로 분류하여 개수를 센다.",
            },
            "execute": {
                "expected_operations": [
                    "count_small_triangles",
                    "count_medium_triangles",
                    "count_large_triangles",
                    "count_extra_large_triangles",
                    "sum_all"
                ]
            },
            "review": {"check_methods": []},
        },
    },
    "answer": {
        "target": {
            "type": "number",
            "description": "크고 작은 직각삼각형의 총 개수",
        },
        "value": 40,
        "unit": "개",
    },
}

SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'Hpdf_lah0OIGiEi',
    'problem_type': 'count_right_triangles',
    'inputs': {   'total_ticks': 40,
                  'target_label': '직각삼각형 개수',
                  'target_ticks': 40,
                  'target_count': 40,
                  'unit': '개'},
    'plan': [   '크기가 가장 작은 직각삼각형 (정사각형의 1/4 크기) 개수를 구한다: 4개의 정사각형에 각각 4개씩 있으므로 16개.',
                '중간 크기의 직각삼각형 (정사각형의 1/2 크기) 개수를 구한다: 4개의 정사각형에 각각 4개씩 있으므로 16개.',
                '큰 직각삼각형 (정사각형 1개 크기, 인접한 두 정사각형으로 만들어짐) 개수를 구한다: 맞닿은 부분마다 2개씩 생기며, 맞닿은 변이 3곳이므로 3 '
                'x 2 = 6개.',
                '가장 큰 직각삼각형 (정사각형 2개 크기) 개수를 구한다: 2개.',
                '모두 합하면 16 + 16 + 6 + 2 = 40개이다.'],
    'steps': [   {'id': 'step.1', 'expr': '가장 작은 직각삼각형', 'value': 16},
                 {'id': 'step.2', 'expr': '중간 크기 직각삼각형', 'value': 16},
                 {'id': 'step.3', 'expr': '큰 직각삼각형', 'value': 6},
                 {'id': 'step.4', 'expr': '가장 큰 직각삼각형', 'value': 2},
                 {'id': 'step.5', 'expr': '16 + 16 + 6 + 2', 'value': 40}],
    'checks': [   {   'id': 'check.1',
                      'expr': '16 + 16 + 6 + 2',
                      'expected': 40,
                      'actual': 40,
                      'pass': True}],
    'answer': {'value': 40, 'unit': '개'}}
