from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    CircleSlot,
    RectSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_cAV8nIGcoF",
        title="오각형의 각 변",
        canvas=Canvas(width=560, height=520, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                    "slot.q5",
                    "slot.q6",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.edge.ㄱ",
                    "slot.edge.ㄴ",
                    "slot.edge.ㄷ",
                    "slot.edge.ㄹ",
                    "slot.edge.ㅁ",
                    "slot.node.387",
                    "slot.node.372",
                    "slot.node.339",
                    "slot.node.323",
                    "slot.node.346",
                    "slot.label.ㄱ",
                    "slot.label.ㄴ",
                    "slot.label.ㄷ",
                    "slot.label.ㄹ",
                    "slot.label.ㅁ",
                    "slot.t.node.387",
                    "slot.t.node.372",
                    "slot.t.node.339",
                    "slot.t.node.323",
                    "slot.t.node.346",
                    "slot.t.label.ㄱ",
                    "slot.t.label.ㄴ",
                    "slot.t.label.ㄷ",
                    "slot.t.label.ㄹ",
                    "slot.t.label.ㅁ",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="오각형의 각 변에 있는 세 수의 합이 모두 같도",
                style_role="question",
                x=10.0,
                y=36.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="록 ㉠~㉤에 210, 188, 259, 162, 252를 알",
                style_role="question",
                x=10.0,
                y=70.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="맞게 써넣으려고 합니다. ㉠에 들어갈 수를 구",
                style_role="question",
                x=10.0,
                y=104.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="하시오.",
                style_role="question",
                x=10.0,
                y=138.0,
                font_size=28,
            ),
            # Edges
            LineSlot(
                id="slot.edge.ㄱ",
                prompt="",
                x1=280.0,
                y1=190.0,
                x2=423.0,
                y2=294.0,
                stroke="#BDBDBD",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.edge.ㄴ",
                prompt="",
                x1=423.0,
                y1=294.0,
                x2=368.0,
                y2=461.0,
                stroke="#BDBDBD",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.edge.ㄷ",
                prompt="",
                x1=368.0,
                y1=461.0,
                x2=192.0,
                y2=461.0,
                stroke="#BDBDBD",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.edge.ㄹ",
                prompt="",
                x1=192.0,
                y1=461.0,
                x2=137.0,
                y2=294.0,
                stroke="#BDBDBD",
                stroke_width=4.0,
            ),
            LineSlot(
                id="slot.edge.ㅁ",
                prompt="",
                x1=137.0,
                y1=294.0,
                x2=280.0,
                y2=190.0,
                stroke="#BDBDBD",
                stroke_width=4.0,
            ),
            # Nodes
            CircleSlot(
                id="slot.node.387",
                prompt="",
                cx=280.0,
                cy=190.0,
                r=34.0,
                stroke="#C8C8C8",
                stroke_width=4.0,
                fill="#F3F3F3",
            ),
            CircleSlot(
                id="slot.node.372",
                prompt="",
                cx=423.0,
                cy=294.0,
                r=34.0,
                stroke="#C8C8C8",
                stroke_width=4.0,
                fill="#F3F3F3",
            ),
            CircleSlot(
                id="slot.node.339",
                prompt="",
                cx=368.0,
                cy=461.0,
                r=34.0,
                stroke="#C8C8C8",
                stroke_width=4.0,
                fill="#F3F3F3",
            ),
            CircleSlot(
                id="slot.node.323",
                prompt="",
                cx=192.0,
                cy=461.0,
                r=34.0,
                stroke="#C8C8C8",
                stroke_width=4.0,
                fill="#F3F3F3",
            ),
            CircleSlot(
                id="slot.node.346",
                prompt="",
                cx=137.0,
                cy=294.0,
                r=34.0,
                stroke="#C8C8C8",
                stroke_width=4.0,
                fill="#F3F3F3",
            ),
            # Labels (Rects)
            RectSlot(
                id="slot.label.ㄱ",
                prompt="",
                x=317.5,
                y=220.0,
                width=68.0,
                height=44.0,
                stroke="#CFCFCF",
                stroke_width=4.0,
                fill="#FFFFFF",
            ),
            RectSlot(
                id="slot.label.ㄴ",
                prompt="",
                x=361.5,
                y=355.5,
                width=68.0,
                height=44.0,
                stroke="#CFCFCF",
                stroke_width=4.0,
                fill="#FFFFFF",
            ),
            RectSlot(
                id="slot.label.ㄷ",
                prompt="",
                x=246.0,
                y=439.0,
                width=68.0,
                height=44.0,
                stroke="#CFCFCF",
                stroke_width=4.0,
                fill="#FFFFFF",
            ),
            RectSlot(
                id="slot.label.ㄹ",
                prompt="",
                x=130.5,
                y=355.5,
                width=68.0,
                height=44.0,
                stroke="#CFCFCF",
                stroke_width=4.0,
                fill="#FFFFFF",
            ),
            RectSlot(
                id="slot.label.ㅁ",
                prompt="",
                x=174.5,
                y=220.0,
                width=68.0,
                height=44.0,
                stroke="#CFCFCF",
                stroke_width=4.0,
                fill="#FFFFFF",
            ),
            # Node Texts
            TextSlot(
                id="slot.t.node.387",
                prompt="",
                text="387",
                style_role="answer",
                x=280.0,
                y=199.0,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.node.372",
                prompt="",
                text="372",
                style_role="answer",
                x=423.0,
                y=303.0,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.node.339",
                prompt="",
                text="339",
                style_role="answer",
                x=368.0,
                y=470.0,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.node.323",
                prompt="",
                text="323",
                style_role="answer",
                x=192.0,
                y=470.0,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.node.346",
                prompt="",
                text="346",
                style_role="answer",
                x=137.0,
                y=303.0,
                font_size=28,
                anchor="middle",
            ),
            # Label Texts
            TextSlot(
                id="slot.t.label.ㄱ",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=351.5,
                y=251.0,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.label.ㄴ",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=395.5,
                y=386.5,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.label.ㄷ",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=280.0,
                y=470.0,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.label.ㄹ",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=164.5,
                y=386.5,
                font_size=28,
                anchor="middle",
            ),
            TextSlot(
                id="slot.t.label.ㅁ",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=208.5,
                y=251.0,
                font_size=28,
                anchor="middle",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_cAV8nIGcoF",
    "problem_type": "number_puzzle",
    "metadata": {
        "language": "ko",
        "question": "오각형의 각 변에 있는 세 수의 합이 모두 같도록 ㉠~㉤에 210, 188, 259, 162, 252를 알맞게 써넣는 문제",
        "instruction": "㉠에 들어갈 수를 구하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.n387", "type": "given_number", "value": 387},
            {"id": "obj.n346", "type": "given_number", "value": 346},
            {"id": "obj.n372", "type": "given_number", "value": 372},
            {"id": "obj.n323", "type": "given_number", "value": 323},
            {"id": "obj.n339", "type": "given_number", "value": 339},
            {"id": "obj.x1", "type": "unknown_number", "symbol": "㉠"},
            {"id": "obj.x2", "type": "unknown_number", "symbol": "㉡"},
            {"id": "obj.x3", "type": "unknown_number", "symbol": "㉢"},
            {"id": "obj.x4", "type": "unknown_number", "symbol": "㉣"},
            {"id": "obj.x5", "type": "unknown_number", "symbol": "㉤"},
            {
                "id": "obj.values",
                "type": "number_set",
                "members": [210, 188, 259, 162, 252],
            },
        ],
        "relations": [
            {
                "id": "rel.equal_edge_sum",
                "type": "equal_sum_on_each_edge",
                "from_id": "obj.n387",
                "through": ["obj.x1", "obj.n372"],
                "to_id": "obj.n372",
            }
        ],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.n387",
                    "obj.n346",
                    "obj.n372",
                    "obj.n323",
                    "obj.n339",
                    "obj.values",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.equal_edge_sum"],
            },
            "plan": {
                "method": "equal_edge_sum_balance",
                "description": "각 변의 합이 모두 같다는 조건을 이용해 한 변의 합을 기준으로 미지수를 배치한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_edge_sums",
                    "match_numbers_to_unknowns",
                    "determine_㉠",
                ]
            },
            "review": {"check_methods": ["equal_sum_check", "number_usage_check"]},
        },
    },
    "answer": {
        "target": {"type": "missing_number", "description": "㉠에 들어갈 수"},
        "value": None,
        "unit": "",
    },
}
SOLVABLE = None
