from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    Region,
    TextSlot,
)


SEMANTIC_OVERRIDE = {
    "problem_type": "geometry_right_angle_count",
    "metadata": {
        "instruction": "다음 5개의 점 중에서 3개의 점을 이용하여 직각을 그릴 때, 그릴 수 있는 직각은 모두 몇 개입니까?",
        "question": "5개 점에서 3개 점을 골라 만들 수 있는 직각의 개수를 구하시오.",
        "tags": ["geometry", "right-angle", "grid", "combinatorics"],
    },
    "domain": {
        "objects": [
            {
                "id": "pt.giyeok",
                "type": "point",
                "properties": {"label": "ㄱ", "x": 218.0, "y": 210.0},
                "confidence": 1.0,
            },
            {
                "id": "pt.nieun",
                "type": "point",
                "properties": {"label": "ㄴ", "x": 218.0, "y": 282.0},
                "confidence": 1.0,
            },
            {
                "id": "pt.digeut",
                "type": "point",
                "properties": {"label": "ㄷ", "x": 290.0, "y": 282.0},
                "confidence": 1.0,
            },
            {
                "id": "pt.rieul",
                "type": "point",
                "properties": {"label": "ㄹ", "x": 290.0, "y": 210.0},
                "confidence": 1.0,
            },
            {
                "id": "pt.mieum",
                "type": "point",
                "properties": {"label": "ㅁ", "x": 326.0, "y": 246.0},
                "confidence": 1.0,
            },
            {
                "id": "grid.main",
                "type": "grid",
                "properties": {"rows": 4, "cols": 5},
                "confidence": 1.0,
            },
            {
                "id": "set.points",
                "type": "point_set",
                "properties": {"count": 5, "labels": ["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ"]},
                "confidence": 1.0,
            },
            {
                "id": "comb.triples",
                "type": "combination",
                "properties": {"n": 5, "r": 3, "count": 10},
                "confidence": 1.0,
            },
            {
                "id": "result.right_angle_count",
                "type": "quantity",
                "properties": {"name": "직각의 수", "value": 5, "unit": "개"},
                "confidence": 1.0,
            },
        ],
        "relations": [
            {
                "id": "rel.points.on_grid",
                "type": "defined_on",
                "from_id": "set.points",
                "to_id": "grid.main",
                "properties": {"description": "5개 점은 격자점 위에 배치됨"},
                "confidence": 1.0,
            },
            {
                "id": "rel.comb.from_points",
                "type": "derived_from",
                "from_id": "comb.triples",
                "to_id": "set.points",
                "properties": {"expr": "C(5,3)=10"},
                "confidence": 1.0,
            },
            {
                "id": "rel.angle.abd",
                "type": "right_angle",
                "from_id": "pt.giyeok",
                "to_id": "pt.rieul",
                "properties": {"triple": ["ㄴ", "ㄱ", "ㄹ"], "vertex": "ㄱ"},
                "confidence": 1.0,
            },
            {
                "id": "rel.angle.abc",
                "type": "right_angle",
                "from_id": "pt.nieun",
                "to_id": "pt.giyeok",
                "properties": {"triple": ["ㄱ", "ㄴ", "ㄷ"], "vertex": "ㄴ"},
                "confidence": 1.0,
            },
            {
                "id": "rel.angle.bcd",
                "type": "right_angle",
                "from_id": "pt.digeut",
                "to_id": "pt.nieun",
                "properties": {"triple": ["ㄴ", "ㄷ", "ㄹ"], "vertex": "ㄷ"},
                "confidence": 1.0,
            },
            {
                "id": "rel.angle.cda",
                "type": "right_angle",
                "from_id": "pt.rieul",
                "to_id": "pt.digeut",
                "properties": {"triple": ["ㄱ", "ㄹ", "ㄷ"], "vertex": "ㄹ"},
                "confidence": 1.0,
            },
            {
                "id": "rel.angle.dmr",
                "type": "right_angle",
                "from_id": "pt.digeut",
                "to_id": "pt.rieul",
                "properties": {"triple": ["ㄷ", "ㅁ", "ㄹ"], "vertex": "ㅁ"},
                "confidence": 1.0,
            },
            {
                "id": "rel.target",
                "type": "target",
                "from_id": "set.points",
                "to_id": "result.right_angle_count",
                "properties": {"ask": "직각 개수"},
                "confidence": 1.0,
            },
        ],
        "confidence": 1.0,
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "confidence": 1.0,
        "value": 5,
        "unit": "개",
        "source": "right_angle_count_from_point_triples",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "Hpdf_8mse5GcDz6",
    "problem_type": "geometry_right_angle_count",
    "inputs": {
        "total_ticks": 5,
        "target_label": "직각의 수",
        "target_ticks": 5,
        "target_count": 1,
        "unit": "개",
    },
    "plan": [
        "점 5개에서 3개를 고르는 모든 경우를 확인한다.",
        "각 경우에서 직각이 되는지 판별하고 개수를 합산한다.",
    ],
    "steps": [
        {"id": "s1", "expr": "C(5,3)", "value": 10},
        {
            "id": "s2",
            "expr": "right-angle triples = {(ㄴ,ㄱ,ㄹ), (ㄱ,ㄴ,ㄷ), (ㄴ,ㄷ,ㄹ), (ㄱ,ㄹ,ㄷ), (ㄷ,ㅁ,ㄹ)}",
            "value": 5,
        },
    ],
    "checks": [
        {
            "id": "c1",
            "expr": "count(right-angle triples)",
            "expected": 5,
            "actual": 5,
            "pass": True,
        }
    ],
    "answer": {"value": 5, "unit": "개"},
}


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_8mse5GcDz6",
        title="점 3개로 만들 수 있는 직각의 개수",
        canvas=Canvas(width=558, height=327, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.grid.v1",
                    "slot.grid.v2",
                    "slot.grid.v3",
                    "slot.grid.v4",
                    "slot.grid.v5",
                    "slot.grid.v6",
                    "slot.grid.h1",
                    "slot.grid.h2",
                    "slot.grid.h3",
                    "slot.grid.h4",
                    "slot.grid.h5",
                    "slot.pt.giyeok",
                    "slot.pt.nieun",
                    "slot.pt.digeut",
                    "slot.pt.rieul",
                    "slot.pt.mieum",
                    "slot.lb.giyeok",
                    "slot.lb.nieun",
                    "slot.lb.digeut",
                    "slot.lb.rieul",
                    "slot.lb.mieum",
                ),
            ),
            Region(
                id="region.answer",
                role="answer",
                flow="absolute",
                slot_ids=("slot.answer",),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="다음 5개의 점 중에서 3개의 점을 이용하여 직",
                style_role="body",
                x=8.0,
                y=42.0,
                font_size=22,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="각을 그릴 때, 그릴 수 있는 직각은 모두 몇 개",
                style_role="body",
                x=8.0,
                y=85.0,
                font_size=22,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="입니까?",
                style_role="question",
                x=8.0,
                y=128.0,
                font_size=22,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="",
                style_role="body",
                x=8.0,
                y=150.0,
                font_size=1,
            ),
            LineSlot(
                id="slot.grid.v1",
                prompt="",
                x1=182.0,
                y1=174.0,
                x2=182.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v2",
                prompt="",
                x1=218.0,
                y1=174.0,
                x2=218.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v3",
                prompt="",
                x1=254.0,
                y1=174.0,
                x2=254.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v4",
                prompt="",
                x1=290.0,
                y1=174.0,
                x2=290.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v5",
                prompt="",
                x1=326.0,
                y1=174.0,
                x2=326.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v6",
                prompt="",
                x1=362.0,
                y1=174.0,
                x2=362.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h1",
                prompt="",
                x1=182.0,
                y1=174.0,
                x2=362.0,
                y2=174.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h2",
                prompt="",
                x1=182.0,
                y1=210.0,
                x2=362.0,
                y2=210.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h3",
                prompt="",
                x1=182.0,
                y1=246.0,
                x2=362.0,
                y2=246.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h4",
                prompt="",
                x1=182.0,
                y1=282.0,
                x2=362.0,
                y2=282.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h5",
                prompt="",
                x1=182.0,
                y1=318.0,
                x2=362.0,
                y2=318.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.pt.giyeok",
                prompt="",
                cx=218.0,
                cy=210.0,
                r=3.8,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.pt.nieun", prompt="", cx=218.0, cy=282.0, r=3.8, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.digeut",
                prompt="",
                cx=290.0,
                cy=282.0,
                r=3.8,
                fill="#222222",
            ),
            CircleSlot(
                id="slot.pt.rieul", prompt="", cx=290.0, cy=210.0, r=3.8, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.mieum", prompt="", cx=326.0, cy=246.0, r=3.8, fill="#222222"
            ),
            TextSlot(
                id="slot.lb.giyeok",
                prompt="",
                text="ㄱ",
                style_role="body",
                x=202.0,
                y=202.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.nieun",
                prompt="",
                text="ㄴ",
                style_role="body",
                x=202.0,
                y=297.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.digeut",
                prompt="",
                text="ㄷ",
                style_role="body",
                x=300.0,
                y=297.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.rieul",
                prompt="",
                text="ㄹ",
                style_role="body",
                x=300.0,
                y=202.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.lb.mieum",
                prompt="",
                text="ㅁ",
                style_role="body",
                x=332.0,
                y=238.0,
                font_size=24,
            ),
            TextSlot(
                id="slot.answer",
                prompt="",
                text="답: (        )",
                style_role="answer",
                x=8.0,
                y=310.0,
                font_size=18,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("geometry", "right-angle", "grid"),
    )


PROBLEM_TEMPLATE = build_problem_template()
