from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1280,
        height=720,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.instruction',
             'slot.sub_instruction',
             'slot.eraser_body',
             'slot.eraser_label',
             'slot.major_number_2',
             'slot.major_number_3',
             'slot.major_number_4',
             'slot.major_number_5',
             'slot.answer_left_paren',
             'slot.answer_right_paren'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.instruction',
            prompt='',
            text='2. 지우개의 길이는 몇 mm입니까?',
            style_role='body',
            x=72.0,
            y=80.0,
            font_size=42,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#000000',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.sub_instruction',
            prompt='',
            text='(* 눈금을 보고 써 보아요.)',
            style_role='body',
            x=72.0,
            y=128.0,
            font_size=30,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#000000',
            semantic_role='sub_instruction',
        ),
        LineSlot(
            id='slot.dash_left',
            prompt='',
            x1=493.3333333333333,
            y1=150.0,
            x2=493.3333333333333,
            y2=334.0,
            stroke='#000000',
            stroke_width=3.0,
        ),
        LineSlot(
            id='slot.dash_right',
            prompt='',
            x1=930.6666666666666,
            y1=150.0,
            x2=930.6666666666666,
            y2=334.0,
            stroke='#000000',
            stroke_width=3.0,
        ),
        RectSlot(
            id='slot.eraser_body',
            prompt='',
            x=493.3333333333333,
            y=170.0,
            width=437.3333333333333,
            height=135.0,
            stroke='#111111',
            stroke_width=2.0,
            rx=20.0,
            fill='#E5E5E5',
            semantic_role='target_object',
        ),
        TextSlot(
            id='slot.eraser_label',
            prompt='',
            text='지우개',
            style_role='body',
            x=712.0,
            y=251.5,
            font_size=42,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#000000',
            semantic_role='object_label',
        ),
        RectSlot(
            id='slot.ruler_body',
            prompt='',
            x=220.0,
            y=330.0,
            width=820.0,
            height=170.0,
            stroke='#111111',
            stroke_width=6.0,
            rx=0.0,
            fill='none',
            semantic_role='scale',
        ),
        LineSlot(
            id='slot.tick_00',
            prompt='',
            x1=220.0,
            y1=330.0,
            x2=220.0,
            y2=394.0,
            stroke='#111111',
            stroke_width=6.0,
            semantic_role='tick_major',
        ),
        LineSlot(
            id='slot.tick_01',
            prompt='',
            x1=274.6666666666667,
            y1=330.0,
            x2=274.6666666666667,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_02',
            prompt='',
            x1=329.3333333333333,
            y1=330.0,
            x2=329.3333333333333,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_03',
            prompt='',
            x1=384.0,
            y1=330.0,
            x2=384.0,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_04',
            prompt='',
            x1=438.66666666666663,
            y1=330.0,
            x2=438.66666666666663,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_05',
            prompt='',
            x1=493.3333333333333,
            y1=330.0,
            x2=493.3333333333333,
            y2=394.0,
            stroke='#111111',
            stroke_width=6.0,
            semantic_role='tick_major',
        ),
        LineSlot(
            id='slot.tick_06',
            prompt='',
            x1=548.0,
            y1=330.0,
            x2=548.0,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_07',
            prompt='',
            x1=602.6666666666666,
            y1=330.0,
            x2=602.6666666666666,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_08',
            prompt='',
            x1=657.3333333333333,
            y1=330.0,
            x2=657.3333333333333,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_09',
            prompt='',
            x1=712.0,
            y1=330.0,
            x2=712.0,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_10',
            prompt='',
            x1=766.6666666666666,
            y1=330.0,
            x2=766.6666666666666,
            y2=394.0,
            stroke='#111111',
            stroke_width=6.0,
            semantic_role='tick_major',
        ),
        LineSlot(
            id='slot.tick_11',
            prompt='',
            x1=821.3333333333333,
            y1=330.0,
            x2=821.3333333333333,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_12',
            prompt='',
            x1=876.0,
            y1=330.0,
            x2=876.0,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_13',
            prompt='',
            x1=930.6666666666666,
            y1=330.0,
            x2=930.6666666666666,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_14',
            prompt='',
            x1=985.3333333333333,
            y1=330.0,
            x2=985.3333333333333,
            y2=364.0,
            stroke='#111111',
            stroke_width=5.0,
            semantic_role='tick_minor',
        ),
        LineSlot(
            id='slot.tick_15',
            prompt='',
            x1=1040.0,
            y1=330.0,
            x2=1040.0,
            y2=394.0,
            stroke='#111111',
            stroke_width=6.0,
            semantic_role='tick_major',
        ),
        TextSlot(
            id='slot.major_number_2',
            prompt='',
            text='2',
            style_role='body',
            x=233.03053,
            y=462.0,
            font_size=40,
            font_family='Arial',
            anchor='middle',
            fill='#000000',
        ),
        TextSlot(
            id='slot.major_number_3',
            prompt='',
            text='3',
            style_role='body',
            x=493.3333333333333,
            y=462.0,
            font_size=40,
            font_family='Arial',
            anchor='middle',
            fill='#000000',
        ),
        TextSlot(
            id='slot.major_number_4',
            prompt='',
            text='4',
            style_role='body',
            x=766.6666666666666,
            y=462.0,
            font_size=40,
            font_family='Arial',
            anchor='middle',
            fill='#000000',
        ),
        TextSlot(
            id='slot.major_number_5',
            prompt='',
            text='5',
            style_role='body',
            x=1027.9718,
            y=462.0,
            font_size=40,
            font_family='Arial',
            anchor='middle',
            fill='#000000',
        ),
        TextSlot(
            id='slot.answer_left_paren',
            prompt='',
            text='(',
            style_role='body',
            x=530.0,
            y=640.0,
            font_size=54,
            font_family='Arial',
            anchor='middle',
            fill='#000000',
        ),
        TextSlot(
            id='slot.answer_right_paren',
            prompt='',
            text=')',
            style_role='body',
            x=782.72516,
            y=640.0,
            font_size=54,
            font_family='Arial',
            anchor='middle',
            fill='#000000',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='0002_길이 재기',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0002_길이 재기',
 'problem_type': 'measurement_length_mm',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '지우개의 길이는 몇 mm입니까?',
              'question': '자 눈금을 이용하여 지우개의 길이를 mm 단위로 측정하는 문제',
              'required_layout_ids': ['slot.dash_left',
                                      'slot.dash_right',
                                      'slot.eraser_body',
                                      'slot.ruler_body',
                                      'slot.tick_00',
                                      'slot.tick_01',
                                      'slot.tick_02',
                                      'slot.tick_03',
                                      'slot.tick_04',
                                      'slot.tick_05',
                                      'slot.tick_06',
                                      'slot.tick_07',
                                      'slot.tick_08',
                                      'slot.tick_09',
                                      'slot.tick_10',
                                      'slot.tick_11',
                                      'slot.tick_12',
                                      'slot.tick_13',
                                      'slot.tick_14',
                                      'slot.tick_15'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.eraser', 'type': 'object', 'name': '지우개'},
                        {'id': 'obj.ruler', 'type': 'tool', 'name': '자', 'unit': 'mm'}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'visual_measurement',
                                         'description': '자 눈금의 시작과 끝을 확인하여 길이를 mm 단위로 읽는다.'}}},
 'answer': {'blanks': [],
            'choices': [{'index': 2, 'text': '2. 지우개의 길이는 몇 mm입니까?', 'value': '지우개의 길이는 몇 mm입니까?'}],
            'answer_key': [],
            'confidence': 1.0,
            'value': 16,
            'unit': 'mm',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0002_길이 재기',
 'problem_type': 'measurement_length_mm',
 'inputs': {'total_ticks': 1,
            'target_label': '',
            'target_ticks': 1,
            'target_count': 1,
            'unit': 'mm'},
 'given': [],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': 16,
             'actual': 16,
             'pass': True}],
 'answer': {'value': 16, 'unit': 'mm', 'derived_from': 'step.1'}}
