from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008733",
        title="사다리를 타고 내려가 도착한 곳이 참이면 ○표, 거짓이면 ×표 하세요.",
        canvas=Canvas(width=920, height=650, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.top",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q2",
                    "slot.q9",
                    "slot.q10",
                    "slot.q11",
                    "slot.q18",
                    "slot.q19",
                    "slot.q20",
                    "slot.q21",
                    "slot.q22",
                    "slot.q23",
                    "slot.q24",
                    "slot.q25",
                    "slot.q26",
                    "slot.q27",
                    "slot.q28",
                    "slot.math.fraction.num",
                    "slot.math.fraction.bar",
                    "slot.math.fraction.den",
                    "slot.math.fraction_1.num",
                    "slot.math.fraction_1.bar",
                    "slot.math.fraction_1.den",
                    "slot.math.fraction_2.num",
                    "slot.math.fraction_2.bar",
                    "slot.math.fraction_2.den",
                    "slot.math.fraction_3.num",
                    "slot.math.fraction_3.bar",
                    "slot.math.fraction_3.den",
                    "slot.math.fraction_4.num",
                    "slot.math.fraction_4.bar",
                    "slot.math.fraction_4.den",
                    "slot.math.fraction_5.num",
                    "slot.math.fraction_5.bar",
                    "slot.math.fraction_5.den",
                ),
            ),
            Region(
                id="region.bottom",
                role="support",
                flow="absolute",
                slot_ids=("slot.b39",),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q2",
                prompt="",
                text="사다리를 타고 내려가 도착한 곳이 참이면 ○표, 거짓이면 ×표하세요.",
                style_role="question",
                x=35,
                y=105,
                font_size=30,
            ),
            RectSlot(
                id="slot.q9",
                prompt="",
                x=229,
                y=200,
                width=90,
                height=105,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.q10",
                prompt="",
                x=384,
                y=200,
                width=80,
                height=100,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.q11",
                prompt="",
                x=534,
                y=200,
                width=80,
                height=95,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.q18",
                prompt="",
                x1=275,
                y1=305,
                x2=275,
                y2=425,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.q19",
                prompt="",
                x1=425,
                y1=305,
                x2=425,
                y2=425,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.q20",
                prompt="",
                x1=575,
                y1=300,
                x2=575,
                y2=425,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.q21",
                prompt="",
                x1=275,
                y1=345,
                x2=425,
                y2=345,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.q22",
                prompt="",
                x1=425,
                y1=375,
                x2=575,
                y2=375,
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.q23",
                prompt="",
                x1=275,
                y1=400,
                x2=425,
                y2=400,
                stroke="#111111",
                stroke_width=2,
            ),
            RectSlot(
                id="slot.q24",
                prompt="",
                x=213,
                y=425,
                width=110,
                height=45,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.q25",
                prompt="",
                x=370,
                y=425,
                width=100,
                height=45,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.q26",
                prompt="",
                x=517,
                y=425,
                width=100,
                height=45,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.q27",
                prompt="",
                text="가분수",
                style_role="label",
                x=230,
                y=455,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q28",
                prompt="",
                text="가분수",
                style_role="label",
                x=380,
                y=455,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q29",
                prompt="",
                text="진분수",
                style_role="label",
                x=530,
                y=455,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q30",
                prompt="",
                text="(○, ×)",
                style_role="label",
                x=222,
                y=512,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q31",
                prompt="",
                text="(○, ×)",
                style_role="label",
                x=372,
                y=512,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q32",
                prompt="",
                text="(○, ×)",
                style_role="label",
                x=522,
                y=512,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.b39",
                prompt="",
                text="",
                style_role="label",
                x=0.0,
                y=0.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.math.fraction.num",
                prompt="",
                text="2",
                x=((((((460) + (380.0)) + (-555.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y=((((415) + (-160.0)) + (-15.0)) + (5.0)) + (-1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction.bar",
                prompt="",
                x1=((((((440) + (380.0)) + (-555.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y1=((((430) + (-160.0)) + (-15.0)) + (5.0)) + (-1.0),
                x2=((((((480) + (380.0)) + (-555.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y2=((((430) + (-160.0)) + (-15.0)) + (5.0)) + (-1.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction.den",
                prompt="",
                text="8",
                x=((((((460) + (380.0)) + (-555.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y=((((455) + (-160.0)) + (-15.0)) + (5.0)) + (-1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_1.num",
                prompt="",
                text="9",
                x=((((((460) + (-30.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (1.0),
                y=((415) + (-170.0)) + (-1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_1.bar",
                prompt="",
                x1=((((((440) + (-30.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (1.0),
                y1=((430) + (-170.0)) + (-1.0),
                x2=((((((480) + (-30.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (1.0),
                y2=((430) + (-170.0)) + (-1.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_1.den",
                prompt="",
                text="10",
                x=((((((460) + (-30.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (1.0),
                y=((455) + (-170.0)) + (-1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_2.num",
                prompt="",
                text="4",
                x=(((((((460) + (115.0)) + (1.0)) + (1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y=((((((415) + (-165.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_2.bar",
                prompt="",
                x1=(((((((440) + (115.0)) + (1.0)) + (1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y1=((((((430) + (-165.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                x2=(((((((480) + (115.0)) + (1.0)) + (1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y2=((((((430) + (-165.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_2.den",
                prompt="",
                text="4",
                x=(((((((460) + (115.0)) + (1.0)) + (1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                y=((((((455) + (-165.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0)) + (-1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_3.num",
                prompt="",
                text="3",
                x=(460) + (-185.0),
                y=(310) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_3.bar",
                prompt="",
                x1=(440) + (-185.0),
                y1=(325) + (-70.0),
                x2=(480) + (-185.0),
                y2=(325) + (-70.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_3.den",
                prompt="",
                text="10",
                x=(460) + (-185.0),
                y=(350) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_4.num",
                prompt="",
                text="2",
                x=(460) + (-35.0),
                y=(310) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_4.bar",
                prompt="",
                x1=(440) + (-35.0),
                y1=(325) + (-70.0),
                x2=(480) + (-35.0),
                y2=(325) + (-70.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_4.den",
                prompt="",
                text="2",
                x=(460) + (-35.0),
                y=(350) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_5.num",
                prompt="",
                text="15",
                x=(460) + (115.0),
                y=(310) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_5.bar",
                prompt="",
                x1=(440) + (115.0),
                y1=(325) + (-70.0),
                x2=(480) + (115.0),
                y2=(325) + (-70.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_5.den",
                prompt="",
                text="7",
                x=(460) + (115.0),
                y=(350) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008733",
    "problem_type": "분수 분류",
    "metadata": {
        "language": "ko",
        "question": "사다리를 타고 내려가 도착한 곳이 참이면 ○표, 거짓이면 ×표를 선택하는 문제",
        "instruction": "분수를 가분수와 진분수로 분류한다.",
        "points": 5,
    },
    "domain": {
        "objects": [
            {"id": "obj.frac.1", "type": "fraction", "value": "3/10"},
            {"id": "obj.frac.2", "type": "fraction", "value": "2/2"},
            {"id": "obj.frac.3", "type": "fraction", "value": "15/7"},
            {"id": "obj.class.1", "type": "classification", "value": "가분수"},
            {"id": "obj.class.2", "type": "classification", "value": "진분수"},
            {"id": "obj.class.3", "type": "classification", "value": "진분수"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.frac.1", "obj.frac.2", "obj.frac.3"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.match.1", "rel.match.2", "rel.match.3"],
            },
            "plan": {
                "method": "분수의 분류 확인",
                "description": "각 분수가 가분수인지 진분수인지 분류를 확인한다.",
            },
            "execute": {"expected_operations": ["분류 확인", "선택지 대응 확인"]},
            "review": {"check_methods": ["화면에 보이는 해설과 대응 관계 확인"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selection_pattern", "description": "○, ×, ○"},
        "value": "○, ×, ○",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008733",
    "problem_type": "분수 분류",
    "inputs": {
        "total_ticks": 3,
        "target_label": "선택 결과",
        "target_ticks": 3,
        "target_count": 3,
        "unit": "",
    },
    "given": [
        {"ref": "obj.frac.1", "value": "3/10"},
        {"ref": "obj.frac.2", "value": "2/2"},
        {"ref": "obj.frac.3", "value": "15/7"},
    ],
    "target": {"ref": "answer.target", "type": "selection_pattern"},
    "method": "분수 분류 확인",
    "plan": ["각 분수를 보고 가분수와 진분수를 구분한다.", "화면에 제시된 해설과 대응을 확인한다."],
    "steps": [
        {"id": "step.1", "expr": "3/10의 분류 확인", "value": "진분수"},
        {"id": "step.2", "expr": "2/2의 분류 확인", "value": "가분수"},
        {"id": "step.3", "expr": "15/7의 분류 확인", "value": "가분수"},
        {"id": "step.4", "expr": "선택 결과", "value": "○, ×, ○"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "화면의 (정답) 표기와 선택 결과 일치 여부",
            "expected": "○, ×, ○",
            "actual": "○, ×, ○",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selection_pattern", "description": "○, ×, ○"},
        "value": "○, ×, ○",
        "unit": "",
    },
}
