from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008742",
        title="두 분수의 크기 비교",
        canvas=Canvas(width=960, height=700, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q2", "slot.q3", "slot.q2.copy1"),
            ),
            Region(
                id="region.diagram.top",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.top.box",
                    "slot.top.text",
                    "slot.top.line",
                    "slot.mid.left.box",
                    "slot.mid.right.box",
                    "slot.mid.connector",
                    "slot.leaf.1",
                    "slot.leaf.2",
                    "slot.leaf.3",
                    "slot.leaf.4",
                    "slot.math.fraction.num",
                    "slot.math.fraction.bar",
                    "slot.math.fraction.den",
                    "slot.math.fraction_1.num",
                    "slot.math.fraction_1.bar",
                    "slot.math.fraction_1.den",
                    "slot.math.mixed_fraction.whole",
                    "slot.math.mixed_fraction.num",
                    "slot.math.mixed_fraction.bar",
                    "slot.math.mixed_fraction.den",
                    "slot.math.mixed_fraction_1.whole",
                    "slot.math.mixed_fraction_1.num",
                    "slot.math.mixed_fraction_1.bar",
                    "slot.math.mixed_fraction_1.den",
                    "slot.top.line.copy10",
                    "slot.top.line.copy11",
                    "slot.mid.connector.copy12",
                    "slot.mid.connector.copy13",
                    "slot.top.line.copy14",
                    "slot.top.line.copy15",
                    "slot.top.line.copy14.copy16",
                    "slot.top.line.copy14.copy17",
                    "slot.top.line.copy14.copy18",
                    "slot.top.line.copy14.copy19",
                ),
            ),
            Region(id="region.note", role="annotation", flow="absolute", slot_ids=()),
            Region(id="region.diagram.bottom", role="diagram", flow="absolute", slot_ids=()),
            Region(id="region.solution.text", role="explanation", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.math.fraction.num",
                prompt="",
                text="23",
                x=((200) + (-10.0)) + (325.0),
                y=((((((475) + (125.0)) + (-1.0)) + (-55.0)) + (95.0)) + (-105.0)) + (1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction.bar",
                prompt="",
                x1=((180) + (-10.0)) + (325.0),
                y1=((((((492) + (125.0)) + (-1.0)) + (-55.0)) + (95.0)) + (-105.0)) + (1.0),
                x2=((220) + (-10.0)) + (325.0),
                y2=((((((492) + (125.0)) + (-1.0)) + (-55.0)) + (95.0)) + (-105.0)) + (1.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction.den",
                prompt="",
                text="15",
                x=((200) + (-10.0)) + (325.0),
                y=((((((520) + (125.0)) + (-1.0)) + (-55.0)) + (95.0)) + (-105.0)) + (1.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_1.num",
                prompt="",
                text="26",
                x=((((337) + (-10.0)) + (5.0)) + (325.0)) + (-1.0),
                y=(((((475) + (125.0)) + (-1.0)) + (-60.0)) + (105.0)) + (-110.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_1.bar",
                prompt="",
                x1=((((317) + (-10.0)) + (5.0)) + (325.0)) + (-1.0),
                y1=(((((492) + (125.0)) + (-1.0)) + (-60.0)) + (105.0)) + (-110.0),
                x2=((((357) + (-10.0)) + (5.0)) + (325.0)) + (-1.0),
                y2=(((((492) + (125.0)) + (-1.0)) + (-60.0)) + (105.0)) + (-110.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_1.den",
                prompt="",
                text="15",
                x=((((337) + (-10.0)) + (5.0)) + (325.0)) + (-1.0),
                y=(((((520) + (125.0)) + (-1.0)) + (-60.0)) + (105.0)) + (-110.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction.whole",
                prompt="",
                text="1",
                x=(((510) + (-20.0)) + (-340.0)) + (20.0),
                y=((((500) + (125.0)) + (-60.0)) + (95.0)) + (-95.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction.num",
                prompt="",
                text="3",
                x=(((542) + (-20.0)) + (-340.0)) + (20.0),
                y=((((475) + (125.0)) + (-60.0)) + (95.0)) + (-95.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction.bar",
                prompt="",
                x1=(((522) + (-20.0)) + (-340.0)) + (20.0),
                y1=((((492) + (125.0)) + (-60.0)) + (95.0)) + (-95.0),
                x2=(((562) + (-20.0)) + (-340.0)) + (20.0),
                y2=((((492) + (125.0)) + (-60.0)) + (95.0)) + (-95.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction.den",
                prompt="",
                text="15",
                x=(((542) + (-20.0)) + (-340.0)) + (20.0),
                y=((((520) + (125.0)) + (-60.0)) + (95.0)) + (-95.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.whole",
                prompt="",
                text="1",
                x=(((645) + (-15.0)) + (-335.0)) + (10.0),
                y=(((((500) + (120.0)) + (-5.0)) + (-55.0)) + (110.0)) + (-105.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.num",
                prompt="",
                text="1",
                x=(((677) + (-15.0)) + (-335.0)) + (10.0),
                y=(((((475) + (120.0)) + (-5.0)) + (-55.0)) + (110.0)) + (-105.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction_1.bar",
                prompt="",
                x1=(((657) + (-15.0)) + (-335.0)) + (10.0),
                y1=(((((492) + (120.0)) + (-5.0)) + (-55.0)) + (110.0)) + (-105.0),
                x2=(((697) + (-15.0)) + (-335.0)) + (10.0),
                y2=(((((492) + (120.0)) + (-5.0)) + (-55.0)) + (110.0)) + (-105.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.den",
                prompt="",
                text="15",
                x=(((677) + (-15.0)) + (-335.0)) + (10.0),
                y=(((((520) + (120.0)) + (-5.0)) + (-55.0)) + (110.0)) + (-105.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="두 분수의 크기를 비교하여 빨간색 선을 만나면 큰 분수를,",
                style_role="question",
                x=25,
                y=80,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="㉠에 들어갈 분수로 알맞은 것을 가장 아래 칸의 분수들 중에 선택해 보세요.",
                style_role="question",
                x=20,
                y=175,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.top.box",
                prompt="",
                x=370,
                y=224,
                width=100,
                height=95,
                fill="#FFFFFF",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.top.text",
                prompt="",
                text="㉠",
                style_role="label",
                x=405,
                y=281,
                font_size=30,
                fill="#111111",
            ),
            LineSlot(
                id="slot.top.line",
                prompt="",
                x1=419,
                y1=319,
                x2=419,
                y2=339,
                stroke="#dc2626",
                stroke_width=1.6,
            ),
            RectSlot(
                id="slot.mid.left.box",
                prompt="",
                x=208,
                y=362,
                width=100,
                height=95,
                fill="#FFFFFF",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.mid.right.box",
                prompt="",
                x=530,
                y=359,
                width=100,
                height=95,
                fill="#FFFFFF",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.mid.connector",
                prompt="",
                x1=255,
                y1=339,
                x2=580,
                y2=339,
                stroke="#dc2626",
                stroke_width=1.6,
            ),
            RectSlot(
                id="slot.leaf.1",
                prompt="",
                x=140,
                y=504,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.leaf.2",
                prompt="",
                x=277,
                y=502,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.leaf.3",
                prompt="",
                x=465,
                y=500,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.leaf.4",
                prompt="",
                x=601,
                y=499,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.top.line.copy10",
                prompt="",
                x1=580,
                y1=338,
                x2=580,
                y2=358,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy11",
                prompt="",
                x1=257,
                y1=341,
                x2=257,
                y2=361,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.mid.connector.copy12",
                prompt="",
                x1=190,
                y1=482,
                x2=325,
                y2=482,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.mid.connector.copy13",
                prompt="",
                x1=511,
                y1=474,
                x2=651,
                y2=474,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14",
                prompt="",
                x1=255,
                y1=460,
                x2=255,
                y2=480,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy15",
                prompt="",
                x1=581,
                y1=453,
                x2=581,
                y2=473,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy16",
                prompt="",
                x1=190,
                y1=482,
                x2=190,
                y2=502,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy17",
                prompt="",
                x1=324,
                y1=482,
                x2=324,
                y2=502,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy18",
                prompt="",
                x1=511,
                y1=474,
                x2=511,
                y2=499,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy19",
                prompt="",
                x1=651,
                y1=474,
                x2=651,
                y2=499,
                stroke="#666666",
                stroke_width=1.6,
            ),
            TextSlot(
                id="slot.q2.copy1",
                prompt="",
                text="파란색 선을 만나면 작은 분수를 빈칸에 써넣으려고 합니다.",
                x=20,
                y=125,
                font_size=30,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008742",
    "problem_type": "분수_크기_비교",
    "metadata": {
        "language": "ko",
        "question": "두 분수의 크기를 비교하여 선택 규칙에 따라 ㉠에 들어갈 분수를 고르는 문제",
        "instruction": "아래 도식과 비교식을 보고 ㉠에 알맞은 분수를 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.left_pair_a", "type": "fraction", "value": "1 3/15"},
            {"id": "obj.left_pair_b", "type": "fraction", "value": "1 1/15"},
            {"id": "obj.right_pair_a", "type": "fraction", "value": "23/15"},
            {"id": "obj.right_pair_b", "type": "fraction", "value": "26/15"},
            {"id": "obj.target_slot", "type": "blank", "label": "㉠"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.left_pair_a",
                    "obj.left_pair_b",
                    "obj.right_pair_a",
                    "obj.right_pair_b",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.left_compare", "rel.right_compare", "rel.final_selection"],
            },
            "plan": {
                "method": "fraction_comparison_then_selection",
                "description": "두 쌍의 분수를 각각 비교하여 조건에 맞는 분수를 중간 결과로 고른 뒤, 그 결과를 다시 비교해 ㉠에 들어갈 분수를 선택한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_left_pair",
                    "compare_right_pair",
                    "select_middle_results",
                    "compare_middle_results",
                ]
            },
            "review": {"check_methods": ["comparison_direction_check", "selection_rule_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "fraction_to_fill_blank", "description": "㉠에 들어갈 분수"},
        "value": "23/15",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008742",
    "problem_type": "분수_크기_비교",
    "inputs": {
        "total_ticks": 4,
        "target_label": "㉠",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.left_pair_a", "value": "1 3/15"},
        {"ref": "obj.left_pair_b", "value": "1 1/15"},
        {"ref": "obj.right_pair_a", "value": "23/15"},
        {"ref": "obj.right_pair_b", "value": "26/15"},
    ],
    "target": {"ref": "answer.target", "type": "fraction_to_fill_blank"},
    "method": "fraction_comparison_then_selection",
    "plan": [
        "왼쪽 두 분수를 비교해 큰 분수를 고른다.",
        "오른쪽 두 분수를 비교해 작은 분수를 고른다.",
        "두 결과를 다시 비교하여 ㉠에 들어갈 분수를 정한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "1 3/15 > 1 1/15", "value": True},
        {"id": "step.2", "expr": "23/15 < 26/15", "value": True},
        {"id": "step.3", "expr": "중간 결과 비교", "value": "1 3/15 < 23/15"},
        {"id": "step.4", "expr": "㉠에 들어갈 분수 선택", "value": "23/15"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "선택 규칙에 따라 큰 분수와 작은 분수를 고르는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "최종 선택이 중간 비교 결과와 일치하는가",
            "expected": "23/15",
            "actual": "23/15",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "fraction_to_fill_blank", "description": "㉠에 들어갈 분수"},
        "value": "23/15",
        "unit": "",
    },
}
