from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=980,
        height=493,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.l1b',
             'slot.card_t_1',
             'slot.card_t_2',
             'slot.card_t_3',
             'slot.card_t_4',
             'slot.l1a',
             'slot.l2',
             'slot.l3',
             'slot.l4',
             'slot.div_sign'),
        ),
    )
    slots = (
        RectSlot(
            id='slot.bg',
            prompt='',
            x=0.0,
            y=0.0,
            width=980.0,
            height=493.0,
            stroke='none',
            stroke_width=0.0,
            fill='#F6F6F6',
            semantic_role='background',
        ),
        RectSlot(
            id='slot.card_1',
            prompt='',
            x=188.0,
            y=13.95,
            width=50.87,
            height=52.32,
            stroke='#000000',
            stroke_width=1.0,
            fill='#BDBDBD',
            semantic_role='card',
        ),
        RectSlot(
            id='slot.card_2',
            prompt='',
            x=256.5,
            y=13.95,
            width=49.65,
            height=53.54,
            stroke='#000000',
            stroke_width=1.0,
            fill='#BDBDBD',
            semantic_role='card',
        ),
        RectSlot(
            id='slot.card_3',
            prompt='',
            x=322.5,
            y=13.97,
            width=52.06,
            height=54.73,
            stroke='#000000',
            stroke_width=1.0,
            fill='#BDBDBD',
            semantic_role='card',
        ),
        RectSlot(
            id='slot.card_4',
            prompt='',
            x=389.8,
            y=13.98,
            width=52.05,
            height=55.94,
            stroke='#000000',
            stroke_width=1.0,
            fill='#BDBDBD',
            semantic_role='card',
        ),
        TextSlot(
            id='slot.l1b',
            prompt='',
            text='를 모두 한 번씩만 사용하여',
            style_role='body',
            x=458.35,
            y=54.1,
            font_size=33,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.card_t_1',
            prompt='',
            text='3',
            style_role='body',
            x=213.435,
            y=55.0,
            font_size=46,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='card_value',
        ),
        TextSlot(
            id='slot.card_t_2',
            prompt='',
            text='5',
            style_role='body',
            x=281.325,
            y=55.0,
            font_size=46,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='card_value',
        ),
        TextSlot(
            id='slot.card_t_3',
            prompt='',
            text='7',
            style_role='body',
            x=348.53,
            y=55.0,
            font_size=46,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='card_value',
        ),
        TextSlot(
            id='slot.card_t_4',
            prompt='',
            text='9',
            style_role='body',
            x=415.825,
            y=55.0,
            font_size=46,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='card_value',
        ),
        TextSlot(
            id='slot.l1a',
            prompt='',
            text='숫자 카드',
            style_role='body',
            x=21.45,
            y=56.56,
            font_size=34,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.l2',
            prompt='',
            text='다음과 같이 (대분수) ÷ (자연수)를 만들려고 합니다.',
            style_role='body',
            x=21.72,
            y=114.22,
            font_size=32,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.l3',
            prompt='',
            text='만들 수 있는 값 중 몫이 가장 작을 때의 몫과 몫이',
            style_role='body',
            x=19.62,
            y=164.03,
            font_size=32,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        TextSlot(
            id='slot.l4',
            prompt='',
            text='가장 클 때의 몫 사이에 있는 자연수는 모두 몇 개인가요?',
            style_role='body',
            x=18.35,
            y=215.79,
            font_size=33,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        RectSlot(
            id='slot.expr_box',
            prompt='',
            x=268.99,
            y=308.46,
            width=315.14,
            height=160.19,
            stroke='#000000',
            stroke_width=1.0,
            rx=14.0,
            fill='none',
            semantic_role='expression',
        ),
        RectSlot(
            id='slot.frac_num_blank',
            prompt='',
            x=383.11,
            y=343.79,
            width=36.0,
            height=34.0,
            stroke='#000000',
            stroke_width=1.0,
            fill='none',
            semantic_role='answer_blank',
        ),
        RectSlot(
            id='slot.whole_blank',
            prompt='',
            x=321.11,
            y=373.79,
            width=36.0,
            height=34.0,
            stroke='#000000',
            stroke_width=1.0,
            fill='none',
            semantic_role='answer_blank',
        ),
        RectSlot(
            id='slot.div_blank',
            prompt='',
            x=486.11,
            y=373.79,
            width=36.0,
            height=34.0,
            stroke='#000000',
            stroke_width=1.0,
            fill='none',
            semantic_role='answer_blank',
        ),
        LineSlot(
            id='slot.frac_bar',
            prompt='',
            x1=369.11,
            y1=390.79,
            x2=433.11,
            y2=390.79,
            stroke='#222222',
            stroke_width=2.0,
            semantic_role='operator',
        ),
        RectSlot(
            id='slot.frac_den_blank',
            prompt='',
            x=383.11,
            y=405.79,
            width=36.0,
            height=34.0,
            stroke='#000000',
            stroke_width=1.0,
            fill='none',
            semantic_role='answer_blank',
        ),
        TextSlot(
            id='slot.div_sign',
            prompt='',
            text='÷',
            style_role='body',
            x=457.11,
            y=406.79,
            font_size=64,
            font_family='Malgun Gothic',
            anchor='middle',
            fill='#222222',
            semantic_role='operator',
        ),
    )
    diagrams = ()
    groups = ()
    constraints = ()
    return ProblemTemplate(
        id='0014_나눗셈 범위',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    'problem_id': '0014_나눗셈 범위',
    'problem_type': 'arithmetic_division_range_count',
    'metadata': {
        'language': 'ko',
        'question': '숫자 카드를 사용하여 만든 나눗셈 식의 몫의 최소값과 최대값 사이의 자연수 개수를 구하는 문제',
        'instruction': '몫이 가장 작을 때와 가장 클 때의 몫 사이에 있는 자연수는 모두 몇 개인가요?',
    },
    'domain': {
        'objects': [
            {'id': 'obj.cards', 'type': 'number_cards', 'values': [3, 5, 7, 9]},
            {'id': 'obj.expr', 'type': 'division_expression', 'form': '(A B/C) / D'},
        ],
        'problem_solving': {
            'plan': {
                'method': 'extreme_value_analysis',
                'description': '몫을 최소화(A=3, D=9, C=7, B=5)하고 최대화(A=9, D=3, C=7, B=5)하는 조합을 찾아 범위를 구한다.',
            }
        },
    },
    'answer': {
        'value': 3,
        'unit': '개',
    },
}

SOLVABLE = {
    'schema': 'modu.solvable.v1',
    'problem_id': '0014_나눗셈 범위',
    'problem_type': 'arithmetic_division_range_count',
    'given': [
        {'ref': 'obj.cards', 'values': [3, 5, 7, 9]}
    ],
    'target': {'type': 'number', 'description': '범위 내 자연수 개수'},
    'method': 'extreme_value_analysis',
    'steps': [
        {
            'id': 'step.s1',
            'operation': 'calculation',
            'expr': '최소_몫 = (3 + 5/7) / 9 = 26/63 ≈ 0.412',
            'value': 0.412
        },
        {
            'id': 'step.s2',
            'operation': 'calculation',
            'expr': '최대_몫 = (9 + 5/7) / 3 = 68/21 ≈ 3.238',
            'value': 3.238
        },
        {
            'id': 'step.s3',
            'operation': 'counting',
            'expr': '범위_내_자연수 = {1, 2, 3}',
            'value': 3
        }
    ],
    'checks': [
        {
            'id': 'check.c1',
            'expr': 'integer_range_counting_check',
            'pass': True,
            'expected': 3,
            'actual': 3
        }
    ],
    'answer': {'value': 3, 'unit': '개', 'derived_from': 'step.s3'},
    'inputs': {
        'total_ticks': 1,
        'target_label': '개수',
        'target_ticks': 1,
        'target_count': 1,
        'unit': '개'
    },
    'plan': ['카드를 조합하여 만든 최소 몫(약 0.412)과 최대 몫(약 3.238) 사이의 자연수 1, 2, 3의 개수를 구합니다.']
}
