from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_qq8Nf5bcmq",
        title="수 카드 만들기",
        canvas=Canvas(width=558, height=282, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                    "slot.q5",
                    "slot.q6",
                ),
            ),
            Region(
                id="region.cards",
                role="diagram",
                flow="absolute",
                slot_ids=("slot.card.1", "slot.card.2", "slot.card.3", "slot.card.4"),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="서로 다른 4장의 수 카드 중에서 3장을 골라 한",
                style_role="question",
                x=12.0,
                y=38.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="번씩만 사용하여 세 자리 수를 만들려고 합니",
                style_role="question",
                x=12.0,
                y=76.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="다. 만들 수 있는 가장 큰 수가 가장 작은 수보",
                style_role="question",
                x=12.0,
                y=114.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="다 618만큼 더 크다면 ▲는 어떤 숫자입니까?",
                style_role="question",
                x=12.0,
                y=152.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.card.1",
                prompt="",
                x=145.0,
                y=221.0,
                width=44.0,
                height=49.0,
                stroke="#6E6E6E",
                stroke_width=1.6,
                rx=6.0,
                ry=6.0,
                fill="#D9D9D9",
            ),
            TextSlot(
                id="slot.card.1.text",
                prompt="",
                text="6",
                style_role="label",
                x=167.0,
                y=253.0,
                font_size=28,
                anchor="middle",
            ),
            RectSlot(
                id="slot.card.2",
                prompt="",
                x=220.0,
                y=221.0,
                width=44.0,
                height=49.0,
                stroke="#6E6E6E",
                stroke_width=1.6,
                rx=6.0,
                ry=6.0,
                fill="#D9D9D9",
            ),
            TextSlot(
                id="slot.card.2.text",
                prompt="",
                text="2",
                style_role="label",
                x=242.0,
                y=253.0,
                font_size=28,
                anchor="middle",
            ),
            RectSlot(
                id="slot.card.3",
                prompt="",
                x=295.0,
                y=221.0,
                width=44.0,
                height=49.0,
                stroke="#6E6E6E",
                stroke_width=1.6,
                rx=6.0,
                ry=6.0,
                fill="#D9D9D9",
            ),
            TextSlot(
                id="slot.card.3.text",
                prompt="",
                text="▲",
                style_role="label",
                x=317.0,
                y=253.0,
                font_size=28,
                anchor="middle",
            ),
            RectSlot(
                id="slot.card.4",
                prompt="",
                x=370.0,
                y=221.0,
                width=44.0,
                height=49.0,
                stroke="#6E6E6E",
                stroke_width=1.6,
                rx=6.0,
                ry=6.0,
                fill="#D9D9D9",
            ),
            TextSlot(
                id="slot.card.4.text",
                prompt="",
                text="8",
                style_role="label",
                x=392.0,
                y=253.0,
                font_size=28,
                anchor="middle",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_qq8Nf5bcmq",
    "problem_type": "number_construction",
    "metadata": {
        "language": "ko",
        "question": "서로 다른 4장의 수 카드 중에서 3장을 골라 한 번씩만 사용하여 세 자리 수를 만들려고 한다. 만들 수 있는 가장 큰 수가 가장 작은 수보다 618만큼 더 크다. ▲는 어떤 숫자입니까?",
        "instruction": "▲에 알맞은 숫자를 구하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.card_6", "type": "digit_card", "value": 6},
            {"id": "obj.card_2", "type": "digit_card", "value": 2},
            {"id": "obj.card_triangle", "type": "digit_card", "symbol": "▲"},
            {"id": "obj.card_8", "type": "digit_card", "value": 8},
        ],
        "relations": [
            {
                "id": "rel.construct_three_digit_numbers",
                "type": "choose_3_from_4_and_arrange",
                "from_id": "obj.card_6",
                "to_id": "obj.card_triangle",
            },
            {
                "id": "rel.range_difference",
                "type": "difference_between_max_and_min",
                "from_id": "obj.card_6",
                "to_id": "obj.card_8",
            },
        ],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.card_6",
                    "obj.card_2",
                    "obj.card_triangle",
                    "obj.card_8",
                ],
                "target_ref": "answer.target",
                "condition_refs": [
                    "rel.construct_three_digit_numbers",
                    "rel.range_difference",
                ],
            },
            "plan": {
                "method": "digit_search",
                "description": "세 자리 수의 최댓값과 최솟값을 만들고, 두 수의 차가 618이 되도록 ▲를 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_max_and_min_numbers",
                    "compare_difference",
                    "find_missing_digit",
                ]
            },
            "review": {"check_methods": ["difference_check", "digit_validity_check"]},
        },
    },
    "answer": {
        "target": {"type": "digit", "description": "▲에 들어갈 숫자"},
        "value": 4,
        "unit": "",
    },
}
SOLVABLE = {   'schema': 'modu.solvable.v1',
    'problem_id': 'Hpdf_qq8Nf5bcmq',
    'problem_type': 'number_construction',
    'given': [   {'ref': 'obj.card_6', 'value': 6},
                 {'ref': 'obj.card_2', 'value': 2},
                 {'ref': 'obj.card_8', 'value': 8},
                 {'ref': 'obj.card_triangle', 'value': None}],
    'target': {'ref': 'answer.target', 'type': 'digit'},
    'method': 'digit_search',
    'steps': [   {   'id': 'step.s1',
                     'operation': 'compare_candidate_digits',
                     'expr': '세 자리 수의 최댓값과 최솟값의 차가 618이 되도록 ▲를 찾는다.',
                     'value': None},
                 {'id': 'step.s2', 'operation': 'solve_digit', 'expr': '▲ = 4', 'value': 4}],
    'checks': [   {   'id': 'check.c1',
                      'type': 'difference_check',
                      'expr': '최댓값 - 최솟값 = 618',
                      'pass': True,
                      'expected': 1,
                      'actual': 1},
                  {   'id': 'check.c2',
                      'type': 'digit_validity_check',
                      'expr': '▲는 한 자리 숫자',
                      'pass': True,
                      'expected': 1,
                      'actual': 1}],
    'answer': {'value': 4, 'unit': '', 'derived_from': 'step.s2'},
    'inputs': {   'total_ticks': 1,
                  'target_label': '답',
                  'target_ticks': 1,
                  'target_count': 1,
                  'unit': ''},
    'plan': ['풀이 과정 없음']}
