from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextBoxSlot,
RectSlot)


PROBLEM_ID = "P3_1_01_00040_02154"
PROBLEM_TITLE = "諛쏆븘?щ┝???덈뒗 ???먮━ ?섏쓽 ?㏃뀍"


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id=PROBLEM_ID,
        title=PROBLEM_TITLE,
        canvas=Canvas(
            width=900,
            height=220,
            coordinate_mode="logical",
        ),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.instruction",'konva_1785114682783_paste_104870_0', 'konva_1785114682783_paste_111670_0', 'konva_1785114682783_paste_120157_0', 'konva_1785114682783_paste_126081_0', 'konva_1785114682783_paste_147820_0', 'konva_1785114682783_paste_147820_1', 'konva_1785114682783_paste_147820_2', 'konva_1785114682783_paste_147820_3', 'konva_1785114682783_paste_180671_0', 'konva_1785114682783_paste_180671_1', 'konva_1785114682783_paste_185807_0', 'konva_1785114682783_paste_185807_1'),
            ),
            Region(
                id="region.problem_1",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.problem_1_number",
                    "slot.problem_1_carry_hundreds",
                    "slot.problem_1_carry_tens",
                    "slot.problem_1_first_addend",
                    "slot.problem_1_plus_sign",
                    "slot.problem_1_second_addend",
                    "slot.problem_1_line",
                    "slot.problem_1_answer_thousands",
                    "slot.problem_1_answer_hundreds",
                    "slot.problem_1_answer_tens",
                    "slot.problem_1_answer_ones",
                ),
            ),
            Region(
                id="region.problem_2",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.problem_2_number",
                    "slot.problem_2_carry_hundreds",
                    "slot.problem_2_carry_tens",
                    "slot.problem_2_first_addend",
                    "slot.problem_2_plus_sign",
                    "slot.problem_2_second_addend",
                    "slot.problem_2_line",
                    "slot.problem_2_answer_thousands",
                    "slot.problem_2_answer_hundreds",
                    "slot.problem_2_answer_tens",
                    "slot.problem_2_answer_ones",
                ),
            ),
        ),
        slots=(TextBoxSlot(
                id="slot.instruction",
                x=20,
                y=8,
                width=840,
                height=34,
                text="???덉뿉 ?뚮쭪? ?섎? ?⑤꽔?쇱떆??",
                font_size=23,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="left",
                valign="middle",
            ),

            # (1) 529 + 775
            TextBoxSlot(
                id="slot.problem_1_number",
                x=24,
                y = 70.394, width=34,
                height=32,
                text="(1)",
                font_size=22,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_carry_hundreds",
                x=63,
                y=38,
                width=28,
                height=28,
                text="",
                font_size=27,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_carry_tens",
                x=94,
                y=38,
                width=28,
                height=28,
                text="",
                font_size=27,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_first_addend",
                x=55,
                y = 83, width=104,
                height=32,
                text="5 2 9",
                font_size=25,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_plus_sign",
                x=41,
                y = 119, width=24,
                height=32,
                text="+",
                font_size=25,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_second_addend",
                x=55,
                y = 119, width=104,
                height=32,
                text="7 7 5",
                font_size=25,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_line",
                x=43,
                y = 147, width=122,
                height=18,
                text="???????",
                font_size=20,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_thousands",
                x=43,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_hundreds",
                x=74,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_tens",
                x=105,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_ones",
                x=136,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),

            # (2) 257 + 769
            TextBoxSlot(
                id="slot.problem_2_number",
                x=137,
                y = 68.134, width=34,
                height=32,
                text="(2)",
                font_size=22,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_carry_hundreds",
                x=180,
                y=38,
                width=28,
                height=28,
                text="",
                font_size=27,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_carry_tens",
                x=211,
                y=38,
                width=28,
                height=28,
                text="",
                font_size=27,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_first_addend",
                x=172,
                y = 84.435, width=104,
                height=32,
                text="2 5 7",
                font_size=25,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_plus_sign",
                x=158,
                y = 120.435, width=24,
                height=32,
                text="+",
                font_size=25,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_second_addend",
                x=172,
                y = 120.435, width=104,
                height=32,
                text="7 6 9",
                font_size=25,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_line",
                x=160,
                y = 148.435, width=122,
                height=18,
                text="???????",
                font_size=20,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_thousands",
                x=160,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_hundreds",
                x=191,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_tens",
                x=222,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_ones",
                x=253,
                y=146,
                width=34,
                height=38,
                text="",
                font_size=34,
                font_family='"Poor Story", "Noto Sans KR", sans-serif',
                fill="#111111",
                align="center",
                valign="middle",
            ),RectSlot(id = 'konva_1785114682783_paste_104870_0', prompt = '', x = 123.957, y = 170.956, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_111670_0', prompt = '', x = 97.239, y = 170.525, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_120157_0', prompt = '', x = 70.043, y = 170.615, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_126081_0', prompt = '', x = 43.325, y = 170.706, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_147820_0', prompt = '', x = 328.818, y = 169.134, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_147820_1', prompt = '', x = 302.1, y = 168.703, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_147820_2', prompt = '', x = 274.904, y = 168.793, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_147820_3', prompt = '', x = 248.186, y = 168.883, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_180671_0', prompt = '', x = 94.521, y = 37.461, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_180671_1', prompt = '', x = 67.804, y = 37.552, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_185807_0', prompt = '', x = 301.775, y = 37.161, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'}), RectSlot(id = 'konva_1785114682783_paste_185807_1', prompt = '', x = 275.057, y = 37.251, width = 24.773, height = 25.461, fill = '#ffffff', stroke = '#111827', stroke_width = 1.2, interaction = {'type': 'input', 'role': 'answer', 'value_type': 'digit', 'max_length': 1, 'include_in_submission': True, 'order': 9, 'group_id': 'final_answer', 'auto_advance': True, 'keyboard': 'number'}, input_style = {'font_size_mode': 'auto', 'font_size_adjust': 0, 'min_font_size': 14, 'max_font_size': 52, 'font_weight': 700, 'horizontal_align': 'center', 'vertical_align': 'middle', 'padding': 6, 'text_color': '#222222'})),
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC = {
    "problem_id": PROBLEM_ID,
    "problem_type": "multi_answer_vertical_addition",
    "metadata": {
        "grade": 3,
        "semester": 1,
        "subject": "?섑븰",
        "topic": "諛쏆븘?щ┝???덈뒗 ???먮━ ?섏쓽 ?㏃뀍",
        "language": "ko-KR",
    },
    "domain": {
        "objects": [
            {
                "id": "addition.problem_1",
                "type": "vertical_addition",
                "label": "problem 1",
                "first_addend": 529,
                "second_addend": 775,
                "sum": 1304,
            },
            {
                "id": "addition.problem_2",
                "type": "vertical_addition",
                "label": "problem 2",
                "first_addend": 257,
                "second_addend": 769,
                "sum": 1026,
            },
        ],
        "relations": [
            {
                "id": "relation.problem_1_sum",
                "type": "sum_of",
                "subject": "addition.problem_1",
                "values": [529, 775],
            },
            {
                "id": "relation.problem_2_sum",
                "type": "sum_of",
                "subject": "addition.problem_2",
                "values": [257, 769],
            },
        ],
    },
    "answer": {
        "value": [1, 1, 1, 3, 0, 4, 1, 1, 1, 0, 2, 6],
        "unit": "",
        "items": [
            {"id": "answer.problem_1.carry_hundreds", "value": 1},
            {"id": "answer.problem_1.carry_tens", "value": 1},
            {"id": "answer.problem_1.thousands", "value": 1},
            {"id": "answer.problem_1.hundreds", "value": 3},
            {"id": "answer.problem_1.tens", "value": 0},
            {"id": "answer.problem_1.ones", "value": 4},
            {"id": "answer.problem_2.carry_hundreds", "value": 1},
            {"id": "answer.problem_2.carry_tens", "value": 1},
            {"id": "answer.problem_2.thousands", "value": 1},
            {"id": "answer.problem_2.hundreds", "value": 0},
            {"id": "answer.problem_2.tens", "value": 2},
            {"id": "answer.problem_2.ones", "value": 6},
        ],
    },
}

SEMANTIC_OVERRIDE = SEMANTIC


SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'P3_1_01_00040_02154',
 'problem_type': 'multi_answer_vertical_addition',
 'inputs': {'target_label': '???몃줈?덉쓽 諛쏆븘?щ┝???섏? 怨꾩궛 寃곌낵',
            'unit': '',
            'answer_type': 'digit_list',
            'quantities': {'problem_1': {'first_addend': 529, 'second_addend': 775},
                           'problem_2': {'first_addend': 257, 'second_addend': 769}},
            'conditions': ['?쇱쓽 ?먮━遺??李⑤??濡?怨꾩궛?⑸땲??',
                           '媛??먮━???⑹씠 10 ?댁긽?대㈃ 諛붾줈 ?쀬옄由щ줈 1??諛쏆븘?щ┝?⑸땲??',
                           '諛쏆븘?щ┝???섏? ?㏃뀍 寃곌낵??媛??먮━ ?レ옄瑜??ㅻえ ?덉뿉 ?곷땲??']},
 'given': [{'ref': 'addition.problem_1', 'value': {'first_addend': 529, 'second_addend': 775}},
           {'ref': 'addition.problem_2', 'value': {'first_addend': 257, 'second_addend': 769}}],
 'target': {'ref': 'answer.vertical_addition_blanks', 'type': 'digit_list'},
 'method': '媛??몃줈?덉뿉???쇱쓽 ?먮━遺???뷀븯怨? 諛쏆븘?щ┝???섎? 諛붾줈 ?쀬옄由?怨꾩궛???ы븿?쒕떎.',
 'plan': ['泥?踰덉㎏ ?몃줈??529+775瑜??쇱쓽 ?먮━遺??怨꾩궛?쒕떎.',
          '泥?踰덉㎏ ?몃줈?덉쓽 諛쏆븘?щ┝???섏? 寃곌낵瑜??대떎.',
          '??踰덉㎏ ?몃줈??257+769瑜??쇱쓽 ?먮━遺??怨꾩궛?쒕떎.',
          '??踰덉㎏ ?몃줈?덉쓽 諛쏆븘?щ┝???섏? 寃곌낵瑜??대떎.'],
 'steps': [{'id': 'step.problem_1.add_ones',
            'expr': '9 + 5',
            'value': 14,
            'explanation': '?쇱쓽 ?먮━?먯꽌 9? 5瑜??뷀븯硫?14?대?濡?4瑜??곌퀬 1??諛쏆븘?щ┝?⑸땲??'},
           {'id': 'step.problem_1.add_tens',
            'expr': '2 + 7 + 1',
            'value': 10,
            'explanation': '??쓽 ?먮━?먯꽌 2? 7??諛쏆븘?щ┝??1???뷀븯硫?10?대?濡?0???곌퀬 1??諛쏆븘?щ┝?⑸땲??'},
           {'id': 'step.problem_1.add_hundreds',
            'expr': '5 + 7 + 1',
            'value': 13,
            'explanation': '諛깆쓽 ?먮━?먯꽌 5? 7??諛쏆븘?щ┝??1???뷀븯硫?13?대?濡?13???욎뿉 ?곷땲??'},
           {'id': 'step.problem_1.compose_sum',
            'expr': '529 + 775',
            'value': 1304,
            'explanation': '泥?踰덉㎏ ?몃줈?덉쓽 寃곌낵??1304?낅땲??'},
           {'id': 'step.problem_2.add_ones',
            'expr': '7 + 9',
            'value': 16,
            'explanation': '?쇱쓽 ?먮━?먯꽌 7怨?9瑜??뷀븯硫?16?대?濡?6???곌퀬 1??諛쏆븘?щ┝?⑸땲??'},
           {'id': 'step.problem_2.add_tens',
            'expr': '5 + 6 + 1',
            'value': 12,
            'explanation': '??쓽 ?먮━?먯꽌 5? 6??諛쏆븘?щ┝??1???뷀븯硫?12?대?濡?2瑜??곌퀬 1??諛쏆븘?щ┝?⑸땲??'},
           {'id': 'step.problem_2.add_hundreds',
            'expr': '2 + 7 + 1',
            'value': 10,
            'explanation': '諛깆쓽 ?먮━?먯꽌 2? 7??諛쏆븘?щ┝??1???뷀븯硫?10?대?濡?10???욎뿉 ?곷땲??'},
           {'id': 'step.problem_2.compose_sum',
            'expr': '257 + 769',
            'value': 1026,
            'explanation': '??踰덉㎏ ?몃줈?덉쓽 寃곌낵??1026?낅땲??'}],
 'checks': [{'id': 'check.problem_1.total',
             'expr': '529 + 775',
             'expected': 1304,
             'actual': 1304,
             'pass': True},
            {'id': 'check.problem_1.inverse',
             'expr': '1304 - 775',
             'expected': 529,
             'actual': 529,
             'pass': True},
            {'id': 'check.problem_2.total',
             'expr': '257 + 769',
             'expected': 1026,
             'actual': 1026,
             'pass': True},
            {'id': 'check.problem_2.inverse',
             'expr': '1026 - 769',
             'expected': 257,
             'actual': 257,
             'pass': True}],
 'answer': {'value': [1, 1, 1, 3, 0, 4, 1, 1, 1, 0, 2, 6],
            'unit': '',
            'items': [{'id': 'answer.problem_1.carry_hundreds', 'value': 1},
                      {'id': 'answer.problem_1.carry_tens', 'value': 1},
                      {'id': 'answer.problem_1.thousands', 'value': 1},
                      {'id': 'answer.problem_1.hundreds', 'value': 3},
                      {'id': 'answer.problem_1.tens', 'value': 0},
                      {'id': 'answer.problem_1.ones', 'value': 4},
                      {'id': 'answer.problem_2.carry_hundreds', 'value': 1},
                      {'id': 'answer.problem_2.carry_tens', 'value': 1},
                      {'id': 'answer.problem_2.thousands', 'value': 1},
                      {'id': 'answer.problem_2.hundreds', 'value': 0},
                      {'id': 'answer.problem_2.tens', 'value': 2},
                      {'id': 'answer.problem_2.ones', 'value': 6}]},
 'understanding': {'summary': 'Find ???몃줈?덉쓽 諛쏆븘?щ┝???섏? 怨꾩궛 寃곌낵 using the given information.',
                   'facts': [{'ref': 'addition.problem_1',
                              'label': 'problem 1',
                              'value': {'first_addend': 529, 'second_addend': 775},
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'addition.problem_2',
                              'label': 'problem 2',
                              'value': {'first_addend': 257, 'second_addend': 769},
                              'unit': '',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.vertical_addition_blanks',
                                 'label': '???몃줈?덉쓽 諛쏆븘?щ┝???섏? 怨꾩궛 寃곌낵',
                                 'unit': '',
                                 'source': 'unknown'}],
                   'relation': {'type': '媛??몃줈?덉뿉???쇱쓽 ?먮━遺???뷀븯怨? 諛쏆븘?щ┝???섎? 諛붾줈 ?쀬옄由?怨꾩궛???ы븿?쒕떎.',
                                'statement': '泥?踰덉㎏ ?몃줈??529+775瑜??쇱쓽 ?먮━遺??怨꾩궛?쒕떎.',
                                'symbolic': '9 + 5',
                                'uses': ['addition.problem_1', 'addition.problem_2'],
                                'result': 'answer.vertical_addition_blanks'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'What should we find?',
                                             'choices': ['problem 1',
                                                         'problem 2',
                                                         '???몃줈?덉쓽 諛쏆븘?щ┝???섏? 怨꾩궛 寃곌낵'],
                                             'answer_index': 2}]}}

SEMANTIC_ANSWER = SOLVABLE["answer"]
