from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008785",
        title="학용품의 무게 비교",
        canvas=Canvas(width=952, height=374, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.table.outer",
                    "slot.table.r1c1.fill",
                    "slot.table.r1c2.fill",
                    "slot.table.r1c3.fill",
                    "slot.table.r1c4.fill",
                    "slot.table.r2c1.fill",
                    "slot.table.r2c2.fill",
                    "slot.table.r2c3.fill",
                    "slot.table.r2c4.fill",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.h1",
                    "slot.table.r1c1",
                    "slot.table.r1c2",
                    "slot.table.r1c3",
                    "slot.table.r1c4",
                    "slot.table.r2c1",
                    "slot.table.r2c2",
                    "slot.table.r2c3",
                    "slot.table.r2c4",
                ),
            ),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(),
            ),
            Region(id="region.extra", role="note", flow="absolute", slot_ids=("slot.choice",)),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="같은 무게의 쇠구슬과 저울을 사용하여 학용품의 무게를 알아본 것입니다.",
                style_role="question",
                x=27,
                y=46,
                font_size=28,
                fill="#111111",
                max_width=786.24,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="가장 무거운 학용품은 어느 것인지 선택해 보세요.",
                style_role="question",
                x=27,
                y=92,
                font_size=28,
                fill="#111111",
                max_width=544.32,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( 공책 , 크레파스 , 가위 )",
                style_role="note",
                x=294,
                y=337,
                font_size=28,
                fill="#111111",
                max_width=362.88,
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=140,
                y=135,
                width=625,
                height=140,
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.r1c1.fill",
                prompt="",
                x=140,
                y=135,
                width=155,
                height=60,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r1c2.fill",
                prompt="",
                x=295,
                y=135,
                width=160,
                height=60,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r1c3.fill",
                prompt="",
                x=455,
                y=135,
                width=155,
                height=60,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r1c4.fill",
                prompt="",
                x=610,
                y=135,
                width=155,
                height=60,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r2c1.fill",
                prompt="",
                x=140,
                y=195,
                width=155,
                height=80,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r2c2.fill",
                prompt="",
                x=295,
                y=195,
                width=160,
                height=80,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r2c3.fill",
                prompt="",
                x=455,
                y=195,
                width=155,
                height=80,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            RectSlot(
                id="slot.table.r2c4.fill",
                prompt="",
                x=610,
                y=195,
                width=155,
                height=80,
                fill="none",
                stroke="none",
                stroke_width=0,
            ),
            LineSlot(
                id="slot.table.v1",
                prompt="",
                x1=332,
                y1=135,
                x2=332,
                y2=275,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.v2",
                prompt="",
                x1=471,
                y1=135,
                x2=471,
                y2=275,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.v3",
                prompt="",
                x1=623,
                y1=135,
                x2=623,
                y2=275,
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.h1",
                prompt="",
                x1=140,
                y1=195,
                x2=765,
                y2=195,
                stroke="#111827",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table.r1c1",
                prompt="",
                text="학용품",
                x=234,
                y=180,
                font_size=28,
                max_width=135,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r1c2",
                prompt="",
                text="공책",
                x=401,
                y=180,
                font_size=28,
                max_width=140,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r1c3",
                prompt="",
                text="크레파스",
                x=545,
                y=180,
                font_size=28,
                max_width=135,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r1c4",
                prompt="",
                text="가위",
                x=693,
                y=180,
                font_size=28,
                max_width=135,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c1",
                prompt="",
                text="쇠구슬의 수(개)",
                x=235.582,
                y=248.258,
                font_size=28,
                max_width=135,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c2",
                prompt="",
                text="11",
                x=401,
                y=250,
                font_size=28,
                max_width=140,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c3",
                prompt="",
                text="17",
                x=545,
                y=250,
                font_size=28,
                max_width=135,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c4",
                prompt="",
                text="13",
                x=693,
                y=250,
                font_size=28,
                max_width=135,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008785",
    "problem_type": "비교",
    "metadata": {
        "language": "ko",
        "question": "같은 무게의 쇠구슬과 저울을 사용하여 학용품의 무게를 알아본 것입니다. 가장 무거운 학용품은 어느 것인지 선택해 보세요.",
        "instruction": "가장 무거운 학용품을 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.notebook", "type": "school_supply", "name": "공책"},
            {"id": "obj.crayons", "type": "school_supply", "name": "크레파스"},
            {"id": "obj.scissors", "type": "school_supply", "name": "가위"},
            {"id": "obj.beads.notebook", "type": "bead_count", "value": 11},
            {"id": "obj.beads.crayons", "type": "bead_count", "value": 17},
            {"id": "obj.beads.scissors", "type": "bead_count", "value": 13},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.beads.notebook", "obj.beads.crayons", "obj.beads.scissors"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.weight_proxy", "rel.compare.1", "rel.compare.2"],
            },
            "plan": {"method": "비교", "description": "쇠구슬 수를 비교하여 가장 큰 값을 찾는다."},
            "execute": {"expected_operations": ["compare_counts", "identify_maximum"]},
            "review": {"check_methods": ["largest_count_matches_heaviest_supply"]},
        },
    },
    "answer": {
        "target": {"type": "school_supply_name", "description": "가장 무거운 학용품"},
        "value": "크레파스",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008785",
    "problem_type": "비교",
    "inputs": {
        "total_ticks": 3,
        "target_label": "가장 무거운 학용품",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.beads.notebook", "value": 11},
        {"ref": "obj.beads.crayons", "value": 17},
        {"ref": "obj.beads.scissors", "value": 13},
    ],
    "target": {"ref": "answer.target", "type": "school_supply_name"},
    "method": "비교",
    "plan": ["쇠구슬의 수를 비교합니다.", "가장 큰 수에 대응하는 학용품을 찾습니다."],
    "steps": [
        {"id": "step.1", "expr": "17 > 13", "value": True},
        {"id": "step.2", "expr": "13 > 11", "value": True},
        {"id": "step.3", "expr": "가장 큰 쇠구슬 수는 17", "value": 17},
        {"id": "step.4", "expr": "17에 대응하는 학용품은 크레파스", "value": "크레파스"},
    ],
    "checks": [
        {"id": "check.1", "expr": "17 > 13 > 11", "expected": True, "actual": True, "pass": True},
        {
            "id": "check.2",
            "expr": "최댓값 17의 대응 항목",
            "expected": "크레파스",
            "actual": "크레파스",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "school_supply_name", "description": "가장 무거운 학용품"},
        "value": "크레파스",
        "unit": "",
    },
}
