from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008740",
        title="두 분수의 크기 비교",
        canvas=Canvas(width=960, height=700, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q2",
                    "slot.q3",
                ),
            ),
            Region(
                id="region.diagram.top",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.top.box",
                    "slot.top.text",
                    "slot.top.line",
                    "slot.mid.left.box",
                    "slot.mid.right.box",
                    "slot.mid.connector",
                    "slot.leaf.1",
                    "slot.leaf.2",
                    "slot.leaf.3",
                    "slot.leaf.4",
                    "slot.math.fraction.num",
                    "slot.math.fraction.bar",
                    "slot.math.fraction.den",
                    "slot.math.fraction_1.num",
                    "slot.math.fraction_1.bar",
                    "slot.math.fraction_1.den",
                    "slot.math.mixed_fraction.whole",
                    "slot.math.mixed_fraction.num",
                    "slot.math.mixed_fraction.bar",
                    "slot.math.mixed_fraction.den",
                    "slot.math.mixed_fraction_1.whole",
                    "slot.math.mixed_fraction_1.num",
                    "slot.math.mixed_fraction_1.bar",
                    "slot.math.mixed_fraction_1.den",
                    "slot.top.line.copy10",
                    "slot.top.line.copy11",
                    "slot.mid.connector.copy12",
                    "slot.mid.connector.copy13",
                    "slot.top.line.copy14",
                    "slot.top.line.copy15",
                    "slot.top.line.copy14.copy16",
                    "slot.top.line.copy14.copy17",
                    "slot.top.line.copy14.copy18",
                    "slot.top.line.copy14.copy19",
                ),
            ),
            Region(id="region.note", role="annotation", flow="absolute", slot_ids=()),
            Region(id="region.diagram.bottom", role="diagram", flow="absolute", slot_ids=()),
            Region(id="region.solution.text", role="explanation", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.math.fraction.num",
                prompt="",
                text="23",
                x=200,
                y=475,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction.bar",
                prompt="",
                x1=180,
                y1=492,
                x2=220,
                y2=492,
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction.den",
                prompt="",
                text="6",
                x=200,
                y=520,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.fraction_1.num",
                prompt="",
                text="21",
                x=337,
                y=475,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction_1.bar",
                prompt="",
                x1=317,
                y1=492,
                x2=357,
                y2=492,
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction_1.den",
                prompt="",
                text="6",
                x=337,
                y=520,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction.whole",
                prompt="",
                text="3",
                x=510,
                y=500,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction.num",
                prompt="",
                text="2",
                x=542,
                y=475,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction.bar",
                prompt="",
                x1=522,
                y1=492,
                x2=562,
                y2=492,
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction.den",
                prompt="",
                text="6",
                x=542,
                y=520,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.whole",
                prompt="",
                text="3",
                x=645,
                y=500,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.num",
                prompt="",
                text="4",
                x=677,
                y=475,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.mixed_fraction_1.bar",
                prompt="",
                x1=657,
                y1=492,
                x2=697,
                y2=492,
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.mixed_fraction_1.den",
                prompt="",
                text="6",
                x=677,
                y=520,
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="두 분수의 크기를 비교하여 더 큰 분수를 빈칸에 써 넣으려고 합니다. ",
                style_role="question",
                x=25,
                y=80,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="①에 들어갈 분수로 알맞은 것을 가장 아래 칸의 분수들 중에 선택해 보세요.",
                style_role="question",
                x=20,
                y=130,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.top.box",
                prompt="",
                x=380,
                y=163,
                width=100,
                height=95,
                fill="#FFFFFF",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.top.text",
                prompt="",
                text="①",
                style_role="label",
                x=415,
                y=220,
                font_size=30,
                fill="#111111",
            ),
            LineSlot(
                id="slot.top.line",
                prompt="",
                x1=429,
                y1=258,
                x2=429,
                y2=278,
                stroke="#666666",
                stroke_width=1.6,
            ),
            RectSlot(
                id="slot.mid.left.box",
                prompt="",
                x=218,
                y=301,
                width=100,
                height=95,
                fill="#FFFFFF",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.mid.right.box",
                prompt="",
                x=540,
                y=298,
                width=100,
                height=95,
                fill="#FFFFFF",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.mid.connector",
                prompt="",
                x1=265,
                y1=278,
                x2=590,
                y2=278,
                stroke="#666666",
                stroke_width=1.6,
            ),
            RectSlot(
                id="slot.leaf.1",
                prompt="",
                x=150,
                y=440,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.leaf.2",
                prompt="",
                x=287,
                y=441,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.leaf.3",
                prompt="",
                x=475,
                y=439,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            RectSlot(
                id="slot.leaf.4",
                prompt="",
                x=610,
                y=439,
                width=100,
                height=95,
                fill="#EBDFF3",
                stroke="#D8C2E6",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.top.line.copy10",
                prompt="",
                x1=590,
                y1=277,
                x2=590,
                y2=297,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy11",
                prompt="",
                x1=267,
                y1=280,
                x2=267,
                y2=300,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.mid.connector.copy12",
                prompt="",
                x1=200,
                y1=421,
                x2=335,
                y2=421,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.mid.connector.copy13",
                prompt="",
                x1=521,
                y1=413,
                x2=661,
                y2=413,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14",
                prompt="",
                x1=265,
                y1=399,
                x2=265,
                y2=419,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy15",
                prompt="",
                x1=591,
                y1=392,
                x2=591,
                y2=412,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy16",
                prompt="",
                x1=200,
                y1=421,
                x2=200,
                y2=441,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy17",
                prompt="",
                x1=334,
                y1=421,
                x2=334,
                y2=441,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy18",
                prompt="",
                x1=521,
                y1=413,
                x2=521,
                y2=438,
                stroke="#666666",
                stroke_width=1.6,
            ),
            LineSlot(
                id="slot.top.line.copy14.copy19",
                prompt="",
                x1=661,
                y1=413,
                x2=661,
                y2=438,
                stroke="#666666",
                stroke_width=1.6,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008740",
    "problem_type": "fraction_comparison",
    "metadata": {
        "language": "ko",
        "question": "두 분수의 크기를 비교하여 더 큰 분수를 빈칸에 써 넣는 문제",
        "instruction": "①에 들어갈 분수를 가장 아래 칸의 분수들 중에서 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.choice_1", "type": "fraction", "value": "23/6"},
            {"id": "obj.choice_2", "type": "fraction", "value": "21/6"},
            {"id": "obj.choice_3", "type": "mixed_number", "value": "3 2/6"},
            {"id": "obj.choice_4", "type": "mixed_number", "value": "3 4/6"},
            {"id": "obj.blank", "type": "blank", "label": "①"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.choice_1", "obj.choice_2", "obj.choice_3", "obj.choice_4"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_1", "rel.compare_2"],
            },
            "plan": {
                "method": "compare_fractions",
                "description": "후보 분수들의 크기를 비교하여 가장 큰 분수를 선택한다.",
            },
            "execute": {
                "expected_operations": ["compare_fraction_pairs", "identify_largest_candidate"]
            },
            "review": {"check_methods": ["comparison_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "blank_fill", "description": "①에 들어갈 분수"},
        "value": "23/6",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008740",
    "problem_type": "fraction_comparison",
    "inputs": {
        "total_ticks": 4,
        "target_label": "①",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.choice_1", "value": "23/6"},
        {"ref": "obj.choice_2", "value": "21/6"},
        {"ref": "obj.choice_3", "value": "3 2/6"},
        {"ref": "obj.choice_4", "value": "3 4/6"},
    ],
    "target": {"ref": "answer.target", "type": "blank_fill"},
    "method": "compare_fractions",
    "plan": ["주어진 후보 분수들의 크기를 비교한다.", "가장 큰 분수를 선택한다."],
    "steps": [
        {"id": "step.1", "expr": "23/6 > 21/6", "value": True},
        {"id": "step.2", "expr": "3 2/6 < 3 4/6", "value": True},
        {"id": "step.3", "expr": "23/6 = 3 5/6", "value": "3 5/6"},
        {"id": "step.4", "expr": "23/6 > 3 4/6", "value": True},
        {"id": "step.5", "expr": "가장 큰 분수 선택", "value": "23/6"},
    ],
    "checks": [
        {"id": "check.1", "expr": "23/6 > 21/6", "expected": True, "actual": True, "pass": True},
        {"id": "check.2", "expr": "3 2/6 < 3 4/6", "expected": True, "actual": True, "pass": True},
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "blank_fill", "description": "①에 들어갈 분수"},
        "value": "23/6",
        "unit": "",
    },
}
