from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, RectSlot, Region, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008775",
        title="누가 물을 더 많이 마셨나요",
        canvas=Canvas(width=940.0, height=469.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.table.outer",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.r1c1",
                    "slot.table.r1c2",
                    "slot.table.r1c3",
                    "slot.table.r2c1",
                    "slot.table.r2c2",
                    "slot.table.r2c3",
                    "slot.table.r3c1",
                    "slot.table.r3c2",
                    "slot.table.r3c3",
                ),
            ),
            Region(
                id="region.table",
                role="diagram",
                flow="absolute",
                slot_ids=(),
            ),
            Region(id="region.foot", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="수경이와 현준이가 물을 마셨습니다. 마시기 전과 마신 후의 물의 양은",
                style_role="question",
                x=18,
                y=40,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="다음과 같습니다. 누가 물을 더 많이 마셨나요?",
                style_role="question",
                x=18,
                y=85,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.c1t",
                prompt="",
                text="",
                style_role="table",
                x=320.0,
                y=116.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.tbl.note",
                prompt="",
                text="( 수경 , 현준 )",
                style_role="note",
                x=349,
                y=389,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=(50) + (45.0),
                y=(135) + (5.0),
                width=630,
                height=205,
                fill="#ffffff",
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.v1",
                prompt="",
                x1=(280) + (45.0),
                y1=(135) + (5.0),
                x2=(280) + (45.0),
                y2=(340) + (5.0),
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.v2",
                prompt="",
                x1=(470) + (45.0),
                y1=(135) + (5.0),
                x2=(470) + (45.0),
                y2=(340) + (5.0),
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.h1",
                prompt="",
                x1=(50) + (45.0),
                y1=(200) + (5.0),
                x2=(680) + (45.0),
                y2=(200) + (5.0),
                stroke="#111827",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.table.h2",
                prompt="",
                x1=(50) + (45.0),
                y1=(270) + (5.0),
                x2=(680) + (45.0),
                y2=(270) + (5.0),
                stroke="#111827",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table.r1c1",
                prompt="",
                text="",
                x=(165) + (45.0),
                y=(180) + (5.0),
                font_size=28,
                max_width=210,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r1c2",
                prompt="",
                text="수경",
                x=(375) + (45.0),
                y=(180) + (5.0),
                font_size=28,
                max_width=170,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r1c3",
                prompt="",
                text="현준",
                x=(575) + (45.0),
                y=(180) + (5.0),
                font_size=28,
                max_width=190,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c1",
                prompt="",
                text="마시기 전",
                x=(165) + (45.0),
                y=(250) + (5.0),
                font_size=28,
                max_width=210,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c2",
                prompt="",
                text="2L 500mL",
                x=(375) + (45.0),
                y=(250) + (5.0),
                font_size=28,
                max_width=170,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r2c3",
                prompt="",
                text="2L",
                x=(575) + (45.0),
                y=(250) + (5.0),
                font_size=28,
                max_width=190,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r3c1",
                prompt="",
                text="마신 후",
                x=(165) + (45.0),
                y=(320) + (5.0),
                font_size=28,
                max_width=210,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r3c2",
                prompt="",
                text="2L 100mL",
                x=(375) + (45.0),
                y=(320) + (5.0),
                font_size=28,
                max_width=170,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
            TextSlot(
                id="slot.table.r3c3",
                prompt="",
                text="1L 400mL",
                x=(575) + (45.0),
                y=(320) + (5.0),
                font_size=28,
                max_width=190,
                anchor="middle",
                style_role="table",
                fill="#111827",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008775",
    "problem_type": "comparison",
    "metadata": {
        "language": "ko",
        "question": "수경이와 현준이가 물을 마셨습니다. 마시기 전과 마신 후의 물의 양은 다음과 같습니다. 누가 물을 더 많이 마셨나요?",
        "instruction": "누가 물을 더 많이 마셨는지 구하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.sugyeong", "type": "person", "name": "수경"},
            {"id": "obj.hyeonjun", "type": "person", "name": "현준"},
            {
                "id": "obj.sugyeong_before",
                "type": "amount",
                "person": "obj.sugyeong",
                "state": "before",
                "value": "2 L 500 mL",
            },
            {
                "id": "obj.sugyeong_after",
                "type": "amount",
                "person": "obj.sugyeong",
                "state": "after",
                "value": "2 L 100 mL",
            },
            {
                "id": "obj.hyeonjun_before",
                "type": "amount",
                "person": "obj.hyeonjun",
                "state": "before",
                "value": "2 L",
            },
            {
                "id": "obj.hyeonjun_after",
                "type": "amount",
                "person": "obj.hyeonjun",
                "state": "after",
                "value": "1 L 400 mL",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.sugyeong_before",
                    "obj.sugyeong_after",
                    "obj.hyeonjun_before",
                    "obj.hyeonjun_after",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_drunk_amount"],
            },
            "plan": {
                "method": "compare_drunk_amount_by_difference",
                "description": "각 사람의 마신 물의 양을 비교하여 더 많이 마신 사람을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "difference_between_before_and_after",
                    "compare_two_amounts",
                ]
            },
            "review": {"check_methods": ["compare_result_consistency"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person", "description": "물을 더 많이 마신 사람"},
        "value": "현준",
        "unit": "",
    },
}

SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'S3_초등_3_008775',
 'problem_type': 'comparison',
 'inputs': {'total_ticks': 2,
            'target_label': '물을 더 많이 마신 사람',
            'target_ticks': 2,
            'target_count': 1,
            'unit': ''},
 'given': [{'ref': 'obj.sugyeong_before', 'value': '2 L 500 mL'},
           {'ref': 'obj.sugyeong_after', 'value': '2 L 100 mL'},
           {'ref': 'obj.hyeonjun_before', 'value': '2 L'},
           {'ref': 'obj.hyeonjun_after', 'value': '1 L 400 mL'}],
 'target': {'ref': 'answer.target', 'type': 'person'},
 'method': 'difference_between_before_and_after',
 'plan': ['각 사람의 마신 물의 양을 구한다.', '두 양을 비교한다.', '더 큰 쪽의 사람을 답한다.'],
 'steps': [{'id': 'step.1', 'expr': '2 L 500 mL - 2 L 100 mL', 'value': '400 mL'},
           {'id': 'step.2', 'expr': '2 L - 1 L 400 mL', 'value': '600 mL'},
           {'id': 'step.3', 'expr': '400 mL < 600 mL', 'value': '참'},
           {'id': 'step.4', 'expr': '더 많이 마신 사람', 'value': '현준'}],
 'checks': [{'id': 'check.1',
             'expr': '마신 양 비교',
             'expected': '600 mL가 400 mL보다 큼',
             'actual': '600 mL > 400 mL',
             'pass': True}],
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'target': {'type': 'person', 'description': '물을 더 많이 마신 사람'},
            'value': '현준',
            'unit': ''},
 'understanding': {'summary': 'Find 물을 더 많이 마신 사람 using the given information.',
                   'facts': [{'ref': 'obj.sugyeong_before',
                              'label': 'sugyeong before',
                              'value': '2 L 500 mL',
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'obj.sugyeong_after',
                              'label': 'sugyeong after',
                              'value': '2 L 100 mL',
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'obj.hyeonjun_before',
                              'label': 'hyeonjun before',
                              'value': '2 L',
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'obj.hyeonjun_after',
                              'label': 'hyeonjun after',
                              'value': '1 L 400 mL',
                              'unit': '',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.target',
                                 'label': '물을 더 많이 마신 사람',
                                 'unit': '',
                                 'source': 'unknown'}],
                   'relation': {'type': 'difference_between_before_and_after',
                                'statement': '각 사람의 마신 물의 양을 구한다.',
                                'symbolic': '2 L 500 mL - 2 L 100 mL',
                                'uses': ['obj.sugyeong_before',
                                         'obj.sugyeong_after',
                                         'obj.hyeonjun_before',
                                         'obj.hyeonjun_after'],
                                'result': 'answer.target'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'What should we find?',
                                             'choices': ['sugyeong before',
                                                         'sugyeong after',
                                                         '물을 더 많이 마신 사람'],
                                             'answer_index': 2}]}}
