from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, RectSlot, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008753",
        title="수조에 물을 가득 채우려면",
        canvas=Canvas(width=960, height=430, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.table.outer",
                    "slot.table.h1",
                    "slot.table.h2",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.v4",
                    "slot.table.r1c1",
                    "slot.table.r1c2",
                    "slot.table.r1c3",
                    "slot.table.r1c4",
                    "slot.table.r2c1",
                    "slot.table.r2c2",
                    "slot.table.r2c3",
                    "slot.table.r2c4",
                    "slot.choice",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="수조에 물을 가득 채우려면 다음과 같이 각각 그릇이 필요합니다.",
                style_role="question",
                x=46,
                y=50,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="㉠ 그릇, ㉡ 그릇, ㉢ 그릇 중 들이가 가장 적은 것을 선택해보세요.",
                style_role="question",
                x=44,
                y=93,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.table.outer",
                prompt="",
                x=110,
                y=163,
                width=580,
                height=118,
                fill="#FFFFFF",
                stroke="#A7C36A",
                stroke_width=1.2,
            ),
            RectSlot(
                id="slot.table.h1",
                prompt="",
                x=110,
                y=163,
                width=580,
                height=44,
                fill="#EAF2D6",
                stroke="#A7C36A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.h2",
                prompt="",
                x=110,
                y=207,
                width=580,
                height=74,
                fill="#FFFFFF",
                stroke="#A7C36A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.v1",
                prompt="",
                x=255,
                y=163,
                width=0,
                height=118,
                fill="#000000",
                stroke="#A7C36A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.v2",
                prompt="",
                x=400,
                y=163,
                width=0,
                height=118,
                fill="#000000",
                stroke="#A7C36A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.v3",
                prompt="",
                x=545,
                y=163,
                width=0,
                height=118,
                fill="#000000",
                stroke="#A7C36A",
                stroke_width=1,
            ),
            RectSlot(
                id="slot.table.v4",
                prompt="",
                x=690,
                y=163,
                width=0,
                height=118,
                fill="#000000",
                stroke="#A7C36A",
                stroke_width=1,
            ),
            TextSlot(
                id="slot.table.r1c1",
                prompt="",
                text="",
                style_role="question",
                x=((192) + (60.0)) + (-70.0),
                y=((170) + (30.0)) + (-10.0),
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r1c2",
                prompt="",
                text="㉠ 그릇",
                style_role="question",
                x=287.153,
                y=199.89,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r1c3",
                prompt="",
                text="㉡ 그릇",
                style_role="question",
                x=435.957,
                y=199.129,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r1c4",
                prompt="",
                text="㉢ 그릇",
                style_role="question",
                x=580.196,
                y=197.608,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c1",
                prompt="",
                text="그릇의 수",
                style_role="question",
                x=132.349,
                y=257.933,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c2",
                prompt="",
                text="5개",
                style_role="question",
                x=310.718,
                y=255.086,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c3",
                prompt="",
                text="4개",
                style_role="question",
                x=456.478,
                y=252.608,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.table.r2c4",
                prompt="",
                text="7개",
                style_role="question",
                x=603.761,
                y=251.847,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( ㉠ 그릇 , ㉡ 그릇 , ㉢ 그릇 )",
                style_role="question",
                x=213,
                y=373,
                font_size=28,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("초등3", "비교", "표읽기"),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008753",
    "problem_type": "comparison_selection",
    "metadata": {
        "language": "ko",
        "question": "표의 값을 비교하여 들이가 가장 적은 그릇을 고르는 문제",
        "instruction": "가, 나, 다 중 들이가 가장 적은 것을 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.a", "type": "container", "label": "㉠ 그릇"},
            {"id": "obj.b", "type": "container", "label": "㉡ 그릇"},
            {"id": "obj.c", "type": "container", "label": "㉢ 그릇"},
            {"id": "obj.count_a", "type": "count", "value": 5, "unit": "개"},
            {"id": "obj.count_b", "type": "count", "value": 4, "unit": "개"},
            {"id": "obj.count_c", "type": "count", "value": 7, "unit": "개"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.count_a", "obj.count_b", "obj.count_c"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_counts", "rel.minimum_capacity"],
            },
            "plan": {
                "method": "value_comparison",
                "description": "그릇의 수를 비교해 가장 큰 값에 대응하는 그릇을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_counts",
                    "find_maximum",
                    "select_corresponding_container",
                ]
            },
            "review": {"check_methods": ["ordering_check", "consistency_with_explanation"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "least_capacity_container",
            "description": "들 이가 가장 적은 그릇",
        },
        "value": 3,
        "unit": "",
    },
}

SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'S3_초등_3_008753',
 'problem_type': 'comparison_selection',
 'inputs': {'total_ticks': 3,
            'target_label': '들이가 가장 적은 그릇',
            'target_ticks': 1,
            'target_count': 1,
            'unit': '개'},
 'given': [{'ref': 'obj.count_a', 'value': 5},
           {'ref': 'obj.count_b', 'value': 4},
           {'ref': 'obj.count_c', 'value': 7}],
 'target': {'ref': 'answer.target', 'type': 'least_capacity_container'},
 'method': 'value_comparison',
 'plan': ['세 그릇에 적힌 수를 비교한다.', '가장 큰 수에 해당하는 그릇을 고른다.'],
 'steps': [{'id': 'step.1', 'expr': '7 > 5 > 4', 'value': 7},
           {'id': 'step.2', 'expr': '가장 큰 수 7에 해당하는 그릇 선택', 'value': '㉢ 그릇'}],
 'checks': [{'id': 'check.1', 'expr': '7 > 5 > 4', 'expected': True, 'actual': True, 'pass': True},
            {'id': 'check.2',
             'expr': '선택한 그릇이 가장 큰 수에 대응하는가',
             'expected': '㉢ 그릇',
             'actual': '㉢ 그릇',
             'pass': True}],
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'target': {'type': 'least_capacity_container', 'description': '들 이가 가장 적은 그릇'},
            'value': 3,
            'unit': ''},
 'understanding': {'summary': 'Find 들이가 가장 적은 그릇 using the given information.',
                   'facts': [{'ref': 'obj.count_a',
                              'label': 'count a',
                              'value': 5,
                              'unit': '개',
                              'source': 'explicit'},
                             {'ref': 'obj.count_b',
                              'label': 'count b',
                              'value': 4,
                              'unit': '개',
                              'source': 'explicit'},
                             {'ref': 'obj.count_c',
                              'label': 'count c',
                              'value': 7,
                              'unit': '개',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.target',
                                 'label': '들이가 가장 적은 그릇',
                                 'unit': '개',
                                 'source': 'unknown'}],
                   'relation': {'type': 'value_comparison',
                                'statement': '세 그릇에 적힌 수를 비교한다.',
                                'symbolic': '7 > 5 > 4',
                                'uses': ['obj.count_a', 'obj.count_b', 'obj.count_c'],
                                'result': 'answer.target'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'What should we find?',
                                             'choices': ['count a', 'count b', '들이가 가장 적은 그릇'],
                                             'answer_index': 2}]}}
