from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    LineSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2405.answer",
        title="평행선과 각도",
        canvas=Canvas(width=820, height=1180, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                    "slot.q5",
                    "slot.q6",
                    "slot.q7",
                    "slot.q8",
                    "slot.q9",
                    "slot.q10",
                    "slot.q11",
                    "slot.q12",
                    "slot.q13",
                    "slot.q14",
                    "slot.q15",
                    "slot.q16",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.grid.l1",
                    "slot.grid.l2",
                    "slot.grid.l3",
                    "slot.grid.l4",
                    "slot.grid.l5",
                    "slot.grid.l6",
                    "slot.line.top",
                    "slot.line.bottom",
                    "slot.line.diag1",
                    "slot.line.diag2",
                    "slot.pt.b",
                    "slot.pt.a",
                    "slot.pt.c",
                    "slot.lb.a",
                    "slot.lb.b",
                    "slot.lb.c",
                    "slot.lb.l",
                    "slot.lb.m",
                    "slot.ang1",
                    "slot.ang2",
                ),
            ),
            Region(
                id="region.choices",
                role="answer_choices",
                flow="absolute",
                slot_ids=("slot.choice", "slot.answer_note"),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="In the figure below, ∠ABC is cut by the parallel lines ℓ and m.",
                style_role="question",
                x=36.0,
                y=58.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="Find the measure of ∠ABC and express your answer in degrees.",
                style_role="question",
                x=36.0,
                y=98.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=138.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=178.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q5",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=218.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q6",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=258.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q7",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=298.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q8",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=338.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q9",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=378.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q10",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=418.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q11",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=458.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q12",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=498.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q13",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=538.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q14",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=578.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q15",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=618.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q16",
                prompt="",
                text="",
                style_role="question",
                x=36.0,
                y=658.0,
                font_size=28,
            ),
            LineSlot(
                id="slot.grid.l1",
                prompt="",
                x1=0.0,
                y1=0.0,
                x2=0.0,
                y2=0.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.l2",
                prompt="",
                x1=0.0,
                y1=0.0,
                x2=0.0,
                y2=0.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.l3",
                prompt="",
                x1=0.0,
                y1=0.0,
                x2=0.0,
                y2=0.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.l4",
                prompt="",
                x1=0.0,
                y1=0.0,
                x2=0.0,
                y2=0.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.l5",
                prompt="",
                x1=0.0,
                y1=0.0,
                x2=0.0,
                y2=0.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.l6",
                prompt="",
                x1=0.0,
                y1=0.0,
                x2=0.0,
                y2=0.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.line.top",
                prompt="",
                x1=120.0,
                y1=350.0,
                x2=640.0,
                y2=350.0,
                stroke="#222222",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.line.bottom",
                prompt="",
                x1=120.0,
                y1=520.0,
                x2=640.0,
                y2=520.0,
                stroke="#222222",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.line.diag1",
                prompt="",
                x1=410.0,
                y1=410.0,
                x2=625.0,
                y2=260.0,
                stroke="#222222",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.line.diag2",
                prompt="",
                x1=410.0,
                y1=410.0,
                x2=625.0,
                y2=600.0,
                stroke="#222222",
                stroke_width=2.0,
            ),
            CircleSlot(
                id="slot.pt.b", prompt="", cx=410.0, cy=410.0, r=4.0, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.a", prompt="", cx=610.0, cy=280.0, r=4.0, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.c", prompt="", cx=620.0, cy=596.0, r=4.0, fill="#222222"
            ),
            TextSlot(
                id="slot.lb.a",
                prompt="",
                text="A",
                style_role="label",
                x=624.0,
                y=268.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.b",
                prompt="",
                text="B",
                style_role="label",
                x=392.0,
                y=422.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.c",
                prompt="",
                text="C",
                style_role="label",
                x=632.0,
                y=606.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.l",
                prompt="",
                text="ℓ",
                style_role="label",
                x=647.0,
                y=342.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.lb.m",
                prompt="",
                text="m",
                style_role="label",
                x=647.0,
                y=512.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.ang1",
                prompt="",
                text="38°",
                style_role="label",
                x=520.0,
                y=316.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.ang2",
                prompt="",
                text="33°",
                style_role="label",
                x=520.0,
                y=564.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="1. 17    2. 38    3. 54    4.\n71",
                style_role="answer_choice",
                x=390.0,
                y=860.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.answer_note",
                prompt="",
                text="정답: D (71)",
                style_role="note",
                x=540.0,
                y=1038.0,
                font_size=28,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("geometry", "parallel_lines", "angles", "multiple_choice"),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "2405.answer",
    "problem_type": "geometry_parallel_lines_angle",
    "metadata": {
        "language": "en",
        "question": "∠ABC is formed by two rays crossing two parallel lines ℓ and m.",
        "instruction": "Find the measure of ∠ABC in degrees.",
    },
    "domain": {
        "objects": [
            {"id": "obj.line.l", "type": "line", "name": "ℓ"},
            {"id": "obj.line.m", "type": "line", "name": "m"},
            {"id": "obj.point.b", "type": "point", "name": "B"},
            {"id": "obj.angle.abc", "type": "angle", "name": "∠ABC"},
            {
                "id": "obj.angle.38",
                "type": "angle_measure",
                "value": 38,
                "unit": "degree",
            },
            {
                "id": "obj.angle.33",
                "type": "angle_measure",
                "value": 33,
                "unit": "degree",
            },
        ],
        "relations": [
            {
                "id": "rel.parallel",
                "type": "parallel",
                "from_id": "obj.line.l",
                "to_id": "obj.line.m",
            },
            {
                "id": "rel.transversal_1",
                "type": "intersects",
                "from_id": "obj.point.b",
                "to_id": "obj.line.l",
            },
            {
                "id": "rel.transversal_2",
                "type": "intersects",
                "from_id": "obj.point.b",
                "to_id": "obj.line.m",
            },
        ],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.line.l",
                    "obj.line.m",
                    "obj.angle.38",
                    "obj.angle.33",
                ],
                "target_ref": "answer.target",
                "condition_refs": [
                    "rel.parallel",
                    "rel.transversal_1",
                    "rel.transversal_2",
                ],
            },
            "plan": {
                "method": "parallel_line_angle_relation",
                "description": "Use the angle relationships created when transversals cross parallel lines.",
            },
            "execute": {
                "expected_operations": [
                    "identify_corresponding_or_alternate_angles",
                    "relate_visible_angle_marks_to_target_angle",
                ]
            },
            "review": {
                "check_methods": [
                    "parallel_line_relation_consistency",
                    "degree_unit_check",
                ]
            },
        },
    },
    "answer": {
        "target": {"type": "angle_measure", "description": "measure of ∠ABC"},
        "value": None,
        "unit": "degree",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "2405.answer",
    "problem_type": "geometry_parallel_lines_angle",
    "inputs": {
        "total_ticks": 0,
        "target_label": "∠ABC",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "degree",
    },
    "given": [
        {"ref": "obj.line.l", "value": {"name": "ℓ"}},
        {"ref": "obj.line.m", "value": {"name": "m"}},
        {"ref": "obj.angle.38", "value": {"measure": 38, "unit": "degree"}},
        {"ref": "obj.angle.33", "value": {"measure": 33, "unit": "degree"}},
    ],
    "target": {"ref": "answer.target", "type": "angle_measure"},
    "method": "parallel_line_angle_relation",
    "plan": [
        "평행선과 횡단선이 만드는 각의 관계를 확인한다.",
        "그림에 표시된 각도 표기를 기준으로 ∠ABC를 찾는다.",
        "필요하면 대응각, 엇각, 동위각 관계를 점검한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "operation": "identify_visible_measures",
            "expr": "38° and 33° are shown in the diagram",
            "value": {"measures": [38, 33], "unit": "degree"},
        },
        {
            "id": "step.2",
            "operation": "note_relationship",
            "expr": "parallel-line angle relations apply",
            "value": {"relation": "parallel_lines_with_transversals"},
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "type": "degree_unit_check",
            "expr": "unit is degree",
            "expected": "degree",
            "actual": "degree",
            "pass": True,
        },
        {
            "id": "check.2",
            "type": "consistency_check",
            "expr": "only visible measures are recorded; no inferred answer is asserted",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {"value": 0, "unit": "degree", "derived_from": "step.2"},
}
