from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, LineSlot, PathSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_riUadxZCRr",
        title="종이테이프 직사각형",
        canvas=Canvas(width=904, height=552, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                    "slot.diagram.base1",
                    "slot.diagram.base2",
                    "slot.diagram.base3",
                    "slot.diagram.overlap1",
                    "slot.diagram.overlap2",
                    "slot.diagram.left_dim",
                    "slot.diagram.top_dim",
                    "slot.diagram.bottom_dim",
                    "slot.diagram.top_arc",
                    "slot.diagram.left_arc",
                    "slot.diagram.bottom_arc",
                    "slot.diagram.overlap1_guide",
                    "slot.diagram.overlap2_guide",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="긴 변이 12 cm, 짧은 변이 3 cm인 직사각형",
                style_role="question",
                x=24.0,
                y=40.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="모양의 종이테이프 3장을 2 cm씩 겹치게 이",
                style_role="question",
                x=24.0,
                y=100.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="어 붙여서 직사각형을 만들었습니다. 만든 직",
                style_role="question",
                x=24.0,
                y=160.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="사각형의 네 변의 길이의 합은 몇 cm입니까?",
                style_role="question",
                x=24.0,
                y=220.0,
                font_size=35,
            ),
            RectSlot(
                id="slot.diagram.base1",
                prompt="",
                x=100.0,
                y=400.0,
                width=240.0,
                height=60.0,
                stroke="#3A3A3A",
                stroke_width=2.0,
                fill="#E9EAED",
            ),
            RectSlot(
                id="slot.diagram.base2",
                prompt="",
                x=300.0,
                y=400.0,
                width=240.0,
                height=60.0,
                stroke="#3A3A3A",
                stroke_width=2.0,
                fill="#E9EAED",
            ),
            RectSlot(
                id="slot.diagram.base3",
                prompt="",
                x=500.0,
                y=400.0,
                width=240.0,
                height=60.0,
                stroke="#3A3A3A",
                stroke_width=2.0,
                fill="#E9EAED",
            ),
            RectSlot(
                id="slot.diagram.overlap1",
                prompt="",
                x=300.0,
                y=400.0,
                width=40.0,
                height=60.0,
                stroke="#3A3A3A",
                stroke_width=2.0,
                fill="#C2C4C8",
            ),
            RectSlot(
                id="slot.diagram.overlap2",
                prompt="",
                x=500.0,
                y=400.0,
                width=40.0,
                height=60.0,
                stroke="#3A3A3A",
                stroke_width=2.0,
                fill="#C2C4C8",
            ),
            TextSlot(
                id="slot.diagram.left_dim",
                prompt="",
                text="3 cm",
                style_role="label",
                x=15.0,
                y=430.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.diagram.top_dim",
                prompt="",
                text="12 cm",
                style_role="label",
                x=190.0,
                y=340.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.diagram.bottom_dim",
                prompt="",
                text="2 cm",
                style_role="label",
                x=300.0,
                y=530.0,
                font_size=35,
            ),
            PathSlot(
                id="slot.diagram.top_arc",
                prompt="",
                d="M 100 395 Q 220 330 340 395",
                stroke="#3A3A3A",
                stroke_width=1.5,
                stroke_dasharray="7 5",
                fill="none",
            ),
            PathSlot(
                id="slot.diagram.left_arc",
                prompt="",
                d="M 95 400 Q 60 430 95 460",
                stroke="#3A3A3A",
                stroke_width=1.5,
                stroke_dasharray="7 5",
                fill="none",
            ),
            PathSlot(
                id="slot.diagram.bottom_arc",
                prompt="",
                d="M 300 465 Q 320 500 340 465",
                stroke="#3A3A3A",
                stroke_width=1.5,
                stroke_dasharray="7 5",
                fill="none",
            ),
            LineSlot(
                id="slot.diagram.overlap1_guide",
                prompt="",
                x1=300.0,
                y1=460.0,
                x2=300.0,
                y2=475.0,
                stroke="#3A3A3A",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.diagram.overlap2_guide",
                prompt="",
                x1=340.0,
                y1=460.0,
                x2=340.0,
                y2=475.0,
                stroke="#3A3A3A",
                stroke_width=1.2,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_riUadxZCRr",
    "problem_type": "geometry_perimeter",
    "metadata": {
        "language": "ko",
        "question": "긴 변이 12 cm, 짧은 변이 3 cm인 직사각형 모양의 종이테이프 3장을 2 cm씩 겹치게 이어 붙여서 만든 직사각형의 네 변의 길이의 합은 몇 cm입니까?",
        "instruction": "겹치게 이어 붙인 직사각형의 전체 가로 길이와 세로 길이를 구해 둘레를 계산한다.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.tape",
                "type": "rectangle",
                "length": 12,
                "width": 3,
                "count": 3,
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.tape"],
                "target_ref": "answer.target",
            },
            "plan": {
                "method": "composite_rectangle_perimeter",
                "description": "전체 가로 길이는 (테이프 길이 * 3) - (겹친 길이 * 2)이다.",
            },
            "execute": {
                "expected_operations": [
                    "calculate_total_length",
                    "calculate_perimeter",
                ]
            },
            "review": {"check_methods": ["stepwise_verification"]},
        },
    },
    "answer": {
        "target": {
            "type": "length",
            "description": "만든 직사각형의 둘레",
        },
        "value": 70,
        "unit": "cm",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "Hpdf_riUadxZCRr",
    "problem_type": "geometry_perimeter",
    "inputs": {
        "total_ticks": 0,
        "target_label": "직사각형의 둘레",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "cm",
    },
    "given": [{"ref": "obj.tape", "value": "12 cm, 3 cm, 3장, 겹침 2 cm"}],
    "target": {"ref": "answer.target", "type": "length"},
    "method": "composite_rectangle_perimeter",
    "plan": [
        "1. 전체 가로 길이를 구한다: (12 * 3) - (2 * 2) = 36 - 4 = 32 cm.",
        "2. 세로 길이는 테이프의 짧은 변과 같으므로 3 cm이다.",
        "3. 직사각형의 둘레를 구한다: (32 + 3) * 2 = 35 * 2 = 70 cm.",
    ],
    "steps": [
        {
            "id": "step.1",
            "operation": "subtract",
            "expr": "12 * 3 - 2 * 2",
            "value": 32,
        },
        {
            "id": "step.2",
            "operation": "multiply",
            "expr": "(32 + 3) * 2",
            "value": 70,
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "type": "unit_consistency_check",
            "expr": "단위가 모두 cm인지 확인",
            "expected": 1,
            "actual": 1,
            "pass": True,
        }
    ],
    "answer": {"value": 70, "unit": "cm", "derived_from": "step.2"},
}
