from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_SDP0DWXI3l",
        title="직사각형 개수",
        canvas=Canvas(width=896, height=663, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2", "slot.q3", "slot.q4"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.fig.v1",
                    "slot.fig.v2",
                    "slot.fig.v3",
                    "slot.fig.v4",
                    "slot.fig.h1",
                    "slot.fig.h2",
                    "slot.fig.h3",
                    "slot.fig.h4",
                    "slot.star_text",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="다음 도형은 직사각형 7개를 겹치지 않게 이어",
                style_role="question",
                x=18.0,
                y=40.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="붙여서 만든 것입니다. 찾을 수 있는 크고 작은",
                style_role="question",
                x=18.0,
                y=95.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="직사각형 중에서 ★ 모양을 포함한 직사각형은",
                style_role="question",
                x=18.0,
                y=150.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="모두 몇 개입니까?",
                style_role="question",
                x=18.0,
                y=205.0,
                font_size=35,
            ),
            LineSlot(
                id="slot.fig.v1",
                prompt="",
                x1=250.0,
                y1=444.0,
                x2=250.0,
                y2=632.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.v2",
                prompt="",
                x1=390.0,
                y1=350.0,
                x2=390.0,
                y2=632.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.v3",
                prompt="",
                x1=530.0,
                y1=350.0,
                x2=530.0,
                y2=632.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.v4",
                prompt="",
                x1=670.0,
                y1=350.0,
                x2=670.0,
                y2=538.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.h1",
                prompt="",
                x1=390.0,
                y1=350.0,
                x2=670.0,
                y2=350.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.h2",
                prompt="",
                x1=250.0,
                y1=444.0,
                x2=670.0,
                y2=444.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.h3",
                prompt="",
                x1=250.0,
                y1=538.0,
                x2=670.0,
                y2=538.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            LineSlot(
                id="slot.fig.h4",
                prompt="",
                x1=250.0,
                y1=632.0,
                x2=530.0,
                y2=632.0,
                stroke="#222222",
                stroke_width=2.5,
            ),
            TextSlot(
                id="slot.star_text",
                prompt="",
                text="★",
                style_role="label",
                x=460.0,
                y=491.0,
                font_size=40,
                anchor="middle",
                fill="#222222",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_SDP0DWXI3l",
    "problem_type": "geometry_rectangle_counting",
    "metadata": {
        "language": "ko",
        "question": "다음 도형은 직사각형 7개를 겹치지 않게 이어 붙여서 만든 것입니다. 찾을 수 있는 크고 작은 직사각형 중에서 ★ 모양을 포함한 직사각형은 모두 몇 개입니까?",
        "instruction": "특정 칸을 포함하는 직사각형의 개수를 체계적으로 센다.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.figure",
                "type": "composite_rectangle",
                "description": "7개의 작은 직사각형으로 구성된 도형",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.figure"],
                "target_ref": "answer.target",
            },
            "plan": {
                "method": "systematic_enumeration",
                "description": "★를 포함하는 직사각형을 높이별로 분류하여 센다.",
            },
            "execute": {
                "expected_operations": [
                    "count_height_1",
                    "count_height_2",
                    "count_height_3",
                ]
            },
            "review": {"check_methods": ["recounting"]},
        },
    },
    "answer": {
        "target": {"type": "count", "description": "★ 모양을 포함한 직사각형의 개수"},
        "value": 9,
        "unit": "개",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "Hpdf_SDP0DWXI3l",
    "problem_type": "geometry_rectangle_counting",
    "inputs": {
        "total_ticks": 0,
        "target_label": "직사각형의 개수",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "개",
    },
    "given": [{"ref": "obj.figure", "value": "7개 조각 도형"}],
    "target": {"ref": "answer.target", "type": "count"},
    "method": "systematic_enumeration",
    "plan": [
        "★를 포함하는 직사각형을 높이별로 나눈다.",
        "높이 1: ★가 있는 줄에서 좌우로 확장하면 4개 (1x1, 1x2(좌), 1x2(우), 1x3)",
        "높이 2: 위쪽 줄과 결합 2개, 아래쪽 줄과 결합 2개",
        "높이 3: 위, 중간, 아래 세 줄을 모두 결합 1개",
        "총합: 4 + 2 + 2 + 1 = 9개",
    ],
    "steps": [
        {"id": "step.1", "operation": "height_1", "expr": "4", "value": 4},
        {"id": "step.2", "operation": "height_2", "expr": "2 + 2", "value": 4},
        {"id": "step.3", "operation": "height_3", "expr": "1", "value": 1},
        {"id": "step.4", "operation": "sum", "expr": "4 + 4 + 1", "value": 9},
    ],
    "checks": [
        {
            "id": "check.1",
            "type": "logic_check",
            "expr": "4 + 4 + 1 = 9",
            "expected": 9,
            "actual": 9,
            "pass": True,
        }
    ],
    "answer": {"value": 9, "unit": "개", "derived_from": "step.4"},
}
