from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_PHt9lD4kUV",
        title="정사각형 모양 조각",
        canvas=Canvas(width=661, height=697, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.q4",
                    "slot.label.first",
                    "slot.label.second",
                    "slot.label.third",
                    "slot.label.fourth",
                    "slot.box.third",
                    "slot.square.first",
                    "slot.square.second.1",
                    "slot.square.second.2",
                    "slot.square.second.3",
                    "slot.square.second.4",
                    "slot.square.fourth.1",
                    "slot.square.fourth.2",
                    "slot.square.fourth.3",
                    "slot.square.fourth.4",
                    "slot.square.fourth.5",
                    "slot.square.fourth.6",
                    "slot.square.fourth.7",
                    "slot.square.fourth.8",
                    "slot.square.fourth.9",
                    "slot.square.fourth.10",
                    "slot.square.fourth.11",
                    "slot.square.fourth.12",
                    "slot.square.fourth.13",
                    "slot.square.fourth.14",
                    "slot.square.fourth.15",
                    "slot.square.fourth.16",
                ),
            ),
        ),
        slots=(

            RectSlot(
                id="slot.box.third",
                prompt="",
                x=31.0,
                y=492.0,
                width=191.0,
                height=188.0,
                stroke="#333333",
                stroke_width=1.2,
                fill="none",
            ),
            RectSlot(
                id="slot.square.first",
                prompt="",
                x=104.0,
                y=339.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.second.1",
                prompt="",
                x=403.0,
                y=341.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.second.2",
                prompt="",
                x=455.0,
                y=341.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.second.3",
                prompt="",
                x=507.0,
                y=341.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.second.4",
                prompt="",
                x=455.0,
                y=289.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.1",
                prompt="",
                x=295.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.2",
                prompt="",
                x=347.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.3",
                prompt="",
                x=399.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.4",
                prompt="",
                x=451.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.5",
                prompt="",
                x=503.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.6",
                prompt="",
                x=555.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.7",
                prompt="",
                x=607.0,
                y=632.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.8",
                prompt="",
                x=347.0,
                y=580.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.9",
                prompt="",
                x=399.0,
                y=580.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.10",
                prompt="",
                x=451.0,
                y=580.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.11",
                prompt="",
                x=503.0,
                y=580.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.12",
                prompt="",
                x=555.0,
                y=580.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.13",
                prompt="",
                x=399.0,
                y=528.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.14",
                prompt="",
                x=451.0,
                y=528.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.15",
                prompt="",
                x=503.0,
                y=528.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            RectSlot(
                id="slot.square.fourth.16",
                prompt="",
                x=451.0,
                y=476.0,
                width=48.0,
                height=48.0,
                stroke="#A8A8A8",
                stroke_width=6.0,
                fill="none",
            ),
            TextSlot(
                id="slot.q1",
                prompt="",
                text="크기가 같은 정사각형 모양 조각을 다음과 같",
                style_role="question",
                x=18.0,
                y=40.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="은 규칙으로 늘어놓았습니다. 셋째에 놓이는",
                style_role="question",
                x=18.0,
                y=100.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="모양에서 찾을 수 있는 크고 작은 직사각형은",
                style_role="question",
                x=18.0,
                y=160.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q4",
                prompt="",
                text="모두 몇 개입니까?",
                style_role="question",
                x=18.0,
                y=220.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.label.first",
                prompt="",
                text="첫째",
                style_role="label",
                x=107.0,
                y=270.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.label.second",
                prompt="",
                text="둘째",
                style_role="label",
                x=449.0,
                y=270.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.label.third",
                prompt="",
                text="셋째",
                style_role="label",
                x=107.0,
                y=460.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.label.fourth",
                prompt="",
                text="넷째",
                style_role="label",
                x=449.0,
                y=460.0,
                font_size=35,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_PHt9lD4kUV",
    "problem_type": "geometry_rectangle_counting",
    "metadata": {
        "language": "ko",
        "question": "크기가 같은 정사각형 모양 조각을 다음과 같은 규칙으로 늘어놓았습니다. 셋째에 놓이는 모양에서 찾을 수 있는 크고 작은 직사각형은 모두 몇 개입니까?",
        "instruction": "규칙을 찾아 셋째 모양을 완성하고, 그 안에서 직사각형의 개수를 센다.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.pattern",
                "type": "pattern_sequence",
                "description": "정사각형 조각의 계단식 배열 규칙",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.pattern"],
                "target_ref": "answer.target",
            },
            "plan": {
                "method": "systematic_counting",
                "description": "넷째 모양이 1, 3, 5, 7개의 정사각형으로 쌓인 4층 탑임을 파악하고 크기별 직사각형을 센다.",
            },
            "execute": {
                "expected_operations": [
                    "determine_fourth_shape",
                    "count_rectangles_by_height",
                ]
            },
            "review": {"check_methods": ["recount"]},
        },
    },
    "answer": {
        "target": {
            "type": "count",
            "description": "넷째 모양에서 찾을 수 있는 크고 작은 직사각형의 개수",
        },
        "value": 80,
        "unit": "개",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "Hpdf_PHt9lD4kUV",
    "problem_type": "geometry_rectangle_counting",
    "inputs": {
        "total_ticks": 0,
        "target_label": "직사각형의 개수",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "개",
    },
    "given": [{"ref": "obj.pattern", "value": "1-3-5-7 층 쌓기"}],
    "target": {"ref": "answer.target", "type": "count"},
    "method": "systematic_counting",
    "plan": [
        "넷째 모양은 위에서부터 1개, 3개, 5개, 7개의 정사각형이 중앙 정렬로 쌓인 모양이다.",
        "높이가 1인 직사각형: 1 + 6 + 15 + 28 = 50개",
        "높이가 2인 직사각형: 1 + 6 + 15 = 22개",
        "높이가 3인 직사각형: 1 + 6 = 7개",
        "높이가 4인 직사각형: 1개",
        "총합: 50 + 22 + 7 + 1 = 80개",
    ],
    "steps": [
        {
            "id": "step.1",
            "operation": "count_height_1",
            "expr": "1 + 6 + 15 + 28",
            "value": 50,
        },
        {
            "id": "step.2",
            "operation": "count_height_2",
            "expr": "1 + 6 + 15",
            "value": 22,
        },
        {
            "id": "step.3",
            "operation": "count_height_3",
            "expr": "1 + 6",
            "value": 7,
        },
        {
            "id": "step.4",
            "operation": "count_height_4",
            "expr": "1",
            "value": 1,
        },
        {
            "id": "step.5",
            "operation": "sum",
            "expr": "50 + 22 + 7 + 1",
            "value": 80,
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "type": "logic_check",
            "expr": "50 + 22 + 7 + 1 = 80",
            "expected": 80,
            "actual": 80,
            "pass": True,
        }
    ],
    "answer": {"value": 80, "unit": "개", "derived_from": "step.5"},
}
