from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="Hpdf_PhzLdbr6qh",
        title="각의 개수",
        canvas=Canvas(width=920, height=544, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.grid.border",
                    "slot.grid.v1",
                    "slot.grid.v2",
                    "slot.grid.v3",
                    "slot.grid.v4",
                    "slot.grid.v5",
                    "slot.grid.v6",
                    "slot.grid.v7",
                    "slot.grid.v8",
                    "slot.grid.h1",
                    "slot.grid.h2",
                    "slot.grid.h3",
                    "slot.grid.h4",
                    "slot.grid.h5",
                    "slot.grid.h6",
                    "slot.pt.1",
                    "slot.pt.2",
                    "slot.pt.3",
                    "slot.pt.4",
                    "slot.lb.1",
                    "slot.lb.2",
                    "slot.lb.3",
                    "slot.lb.4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="4개의 점 중에서 3개의 점을 반직선으로 이여",
                style_role="question",
                x=12.0,
                y=40.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="서 그릴 수 있는 각은 모두 몇 개입니까?",
                style_role="question",
                x=12.0,
                y=100.0,
                font_size=35,
            ),
            RectSlot(
                id="slot.grid.border",
                prompt="",
                x=223.0,
                y=200.0,
                width=472.0,
                height=328.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                fill="none",
            ),
            LineSlot(
                id="slot.grid.v1",
                prompt="",
                x1=282.0,
                y1=200.0,
                x2=282.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v2",
                prompt="",
                x1=341.0,
                y1=200.0,
                x2=341.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v3",
                prompt="",
                x1=400.0,
                y1=200.0,
                x2=400.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v4",
                prompt="",
                x1=459.0,
                y1=200.0,
                x2=459.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v5",
                prompt="",
                x1=518.0,
                y1=200.0,
                x2=518.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v6",
                prompt="",
                x1=577.0,
                y1=200.0,
                x2=577.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v7",
                prompt="",
                x1=636.0,
                y1=200.0,
                x2=636.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.v8",
                prompt="",
                x1=695.0,
                y1=200.0,
                x2=695.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h1",
                prompt="",
                x1=223.0,
                y1=254.7,
                x2=695.0,
                y2=254.7,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h2",
                prompt="",
                x1=223.0,
                y1=309.3,
                x2=695.0,
                y2=309.3,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h3",
                prompt="",
                x1=223.0,
                y1=364.0,
                x2=695.0,
                y2=364.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h4",
                prompt="",
                x1=223.0,
                y1=418.7,
                x2=695.0,
                y2=418.7,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h5",
                prompt="",
                x1=223.0,
                y1=473.3,
                x2=695.0,
                y2=473.3,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            LineSlot(
                id="slot.grid.h6",
                prompt="",
                x1=223.0,
                y1=528.0,
                x2=695.0,
                y2=528.0,
                stroke="#9AA0A6",
                stroke_width=1.2,
                stroke_dasharray="5 3",
            ),
            CircleSlot(
                id="slot.pt.1", prompt="", cx=459.0, cy=254.0, r=5.0, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.2", prompt="", cx=282.0, cy=364.0, r=5.0, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.3", prompt="", cx=459.0, cy=473.0, r=5.0, fill="#222222"
            ),
            CircleSlot(
                id="slot.pt.4", prompt="", cx=518.0, cy=473.0, r=5.0, fill="#222222"
            ),
            TextSlot(
                id="slot.lb.1",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=446.0,
                y=230.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.lb.2",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=230.0,
                y=360.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.lb.3",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=445.0,
                y=505.0,
                font_size=35,
            ),
            TextSlot(
                id="slot.lb.4",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=515.0,
                y=505.0,
                font_size=35,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("도형", "각", "점"),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "Hpdf_PhzLdbr6qh",
    "problem_type": "geometry_angle_counting",
    "metadata": {
        "language": "ko",
        "question": "4개의 점 중에서 3개의 점을 반직선으로 이어서 그릴 수 있는 각은 모두 몇 개입니까?",
        "instruction": "주어진 점들로 만들 수 있는 모든 각의 가짓수를 구한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.points", "type": "point_set", "count": 4},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.points"],
                "target_ref": "answer.target",
            },
            "plan": {
                "method": "combinatorial_counting",
                "description": "한 점을 꼭짓점으로 하고 나머지 점들 중 두 점을 이어 각을 만드는 경우의 수를 계산한다.",
            },
            "execute": {
                "expected_operations": [
                    "choose_vertex",
                    "choose_rays",
                ]
            },
            "review": {"check_methods": ["enumeration"]},
        },
    },
    "answer": {
        "target": {"type": "count", "description": "만들 수 있는 각의 개수"},
        "value": 12,
        "unit": "개",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1",
    "problem_id": "Hpdf_PhzLdbr6qh",
    "problem_type": "geometry_angle_counting",
    "inputs": {
        "total_ticks": 0,
        "target_label": "각의 개수",
        "target_ticks": 0,
        "target_count": 0,
        "unit": "개",
    },
    "given": [{"ref": "obj.points", "value": 4}],
    "target": {"ref": "answer.target", "type": "count"},
    "method": "combinatorial_counting",
    "plan": [
        "1. 한 점을 꼭짓점으로 정한다. (4가지 선택 가능)",
        "2. 선택한 꼭짓점에서 나머지 3개의 점 중 2개를 골라 각을 만든다. (3C2 = 3가지 가능)",
        "3. 따라서 총 각의 개수는 4 * 3 = 12개이다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "operation": "multiply",
            "expr": "4 * 3",
            "value": 12,
        }
    ],
    "checks": [
        {
            "id": "check.1",
            "type": "logic_check",
            "expr": "4 * 3 = 12",
            "expected": 12,
            "actual": 12,
            "pass": True,
        }
    ],
    "answer": {"value": 12, "unit": "개", "derived_from": "step.1"},
}
