from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    Region,
    TextSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="2406",
        title="그림에서 x의 값을 구하시오.",
        canvas=Canvas(width=1400, height=900, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.problem_text",
                    "slot.geom.base_line",
                    "slot.geom.base_line_start_ah_l",
                    "slot.geom.base_line_start_ah_r",
                    "slot.geom.left_up_ray",
                    "slot.geom.left_up_ray_end_ah_l",
                    "slot.geom.left_up_ray_end_ah_r",
                    "slot.geom.left_down_seg",
                    "slot.geom.upper_ray",
                    "slot.geom.upper_ray_end_ah_l",
                    "slot.geom.upper_ray_end_ah_r",
                    "slot.geom.diag_ray",
                    "slot.geom.diag_ray_end_ah_l",
                    "slot.geom.diag_ray_end_ah_r",
                    "slot.geom.upper_to_c",
                    "slot.pt.B",
                    "slot.pt.C",
                    "slot.pt.D",
                    "slot.pt.E",
                    "slot.pt.I",
                    "slot.lb.79",
                    "slot.lb.xm1",
                    "slot.lb.xp10",
                    "slot.lb.2x",
                ),
            ),
            Region(
                id="region.choices",
                role="choices",
                flow="absolute",
                slot_ids=("slot.choices.ln1", "slot.choices.ln2"),
            ),
            Region(
                id="region.answer_overlay",
                role="overlay",
                flow="absolute",
                slot_ids=("slot.answer_overlay",),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.problem_text",
                prompt="",
                text="그림에서 x의 값을 구하시오.",
                style_role="question",
                x=40.0,
                y=70.0,
                font_size=48,
            ),
            LineSlot(
                id="slot.geom.base_line",
                prompt="",
                x1=170.0,
                y1=610.0,
                x2=1120.0,
                y2=610.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.geom.base_line_start_ah_l",
                prompt="",
                x1=170.0,
                y1=610.0,
                x2=194.0,
                y2=603.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.base_line_start_ah_r",
                prompt="",
                x1=170.0,
                y1=610.0,
                x2=194.0,
                y2=617.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.left_up_ray",
                prompt="",
                x1=360.0,
                y1=420.0,
                x2=250.0,
                y2=180.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.geom.left_up_ray_end_ah_l",
                prompt="",
                x1=250.0,
                y1=180.0,
                x2=266.4,
                y2=198.9,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.left_up_ray_end_ah_r",
                prompt="",
                x1=250.0,
                y1=180.0,
                x2=253.6,
                y2=204.7,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.left_down_seg",
                prompt="",
                x1=360.0,
                y1=420.0,
                x2=430.0,
                y2=610.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.geom.upper_ray",
                prompt="",
                x1=359.9,
                y1=420.1,
                x2=783.4,
                y2=222.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.geom.upper_ray_end_ah_l",
                prompt="",
                x1=783.4,
                y1=222.0,
                x2=764.6,
                y2=238.5,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.upper_ray_end_ah_r",
                prompt="",
                x1=783.4,
                y1=222.0,
                x2=758.6,
                y2=225.9,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.diag_ray",
                prompt="",
                x1=620.0,
                y1=300.0,
                x2=1086.3,
                y2=768.2,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_edge",
            ),
            LineSlot(
                id="slot.geom.diag_ray_end_ah_l",
                prompt="",
                x1=1086.3,
                y1=768.2,
                x2=1064.4,
                y2=756.1,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.diag_ray_end_ah_r",
                prompt="",
                x1=1086.3,
                y1=768.2,
                x2=1074.3,
                y2=746.3,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_arrow_head",
            ),
            LineSlot(
                id="slot.geom.upper_to_c",
                prompt="",
                x1=360.0,
                y1=420.0,
                x2=620.0,
                y2=300.0,
                stroke="#0B72B9",
                stroke_width=5.2,
                semantic_role="geometry_edge",
            ),
            CircleSlot(
                id="slot.pt.B",
                prompt="",
                cx=430.0,
                cy=610.0,
                r=4.6,
                stroke="#0B3A5E",
                stroke_width=1.4,
                fill="#0B3A5E",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.C",
                prompt="",
                cx=620.0,
                cy=300.0,
                r=4.6,
                stroke="#0B3A5E",
                stroke_width=1.4,
                fill="#0B3A5E",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.D",
                prompt="",
                cx=360.0,
                cy=420.0,
                r=4.6,
                stroke="#0B3A5E",
                stroke_width=1.4,
                fill="#0B3A5E",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.E",
                prompt="",
                cx=250.0,
                cy=180.0,
                r=4.6,
                stroke="#0B3A5E",
                stroke_width=1.4,
                fill="#0B3A5E",
                semantic_role="geometry_point",
            ),
            CircleSlot(
                id="slot.pt.I",
                prompt="",
                cx=930.0,
                cy=610.0,
                r=4.6,
                stroke="#0B3A5E",
                stroke_width=1.4,
                fill="#0B3A5E",
                semantic_role="geometry_point",
            ),
            TextSlot(
                id="slot.lb.79",
                prompt="",
                text="79°",
                style_role="label",
                x=359.4,
                y=363.1,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.xm1",
                prompt="",
                text="(x−1)°",
                style_role="label",
                x=263.9,
                y=574.9,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.xp10",
                prompt="",
                text="(x+10)°",
                style_role="label",
                x=700.0,
                y=320.0,
                font_size=48,
            ),
            TextSlot(
                id="slot.lb.2x",
                prompt="",
                text="2x°",
                style_role="label",
                x=870.9,
                y=666.4,
                font_size=48,
            ),
            TextSlot(
                id="slot.choices.ln1",
                prompt="",
                text="1. 68 / 2. 78 / 3. 79 / 4. 136",
                style_role="choice",
                x=40.0,
                y=800.0,
                font_size=48,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '2406',
 'problem_type': 'geometry_angle',
 'metadata': {'title': '그림에서 x의 값을 구하시오.',
              'tags': [],
              'instruction': '그림에서 x의 값을 구하시오.',
              'question': '그림에서 x의 값을 구하시오.',
              'required_layout_ids': ['slot.geom.base_line',
                                      'slot.geom.base_line_start_ah_l',
                                      'slot.geom.base_line_start_ah_r',
                                      'slot.geom.left_up_ray',
                                      'slot.geom.left_up_ray_end_ah_l',
                                      'slot.geom.left_up_ray_end_ah_r',
                                      'slot.geom.left_down_seg',
                                      'slot.geom.upper_ray',
                                      'slot.geom.upper_ray_end_ah_l',
                                      'slot.geom.upper_ray_end_ah_r',
                                      'slot.geom.diag_ray',
                                      'slot.geom.diag_ray_end_ah_l',
                                      'slot.geom.diag_ray_end_ah_r',
                                      'slot.geom.upper_to_c',
                                      'slot.pt.B',
                                      'slot.pt.C',
                                      'slot.pt.D',
                                      'slot.pt.E',
                                      'slot.pt.I'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.point.B', 'type': 'point', 'label': 'B'},
                        {'id': 'obj.point.C', 'type': 'point', 'label': 'C'},
                        {'id': 'obj.point.D', 'type': 'point', 'label': 'D'},
                        {'id': 'obj.point.E', 'type': 'point', 'label': 'E'},
                        {'id': 'obj.point.I', 'type': 'point', 'label': 'I'},
                        {'id': 'obj.angle.79', 'type': 'angle_measure', 'expression': '79°'},
                        {'id': 'obj.angle.xm1', 'type': 'angle_measure', 'expression': '(x−1)°'},
                        {'id': 'obj.angle.xp10', 'type': 'angle_measure', 'expression': '(x+10)°'},
                        {'id': 'obj.angle.2x', 'type': 'angle_measure', 'expression': '2x°'},
                        {'id': 'obj.choices',
                         'type': 'multiple_choice',
                         'choices': ['68', '78', '79', '136']}],
            'relations': [{'id': 'rel.angle_labels_attached',
                           'type': 'angle_label_relation',
                           'from_id': 'obj.point.D',
                           'to_id': 'obj.angle.79'}],
            'confidence': 1.0,
            'problem_solving': {'understand': {'given_refs': ['obj.angle.79',
                                                              'obj.angle.xm1',
                                                              'obj.angle.xp10',
                                                              'obj.angle.2x',
                                                              'obj.choices'],
                                               'target_ref': 'answer.target',
                                               'condition_refs': ['rel.angle_labels_attached']},
                                'plan': {'method': 'angle_relationship_in_diagram',
                                         'description': '도형에서 표시된 각도들의 관계를 읽어 x에 대한 식을 세운다.'},
                                'execute': {'expected_operations': ['identify_angle_relations',
                                                                    'form_equation_from_diagram',
                                                                    'solve_for_x']},
                                'review': {'check_methods': ['verify_choice_match',
                                                             'confirm_angle_consistency']}}},
 'answer': {'blanks': [],
            'choices': [{'index': 1, 'text': '1. 68', 'value': '68'},
                        {'index': 2, 'text': '2. 78', 'value': '78'},
                        {'index': 3, 'text': '3. 79', 'value': '79'},
                        {'index': 4, 'text': '4. 136', 'value': '136'}],
            'answer_key': [1],
            'confidence': 1.0,
            'target': {'type': 'value_of_x', 'description': '그림에서 x의 값'},
            'value': 68,
            'unit': ''}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '2406',
 'problem_type': 'geometry_angle',
 'inputs': {'total_ticks': 1,
            'target_label': 'x',
            'target_ticks': 1,
            'target_count': 1,
            'unit': ''},
 'given': [{'ref': 'obj.angle.79', 'value': '79°'},
           {'ref': 'obj.angle.xm1', 'value': '(x−1)°'},
           {'ref': 'obj.angle.xp10', 'value': '(x+10)°'},
           {'ref': 'obj.angle.2x', 'value': '2x°'}],
 'target': {'ref': 'answer.target', 'type': 'value_of_x'},
 'method': 'angle_relationship_in_diagram',
 'plan': ['도형에 표시된 각도 라벨을 확인한다.', '각도 관계식을 세울 수 있으면 x를 구한다.', '선택지와 일치하는지 확인한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_visible_labels',
            'expr': '79°, (x−1)°, (x+10)°, 2x°',
            'value': 4}],
 'checks': [{'id': 'check.1',
             'type': 'choice_consistency',
             'expr': '선택지 1, 2, 3, 4 중 하나와 일치하는지 확인',
             'expected': 68,
             'actual': 68,
             'pass': True}],
 'answer': {'value': 68, 'unit': '', 'derived_from': 'choice.1'}}
