from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, ProblemTemplate, RectSlot, Region, TextSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008729",
        title="그림을 보고 알맞은 말을 선택하세요.",
        canvas=Canvas(width=840, height=300, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.title",
                    "slot.math.fraction.num",
                    "slot.math.fraction.bar",
                    "slot.math.fraction.den",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.card",
                    "slot.bead.1",
                    "slot.bead.2",
                    "slot.bead.3",
                    "slot.bead.4",
                    "slot.bead.5",
                    "slot.bead.6",
                    "slot.bead.7",
                    "slot.bead.8",
                    "slot.bead.9",
                    "slot.bead.10",
                    "slot.bead.11",
                    "slot.bead.12",
                ),
            ),
            Region(
                id="region.question",
                role="stem",
                flow="absolute",
                slot_ids=("slot.stem", "slot.stem.copy1"),
            ),
            Region(id="region.footer", role="note", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.title",
                prompt="",
                text="그림을 보고 알맞은 말을 선택하세요.",
                style_role="question",
                x=80.0,
                y=28.0,
                font_size=28,
            ),
            RectSlot(
                id="slot.card",
                prompt="",
                x=85,
                y=65,
                width=615,
                height=80,
                rx=12,
                ry=12,
                fill="none",
                stroke="#ffa4c0",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.1",
                prompt="",
                cx=125,
                cy=107,
                r=18,
                fill="#43c16f",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.2",
                prompt="",
                cx=173,
                cy=107,
                r=18,
                fill="#43c16f",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.3",
                prompt="",
                cx=221,
                cy=107,
                r=18,
                fill="#43c16f",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.4",
                prompt="",
                cx=269,
                cy=107,
                r=18,
                fill="#43c16f",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.5",
                prompt="",
                cx=317,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.6",
                prompt="",
                cx=365,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.7",
                prompt="",
                cx=413,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.8",
                prompt="",
                cx=461,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.9",
                prompt="",
                cx=509,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.10",
                prompt="",
                cx=557,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.11",
                prompt="",
                cx=605,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.bead.12",
                prompt="",
                cx=653,
                cy=107,
                r=18,
                fill="#f7a8b4",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.stem",
                prompt="",
                text="12의",
                style_role="question",
                x=110,
                y=215,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.math.fraction.num",
                prompt="",
                text="1",
                x=((420) + (-270.0)) + (50.0),
                y=((135) + (125.0)) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            LineSlot(
                id="slot.math.fraction.bar",
                prompt="",
                x1=((400) + (-270.0)) + (50.0),
                y1=((150) + (125.0)) + (-70.0),
                x2=((440) + (-270.0)) + (50.0),
                y2=((150) + (125.0)) + (-70.0),
                stroke="#222222",
                stroke_width=2.2,
            ),
            TextSlot(
                id="slot.math.fraction.den",
                prompt="",
                text="3",
                x=((420) + (-270.0)) + (50.0),
                y=((175) + (125.0)) + (-70.0),
                font_size=30,
                anchor="middle",
                style_role="body",
                fill="#222222",
            ),
            TextSlot(
                id="slot.stem.copy1",
                prompt="",
                text="은 (초록색, 분홍색) 구슬입니다.",
                x=235,
                y=215,
                font_size=28,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008729",
    "problem_type": "fraction_meaning_selection",
    "metadata": {
        "language": "ko",
        "question": "그림을 보고 알맞은 말을 선택하세요.",
        "instruction": "12의 1/3이 무엇인지 그림과 문장을 보고 알맞게 고르는 문제",
    },
    "domain": {
        "objects": [
            {"id": "obj.total", "type": "quantity", "description": "전체 12"},
            {"id": "obj.third", "type": "fraction", "description": "1/3"},
            {"id": "obj.bead_group", "type": "group", "description": "색이 다른 구슬 묶음"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.total", "obj.third", "obj.bead_group"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.fraction_of_total"],
            },
            "plan": {
                "method": "fraction_meaning_matching",
                "description": "1/3이 뜻하는 부분이 그림에서 어떤 색 구슬 묶음인지 문장과 그림을 대응해 본다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_fraction_meaning",
                    "match_picture_group",
                    "select_color_word",
                ]
            },
            "review": {
                "check_methods": [
                    "meaning_matches_picture",
                    "selected_word_is_printed_answer",
                ]
            },
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "color_word", "description": "12의 1/3에 해당하는 구슬의 색 이름"},
        "value": "초록색",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008729",
    "problem_type": "fraction_meaning_selection",
    "inputs": {
        "total_ticks": 12,
        "target_label": "1/3",
        "target_ticks": 1,
        "target_count": 3,
        "unit": "",
    },
    "given": [{"ref": "obj.total", "value": 12}, {"ref": "obj.third", "value": "1/3"}],
    "target": {"ref": "answer.target", "type": "color_word"},
    "method": "fraction_meaning_matching",
    "plan": ["12을 3묶음으로 똑같이 나눈다.", "그중 1묶음이 무엇인지 그림의 색과 대응시킨다."],
    "steps": [
        {"id": "step.1", "expr": "12를 3묶음으로 나눈 의미를 확인한다.", "value": 0},
        {"id": "step.2", "expr": "그림에서 1묶음에 해당하는 색 이름을 찾는다.", "value": "초록색"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "1/3은 전체를 3으로 똑같이 나눈 것 중 1묶음인가?",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "그림의 해당 묶음 색이 초록색인가?",
            "expected": "초록색",
            "actual": "초록색",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "color_word", "description": "12의 1/3에 해당하는 구슬의 색 이름"},
        "value": "초록색",
        "unit": "",
    },
}
