from __future__ import annotations

from modu_math.dsl import Canvas, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008553",
        title="색칠된 부분은 실제 어떤 수의 곱인지 찾아 기호를 선택해 보세요.",
        canvas=Canvas(width=900, height=420, coordinate_mode="logical"),
        regions=(
            Region(id="region.stem", role="stem", flow="absolute", slot_ids=("slot.q.text")),
            Region(id="region.work", role="diagram", flow="absolute", slot_ids=()),
            Region(id="region.choices", role="choices", flow="absolute", slot_ids=()),
            Region(id="region.footer", role="footer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q.text",
                prompt="",
                text="색칠된 부분은 실제 어떤 수의 곱인지 찾아 기호를 선택해 보세요.",
                style_role="question",
                x=36.005,
                y=58,
                font_size=32,
                fill="#111111",
            ),
            TextSlot(
                id="slot.top.d0",
                prompt="",
                text="5 7 4",
                style_role="diagram",
                x=329.005,
                y=134,
                font_size=36,
                fill="#111111",
            ),
            TextSlot(
                id="slot.mul.sign",
                prompt="",
                text="×",
                style_role="diagram",
                x=288.005,
                y=175,
                font_size=36,
                fill="#111111",
            ),
            TextSlot(
                id="slot.mul.d0",
                prompt="",
                text="3",
                style_role="diagram",
                x=388.005,
                y=175,
                font_size=36,
                fill="#111111",
            ),
            LineSlot(
                id="slot.bar.1",
                prompt="",
                x1=289.005,
                y1=189,
                x2=409.005,
                y2=189,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.part0.d0",
                prompt="",
                text="1 2",
                style_role="diagram",
                x=354.005,
                y=229,
                font_size=36,
                fill="#111111",
            ),
            RectSlot(
                id="slot.highlight",
                prompt="",
                x=314.005,
                y=234,
                width=100,
                height=50,
                fill="#d9ddb7",
                stroke="#111111",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.part1.d0",
                prompt="",
                text="2 1 0",
                style_role="diagram",
                x=324.005,
                y=274,
                font_size=36,
                fill="#111111",
            ),
            TextSlot(
                id="slot.part2.d0",
                prompt="",
                text="1 5 0 0",
                style_role="diagram",
                x=294.005,
                y=319,
                font_size=36,
                fill="#111111",
            ),
            LineSlot(
                id="slot.bar.2",
                prompt="",
                x1=284.005,
                y1=329,
                x2=406.005,
                y2=329,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.final.d0",
                prompt="",
                text="1 7 2 2",
                style_role="diagram",
                x=294.005,
                y=369,
                font_size=36,
                fill="#111111",
            ),
            RectSlot(
                id="slot.choice.box",
                prompt="",
                x=524.005,
                y=106,
                width=214,
                height=252,
                fill="none",
                stroke="#111111",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="㉠ 7 × 3",
                style_role="choice",
                x=534.005,
                y=171,
                font_size=36,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="㉡ 7 × 30",
                style_role="choice",
                x=534.005,
                y=215,
                font_size=36,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="㉢ 70 × 3",
                style_role="choice",
                x=534.005,
                y=259,
                font_size=36,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="㉣ 700 × 3",
                style_role="choice",
                x=534.005,
                y=303,
                font_size=36,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=("초등", "수학", "곱셈", "세로셈", "자리값"),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008553",
    "problem_type": "multiplication_place_value_choice",
    "metadata": {
        "language": "ko",
        "question": "색칠된 부분은 실제 어떤 수의 곱인지 찾아 기호를 선택해 보세요.",
        "instruction": "보기에서 알맞은 식을 고르세요.",
    },
    "domain": {
        "objects": [{"id": "obj.target", "type": "expression", "text": "70 × 3"}],
        "relations": [],
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_expression", "description": "색칠된 부분에 해당하는 식"},
        "value": "㉢ 70 × 3",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008553",
    "problem_type": "multiplication_place_value_choice",
    "inputs": {
        "total_ticks": 0,
        "target_label": "색칠된 부분에 해당하는 식",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [{"ref": "obj.target", "value": "70 × 3"}],
    "target": {"ref": "answer.target", "type": "selected_expression"},
    "method": "place_value_matching",
    "plan": ["세로셈에서 색칠된 210이 어떤 자리값 곱인지 확인한다.", "보기 중 같은 식을 고른다."],
    "steps": [{"id": "step.1", "expr": "색칠된 부분과 보기 비교", "value": "70 × 3"}],
    "checks": [
        {
            "id": "check.1",
            "expr": "선택한 식 검산",
            "expected": "일치",
            "actual": "일치",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_expression", "description": "색칠된 부분에 해당하는 식"},
        "value": "㉢ 70 × 3",
        "unit": "",
    },
}
