from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1498,
        height=644,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.inst', 'slot.r1c1', 'slot.r1c2', 'slot.r2c1', 'slot.r2c2'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.inst',
            prompt='',
            text='빈칸에 알맞은 수를 써 넣으세요.',
            style_role='body',
            x=28.0,
            y=106.44896,
            font_size=72,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='instruction',
        ),
        LineSlot(
            id='slot.arrow_head1',
            prompt='',
            x1=910.18445,
            y1=228.24083,
            x2=880.18445,
            y2=198.24083,
            stroke='#CCCED2',
            stroke_width=22.0,
            semantic_role='flow_arrow',
        ),
        LineSlot(
            id='slot.plus_v',
            prompt='',
            x1=614.18445,
            y1=203.24083,
            x2=614.18445,
            y2=253.24083,
            stroke='#3A3338',
            stroke_width=4.0,
            semantic_role='operator',
        ),
        LineSlot(
            id='slot.arrow',
            prompt='',
            x1=317.18445,
            y1=228.24083,
            x2=910.18445,
            y2=228.24083,
            stroke='#CCCED2',
            stroke_width=22.0,
            semantic_role='flow_arrow',
        ),
        LineSlot(
            id='slot.plus_h',
            prompt='',
            x1=589.18445,
            y1=228.24083,
            x2=639.18445,
            y2=228.24083,
            stroke='#3A3338',
            stroke_width=4.0,
            semantic_role='operator',
        ),
        CircleSlot(
            id='slot.plus_circle',
            prompt='',
            cx=614.18445,
            cy=228.24083,
            r=48.0,
            stroke='#B9D8DA',
            stroke_width=10.0,
            fill='#F6F6F6',
            semantic_role='operator',
        ),
        LineSlot(
            id='slot.arrow_head2',
            prompt='',
            x1=910.18445,
            y1=228.24083,
            x2=880.18445,
            y2=258.24084,
            stroke='#CCCED2',
            stroke_width=22.0,
            semantic_role='flow_arrow',
        ),
        RectSlot(
            id='slot.table',
            prompt='',
            x=319.18445,
            y=298.24084,
            width=888.0,
            height=279.0,
            stroke='#B9D8DA',
            stroke_width=9.0,
            fill='none',
            semantic_role='table',
        ),
        LineSlot(
            id='slot.v1',
            prompt='',
            x1=616.18445,
            y1=298.24084,
            x2=616.18445,
            y2=577.2408399999999,
            stroke='#B9D8DA',
            stroke_width=4.0,
            semantic_role='table_grid',
        ),
        LineSlot(
            id='slot.v2',
            prompt='',
            x1=909.18445,
            y1=298.24084,
            x2=909.18445,
            y2=577.2408399999999,
            stroke='#B9D8DA',
            stroke_width=4.0,
            semantic_role='table_grid',
        ),
        RectSlot(
            id='slot.r1_blank',
            prompt='',
            x=939.18445,
            y=329.24084,
            width=238.0,
            height=78.0,
            stroke='#69BEEA',
            stroke_width=4.0,
            rx=10.0,
            fill='none',
            semantic_role='answer_blank',
        ),
        TextSlot(
            id='slot.r1c1',
            prompt='',
            text='467',
            style_role='body',
            x=468.18445,
            y=392.24084,
            font_size=68,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='table_value',
        ),
        TextSlot(
            id='slot.r1c2',
            prompt='',
            text='359',
            style_role='body',
            x=761.18445,
            y=392.24084,
            font_size=68,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='table_value',
        ),
        LineSlot(
            id='slot.h1',
            prompt='',
            x1=319.18445,
            y1=437.24084,
            x2=1207.18445,
            y2=437.24084,
            stroke='#B9D8DA',
            stroke_width=4.0,
            semantic_role='table_grid',
        ),
        RectSlot(
            id='slot.r2_blank',
            prompt='',
            x=939.18445,
            y=465.24084,
            width=238.0,
            height=78.0,
            stroke='#69BEEA',
            stroke_width=4.0,
            rx=10.0,
            fill='none',
            semantic_role='answer_blank',
        ),
        TextSlot(
            id='slot.r2c1',
            prompt='',
            text='735',
            style_role='body',
            x=468.18445,
            y=528.24084,
            font_size=68,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='table_value',
        ),
        TextSlot(
            id='slot.r2c2',
            prompt='',
            text='418',
            style_role='body',
            x=761.18445,
            y=528.24084,
            font_size=68,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='table_value',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='0010_덧셈 기계',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0010_덧셈 기계',
 'problem_type': 'arithmetic_flow_table_addition',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '빈칸에 알맞은 수를 써 넣으세요.',
              'question': '덧셈 기계(두 수를 더하는 로직)를 통과하는 두 쌍의 수들의 합을 구하는 문제',
              'required_layout_ids': ['slot.arrow_head1',
                                      'slot.plus_v',
                                      'slot.arrow',
                                      'slot.plus_h',
                                      'slot.plus_circle',
                                      'slot.arrow_head2',
                                      'slot.table',
                                      'slot.v1',
                                      'slot.v2',
                                      'slot.r1_blank',
                                      'slot.h1',
                                      'slot.r2_blank'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.row1', 'type': 'input_pair', 'value': [467, 359]},
                        {'id': 'obj.row2', 'type': 'input_pair', 'value': [735, 418]}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'repeated_addition',
                                         'description': '각 행의 두 수를 더하여 결과를 산출한다.'}}},
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'confidence': 1.0,
            'value': 0,
            'unit': '',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0010_덧셈 기계',
 'problem_type': 'arithmetic_flow_table_addition',
 'inputs': {'total_ticks': 1, 'target_label': '', 'target_ticks': 1, 'target_count': 1, 'unit': ''},
 'given': [{'ref': 'obj.row1', 'value': [467, 359]}, {'ref': 'obj.row2', 'value': [735, 418]}],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': [826, 1153],
             'actual': [826, 1153],
             'pass': True}],
 'answer': {'value': 0, 'unit': '', 'derived_from': 'step.1'}}
