from __future__ import annotations

from modu_math.dsl import Arrow, BlankSlot, Canvas, ChoiceSlot, Circle, CircleSlot, Constraint, Cube, DiagramTemplate, FractionAreaModel, Grid, Group, LabelSlot, LineSlot, PathSlot, PolygonSlot, ProblemTemplate, RectSlot, Region, ShapeObject, TextSlot, Triangle

def build_problem_template() -> ProblemTemplate:
    canvas = Canvas(
        width=1852,
        height=554,
        coordinate_mode='logical',
    )
    regions = (
        Region(
            id='region.stem',
            role='stem',
            flow='vertical',
            slot_ids=('slot.instruction',
             'slot.left_expr',
             'slot.right_expr',
             'slot.left_paren_l',
             'slot.left_paren_r',
             'slot.right_paren_l',
             'slot.right_paren_r'),
        ),
    )
    slots = (
        TextSlot(
            id='slot.instruction',
            prompt='',
            text='계산 결과가 더 큰 것에 ○표 하세요.',
            style_role='body',
            x=44.0,
            y=106.0,
            font_size=72,
            font_family='Malgun Gothic',
            anchor='start',
            fill='#222222',
            semantic_role='decorative',
        ),
        RectSlot(
            id='slot.left_box',
            prompt='',
            x=320.0,
            y=180.0,
            width=590.0,
            height=210.0,
            stroke='none',
            stroke_width=0.0,
            rx=75.0,
            fill='#D0CABB',
            semantic_role='choice',
        ),
        RectSlot(
            id='slot.right_box',
            prompt='',
            x=1200.0,
            y=180.0,
            width=590.0,
            height=210.0,
            stroke='none',
            stroke_width=0.0,
            rx=75.0,
            fill='#D0CABB',
            semantic_role='choice',
        ),
        TextSlot(
            id='slot.left_expr',
            prompt='',
            text='605+298',
            style_role='body',
            x=615.0,
            y=294.0,
            font_size=74,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='decorative',
        ),
        TextSlot(
            id='slot.right_expr',
            prompt='',
            text='567+385',
            style_role='body',
            x=1495.0,
            y=294.0,
            font_size=74,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='decorative',
        ),
        TextSlot(
            id='slot.left_paren_l',
            prompt='',
            text='(',
            style_role='body',
            x=500.0,
            y=478.0,
            font_size=92,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='decorative',
        ),
        TextSlot(
            id='slot.left_paren_r',
            prompt='',
            text=')',
            style_role='body',
            x=735.0,
            y=478.0,
            font_size=92,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='decorative',
        ),
        TextSlot(
            id='slot.right_paren_l',
            prompt='',
            text='(',
            style_role='body',
            x=1380.0,
            y=478.0,
            font_size=92,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='decorative',
        ),
        TextSlot(
            id='slot.right_paren_r',
            prompt='',
            text=')',
            style_role='body',
            x=1615.0,
            y=478.0,
            font_size=92,
            font_family='Cambria',
            anchor='middle',
            fill='#222222',
            semantic_role='decorative',
        ),
    )
    diagrams = (
    )
    groups = (
    )
    constraints = (
    )
    return ProblemTemplate(
        id='0005_합의 크기 비교',
        title='',
        canvas=canvas,
        regions=regions,
        slots=slots,
        diagrams=diagrams,
        groups=groups,
        constraints=constraints,
    )

PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {'problem_id': '0005_합의 크기 비교',
 'problem_type': 'arithmetic_comparison_sum',
 'metadata': {'title': '',
              'tags': [],
              'instruction': '계산 결과가 더 큰 것에 ○표 하세요.',
              'question': '두 덧셈식(605+298, 567+385)의 결과를 비교하여 더 큰 쪽을 찾는 문제',
              'required_layout_ids': ['slot.left_box', 'slot.right_box'],
              'extraction_confidence': 1.0,
              'language': 'ko'},
 'domain': {'objects': [{'id': 'obj.expr1', 'type': 'expression', 'value': '605+298'},
                        {'id': 'obj.expr2', 'type': 'expression', 'value': '567+385'}],
            'relations': [],
            'confidence': 1.0,
            'problem_solving': {'plan': {'method': 'direct_calculation_and_comparison',
                                         'description': '각 식을 계산한 뒤 두 결과를 비교한다.'}}},
 'answer': {'blanks': [],
            'choices': [],
            'answer_key': [],
            'confidence': 1.0,
            'value': 0,
            'unit': '',
            'target': {'type': 'unknown', 'description': ''}}}

SOLVABLE = {'schema': 'modu.solvable.v1',
 'problem_id': '0005_합의 크기 비교',
 'problem_type': 'arithmetic_comparison_sum',
 'inputs': {'total_ticks': 1, 'target_label': '', 'target_ticks': 1, 'target_count': 1, 'unit': ''},
 'given': [{'ref': 'obj.expr1', 'value': '605+298'}, {'ref': 'obj.expr2', 'value': '567+385'}],
 'target': {'ref': 'answer.target', 'type': 'unknown'},
 'method': 'read_visible_information',
 'plan': ['주어진 조건을 읽고 목표 값을 계산한다.'],
 'steps': [{'id': 'step.1',
            'operation': 'identify_target',
            'expr': 'identify target from problem',
            'value': 0}],
 'checks': [{'id': 'check.1',
             'expr': 'basic consistency check',
             'expected': '567+385',
             'actual': '567+385',
             'pass': True}],
 'answer': {'value': 0, 'unit': '', 'derived_from': 'step.1'}}
